### ISSUE TITLE
Data bridge skeleton

### ISSUE THREAD

**Issue by bitbager** [DivanteLtd/vue-storefront#1001]
Hello there!

Are you planning to prepare a data bridge extension skeleton? It’s nice to depend on Pimcore or Magento data bridges, but all of them differ a lot from each other and contain code that's redundant for a new bridge integration.

What I mean by a skeleton is a totally new repository, which would contain only what's needed for the 3rd party integration with a nice manual on how to make the data work in VueStorefront.

WDYT?

**Comment by pkarw** [comment]
Good point, however we don't it on our roadmap :( Please take a look at github.com/DivanteLtd/magento1-vsbridge -> node-app.

This is a pretty good example of how the skeleton can look like. The assumption is that API endpoints returns the data in the exact same format as ElasticSearch entities (arrays of JSON)

So in case when we do have API specs for the endpoints  and this skeleton node-app -> it seems like we have it - the data bridge boilerplate

I think I would be able to create the specs for the REST API - but I won't make it to combine it all together.
How about putting it all together @bitbager? Maybe You could do this?

**Comment by bitbager** [comment]
Sure. Once I master it, I think it should be straightforward to publish it 🙂

**Comment by pkarw** [comment]
https://github.com/DivanteLtd/magento1-vsbridge/blob/master/doc/VueStorefrontBridge%20API%20specs.md here You have the docs for the API that should be exposed to have full integration (checkout, shopping carts, user accounts + catalog) with the example on Magento1 (partially implemented yet)

**Comment by pkarw** [comment]
Having such API you need to use:
- node-app - https://github.com/DivanteLtd/magento1-vsbridge/tree/master/node-app - for consuming the endpoints responsible for the catalog (attributes, products, categories, taxrules)
- vue-storefront-api - to proxy the rest of the endpoints (it should be transparent proxy in this case as the VueStorefrontBridgeApi == vue-storefront-api bridge)

**Comment by pkarw** [comment]
TODO: publish it as a boilerplate with separate github repo + write some docs on how to start giving magento1-vsbridge as an example

**Comment by pkarw** [comment]
Consider it done: https://github.com/DivanteLtd/vue-storefront-integration-boilerplate
