### ISSUE TITLE
Testing the app

### ISSUE THREAD

**Issue by bitbager** [DivanteLtd/vue-storefront#1002]
Hi again 🙂 

I did not find any documentation on how to test the app. Although it has some tests, actually the Modal spec was the only one I found, I have no clue on how to run and debug specific parts of the app, especially the ones I'm implementing & customizing in the src.

Do you have any recommended way of testing specific features? Perhaps it would be great to at least describe it in the docs or put some references.

**Comment by filrak** [comment]
Since it is a vue application most of the tests can be done with vue devtools. The sync parts need to be checked in magento directly
