### ISSUE TITLE
ISO language codes and translations

### ISSUE THREAD

**Issue by unherz** [DivanteLtd/vue-storefront#1008]
Hello everyone

atm there are some translations wiht ISO code names like "en-US" or "de-DE". 
**Is there a need or a usecase for a more complete list of translations like "en-AU", "en-GB"?**

On the one hand we are talking about simple translations but on the other hand date formats might change per country + language. Also there are some people with a fixed languagecode in their browser like "en-GB" but no defined fallback.

FYI: my reference is this list [www.lingoes.net/en/translator/langcode.htm](http://www.lingoes.net/en/translator/langcode.htm)

**Comment by pkarw** [comment]
You’re basically right but we’re using the ISO codes for culture selection as you said- because of the general internationalization (currency, date formats). At this stage is just on the roadmap but this was the reason
