### ISSUE TITLE
Progressive Web AMPs

### ISSUE THREAD

**Issue by kyvaith** [DivanteLtd/vue-storefront#1011]
Maybe as a part of next big release, but vue-storefront should defenitly leverage next big approach of integrating AMP with PWA. Please refer to:
https://www.smashingmagazine.com/2016/12/progressive-web-amps/#amp-to-pwa
https://amphtml.wordpress.com/2016/08/22/getting-started-with-amp-for-e-commerce/
https://ampbyexample.com/introduction/amp_for_e-commerce_getting_started/

Example of AMP that installs service worker and become PWA with e-commerce suport by utilising Payment Request API: https://ampbyexample.com/advanced/payments_in_amp/preview/

**Comment by pkarw** [comment]
@filrak @Igloczek guys could I put you in on this?

**Comment by Igloczek** [comment]
I'll just copy paste my answer from Slack :)
"I know it's possible to build "PWAMP", but this product needs a lot of love to be fully functional SPA, then we can think about more and more PWA features and then maybe we should think about AMP.
Stop hyping on cool acronyms, do one thing good and them move forward"

**Comment by alankent** [comment]
Just FYI, I am doing some research on PWA, AMP, and ecommerce. So feel free to drop me a line if you ever get around to this.

**Comment by filrak** [comment]
@pkarw AMP is a great piece of tech especially the newest version with shadow-amp allowing to easly integrate it with any website withou affecting design that much but I think it's more a 'nice to have' than 'must have' before 1.0.

**Comment by pkarw** [comment]
After some research done on the topic -> it makes no sense to combine PWA + AMP due to AMPHTML limitations (by some validation constraints / security rules it's not possible to use dynamic content as JS inside AMPHTML sites)
