### ISSUE TITLE
AWS?

### ISSUE THREAD

**Issue by wsheldon** [DivanteLtd/vue-storefront#1015]
Brilliant project!  Thanks Piotr and others.

At first glance, it seems that AWS Elasticsearch, ElasticCache, DynamoDB, Lambda and CloudFront could be leveraged for those services.  Then wrap it all into a CloudFormation template and distribute.

Has anyone tried this?  I may give it a shot, out of curiosity.

**Comment by pkarw** [comment]
Hi Wilson, thanks! Yes, Your idea sounds like a way to go, it will be marvelous to have a demo showing the VS on cloud 

Could You try to take care of this?

**Comment by wsheldon** [comment]
@pkarw Hi Piotr, yes I will try to work on this in the next few weeks.  It may ultimately be a CloudFormation template but hoping it doesn't require a fork (though that may be necessary).  Thanks!

**Comment by pkarw** [comment]
@wsheldon any progress regarding this issue? :)

**Comment by wsheldon** [comment]
@pkarw Would really like to but haven't had any time yet.  Perhaps in June

**Comment by danieldeicide** [comment]
@wsheldon I am also interested. Can't wait to see it in action.

**Comment by wsheldon** [comment]
Thanks @danieldeicide Ok will do my best to work on it in next few weeks

**Comment by ehartford** [comment]
is it possible to use dynamodb and lambda for backend?  MAybe using endless-commerce?

**Comment by JakubKontra** [comment]
Any progress?

**Comment by ehartford** [comment]
I need to do this in the coming months.  If i come up with anything interesting I will post it here.

**Comment by klapperkopp** [comment]
I am also on this at the moment. I I get something running, will update here. One of the problems I bumped into already is that Amazon requires https on Elasticsearch calls and also some headers, which don't seem to be easily added to the VSF-Api-calls to Elasticsearch...

**Comment by simonmaass** [comment]
hey guys - would also be interested in a status here or contribute... any news here?

**Comment by iamn1ck** [comment]
Since the ssr is running in ts-node, I managed to create an ssr bundle with webpack that runs on lambda. It still needs a few things fixed for everything to work properly, and I there weren't any performance changes than running it on my companies production server. If anyone is interested, I'd be willing to add some of the changes to a pull request

**Comment by ehartford** [comment]
Super interested
