### ISSUE TITLE
Does not open the product card

### ISSUE THREAD

**Issue by 99percent6** [DivanteLtd/vue-storefront#1035]
Hello!
I found one problem - in browsers FireFox and mobile Safari (in these it is checked for sure, there may be some others also have a problem) after the first download of the site, the product card does not open. I checked this also on https://demo.vuestorefront.io/ . You can click it as many times as you like, but it will not open, after restarting the page the card opens. Seems a problem with the cache.
The problem for these browsers is that we first try to take data from the cache, but they are not there. And only then we make a request to the ElasticSearch. Apparently the code execution hangs at the stage of trying to access the browser cache. 
Refusing a cache request solves the problem, but this is not a good solution.

**Comment by pkarw** [comment]
Yes, I've observed this last week and even came with some fix: https://github.com/DivanteLtd/vue-storefront/commit/b621f12cd1a66b313e41a4365adaffddf71a5367

Setting the cache timeout for 2s; Did you tested this version (I mean the latest "develop" snapshot)? 
If it still occurs then we should find for some other solution

**Comment by 99percent6** [comment]
No, I have not tested it yet, but I will definitely do it and give feedback.

**Comment by 99percent6** [comment]
Yes, it's working!
