### ISSUE TITLE
Adjustments in the design of homepage

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#105]
My comments/suggestions (in Polish, sorry ;):
![1](https://user-images.githubusercontent.com/18116406/31544819-fac3ae64-b01c-11e7-91c2-a629df93e745.png)

The design:
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/18116406/31544858-18c54260-b01d-11e7-8bc9-95da924cb4ff.png">

**Comment by karolbzik** [comment]
Magento's logo - https://cdn.worldvectorlogo.com/logos/magento-2.svg.

**Comment by karolbzik** [comment]
@filrak could you please pick this issue? :)

**Comment by pkarw** [comment]
@karolbzik is it ready to be closed?

ps. Logo need to be clickable

**Comment by karolbzik** [comment]
@patrykpiston will check it.
