### ISSUE TITLE
Provide the higher quality icon for PWA splashscreen

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1060]
https://www.dropbox.com/s/5haebp7y9i5hr3d/Screenshot%202018-04-19%2012.53.57.png?dl=0

Would be good to have it till Imagine

**Comment by karolbzik** [comment]
@StasiekDivante could you please export logo from Figma?

**Comment by StasiekDivante** [comment]
![logo](https://user-images.githubusercontent.com/37068687/39864695-bbf4de6a-544a-11e8-9b48-bc687e20c5dc.png)

Logo in bigger size

**Comment by zavodyanka** [comment]
I will work on it
