### ISSUE TITLE
Adjustments in the design of sidebar cart

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#107]
My comments/suggestions (in Polish):
![4](https://user-images.githubusercontent.com/18116406/31545539-26879af8-b020-11e7-903e-8401094eb012.png)

The design:
<img width="1440" alt="5" src="https://user-images.githubusercontent.com/18116406/31545543-32fe403e-b020-11e7-9cb8-753f4314e0bd.png">

**Comment by patrykpiston** [comment]
Close comment did not register closing of this ticket
