### ISSUE TITLE
Images; 500 Internal Server Error

### ISSUE THREAD

**Issue by fit** [DivanteLtd/vue-storefront#1074]
Hi!
The product images are not fetched from the database because I have an error 500
![image](https://user-images.githubusercontent.com/26653363/39109890-993d1bf6-46d7-11e8-9a3c-b7c4c3afa981.png)

I installed **vue-storefront** with `yarn installer` and everything seems to work except images of the products :(
I tried to reinstall  **vue-storefront** but it did't help me

How to solve this problem?

PS When I try to connect to `http://localhost:8080/catalog/vue_storefront_catalog/product/_search?q=bag&size=50&from=0` I get an error `Cannot GET /catalog/vue_storefront_catalog/product/_search`

**Comment by pkarw** [comment]
Do you have imagemagick (“convert” cli command) available?
The second thing is if you have config.magento2 urls set properly to point to the magento2 media url?

**Comment by pkarw** [comment]
Any issue in the vue-storefront-api console?

**Comment by fit** [comment]
Oh...
I did not expect this at all but my problem was with `imagemagick`.
```brew install imagemagick``` solved my problem.
Thanks!
