### ISSUE TITLE
Filter Products Imported From Magento To Elastic Search By Stock Availability Or Other Criteria

### ISSUE THREAD

**Issue by phronesis** [DivanteLtd/vue-storefront#1076]
For our implementation, we have a requirement to only display products that are in stock or have backorder set on them or products from certain Magento website_ids. I am assuming that some others may have similar use cases and wanted to work on a PR that will be useful to others.

My thoughts on implementing this are:
Setting configuration options on mage2vs config to import products based on certain Magento filter attributes. Examples will include qty or website_ids. Then parsing those options to build the final query used to pull out products from Magento.
My challenge is that there seems to be a limitation on Magento 2 on filtering by extension_attributes as the stock_item.qty and website_ids fields are part of extension attributes.

Can anyone here confirm that this limitation indeed exists on the current stable releases of Magento2?

If they do, will it make sense to implement this as a filter just before writing the data to Elasticsearch based on the criteria that will be defined the configuration setting?

What are other recommendations?

**Comment by pkarw** [comment]
Good point! The out of stock products are listed or not regarding the Magento2 configuration (https://magento.stackexchange.com/questions/173486/magento2-rest-api-products-list-and-out-of-stock) I’m not sure if they can be filtered base on the availability thru api?

Filter before pushing products to ES / it may have sense; other option is to just filter them on the frontend extending the current ES query used on Category.vue (it should be a config. option to filter the unavailable products or not)

I have no opinion which way is better / maybe it’s good to have both for user to choose.

For sure it’s good to have the website_id filter as it’s required for multi website indexing - but if to be implemented it need to be implemented for all entity types not only products. Right now it can be just changed globally by changing the Magento2 api url as Magento supports the store view prefix (for example “en”, “pl”) for the rest api calls:

The answer seems to be quite simple. All you need to do is add the store code to the URL.

Example URL: http://localhost:8888/magento/index.php/rest/{store_code}/V1/products

**Comment by phronesis** [comment]
@pkarw thanks for your prompt response. I can confirm from this magento issue: https://github.com/magento/magento2/issues/2245 that we can't do the filtering on the API level, it MAY change in the 2.3 release.

So I will go with the options of filtering just before pushing to ES or filtering on the frontend. 

Will reference this issue in the PR.

Thanks for the heads-up on adding the store code to the api url to filter by a particular store, will try it out and see how that goes.

Thanks.

**Comment by pkarw** [comment]
OK! Please let me know about the progress and if You need any support

**Comment by shkodasv** [comment]
@phronesis do you know if this issue is fixed in newest version of the M2?
