### ISSUE TITLE
Adjustments in the design of product card

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#108]
My comments (in Polish):
![6](https://user-images.githubusercontent.com/18116406/31545878-6480f240-b021-11e7-8a38-a240a11a5882.png)

The design:
<img width="1440" alt="7" src="https://user-images.githubusercontent.com/18116406/31546008-dc4824ba-b021-11e7-84bf-b6e2c2cbffcd.png">

Please use this styling for the color and size selectors (active, choosen size or color should have a styled border):
<img width="375" alt="zrzut ekranu 2017-10-13 o 14 18 49" src="https://user-images.githubusercontent.com/18116406/31545899-74a69a26-b021-11e7-884d-59fbbc770cca.png">

Please remember to use the button as a place for the size and color validation messages.
<img width="305" alt="zrzut ekranu 2017-10-13 o 14 21 02" src="https://user-images.githubusercontent.com/18116406/31545981-c47fd850-b021-11e7-82a5-fcb5a5462133.png">

**Comment by patrykpiston** [comment]
I kept this open because:  
Issue now referenced in #156  
The validation messages aren't done yet
