### ISSUE TITLE
Notification: click on the message should fire the default action1

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1096]
It should just close the notification in the most cases. On the mobile - it’s relatively hard to point out to “OK” button with your thumbs:)
![41780f8b-bea7-4da1-8f87-4a9296a8e50f](https://user-images.githubusercontent.com/211899/39398130-abc97964-4b09-11e8-964f-a464b1e4dffb.png)

**Comment by Januszpl** [comment]
So perhaps we should change the design here ? Make OK btn wider and put some line between two actions "OK" and "PROCEED TO CHECKOUT" ?

**Comment by pkarw** [comment]
Could you just try with 50/50% and send screen how it looks like?

**Comment by Januszpl** [comment]
## Version with just chaning the width 50/50
<img width="376" alt="ver2b" src="https://user-images.githubusercontent.com/7412776/39399065-a5cffea0-4aed-11e8-80e3-d9e6ce5bb4e7.png">
<img width="496" alt="ver2" src="https://user-images.githubusercontent.com/7412776/39399066-a5eac794-4aed-11e8-91cb-28a584d1dcd2.png">

## version with some min-height (centered via flexbox) and with separator:*
<img width="494" alt="ver1b" src="https://user-images.githubusercontent.com/7412776/39399067-a60689f2-4aed-11e8-87e6-70d2ebcf2ae7.png">
<img width="355" alt="ver1" src="https://user-images.githubusercontent.com/7412776/39399068-a61fd6dc-4aed-11e8-9981-e3cbf7e3db74.png">

**Comment by pkarw** [comment]
It doesn’t look good for me to be honest. My suggestion:
- text message shouldn’t have been centered - please align to left
- optimize the default action position for mobile - align it to the right for being accessible by right thumb
- action1 should be aligned to right 
- action2 should be aligned to left 
- actions should have some min width / left and right paddling a for about 20px from text - but the width shouldn’t be set to constant: [   proceed to checkout   ] [   OK  ]
- clicking th text should execute action1 always

**Comment by Januszpl** [comment]
My suggestions:
- I would replace "OK" for "CLOSE" or "KEEP SHOPPING" (which is used by many top large ecommerce and we give clear action label). 
- I would not make "Product has been added to the cart!" triggering any action.

**Comment by JCown** [comment]
I'll work on that

**Comment by lorenaramonda** [comment]
I agree with @Januszpl 
I also don't like too much "proceed to checkout" splitted in two lines 🤔

**Comment by JCown** [comment]
Progress:
- replaced the actions ("OK" is on the right side now - to make it easier to tap on mobile). 
- clicking on notification (but not on action buttons) will fire action like "OK" button does
- text aligned to left; width of action buttons is no longer equal (and buttons are aligned to right side of notification popup)

Please see attached screenshots for mobile and desktop view and **share your opinion**!

Desktop:
![obraz](https://user-images.githubusercontent.com/28540671/40835644-53e9e198-6594-11e8-9a74-1afca052b845.png)

Mobile:
![obraz](https://user-images.githubusercontent.com/28540671/40835689-71a11fe4-6594-11e8-9e7a-cd2ab577b7bc.png)

**Comment by MatWaligora** [comment]
Here are some of my ideas on it :-)

<img width="485" alt="zrzut ekranu 2018-08-03 o 14 12 50" src="https://user-images.githubusercontent.com/20928689/43642503-1ed33700-9728-11e8-9e5f-a41ec2ee04a6.png">
<img width="488" alt="zrzut ekranu 2018-08-03 o 14 16 09" src="https://user-images.githubusercontent.com/20928689/43642504-1ef1d4da-9728-11e8-8bd5-ee1f9a6cd11d.png">
<img width="435" alt="zrzut ekranu 2018-08-03 o 14 03 37" src="https://user-images.githubusercontent.com/20928689/43642505-1f26c41a-9728-11e8-98a0-a1289a25936b.png">
