### ISSUE TITLE
The number of product added to the cart

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#110]
<img width="565" alt="zrzut ekranu 2017-10-13 o 14 31 45" src="https://user-images.githubusercontent.com/18116406/31546359-4614ae4e-b023-11e7-91a7-848680a7727a.png">

The design of this small component is available here - https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront-Open-Source?node-id=76%3A0, on the "Products listing with vertical filters" design.

**Comment by mercs600** [comment]
I think we can close it
