### ISSUE TITLE
Add store.override()

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1102]
It would be nice to have an option to re-map the Vuex action used by core/store module in the VS 

I see it as a method to extend the Vuex.store used by VS:-
`store.override('product/list', (payload) => {})`
or
`store.override('product/list', 'mystore/list')`

Then we need to override `dispatch()` method to make the usage of such a map. Of course, we'll be needing a `dispatchOriginal()` to execute the original action and allow the extension developers to modify the result

Such a "cheap IoC" could be of course generating some issues - like never be sure which exact method will be executed when few extensions will override some basic actions. Although it's still kind of useful option to modify the ways data is loaded from ES / other sources - without modifying the core.

**Comment by filrak** [comment]
If noone will take it I can start development next week.

**Comment by mercs600** [comment]
@filrak @pkarw did you see this approach ? 
article: https://blog.hellocomet.co/mixin-composition-in-vuex/ 
example: https://gitlab.com/etnbrd/vuex-composition-example/tree/master

**Comment by gopkumargopi** [comment]
@pkarw please assign this to me if my PR addressed this issue.
