### ISSUE TITLE
Support URL filters on the Category page

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1104]
We should have support for passing the filters in the URL to create the SEO friendly and promo links

I mean for example:
https://demo.vuestorefront.io/c/women-20/color/241/size/124

Right now the filters works fully just on the client side and are not supoprted by the SSR
After changing the filter the attributes should've been added to the window.location

**Comment by pkarw** [comment]
OK; with the new UrlDispatcher we should use queryString instead `?filter=value` ...

**Comment by patzick** [comment]
It's a good practice to add search filters as queryParams, not pathParams.
To complete this issue we should use queryString lib to just change filtersObject and parse it.

**Comment by patzick** [comment]
yup, exactly @pkarw :)

**Comment by pkarw** [comment]
This is related to #2180 so I've assigned it to  You @patzick

**Comment by pkarw** [comment]
Closed by #2724
