### ISSUE TITLE
Change the notification event name for custom actions

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1105]
https://github.com/DivanteLtd/vue-storefront/blob/9a98265b0e014f450b30095fceb64f4f3b762252/core/components/Notification.vue#L27

It should be changed to: **notification-after-**

We should include some additional data/arguments as an option for custom actions.

For example:
```js
          this.$bus.$emit('notification', {
            type: 'error',
            message: i18n.t(result.result),
            action1: { label: i18n.t('OK'), action: 'close' }
            action2: { label: i18n.t('Continue'), action: 'customAction', payload: { someCustom: 'attributes' } }
          })
```

The **payload** should be included in the $emit call of the **"notification-after-" + action event**

Add the default action "link" which is just for opening the URLs:

```js
          this.$bus.$emit('notification', {
            type: 'error',
            message: i18n.t(result.result),
            action1: { label: i18n.t('OK'), action: 'close' }
            action2: { label: i18n.t('Continue'), action: 'link', href: 'http://example.com' }
          })
```

**Comment by patrykpiston** [comment]
Closing as the notification event name was changed accordingly to the task  

PR: https://github.com/DivanteLtd/vue-storefront/pull/1159
