### ISSUE TITLE
Add and test the support for all other custom attribute types

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1106]
Multiselect  (99% cases it works just fine)
Text
Date

**Comment by mercs600** [comment]
@pkarw Which custom attributes do you mean ? Category filters or product details ? 
BTW. For better support various attributes on product details page we should have access to type of these attributes. I see this field with attributes for category, but not for product page.  .  

![zrzut ekranu 2018-05-16 o 22 57 15](https://user-images.githubusercontent.com/7935392/40143741-8c00c2c0-595c-11e8-8cd7-18c10de6c983.png)

**Comment by pkarw** [comment]
Hi Adam, Yes I meant category filters + displaying the filters on the category page at first step. Then kind of different options should be checked for Bundle products and for Configurable Options for products - all these types are supported by VS now but need to be tested.

Regarding the question - You can get the attribute metadata (the record You're refering to) from:
state.attribute.list_by_code[attriubute_code] OR state.attribute.list_by_id[attriubute_id]

These collections are always loaded with the attributes meta data.

Please take a look at:
