### ISSUE TITLE
Create translation for Brazilian Portuguese (pt_BR)

### ISSUE THREAD

**Issue by cagartner** [DivanteLtd/vue-storefront#1108]
Hello,

This project is awesome and a want help with a translation for brazilian portuguese, soon I'll send a PR with a translation.

Cheers.

**Comment by pkarw** [comment]
That's great! Looking forward to it!

**Comment by cagartner** [comment]
Created PR :)

**Comment by pkarw** [comment]
Thanks, great job! Merged!
