### ISSUE TITLE
Add the notification message that "the product was added to the cart"

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#111]
After the product was added to the cart (via product card, after clicking the button "Add to cart"), the notification should be presented.
<img width="447" alt="zrzut ekranu 2017-10-13 o 14 37 32" src="https://user-images.githubusercontent.com/18116406/31546569-263a9ede-b024-11e7-8f90-bbc440c538c2.png">

The notification should appear with the animation, similar to the patter of Material Motion.

The notification should be linked to the sidebar cart and checkout.

The design for the notification is available here https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront-Open-Source.

**Comment by karolbzik** [comment]
Let's do the notifications for "Product added to the cart" and "There's no product in the stock".

**Comment by karolbzik** [comment]
The notifications should enter the main screen from the bottom-left or bottom (in case of mobile views), similar to the notifications in the Google Drive.

**Comment by pkarw** [comment]
@mercs600 can you take care of finishing this task?

**Comment by mercs600** [comment]
@pkarw no problem, I would like to add some base animation for desktop only ;-)

**Comment by karolbzik** [comment]
@mercs600 here's my suggestion for the animation
![vs4](https://user-images.githubusercontent.com/18116406/33650513-96cd45a8-da62-11e7-9854-aa9b8c7a0f14.gif)

**Comment by mercs600** [comment]
@karolbzik did you test my last modification related with these notifications ? I added some animation like this.

**Comment by pkarw** [comment]
Add default fadeOut time for 5s + optional parameter for 'notification' message to override this default for custom values

**Comment by filrak** [comment]
done, you can see example notification data in `model/notification.json`
