### ISSUE TITLE
Category filter for color is good, add price range and it forgets the color?

### ISSUE THREAD

**Issue by alankent** [DivanteLtd/vue-storefront#1114]
I browse to a category and select a color filter (e.g. red). All the images refresh to be red photos - very nice! I can add size constraints. Still nice red product photos, with the added size constraint.

I then added a price filter constraint. All the images went back to random colors (blue, green, etc). The size filter still seems to be applied. But any combination I try with a price filter specified does not display product images in the selected color any more.

**Comment by pkarw** [comment]
Thanks Alan! Will check it, seems like and/or filter priorities issue probably

**Comment by pkarw** [comment]
Fixed in develop branch
