### ISSUE TITLE
Testing RWD

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#112]

**Comment by pkarw** [comment]
Patryk czy możesz - jakby starczyło ci czasu poklikac na iPhone/android;
Ale to jak uda się ogarnąć te pozostałe rzeczy zgłoszone przez karola

**Comment by pkarw** [comment]
![img_8842](https://user-images.githubusercontent.com/211899/31558810-ace18b80-b04e-11e7-8a16-aca639ab0de3.PNG)
![img_8843](https://user-images.githubusercontent.com/211899/31558811-ad36a8b8-b04e-11e7-95be-08b43564e9e9.PNG)
![img_8844](https://user-images.githubusercontent.com/211899/31558813-ad84942e-b04e-11e7-8d11-6d738367fec7.PNG)
![img_8845](https://user-images.githubusercontent.com/211899/31558814-adb72e34-b04e-11e7-82fe-ae1ce45708d4.PNG)
![img_8846](https://user-images.githubusercontent.com/211899/31558816-ae13cca2-b04e-11e7-8139-354e8a189ab4.PNG)

**Comment by patrykpiston** [comment]
Pewnie, robiłem to chwile dzisiaj jak wracałem z biura, aplikacje ogólnie
trzeba zaadoptować pod RWD.

**Comment by patrykpiston** [comment]
I'm taking this

**Comment by pkarw** [comment]
Connected with #170
