### ISSUE TITLE
docker-compose up not work

### ISSUE THREAD

**Issue by benyang2015** [DivanteLtd/vue-storefront#1178]

**Comment by pkarw** [comment]
Please provide us with the exact logs

**Comment by mfdeveloper** [comment]
Hey @benyang2015, I've got the same problem to start the `backend` services with `docker-compose` after shutdown my PC. Try to run `npm run all`. This npm task run `docker-compose up -d > /dev/null 2>&1`. If you run just `docker-compose up`, the Elasticsearch service will be with **red** signal
