### ISSUE TITLE
how can I stop port 3000

### ISSUE THREAD

**Issue by iamike** [DivanteLtd/vue-storefront#1196]
it looks once it started by yarn, you can never get it stop. please advice...

**Comment by tomtev** [comment]
None of these works.

**Comment by LiTiang** [comment]
Hi, by using ` killall node `, 
i still can access **localhost:3000** in my browser

and after i reboot my Mac, 
i have no idea that why i still can access **localhost:3000** ?
( i.e. vue-storefront still running ! )


at now, i really don't know how to kill that ( or kill all container ? )
### please help . . .

**Comment by BenSpace48** [comment]
This is a bizarre choice, why can't it work like every other node workflow where running `npm start` boots the server and stopping that process kills the server?

It feels really wrong to have it running at all times, I only wanted to try out Vue Storefront but now it runs 24/7.

At the very least please give instructions on how to prevent this.

**Comment by manojibcarockers** [comment]
Reset server config file like apache2 -> 000-default.conf
After restart the server to solve the issue.
