### ISSUE TITLE
Improve the SEO support

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1226]
We're getting some calls from the users that would be great to update the SEO capabilities VS is offering:
- routes + redirects (we should support magento urls to be perfectly honest),
- markup structure
- meta tags 

We need some basic SEO audit for the default theme + apply the insights

**Comment by Triloworld** [comment]
Thats bad. There isn't any additional markup. 

First question: what type of data will be implemented? 
Source: https://developers.google.com/search/docs/guides/intro-structured-data#multiple-entities-on-the-same-page#structured-data-format

There is place for module with provide some additional data to header/content.

Rich snippet (there is need to be added some helper):

- Brand & contact - main data 
https://developers.google.com/search/docs/data-types/logo https://developers.google.com/search/docs/data-types/corporate-contact
https://developers.google.com/search/docs/data-types/social-profile
- Breadcrumbs - navigation
- Search - to enable searching from search bar (https://developers.google.com/search/docs/data-types/sitelinks-searchbox)
- Product page - name, quantity (in stock, how much etc), (https://developers.google.com/search/docs/data-types/product)
- Product card - link/id to disable duplication across site (many card, one canonical link to page with all data)
- Category - canonical url to force one url 
- CMS page - author, date of publishing

URL: 
Product: https://demo.vuestorefront.io/p/WSH12/erika-running-short-2045/WSH12
Double SKU in url, additional "p" in url. 

Category: https://demo.vuestorefront.io/c/women-20
Only additional "c" letter. 
How to apply filters to have it in url (share to friend etc)?

As I understand, this is to recognize types of page.

**Comment by filrak** [comment]
Some of the seo problems will be solved with new theme, regarding routes we should do it now

**Comment by ngeleedst** [comment]
Hi Filrak,

Any news about this thread? And in special the routing request, i would like to use clean urls without sku or /p etc.

Thanks!

**Comment by pkarw** [comment]
You can remove `p` and `c` from url wiht this option: https://divanteltd.github.io/vue-storefront/guide/basics/configuration.html#products Please try it out and let us know if it helped?

**Comment by ngeleedst** [comment]
Hi Pkarw,

Thanks for the quick reply, this is already helping me but i would like to completely remove sku/id from url. Is it possible to use the url_key as identifier?

**Comment by ngeleedst** [comment]
@pkarw any news about this, please see my last question?

**Comment by pkarw** [comment]
Hi Nick, could you please add ticket for this feature requests? It require us to modify how product/single action works to find product by url_key either add a url_key to sku mapper

**Comment by pkarw** [comment]
Please check and comment this PR: https://github.com/DivanteLtd/vue-storefront/pull/2401
