### ISSUE TITLE
Checkout: required (red label) missing on country select 

### ISSUE THREAD

**Issue by Triloworld** [DivanteLtd/vue-storefront#1227]
<img width="732" alt="zrzut ekranu 2018-05-30 o 14 14 22" src="https://user-images.githubusercontent.com/2671726/40719430-ea577b86-6413-11e8-9ea9-8d530fe9c7d4.png">

**Comment by pkarw** [comment]
I've added '*' - but probably the ticket is about the missing green/red label right? @mercs600 are You willing to help with that?

**Comment by Triloworld** [comment]
Consistent is key. If other field are colored in red then this one need to react in same manner.
