### ISSUE TITLE
Checkout: tabbing & pressing enter can remove accidental items in summary.

### ISSUE THREAD

**Issue by Triloworld** [DivanteLtd/vue-storefront#1228]
This state produce error when submitting form.
That feature can be removed from code
<img width="1004" alt="zrzut ekranu 2018-05-30 o 14 20 02" src="https://user-images.githubusercontent.com/2671726/40719707-a4c224c6-6414-11e8-95ce-7673ecbb437e.png">

**Comment by pkarw** [comment]
Don't quite get it? It seems like You've different passwords provided, validation error + cannot continue to shipping (disabled button). Isn't it correct behavior?

**Comment by pkarw** [comment]
OK, it shouldn't be empty - for sure :) So How to reproduce this step by step?

**Comment by Triloworld** [comment]
There are inputs that are accessible by pressing TAB (it give focus on buttond, inputs etc) on checkout page. 
I removed style so there is: edit, remove and close button. I can even change quantity by focus on it. 

<img width="921" alt="zrzut ekranu 2018-05-30 o 15 07 20" src="https://user-images.githubusercontent.com/2671726/40721937-36a1c698-641b-11e8-8d20-57c60b3e57a2.png">

**Comment by pkarw** [comment]
OK :D

**Comment by Triloworld** [comment]
I will focus on heavy test before we (as a company) will be using it on production.
I have more issues, as that can I create it like that? I will more precise describe steps :)

**Comment by pkarw** [comment]
Couldn't reproduce the sequence with tab etc. But I've hardened the  Checkout checks for the cart items instead
