### ISSUE TITLE
Quantity field - accept dot (.) and show error

### ISSUE THREAD

**Issue by Triloworld** [DivanteLtd/vue-storefront#1229]
1. Add product to card
2. Open cart
3. Press "Edit"
4. Type "0.1" into number field. It will produce error as visible on screenshoot.

<img width="731" alt="zrzut ekranu 2018-05-30 o 15 16 58" src="https://user-images.githubusercontent.com/2671726/40722498-cdabf508-641c-11e8-93b3-96cc1b145417.png">

**Comment by pkarw** [comment]
Thanks, fixed!
