### ISSUE TITLE
Adding to compare/favorite - name value missing in popup message

### ISSUE THREAD

**Issue by Triloworld** [DivanteLtd/vue-storefront#1230]
1. Go to https://demo.vuestorefront.io/p/24-WG09/luma-analog-watch-41
2. Click "Add to compare"

<img width="842" alt="zrzut ekranu 2018-05-30 o 15 46 07" src="https://user-images.githubusercontent.com/2671726/40724151-a94a7726-6420-11e8-86ae-71e226809174.png">

**Comment by pkarw** [comment]
Thanks, fixed!
