### ISSUE TITLE
My account - newsletter button is active even wihout change

### ISSUE THREAD

**Issue by Triloworld** [DivanteLtd/vue-storefront#1231]
1. Log in
2. Go to newsletter section
3. Click "Edit newsletter preferences"
4. Button is active, even if no change occur.
 
<img width="653" alt="zrzut ekranu 2018-05-30 o 15 56 51" src="https://user-images.githubusercontent.com/2671726/40724781-2be5d1f2-6422-11e8-95d7-2ccb91486d97.png">

**Comment by pkarw** [comment]
@akbarik could You please take care of that one?

**Comment by sheensol** [comment]
@pkarw I can do this

**Comment by pkarw** [comment]
OK, go for it

**Comment by sheensol** [comment]
kindly add me contributor in repo

**Comment by akbarik** [comment]
Currently on all My Account pages, including My Profile, My Shipping Details and My Newsletter (newsletter has a bug though), the Update button is always active, no matter were there any changes in the fields or not. If there are no changes, pressing Update button doesn't trigger the API call to the backend. 
Should we leave it this way or should we make the Update button inactive (disabled) if there are no changes?

**Comment by pkarw** [comment]
There is an agreed change to the validation mechanism to make the buttons enabled all the time and show apropriate validation messages when sth is wrong: https://github.com/DivanteLtd/vue-storefront/pull/1073

I think we should leave it as it is
