### ISSUE TITLE
My account - Session break

### ISSUE THREAD

**Issue by Triloworld** [DivanteLtd/vue-storefront#1232]
This is weird.
1. Log in
2. Click "My profile"
2. Click "My shipping details"
3.  Click "My profile"

You get "https://demo.vuestorefront.io/it/my-account" with italian language and session is broken. 
You cannot go back (not working)
Cannot click on profile avatar
Cannot change language

<img width="1324" alt="zrzut ekranu 2018-05-30 o 16 07 16" src="https://user-images.githubusercontent.com/2671726/40725372-8cf7f5be-6423-11e8-89b6-40e988b54e00.png">

**Comment by Triloworld** [comment]
One more place:
1. Click in footer on "About us" 
2. Click logo from top.
Italian language and broken session.

**Comment by pkarw** [comment]
Thanks, fixed!
