### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by Igloczek** [DivanteLtd/vue-storefront#1233]
Add a CHANGELOG.md file, following rules of https://keepachangelog.com/en/1.0.0/

OFC we will need to adjust contribution rules, to force everyone to add changes description to "Unreleased" group on every PR.

**Comment by pkarw** [comment]
This is good idea! We can start by combining the [Release notes](https://github.com/DivanteLtd/vue-storefront/releases) with [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Upgrade%20notes.md)

**Comment by pkarw** [comment]
Anybody willing to start? :)

**Comment by dennisotugo** [comment]
@pkarw I would like to start this!

**Comment by pkarw** [comment]
Thats great! Please go on and propose the initial version as a Pull Request!
