### ISSUE TITLE
Improve the docs

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1239]
Now the docs are scattered across multiple medium (github, medium.com ...), different formats etc

It may be really confusing, especially for the newcomers!

Which tools should we use? wiki? What for API specs?

We’re also looking for volunteers ready to help us with improving the docs

**Comment by pkarw** [comment]
Any ideas, requests, what to improve first hand - are welcome

**Comment by cagartner** [comment]
I think a video/documentation showing how to config a basic production enviroment, in digital ocean for example.

**Comment by collymore** [comment]
How about using Vuepress?   
It's really easy to use and I'd be happy to setup this?

It's what powers the main vue docs https://vuejs.org and vuepress site https://vuepress.vuejs.org/guide

**Comment by Igloczek** [comment]
I'd say that first of all docs should have own repository, to not mix docs updates with development, but what is most important, everything will be in one place.
Talking about tools +1 to vuepress, but also https://github.com/GitbookIO/gitbook is a nice choice, in snowdog we are using is currently for various things and just works.

**Comment by filrak** [comment]
I'm currently working on docs.vuestorefront.io since last month. I'll finish it after everything I'm working on currently will be done. I started doing ti with nuxt and GH API but it can be easly moved to anything else

**Comment by pkarw** [comment]
@filrak has some idea for that - ask him :)

**Comment by pkarw** [comment]
I think we can use VuePress - and start this task by simply running vue press instance + moving `/doc` folder to the new structure.

**Comment by pkarw** [comment]
This is going to happen in here: https://github.com/DivanteLtd/vue-storefront/pull/1728
