### ISSUE TITLE
When placing order, regionId is a required field error.

### ISSUE THREAD

**Issue by jimcreate78** [DivanteLtd/vue-storefront#1258]
error: API call failed: Please check the shipping address information. regionId is a required field.
2018-06-03T21:04:06.555Z - error: Error placing an order Please check the shipping address information. regionId is a required field. string

When placing an order the regionId is set to 0 which the api is not accepting.

**Comment by pkarw** [comment]
OK, so I've added a region mapper:
- https://github.com/DivanteLtd/vue-storefront-api/commit/0bf0f2effe146f1641da9bc7a62b42e0703f2e52

... and added support for region_code/region_id fields in the Checkout:

- https://github.com/DivanteLtd/vue-storefront/commit/e5dd7e1fffc6256fe0a92150bbf35d9b07dcd7c8


Now You can:
- set in the theme: Checkout/ShippingInformation and Checkout/BillingInformation the fields "regiod_id" and "region_code"
- OR - not changing anything in the theme - but just to validate the "region" field (which is now open text) to be a valid one -> for example "region" => "CA" will be mapped to California etc.  -> order_2_magento will map this region code to the valid region

List of the valid regions:
CA, WA, ... - two letter ISO codes as set in Magento

Please be sure that magento2-rest-client has been updated prior to running `npm run o2m` by executing `npm install magento2-rest-client`

**Comment by jimcreate78** [comment]
I am getting permission denied when trying to...
sudo npm install github:DivanteLtd/magento2-rest-client
or
sudo npm install magento2-rest-client

**Comment by jimcreate78** [comment]
I have never been able to get region or regionId to pass to the api.  Had something been changed to make this not work?

**Comment by jimcreate78** [comment]
I was able to get this working
