### ISSUE TITLE
npm run installer in Dockerfile

### ISSUE THREAD

**Issue by GarPit** [DivanteLtd/vue-storefront#1264]
Hello,

I'm trying to make an image and writing a Dockerfile:

    FROM node:latest
    RUN git clone https://github.com/DivanteLtd/vue-storefront.git
    WORKDIR /vue-storefront
    RUN npm install
    RUN /bin/echo -e “No\ngit\n../vue-storefront-api\nhttp://localhost:8080/img/” | npm run installer

But last one doesn't work, `npm run installer` requires user input. Is there a way to pass it?

**Comment by GarPit** [comment]
Ok, but after this `npm run installer`, right?

**Comment by zstarer** [comment]
thanks! man that was a quick response :)

**Comment by pkarw** [comment]
Yes

**Comment by GarPit** [comment]
So using `yarn` instead of `npm` will make my input args work?

**Comment by pkarw** [comment]
We’re working on official docker images. Currently you can test the vue-storefront-api image and next 1-2 weeks we’ll be having the frontend image as well: https://github.com/DivanteLtd/vue-storefront-api/tree/feature/docker?files=1

**Comment by pkarw** [comment]
@GarPit no, it’s not abot arguments it’s about workspaces which are supported only by yarn; args is different story

**Comment by zstarer** [comment]
we just moved from using node:latest to node:8.5.0 since we saw an earlier PR that you were using 8.5.0 on debian

**Comment by pkarw** [comment]
You’re preparing these images for your deployment or kind of general ones?

**Comment by GarPit** [comment]
@pkarw Thanks, I saw both vue-storefront-api and vue-storefront repos on DockerHub. Not working yet?

**Comment by GarPit** [comment]
For development

**Comment by GarPit** [comment]
So my question is about passing input to those 4 questions. `yarn` or `npm` it doesn't matter

**Comment by pkarw** [comment]
Never tried this :) maybe just add the second mode to the installer / getting params from the named  args or ENV?

Generally speaking installer uses lot of defaults to generate the config file and maybe it’s a better way to generate the local.json outside the installer?

This is how we probably will approach configs in our official docker

**Comment by pszreder** [comment]
@GarPit we are working on a fully containerized environment for both projects (vue-storefront and vue-storefront-api).

For vue-storefront-api - take a look at the feature/docker branch. Testers welcome! :-)

For the vue-storefront - we are working on an official image, currently available at hub.docker.com is incomplete (for clarity, I will remove it so that it does not cause confusion). There are several architectural challenges to overcome, but the goal is to make the Docker engine the only locally installed requirement for the project.
