### ISSUE TITLE
The color switcher doesn't always switch the photo

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1268]
https://www.dropbox.com/s/zp06g0db8z3pelr/Screenshot%202018-06-08%2010.47.47.png?dl=1

All other attributes are correctly set; photo not - but just .. by the switcher in the middle :D The color switchers on the edges works fine - not sure if it's anyhow related :) Just an observation

**Comment by Januszpl** [comment]
@pkarw @nuovecode Bug is related to using media_gallery with children images and using uniqBy method (imho problems is with the last as it removes duplicated entries but unfortunately without any extra logic and it removes the one coming from variant (simple product). Then later we can't show image assigned to this variant as it was removed from the array.  We should refactor this part and fix at once #1327 and #1326 

Magento use option 
```
<vars module="Magento_ConfigurableProduct">
      <var name="gallery_switch_strategy">prepend</var>
</vars>
```

to replace or prepend variant images to the main configurable image when selecting variant. On page load it shows images set for configurable product. (I know it was said in case user set variant on category page and go to product page it should already show variant image)

I think I will be able to find some time and refactor this part of code to provide for all three issues.
