### ISSUE TITLE
Check core components

### ISSUE THREAD

**Issue by Aekal** [DivanteLtd/vue-storefront#1269]
We should check existing core components and move some logic from/to theme. 
At the moment we have some empty files in core. It'll be nice to check each file and decide which logic should be placed in core and which in theme.
We can also clean up some code, remove unnecessary files etc.

**Comment by pkarw** [comment]
@aekal Please remove {{ multistoreEnabled }} snippet from filter which causes displaying ... true 
![0cd7e098-3d22-48a3-addd-dd8c7d58b3a3](https://user-images.githubusercontent.com/211899/41174892-a1878302-6b5b-11e8-833a-e4407aaff7c1.jpeg)

**Comment by Aekal** [comment]
@pkarw I forgot to remove one line for debugging purposes :P

**Comment by pkarw** [comment]
Good job!
