### ISSUE TITLE
Documentation - readme.md

### ISSUE THREAD

**Issue by Triloworld** [DivanteLtd/vue-storefront#1273]
Why even bother? 
No informations about supporting browsers - thats first important section.
Take for example: https://github.com/vuejs/vue 👀 
Requirements section is very important as many folks on slack pointed out (ImageMagick for example).  - second
There exist logo, maybe add it ? - third
License section can go to the end of list, because there can be added little badge in header :)
Technology section can have some logo of vuejs, elasticsearch, Magento 2 (only required show)
There need to be node instance along with elasticsearch.
Partners can be higher to show that project is alive and have companies behind it 👍 

This issue need of course collaboration, only pointing out what missing or can be better in my opinion :)

What about documentation? It is up to date? No static site ;/
Is there some roadmap with documentation? I found some of them :) I will help with that if I can

Thanks that I can add some value to this amazing work 💛

**Comment by pkarw** [comment]
Thanks for your feedback! Sure - Readme is worth improving, we'll take care of the changes.
Would be great if You could help us with the docs and other issues! Feel free to choose some interesting tickets and start working on them!

**Comment by janmyszkier** [comment]
So summary of things needed
- [x] add vuestorefront logo to readme
- [ ] add section about supported browsers, tell to look into `"browserslist"` of `package.json`
- [ ] in `technology` section, replace possible technologies with logos, add the non-logo as "and also Tech1, tech2(,techn) and techn+1
- [ ] Move `License` section to the end of readme(below screenshots)

While the OP requested to add imagemagick to the stack, imagemagick is `vue-storefront-api` requirement and if needed, should be added there.

**Comment by janmyszkier** [comment]
I think this can be closed thanks to PRs made and mentioned here

**Comment by simonmaass** [comment]
@pkarw @janmyszkier agree - this can be closed
