### ISSUE TITLE
Installation guide with local redis & elasticsearch 

### ISSUE THREAD

**Issue by jonashrem** [DivanteLtd/vue-storefront#1275]
The guide here https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Installing%20on%20Linux%20and%20MacOS.md states that you can use a local elasticsearch and redis instead of locker.

But the guide below only explains a deployment using docker.

Is anyone interested in extending the guide for installation without docker?

**Comment by benyang2015** [comment]
@jonashrem do you solved this? I also want to know how to install redis & elasticsearch on local

**Comment by pkarw** [comment]
Consider it done: https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Production%20setup%20(WIP).md
