### ISSUE TITLE
how to add bestseller on the left filter on the category?

### ISSUE THREAD

**Issue by benyang2015** [DivanteLtd/vue-storefront#1276]

**Comment by pkarw** [comment]
Please take a look on how this component has been designed: https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/components/theme/blocks/Inspirations/Inspirations.vue

And try to create Your own for displaying bestsellers. Then please use it in the https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/components/core/blocks/Category/Sidebar.vue
