### ISSUE TITLE
Create facebook pixel Integration extension

### ISSUE THREAD

**Issue by benyang2015** [DivanteLtd/vue-storefront#1277]

**Comment by pkarw** [comment]
Could You provide some more spec + acceptance criteria for this featuer?

**Comment by benyang2015** [comment]
facebook pixel plugin：like
https://marketplace.magento.com/apptrian-facebook-pixel.html

**Comment by collymore** [comment]
Plugin available here https://github.com/new-fantastic/vsf-facebook-pixel
