### ISSUE TITLE
Dynamic config reload OR just to use the ENV variables for endpoint hosts and key variables

### ISSUE THREAD

**Issue by ismailyenigul** [DivanteLtd/vue-storefront#1290]
I installed vue-storefront-1.0.5 and modifed config/local.json file.
replaced all localhost:8080 to http://myhostname:8080 in local.json

There is not localhost string in local.cf but I see that vue-storefront still tries to connect localhost:8080 
for some requests.

![image](https://user-images.githubusercontent.com/2566232/41378731-a9e8ec6e-6f68-11e8-9cb5-4f74ca7d5795.png)

Is there any other place to replace api url?

**Comment by pkarw** [comment]
Config files are being read only during the compilation process. Have you restarted “yarn dev” after changing the endpoints? Please also “Clear Storage” in the browser developer tools “Application” pane. Let me know if the problem still exists.

**Comment by ismailyenigul** [comment]
Thanks for the update.
But I am still looking for where to update for localhost:8080/api/user/create calls?
Everything in local.json refers to my custom domain url.

**Comment by pkarw** [comment]
Please attach the default + local jsons to let me check it

**Comment by ismailyenigul** [comment]
local.json

more config/local.json 
{
  "server": {
    "host": "167.99.181.100",
    "port": 3000
  },
  "elasticsearch": {
    "httpAuth": "",
    "host": "http://vuestore.ysrtech.net:8080/api/catalog",
    "index": "vue_storefront_catalog"
  },
  "ssr": {
    "executeMixedinAsyncData": true
  },
  "storeViews": {
    "multistore": false,
    "mapStoreUrlsFor": [
      "de",
      "it"
    ],
    "de": {
      "storeCode": "de",
      "disabled": true,
      "storeId": 3,
      "name": "German Store",
      "url": "/de",
      "elasticsearch": {
        "host": "167.99.181.100:8080/api/catalog",
        "index": "vue_storefront_catalog_de"
      },
      "tax": {
        "defaultCountry": "DE",
        "defaultRegion": "",
        "calculateServerSide": true
      },
      "i18n": {
        "fullCountryName": "Germany",
        "fullLanguageName": "German",
        "defaultLanguage": "DE",
        "defaultCountry": "DE",
        "defaultLocale": "de-DE",
        "currencyCode": "EUR",
        "currencySign": "EUR",
        "dateFormat": "HH:mm D-M-YYYY"
      }
    },
    "it": {
      "storeCode": "it",
      "disabled": true,
      "storeId": 4,
      "name": "Italian Store",
      "url": "/it",
      "elasticsearch": {
        "host": "167.99.181.100:8080/api/catalog",
        "index": "vue_storefront_catalog_it"
      },
      "tax": {
        "defaultCountry": "IT",
        "defaultRegion": "",
        "calculateServerSide": true
      },
      "i18n": {
        "fullCountryName": "Italy",
        "fullLanguageName": "Italian",
        "defaultCountry": "IT",
        "defaultLanguage": "IT",
        "defaultLocale": "it-IT",
        "currencyCode": "EUR",
        "currencySign": "EUR",
        "dateFormat": "HH:mm D-M-YYYY"
      }
    }
  },
  "entities": {
    "optimize": true,
    "twoStageCaching": true,
    "category": {
      "includeFields": [
        "children_data",
        "id",
        "children_count",
        "sku",
        "name",
        "is_active",
        "parent_id",
        "level"
      ]
    },
    "attribute": {
      "includeFields": [
        "attribute_code",
        "id",
        "entity_type_id",
        "options",
        "default_value",
        "is_user_defined",
        "frontend_label",
        "attribute_id",
        "default_frontend_label",
        "is_visible_on_front",
        "is_visible",
        "is_comparable"
      ]
    },
    "productList": {
      "sort": "",
      "includeFields": [
        "type_id",
        "sku",
        "product_links",
        "tax_class_id",
        "special_price",
        "special_to_date",
        "special_from_date",
        "name",
        "price",
        "priceInclTax",
        "originalPriceInclTax",
        "originalPrice",
        "specialPriceInclTax",
        "id",
        "image",
        "sale",
        "new"
      ],
      "excludeFields": [
        "configurable_children",
        "description",
        "configurable_options",
        "sgn"
      ]
    },
    "productListWithChildren": {
      "includeFields": [
        "type_id",
        "sku",
        "name",
        "tax_class_id",
        "special_price",
        "special_to_date",
        "special_from_date",
        "price",
        "priceInclTax",
        "originalPriceInclTax",
        "originalPrice",
        "specialPriceInclTax",
        "id",
        "image",
        "sale",
        "new",
        "configurable_children.image",
        "configurable_children.sku",
        "configurable_children.price",
        "configurable_children.special_price",
        "configurable_children.priceInclTax",
        "configurable_children.specialPriceInclTax",
        "configurable_children.originalPrice",
        "configurable_children.originalPriceInclTax",
        "configurable_children.color",
        "configurable_children.size",
        "product_links"
      ],
      "excludeFields": [
        "description",
        "sgn"
      ]
    },
    "product": {
      "excludeFields": [
        "updated_at",
        "created_at",
        "attribute_set_id",
        "status",
        "visibility",
        "tier_prices",
        "options_container",
        "url_key",
        "msrp_display_actual_price_type",
        "has_options",
        "stock.manage_stock",
        "stock.use_config_min_qty",
        "stock.use_config_notify_stock_qty",
        "stock.stock_id",
        "stock.use_config_backorders",
        "stock.use_config_enable_qty_inc",
        "stock.enable_qty_increments",
        "stock.use_config_manage_stock",
        "stock.use_config_min_sale_qty",
        "stock.notify_stock_qty",
        "stock.use_config_max_sale_qty",
        "stock.use_config_max_sale_qty",
        "stock.qty_increments",
        "small_image"
      ],
      "includeFields": null
    }
  },
  "cart": {
    "server_merge_by_default": true,
    "synchronize": true,
    "synchronize_totals": true,
    "setCustomProductOptions": true,
    "setConfigurableProductOptions": true,
    "create_endpoint": "http://167.99.181.100:8080/api/cart/create?token={{token}}",
    "updateitem_endpoint": "http://167.99.181.100:8080/api/cart/update?token={{token}}&cartId={{cartId}}",
    "deleteitem_endpoint": "http://167.99.181.100:8080/api/cart/delete?token={{token}}&cartId={{cartId}}",
    "pull_endpoint": "http://167.99.181.100:8080/api/cart/pull?token={{token}}&cartId={{cartId}}",
    "totals_endpoint": "http://167.99.181.100:8080/api/cart/totals?token={{token}}&cartId={{cartId}}",
    "paymentmethods_endpoint": "http://167.99.181.100:8080/api/cart/payment-methods?token={{token}}&cartId={{cartId}}",
    "shippingmethods_endpoint": "http://167.99.181.100:8080/api/cart/shipping-methods?token={{token}}&cartId={{cartId}}",
    "shippinginfo_endpoint": "http://167.99.181.100:8080/api/cart/shipping-information?token={{token}}&cartId={{cartId}}",
    "collecttotals_endpoint": "http://167.99.181.100:8080/api/cart/collect-totals?token={{token}}&cartId={{cartId}}",
    "deletecoupon_endpoint": "http://167.99.181.100:8080/api/cart/delete-coupon?token={{token}}&cartId={{cartId}}",
    "applycoupon_endpoint": "http://167.99.181.100:8080/api/cart/apply-coupon?token={{token}}&cartId={{cartId}}"
  },
  "products": {
    "configurableChildrenStockPrefetchStatic": false,
    "configurableChildrenStockPrefetchDynamic": false,
    "configurableChildrenStockPrefetchStaticPrefetchCount": 8,
    "filterUnavailableVariants": false,
    "preventConfigurableChildrenDirectAccess": true,
    "alwaysSyncPlatformPricesOver": false,
    "clearPricesBeforePlatformSync": false,
    "waitForPlatformSync": false,
    "setupVariantByAttributeCode": true,
    "endpoint": "http://167.99.181.100:8080/api/product",
    "defaultFilters": [
      "color",
      "size",
      "price",
      "erin_recommends"
    ],
    "galleryVariantsGroupAttribute": "color"
  },
  "orders": {
    "endpoint": "http://167.99.181.100:8080/api/order",
    "payment_methods_mapping": {}
  },
  "users": {
    "autoRefreshTokens": true,
    "endpoint": "http://167.99.181.100:8080/api/user",
    "history_endpoint": "http://167.99.181.100:8080/api/user/order-history?token={{token}}",
    "resetPassword_endpoint": "http://167.99.181.100:8080/api/user/resetPassword",
    "changePassword_endpoint": "http://167.99.181.100:8080/api/user/changePassword?token={{token}}",
    "login_endpoint": "http://167.99.181.100:8080/api/user/login",
    "create_endpoint": "http://167.99.181.100:8080/api/user/create",
    "me_endpoint": "http://167.99.181.100:8080/api/user/me?token={{token}}",
    "refresh_endpoint": "http://167.99.181.100:8080/api/user/refresh"
  },
  "stock": {
    "synchronize": true,
    "allowOutOfStockInCart": true,
    "endpoint": "http://167.99.181.100:8080/api/stock"
  },
  "images": {
      "baseUrl": "https://demo.vuestorefront.io/img/",
    "productPlaceholder": "/assets/placeholder.jpg"
  },
  "install": {
    "is_local_backend": true,
    "backend_dir": "../vue-storefront-api"
  },
  "demomode": true,
  "tax": {
    "defaultCountry": "PL",
    "defaultRegion": "",
    "calculateServerSide": true
  },
  "i18n": {
    "defaultCountry": "US",
    "defaultLanguage": "EN",
    "availableLocale": [
      "en-US",
      "de-DE",
      "fr-FR",
      "es-ES",
      "nl-NL",
      "jp-JP",
      "ru-RU",
      "it-IT",
      "pt-BR",
      "pl-PL"
    ],
    "defaultLocale": "en-US",
    "currencyCode": "USD",
    "currencySign": "$",
    "dateFormat": "HH:mm D/M/YYYY",
    "fullCountryName": "United States",
    "fullLanguageName": "English"
  },
  "mailchimp": {
    "endpoint": "http://167.99.181.100:8080/api/ext/mailchimp-subscribe/subscribe"
  },
  "theme": "@vue-storefront/theme-default",
  "analytics": {
    "id": false
  },
  "stripe": {
    "api_key": "my_example_api_key"
  }
}


default.json


# more config/default.json 
{
    "server": {
      "host": "localhost",
      "port": 3000
    },
    "elasticsearch": {
      "httpAuth": "",
      "host": "localhost:8080/api/catalog",
      "index": "vue_storefront_catalog"
    },
    "ssr": {
      "executeMixedinAsyncData": true
    },
    "storeViews": {
      "multistore": false,
      "mapStoreUrlsFor": ["de", "it"],
      "de": {
        "storeCode": "de",
        "disabled": true,
        "storeId": 3,
        "name": "German Store",
        "url": "/de",
        "elasticsearch": {
          "host": "localhost:8080/api/catalog",
          "index": "vue_storefront_catalog_de"
        },
        "tax": {
          "defaultCountry": "DE",
          "defaultRegion": "",
          "calculateServerSide": true
        },
        "i18n": {
          "fullCountryName": "Germany",
          "fullLanguageName": "German",
          "defaultLanguage": "DE",
          "defaultCountry": "DE",
          "defaultLocale": "de-DE",
          "currencyCode": "EUR",
          "currencySign": "EUR",
          "dateFormat": "HH:mm D-M-YYYY"
        }
      },
      "it": {
        "storeCode": "it",
        "disabled": true,
        "storeId": 4,
        "name": "Italian Store",
        "url": "/it",
        "elasticsearch": {
          "host": "localhost:8080/api/catalog",
          "index": "vue_storefront_catalog_it"
        },
        "tax": {
          "defaultCountry": "IT",
          "defaultRegion": "",
          "calculateServerSide": true
        },
        "i18n": {
          "fullCountryName": "Italy",
          "fullLanguageName": "Italian",
          "defaultCountry": "IT",
          "defaultLanguage": "IT",
          "defaultLocale": "it-IT",
          "currencyCode": "EUR",
          "currencySign": "EUR",
          "dateFormat": "HH:mm D-M-YYYY"
        }
      }
    },
    "entities": {
      "optimize": true,
      "twoStageCaching": true,
      "category": {
        "includeFields": [ "children_data", "id", "children_count", "sku", "name", "is_active", "parent_id", "level" ]
      },
      "attribute": {
        "includeFields": [ "attribute_code", "id", "entity_type_id", "options", "default_value", "is_user_defined", "frontend_label", 
"attribute_id", "default_frontend_label", "is_visible_on_front", "is_visible", "is_comparable" ]
      },
      "productList": {
        "sort": "",
        "includeFields": [ "type_id", "sku", "product_links", "tax_class_id", "special_price", "special_to_date", "special_from_date",
 "name", "price", "priceInclTax", "originalPriceInclTax", "originalPrice", "specialPriceInclTax", "id", "image", "sale", "new" ],
        "excludeFields": [ "configurable_children", "description", "configurable_options", "sgn" ]
      },
      "productListWithChildren": {
        "includeFields": [ "type_id", "sku", "name", "tax_class_id", "special_price", "special_to_date", "special_from_date", "price",
 "priceInclTax", "originalPriceInclTax", "originalPrice", "specialPriceInclTax", "id", "image", "sale", "new", "configurable_children.
image", "configurable_children.sku", "configurable_children.price", "configurable_children.special_price", "configurable_children.pric
eInclTax", "configurable_children.specialPriceInclTax", "configurable_children.originalPrice", "configurable_children.originalPriceInc
lTax", "configurable_children.color", "configurable_children.size", "product_links" ],
        "excludeFields": [ "description", "sgn"]
      },
      "product": {
        "excludeFields": [ "updated_at", "created_at", "attribute_set_id", "status", "visibility", "tier_prices", "options_container",
 "url_key", "msrp_display_actual_price_type", "has_options", "stock.manage_stock", "stock.use_config_min_qty", "stock.use_config_notif
y_stock_qty", "stock.stock_id",  "stock.use_config_backorders", "stock.use_config_enable_qty_inc", "stock.enable_qty_increments", "sto
ck.use_config_manage_stock", "stock.use_config_min_sale_qty", "stock.notify_stock_qty", "stock.use_config_max_sale_qty", "stock.use_co
nfig_max_sale_qty", "stock.qty_increments", "small_image"],
        "includeFields": null
      }
    },
    "cart": {
      "server_merge_by_default": true,
      "synchronize": true,
      "synchronize_totals": true,
      "setCustomProductOptions": true,
      "setConfigurableProductOptions": true,
      "create_endpoint": "http://localhost:8080/api/cart/create?token={{token}}",
      "updateitem_endpoint": "http://localhost:8080/api/cart/update?token={{token}}&cartId={{cartId}}",
      "deleteitem_endpoint": "http://localhost:8080/api/cart/delete?token={{token}}&cartId={{cartId}}",
      "pull_endpoint": "http://localhost:8080/api/cart/pull?token={{token}}&cartId={{cartId}}",
      "totals_endpoint": "http://localhost:8080/api/cart/totals?token={{token}}&cartId={{cartId}}",
      "paymentmethods_endpoint": "http://localhost:8080/api/cart/payment-methods?token={{token}}&cartId={{cartId}}",
      "shippingmethods_endpoint": "http://localhost:8080/api/cart/shipping-methods?token={{token}}&cartId={{cartId}}",
      "shippinginfo_endpoint": "http://localhost:8080/api/cart/shipping-information?token={{token}}&cartId={{cartId}}",
      "collecttotals_endpoint": "http://localhost:8080/api/cart/collect-totals?token={{token}}&cartId={{cartId}}",
      "deletecoupon_endpoint": "http://localhost:8080/api/cart/delete-coupon?token={{token}}&cartId={{cartId}}",
      "applycoupon_endpoint": "http://localhost:8080/api/cart/apply-coupon?token={{token}}&cartId={{cartId}}&coupon={{coupon}}"
    },
    "products": {
      "configurableChildrenStockPrefetchStatic": false,
      "configurableChildrenStockPrefetchDynamic": false,
      "configurableChildrenStockPrefetchStaticPrefetchCount": 8,
      "filterUnavailableVariants": false,
      "preventConfigurableChildrenDirectAccess": true,
      "alwaysSyncPlatformPricesOver": false,
      "clearPricesBeforePlatformSync": false,
      "waitForPlatformSync": false,
      "setupVariantByAttributeCode": true,
      "endpoint": "http://localhost:8080/api/product",
      "defaultFilters": ["color", "size", "price", "erin_recommends"],
      "galleryVariantsGroupAttribute": "color"
    },
    "orders": {
      "endpoint": "http://localhost:8080/api/order",
      "payment_methods_mapping": {
      }
    },
    "users": {
      "autoRefreshTokens": true,
      "endpoint": "http://localhost:8080/api/user",
      "history_endpoint": "http://localhost:8080/api/user/order-history?token={{token}}",
      "resetPassword_endpoint": "http://localhost:8080/api/user/resetPassword",
      "changePassword_endpoint": "http://localhost:8080/api/user/changePassword?token={{token}}",
      "login_endpoint": "http://localhost:8080/api/user/login",
      "create_endpoint": "http://localhost:8080/api/user/create",
      "me_endpoint": "http://localhost:8080/api/user/me?token={{token}}",
      "refresh_endpoint": "http://localhost:8080/api/user/refresh"
    },
    "stock": {
      "synchronize": true,
      "allowOutOfStockInCart": true,
      "endpoint": "http://localhost:8080/api/stock"
    },
    "images": {
      "baseUrl": "https://demo.vuestorefront.io/img/",
      "productPlaceholder": "/assets/placeholder.jpg"
    },
    "install": {
      "is_local_backend": true,
      "backend_dir": "../vue-storefront-api"
    },
    "demomode": true,
    "tax": {
      "defaultCountry": "PL",
      "defaultRegion": "",
      "calculateServerSide": true
    },
    "i18n": {
      "defaultCountry": "US",
      "defaultLanguage": "EN",
      "availableLocale": ["en-US","de-DE","fr-FR","es-ES","nl-NL", "jp-JP", "ru-RU", "it-IT", "pt-BR", "pl-PL"],
      "defaultLocale": "en-US",
      "currencyCode": "USD",
      "currencySign": "$",
      "dateFormat": "HH:mm D/M/YYYY",
      "fullCountryName": "United States",
      "fullLanguageName": "English"
    },
    "mailchimp": {
      "endpoint": "http://localhost:8080/api/ext/mailchimp-subscribe/subscribe"
    },
    "theme": "@vue-storefront/theme-default",
    "analytics": {
      "id": false
    },
    "stripe": {
      "api_key": "my_example_api_key"
  }
 }

**Comment by pkarw** [comment]
The config looks good at a first glance. Please let me know which exact requests go to the localhost? It may help me spot the problem.

Please also do confirm that after chaning the config you've restarted the app + cleared the browser storage?

**Comment by mingfang** [comment]
I'm seeing the same problem.

The exact urls are http://localhost:8080/api/cart/create?token=, and pretty much every api call.
Having to run build to change the url is not acceptable.
I build once and promote from dev to qa to prod with different config files and can't do another build.

**Comment by pkarw** [comment]
Thanks, so definitely we need to add the support of dynamic config variables via env

**Comment by mingfang** [comment]
The solution is to name the json file to be the same as NODE_ENV, e.g. if NODE_ENV=production then the config file should be production.json.

**Comment by pkarw** [comment]
It’s not he solution to have dynamic reloading. Currently to have it supported (node-config) by webpack we’re generating static json file. It was recommended solution by node-config authors but then as I’ve seen they came with some other options. Please just take a look at he options of integrating node-config with webpack apps

**Comment by pkarw** [comment]
@akbarik how about this one?

**Comment by pkarw** [comment]
@mdanilowicz if You havent started with this one I'll take it from there

**Comment by pkarw** [comment]
Now the config can be reloaded on-fly with each server request if `config.server.dynamicConfigReload` is set to true. However in that case the config is added to `window.__INITIAL_STATE__` with the responses.

**Comment by pkarw** [comment]
@NataliaTepluhina I just discovered that we missed this option in official docs (however it was pointed out in https://github.com/DivanteLtd/vue-storefront/blob/36989bdf9fc22726718493f93cfb4a13d9d72127/doc/Config%20docs.md) - can You update the docs please?
