### ISSUE TITLE
how to start vue-storefront and vue-storefront-api after installing

### ISSUE THREAD

**Issue by ismailyenigul** [DivanteLtd/vue-storefront#1291]
Hi

I installed vue-storefront and vue-storefront-api with yarn && yarn installer

when I reboot the server, how should I start it again? I do not see any information about this on documentation.  I simply run npm start on vue-storefront and vue-storefront-api directory.
But I am not sure whether this is propery way or not.

and Is there any stop command rather then kill ?

**Comment by pkarw** [comment]
Yes it’s correct way to start it. It’s just a Node app. We’re working on docker containers for VS and VS-api so it will surely simplify start/stop process
