### ISSUE TITLE
Error: render function or template not defined in component: GenericSelector

### ISSUE THREAD

**Issue by chetan-prime** [DivanteLtd/vue-storefront#1315]
I have updated to 1.05 to see if it would fix an issue with the products not displaying.
Now I can see the error in console, earlier 1.01 would give a "500 | Internal Server Error" but nothing on console.
I am using products I imported from magento2 using the mage2vuestorefront package. That imported fine with no errors. I'm able to open the category pages just fine and can see the products list along with thumbnail. However when I click on a product there is no response. When I open the product link in a New Tab , then it shows the "500 | Internal Server Error" 

Is there any configuration issue on my end?

[render_errors.log](https://github.com/DivanteLtd/vue-storefront/files/2114450/render_errors.log)

[javascript_errors_on_product_clicked.log](https://github.com/DivanteLtd/vue-storefront/files/2114469/javascript_errors_on_product_clicked.log)

**Comment by chetan-prime** [comment]
Looks like I need to change some of the hostnames from "localhost" in my local.json. That I'm changing but this is not connected to the product link opening error I mentioned above

**Comment by pkarw** [comment]
Please change the import path of GenericSelector from the `core/components/GenericSelector` to `theme/components/core/GenericSelector` in your theme
