### ISSUE TITLE
Add critical CSS to <head> via webpack plugin

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#133]
It would be nice if we add critical CSS inlined in `<head>` to speed up page rendering.

Here is a webpack plugin we can use to easly achieve it: https://www.npmjs.com/package/webpack-plugin-critical

**Comment by pkarw** [comment]
@Aekal could you please take this one?

**Comment by filrak** [comment]
I can't figure out why it doesn't work but https://github.com/vuejs/vue/issues/6602  could be related to this, for now I'm moving it to 0.4 and will try to find why it doesn't work when more important issues are done

**Comment by cartok** [comment]
It should work with the bundle renderer out of the box, when we give it the template in it's options. I tried it in our VSF project (as as string) but unfortunately without the expected results.

The SSR Docs say:
```
Automatic critical CSS when using bundleRenderer.

If used during a server render, a component's CSS can be collected and inlined in the HTML (automatically handled when using template option). On the client, when the component is used for the first time, vue-style-loader will check if there is already server-inlined CSS for this component - if not, the CSS will be dynamically injected via a <style> tag.
```
https://ssr.vuejs.org/guide/css.html#enabling-css-extraction
The extraction article seems outdated though.

My current workaround is to manually create a list of all critical components and use a extra loader configuration (via oneOf) on scss where I extract it to a file using mini-css-extract-plugin.

The CSS then gets bundled by optimization.splitChunks.cacheGroups with a callback as test that also checks on that list.
