### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by leon0v** [DivanteLtd/vue-storefront#1333]
I ran a [Lighthouse](https://developers.google.com/web/tools/lighthouse/) audit on the default PWA. 1 failing audit is that the app doesn't use HTTP/2. I get that it's not necessary, but what would be the best way to implement this?

**Comment by pkarw** [comment]
we're using http2 on the https://demo.vuestorefront.io (nginx level). http2 is just experimentally supported by the nodejs so that's the reason we don't support it directly in the app
