### ISSUE TITLE
Please configure product custom options and fix the validation errors

### ISSUE THREAD

**Issue by chetan-prime** [DivanteLtd/vue-storefront#1334]
I have vuestore configured along with products imported via mage2vuestorefront .
This is magento2 for a optical vision store, so each product has custom options like "Right-sphere" , "Left-sphere" etc. which user has to specify power etc. before selecting an item. In M2 it shows the dropdown for each option.

However in vue-storefront I can see the default options like size, color etc., but all the custom options show these errors at the top - "Please configure product custom options and fix the validation errors.", and next to each field name I see the below error - "Field is required." , with no dropdown to select the power etc.

I was unable to find anything in the previous issues regarding this, so I have opened as a new issue.

![berlin1](https://user-images.githubusercontent.com/5426103/41764736-abad18be-761f-11e8-87b2-165684176d84.png)
![berlin2](https://user-images.githubusercontent.com/5426103/41764737-abf25d84-761f-11e8-8705-edb60b13dd0e.png)

**Comment by pkarw** [comment]
Hi! Thanks for this issue! We're currently supporting just a basic types of the configurable options:
https://github.com/DivanteLtd/vue-storefront/blob/master/core/components/ProductCustomOptions.js

https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/components/core/ProductCustomOptions.vue

It seems like Your options types differs from "radio", "select" neither "checkbox". 
So You probably should extend this feature a little bit for Your case

**Comment by chetan-prime** [comment]
Thanks, for some reason github took 20 hours your reply to be visible on my end.
I can see in the code that "select" dropdowns don't seem to be covered. Will attempt to change the code on my end and send a PR in when I get it to work with default theme

**Comment by chetan-prime** [comment]
This is a simplistic patch for the default theme that enables support for "drop_down" custom options. This is apparently different from "select" which the theme already has code for.
In this patch had elected to use a custom ProductOptions.js within the theme itself.
This is mainly for the reference of anyone else who faced problems with their "drop_down" product options.

[1.05-productoptions-patch.txt](https://github.com/DivanteLtd/vue-storefront/files/2130753/1.05-productoptions-patch.txt)

**Comment by pkarw** [comment]
Cool! How about including this change in the core? Would be great if you will be willing to test it a little bit and send us a Pull Requst?

**Comment by pkarw** [comment]
@chetan-prime let me know what do you think about it?

**Comment by chetan-prime** [comment]
Sure, will do a PR in a day or two. I am checking on my end for the correct vue classes to use to make the select look better
