### ISSUE TITLE
Thank You Page improvements

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1351]
- text layout
- remove Notification button on iPhone
![2bc080a7-dfa5-4127-ac9f-fa49ce15de80](https://user-images.githubusercontent.com/211899/41806276-06514b8c-76bb-11e8-9633-8376f4c3b7e5.png)
![ba15df21-fc6a-4125-896f-49d321eded1c](https://user-images.githubusercontent.com/211899/41806277-067965ae-76bb-11e8-9b75-a4abbca1a57b.png)

**Comment by pkarw** [comment]
@filrak and the UI improvements?

**Comment by MatWaligora** [comment]
Added a PR with UI improvements:

https://github.com/DivanteLtd/vue-storefront/pull/1501
