### ISSUE TITLE
Develop branch doesn't work

### ISSUE THREAD

**Issue by szafran89** [DivanteLtd/vue-storefront#1357]
Please check latest version of develop

![image](https://user-images.githubusercontent.com/5370251/41853542-4b9d7164-788e-11e8-943b-2259b730cb91.png)

**Comment by pkarw** [comment]
It seems like it stopped to work after the last commits from Saturday. I've got a version from the end of the Friday and it's fine. From the message from @szafran89 it seems like it maybe somehow connected to 
https://github.com/DivanteLtd/vue-storefront/commit/1f569054b73d9412e934fe25985c41e70026b66b

I'm not sure if mixins shouldn't have been a array (in this commit it's an object)

**Comment by filrak** [comment]
My fault, mixins should be an Array. I must admit im an idiot :x
