### ISSUE TITLE
Automated tests with Gherkin, Cucumber and Puppeteer

### ISSUE THREAD

**Issue by kyvaith** [DivanteLtd/vue-storefront#1364]
Another proposal. Please look at this article on Medium: https://medium.com/@anephenix/end-to-end-testing-single-page-apps-and-node-js-apis-with-cucumber-js-and-puppeteer-ad5a519ace0

This looks cool and modern. Gherkin simplifies a way to write automated test, using high-level speakeen language to define steps and tests.

**Comment by pkarw** [comment]
We've started the e2e tests initiative using cypress and probably won't like to change the framework for a while https://github.com/DivanteLtd/vue-storefront/tree/develop/cypress/integration
