### ISSUE TITLE
Products not displayed on storefront (Home/Catalog etc).

### ISSUE THREAD

**Issue by dimasch** [DivanteLtd/vue-storefront#137]
Product not displayed on storefront (Home/Catalog etc).

Issues with retrieve catalog of products from ES on storefront. See illegal_argument_exception in chrome console.

![2017-10-20_22-36-16](https://user-images.githubusercontent.com/414067/31837606-83d876e4-b5ea-11e7-8311-b677429633e1.png)

`Error: {"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [created_at] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"vue_storefront_catalog","node":"7NJgUxmQTLSF-IFOLsGdaw","reason":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [created_at] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}]}`

**Comment by pkarw** [comment]
We need to have schema setup in `npm run restore`
This problem will be fixed after `npm run migrate` becuase one of the migrations sets up proper data types:

```
common.db.indices.putMapping({
        index: newIndexVersion,
        type: "product",
        body: {
          properties: {
            size: { type: "integer" },
            price: { type: "double" },
            color: { type: "integer" },
            pattern: { type: "integer" },
            id: { type: "integer" },
            status: { type: "integer" },
            weight: { type: "integer" },
            visibility: { type: "integer" },
            created_at: { 
              type: "date",           
              format: "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
            },
            updated_at: { 
              type: "date",           
              format: "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
            },
            description: { type: "text" },
            name: { type: "text" },
          }
        }
      }).then((res) => {

```

**Comment by pkarw** [comment]
@dimasch Dima, please do confirm if run migrate solves this issue? I've added suggestion to run this command to installation procedure as for now

**Comment by dimasch** [comment]
@pkarw Piotr, thx. Unfortunately no...  But possible in my case to reproduse.

I reinstall vue-storefront-api newly with additional step with  run migrate:

- docker-compose up
- npm run migrate  (Additional step)
- npm run restore

Accordance by
[https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Installing%20on%20Linux%20and%20MacOS.md](url)

And i install without the datapump from magento https://github.com/DivanteLtd/mage2nosql 
Can it affect?

My nodejs version v8.7.0 lstest (not v8.3.0  like in installation docs).
Can it affect?

Thank you!

**Comment by pkarw** [comment]
@dimasch still the same error (about created_at)? I used the opposite sequence:
‘’’
npm run restore
npm run migrate
‘’’

But it shouldn’t make any difference. But maybe it does?;)

As for now you can change the elastic query in Home.vue to disable sorting by created_at field

Newer nodejs doesn’t make difference here

Does mage2nosql works for you?

**Comment by dimasch** [comment]
@pkarw Yes, the same error about created_at. 

Yes, correct sequence:
npm run restore
npm run migrate

And i remove sorting for some views (Home.vue etc), and work fine. Is hipster hack) But I would like to fix the migration.

Today i check with mage2nosql. Now install clear m2 (ce 2.1.9). 
I notify about results.

**Comment by pkarw** [comment]
OK! The solution with removing sorting field is a little bit creepy :) So maybe would You like to take a look at it?
The issue is that index should have correct structutre. It's the following one:

```
common.db.indices.putMapping({
        index: newIndexVersion,
        type: "product",
        body: {
          properties: {
            size: { type: "integer" },
            price: { type: "double" },
            color: { type: "integer" },
            pattern: { type: "integer" },
            id: { type: "integer" },
            status: { type: "integer" },
            weight: { type: "integer" },
            visibility: { type: "integer" },
            created_at: { 
              type: "date",           
              format: "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
            },
            updated_at: { 
              type: "date",           
              format: "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
            },
            description: { type: "text" },
            name: { type: "text" },
          }
        }
      }).then((res) => {
```

as described in `src/migrations/1507147503759-change-size-color.js`

**Comment by pkarw** [comment]
Could you also paste an output from 'npm run migrate'?

**Comment by pkarw** [comment]
Would be great if you could create kind of installer for Elastic which creates the schema and then executes restore command for importing initial data dump.

If we can have something like `npm run setup` or `npm run install` to perform such 2 operations it would be very very apreciated! :)

**Comment by dimasch** [comment]
> Could you also paste an output from 'npm run migrate'?

Ready output:
[npm-run-migrate.log](https://github.com/DivanteLtd/vue-storefront/files/1403867/npm-run-migrate.log)

**Comment by dimasch** [comment]
@pkarw 
> If we can have something like npm run setup or npm run install to perform such 2 operations it would be very very apreciated!

Nice idea! :)

**Comment by dimasch** [comment]
@pkarw 

Try mage2nosql to sync from m2

![2017-10-21_11-19-45](https://user-images.githubusercontent.com/414067/31849330-f714e1da-b651-11e7-91c1-6a194bbbfa4f.png)

**Comment by dimasch** [comment]
See null in .migrate (vue-storefront-api repo)

![2017-10-21_12-51-58](https://user-images.githubusercontent.com/414067/31850136-bc02c08c-b65e-11e7-8c21-a0352cd04626.png)

**Comment by dimasch** [comment]
I fix on localy. This is only doc issue.

1) After run migrate need go to ES head [https://github.com/mobz/elasticsearch-head](url)
and check applyed type for "Fields" 
![2017-10-21_21-26-54](https://user-images.githubusercontent.com/414067/31854264-e6c0a95e-b6a6-11e7-9840-7d5baabef157.png)

2) Copy actual ES (ElasticSearch) index id:
![2017-10-21_21-31-28](https://user-images.githubusercontent.com/414067/31854293-4f92d998-b6a7-11e7-8dc0-b43c7ef4f2c1.png)

3) Update ES index with use coped value for all configs for certain sections
`vue-storefront/src/config.js
vue-storefront-api/src/config.json`

4) Very cool result!  We see products on home page and catalog!
![2017-10-21_21-21-10](https://user-images.githubusercontent.com/414067/31854281-1d8a04b2-b6a7-11e7-8a9f-d427682ed3c2.png)

**Comment by dimasch** [comment]
@pkarw Piotr, thx, we can close this issue. And update docs.

**Comment by pkarw** [comment]
Thanks for the investigation. It seems like the last step of migration - updating alias for this fresh index hasn’t succeed :/ 

Anyway would be great to prepare an installer. Let keep it open ;)


ps. If you setup image proxy in config.js to https://demo.vuestorefront.io/img it should start showing pictures on product lists

**Comment by pkarw** [comment]
@dimasch could you retest and close the issue after https://github.com/DivanteLtd/vue-storefront-api/pull/4 ?

**Comment by dimasch** [comment]
I retest this two weeks ago - it's works fine!  Today i retest again and feedback you.

**Comment by pkarw** [comment]
thx

**Comment by Chiragsorathiya** [comment]
I have the same problem can you help me?
