### ISSUE TITLE
Wrong validation for Zip-code field.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#1372]
1.  Log in into Vuestorefront
2. Go to My Account→ My shipping details
3. Edit your shipping details
4. Type three letters into Zip-code and try to save changes

**Actual results:**
Wrong validation.
![image](https://user-images.githubusercontent.com/36628922/41968554-1458f200-7a05-11e8-946f-0d1fe4f410fd.png)

**Expected:**
It should be possible saving three letters or notification should be changed (for example "Zip-code must have at least 5 signs"

**Comment by ibugaj** [comment]
@pkarw Could you reopen this issue?
I find new place where Zip-code is valid, even when user provided 4 letter, see:
![image](https://user-images.githubusercontent.com/47220013/52233151-a645cb80-28be-11e9-9e53-14b18d01f99d.png)

It is for logged user, when user edit **My profil** - _/my-account_ page

Tested on https://test.storefrontcloud.io

**Comment by pkarw** [comment]
@ibugaj thanks
