### ISSUE TITLE
Category component doesn't contain data about category description and category image

### ISSUE THREAD

**Issue by mishanino** [DivanteLtd/vue-storefront#1383]
We use the latest versions of vue-storefront and vue-storefront-api from master branch, but we can't to get data from component or from vuex about category description and category image.
Magento Admin Dashboard: 
![image](https://user-images.githubusercontent.com/4930295/42033932-1bfc939e-7ae7-11e8-9f33-0793e6f31471.png)

Vue Storefront Component Data: 
![image](https://user-images.githubusercontent.com/4930295/42034080-95d418a4-7ae7-11e8-9dd2-e7aa1803afdc.png)
Vue Storefront Vues Data
![image](https://user-images.githubusercontent.com/4930295/42034120-adb030ac-7ae7-11e8-83ad-2ec514a17a04.png)

**Comment by mishanino** [comment]
take a look at config/local.json (vue-storefront) entites section
add the fields to the includeFields
and restart yarn dev

**Comment by mishanino** [comment]
@pkarw, it doesn't work anymore (VS 1.5), I added "description" and "short_description" in the local.json
`"category": {
        "includeFields": [ "children_data", "description", "short_description", "id", "children_count", "sku", "name", "is_active", "parent_id", "level", "url_key", "product_count", "path"]
      }`
but I don't see this data in component or in vuex

**Comment by pkarw** [comment]
You probably need to run the category importer with `--extendCategories=true`: 
https://github.com/DivanteLtd/mage2vuestorefront/blob/master/src/test_categoryextended.sh

**Comment by mishanino** [comment]
@pkarw, thank you, will try

**Comment by zukilover** [comment]
> You probably need to run the category importer with `--extendCategories=true`:
> https://github.com/DivanteLtd/mage2vuestorefront/blob/master/src/test_categoryextended.sh

Hi @pkarw , is there any similar approach for VSFBridgeIndexer?

**Comment by upandfine** [comment]
Can confirm the leak with too little memory. Unfortunately, no error message is displayed!
