### ISSUE TITLE
URGENT: vue-carousel isn't compilant with SSR

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#139]
Patryk, i've just added SSR support and vue-carousel stoped to work regarding: https://github.com/SSENSE/vue-carousel/issues/31

I've added 'no-ssr' component to work around and right now site is working BUT the slider is loading with all the slides expanded. Need to be fixed - visually or by chaning the component

**Comment by pkarw** [comment]
@filrak @patrykpiston in case of issues after pulling the code from repo - please do clear local storage (because service worker is caching locally index.html)

**Comment by patrykpiston** [comment]
Thank you, I will see the problem tomorrow asap

**Comment by patrykpiston** [comment]
@pkarw I will try to look for an SSR compliant plugin/solution, if I won't find anything than I will rewrite the carousel without a library to make sure it works.

**Comment by pkarw** [comment]
@patrykpiston I see that slider on HP currently works like it probably should; what's here more to do ?

**Comment by patrykpiston** [comment]
@pkarw I think we can close it if it doesn't produce any errors. What do you think? Rewriting it can be assigned as an optional improvement.
