### ISSUE TITLE
Fix the SearchPanel query

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1395]
Currently, the search breaks on such cases:
- doesn't search for products by "sku"
- uses OR operator (probably needs to use AND) -> https://www.dropbox.com/s/48vf4dlqlrduwg6/Screenshot%202018-06-29%2016.08.13.png?dl=0
- doesn't support fuzzy/partial searches (https://www.dropbox.com/s/hq2xmeioxbtiy5t/Screenshot%202018-06-29%2016.08.43.png?dl=0)

Would be great if somebody could take care of the search query and tweak it a little bit:
https://github.com/DivanteLtd/vue-storefront/blob/e5e45da1d767cd02500d5cba85d900139ff44b06/core/components/blocks/SearchPanel/SearchPanel.js#L39

**Comment by Altamash-s-s** [comment]
currently it search only with product name but i want it search with color and other attribute also
can you please ??
