### ISSUE TITLE
Create webpack alias for components refering to theme they are located in

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#14]
It would be much more elegant and easier to understand and wirte if components in themes can be refered to their path via simple alias e.g "theme/components" being alias for theme's root like "components" now is an alias for base components root

**Comment by pkarw** [comment]
OK, so I've just added following alliases - please inform me if it works as it should for you:

      theme_pages: path.resolve(__dirname, '../themes/default/pages'),
      theme_components: path.resolve(__dirname, '../themes/default/components'),
      'components': path.resolve(__dirname, '../themes/default/components'),
      'pages': path.resolve(__dirname, '../themes/default/pages')

**Comment by pkarw** [comment]
@filrak if it works' jsut fine - please close the ticket

**Comment by filrak** [comment]
@pkarw it works! ;)
