### ISSUE TITLE
There is no menu option on the mobile device that redirects to the "Compare Products" site.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#1406]
1. Visit Vuestorefront on your mobile phone
2. Choose any products
3. Add to compare
4. Go to Compare Products

**Actual results:**
There is nowhere Product comparison site.

**Expected results:**
There should be "Compare Products" option in hamburger menu or some icon in the header of the page redirecting to Product comparison.

**Comment by pkarw** [comment]
@StasiekDivante please propose how this option should look like

**Comment by StasiekDivante** [comment]
<img width="360" alt="sidebar menu on mobile" src="https://user-images.githubusercontent.com/37068687/42681516-33e70e24-8688-11e8-94fd-a8c6228d5706.png">
Let's just add compare products link in sliding menu
