### ISSUE TITLE
Search results don't match entered query.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#1408]
1. Visit Vuestorefront 
2. Click on Search icon
3. Type "SALE" and look at the results
4. Now clear field and type "NEW" and also look at the results

**Actual results:**
After step 3 there are products with "SALE" label (ok).
After step 4 - results include products that don't match the search query (-).
![image](https://user-images.githubusercontent.com/36628922/42222181-a38d7fbc-7ed4-11e8-9258-7b8d2853167b.png)

**Expected results:**
Search results should only display products that match the search query.

**Comment by qiqqq** [comment]
After analysis this issue with @alinadivante we decided that this queries works ok so we decided to close this issue.
