### ISSUE TITLE
After marking and unmarking the checkbox the hover effect remains on it.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#1415]
1. Visit Vuestorefront 
2. Open any category
3. In Price column mark a checkbox
4. Unmark the same checkbox

**Actual results:**
Hover effect remains on unmarked checkbox.
![image](https://user-images.githubusercontent.com/36628922/42317771-702ebf62-804d-11e8-9fc7-4ece8831474a.png)

**Expected results:**
Hover effect should disappear if mouse cursor is not on the checkbox.

**Comment by mdanilowicz** [comment]
Fixed in #1424
