### ISSUE TITLE
In Gear category, the filter contains only a black color, despite the products available in different colors.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#1416]
1. Visit the Vuestorefront
2. Go to the Hardware category
3. Check the available colors in the filter

**Current results:**
There is only a black color, although there are products of different colors.
![image](https://user-images.githubusercontent.com/36628922/42318419-4012e982-804f-11e8-9f5f-97d4b68fbbeb.png)
![image](https://user-images.githubusercontent.com/36628922/42318431-4c25041c-804f-11e8-84f3-73cf940d4262.png)

**Expected results:**
More colors should be available in the filter.

**Comment by pkarw** [comment]
Fixed!
