### ISSUE TITLE
After changing application language all products disapper from cart and wishlist

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#1417]
1. Log in into the Vuestorefront
2. Add some products to cart and wishlist
3. Change the application language (click on US/EN/USD and Choose your country)
4. Check your cart

**Current results:**
After changing application language all products disapper from cart and wishlist

**Expected results:**
There should be the same products that were added before changing the language

**Comment by pkarw** [comment]
This is an intentional behavior. I'm not sure about mixing the content from 2 shops (prices, currency, order routing ...). Well, I can of course add this option (like keeping the carts as an configuration option).

It's just a prefix-issue for the localStorage current-cart collection

**Comment by valmedia** [comment]
Will it be able to auto convert the item to a linked item for given language?
