### ISSUE TITLE
Password rules not alligned

### ISSUE THREAD

**Issue by frankgrupe** [DivanteLtd/vue-storefront#1420]
Tried demo.vuestorefront.io from mobile:
1. added items to cart
2. registered with password "test1234"
3. gone through checkout
4. confirming the order I get a password error and cannot "easily" correct it (see
![screenshot_20180707-082839_chrome](https://user-images.githubusercontent.com/40632569/42449308-6aa86314-8380-11e8-8190-cc74b87482a3.jpg)
)

Password rules should be the same throughout the entire experience.

**Comment by pkarw** [comment]
Thanks! 

Just a short question to let us reproduce this issue: Have You clicked "login to your account" in the checkout? I've just tested this path and got this kind of error immediately in the "Register" form - not being able to go to "place an order" step (which is desired flow).

I'm just trying to localize the form that passed You to the checkout :)

**Comment by frankgrupe** [comment]
I ticked "I want to create an account" on the way to checkout and entered the password "test1234" there twice.

**Comment by pkarw** [comment]
Thanks! Now it's clear.

I think we should do two things:

1). Adjust our form validation to the backend validation rules (exactly as described in the err. msg)
2).  As this is a separate rest call - we can handle the errors in a more sophisticated/use-friendly way. In case of the `user/register` error, we should scroll the screen up and set the focus to the `password` field, to make it easier to fix the issue for the user. 

After applying the 1) probably the 2) will be very rare - and possibly it will be just for some other/general API errors. Anyway, it's worth applying both fixes to the problem.

@akbarik a You were in charge of this feature initially, could You please take care of that one?

@frankgrupe thanks for finding this issue! :)

**Comment by akbarik** [comment]
Yes, @pkarw, I'm taking it

**Comment by pkarw** [comment]
@akbarik could You just let me know about the status in here
