### ISSUE TITLE
Dublicated rows in Indexed DB for CMS extension

### ISSUE THREAD

**Issue by dimasch** [DivanteLtd/vue-storefront#1428]
The includes work only for simple array `['cat', 'etc']` But in CMS blocs using `[{id: '', identifier: ''}, {...}]`
https://github.com/DivanteLtd/vue-storefront/blob/f8035412705c0449783bf7441cbf560822ff7677/src/extensions/cms/store.js#L45

I check fix:
```
if (!state.cmsBlock.filter(e => e.id === data.id).length > 0) {
```

**Comment by pkarw** [comment]
@anqaka coult You take a look at this?
