### ISSUE TITLE
The product page shows incorrect related products until you refresh page

### ISSUE THREAD

**Issue by mishanino** [DivanteLtd/vue-storefront#1429]
The product page shows incorrect related products untill you refresh page

**Steps to reproduce:**
1) go to the product page https://demo.vuestorefront.io/p/WS10/karissa-v-neck-tee-1529/WS10
2) go to the "Similar products" section and click to the 4th product
![image](https://user-images.githubusercontent.com/4930295/42825374-8e2c335e-89ea-11e8-82e6-0cab81937774.png)
3) go to the "Similar products", you can see related products for previous product
![image](https://user-images.githubusercontent.com/4930295/42825374-8e2c335e-89ea-11e8-82e6-0cab81937774.png)
4) refresh page and you will see correct related products 
![image](https://user-images.githubusercontent.com/4930295/42825499-cdea6e48-89ea-11e8-8907-05fc53a983d8.png)

**Comment by pkarw** [comment]
This is the expected behavior as we’re just reloading the product data without related information. However we could easily fix it within the theme - the solution may be to use a event in the Related component to refresh the data or to use <a href... instead of <router-links to address the related products (which is not recommended)

**Comment by mishanino** [comment]
@pkarw, how can I easily to get related item url for <a href, because seems localizedRoute wokrs only for router-link and url_key is empty in component?

**Comment by pkarw** [comment]
Hi mishanino, what do You mean? Could You paste Your code to letm e better understand the problem?

**Comment by mishanino** [comment]
@pkarw you wrote that "to use <a href... instead of <router-links to" but localizedRoute don't working for <a> element
`<a
    class="mr5 mb5 bg-cl-transparent brdr-1 brdr-circle brdr-cl-transparent :brdr-cl-bg-primary relative inline-flex pointer color border-box"
    :href="localizedRoute({
      name: product.type_id + '-product',
      params: {
        parentSku: product.parentSku ? product.parentSku : product.sku,
        slug: product.slug,
        childSku: product.sku
      }
    })"
  >`
![image](https://user-images.githubusercontent.com/4930295/43083448-393dcfe2-8e9f-11e8-8a7e-69d72c5cbc35.png)
I tried to found product url in the component data, but url keys are empty
![image](https://user-images.githubusercontent.com/4930295/43083554-75809e26-8e9f-11e8-80d1-e5e5236113f5.png)

**Comment by pkarw** [comment]
Hi!

localizedRoute returns an object which unfortunatelly is not compilant with the href property. The method has the second mode - working on strings

Please try to use sth like this:
```html
        <p><a :href="localizedRoute('/p/' + product.sku + '/' + product.slug +'/' + product.sku)">Product Page</a></p>
```

**Comment by mishanino** [comment]
@pkarw Hello, thank you, it is working
