### ISSUE TITLE
VS frontend crashing multiple times a day in production

### ISSUE THREAD

**Issue by Tjitse-E** [DivanteLtd/vue-storefront#1431]
I'm running Vue Storefront 1.1, deployed on a server, with Elastic and Redis, not using docker. I'm using Nagios to check if both the API and the frontend are up. I've noticed that the frontend is crashing multiple times a day. This actually causes a few minutes of downtime multiple times a day. 

I'm building the frontend like this, using PM2:
```
yarn build
yarn start
```

What triggers a frontend rebuild? Any ideas why the fronted would rebuild multiple times a day?

![slack_-_vendic-2](https://user-images.githubusercontent.com/14849044/42869284-e9444b66-8a74-11e8-92e9-baad27b709a5.png)

**Comment by pkarw** [comment]
This is stange. None of these commands is running the build process. Are you shure it's rebuilding or restarting (significant difference) ;)

**Comment by Tjitse-E** [comment]
Ok i've doubled the ES memory to 8GB, let's see if that solves the issue.

**Comment by pkarw** [comment]
Probably sth around 16GB would be safe; but please just let me know if it helped

**Comment by Tjitse-E** [comment]
We've just doubled the memory again to 16GB now, hopefully this will help.

**Comment by pkarw** [comment]
OK, let me know how it was after such a change

**Comment by Tjitse-E** [comment]
We've increased the elastic size to 16GB but this didn't help, the frontend is still crashing multiple times per day. After a view minutes it's back online. Elastic is functioning as normal (no entries in the logs), and `pm2 log` also returns nothing special.

@pkarw can you re-open this issue?

**Comment by kosirm** [comment]
Hi, I'm totally new to VS and this thread scares me a bit... @Tjitse-E could you confirm that problem is solved permanently? Could you explain for a beginner what are concrete steps to solve such a problem? @pkarw  I would like to know what is recommended server specification for Magento + VS to work properly (for middle size store, let say 1000 products)? Because if I need 16 GB of RAM only for ElasticSearch, how much do I need for everything together?
Thanks for any reply.

**Comment by Tjitse-E** [comment]
@kosirm this was just a PM2 issue, nothing to do with vue storefront. This is the ecosystem.json config that we're currently using for the frontend:
```
{
  "apps": [
    {
      "name": "frontend",
      "max_memory_restart": "1G",
      "instances": "2",
      "exec_mode": "cluster",
      "script": "./core/scripts/server.js",
      "node_args": "--max_old_space_size=1024",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "ignore_watch": [
        "core/build/config.json",
        "node_modules"
      ]
    }
  ]
}
```

**Comment by kosirm** [comment]
@Tjitse-E Thanks for your time and explanation!

**Comment by dennisotugo** [comment]
@Tjitse-E Is it still crashing?

**Comment by Tjitse-E** [comment]
@dennisotugo no everything is running fine here.
@pkarw cool feature, i'll have a look!
