### ISSUE TITLE
Vue Storefront Setup - #02 Technical Webcast video update (https://www.youtube.com/watch?v=M6lXVZUfnR8))

### ISSUE THREAD

**Issue by dare-adewole** [DivanteLtd/vue-storefront#1432]
[](https://www.youtube.com/watch?v=M6lXVZUfnR8)

**Comment by pkarw** [comment]
Updated: https://youtu.be/iyOL_31BD4A?t=2m4s

**Comment by dare-adewole** [comment]
Dear Piotr,

Confirmed. Thanks for the Notification.
Awesome work you guys are doing.

Best Regards,
Dare McAdewole.
