### ISSUE TITLE
[ Cart ] Add coupon functionalities to cart module

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1433]
Read before picking:
- [About modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) - explaination, structure, motivations behind modules
- [Refactoring plan for modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/refactoring-to-modules.md)

Currently our Core Cart Module contains Microcart and Cart items behavior (mostly from `Microcart.js and `Microcart/Product.js'. Now it's time to extend it with coupon functilnalities.

**What should be done**
- [ ] Coupon functionalities should be moved to `core/api/cart` module
- [ ] Moved functionalities used in core components should now use core API Module (you can see similar examples of what I did in `Microcart.js` and `Microcart/Product.js` with `addToCart', `removeFromCart` etc.)
- [ ] New methods should be unit tested (like other methods in cart module)
- [ ] Every exported modules should be properly commented for Intelisense (see Cart module as example)
- [ ] Create docs file (see example https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/cart.md)

Proposed functionalities to move (ofc I'm open to discussion if you have better ideas)
- `applyCoupon(code)` - will dispatch `cart/applyCoupon` Vuex action and inform if it failed or succeeded via event (notification should be removed from core Vuex action and moved to default theme)
- `removeCoupon`- will dispatch `cart/removeCoupon` Vuex action

**Optional**
- [ ] Feature request for `getAppliedCoupon` method that will return at least coupons code and  provided discount. It's probably somewhere in cart totals so ideally should be extracted to cart vuex store. If the person that will take this issue is not willing to add this feature i will make another issue for it ;)

The task includes rewriting all core components and pages parts that are using this functions to use core modules.

Read more about modules: https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md

**Comment by mercs600** [comment]
@BartoszLiburski are you working on it ? I can handle it.

**Comment by BartoszLiburski** [comment]
@mercs600 no I am not. You can give it a shot!
