### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1437]
We're supporting all the modern browsers but seemingly the IE11 still got some issues with Vue Storefront. We're looking forward for somebody to test it out and fix the major IE11 errors.

**Comment by kjugi** [comment]
I've just seen you are using VueCarousel here to sliders. Unfortunately, it's not supported in IE11 and they have still opened an issue on GH here: https://github.com/SSENSE/vue-carousel/issues/190
TLDR;
They need to add polyfill - array.prototype.includes()
The worst information here is an empty gallery in the product page

**Comment by kjugi** [comment]
If this PR: https://github.com/SSENSE/vue-carousel/pull/266 will be merged and released we can update lib in our `package.json` and sliders in vue-storefron should working fine. But dunno when and if it will be done.

**Comment by bookernath** [comment]
The PR you mentioned is merged now, @kjugi

**Comment by kjugi** [comment]
It's merged and released but I think it's still old version in `package.json` in this repo. Need to update it min. to `0.12.0`

**Comment by bonfinnk** [comment]
IE11 is still not working.

**Comment by ChristopherMally** [comment]
This issue still exists. There is no running version of it for IE11. Are there any libs which can help polyfilling?

**Comment by lfritsche** [comment]
Hi together, hi @pkarw 

I've seen that you dropped IE11 support in the package.json officially from 1.10.1 and upwards.
As you are focusing on stability and maintainability of VSF 1 - are you planning to reenable IE11 support, or is this something you would like to have the community to work on? #hackathon

**Comment by clinton-origin** [comment]
I would like to add that not having IE11 support is pretty poor. I know only 2% of people use this but from looking at one of my sites that's still over 2000 customers not been able to shop. For a so-called production-ready system this isn't great and going to make it really difficult for agencies like myself to support it. 

Does anyone have a list of how many modules are broken in IE?

I started on it hoping for a quick fix but stopped after about 4, they were:

Proxy-polyfill : problems with special chars
query-string: => problem
strict-uri-encode: same as above
vue-offline: I can see someone made a start on it but it's in the core.


@lfritsche @pkarw

**Comment by pkarw** [comment]
Unfortunately, we as a core team, are not able to invest our focus and resources into IE11 anymore. We're focused on VSF 1.12, 1.13 and VSF-next instead and we believe it will bring more value to the humanity ;P Any contributions regarding IE11 welcomed (of course if they won't break the UX or performance for non-IE users). Thanks!

**Comment by clinton-origin** [comment]
"Unfortunately, we as a core team, are not able to invest our focus and resources into IE11 anymore. We're focused on VSF 1.12, 1.13 and VSF-next instead and we believe it will bring more value to the humanity ;P Any contributions regarding IE11 welcomed (of course if they won't break the UX or performance for non-IE users). Thanks!"
