### ISSUE TITLE
Untranslated content in 'Payment method' section.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#1443]
1. Login into Vuestorefront
2. Add something to the cart
3. Go to checkout
4. Continue to shipping
5. In 'Payment method' select Stripe option
6. Press 'Go review the order'

**Actual results:**
Untranslated content.
The card number and alert are not translated.
![image](https://user-images.githubusercontent.com/36628922/42985573-597fe6be-8bf2-11e8-8912-2906a3f36864.png)
![image](https://user-images.githubusercontent.com/36628922/42985591-70c533d8-8bf2-11e8-8809-36ba53829642.png)
![image](https://user-images.githubusercontent.com/36628922/42985563-4b7578f4-8bf2-11e8-9b9c-e77073606d6b.png)

**Expected:**
All content should be in English.

**Comment by pkarw** [comment]
Alina, this is from Stripe - it discovers the language using browser settings (probably Polish in Your case), it's not a bug ;)

**Comment by alinadivante** [comment]
Oh, ok :)
