### ISSUE TITLE
Errors in the console after refreshing the checkout page.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#1444]
1. Login into Vuestorefront
2. Go to checkout
3. Refresh page

**Actual results:**
User is logged out. Errors in Console.
(After the next refresh of the page, the user is logged in and the home page is opened)
![image](https://user-images.githubusercontent.com/36628922/42985997-1eb28f8a-8bf4-11e8-80a0-8e1cebdf999e.png)

**Expected:**
The user should stay logged in to the checkout page.

**Comment by filrak** [comment]
I was able only to reproduce the redirection to homepage

**Comment by Januszpl** [comment]
The problem is in **core/pages/Checkout.js** where don't have access when loading page on store state cart data and then the first condition in beforeMOunt method is true so we got redirection to homepage
