### ISSUE TITLE
Question about architecture

### ISSUE THREAD

**Issue by zadigus** [DivanteLtd/vue-storefront#1448]
Hi,
Can someone tell me the meaning of the arrow that goes from the elastic database to vue-storefront-api? What is supposed to happen there? I would have expected the opposite, i.e. an arrow going from the api to the database as I can imagine that the api depends on the database rather than the other way around. 
Hence my question: what do you mean with it? I am working on an e-commerce platform for which we have no interest in using the classical cms like Magento or prestashop. Because I want to extend your architecture to fulfill my needs, but in the same time I would like to comply to your philosophy, I need to understand that kind of details.
Thanks in advance for your support!

**Comment by pkarw** [comment]
Hi @zadigus thanks for pointig out this issue. Unfortunatelly this diagram has been processed so many times that it contains such minor issues.

You're right - api depends on the database and the arrow shows the data flow correctly. vue-storefront-api hasn't got any write permissions to the ElasticSearch (just read only as ES is populated by data pump - mage2vuestorefront in that case).

Please take a look at this repo: https://github.com/DivanteLtd/vue-storefront-integration-boilerplate it may be helpful to You. 

Let me know if you'll need any further guidances
