### ISSUE TITLE
E2E tests - managing state (logged/not logged)

### ISSUE THREAD

**Issue by Januszpl** [DivanteLtd/vue-storefront#1449]
@pkarw @Aekal 
We have some basic tests but we should think how we want test app for logged in users

Here we have some strategies:
https://youtu.be/5XQOK0v_YRE?t=541

1. Sub requests (fast, easy, flexible, no server/db, not true e2e, requieres fixtures),
2. static user (real session e2e, requires server, seed the db, shares test state),
3. Dynamic user: (no state mutations, flexible / powerful, db setup / teardown, slow/ complex)

I anyone has some more experience share your input or try to help with some PR.

I also think that the first added test basic-client-path should be removed or (renamed/refactored) to test specific parts like (checkout) as now we have some duplicated testing code (we add here product and we already test it in add-to-cart.js test).

**Comment by pkarw** [comment]
Good point. @alinadivante maybe You would like to add sth?

**Comment by alinadivante** [comment]
I will think about what to do with basic-client-path test.
When I'll have less work in my projects, I will try to think also  about tests of the logged in user.
