### ISSUE TITLE
Not deleting empty class in textarea when filled

### ISSUE THREAD

**Issue by Aylay** [DivanteLtd/vue-storefront#1454]
_Component :_ ~/components/core/blocks/Form/BaseTextarea.vue

Like BaseInput component, the BaseTextarea label have to move above the field when it's filled. But it doesn't.

_The solution :_ 
Replace `@textarea="$emit('textarea', $event.target.value)"`
By `@input="$emit('input', $event.target.value)"`
In ~/components/core/blocks/Form/BaseTextarea.vue

[https://vuejs.org/v2/guide/forms.html](https://vuejs.org/v2/guide/forms.html)

What do you think ?

**Comment by filrak** [comment]
@Aylay can you make a PR with the solution? ;)

**Comment by Aylay** [comment]
@filrak Yes, no problem, i do it right now :)
