### ISSUE TITLE
Compared products are deleted when there is a pagerefresh

### ISSUE THREAD

**Issue by mishanino** [DivanteLtd/vue-storefront#1457]
**Steps to reproduce:**
1. Add product to compare
2. Make page refresh
3. compare products are gone

**Comment by pkarw** [comment]
Hmm is it on demo or test? I've just tested it out and seems like it's fine - could You please check the dev-tools Application/IndexedDb tab if the compare data is stored in there?
<img width="1623" alt="screen shot 2018-07-25 at 06 22 50" src="https://user-images.githubusercontent.com/211899/43195521-4be9fda2-8fd3-11e8-92a7-4823dc9dbf3a.png">

**Comment by pkarw** [comment]
Cofirmed :) It works fine when You first go to the compare page (products are then stored)
