### ISSUE TITLE
ordersHistory always displayed ?

### ISSUE THREAD

**Issue by Aylay** [DivanteLtd/vue-storefront#1465]
Hi !

I just created an account on the demo.
I go to my account -> my orders
The empty table is displayed but I think that "No orders yet" that should be displayed.
What do you think ?

Here is the code : `<div class="col-xs-12" v-if="ordersHistory">` 
Here is the debug : [Screenshot](https://dsh.re/4cee1)

I think that we should check if ordersHistory is empty or not because it always exists.
What do you think ?

**Comment by Aylay** [comment]
Here's the code that checked that : 
`<div class="col-xs-12" v-if="ordersHistory.length > 0">`

Go PR ?

**Comment by pkarw** [comment]
Sure, good idea

**Comment by Aylay** [comment]
Ok @pkarw  let's go :)
