### ISSUE TITLE
Enforce coding guidelines with ESLint + TSLint + Prettier

### ISSUE THREAD

**Issue by DavidRouyer** [DivanteLtd/vue-storefront#1477]
https://prettier.io/ is a pretty popular code formatter and it's integrated with a lot of tools.

**Comment by lukeromanowicz** [comment]
We need a preset of rules that will match in all three tools without causing conflicts

**Comment by pkarw** [comment]
Please note the comment: https://github.com/DivanteLtd/vue-storefront/pull/2843#issuecomment-497914800
