### ISSUE TITLE
Login/Register pages are not adaptive on small resolutions

### ISSUE THREAD

**Issue by akbarik** [DivanteLtd/vue-storefront#1480]
On small resolutions (like width 320px) Login and Register pages don't look very adaptive. Text is overlapping. Screenshots talk to themselves.
<img width="399" alt="screen shot 2018-08-01 at 17 13 16" src="https://user-images.githubusercontent.com/15943863/43530735-96d16b76-95ae-11e8-9a08-0cdfa93074c7.png">
<img width="388" alt="screen shot 2018-08-01 at 17 13 31" src="https://user-images.githubusercontent.com/15943863/43530736-96f239aa-95ae-11e8-8b40-8ce6ee777e42.png">

**Comment by bartdominiak** [comment]
This issue is also related to forgot-pass component. Please check out my bugfix.
