### ISSUE TITLE
Translation improvements

### ISSUE THREAD

**Issue by DavidRouyer** [DivanteLtd/vue-storefront#1481]
- [ ] Replace CSV files with JSON -> Remove the need of preprocessing and additional dependencies
- [x] Lazy load translations https://kazupon.github.io/vue-i18n/guide/lazy-loading.html 
- [ ] Replace the lang attribute in the HTML tag

**Comment by pkarw** [comment]
I’m not sure about the point no. 1 as many translators / agencies / tools used to user the csv/excel for translations. JSON format doesn’t has such a good support regarding the i18n tooling

**Comment by DavidRouyer** [comment]
I haven't seen any project supporting CSV files, [WordPress](https://developer.wordpress.org/themes/functionality/localization/) & [Drupal](https://localize.drupal.org/download) are using PO files, [Angular](https://angular.io/guide/i18n) uses XLF files (Vue doesn't support any file type OOB).
If we want a broader support, we should use the PO file format then?

**Comment by pkarw** [comment]
OK, which problem is this solving - time to build?

**Comment by DavidRouyer** [comment]
For now I'll keep the CSV files, but I'll totally redo the way translations are handled.
Until now, we had the translation.preprocessor.js in the [webpack.base.config.js](https://github.com/DivanteLtd/vue-storefront/blob/da5d5d50412ac45b08db994941a964bfbd599539/core/build/webpack.base.config.js#L180-L191) but it appears in https://github.com/DivanteLtd/vue-storefront/blob/da5d5d50412ac45b08db994941a964bfbd599539/core/lib/themes.js#L2 too, resulting in a big chunk as you can see on my PR #1479.

**I'll preprocess the CSV files to generate JSON and statically serve them.** This way, we will be able to lazy load translations and reduce the size of the bundle.

**Comment by pkarw** [comment]
Cool!
