### ISSUE TITLE
Do not prepend http to elasticsearch.host

### ISSUE THREAD

**Issue by mingfang** [DivanteLtd/vue-storefront#1482]
https://github.com/DivanteLtd/vue-storefront/blob/da5d5d50412ac45b08db994941a964bfbd599539/core/store/lib/search.js#L24

I want to use relative paths in the config files.  
That works for all other endpoints except for this one due to the prepend logic above.

**Comment by pkarw** [comment]
Good point :)

**Comment by pkarw** [comment]
Related to #1290
