### ISSUE TITLE
Two different Elasticsearch clients - How to include them

### ISSUE THREAD

**Issue by Galch24** [DivanteLtd/vue-storefront#1483]
Hello.
We use one more Elasticsearch'es host to get addresses of Organizations.
My questions is how should I include a different Elasticsearch in the right way?

What I tryed to do:
1) I need to use different elastic  only in input form of address. So I create new vue component in storfront path:
storefront/src/themes/mytheme/components/theme/blocks/Form/AutocompleteAddress.vue

2) In my component I add a method that must return response of search result:

```
export default {
  data () {
    return {
      value: '',
      suggestions: [],
      query: '{"query":{"bool":{"must":[{"match":{"address_full":"Moscow city"}}]}},"size":10}'
    }
  },
  methods: {
    onInputEvent () {
      let self = this
      let body = {
        query: this.query,
        start: 0,
        size: 50,
        entityType: 'fias',
        sort: '',
        refresh: true
      }
      this.suggestions = []
      quickSearchByQuery(body)
        .then((results) => {
          for (let item of results.items) {
            self.suggestions.push(item)
          }
        }).catch((error) => {
          console.log(error)
        })
    }
  }
  components: {
    VueSimpleSuggest,
    quickSearchByQuery
  }
}
```

3) Then I edit storefront/core/lib/search.js  with some hard code to check connection with another Elasticsearch client.

So, in storefront/core/lib/search.js  I added the lines:

`
```
...
let es = require('elasticsearch')

let efias = require('elasticsearch')

...

let clientFias = new efias.Client({
  host: config.elasticfias.host,
  httpAuth: config.elasticfias.httpAuth,
  log: 'debug',
  apiVersion: '5.5',
  requestTimeout: 5000
})

...

export function quickSearchByQuery ({ query, start = 0, size = 50, entityType = 'product', sort = '', refresh = true }) {
	
  ...

  if (entityType === 'orders') {
    index = config.elasticsearch.indexEatOrders
  }

  if (entityType === 'fias') {
    index = config.elasticfias.indexFias
    client = clientFias
    clientFias.ping({
      requestTimeout: 5000
    }, (error) => {
      // at this point, eastic search is down, please check your Elasticsearch service
      if (error) {
        console.error('Elasticsearch cluster is down!')
      } else {
        console.log('Everything is ok')
      }
    })
  }

  ...

}
```
`
Here I use some settings from my local.json (config.elasticfias).

4) After all that steps I get an error in console:
`
```
xhr.js:82 HEAD http://localhost:8080/api/catalog/ 500 (Internal Server Error)
client Elasticsearch  cluster is down!     search.js:111
Failed to load http://elasticsearch:9206/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

console.js:38 ERROR: 2018-08-02T08:05:03Z
Error: Request error, retrying
  HEAD http://elasticsearch:9206/ => Request failed to complete.
      at Log.error (http://localhost:3000/dist/app.js:32874:56)
      at checkRespForFailure (http://localhost:3000/dist/app.js:42622:18)
      at XMLHttpRequest.xhr.onreadystatechange (http://localhost:3000/dist/app.js:224341:7)
Failed to load http://elasticsearch:9206/fias_addresses/fias/_search?size=50&from=0&sort=: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```
`

5) I check that elasticsearch host is works with  "Google Chrome Elastic toolbox" and with "Elasticsearch Head".
I check  http://elasticsearch:9206 and it's working fine.

I know that I should't edit search.js but in my case I just need to get list of addresses for autocomplete input. 

Can somebody give me the hint about architecture how to include different Elasticsearch in my storfront?

**Comment by pkarw** [comment]
Hello! In the new release we're not using elasticsearch-js anymore (https://github.com/DivanteLtd/vue-storefront/blob/master/core/store/lib/search.js). The problem with `localhost:9206` in Your case regards the header: `Failed to load http://elasticsearch:9206/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`

So I think after fixing this issue it will work however the better option is to do a official PullRequest modifying the https://github.com/DivanteLtd/vue-storefront/blob/master/core/store/lib/search.js#L21 to let user decide (with argument with default value - which will fallback to current behavior) if to use specific ElasticURL (given as a parameter or use the configValue - current behaviour).
