### ISSUE TITLE
vue-storefront API | Facing error while installing

### ISSUE THREAD

**Issue by diptipatel** [DivanteLtd/vue-storefront#1495]
Connector to Mangento : https://medium.com/@piotrkarwatka/vue-storefront-how-to-install-and-integrate-with-magento2-227767dd65b2

Without docker, it will install API? 

In reference URL also mention "you must have docker and redis instances up and running (docker-compose up in vue-storefront-api directory)"

I am using ubuntu 16.0 OS. I installed npm, yarn etc..

I have not docker.

I am getting error as docker can't start automatically. 
Refer attached screenshot

![error-docker](https://user-images.githubusercontent.com/6316566/43632285-2c568144-96f5-11e8-9ade-0c7babd549b4.png)

**Comment by michiel2806** [comment]
You have to [install docker](https://docs.docker.com/install/linux/docker-ce/ubuntu/) and add the docker group and add your account to the group.

To create the docker group and add your user:

    Create the docker group.

    $ sudo groupadd docker

    Add your user to the docker group.

    $ sudo usermod -aG docker $USER

**Comment by ashishsjagnani** [comment]
Is anyone have the solution of this issue. I am getting the same issue.

**Comment by razzul** [comment]
I am also facing the same issue

**Comment by Faizanq** [comment]
Am also facing same issue, USER already added into gruop.

I can run "docker run helllo-world" which work fine 

what else am missing

**Comment by Faizanq** [comment]
For latecomers,

In my case in I have old docker version, that causing the issue.

But if you still facing the issue the do below changes, so will get more idea about the error

1. find line[196], vue-storefront/core/scripts/installer.js
2. inside [if] condition change "docker-compose up -d > /dev/null 2>&1" to "docker-compose up -d"
i.e.

 if (shell.exec(`docker-compose up -d`).code !== 0) {
        reject(new Error('Can\'t start Docker in background.'))
  }

**Comment by amman20** [comment]
just use "sudo docker-compose up  -d" inside (vue-storefront/core/scripts/installer.js) in line 196

**Comment by sanaullahAhmad** [comment]
To resolve this error edit the line 196 in path

vue-storefront/core/scripts/installer.js
change conditon to  "sudo docker -composer up -d"

/**
   * Run 'docker-compose up' in background
   *
   * @returns {Promise}
   */
  dockerComposeUp () {
    return new Promise((resolve, reject) => {
      Message.info('Starting Docker in background...')

      if (shell.exec(`sudo docker-compose up -d`).code !== 0) {
        reject(new Error('Can\'t start Docker in background.'))
      }
      // Adding 20sec timer for ES to get up and running
      // before starting restoration and migration processes
      setTimeout(() => { resolve() }, 20000)
    })
  }
