### ISSUE TITLE
Product configuration works properly for one attribute only

### ISSUE THREAD

**Issue by mercs600** [DivanteLtd/vue-storefront#150]
Reproduce steps:
1. Open some configuration product
2. Select some color (e.g green) and add to the cart. 
3. You can see green variant in minicart. 
4. Select additional attribute (e.g size 31) with previous green attribute.
5. You can see product with size 31 and color black. 

vue-storefront/src/store/modules/product.js:91 
I see we check each attribute but previous matching is overwritten ?

**Comment by pkarw** [comment]
I will take a look at IT
Assigned to: pkarw
