### ISSUE TITLE
Styling break during few seconds after each page refresh

### ISSUE THREAD

**Issue by mishanino** [DivanteLtd/vue-storefront#1503]
I see broken styles during few seconds after each page refresh
![image](https://user-images.githubusercontent.com/4930295/43638664-5f78aa2a-9722-11e8-8782-cd8e03a8c523.png) I have this issue only when I use my own backend host, but I don't see any errors in the console. When I use your demo backend seems everything is ok with styling. I use vue-storefront 1.2.0 and defualt theme. Do you have any ideas about the reason of this issue, and how can I fix it?

**Comment by mercs600** [comment]
@mishanino which browser do you use ?

**Comment by mishanino** [comment]
@mercs600 I have this issue for Chrome and Firefox
