### ISSUE TITLE
all in one docker-compose.yml

### ISSUE THREAD

**Issue by roboto-cloud** [DivanteLtd/vue-storefront#151]
someone know if this project have mage2nosql and vue-storefront in one single docker-compose.yml file?
thanks in advance,

**Comment by pkarw** [comment]
As far as I know we don't have such configuration yet. I agree - it would be great to have it. We have to find somebody who'll be eager to prepare it :D @mkoszutowski Mateusz maybe you're the one? :) Great first contribution to the prject!
