### ISSUE TITLE
Border color for warning and error notifications

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1518]
<img width="338" alt="screen shot 2018-08-03 at 16 30 29" src="https://user-images.githubusercontent.com/211899/43648409-9ae72114-973a-11e8-995f-b6256f430f49.png">

We need just fix this OK button border?

**Comment by MatWaligora** [comment]
Sure, sorry I was not aware of different notification types. Fix: https://github.com/DivanteLtd/vue-storefront/pull/1521

**Comment by filrak** [comment]
Can you please also remove the align center for the text? Please don't take it as an insult but for me it just looks very bad :/

**Comment by MatWaligora** [comment]
@filrak https://github.com/DivanteLtd/vue-storefront/pull/1527
