### ISSUE TITLE
Cannot check the checkbox

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1529]
After the Base components refactor sth bad happened with checkboxes :)
It’s not possible to check it

Please take care of it as it critical issue in the checkout and other forms
![32b616b6-6c7e-44f6-9b33-1154cfa732d1](https://user-images.githubusercontent.com/211899/43684525-f5a5fb44-98a1-11e8-9435-1e91886ffe98.png)

**Comment by PanMisza** [comment]
I'll fix it today.

**Comment by pkarw** [comment]
Hmm it resulted in checkbox problem but maybe the source of it is in something else - I’ll take a look at it today thanks :) 

The local problem you’re facing seems like it’s caused by ... non exiting Es index. Try to run “npm run restore2main; npm run db rebuild” to restore database

**Comment by pkarw** [comment]
I don't have any console erros in Safari + dev tools on Macosx; but the checkboxes don't work :)
