### ISSUE TITLE
Spread operator error on Safari

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1530]
https://demo.vuestorefront.io (master branch) - Safari 11.0.3 - works just fine
https://test.vuestorefront.io (develop branch) OR localhost - Safari 11.0.3 - ends up with the following error:

```
SyntaxError: Unexpected token '...'. Expected a property name.
```

Chrome - works perfectly fine.

It's pretty strange. My first thought was that maybe after separating the core as module sth bad happened to babel-preprocessing these files?

I need Your help guys :)

![screen shot 2018-08-06 at 09 58 05](https://user-images.githubusercontent.com/211899/43704240-46e40a2e-995f-11e8-9a76-7866405b89dc.png)

**Comment by Igloczek** [comment]
Babel processing is enabled for these modules https://github.com/DivanteLtd/vue-storefront/blob/develop/core/build/webpack.base.config.js#L133

**Comment by Igloczek** [comment]
That's the point, we want to run babel only on `node_modules/@vue-storefront`  ignoring rest of the `node_modules`

**Comment by DavidRouyer** [comment]
Yes, but we want to run Babel in the src and core folder too. I've tried some regex in exclude to exclude all of the packages except one based on https://github.com/webpack/webpack/issues/2031 but it didn't work, so remove the exclude, and add in the include part all the folders which should be babelified

**Comment by Igloczek** [comment]
Fixed
