### ISSUE TITLE
The product sorting option doesn't work.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#1532]
1. Open https://test.vuestorefront.io/
2. Go to any category
3. Sort products by price or latest

*Current:*
Nothing happens. Sorting doesn't work.
![image](https://user-images.githubusercontent.com/36628922/43711346-ac7b316a-9972-11e8-99e7-f5e258a2d1a5.png)

*Expected:*
All products should be sorted by price (or from the latest ones).

**Comment by PanMisza** [comment]
I'll check that today.

**Comment by pkarw** [comment]
Can not reproduce it anymore
