### ISSUE TITLE
Unintuitive sorting option.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#1533]
1. Open https://test.vuestorefront.io/
2. Go to any category
3. Sort products

*Current:*
The "Sort by" option is very unintuitive for new user.
First of all - "arrow" icon suggests that dropdown list will be expand.
Second point - after hover over "Sort By" ("arrow cursor") is not changed to "hand-cursor"

(At the beginning I didn't know why Error message was displayed.)
![image](https://user-images.githubusercontent.com/36628922/43711072-e104d81a-9971-11e8-8dd2-5f26a6181dd0.png)

*Expected:*
We should think about new design or the sorting option..

**Comment by lorenaramonda** [comment]
Hi @alinadivante what about this?

I moved the sorting from the header to the list container:
<img width="1200" alt="schermata 2018-08-31 alle 10 29 20" src="https://user-images.githubusercontent.com/4409084/44901887-d6ce7b80-ad08-11e8-8de6-25a60a3833de.png">
removed the sorting arrows when not needed, while showed when a valid sort is selected:
<img width="1190" alt="schermata 2018-08-31 alle 10 29 30" src="https://user-images.githubusercontent.com/4409084/44901888-d6ce7b80-ad08-11e8-9e3b-5d66dde42a47.png">

**Comment by alinadivante** [comment]
I thought that maybe you could apply a solution such as for example on Aliexpress?
![image](https://user-images.githubusercontent.com/36628922/44958688-fec60680-aee3-11e8-8b43-3ec650a64f89.png)

![image](https://user-images.githubusercontent.com/36628922/44958686-f1108100-aee3-11e8-85f9-13d62635bde5.png)

What do you think? Is it possible?

**Comment by vaggelisk** [comment]
I'm working on this issue and I'm close to finish it but what exactly means `Best Match`? Could you explain it some more?

**Comment by pkarw** [comment]
This is just an example. Skip it please.

**Comment by inpronet** [comment]
I'm on it
