### ISSUE TITLE
Incorrect order of sizes.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#1535]
1. Go to any category
2. Look at 'Size' section

*Current:*
Incorrect order of sizes: S M L XS XL
![image](https://user-images.githubusercontent.com/36628922/43714655-f8f21b7a-997d-11e8-8f86-d47442814dab.png)

*Expected:*
There should be: XS S M L XL

**Comment by diboy2** [comment]
I'd like to work on this.

**Comment by pkarw** [comment]
@diboy2 ok, go for it :)

**Comment by diboy2** [comment]
Hello @pkarw ,

I don't think I'm able to do this issue since I don't have enough ram to use linux and get mage2vuestorefront running.

**Comment by diboy2** [comment]
@pkarw nvm, I found a fix. https://github.com/DivanteLtd/vue-storefront/pull/1797
