### ISSUE TITLE
Remove every call to the global variable

### ISSUE THREAD

**Issue by DavidRouyer** [DivanteLtd/vue-storefront#1540]
Alternatives:

- Event bus
- Local storage
- Root store

Variables:

- [x] `global.$VS.version` -> root store
- [x] `global.$VS.__DEMO_MODE__` -> root store or env.process variable handled by Webpack
- [x] `global.$VS.isSSR` -> Vue.prototype.$isServer
- [x] `global.$VS.storeView` -> root store
- [x] `global.$VS.localCache` -> Vue.prototype
- [x] `global.$VS.twoStageCachingDisabled` -> root store
- [x] `global.$VS.twoStageCachingDelta1` -> root store
- [x] `global.$VS.twoStageCachingDelta2` -> root store
- [x] `global.$VS.userTokenInvalidateLock` -> root store
- [x] `global.$VS.config` -> root store
- [x] `global.$VS.cacheErrorsCount` -> property of LocalForageCacheDriver
- [x] `global.$VS.db.attributesCollection` -> root store
- [x] `global.$VS.db.cartsCollection` -> root store
- [x] `global.$VS.db.categoriesCollection` -> root store
- [x] `global.$VS.db.cmsData` -> root store
- [x] `global.$VS.db.checkoutFieldsCollection` -> root store
- [x] `global.$VS.db.claimsCollection` -> root store
- [x] `global.$VS.db.compareCollection` -> root store
- [x] `global.$VS.db.elasticCacheCollection` -> root store
- [x] `global.$VS.db.newsletterPreferencesCollection` -> root store
- [x] `global.$VS.db.ordersCollection` -> root store
- [x] `global.$VS.db.ordersHistoryCollection` -> root store
- [x] `global.$VS.db.syncTaskCollection` -> root store
- [x] `global.$VS.db.usersCollection` -> root store
- [x] `global.$VS.db.wishlistCollection` -> root store
- [x] `global.$VS.eventBus` -> Vue.prototype
- [x] `global.$VS.i18n` -> Vue.prototype

**Comment by pkarw** [comment]
Related to #1507

**Comment by pkarw** [comment]
https://github.com/inversify/InversifyJS - and some kind of global Registries? 

Let's say we'll be having a singleton registries named like:
- Database - for collections
- Context - for SSR, storeView, localCache, eventBus, i18n
- Config - for config

Then we can in the first step refactor `/core/store/lib/i18n` to just use this kind of registry that we'll be resolved by IoC to get the specific properties.

I mean - it's kind of first step easier and faster than refactoring every single instance of the objects to IoC property

**Comment by DavidRouyer** [comment]
I suggest to remove those first 11 global variables and replace it with what I'm suggesting for each one (I can do it with a little refactoring), what do you guys think @pkarw @Igloczek @filrak?

**Comment by pkarw** [comment]
I think that we should start with some incremental changes - the first 11 variables to be moved to root store : for me it’s fine, fair enough

@Igloczek, @filrak?

**Comment by Igloczek** [comment]
Moving this to the root store makes sense for me, but probably will be worth to clean up the `store/index.js` file or at least add some comments here, since it's kinda hard to understand what is going on, since it doesn't look like the typical Vuex store setup.

**Comment by pkarw** [comment]
@DavidRouyer I belive this one is good close; could You close it?
