### ISSUE TITLE
Image Doesn't Display For Products?

### ISSUE THREAD

**Issue by john19691** [DivanteLtd/vue-storefront#1541]
For some reason my localhost link is correct, but my image src always stays at the assets/placeholder for some reason.

<img width="1031" alt="screen shot 2018-08-07 at 11 21 21 am" src="https://user-images.githubusercontent.com/40464112/43760838-5b13ecbe-9a34-11e8-94f5-2ac2d545a575.png">

**Comment by filrak** [comment]
If you put img address directly in a browser does it display the desired image?

**Comment by pkarw** [comment]
Please do also check the `vue-storefront-api/config/local.json` the section named `imageable`  + `magento2` in the latter one You should have propper magento2 image path (`/media/catalog/product...`) set

**Comment by pkarw** [comment]
Then check if You have imagemagick (`convert` cli command) installed

**Comment by john19691** [comment]
@pkarw Yes both are already done. Right now the issue is a few images show up, but the rest do not.

**Comment by benxh1995** [comment]
The path `media/catalog/product/` should be renamed to `pub/media/catalog/product/`.

This is the solution that works for me in my tests.

**Comment by Chiragsorathiya** [comment]
same problem
