### ISSUE TITLE
Can't build storefront npm

### ISSUE THREAD

**Issue by bishwos** [DivanteLtd/vue-storefront#1546]
OS: Macos
npm: 6.12.0
node: v10.8.0
---

try to install Vue-storefront as the introduction on gitHub on the master branch.
Then errors similar to below on the step to run `yarn build` in vue-storefront

ERROR in ./src/extensions/index.js
Module not found: Error: Can't resolve '@vue-storefront/extension-droppoint-shipping/index.js' in '/Users/me/itg/store/vue-storefront/src/extensions'
 @ ./src/extensions/index.js 4:16-80
 @ ./core/app.js
 @ ./core/client-entry.js

other error related to @vue-storefront.. not found and 

ERROR in ./core/store/modules/category/actions.js
Module not found: Error: Can't resolve 'lodash-es/toString' in '/Users/me/itg/store/vue-storefront/core/store/modules/category'
 @ ./core/store/modules/category/actions.js 11:0-42 342:45-53
 @ ./core/store/modules/category/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

hild html-webpack-plugin for "index.html":
     1 asset
error Command failed with exit code 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-storefront@ build: `rimraf dist && yarn build:client && yarn build:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-storefront@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by pkarw** [comment]
Have You run „yarn install” before?

**Comment by bishwos** [comment]
> Have You run „yarn install” before?

Yes, I have.
I followed the following steps:
Checked out throught git
`yarn`
`yarn build`

It fails on `yarn build`

also tried `yarn install` & then `yarn build`

**Comment by bishwos** [comment]
Here is the error:

yarn build v0.21.3
$ rimraf dist && yarn build:client && yarn build:server 
yarn build:client v0.21.3
$ cross-env NODE_ENV=production webpack --config ./core/build/webpack.prod.client.config.js --mode production --progress --hide-modules 
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
 16% building modules 54/59 modules 5 active …ader/lib/runtime/componentNormalizer.jsProcessing translation file: /Users/me/itg/store/vue-storefront/core/resource/i18n/de-DE.csv => de-DE
Processing translation file: /Users/me/itg/store/vue-storefront/core/resource/i18n/en-US.csv => en-US
Processing translation file: /Users/me/itg/store/vue-storefront/core/resource/i18n/es-ES.csv => es-ES
Processing translation file: /Users/me/itg/store/vue-storefront/core/resource/i18n/fr-FR.csv => fr-FR
Processing translation file: /Users/me/itg/store/vue-storefront/core/resource/i18n/it-IT.csv => it-IT
Processing translation file: /Users/me/itg/store/vue-storefront/core/resource/i18n/jp-JP.csv => jp-JP
Processing translation file: /Users/me/itg/store/vue-storefront/core/resource/i18n/nl-NL.csv => nl-NL
Processing translation file: /Users/me/itg/store/vue-storefront/core/resource/i18n/pl-PL.csv => pl-PL
Processing translation file: /Users/me/itg/store/vue-storefront/core/resource/i18n/pt-BR.csv => pt-BR
Processing translation file: /Users/me/itg/store/vue-storefront/core/resource/i18n/ru-RU.csv => ru-RU
Processing translation file: /Users/me/itg/store/vue-storefront/src/themes/theme-starter/resource/i18n/en-US.csv => en-US
 35% building modules 211/220 modules 9 active …e-storefront/core/api/wishlist/index.jsDEPRECATION WARNING on line 1, column 8 of stdin:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

Hash: e4cd9e2fd847e71e1dc3                                                                          
Version: webpack 4.12.2
Time: 13407ms
Built at: 08/08/2018 10:23:37 AM
 6 assets

ERROR in ./src/extensions/index.js
Module not found: Error: Can't resolve '@vue-storefront/extension-droppoint-shipping/index.js' in '/Users/me/itg/store/vue-storefront/src/extensions'
 @ ./src/extensions/index.js 4:16-80
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./src/extensions/index.js
Module not found: Error: Can't resolve '@vue-storefront/extension-google-analytics/index.js' in '/Users/me/itg/store/vue-storefront/src/extensions'
 @ ./src/extensions/index.js 4:82-144
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./src/extensions/index.js
Module not found: Error: Can't resolve '@vue-storefront/extension-mailchimp-subscribe/index.js' in '/Users/me/itg/store/vue-storefront/src/extensions'
 @ ./src/extensions/index.js 4:146-211
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./src/extensions/index.js
Module not found: Error: Can't resolve '@vue-storefront/extension-payment-backend-methods/index.js' in '/Users/me/itg/store/vue-storefront/src/extensions'
 @ ./src/extensions/index.js 4:213-282
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./src/extensions/index.js
Module not found: Error: Can't resolve '@vue-storefront/extension-payment-cash-on-delivery/index.js' in '/Users/me/itg/store/vue-storefront/src/extensions'
 @ ./src/extensions/index.js 4:284-354
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./src/extensions/index.js
Module not found: Error: Can't resolve '@vue-storefront/extension-template/index.js' in '/Users/me/itg/store/vue-storefront/src/extensions'
 @ ./src/extensions/index.js 4:356-410
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/client-entry.js
Module not found: Error: Can't resolve '@vue-storefront/store' in '/Users/me/itg/store/vue-storefront/core'
 @ ./core/client-entry.js 9:0-46 27:18-27 337:0-9 338:0-9 339:0-9

ERROR in ./core/app.js
Module not found: Error: Can't resolve '@vue-storefront/store' in '/Users/me/itg/store/vue-storefront/core'
 @ ./core/app.js 4:0-42 41:4-9 60:0-5 84:7-12 87:11-16 94:90-95 96:43-48 106:44-49
 @ ./core/client-entry.js

ERROR in ./core/components/ProductTile.js
Module not found: Error: Can't resolve '@vue-storefront/store/helpers' in '/Users/me/itg/store/vue-storefront/core/components'
 @ ./core/components/ProductTile.js 1:0-69 27:22-42
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/themes/theme-starter/components/ProductTile.vue?vue&type=script&lang=js
 @ ./src/themes/theme-starter/components/ProductTile.vue?vue&type=script&lang=js
 @ ./src/themes/theme-starter/components/ProductTile.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/themes/theme-starter/pages/Category.vue?vue&type=script&lang=js
 @ ./src/themes/theme-starter/pages/Category.vue?vue&type=script&lang=js
 @ ./src/themes/theme-starter/pages/Category.vue
 @ ./src/themes/theme-starter/router/index.js
 @ ./src/themes/theme-starter/index.js
 @ ./core/lib/themes.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/pages/Category.js
Module not found: Error: Can't resolve '@vue-storefront/store/helpers' in '/Users/me/itg/store/vue-storefront/core/pages'
 @ ./core/pages/Category.js 7:0-98 102:65-88 156:42-66 169:21-45 186:23-47 216:35-58
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/themes/theme-starter/pages/Category.vue?vue&type=script&lang=js
 @ ./src/themes/theme-starter/pages/Category.vue?vue&type=script&lang=js
 @ ./src/themes/theme-starter/pages/Category.vue
 @ ./src/themes/theme-starter/router/index.js
 @ ./src/themes/theme-starter/index.js
 @ ./core/lib/themes.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/client-entry.js
Module not found: Error: Can't resolve '@vue-storefront/store/lib/multistore' in '/Users/me/itg/store/vue-storefront/core'
 @ ./core/client-entry.js 10:0-110 28:4-20 71:25-43 72:27-43 77:12-28 131:18-34 217:18-34

ERROR in ./core/filters/date/index.js
Module not found: Error: Can't resolve '@vue-storefront/store/lib/multistore' in '/Users/me/itg/store/vue-storefront/core/filters/date'
 @ ./core/filters/date/index.js 1:0-72 9:18-34
 @ ./core/filters/index.js
 @ ./core/lib/themes.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/filters/price/index.js
Module not found: Error: Can't resolve '@vue-storefront/store/lib/multistore' in '/Users/me/itg/store/vue-storefront/core/filters/price'
 @ ./core/filters/price/index.js 1:0-72 12:18-34
 @ ./core/filters/index.js
 @ ./core/lib/themes.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/mixins/multistore/index.js
Module not found: Error: Can't resolve '@vue-storefront/store/lib/multistore' in '/Users/me/itg/store/vue-storefront/core/mixins/multistore'
 @ ./core/mixins/multistore/index.js 1:0-112 12:22-38 13:13-33
 @ ./core/mixins/index.js
 @ ./core/lib/themes.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/lib/task.js
Module not found: Error: Can't resolve '@vue-storefront/store/lib/multistore' in '/Users/me/itg/store/vue-storefront/core/store/lib'
 @ ./core/store/lib/task.js 9:0-78 39:10-32
 @ ./core/store/modules/sync/actions.js
 @ ./core/store/modules/sync/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/modules/order/actions.js
Module not found: Error: Can't resolve '@vue-storefront/store/lib/multistore' in '/Users/me/itg/store/vue-storefront/core/store/modules/order'
 @ ./core/store/modules/order/actions.js 4:0-72 19:20-36
 @ ./core/store/modules/order/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./src/themes/theme-starter/index.js
Module not found: Error: Can't resolve '@vue-storefront/store/lib/multistore' in '/Users/me/itg/store/vue-storefront/src/themes/theme-starter'
 @ ./src/themes/theme-starter/index.js 1:0-77 10:2-23
 @ ./core/lib/themes.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/client-entry.js
Module not found: Error: Can't resolve '@vue-storefront/store/lib/storage' in '/Users/me/itg/store/vue-storefront/core'
 @ ./core/client-entry.js 4:0-65 134:29-45 220:31-47 225:28-44 230:28-44

ERROR in ./core/store/modules/sync/actions.js
Module not found: Error: Can't resolve '@vue-storefront/store/lib/storage' in '/Users/me/itg/store/vue-storefront/core/store/modules/sync'
 @ ./core/store/modules/sync/actions.js 5:0-65 35:33-49 52:30-46 57:30-46
 @ ./core/store/modules/sync/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/client-entry.js
Module not found: Error: Can't resolve '@vue-storefront/store/lib/task' in '/Users/me/itg/store/vue-storefront/core'
 @ ./core/client-entry.js 3:0-57 263:19-26

ERROR in ./src/themes/theme-starter/store/product-extensions.js
Module not found: Error: Can't resolve '@vue-storefront/store/modules/product' in '/Users/me/itg/store/vue-storefront/src/themes/theme-starter/store'
 @ ./src/themes/theme-starter/store/product-extensions.js 4:0-62 15:27-36
 @ ./src/themes/theme-starter/store/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./src/themes/theme-starter/store/ui-store.js
Module not found: Error: Can't resolve '@vue-storefront/store/modules/ui-store' in '/Users/me/itg/store/vue-storefront/src/themes/theme-starter/store'
 @ ./src/themes/theme-starter/store/ui-store.js 4:0-63 49:27-36
 @ ./src/themes/theme-starter/store/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/modules/category/actions.js
Module not found: Error: Can't resolve 'lodash-es/chunk' in '/Users/me/itg/store/vue-storefront/core/store/modules/category'
 @ ./core/store/modules/category/actions.js 9:0-36 294:34-39
 @ ./core/store/modules/category/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/modules/product/helpers.js
Module not found: Error: Can't resolve 'lodash-es/flattenDeep' in '/Users/me/itg/store/vue-storefront/core/store/modules/product'
 @ ./core/store/modules/product/helpers.js 7:0-48 313:24-35
 @ ./core/store/modules/product/actions.js
 @ ./core/store/modules/product/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/pages/Product.js
Module not found: Error: Can't resolve 'lodash-es/groupBy' in '/Users/me/itg/store/vue-storefront/core/pages'
 @ ./core/pages/Product.js 7:0-40 90:33-40
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/themes/theme-starter/pages/Product.vue?vue&type=script&lang=js
 @ ./src/themes/theme-starter/pages/Product.vue?vue&type=script&lang=js
 @ ./src/themes/theme-starter/pages/Product.vue
 @ ./src/themes/theme-starter/router/index.js
 @ ./src/themes/theme-starter/index.js
 @ ./core/lib/themes.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/lib/task.js
Module not found: Error: Can't resolve 'lodash-es/isNaN' in '/Users/me/itg/store/vue-storefront/core/store/lib'
 @ ./core/store/lib/task.js 3:0-36 58:14-19 59:14-19
 @ ./core/store/modules/sync/actions.js
 @ ./core/store/modules/sync/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/modules/cart/index.js
Module not found: Error: Can't resolve 'lodash-es/isString' in '/Users/me/itg/store/vue-storefront/core/store/modules/cart'
 @ ./core/store/modules/cart/index.js 8:0-42 68:28-36
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/lib/task.js
Module not found: Error: Can't resolve 'lodash-es/isUndefined' in '/Users/me/itg/store/vue-storefront/core/store/lib'
 @ ./core/store/lib/task.js 4:0-48 58:68-79 59:59-70
 @ ./core/store/modules/sync/actions.js
 @ ./core/store/modules/sync/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/lib/search.js
Module not found: Error: Can't resolve 'lodash-es/map' in '/Users/me/itg/store/vue-storefront/core/store/lib'
 @ ./core/store/lib/search.js 1:0-32 79:13-16
 @ ./core/store/modules/attribute/actions.js
 @ ./core/store/modules/attribute/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/lib/themes.js
Module not found: Error: Can't resolve 'lodash-es/merge' in '/Users/me/itg/store/vue-storefront/core/lib'
 @ ./core/lib/themes.js 1:0-36 27:9-14 34:9-14 38:9-14
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/modules/cart/actions.js
Module not found: Error: Can't resolve 'lodash-es/omit' in '/Users/me/itg/store/vue-storefront/core/store/modules/cart'
 @ ./core/store/modules/cart/actions.js 10:0-34 242:19-23
 @ ./core/store/modules/cart/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/modules/product/helpers.js
Module not found: Error: Can't resolve 'lodash-es/omit' in '/Users/me/itg/store/vue-storefront/core/store/modules/product'
 @ ./core/store/modules/product/helpers.js 8:0-34 621:11-15 729:27-31 770:24-28
 @ ./core/store/modules/product/actions.js
 @ ./core/store/modules/product/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/modules/product/actions.js
Module not found: Error: Can't resolve 'lodash-es/omit' in '/Users/me/itg/store/vue-storefront/core/store/modules/product'
 @ ./core/store/modules/product/actions.js 13:0-34 626:19-23
 @ ./core/store/modules/product/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/modules/product/helpers.js
Module not found: Error: Can't resolve 'lodash-es/remove' in '/Users/me/itg/store/vue-storefront/core/store/modules/product'
 @ ./core/store/modules/product/helpers.js 9:0-38 128:30-36
 @ ./core/store/modules/product/actions.js
 @ ./core/store/modules/product/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/modules/cart/getters.js
Module not found: Error: Can't resolve 'lodash-es/sumBy' in '/Users/me/itg/store/vue-storefront/core/store/modules/cart'
 @ ./core/store/modules/cart/getters.js 1:0-36 15:17-22 29:17-22 39:11-16
 @ ./core/store/modules/cart/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/pages/Category.js
Module not found: Error: Can't resolve 'lodash-es/toString' in '/Users/me/itg/store/vue-storefront/core/pages'
 @ ./core/pages/Category.js 2:0-42 162:63-71 162:93-101
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/themes/theme-starter/pages/Category.vue?vue&type=script&lang=js
 @ ./src/themes/theme-starter/pages/Category.vue?vue&type=script&lang=js
 @ ./src/themes/theme-starter/pages/Category.vue
 @ ./src/themes/theme-starter/router/index.js
 @ ./src/themes/theme-starter/index.js
 @ ./core/lib/themes.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/lib/task.js
Module not found: Error: Can't resolve 'lodash-es/toString' in '/Users/me/itg/store/vue-storefront/core/store/lib'
 @ ./core/store/lib/task.js 5:0-42 54:49-57
 @ ./core/store/modules/sync/actions.js
 @ ./core/store/modules/sync/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/modules/attribute/helpers.js
Module not found: Error: Can't resolve 'lodash-es/toString' in '/Users/me/itg/store/vue-storefront/core/store/modules/attribute'
 @ ./core/store/modules/attribute/helpers.js 7:0-42 28:10-18 28:33-41
 @ ./core/store/modules/category/actions.js
 @ ./core/store/modules/category/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/modules/cart/index.js
Module not found: Error: Can't resolve 'lodash-es/toString' in '/Users/me/itg/store/vue-storefront/core/store/modules/cart'
 @ ./core/store/modules/cart/index.js 9:0-42 22:38-46
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/modules/category/actions.js
Module not found: Error: Can't resolve 'lodash-es/toString' in '/Users/me/itg/store/vue-storefront/core/store/modules/category'
 @ ./core/store/modules/category/actions.js 11:0-42 342:45-53
 @ ./core/store/modules/category/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/modules/product/helpers.js
Module not found: Error: Can't resolve 'lodash-es/toString' in '/Users/me/itg/store/vue-storefront/core/store/modules/product'
 @ ./core/store/modules/product/helpers.js 10:0-42 730:17-25 730:65-73
 @ ./core/store/modules/product/actions.js
 @ ./core/store/modules/product/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/modules/category/actions.js
Module not found: Error: Can't resolve 'lodash-es/trim' in '/Users/me/itg/store/vue-storefront/core/store/modules/category'
 @ ./core/store/modules/category/actions.js 10:0-34 369:24-28
 @ ./core/store/modules/category/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/store/modules/product/actions.js
Module not found: Error: Can't resolve 'lodash-es/trim' in '/Users/me/itg/store/vue-storefront/core/store/modules/product'
 @ ./core/store/modules/product/actions.js 14:0-34 336:20-24
 @ ./core/store/modules/product/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/app.js
Module not found: Error: Can't resolve 'lodash-es/union' in '/Users/me/itg/store/vue-storefront/core'
 @ ./core/app.js 1:0-36 94:21-26
 @ ./core/client-entry.js

ERROR in ./core/client-entry.js
Module not found: Error: Can't resolve 'lodash-es/union' in '/Users/me/itg/store/vue-storefront/core'
 @ ./core/client-entry.js 7:0-36 92:6-11

ERROR in ./core/store/modules/product/helpers.js
Module not found: Error: Can't resolve 'lodash-es/union' in '/Users/me/itg/store/vue-storefront/core/store/modules/product'
 @ ./core/store/modules/product/helpers.js 11:0-36 164:52-57 318:15-20
 @ ./core/store/modules/product/actions.js
 @ ./core/store/modules/product/index.js
 @ ./core/store/modules/index.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in ./core/pages/Product.js
Module not found: Error: Can't resolve 'lodash-es/uniqBy' in '/Users/me/itg/store/vue-storefront/core/pages'
 @ ./core/pages/Product.js 8:0-38 108:13-19
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/themes/theme-starter/pages/Product.vue?vue&type=script&lang=js
 @ ./src/themes/theme-starter/pages/Product.vue?vue&type=script&lang=js
 @ ./src/themes/theme-starter/pages/Product.vue
 @ ./src/themes/theme-starter/router/index.js
 @ ./src/themes/theme-starter/index.js
 @ ./core/lib/themes.js
 @ ./core/app.js
 @ ./core/client-entry.js

ERROR in app.js from UglifyJs
Unexpected token: operator (!) [./core/store/modules/sync/actions.js:31,35][app.js:26863,33]
Child html-webpack-plugin for "index.html":
     1 asset
error Command failed with exit code 2.
error Command failed with exit code 1.

**Comment by pkarw** [comment]
@Igloczek it seems like a problem with the lerna - have you got sth like this before? After using "yarn install; yarn build" it should work just fine

**Comment by Igloczek** [comment]
Lerna is used only for publishing packages, plase do not confuse it with setting up local dependecies, because that is 100% based on yarn.

Questions round:
- what is your yarn version?
- did you run any `npm` commands before `yarn`? If true, plase remove whole `node_modules` and use just `yarn`. Using `npm` is prohibited in this project, becasue lack of support for features we need.

**Comment by bishwos** [comment]
@Igloczek Thanks, turns out the issue was the yarn version. Worked perfectly

**Comment by ShashankChitranshi** [comment]
Waht is the yarn version you have used
I am facing the same issue

**Comment by mayank1513** [comment]
Facing same issue

**Comment by abogdanov-work** [comment]
Same issue here, please, provide a solution
