### ISSUE TITLE
[TypeScript] Optimizations

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1547]
We've introduced TypeScript to the project but for sure we need to find some ways to optimize how it's used:
- [ ] Do we still need Babel, or can we limit it's usage because TS is compiling the source anyway :)
- [ ] Can we limit the scope (modules) of what TS is compiling - because it's taking lot of time at first build

**Comment by pkarw** [comment]
@DavidRouyer I've assigned this one to You for 1.4.0 (October) as You probably have the strongest experience of TypeScript among the core team ;P

**Comment by filrak** [comment]
Imho we should definiately limit ts scope to core and src/modules. I think migrating to babel 7 and getting rid of ts-loader can be an issue for next milestone @pkarw wdyt?

**Comment by pkarw** [comment]
Makes sense!
