### ISSUE TITLE
Bluefoot CMS integration

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1552]
Bluefoot CM available in the Commerce edition of Magento2 stores the data inside pages/blocks collection in the following format:

```json
<!--GENE_BLUEFOOT="[{"type":"row","children":[{"contentType":"buttons","children":{"button_items":[{"contentType":"button_item","entityId":"4","formData":{"align":"","metric":""}}]},"entityId":"3","formData":{"align":"","metric":""}},{"contentType":"textarea","entityId":"5","formData":[]}]},{"type":"row"}]"-->;
```

- [ ] Add a Magento2 api extension to return the JSON stored by Bluefoot CMS inside the magento/cms blocks and magento/cms pages - enrich with the related entities (bluefoot CMS stores just an entityId)
- [ ] Add an extension to [mage2vuestorefront](https://github.com/DivanteLtd/mage2vuestorefront) to download the json objects from bluefoot CMS and store them in the ElasticSearch
- [ ] Create a abstract/general component in the UI to process the JSON objects from Bluefoot CMS

**Comment by pkarw** [comment]
The result as it's returned from the API:

```json
{
  "id": 2,
  "identifier": "footer_links_block",
  "title": "Footer Links Block",
  "content": "<!--GENE_BLUEFOOT=\"[{\"type\":\"row\",\"children\":[{\"contentType\":\"buttons\",\"children\":{\"button_items\":[{\"contentType\":\"button_item\",\"entityId\":\"4\",\"formData\":{\"align\":\"\",\"metric\":\"\"}}]},\"entityId\":\"3\",\"formData\":{\"align\":\"\",\"metric\":\"\"}},{\"contentType\":\"textarea\",\"entityId\":\"5\",\"formData\":[]}]},{\"type\":\"row\"}]\"-->",
  "creation_time": "2018-08-01 05:24:41",
  "update_time": "2018-08-02 04:15:11",
  "active": true
}
```

**Comment by sandermangel** [comment]
@pkarw can we close this since BlueFoot is not available anymore?

**Comment by pkarw** [comment]
True, positive
