### ISSUE TITLE
typo and inactive link

### ISSUE THREAD

**Issue by daksamit** [DivanteLtd/vue-storefront#1557]
We have 'Youe' instead of 'Your' at the end of file: 
https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Extending%20vue-storefront-api.md

Also, inactive link under "Extensions list" section:
https://github.com/DivanteLtd/vue-storefront/blob/master/doc/extensions/Working%20with%20extensions.md

"Example of custom extension" link : https://github.com/DivanteLtd/vue-storefront/tree/master/src/extensions/custom_extension

**Comment by pkarw** [comment]
Thanks, could You please fix it and send us a Pull Request please?
