### ISSUE TITLE
Facebook login feature

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1562]
To add the Facebook login feature we should start with vue-storefront-api I believe. It should be an extension adding oauth2 endpoints I believe. Then we should also think of how to integrate it with the Magento2 authorization

However, the oauth2 endpoint should be implemented solely in the vue-storefront + vue-storefront-api w - not in the eCommerce backend.

**Comment by sandermangel** [comment]
Duplicate of #3316
