### ISSUE TITLE
Update on microcart doesn’t update the cart model qty 

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#157]
Label: Easy first pick

**Comment by mercs600** [comment]
@pkarw could you explain a bit more the issue ? I noticed another issue with updating. Described in #168

**Comment by pkarw** [comment]
After your PR it works BUT please add return key support for accepting new value; now - clicking the "Edit" is counter-intuitive

**Comment by pkarw** [comment]
@mercs600
