### ISSUE TITLE
[ Newsletter ] Create newsletter module

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1576]
Read before picking:
- [About modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md) - explaination, structure, motivations behind modules
- [Refactoring plan for modules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/refactoring-to-modules.md)

Create module containing all logic connected to newsletter.

For now obviously we need to provide this methods but feel free to propose more if you think something is missing.
- `subscribe(email)` 
- `account/unsubscribe(email)` 
- `account/isSubscribed(email)` 

The task includes rewriting all core components and pages parts that are using this functions to use core modules.

TODO:
- [ ] create functions listed above
- [ ] documment them
- [ ] write unit tests
- [ ] change core pages and core components that are using this features to use module

Feel free to reach me on slack for details

**Comment by qiqqq** [comment]
@nuovecode I started work with this and I see you commited some changes. I will finish this taks

**Comment by nuovecode** [comment]
OOk @qiqqq go on 👍
