### ISSUE TITLE
Safari issues (on develop branch)

### ISSUE THREAD

**Issue by lorenaramonda** [DivanteLtd/vue-storefront#1578]
I was checking the develop branch on safari and found out this couple of problems, one of which breaks the page. I think we should pay attention to these before going into production.

**MAJOR**
SyntaxError: The delete operator requires a reference expression.
`delete typeof this._localCache[key]`
This prevents the page to load images and any other js action to work

It can be solved by removing typeof, is there any reason why it's there? I've already fix it on my fork, if you agree with removing typeof I can push it.

**MINOR**
[Error] Viewport argument key "minimal-ui" not recognized and ignored. (localhost, line 5)
https://stackoverflow.com/a/26884561/3710148

This does not break anything but it's not compatible for sure. So it's up to you to choose how to behave ✌️ 

/cc @pkarw @filrak

**Comment by DavidRouyer** [comment]
I don't know about the 'minimal-ui' stuff, but try to pull again we've just fixed a thing https://github.com/DivanteLtd/vue-storefront/pull/1579

**Comment by pkarw** [comment]
For sure kind of `delete typeof this._localCache[key]` is an error that need to be fixed :)

**Comment by pkarw** [comment]
So, please pull the latest changes that fixed babel support and go on with other things You see that need to be fixed on Safari

**Comment by lorenaramonda** [comment]
uuuh maybe it's due to http without https, let me check

**Comment by pkarw** [comment]
@lorenaramonda please push this change , thanks!

**Comment by pkarw** [comment]
@lorenaramonda is your recent fix #1584 closing this issue?

**Comment by lorenaramonda** [comment]
@pkarw yes it does. it still remains this -> [Error] Viewport argument key "minimal-ui" not recognized and ignored. (localhost, line 5) but it's non-blocking
