### ISSUE TITLE
Normalize paths in installer script

### ISSUE THREAD

**Issue by Igloczek** [DivanteLtd/vue-storefront#1590]
If the user passes path containing space for example `/User/name/My Folder/project` and then we use it to clone the backend repository, script crashes (without any meaningful error 😭 ).

To check: https://github.com/DivanteLtd/vue-storefront/blob/develop/core/scripts/installer.js#L138

Error log from send by one of users:
![untitled](https://user-images.githubusercontent.com/5119280/44120792-ca39c390-a01d-11e8-9032-a5e57ed2b46c.jpeg)

**Comment by pkarw** [comment]
@vue-kacper if You find some time before Bartek will - please close this issue as well
