### ISSUE TITLE
Add some <title> and <meta description> support

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#160]
![zrzut ekranu 2017-10-24 21 19 48](https://user-images.githubusercontent.com/211899/31963514-3461dd0c-b901-11e7-97f9-53fb4c956392.png)

**Comment by mercs600** [comment]
I will take it

**Comment by patrykpiston** [comment]
#160 looks nice, it can be easily expanded upon @filrak @mercs600

**Comment by patrykpiston** [comment]
b37c7088fb70a75cddb6b8606aa66b5859865fd0 looks nice and can be easily expanded upon. @filrak ?

**Comment by mercs600** [comment]
@patrykpiston I haven't finished it yet, this is only my prototype from yesterday. I have to improve it ;-)

**Comment by mercs600** [comment]
I think we can close it
