### ISSUE TITLE
Incorrect productinfo after searching for different product

### ISSUE THREAD

**Issue by EsteraVendic** [DivanteLtd/vue-storefront#1601]
### Steps to reproduce:

1. Search for "short" 
2. Click on "Erika Running Short"
3. Check specifications
4. Notice the pattern is set on "Graphic Print"
5. Search for "short" again
6. Click on "Hawkeye Yoga Short" 
7. Check specifications
8. Notice the pattern is set on "Graphic Print"
9. Refresh page with cmd + R  or (ctrl+r) and check specifications again
10. Notice the pattern is changed to "Solid, Striped"

### Expected result:
Specifications showing for correct product

### Actual result:
Specifications showing from previous product

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/30499229/44262306-d5865480-a21a-11e8-8482-ff13f4252192.gif)

**Comment by pkarw** [comment]
Thanks! This is related to https://github.com/DivanteLtd/vue-storefront/issues/1429

Solution for #1429: https://github.com/pkarw/vue-storefront/commit/e3f909ce4ecd54ad65e8d33c3eba4ec42f6bd7aa

We should add exactly the same event handler + refresh to: https://github.com/DivanteLtd/vue-storefront/blob/master/core/pages/Product.js

`customAttributes` computer property is not causing the UI refresh as it seems

**Comment by pkarw** [comment]
Fixed + tested
