### ISSUE TITLE
Move features inside core modules root to /features folder

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1605]
According to [modules guide](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md#how-module-should-look-like) `.ts` files that are now in the root of the modules should be in a `features` folder.

So for example for a `core/api/cart` module we have files like `addToCart.ts` etc in a root of the module. They should be moved to the `core/api/module_name/features` folder to not confuse other ppl working on a modules.

The task involves
- [x] moving modules features from all modules to `core/api/module_name/features` folder
- [x] correcting all the pathes pointing to the old location of this features

**Comment by pkarw** [comment]
@filrak what's the preferred way to add custom / new modules on the extension / theme layer or via npm module? I think we should have a way for doing so as a third option for having vue storefront extendable

**Comment by filrak** [comment]
Currently it's just importing appropiate features since we have only them in the modules. I want to stick with it as long as we don't have most of the features separated to be backward compatible (from the developer PoV nothing changes). Once we have the main modules we will change the way we are currently registering it's parts and move it to one place
