### ISSUE TITLE
Facing error while install mage2vuestorefront (Magento to Vue StoreFront)

### ISSUE THREAD

**Issue by diptipatel** [DivanteLtd/vue-storefront#1606]
I am trying to connect Magento to vue storefront API

I am referring below URL 
**https://medium.com/@piotrkarwatka/vue-storefront-how-to-install-and-integrate-with-magento2-227767dd65b2**

While running **node cli.js **taxrule****  
I am getting below Error as error: API call failed: Consumer is not authorized to access Magento_Tax::manage_tax

I am getting same error while running node cli.js products.

Consumer is not authorized to access Magento_Tax::manage_tax

Where need to pass Authorization Bearer token?

What i missed.

I configured all key into mage2vs/src/local.json file

Could you please help me?

**Comment by pkarw** [comment]
Please check/enable the Tax permission in Magento2->System->Integrations integrations settings

**Comment by diptipatel** [comment]
node cli.js categories
node cli.js productcategories
node cli.js product

Getting same error for while running all above command.
Consumer is not authorized to access Magento_CatalogInventory::cataloginventory

**Comment by zadigus** [comment]
@pkarw you mean checking Stores -> Taxes solves the issue, as there are other Tax options, like Report -> Sales -> Tax and Stores -> Settings -> Configuration -> Tax Section which will not make the ˋnode cli.js taxruleˋ work. I got it working that way.

**Comment by mateo2181** [comment]
Hi have the same problem. I got the error 
Consumer is not authorized to access Magento_CatalogInventory::cataloginventory

**Comment by mateo2181** [comment]
That works! thanks! I have another problem, when I run node cli.js categories just get default category. Do you why happen this?

**Comment by mateo2181** [comment]
That works! Thanks!

**Comment by diptipatel** [comment]
Wow great to hear.

My Vue store front not showing Magento product images
I already installed imagick extension and also provide Magento catalog url in config.json file
Still images not displaying in Dev environment.

Any idea?
Is any other dependencies install?

**Comment by mateo2181** [comment]
@diptipatel I had the same probem and my error was the properties magento2.url and magento2.imgUrl in file local.json under vue-storefront-api/config folder. I solved this trying to access to an image of a product in the browser, for example, in my case I have magento running in localhost and I can see an image in http://localhost/pub/media/catalog/product/b/u/buzo.jpg. 
So in my case magento2.imgUrl: http://localhost/pub/media/catalog/product

**Comment by diptipatel** [comment]
@mateo2181 Still i can't able to see image magento product image in vue storefront. I have already installed **imagemagick**.
I have following questions:
1. **What is image path need to provide while installing vue store front? What is use of this image path?**

---------------------------------------------
2. **Magento Image path coming like from cache folder**
Magento Image Path
`<img class="product-image-photo" src="http://magento host.com/pub/media/catalog/product/cache/f073062f50e48eb0f0998593e568d857/m/h/mh01-gray_main.jpg" alt="Chaz Kangeroo Hoodie" width="240" height="300">`

**Vue StoreFront getting path as**
`<img alt="Tiffany Fitness Tee" src="/assets/placeholder.jpg" data-testid="productImage" data-v-af5f87e8="" data-src="http://magento host.com/pub/media/catalog/product/**310/300/resize**/w/s/ws09-blue_main.jpg" lazy="error" width="310" height="300">`

I did below setting into vue-Store-front config/local.json file as below parameter.

"images": {
"baseUrl": "http://magento host.com/pub/media/catalog/product/", 
"productPlaceholder": "/assets/placeholder.jpg" 
},
@pkarw 
Could you please correct me? What was wrong? This is urgent
Still i am unable to see images.

**Comment by mateo2181** [comment]
@diptipatel the url should be http://localhost:8080/.... I have vue-storefront-api running in that address. 
And vue-storefront-api call to Magento2.

My local.json below vue-storefront is 
"images": {
    "baseUrl": "http://localhost:8080/img/",
    "productPlaceholder": "/assets/placeholder.jpg"
}
. . .

and my local.json in vue-storefront-api is
"magento2": {
    "url": "http://localhost",
    "imgUrl": "http://localhost/pub/media/catalog/product",
    . . .
}
"imageable": {
    "namespace": "",
    . . .
}
. . .
  
I think these are the properties you need set correctly to see images.

**Comment by zadigus** [comment]
Please double-check my answer here: https://github.com/DivanteLtd/mage2vuestorefront/issues/28. I faced the very same problem yesterday.

**Comment by diptipatel** [comment]
Thank you every one. I have refereed DivanteLtd/mage2vuestorefront#28
Magento product/images showing in vue storefront.
