### ISSUE TITLE
Cannot add bundle product with different configuration to shopping cart

### ISSUE THREAD

**Issue by afirlejczyk** [DivanteLtd/vue-storefront#1620]
Try to choose different configuration for any bundle product.
In the shopping cart, there is always same product (with the same options), only quantity has changed.

![bundle-cart](https://user-images.githubusercontent.com/4245592/44460011-d00a7f00-a60b-11e8-8a97-d4efd15f4649.png)

**Comment by pkarw** [comment]
In my case the options are set correctly (different options) - but not as another product but rather incrementing the qty.
How it exactly works in Magento2?

**Comment by afirlejczyk** [comment]
Separated products are created in Magento2.

![bundle-magento-cart](https://user-images.githubusercontent.com/4245592/44460265-b289e500-a60c-11e8-84ba-3ac22a63b417.png)

**Comment by ananth-iyer** [comment]
@pkarw I want to work on this issue so please assign this issue to me

**Comment by PatrickKluwig** [comment]
Hey, hope you are fine @pkarw :)
Do you know when this issue will be fixed? 
Best regards

**Comment by klapperkopp** [comment]
I am also stuck at this. Any progress by @ananth-iyer ?
maybe this is a hackathon topic @pkarw @PatrickKluwig

**Comment by ananth-iyer** [comment]
@klapperkopp @filrak There are some codes written which are hard-coded deep inside the core, that needs to change. I will soon post the screenshot for suggestions to change it.

Note: That is related to products add to cart functionality

**Comment by ananth-iyer** [comment]
@klapperkopp @filrak Please check the screenshot and let me know how can I make it use for multi-selection options in Bundle product:
![2019_05_28_Bundle_Product_selectionOptions](https://user-images.githubusercontent.com/24892273/58482262-b0484e80-817b-11e9-9aa6-5ed6929cd718.png)

https://github.com/DivanteLtd/vue-storefront/blob/cc4ce10e712e57dee54eb5bc1babac106df5fac7/core/modules/catalog/store/product/mutations.ts#L23-L28

**Comment by pkarw** [comment]
Fixed with #3261
