### ISSUE TITLE
[i18n] Translation blinking after page refresh

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1630]
Steps to reproduce:
- https://test.vuestorefront.io/de/c/frauen-20 - refresh the page
- take a look at the Filters "Farbe" -> "Color" -> "Farbe"

**Comment by pkarw** [comment]
Seems like SSR generated page has correct translations -> then i18n loads default translation (which is english) and then loads the correct translation file again. Maybe we just must serve all supported languages (maybe just to make it possible in the config to mark which one's or load this information form `config.storeViews` during the compilation).

I know it's maybe not 10000% optimal regarding bundle size, but i18n blinking is not acceptable :)

**Comment by DavidRouyer** [comment]
https://stackoverflow.com/a/48967239
They don't use the default locale and fallbackLocale https://github.com/DivanteLtd/vue-storefront/blob/0fc92cbc5c0a9d5e18ee1c6f96f3d987308e3e38/core/lib/i18n.ts#L9-L10 like we do. We just need to remove that and wait until the language is loaded to set it, it will be more elegant
