### ISSUE TITLE
[default] filters are not updating

### ISSUE THREAD

**Issue by vue-kacper** [DivanteLtd/vue-storefront#1649]
# Steps to reproduce:

- Visit https://demo.vuestorefront.io
- Refresh browser window
- Select category Women -> Tops -> Jackets
- Click on Breadcrumbs "Tops"

![filters](https://user-images.githubusercontent.com/42430550/44771229-b8cb1480-ab6a-11e8-90ba-6fda10988f8c.PNG)

# Expected result:

Filters on the left sidebar should update accordingly without need for page refresh

# Actual result:

Filters are not updating, page refresh is needed to see filters current state

**Comment by pkarw** [comment]
Good point
