### ISSUE TITLE
Unable to uncheck the checkbox product in bundle product

### ISSUE THREAD

**Issue by bachus03** [DivanteLtd/vue-storefront#1675]
Hi, I have experienced an Issue with bundle product.

I have migrated products form magento 2 store to VS and when i I am on product page where the product is a bundle type I am unable to uncheck the product if the option is checkbox an there is only one checkbox. Offcourse I checked that the option IS NOT REQUIRED.

**Comment by pkarw** [comment]
Please check the ProductBundleOptions.vue - how the checkboxes logic is supported in there; as far as I know we’re currently not supporting all bundle options types so maybe it’s a good area for the contribution as well!

**Comment by ananth-iyer** [comment]
@pkarw I am working on it

**Comment by ananth-iyer** [comment]
@pkarw Magento - Bundle product items support 4 variants of input type - Drop-down, Radio buttons, Checkbox, Multiple Select.

So I am working on to supports all. Currently, VS only supports radio button.

**Comment by pkarw** [comment]
@ananth-iyer thats awesome! Thanks

**Comment by ananth-iyer** [comment]
@mcspronko I am working on it & half-way completed. Soon I will create PR.

**Comment by mcspronko** [comment]
Ok thanks, removed myself from Assignee.

**Comment by PatrickKluwig** [comment]
Hey, are there any news on it? :)

**Comment by ananth-iyer** [comment]
@PatrickKluwig I am working on this issue
Because the Base Checkbox component is currently improved I am to refactor the current implementations for the bundle product.
PR: https://github.com/DivanteLtd/vue-storefront/pull/2679

**Comment by dmytrokravch** [comment]
Hi guys, any updates? :)

**Comment by ananth-iyer** [comment]
I am no more working on this issue, anybody is willing to contribute is most welcome

**Comment by andrzejewsky** [comment]
I think it was fixed @bachus03 could you check this on `develop` branch?
