### ISSUE TITLE
Can't Install Backend

### ISSUE THREAD

**Issue by bachus03** [DivanteLtd/vue-storefront#1677]
Os ubuntu 16.04
node 10.9.0
docker 18.06.1-ce, build e68fc7a
yarn 1.9.4
docker-compose  1.22.0, build f46880fe

When I run the yarn installer I get error like this:

![screenshot from 2018-09-01 16-13-01](https://user-images.githubusercontent.com/37640343/44946909-49248600-ae05-11e8-9829-3815b0f4c32d.png)

/home/bachu/vue_fun/vue-storefront/var/log/install.log  
![image](https://user-images.githubusercontent.com/37640343/44946791-3d37c480-ae03-11e8-9e1b-42829e7b8c8e.png)

/home/bachu/.npm/_logs/2018-09-01T14_08_11_767Z-debug.log
![screenshot from 2018-09-01 16-35-36](https://user-images.githubusercontent.com/37640343/44946898-23977c80-ae05-11e8-9a5e-2d4a6f2aed81.png)

What I am doing wrong?

**Comment by bachus03** [comment]
Found the solution: https://stackoverflow.com/questions/52128212/npm-not-installing-package-hostname-ip-doesnt-match-certificates-altnames

**in my case I needed Add the line to /etc/hosts:**

1.1.1.1  a.sni.fastly.net.

**Comment by pkarw** [comment]
Thanks! Could You please add this solution to the doc/FAQ and recipes.md? If everything is fine please also close this issue
