### ISSUE TITLE
Can't install backend npm

### ISSUE THREAD

**Issue by bachus03** [DivanteLtd/vue-storefront#1678]
Os ubuntu 16.04
node 10.9.0
docker 18.06.1-ce, build e68fc7a
yarn 1.9.4
docker-compose  1.22.0, build f46880fe

When I run the yarn installer I get error like this:

![screenshot from 2018-09-01 16-13-01](https://user-images.githubusercontent.com/37640343/44946909-49248600-ae05-11e8-9829-3815b0f4c32d.png)

/home/bachu/vue_fun/vue-storefront/var/log/install.log  
![image](https://user-images.githubusercontent.com/37640343/44946791-3d37c480-ae03-11e8-9e1b-42829e7b8c8e.png)

/home/bachu/.npm/_logs/2018-09-01T14_08_11_767Z-debug.log
![screenshot from 2018-09-01 16-35-36](https://user-images.githubusercontent.com/37640343/44946898-23977c80-ae05-11e8-9a5e-2d4a6f2aed81.png)

What I am doing wrong?

**Comment by Decntdefalt** [comment]
Did you find any solution to this?

**Comment by rebinti** [comment]
Any idea for the above issue???

**Comment by rizwan-i-khan** [comment]
any solutions for this?

**Comment by sdwebdesign** [comment]
any update on this?

**Comment by zuls** [comment]
facing the same problem.
