### ISSUE TITLE
Run in docker container ? Or link with existing containers ? 

### ISSUE THREAD

**Issue by sezio** [DivanteLtd/vue-storefront#1685]
Hi, 

I have the following docker config for a project I'm working on : 3 docker containers already linked to each others, that I use as my development environment : 
* 1 container I use as a webserver, with the sources on a volume I share with my host 
* 1 container for mysql, db data shared on a volume
* 1 container for elastic search (for other purposes than vue-storefront)

From what I see, docker-compose is required to use vue-storefront so (maybe I missed something) how can I do if I want to run it in an existing container (as I don't have a webserver / any php version installed on my host) ? 
Is there a way to docker-compose up the api in a fourth container that would connect to the db container ? 

Let me know if I'm not clear enough. Maybe I missed something that could solve the problem ? 
I currently have errors when I run the "yarn installer" command in the "Installing backend npm" step, from within my container (as docker-compose is not installed in my container, I assume this is normal)

Thanks!

**Comment by stuartz-VernonCo** [comment]
use a docker-compose.yml file to run all four of your containers and link them.  For an example of a docker-compose file linking containers, view https://docs.docker.com/compose/compose-file/#depends_on
