### ISSUE TITLE
Potential memory leaks on SSR Vue components and Event Bus

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1686]
Related to: https://github.com/DivanteLtd/vue-storefront/issues/1651

There may potential memory leaks in `created` and `beforeCreate` lifecycle hooks on server side.
 If there are any global side effects created in this lifecycle hooks they are deleted mostly on `destroyed` or `beforeDesktroy`which are platform specific so the side effects can remain on the server side. This applies mostly to places where we are setting EventBus listeners on platform-agnostic lifecycle hooks.

Ideally you should investigate if problem occurs and move all logic that produce global side effects to platform-specific lifecycle hooks

**Comment by pkarw** [comment]
Good observation. Could You please find and give one specific example from VS code base? @filrak

**Comment by pkarw** [comment]
https://github.com/vuejs/vue/tree/dev/packages/vue-server-renderer#externals-caveats

**Comment by pkarw** [comment]
https://github.com/vuejs/vue/issues/5089

**Comment by pkarw** [comment]
Here is an report (in Polish - but You can get an idea) made by @tomasz-duda 
[vsf-mem-leak.pdf](https://github.com/DivanteLtd/vue-storefront/files/2345280/vsf-mem-leak.pdf)

**Comment by filrak** [comment]
@pkarw our checkout is a perfect example ;)
https://github.com/DivanteLtd/vue-storefront/blob/master/core/pages/Checkout.js#L88
```js
  created () {
    // TO-DO: Dont use event bus ad use v-on at components (?)
    this.$bus.$on('network-before-checkStatus', this.onNetworkStatusCheck)
    // TO-DO: Use one event with name as apram
    this.$bus.$on('cart-after-update', this.onCartAfterUpdate)
    this.$bus.$on('cart-after-delete', this.onCartAfterUpdate)
    this.$bus.$on('checkout-after-personalDetails', this.onAfterPersonalDetails)
    this.$bus.$on('checkout-after-shippingDetails', this.onAfterShippingDetails)
    this.$bus.$on('checkout-after-paymentDetails', this.onAfterPaymentDetails)
    this.$bus.$on('checkout-after-cartSummary', this.onAfterCartSummary)
    this.$bus.$on('checkout-before-placeOrder', this.onBeforePlaceOrder)
    this.$bus.$on('checkout-do-placeOrder', this.onDoPlaceOrder)
    this.$bus.$on('checkout-before-edit', this.onBeforeEdit)
    this.$bus.$on('order-after-placed', this.onAfterPlaceOrder)
    this.$bus.$on('checkout-before-shippingMethods', this.onBeforeShippingMethods)
    this.$bus.$on('checkout-after-shippingMethodChanged', this.onAfterShippingMethodChanged)
  },
  destroyed () {
    this.$bus.$off('cart-after-update', this.onCartAfterUpdate)
    this.$bus.$off('cart-after-delete', this.onCartAfterUpdate)
    this.$bus.$off('network-before-checkStatus', this.onNetworkStatusCheck)
    this.$bus.$off('checkout-after-personalDetails', this.onAfterPersonalDetails)
    this.$bus.$off('checkout-after-shippingDetails', this.onAfterShippingDetails)
    this.$bus.$off('checkout-after-paymentDetails', this.onAfterPaymentDetails)
    this.$bus.$off('checkout-after-cartSummary', this.onAfterCartSummary)
    this.$bus.$off('checkout-before-placeOrder') // this is intentional exception as the payment methods are dynamically binding to the before-placeOrder event
    this.$bus.$off('checkout-do-placeOrder', this.onDoPlaceOrder)
    this.$bus.$off('checkout-before-edit', this.onBeforeEdit)
    this.$bus.$off('order-after-placed', this.onAfterPlaceOrder)
    this.$bus.$off('checkout-before-shippingMethods', this.onBeforeShippingMethods)
    this.$bus.$off('checkout-after-shippingMethodChanged', this.onAfterShippingMethodChanged)
  },
```

**Comment by pkarw** [comment]
@filrak could you provide the solution for this particular case as an example?

Can we also test if it’s a real case for us? We need to be sure it’s causing a problems before solving it as this way of hooking the events is pretty popular in the app

Would be great if you can take 2h and test it maybe?

**Comment by pkarw** [comment]
Most of these events are used to update the UI based on use actions and are just unnecessary server side. We can check if Vue.prototype.$isServer and of true - skip binding the events probably

**Comment by filrak** [comment]
@pkarw moving the listeners to `beforeMount` or `mounted` hooks will be enough but as I mentioned at the beginning  (and as you also mentioned) first we need to be sure if it's producing this leaks so if anyone si willing to take this issue please start with this investigation :).

**Comment by filrak** [comment]
Update, @tomasz-duda confirmed leaks
