### ISSUE TITLE
Move development to "development" branch and make "master" stable

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#169]
@filrak can you be in charge of it?

@patrykpiston @mercs600 please notice this change!

**Comment by Igloczek** [comment]
@filrak now we have `develop` branch (I see you already merged few PR here 👍 ), but probably will be nice to add info somewhere in the docs about it and the git-flow rules.

**Comment by pkarw** [comment]
Added info to the contributing docs
