### ISSUE TITLE
Category filters not importing from magento 2

### ISSUE THREAD

**Issue by bachus03** [DivanteLtd/vue-storefront#1690]
As described here https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Feature%20list.md "Layered / Faceted Navigation for filtering of products in categories" **I am expecting that the filters will be created automatically** in vuestorefront after full import from magento 2, Am I wrong?

1. I have followed this:
https://medium.com/@piotrkarwatka/vue-storefront-how-to-install-and-integrate-with-magento2-227767dd65b2 to install vuestorefront and integreate it with magneto 2. After some struggles it worked as espected. 

2. Then I did "Initial Vue Storefront import" like describe here https://github.com/DivanteLtd/mage2vuestorefront . I actually run:

- [ ] node --harmony cli.js categories --partitions=1 --removeNonExistient=true
- [ ] node --harmony cli.js productcategories --partitions=1
- [ ] node --harmony cli.js attributes --partitions=1 --removeNonExistient=true
- [ ] node --harmony cli.js taxrule --partitions=1 --removeNonExistient=true
- [ ] node --harmony cli.js products --partitions=1 --removeNonExistient=true

3. Next I did full reindex using npm **run db rebuild -- --indexName=vue_storefront_catalog** comand

I had clean magento 2 installation with 3 products and one extra filterable attibutte wihich works with default magento 2 luma.

**Expected result**
- see the filter on vuestorrefront

Also how to change the default vaules for price filtering ?
Thanks.

**Comment by pkarw** [comment]
This is not an issue. The filter list is not being populated automatically. You need to add the filters You'll like to have displayed to the `config/local.json` field name is: `defaultFilters`

And then You can use proper controls for each individual filter in here:
https://github.com/DivanteLtd/vue-storefront/blob/49dc8a2dc9326e9e83d663cc27f8bb0688525f13/src/themes/default/components/core/blocks/Category/Sidebar.vue

**Comment by bachus03** [comment]
Thanks a lot, I am just starting playing with VS.

**Comment by bachus03** [comment]
@pkarw Unfortunetly it didn't work. I have edited the config/local.json 
![image](https://user-images.githubusercontent.com/37640343/45002681-c56fc280-afd9-11e8-8e31-0863fa2d3a98.png) and now category page is not loading at all. I can see to blue loading bar moving but noting more is happening. When I try to enter direct category url i get 404 error?
In Category/Sidebar.vue I can see the "else" for other than default attributes so it schould work in some default way? 

Schould I create separate issue for this?
