### ISSUE TITLE
error production

### ISSUE THREAD

**Issue by marcelowu** [DivanteLtd/vue-storefront#1691]
![1](https://user-images.githubusercontent.com/30912144/44997114-59ae3b00-af82-11e8-947b-363bdb3d3eaa.JPG)
![2](https://user-images.githubusercontent.com/30912144/44997115-59ae3b00-af82-11e8-982a-393ee348938d.JPG)
![default](https://user-images.githubusercontent.com/30912144/45008381-b50b1800-afd8-11e8-97da-4ad170c91965.PNG)

**Comment by pkarw** [comment]
Please provide us with the `vue-storefront` logs (`yarn pm2 logs server` or `yarn pm2 monit server`)

**Comment by marcelowu** [comment]
![1](https://user-images.githubusercontent.com/30912144/45001339-9be77480-afa2-11e8-8635-a5db94ec85fe.JPG)
![2](https://user-images.githubusercontent.com/30912144/45001340-9be77480-afa2-11e8-96b9-e538d207d12d.JPG)
![3](https://user-images.githubusercontent.com/30912144/45001341-9be77480-afa2-11e8-93e8-dce456929952.JPG)

**Comment by pkarw** [comment]
Ok, try to run "npm run db rebuild" in the vsapi folder at first

**Comment by marcelowu** [comment]
![default](https://user-images.githubusercontent.com/30912144/45011127-54370c00-afe7-11e8-91db-11b7d0758152.PNG)

**Comment by marcelowu** [comment]
![default](https://user-images.githubusercontent.com/30912144/45011781-bc3b2180-afea-11e8-9907-67e0b0003b43.PNG)

**Comment by marcelowu** [comment]
thanks..
