### ISSUE TITLE
Populate elasticCache collection after SSR reload

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1698]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

Currently the offline cache (indexedDb - elasticCache collection) is populated only when user clicks thru categories in the CSR (client's side rendering) mode. We should populate the caceh after full page reload with the window.__INITIAL_STATE__ otherwise offline mode won't work for the products loaded in the SSR

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by pkarw** [comment]
Probably the easiest and most safe way to populate the cache is to just call the ‘product/list’ in the background (correct, it’s separate request but the INITIAL_STATE doesn’t contain all the product attributes thereferore we couldn’t populate cache with it)

**Comment by pkarw** [comment]
We need to run exactly this kind of request: 
https://github.com/DivanteLtd/vue-storefront/blob/41ec50deebd183e08c4b59a3eca1a58b101f61c0/core/modules/catalog/store/category/actions.ts#L284

**Comment by patzick** [comment]
With this issue also Homepage products should be cached for offline use on first page render
