### ISSUE TITLE
Create a VS backend mock server

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1700]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the motivation / use case for changing the behavior?**

Right now to play with VS on your own backend is required. It makes jumping into it quite harder even with our demo instance since it's impossible to track flow of data changes etc. Not to mention testing some specific use cases with additional attributes etc.

Ideally we should have mock server for our backend which will allow us to run VS frontend locally without any backend dependency. It'll also allow frontend developers to quickly change the data formats and test new fucntionalities without digging into backend (like we had to do with content CMS integration)

I recommend using [json-server](https://github.com/typicode/json-server) for mock server and [faker](https://github.com/marak/Faker.js/) for generating data but if you feel comfortable with other solutions feel free to use them..

**Comment by pkarw** [comment]
It's been done with the Simple API example in the integration SDK: https://github.com/DivanteLtd/vue-storefront-integration-sdk/tree/tutorial/sample-api-js
