### ISSUE TITLE
Getting error while starting VS in docker after upgrade to v1.3.1

### ISSUE THREAD

**Issue by kovinka** [DivanteLtd/vue-storefront#1706]
* [bug] **Getting error while starting VS in docker after upgrade to v1.3.1**
<img width="697" alt="screen shot 2018-09-06 at 21 35 48" src="https://user-images.githubusercontent.com/10535709/45215604-a6598500-b2a6-11e8-8ba3-dd39bd77fa80.png">

**Additional info:**
  - all files connected to docker, webpack or typescript configuration are not modified;
  - themes and extensions are temporary removed from the project;
  - previous VS (1.2) works well in docker;
  - running VS (1.3) on non-docker environment in development/production mode is successful (localhost:3000)

**vue-storefront.sh:**
```
#!/bin/sh
set -e

yarn install || exit $?

yarn build:client && yarn build:server || exit $?

if [ "$VS_ENV" = 'dev' ]; then
  yarn dev
else
  yarn start
fi
```

**Dockerfile:**
```
FROM node:8-alpine

ENV VS_ENV prod

WORKDIR /var/www

COPY package.json ./

RUN apk add --no-cache --virtual .build-deps ca-certificates wget git \
  && yarn install --no-cache \
  && apk del .build-deps

COPY docker/vue-storefront/vue-storefront.sh /usr/local/bin/

CMD ["vue-storefront.sh"]
```
**default.env:**
```
NODE_CONFIG_ENV=docker
VS_ENV=prod
BIND_HOST=0.0.0.0
PM2_ARGS=--no-daemon
```

**Steps to reproduce:**
  - clone the repository
  - run *docker-compose up* inside the project

**Fresh installation:**
<img width="973" alt="screen shot 2018-09-07 at 15 10 55" src="https://user-images.githubusercontent.com/10535709/45218527-8c24a480-b2b0-11e8-9fdc-03bab07db125.png">

**Local Environment:**
  - OS: MacOS
  - Docker: 18.06.1
  - Language: [TypeScript 3.0.3 | NodeJS - 8.11.4 | npm - 5.6.0 | yarn - 1.7.0]

**Docker Environment:**
  - OS: Linux 
  - Language: [TypeScript 3.0.1 | NodeJS - 8.11.4 | npm - 5.6.0 | yarn - 1.6.0]

**Comment by pkarw** [comment]
@vue-kacper can You please test this issue as You're testing it on Linux anyway?

**Comment by kovinka** [comment]
@pkarw fixed issue by adding missing lines/files to volumes config in docker-compose.yml
```
- './tsconfig.json:/var/www/tsconfig.json'
- './shims.d.ts:/var/www/shims.d.ts'
```
Docker starts now. Is it correct fix?

**Comment by pkarw** [comment]
@kovinka yes, please create Pull Request for it

**Comment by kovinka** [comment]
@pkarw done, please review PR.

**Comment by pkarw** [comment]
Thanks! Merged in :-)
