### ISSUE TITLE
Make intelisense for modules working with lerma

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1719]
* [bug] **What is the current behavior?**
When using intelisense on VS modules imported by alias `@vue0storefront/core/modules` we are not receiving intelisense description for the method

![image](https://user-images.githubusercontent.com/15185752/45349643-25560280-b5b2-11e8-9bf9-b1f9955857c9.png)
(it displays only import but i needed to press shift to make screenshot ^^)
* [bug] **What is the expected behavior?**
It should display appropiate feature description with intelisense
![image](https://user-images.githubusercontent.com/15185752/45349527-c55f5c00-b5b1-11e8-96a5-cec13fc8dbe2.png)

* [bug] **Please provide the steps to reproduce and if possible a minimal demo of the problem** 
Go to `/core/components/blocks/Microcart/Microcart.js` and try to have intelisense in any of elements imported with `@vue-storefront` alias

* **What is the motivation / use case for changing the behavior or adding new feature?**
Better dev experience ;)

* **Acceptance criteria**
- [ ] after importing module features using `@vue-storefront` alias it should display the intelisense description

Probably you should start with `tsconfig` or `jsconfig` (merge them :) ) and see if you can fix it from there

**Comment by pkarw** [comment]
@filrak can you close this ticket till 6th (planned date for 1.4)?

**Comment by filrak** [comment]
sure but it's kind of important

**Comment by pkarw** [comment]
close means => make it happen not physically close :D

**Comment by filrak** [comment]
now it's done ^^
