### ISSUE TITLE
Add Open Loyalty integration as a extension

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1720]
* **What is the motivation/use case for changing the behavior or adding a new feature?**

We would like to synchronize all the events + user transactions with openloyalty.io using the API. We should've been able to display the points + redeem coupon codes from OLOY in the VS checkout as well.

* **Acceptance criteria**
- [ ] we're recording the transactions from VS to Open Loyalty
- [ ] we're displaying the rewards information in Vue Storefront for logged in user

**Comment by filrak** [comment]
I can take care of this next month ;)
