### ISSUE TITLE
GraphQL improvements

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1721]
* **What is the motivation/use case for changing the behavior or adding new feature?**

We need to make graphQL more extendable. Of course - one can use `AppoloQuery` to directly query the data but still many users will be using `SearchQuery` and vuex stores maintaining the API/graphQL interoperability. 

* **Acceptance criteria**
- [x] Add the mechanism to extend the graphQL queries / entity types: https://github.com/DivanteLtd/vue-storefront/pull/1616/files#r216917642
- [x] Add support for `_sourceInclude` and `_sourceExclude` fields  - https://github.com/DivanteLtd/vue-storefront/pull/1616/files#r216919147 - it should be passed from frontend to backend (currently it's being configured in the backend only which may be misleading for the developers (as for ES it's passed from frontend to backend). Moreover to have this "progressive caching" feature up and running the frontend must have a choose which fields is it fetching: https://github.com/DivanteLtd/vue-storefront/blob/2aee2fc4cc98341dcc643916dc118c96568daeec/core/store/modules/category/actions.ts#L156 (the fields list vary on the case - once we're getting full product list other time just a limited number of fields)
- [x] Get rid off te warning `<ApolloProvider>.provide() is deprecated. Use the 'apolloProvider' option instead with the provider object directly.`

Anyway, great job with this graphQL support!

**Comment by filrak** [comment]
Maybe we can completely switch to Apollo?
