### ISSUE TITLE
Bundle product price is presented without the tax

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1723]
The product page - price is Net = 73:
![screenshot 2018-09-12 10 03 27](https://user-images.githubusercontent.com/211899/45410930-3d418b00-b673-11e8-937e-bf8006ebfae9.png)

In micro cart - we do have the price with tax (23%)
![screenshot 2018-09-12 10 03 33](https://user-images.githubusercontent.com/211899/45410960-4af71080-b673-11e8-8ac7-bde7c696df0b.png)

* **Acceptance criteria**
- [ ] Tax should be applied on the Bundle product page

**Comment by pkarw** [comment]
To check: https://github.com/DivanteLtd/vue-storefront/blob/813857a51219cf0467bf5d437493630c12819d26/core/pages/Product.js#L142

**Comment by pkarw** [comment]
It may be related to the issue we've discovered with the mage2vuestorefront: https://github.com/DivanteLtd/mage2vuestorefront/blob/ada7a243245597bd7634bbdfbb338307998f499d/src/adapters/magento/product.js#L103

**Comment by vue-kacper** [comment]
On develop branch I get the same price on product page as in shopping cart

![p1](https://user-images.githubusercontent.com/42430550/45417208-edb68b80-b681-11e8-9c45-e2c5d4e1c38d.PNG)

![p2](https://user-images.githubusercontent.com/42430550/45417216-f14a1280-b681-11e8-9dbd-b2218d3cb8a4.PNG)

**Comment by pkarw** [comment]
OK, seems like sth is wrong with my config then :/ Closing for now
