### ISSUE TITLE
Is it normal that npm i != yarn?

### ISSUE THREAD

**Issue by zadigus** [DivanteLtd/vue-storefront#1725]
* [bug] **What is the current behavior?**

```npm install != yarn```

If I do

```
npm install
npm run installer:ci
```
then some packages are missing to let the installation / app execution work.

* [bug] **What is the expected behavior?**

```
npm install
npm run installer:ci
```
is equivalent to
```
yarn
yarn installer --default-config
```
My motivation is pretty simple: I am willing to deploy the application on a Jelastic system where each node reboot triggers an `npm install` which everytime breaks my installation.

**Comment by pkarw** [comment]
This won't be possible :( We're using `Lerna` to handle Multirepo and it requires `yarn` https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Monorepo.md

**Comment by zadigus** [comment]
Yeah but why is the output of 
```
npm install
```
so much different from that of 
```
yarn
``` 
? That should at least match, shouldn't it?

**Comment by pkarw** [comment]
It's pretty different as Lerna is creating lot of symlinks for `@vue-storefront/core` and other "virtual" modules, we cannot use npm anymore :(
