### ISSUE TITLE
Intellisense does not work w/ VS Code + Vetur

### ISSUE THREAD

**Issue by cmeyertons** [DivanteLtd/vue-storefront#1727]
* [bug] **What is the current behavior?**
Intellisense (go to definition, etc.) does not work w/ VS Code + Vetur in .vue files 

* [bug] **What is the expected behavior?**
These should work out of the box

I attempted tweaking the jsconfig.json w/o luck

* [bug] **Please provide the steps to reproduce and if possible a minimal demo of the problem** via
1. Pull master
1. go to `src/themes/default/core/components/ProductsSlider.vue` and attempt to go to definition on both the ProductSlider and ProductTile imports 

* [bug] **Please tell us about your environment:**
  - Version: MacOS (latest VS code and Vetur)
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all ]

* **What is the motivation / use case for changing the behavior or adding new feature?**
Going to definition / autocomplete is important to anyone who doesn't have intimate knowledge of the underlying framework and should be available out of the box.

* **Acceptance criteria**
- [ ] Using .vue files should have the equivalent development experience as other projects

**Comment by pkarw** [comment]
Not sure if it's related to https://github.com/DivanteLtd/vue-storefront/issues/1719

@filrak ?

**Comment by filrak** [comment]
Yes it's related to lerma  and `@vue-storefront ` alias that is not recognized by InteliSense

**Comment by cmeyertons** [comment]
looks like this is already an issue logged against Vetur:

https://github.com/vuejs/vetur/issues/890
