### ISSUE TITLE
Catalog view infinite scroll not working on mobile 

### ISSUE THREAD

**Issue by jorkvist** [DivanteLtd/vue-storefront#1733]
* [bug] 
  - Version: 
  - Browser: Firefox 62.0.1 | Mobile Chrome 69.0.3497.91

Products lazyload (infinite scroll) is broken on mobile, when scrolling to the bottom, no new products is loading. Tested on my live site but also on https://demo.vuestorefront.io/

(bonus, the counter is not working always says 50 items)

**Comment by pkarw** [comment]
@mdanilowicz @vue-kacper or @qiqqq could you please take a look  at this one, please?
