### ISSUE TITLE
Broken menu link on PDP

### ISSUE THREAD

**Issue by jorkvist** [DivanteLtd/vue-storefront#1734]
* [bug] **What is the current behavior?**
When going to a product with a direct link, fx: https://demo.vuestorefront.io/p/WS12/radiant-tee-1561/WS12 the menu in the left upper corner is expected, instead an arrow is shown and when that's clicked the visitor goes to a invalid route and jumps of the site. 

* [bug] **What is the expected behavior?**
Show menu instead when a user not comes from internal link. 

* [bug] **Please tell us about your environment:**
  - Version: 
  - Browser: Chrome 69.0.3497.92

**Comment by mdanilowicz** [comment]
@jorkvist Thank you for reporting
