### ISSUE TITLE
Move theme specific translations to the theme

### ISSUE THREAD

**Issue by DavidRouyer** [DivanteLtd/vue-storefront#1737]
* [bug] **What is the current behavior?**

Strings translations used in the theme are specified in the core files.

* [bug] **What is the expected behavior?**

Strings translations specific to the theme should be in `src/themes/<theme>/resource/i18n`

* **What is the motivation / use case for changing the behavior or adding new feature?**

- Leaner core
- Make it clearer of what to override
- Can remove unused translations

**Comment by filrak** [comment]
it's ok, @pkarw is on vacation so feel free to go on with this one :d

**Comment by DavidRouyer** [comment]
You've already merged it so I'm closing it 😄
