### ISSUE TITLE
Get rid of cart-after-itemchanged event

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1742]
* **What is the motivation / use case for changing the behavior or adding new feature?**
We are slowly moving to more reliable and easier to debug architecture which includes removing event-based scenarios.

The task here is to rewrite all `cart-after-itemchanged` event-based functionalities to ones relying on Vue reactivity system and Vuex. The cart object should only change in Vuex and components (like `product.js`) should be just displaying the Vuex state. 
These are the files that are relying on this event (may be some more)
![image](https://user-images.githubusercontent.com/15185752/45751299-3fc35800-bc12-11e8-9381-810345b75b4c.png)

* **Acceptance criteria**
- [ ] Remove `cart-after-itemchanged` event-based behavior
- [ ] Use native vue reactivity instead

**Comment by pkarw** [comment]
The main reason for having this event is to update the microcart information adding info about stock etc and were emitting this event to do forceUpdate on the micro art product item. So maybe just using Vue.set instead would have solved the initial issue which caused adding this event

**Comment by diboy2** [comment]
@vaggelisk, are you still working on this issue? I'd like to work on it.

**Comment by vaggelisk** [comment]
@diboy2  after a discussion with a main contributor, he informed me that the issue is quite difficult, so I started to work with another.
