### ISSUE TITLE
RFC: i18n

### ISSUE THREAD

**Issue by DavidRouyer** [DivanteLtd/vue-storefront#1749]
- Feature Name: i18n overhaul
- Start Date: 2018-09-20
- RFC PR: 

# Summary
[summary]: #summary

Overhaul of the i18n module by:
 - Supporting multistore scenarios & multilanguage stores
 - Move all the translations into one JSON file inside the theme, and introduce core/modules/extensions translation keys scoping
 - Add a mechanism for modules to expose translations keys & add warnings for missing translations keys for enabled languages in development mode
- BONUS: better translation key naming

# Motivation
[motivation]: #motivation

As of today, we only support multistore scenarios.
It's impossible to know which translation key is exposed by a module or an extension and it's hard to find them because they are all mixed up.
We have to merge files and convert them from CSV files.
As the translations keys are not in the theme file, I don't know what are the default translations and I don't know which languages are supported. If I want to translate my store in Latin, I have to implement ALL core translations keys.
Translations keys can clash: if I add an extension with an existing core translation key I can override it without knowing it

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation

Example of the new translation files:
```json
{
  "core": {
    "ok": "OK",
    "remove-compare": "Remove from compare",
    "resetting-password": "Resetting the password ...",
    "error-reset-password-email": "Error while sending reset password e-mail"
  },
  "offline-order": {
    "confirm-order-offline": "Your order has been confirmed but you're offline"
  },
  "google-analytics": {
    "cookie-google-analytics": "This website uses Google Analytics"
  },
  "home": {
    "home-page": "This is our home page"
  },
  "about": {
    "introduction": "Introducing our team"
  }
}
```

How to use them?

`t('core.ok')`

Each time you add a page, a module or an extension, you add the scoped section inside the JSON file and you add the translations exposed by the module/extension.

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation

# Drawbacks
[drawbacks]: #drawbacks

The users who wants to upgrade will have to migrate their CSV files to the new format.

# Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

# Prior art
[prior-art]: #prior-art

# Unresolved questions
[unresolved-questions]: #unresolved-questions

**Comment by filrak** [comment]
Totally agree that it's a good way, now it's such a mess

Regarding extension scoping - extensions will also be a modules so I'm wondering if the separation is needed. H

**Comment by DavidRouyer** [comment]
extension/modules -> they work the same way so if the extension concept disappear, it doesn't impact this :)

**Comment by pkarw** [comment]
I understand this need and why this RFC is proposed but I always was a fan of simple solutions - and these abstract labels are not something I like. The code is a little bit less readable and writing any new feature you must remember to add the translation strings. In exchange you have simpler and more elegant translation files.

For sure, if we decide to implement this, we should have backward compatibility with config option for current users.

I would like to hear others opinion on that as this is pretty massive change @Igloczek @phoenix-bjoern  @qiqqq @mercs600

**Comment by DavidRouyer** [comment]
I haven't finished writing it :sweat_smile:

I hope you're kidding about translations keys. Actual translations keys are unmanageable because some of them takes 3 lines and they'll break with every typo.

**Comment by DavidRouyer** [comment]
And we have to understand users will adapt those strings for their stores, so it's misleading for them if they have a string which translates to another. It's our job to write understandable translations keys (we have ~50 strings in the core, it should be feasible).

**Comment by Igloczek** [comment]
I like this idea, for example, [Redmine](https://www.redmine.org/) and other RoR based apps translations are done in the same way and I really enjoy working with it.

**Comment by pkarw** [comment]
OK folks, If You like to go with this idea we can do it. The only thing is how to migrate automatically old translation files to new ones?

We need such a mechanism. Probably just mapping (kind of hash or ... translation file ;P) the old identifiers to new ones + find & replace in files automatically in the theme is a solution.

Or some other way to keep the themes update'able?

**Comment by shkodasv** [comment]
How to load only required languages on the site and avoid loading all available files from core/i18n/resource/i18n?
<img width="694" alt="langs-prefetch" src="https://user-images.githubusercontent.com/837554/47421643-b3b0cd00-d789-11e8-9dcb-32721df4c1d8.png">

Another thing. After update to 1.3 translations don't work. What are the requirements for them? 

My translations are in src/themes/[MYTHEME]/resource/i18n/*.csv. In config it is set 
`"i18n": {
    "defaultCountry": "AT",
    "defaultLanguage": "DE",
    "availableLocale": ["de-DE", "de-AT"],
    "defaultLocale": "de-AT",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dateFormat": "HH:mm D.M.YYYY",
    "fullCountryName": "Austria",
    "fullLanguageName": "German"
  },`

But I see the messages in EN only.
