### ISSUE TITLE
[CONSOLE LOG] Prevent log to be printed unless configuration for is true

### ISSUE THREAD

**Issue by lorenaramonda** [DivanteLtd/vue-storefront#1752]
The long list of logs into the console it's too thick and sometimes makes hard to debug own component. I suggest thinking about using a method that, instead of using console.log() directly, first checks if the config for logs is set and is true and then console.log().
In any case, logs shouldn't be printed in production mode like vuejs framework already does.

**Comment by pkarw** [comment]
Good idea. It should be set in config - we’ve moved to console.debug in most places but chrome displays the message anyway

**Comment by DavidRouyer** [comment]
Why not printing anything unless there is a problem?

**Comment by pkarw** [comment]
That’s fine - please just make it configurable for some dev. scenarios as well?

**Comment by pkarw** [comment]
@NataliaTepluhina I've added the configuration option:

```json
    "console": {
      "verbosityLevel": "only-errors"
    },
```

Available options: `only-errors` - displays only error messages, `no-console` - silent mode, `display-everything` - displays everything (it may be usefull for development purposes)

Could You please update the docs with this info?
