### ISSUE TITLE
Problem with filter labels + selected filters

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1753]
Related to:
#1747 #1750 

-----------------------------------
* [bug] **What is the current behavior?**

1. Missed dynamic translations for “filter_” + attr.code - to be reproduced on test.vuestorefront.io @DavidRouyer can You please add the translations to the theme file + check if there are other cases like this one (I don’t remember if there are other cases such like this - probably safest way is to check all t() references)? These translation keys are referenced from Category/SidebarMenu.vue 

2. Selected filters are not marked on iOS (the same is on both: demo so master branch and test.vuestorefront.io - develop branch) @vue-kacper 

![cfda6292-c303-4ab9-b1fd-dfc7e89a52de](https://user-images.githubusercontent.com/211899/45915560-29f2a480-be57-11e8-9705-431c656765e8.png)

* [bug] **What is the expected behavior?**

* [bug] **Please provide the steps to reproduce and if possible a minimal demo of the problem** 

The problem is visible on test.vuestorefront.io - any category

* [bug] **Please tell us about your environment:**
  - Version: 
  - Browser: Chrome on iOS (latest)

* **Acceptance criteria**
- [ ] selected filters are marked 
- [ ] filter labels are translated

**Comment by DavidRouyer** [comment]
It is possible that I've missed a few ones, will take a look

**Comment by pkarw** [comment]
Thanks David, You’re the man!

**Comment by pkarw** [comment]
@vue-kacper steps to reproduce this issue on my iOS:
- open filters
- check some color, size (filters are marked as selected)
- close filters pop up
- open it again - none of previously selected filters are active
