### ISSUE TITLE
Pricefilter on category page return wrong products

### ISSUE THREAD

**Issue by jorkvist** [DivanteLtd/vue-storefront#1760]
* [bug] Goto https://demo.vuestorefront.io/c/women-20 
Click filter on the pricefilter: <50 and look at the list, second in the list is 
"Erika Running Short" cost: $55.35

* [bug] **What is the expected behavior?**
Expected not showing any product outside the filtered interval 

* [bug] **Please tell us about your environment:**
  - Version: 
  - Browser: Chrome Desktop Latest

**Comment by pkarw** [comment]
This is because the filter by deafault uses price field which is price Net to filter
