### ISSUE TITLE
Main menu, a few different bugs 

### ISSUE THREAD

**Issue by jorkvist** [DivanteLtd/vue-storefront#1761]
- When you have a lot of items in level 2 and 3, there is a scroll on level 1 in the menu. 
- When one category with few items in the level 2, but in another subcategory in level 2 have more items, those items showing up under the wrong subcategory. ( Test on: ribatex.se click fx Fiskerullar in the menu and scrool down. The items that coming in the bottom is from another category. )
- When a category have none active subcategories, its expected that if you click it, it will not fold out a submenu. (This seams to happen when you have magento setting "show in menu: no" on the child.) 

* [bug] **Please tell us about your environment:**
  - Version: 
  - Browser: Chrome

**Comment by qiqqq** [comment]
@jorkvist I will check this bugs and try to fix it next week

**Comment by filrak** [comment]
it's fixed on current dev
