### ISSUE TITLE
The currency sign is not corrected displayed for price filter on catalog page

### ISSUE THREAD

**Issue by dimasch** [DivanteLtd/vue-storefront#1765]
The currency sign is not corrected displayed for price filter on catalog page.

![2018-09-25_22-27-42](https://user-images.githubusercontent.com/414067/46034703-63a30400-c112-11e8-8ebe-78b848a0ee6f.png)

### Expected result
Currency sign displayed for the price filter accordance by config settings.

### Reproduce
Set custom `currencySign` in you local.json 
```
"i18n": {
      ...,
      "currencySign": "£",
      ...
    },
```

### Related line of code 
https://github.com/DivanteLtd/vue-storefront/blob/19618fc3fa89d08651b1708bb4f044e1823ef45c/core/store/modules/category/actions.ts#L254

**Comment by pkarw** [comment]
Can You please fix it an report PR, please?

**Comment by pkarw** [comment]
Fixed
