### ISSUE TITLE
Loading Plugin with SSR false

### ISSUE THREAD

**Issue by sansor** [DivanteLtd/vue-storefront#1766]
Looks like a very generic SSR issue which I am facing while adding new plugins. if I need to install any plugin with "ssr: false" where should I do that? Wrapping the function around <no-ssr> doesn't work as it throws while loading plugin itself.

In most of the cases, either window is not found or document is not ready are thrown. Most of the solution provided is given only for nuxt framework where they load the plugin with ssr:false in nuxt.config file.

Please pardon me if I am asking very naive questions. I am new to VUE and overall UI development.

Thanks,
Sanjay

**Comment by pkarw** [comment]
Please take a look at `no-ssr` component -> for example how sliders are placed in the `Home.vue` component; it should be clear how to use it afterwards
