### ISSUE TITLE
Base Radio Button Checked vs Value

### ISSUE THREAD

**Issue by shkodasv** [DivanteLtd/vue-storefront#1767]
Hello!
Radio buttons can have different values AFAIK, but on the core code I can see the property "value" with Boolean type. https://github.com/DivanteLtd/vue-storefront/blob/19618fc3fa89d08651b1708bb4f044e1823ef45c/core/components/blocks/Form/BaseRadiobutton.js#L8

 And it is used for attribute "checked" in https://github.com/DivanteLtd/vue-storefront/blob/19618fc3fa89d08651b1708bb4f044e1823ef45c/src/themes/default/components/core/blocks/Form/BaseRadiobutton.vue#L8

Is it a bug or there is some specific logic? 

I guess BaseRadiobutton should have "checked" and "value" separately, what do you think ?

**Comment by pkarw** [comment]
Yes, I agree with You - I think that sbd who was creating this component was just ... too specific to some individual goal/problem he or she was approaching. I believe it's good to change it and make more general. Please feel free to do so. But please also be aware of all the instances of this component and please do test them well before committing a PR :-)

**Comment by lukeromanowicz** [comment]
This bug is still valid
