### ISSUE TITLE
How to add another Resolver for different entity type from the extension/theme level?

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1769]
Related: #1721 

We need to have a doc on how to add different entity types to Elastic to be solved by GraphQL resolvers. I mean - if somebody will add custom entity (for example "Tour" entity when You're in travel industry). How to add this very custom entity to be available in GraphQL Queries?

It should be doable from the extension and theme levels.

### What is the motivation / use case for changing the behavior or adding new feature?

Currently, there is no clear way on how to extend the GraphQL data model "the right way".

### Acceptance criteria

- [ ] User can add different entity types from the extension / theme
- [ ] Would be great - but it's not required - if the user could modify the GraphQL schema of existing queries and entities from the extensions.

**Comment by yuriboyko** [comment]
Please note only entity type on the  Vue-storefront side can be created via extension.
On the API side you have to add  a subfolder under src/graphql with new resolver

**Comment by pkarw** [comment]
@yuriboyko thanks! That solves the issue!

**Comment by pkarw** [comment]
This should be still solved on the extension level. Now the vs-api extensions can hardly add new entity types - and they should

**Comment by Yoann-Vie** [comment]
I did a [PR](https://github.com/DivanteLtd/vue-storefront-api/pull/131) on vs-api to allow the graphQL custom entities creation from extension level

**Comment by pkarw** [comment]
Thanks @Yoann-Vie can You please write a short doc on how to extend GraphQL both in the vs-api and vs-front?

**Comment by Yoann-Vie** [comment]
Yes I could work on it 🙂which format do you want ? do you want a Readme file in a specific location on both projects ?

For the vs-api part I have already do a simple example in my [PR](https://github.com/DivanteLtd/vue-storefront-api/pull/131) description, do you think some details are missing ?

**Comment by pkarw** [comment]
Great! Please just add a short doc into /doc folder and let know when it’s done to @NataliaTepluhina who’s our technical writer in charge of overall docs :) thanks!

**Comment by Yoann-Vie** [comment]
@NataliaTepluhina the doc was added :) @pkarw I made a PR for it
