### ISSUE TITLE
Same item with different sizes deleted once the stock sizes error appear

### ISSUE THREAD

**Issue by Able2Code** [DivanteLtd/vue-storefront#1795]
![sizes](https://user-images.githubusercontent.com/5517831/46247362-71a29e80-c40a-11e8-872c-ea49b79219fc.gif)

**Comment by pkarw** [comment]
Fixed in https://github.com/DivanteLtd/vue-storefront/pull/1787/commits/0bc37a0f0c9f198f6fa4bf542f71bb582bab0438
