### ISSUE TITLE
Filter by, problems

### ISSUE THREAD

**Issue by Able2Code** [DivanteLtd/vue-storefront#1806]
Hi ! sorry for my delay, today also me can not reproduce the same bug, but only one very similar and, i think, related bug.
Also color filter, seldom, do not disappear when where no item corresponding.
My hd video url https://youtu.be/2YG9zQ72aqc

**Comment by filrak** [comment]
Please use a proper issue template next time

**Comment by Able2Code** [comment]
> Please use a proper issue template next time

I apologize, my mistake

**Comment by idziakjakub** [comment]
I'm on it
