### ISSUE TITLE
Adjustments for slider in mobile and rewrite the homepage hero slider

### ISSUE THREAD

**Issue by patrykpiston** [DivanteLtd/vue-storefront#181]
We should think weather or not it is a good idea to rewrite the homepage slider in such a way that it'll not be using any external library. It would be more compliant with our code and more flexible.

**Comment by karolbzik** [comment]
I will design smaller slides.

**Comment by karolbzik** [comment]
@patrykpiston let's use smaller slide image and smaller fonts for the slider in mobile, the smallest version of the RWD used in the application. I recommend changes:
![homepage mobile](https://user-images.githubusercontent.com/18116406/32462415-8dbe9d4e-c339-11e7-80fc-4ee0af5eaeb5.png).

All details including font sizes you can track in the design file here - https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront-Open-Source, in the view named "Homepage mobile".
