### ISSUE TITLE
Creatie native PIMCore indexer

### ISSUE THREAD

**Issue by ngeleedst** [DivanteLtd/vue-storefront#1834]
## What is the motivation for adding / enhancing this feature?
We should replace pimcore2vuestorefront with an native PIMCore indexer indexer. Perhaps the advanced object Search module as Foundation which will be pushing the Category, Product, Attribute, Taxrule data directly to ElasticSearch in on-demand mode and with event services.

## What are the acceptance criteria 
compatibility with mage2vuestorefront data formats; Specification: https://github.com/DivanteLtd/vue-storefront-integration-boilerplate

# Can you complete this feature request by yourself?
Maybe, but i would like a push in the right direction. DivanteLTD can you provide some additional information?

**Comment by pkarw** [comment]
We're working on this one. Please do contact us at contributors@vuestorefront.io if You like to get some details on that

**Comment by pkarw** [comment]
This has been already done with: https://github.com/DivanteLtd/coreshop-vsbridge
