### ISSUE TITLE
You can access pages reserved only for authenticated users as a guest

### ISSUE THREAD

**Issue by vue-kacper** [DivanteLtd/vue-storefront#1838]
## Current behavior

You can access pages reserved only for authenticated users as a guest. Those pages are indexed by search engines. Landing on those pages (for example from search engine) will result in bad user experience as **main menu** and **icons on the right side** doesn't work.

## Expected behavior
Guest should be redirected back or to the home page on routes dedicated for authenticated users.

## Steps to reproduce the issue

- Make sure you are logged out from demo.vuestorefront.io
- Open URL https://demo.vuestorefront.io/my-account/shipping-details
- Try to click on the main menu icon

## Additional information

Maybe we should implement route middlewares, something like nuxt has (just an idea)
https://nuxtjs.org/guide/routing/#middleware

**Comment by pkarw** [comment]
Seems like https://github.com/pkarw/vue-storefront/blob/971b5fa296b008fca20bf5c023901155cf2ac678/core/pages/MyAccount.js#L29 stopped to work. I'll check it

**Comment by pkarw** [comment]
@vue-kacper middleware approach is an optimal idea - can You please create separate issue for that + describe some assumptions how should it work?

**Comment by vue-kacper** [comment]
@pkarw Sure

**Comment by pkarw** [comment]
Closed with: https://github.com/DivanteLtd/vue-storefront/pull/1840

Ther account-related pages are no longer accessible in the SSR. 

@vue-kacper we need to have the middleware mechanism working not only client side - but even server side using Expressjs hooks. Please consider this PR: https://github.com/DivanteLtd/vue-storefront/pull/1840

in the `asyncData` which is executed server side there is context object with `context.server.app`, `context.server.request` and `context.request.response` - accesible only in the SSR. The objects = Expressjs components:

https://github.com/DivanteLtd/vue-storefront/blob/13554f68cd4c742127a34cc47bead99b8feff654/core/scripts/server.js#L156
