### ISSUE TITLE
Add the docker support for the installer

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1843]
## What is the motivation for adding / enhancing this feature?

We're able to run the Vue Storefront + Vue Storefront API solely using docker. No other requirements.
So, would be great to add the installer option to run it using docker - without the classical workflow.

To be honest, it's even simpler than current workflow. We just need to:
- clone vue-storefront
- run yarn install; yarn installer
- installer will ask You for lot of things
- in case of local vue-storefront-api - it still need to be cloned from the repo
- we need to setup the configs
- but then we're running just:

In the `vue-storefront-api`:
`docker-compose -f docker-compose.yml -f docker-compose.nodejs.yml up -d`

In the `vue-storefront`:
`docker-compose up -d`

## What are the acceptance criteria 

- There is a question in the installer "Would You like to start Vue Storefront using Docker either local Node instance? [default is the current behavior]"
- The installer runs VS using docker or local node instance accordingly

**Comment by Cyclonecode** [comment]
I can fix this.

**Comment by Cyclonecode** [comment]
@pkarw - Looking at the installer right now it seems like we both are starting the docker container and running the dev environment using `nohup npm run dev`? Shouldn't `docker-compose up -d` only be called if we're not running the api using `npm` or am I missing something here?

```
          .then(this.backend.dockerComposeUp.bind(this.backend)) <-- docker-compose up -d
          .then(this.backend.importElasticSearch.bind(this.backend))
          .then(this.backend.runDevEnvironment.bind(this.backend)) <-- npm run dev
```

**Comment by pkarw** [comment]
Yes, You should run `docker-compose up -d` in the `vue-storefront`. In the `vue-storefront-api` - when local backend has been selected - You need to run 

`docker-compose -f docker-compose.yml -f docker-compose.nodejs.yml up -d`

Please note, that in case running the Dockerized app You need to modify the restore/migrate calls to:

```
docker exec -it vuestorefrontapi_app_1 yarn restore
docker exec -it vuestorefrontapi_app_1 yarn migrate
```

Details:
https://divanteltd.github.io/vue-storefront/guide/installation/linux-mac.html#install-the-vue-storefront-api

**Comment by pkarw** [comment]
@Cyclonecode how are things with this task ?Tomorrow's hackathon is a good moment to close it :)

**Comment by Cyclonecode** [comment]
@pkarw - Completely forgot about this one, but it seems like it has been already implemented so this ticket can now be closed =)

**Comment by pkarw** [comment]
@Cyclonecode it's not yet done - there is just docker started in "classical way" - I mean running just elasticsearch + redis in the api.

We need to modify it to have VS + VS API running 100% on Docker as a result.

**Comment by Cyclonecode** [comment]
@pkarw  - Ah, I looked on the code and I understand. Ok, I will try to look on this during this week.

**Comment by ruthgeridema** [comment]
@Cyclonecode , what is the status of this issue?

**Comment by hitchhooker** [comment]
Would be cool to see compatibility with podman as well.

**Comment by Cyclonecode** [comment]
I have had too much to do lately :) but will move this up in my todo list, actually I might look on this today. Let you know what is happening.
