### ISSUE TITLE
Remove all references to imagemagick

### ISSUE THREAD

**Issue by Cyclonecode** [DivanteLtd/vue-storefront#1844]
## What is the motivation for adding / enhancing this feature?
Since vue-storefront-api now is using sharp instead of imagemagick all documentation should be updated to reflect this.

## What are the acceptance criteria 
- All documentation needs to be updated by removing all previous references to imagemagick.

# Can you complete this feature request by yourself?
Yes.

**Comment by pkarw** [comment]
Let's do this! :)
