### ISSUE TITLE
Current docker / debugging architecture

### ISSUE THREAD

**Issue by cmeyertons** [DivanteLtd/vue-storefront#1845]
## Current behavior
Currently, no source files are passed into the docker image, even for production, which does not allow the docker image to be self-sufficient (build once run anywhere).  It relies on the built packages being mapped to volume mounts, even in production

## Expected behavior
The debugging behavior should be encapsulated in the docker-compose.yml like the Microsoft VS code Node debugging recipe suggests:

https://github.com/Microsoft/vscode-recipes/tree/master/Docker-TypeScript

**Comment by Stolr** [comment]
+1 on this
