### ISSUE TITLE
Serving static assets

### ISSUE THREAD

**Issue by zadigus** [DivanteLtd/vue-storefront#1858]
Hi,

I read your [production setup documentation](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Production%20setup%20(WIP).md) and stumbled upon this:

	location /assets/ {
		proxy_pass http://localhost:3000/assets/;
	}

"The same module is used for providing user with the static assets. Assets will be available under: https://prod.vuestorefront.io/assets."

I think you want to optimize communications, don't you? I am absolutely no web expert hence I did some research over the web. It seems to be possible to prevent the nodejs server from serving these static assets which optimizes communication because any access to these assets would not be a hit to the nodejs server anymore. Assuming your vue-storefront application runs on the nginx server (but the solution works also in the case where the nginx server and the nodejs server run on different computers), what you can do is adapt the nginx configuration like this for example:

    location /assets { 
      root path-to-vuestorefront/src/themes/default/assets; 
    }

In this case, you are sure that the nodejs application isn't serving the assets and that job has been taken over by the nginx server. If your two servers don't run on the same computer, then you need to share the assets folder of the nodejs computer with the nginx computer and let nginx serve the shared folder.

**Comment by pkarw** [comment]
Yes, You can introduce this optimization  but since nginx/varnish can use the caching strategy for serving static assets the question is if it makes any sens? I mean - `/assets` is used in dev. mode - and therefore it's a straightforward way to use the same url structure in prod. You can add this note to the production docs, not a problem - please just create a PR
