### ISSUE TITLE
Error 500 when trying to visit localhost:3000

### ISSUE THREAD

**Issue by BorisZhuang** [DivanteLtd/vue-storefront#1863]
I was just following the installation guide `https://divanteltd.github.io/vue-storefront/guide/installation/linux-mac.html#requirements`, and installation process finished successfully, but error 5000 showing up when I access `http://localhost:3000`, no log in the console, no clue what's going on.
I was on Mac and used `https://demo.vuestorefront.io` as the backend.

**Comment by BorisZhuang** [comment]
[vue-storefront.log](https://github.com/DivanteLtd/vue-storefront/files/2477465/vue-storefront.log)
here is the vue-storefront.log, not sure if it's helpful.

**Comment by filrak** [comment]
From the log it looks like everything is fine. Which OS do you have? Do you use `yarn dev` cmd to set . up vs?

**Comment by allozaur** [comment]
@filrak @pkarw this issue actually occured also in my case when installing the VSF on Debian 9.5 (DigitalOcean) yesterday

https://vsf.colorshakestore.com here you can see it live

**Comment by janmyszkier** [comment]
@BorisZhuang 
steps to debug:
1. check webserver error log
2. check pm2 logs
3. check is all services are running (i.e elasticsearch) and are responding to requests

**Comment by pkarw** [comment]
Thanks @allozaur and @janmyszkier for helping out in here. Could You add this solution to our FAQ https://github.com/DivanteLtd/vue-storefront/blob/master/doc/FAQ%20and%20Receipes.md?

**Comment by allozaur** [comment]
@pkarw just waiting for approval :)

**Comment by danivadion** [comment]
@allozaur this problem is still occurring for me. I have restarted elasticsearch but still no luck.
I am on an ec2 with Amazon Linux. Currently if i try curl localhost:3000 on ec2 it returns 
(52) Empty reply from server.
