### ISSUE TITLE
Simplify ProductBundleOptions component

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/vue-storefront#1864]
## What is the motivation for adding / enhancing this feature?
ProductBundleOptions has too complex logic. This broke e2e tests lately.
Example:
https://github.com/DivanteLtd/vue-storefront/blob/868cd8f2926de0b34ab90083c5afce7133016c7e/src/themes/default/components/core/ProductBundleOptions.vue#L31

## What are the acceptance criteria 
- [ ] each option should be a separate component
- [ ] avoid concatenations such as an example above

# Can you complete this feature request by yourself?
YES

## Additional information
Related PR: https://github.com/DivanteLtd/vue-storefront/pull/1861

**Comment by filrak** [comment]
Feel free to do this, thanks!

**Comment by patzick** [comment]
PR merged, closing.
