### ISSUE TITLE
Integration with an existing Vue.js SPA for cart or nuxt.js

### ISSUE THREAD

**Issue by ghenry** [DivanteLtd/vue-storefront#1866]
Hi all,

I'd thought I'd ask here as I go no response on slack, but can add cart/checkout option be added using vue-storefront into an existing Vue.js SPA or say nuxt.js? I have loads of examples in various Vue.js books to add a simple card and checkout function but didn't want to lose out on this lovely project.

Thanks,
Gavin.

**Comment by pkarw** [comment]
You can try to use the `@vue-storefront-store` package separately from the project - the only required dependencies then are Vue and Vuex; so Yes - it should theoretically work in Nuxt; however nobody has tried it before :D

**Comment by filrak** [comment]
@ghenry tbh It would be much easier to integrate existing app into VS than doing it from the other side
