### ISSUE TITLE
Advice to integrate a theme developped with the quasar framework?

### ISSUE THREAD

**Issue by zadigus** [DivanteLtd/vue-storefront#1876]
Hi,
We are willing to develop our frontend application with the [quasar framework ](https://quasar-framework.org/). Do you have any advice for us to be successful? What are the necessary conditions for a vue-storefront theme to work?
Cheers

**Comment by zadigus** [comment]
Also, would it be possible to use your pure core library (i.e. the calls to vue-storefront-api / magento) in a frontend we would develop with quasar? I mean we might not want to build our frontend app with the webpack config you provided, it depends how we can integrate quasar in there. We are currently trying to evaluate all that, so any advice is good for us to take from you guys.

**Comment by pkarw** [comment]
Hi! It can be pretty hard as nobody yet tried to do so. You can very easily get the idea how vs-api works reading our docs: https://github.com/DivanteLtd/vue-storefront-integration-boilerplate/blob/master/1. Expose the API endpoints required by VS/Required API specification.md

there is a module @vue-storefront/store which is just a vuex implementation of the vsapi calls; theorethicalyl You could use it in You quasar project however with the next release 1.5 - things got complicated as we;re decoupling this module to modules: https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md

**Comment by 3kynox** [comment]
Hello, I'm having the same question. I would like to integrate vue-store-front with a Quasar project on the front part.
The backend part is normally already managed as we use Symfony API-Platform with Sylius, which is already possible to integrate with.

Thanks for further informations about this and sorry to have re-enable this issue.

Cheers
