### ISSUE TITLE
CmsBlock or CmsPage are not ssr 

### ISSUE THREAD

**Issue by stefanobrambilla84** [DivanteLtd/vue-storefront#1894]
## Current behavior
Itry to load cmsBlock in homepage by magento2-cms extencions, but the block is load after page loaded.
i load the cms block by this:
 `<cms-data :identifier="'custom-block'" :type="'Block'"/>`

## Expected behavior
I want load cms block by ssr

**Comment by pkarw** [comment]
Related to #1792

**Comment by stefanobrambilla84** [comment]
thanks @pkarw and @filrak for maintenance this great job.
Have you a deadline for this issue?

**Comment by pkarw** [comment]
@ngeleedst this is right approach (to use Elastic). Please do consider https://github.com/DivanteLtd/vue-storefront/issues/1792 - the intention was to centralize the data loading process like You can include 2-5 CMS widgets on the page and call sth like `store.dispatch('dataloader/addToQueue', this.loadCMSData(12))` - and then in the `asyncData` to have sth like `store.dispatch('dataloader/runQueue')` - to fetch all the required data and populate Vuex store right before the HTML is returned to the browser

**Comment by yuriboyko** [comment]
@ngeleedst @pkarw 
Our team currently are working on the CMS content. But we are applying completely new functionality to work with CMS content data(pages, blocks, hierarchy) with saving data to Elasticsearch. 
CMS pages actually almost done (with using SSR). Once it will be finished we will develop functionality for blocks  and hierarchy as well.

**Comment by pkarw** [comment]
@yuriboyko perfect! and the data loader? :)

**Comment by pkarw** [comment]
CMS pages are currently supporting SSR, blocks - are not yet
