### ISSUE TITLE
Mailchimp module improvements - check if user is subscribed

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1899]
## What is the motivation for adding / enhancing this feature?

Current mailchimp module is very limited in fucntionalities. Basically it allows us to
- sign into newsletter
- sign out from it if we are logged in

Obviously we are missing at least ability to check if logged in user is subscribed to the newsletter (based on it's email). 
## What are the acceptance criteria 

- extend vue-storefront-api `mailchimp` extension with isSusbcribed(email) method that checks if user with provided email is on a mailing list
- extend vue-storefront `mailchimp` module with isSubscribed action/getter (depending on your implementation)
- if user is logged in and signed into newsletter -> hide newsletter opt-in and show the susbcription as checked input box in `MyNewsletter` component
- use currently existing offline cache only for logged in users

https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md

**Comment by mdesmet** [comment]
Hi I have this working already, can submit a PR.

**Comment by pkarw** [comment]
Great! Please do :-)
