### ISSUE TITLE
Create Search module

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1902]
## What is the motivation for adding / enhancing this feature?

Search module should contain all the business logic responsible for a search feature. If needed task involves refactoring of the current search functionality to simplier, more upgradable (abstraction) API. (use core/components as a facade between new and old API to stay backward compatible, you can find examples of such porting in Microcart).

## What are the acceptance criteria 

- Gather all core components/vuex actions etc into one new search module
- Create new Vuex 'search` module to encapsulate all the logic
- If needed refactor current methods/vuex actions to match modules best practices

## Additional information

https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md
You can contact me directly on slack to discuss the module before starting to code

**Comment by yuriboyko** [comment]
@filrak @Aekal 
do you have any information about when we can expect this module?

**Comment by filrak** [comment]
@Aekal ?

**Comment by Aekal** [comment]
Sorry, I didn't do it yet due to lack of time. I'm unassigning myself so maybe someone will want to work on it
