### ISSUE TITLE
Rewrite extensions to modules.

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1906]
## What is the motivation for adding / enhancing this feature?

Current extensions system will be depreciated and we will use VS modules for this purpose. This task involves rewriting
## What are the acceptance criteria 

Woudl be amazing if extension creators can handle it by themselves
- [x] .droppoint-shipping 
- [x] GA 
- [ ] magento2-cms ext by @anqaka 
- [ ] payment-backend-methods ext by @MikeSheward 
- [ ] payment cash on delivery
- [ ] raw-output-example by @pkarw 
- [ ] sample-custom-entity-gql by @phoenix-bjoern 

## Additional information

https://github.com/DivanteLtd/vue-storefront/blob/master/doc/api-modules/about-modules.md

**Comment by kruchy8** [comment]
payment-cash-on-delivery seems to be unused on latest develop

**Comment by pkarw** [comment]
:D @filrak so You should close this one :)
