### ISSUE TITLE
Add checkout feature

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#191]

**Comment by pkarw** [comment]
I've started some initial works under feature/191_checkout

**Comment by pkarw** [comment]
@filrak please continue here: https://github.com/DivanteLtd/vue-storefront/tree/feature/191_checkout

**Comment by karolbzik** [comment]
@filrak, @pkarw here's the design of checkout
<img width="1440" alt="checkout - all steps" src="https://user-images.githubusercontent.com/18116406/32141977-eea54c78-bc8d-11e7-97ef-8ff7a91e9cc2.png">
As always - available on Figma - https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront-Open-Source.

Fields and validations are designed based on Material Design pattern, here's more info - https://material.io/guidelines/patterns/errors.html.

This is a little bit complex page, please start with the development of the frame of the page. At the evening I will upload the design of the checkout on different stages.

**Comment by karolbzik** [comment]
Here's the view of step 1. personal details, I've also added the design to https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront-Open-Source.

<img width="1440" alt="checkout - step 1 personal details" src="https://user-images.githubusercontent.com/18116406/32146432-a693c276-bcd7-11e7-87ca-5df37bce62d8.png">

**Comment by karolbzik** [comment]
Step. 3 Payment, for now - cash only.

![checkout - step 3 payment](https://user-images.githubusercontent.com/18116406/32344213-5c921a4c-c006-11e7-917d-17ef8a3cfe66.png)

**Comment by pkarw** [comment]
@filrak @karolbzik at this point i would suggest to focus on styling this form and polishing it up - not adding new features (like we don't have support for invoices/company data - which is quite simple to add)

We can maybe add option for different billing address but i think it's not necessary for now

**Comment by karolbzik** [comment]
@filrak styling of the checkout needs to be improved.

The current stage with main changes:
![15](https://user-images.githubusercontent.com/18116406/32464018-d4102038-c33e-11e7-843e-6fa402b2fc74.png)

The desired stage:
![checkout - step 1 personal details](https://user-images.githubusercontent.com/18116406/32464045-f56cfad0-c33e-11e7-9a61-9bf445914974.png)

Please note that fields from the second step "shipping" should be visible only after processing the first step "personal data".

**Comment by karolbzik** [comment]
@filrak please apply all changes so the checkout looks like in the design (I don't mean pixel perfect, we just need to stick to the general - top, fields, footer, sidebar cart, material design style for all forms). @pkarw please update all changes uploaded by @filrak to the demo so I could do the check and close the issue. Please use https://github.com/DivanteLtd/vue-storefront/projects/1 for status management.

**Comment by pkarw** [comment]
@filrak can you take care of this one?

**Comment by filrak** [comment]
done in https://github.com/DivanteLtd/vue-storefront/pull/435 thanks to @Aekal
