### ISSUE TITLE
mobile screen header bug

### ISSUE THREAD

**Issue by bartdominiak** [DivanteLtd/vue-storefront#1925]
There is a bug on mobile screen, it shows after deleted duplicated grid styles #1915

<img width="531" alt="zrzut ekranu 2018-10-26 o 18 39 27" src="https://user-images.githubusercontent.com/18058305/47580192-86f9e280-d94e-11e8-9f44-ec8a051c0194.png">

**Comment by filrak** [comment]
@bartdominiak can you fix it by yourself? Probably the solution is to add deleted grid style and remove the 2nd one instead.

**Comment by bartdominiak** [comment]
@filrak Yes. Already fixed that in #1941
