### ISSUE TITLE
this project can use to nativescript-vue and create native mobile app?

### ISSUE THREAD

**Issue by benyang2015** [DivanteLtd/vue-storefront#1937]
## What are the acceptance criteria 

- ...
- ...

# Can you complete this feature request by yourself?

**Comment by filrak** [comment]
Vue Storefront is 100% web-based PWA and I really don't see a reason to use nativscript for it.

Since NS is using it's own APIs and components it's impossible to port existing web application that relies strong on browser APIs into it.
