### ISSUE TITLE
Order is not appearing in 'My Orders' after placing

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1944]
## Current behavior

1. Place the order while logged in
2. Go to My orders section in profile
3. It doesn't contain placed order (appears after refresh)
## Expected behavior
We should see placed order in our profile. Simply by updating the placed orders vuex store after placing it

## Steps to reproduce the issue

posted above
## Repository

https://demo.vuestorefront.io/
## Enviroment details

- Browser:  Chrome 68
- OS:  MacOS HS
- Node:  8.x

**Comment by pkarw** [comment]
This is an isssue with o2m not running on the host. It has been fixed last week with the /api/order endpoint that synchronously sends an order and o2m is no longer required
