### ISSUE TITLE
Refresh on user profile redirects to home page

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1945]
## Current behavior

1. Visit user profile (any section)
2. Refresh
3. You are redirected to home
## Expected behavior

We should stay in the same page we refreshed
## Repository

https://demo.vuestorefront.io/
## Enviroment details

- Browser:  GH68
- OS:  MacOS HS
- Node:  8.x

**Comment by pkarw** [comment]
It's not a bug. SSR is not working well with Account nad we wanted to avoid situation when the user profile is loaded without user being authroized.

**Comment by filrak** [comment]
okay, can we have a task to fix this? I can imagine some situations where merchants can have direct links to account in emails etc. We should check if user is authorised in navigation guards and decide on redirects from there
