### ISSUE TITLE
Possible to use my project in vue?

### ISSUE THREAD

**Issue by wubuyun** [DivanteLtd/vue-storefront#1952]
Possible to use my project in vue?
demo： http://demo.fancyecommerce.com
api: http://www.fecshop.com/doc/fecshop-guide/develop/cn-1.0/guide-fecshop-server.html

**Comment by filrak** [comment]
FOr sure. You just need an API integration https://github.com/DivanteLtd/vue-storefront-integration-boilerplate

**Comment by wubuyun** [comment]
project with mongo, possible direct adaptation?
