### ISSUE TITLE
mail-service

### ISSUE THREAD

**Issue by wubuyun** [DivanteLtd/vue-storefront#1953]
after completing the purchase, I do not receive email,
api
    "mailService": {
      "transport": {
        "host": "smtp.gmail.com",
        "port": 465,
        "secure": true,
        "user": "yanz9999@gmail.com",
        "pass": "######"
      },
      "targetAddressWhitelist": ["yanz9999@gmail.com"],
      "secretString": "__THIS_IS_SO_SECRET__"
    }
  },

VS
    "mailer": {
      "endpoint": {
        "send": "https://www.xayanz.com.br/api/ext/mail-service/send-email",
        "token": "https://www.xayanz.com.br/api/ext/mail-service/get-token"
      },
      "contactAddress": "yanz9999@gmail.com",
      "sendConfirmation": true
    },

**Comment by wubuyun** [comment]
465 or 587 port?

Outgoing Mail (SMTP) Server |
 smtp.gmail.com
Requires SSL: Yes
Requires TLS: Yes (if available)
Requires Authentication: Yes
Port for SSL: 465
Port for TLS/STARTTLS: 587
-- | --

**Comment by akbarik** [comment]
@wubuyun your mail transport settings look fine.
Can you please tell what kind of notification do you get after sending the feedback? And also what are the console logs?

**Comment by wubuyun** [comment]
![default](https://user-images.githubusercontent.com/35350235/47947913-cbfcb680-df04-11e8-9602-79654bdcaaa1.jpg)

**Comment by wubuyun** [comment]
mailService transport can  use Port for TLS/STARTTLS: 587 ?

**Comment by akbarik** [comment]
yes, you can use any mail transport. Looking at the console log, I don't see any errors there. Can you then send me the screenshot of the Network tab? Also, you know that mail is sent after you press "Give a feedback" button, right? Just to make sure.

**Comment by wubuyun** [comment]
Source email address is invalid

index.ts:15 POST https://www.xxx.com.br/api/ext/mail-service/send-email 500
(anonymous) @ index.ts:15
Promise.then (async)
(anonymous) @ index.ts:13
sendEmail @ index.ts:10
(anonymous) @ vuex.esm.js:704
l.dispatch @ vuex.esm.js:426
dispatch @ vuex.esm.js:332
sendEmail @ EmailForm.ts:12
sendFeedback @ ThankYouPage.vue:109
submit @ ThankYouPage.vue?cd44:1
t @ vue.runtime.esm.js:2023
e._withTask.e._withTask @ vue.runtime.esm.js:1822

**Comment by akbarik** [comment]
Alright, the error message you're getting says the email address you specified at Checkout form is invalid. Are you sure you put there a valid address?

**Comment by wubuyun** [comment]
email address  Checkout form, What is the configuration path?

**Comment by wubuyun** [comment]
valid email address yes..other email too

**Comment by wubuyun** [comment]
Using Gmail
Even though Gmail is the fastest way to get started with sending emails, it is by no means a preferable solution unless you are using OAuth2 authentication. Gmail expects the user to be an actual user not a robot so it runs a lot of heuristics for every login attempt and blocks anything that looks suspicious to defend the user from account hijacking attempts. For example you might run into trouble if your server is in another geographical location – everything works in your dev machine but messages are blocked in production.

Additionally Gmail has came up with the concept of “Less Secure” apps which is basically anyone who uses plain password to login to Gmail, so you might end up in a situation where one username can send mail (support for “less secure” apps is enabled) but other is blocked (support for “less secure” apps is disabled). You can configure your Gmail account to allow less secure apps here. When using this method make sure to also enable the required functionality by completing the “Captcha Enable” challenge. Without this, less secure connections probably would not work.

If you are using 2FA you would have to create an “Application Specific” password for Nodemailer to work.

Gmail also always sets authenticated username as the From: e-mail address. So if you authenticate as foo@example.com and set bar@example.com as the from: address, then Gmail reverts this and replaces the sender with the authenticated user.

To prevent having login issues you should either use XOAUTH2 (see details here) or use another provider and preferably a dedicated one like Mailgun or SendGrid or any other. Usually these providers have free plans available that are comparable to the daily sending limits of Gmail. Gmail has a limit of 500 recipients a day (a message with one To and one Cc address counts as two messages since it has two recipients) for @gmail.com addresses and 2000 for Google Apps customers, larger SMTP providers usually offer about 200-300 recipients a day for free.

**Comment by wubuyun** [comment]
erro too

![default](https://user-images.githubusercontent.com/35350235/47976310-faab9600-e098-11e8-97a1-9c8cd5cd7c3b.jpg)

**Comment by wubuyun** [comment]
magento is ok..

![capturar](https://user-images.githubusercontent.com/35350235/48083547-91cd3680-e1dc-11e8-8e7c-566b2a38a5d7.PNG)
