### ISSUE TITLE
Create module boilerplate

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1956]
## What is the motivation for adding / enhancing this feature?

we should have module boilerplate as a separtae repo with instruictions on how to test it, install locally and publish

# Can you complete this feature request by yourself?

Yes, till the end of next week it'll be ready

**Comment by pkarw** [comment]
@filrak we should have it before 1.6 to just show the guys: here You have modules, here You have module boilerplate; extensions are deprecated so feel free to add some modules :)

**Comment by pkarw** [comment]
is it done?
