### ISSUE TITLE
Replace he.js with smaller equivalent

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1966]
## What is the motivation for adding / enhancing this feature?

he.js is taking a lot of space in our vendor bundle yet doing pretty simple task. We should replace it with smaller lib to have smaller bundles.
![image](https://user-images.githubusercontent.com/15185752/48118417-7c075200-e26c-11e8-85fb-fac6fd693963.png)

It's used in
`core/store/lib/filters.ts` and `core/filters/html-decode/index.js`

We should replace it with library doing similar job but much smaller in size, crafted only for this purpose.

he.js is used in product names - it's the right place to test

## What are the acceptance criteria 

- Replace he.js with smaller equivalent

**Comment by DavidRouyer** [comment]
Maybe https://github.com/emn178/js-sha3

**Comment by DavidRouyer** [comment]
Maybe https://lodash.com/docs/4.17.11#unescape can suffice? Need testing

**Comment by filrak** [comment]
Would be great since we already have lodash

**Comment by DavidRouyer** [comment]
It won't work since there is too many HTML entities to take into account. Can't we just return decoded strings?
