### ISSUE TITLE
Replace object_hash.js with smaller equivalent

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1967]
## What is the motivation for adding / enhancing this feature?

object_hash.js is taking a lot of space in our vendor bundle yet doing pretty simple task. We should replace it with smaller lib to have smaller bundles.
![image](https://user-images.githubusercontent.com/15185752/48118644-22535780-e26d-11e8-90e9-d027e53dbc09.png)

## What are the acceptance criteria 

- Replace object_hash.js with smaller equivalent

**Comment by DavidRouyer** [comment]
Maybe https://github.com/emn178/js-sha3
