### ISSUE TITLE
Something went wrong...

### ISSUE THREAD

**Issue by goodforever** [DivanteLtd/vue-storefront#1968]
## Current behavior
After run api and migrate data
docker-compose up  vue-storefront
visit localhost:3000
got error 
app_1  | Error during render : /
app_1  | Error: request to http://localhost:8080/api/catalog/vue_storefront_catalog/category/_search?size=4000&from=0&sort=position%3Aasc&_source_include=children_data%2Cid%2Cchildren_count%2Csku%2Cname%2Cis_active%2Cparent_id%2Clevel%2Curl_key%2Cproduct_count%2Cpath failed, reason: connect ECONNREFUSED 127.0.0.1:8080
app_1  |     at _commonErrorHandler (core/server-entry.ts:14:11)
app_1  |     at server-bundle.js:8843:25
app_1  |     at <anonymous>
app_1  |     at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by pkarw** [comment]
IT seems like vue-storefront-api is not running, please run `yarn dev` in its folder

**Comment by goodforever** [comment]
vue-storefront-api is running.

curl -i   http://localhost:8080/api/catalog/vue_storefront_catalog/category/_search?size=4000&from=0&sort=position%3Aasc&_source_include=children_data%2Cid%2Cchildren_count%2Csku%2Cname%2Cis_active%2Cparent_id%2Clevel%2Curl_key%2Cproduct_count%2Cpath
can get  data list successfully.  
And when it's "Something went wrong ...
We've noticed Internal Server Error while rendering this request"  status , I press home page button homepage can load successfully.
