### ISSUE TITLE
Upgrade to node 10

### ISSUE THREAD

**Issue by DavidRouyer** [DivanteLtd/vue-storefront#1970]
https://nodejs.org/ Node 10 is the new LTS version

**Comment by pkarw** [comment]
@DavidRouyer what do You mean by upgrade? I mean - it works just fine with Node 10 and our reqs are:  `"node": ">=8.x <11.x"` - and it covers 10x :-)

**Comment by DavidRouyer** [comment]
I'll allow 11.x and update our Docker images

**Comment by pkarw** [comment]
Could You take care of this task?

**Comment by DavidRouyer** [comment]
Yes, shouldn't be a big deal

**Comment by pkarw** [comment]
@DavidRouyer can we make this task happen in this week - thereof it will be included in v1.6

**Comment by DavidRouyer** [comment]
Will do it tonight Sir
