### ISSUE TITLE
Add the login and register pop-ups

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#198]
The use scenario: as a customer, I can log in or register from any place in the eCommerce, by clicking the link I will see a pop-up with 2 options - login or register an account.

The design:
<img width="1440" alt="log in pop-up" src="https://user-images.githubusercontent.com/18116406/32146732-7e0fc98a-bcdc-11e7-9a72-db0d395af97e.png">
<img width="1440" alt="register pop-up" src="https://user-images.githubusercontent.com/18116406/32146731-7dff8052-bcdc-11e7-9ffc-49f7ed19b965.png">

The file with the design - https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront-Open-Source.

I suggest starting with the development of the static pop-ups, preparing it for RWD.
Then we will work on the API so the connection with the logic behind the login/registration could be possible.

**Comment by pkarw** [comment]
https://magento.stackexchange.com/questions/150581/magento-2-how-to-call-rest-api-to-register-a-new-customer

**Comment by pkarw** [comment]
I'm going to take care of this adding login/register api methods to vue-storefront-api as a proxy to Magento api calls

**Comment by pkarw** [comment]
This is done @karolbzik
