### ISSUE TITLE
Problems with hot reload

### ISSUE THREAD

**Issue by 4romanchuk** [DivanteLtd/vue-storefront#1986]
1, I ran project by 'yarn dev' 
2. After adding some changes nothing is changed, and only after reuse 'yarn dev'
I've seen new changes.

_How enable hot reload in this project?_

**Comment by pkarw** [comment]
It should work just fine. Typically the recompile/reload cycle takes about 30s

**Comment by DavidRouyer** [comment]
Which version? Are you on the develop branch?

**Comment by filrak** [comment]
@4romanchuk check if you have Service Worker running, it may cause problems like this. if you have latest develop then it's not included in `yarn dev` command but it was for some versions before. Also changes at config are behaving defferently.

**Comment by mosstly-design** [comment]
How does one get hot code reloading to work when running `yarn dev`. I'm having the same issue.

**Comment by haideritx** [comment]
Has anyone found any solution to this.?

**Comment by hurruse** [comment]
I have the same when running on windows
