### ISSUE TITLE
Add the touch feedback animation (ripple effect)

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#199]
Let's add the touch feedback animation from the material motion concept.
It's important for the touchscreens.
The effect should be applied to components: product blocks, buttons, buttons in the navigation, photos.

**Comment by karolbzik** [comment]
@pkarw @patrykpiston @filrak @mercs600 could you suggest the approach?

**Comment by pkarw** [comment]
@filrak please take care of this one while finising checkout there is ready-made library for that for vue

**Comment by Aekal** [comment]
Can we use [vue-material](https://vuematerial.io/) in the project? It'll much easier to follow material design concept with this library.

**Comment by pkarw** [comment]
@filrak ?

**Comment by kacperknapik** [comment]
@pkarw @Aekal I think, we can use `MdButton` only at the moment.

If we need more components in the future, we can surely use the full bundle

**Comment by pkarw** [comment]
let's try

**Comment by kacperknapik** [comment]
unfortunately, `vue-material` is not exactly stable atm.
after using `MdButton` I get a similar error to this: https://github.com/vuematerial/vue-material/issues/1182
we should consider using our own styles, and after `vue-material` is stable, we can use it

**Comment by pkarw** [comment]
OK :)
