### ISSUE TITLE
Use native local storage API instead of our drivers for everything except the catalog

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1995]
## What is the motivation for adding / enhancing this feature?

Like in the title ;). We don't need our complicated caching mechanisms for this
## What are the acceptance criteria 

- ...
- ...

# Can you complete this feature request by yourself?

Yes

**Comment by robwozniak** [comment]
@filrak let me know if I can start working on this :slightly_smiling_face:
