### ISSUE TITLE
CMS Extension Issue 

### ISSUE THREAD

**Issue by danrcoull** [DivanteLtd/vue-storefront#1996]
## Current behavior
A issue with the cms extension as getters are triggering before the data is returned and have no access to the state, so just throws exceptions.

" Error in render: "TypeError: state.cmsPage is undefined"" but also the data returns yet the catch stated "install the module" is always triggered even when that module is isntalled,  but whats even strangers is the json exists , and is readable but still throws a catch, always

## Expected behavior
Ajax runs, displays the content and caches the state and if there is no online connection gives a message rather than throwing an exception internal server error.

**Comment by filrak** [comment]
@danrcoull afaik the extension is currently being rewritten to a module with gql support 
@anqaka should know the details ;)

**Comment by filrak** [comment]
please see https://github.com/DivanteLtd/vue-storefront/issues/1987
