### ISSUE TITLE
Remove markdown-based static pages 

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#2007]
## What is the motivation for adding / enhancing this feature?

This feature appeared to be redundant. It's also complicating our vue-cli pkugin migration plan

We should base demo static pages on simple placeholders or some external cms data.

## What are the acceptance criteria 

- remove markdown static pages and remove corresponding business logic
- replace it with placeholders (can be a static vue component)

# Can you complete this feature request by yourself?

I'm busy doing other issues regarding modules ;/

**Comment by pkarw** [comment]
We can remove them only if we replace the current mockups (terms and conditions etc ...) with static Vue Components. I don't want to have the demo site dependent on any external service (CMS in this case)

**Comment by filrak** [comment]
Ok, scheduled it for today ;)
