### ISSUE TITLE
How to apply translations?

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#201]

**Comment by madonzy** [comment]
@karolbzik  here're some interesting packages: https://github.com/vuejs/awesome-vue#i18n

**Comment by madonzy** [comment]
I think, exactly this will be good one https://github.com/kazupon/vue-i18n

**Comment by karolbzik** [comment]
@madonzy thanks!

@pkarw @filrak - what do you think?

**Comment by pkarw** [comment]
Cool, let's use https://github.com/kazupon/vue-i18n

**Comment by pkarw** [comment]
Could somebody take care of this one?

**Comment by madonzy** [comment]
@pkarw I'll take it ;)
