### ISSUE TITLE
SEO friendly urls

### ISSUE THREAD

**Issue by ngeleedst** [DivanteLtd/vue-storefront#2010]
## What is the motivation for adding / enhancing this feature?
The urls that are being generated in the Vue Storefront are not SEO best practices, we would like to use product slugs without sku. Next to this issue it would be nice to have some kind of url rewrite possibility because now you have to allocate every module to a route like:

Category: /category-slug
Pages: /page/page-slug
Product: /product/123/product-url/123

I think we need to develop a general entry point for all types and from that point match if the slug is for a category, page or product.

## What are the acceptance criteria 
- Product urls from /123/product-slug/123 to /product-slug
- Advanced routing module for url rewrites

# Can you complete this feature request by yourself?
No.

## Additional information
None

**Comment by afirlejczyk** [comment]
- Advanced routing module for url rewrites
We have to remember about urls with extra slashes, e.g `women/tops.html` - this url also should work for category.

- there should be new option in config for this new feature

**Comment by jahvi** [comment]
Is it worth leveraging/porting the `urlResolver` GraphQL query introduced in 2.3? from the docs:

> The urlResolver query returns the canonical URL for a specified product, category or CMS page

The query returns the type of entity (`PRODUCT`, `CATEGORY`, or `CMS_PAGE`) so the right component can be used depending of this.

**Example Query**
```graphql
{
  urlResolver(url: "venia-tops.html") {
    id
    canonical_url
    type
  }
}
```

**Result**
```graphql
{
  "data": {
    "urlResolver": {
      "id": 7,
      "canonical_url": "catalog/category/view/id/7",
      "type": "CATEGORY"
    }
  }
}
```

**Comment by pkarw** [comment]
@madonzy we can probably store the `sku/url_key` mapping in kind of `localStorage` - populated in the [`product/list` method](https://github.com/DivanteLtd/vue-storefront/blob/fbe4b148e5f7044541018eaf49d122925d9a894b/core/modules/catalog/store/product/actions.ts#L327)

Please take a look at #2021 - where I've described exactly how offline cache works

**Comment by jahvi** [comment]
@pkarw I see this sounds more complicated than I thought then, perhaps it might be too hard to implement with the current indexedDB approach.

**Comment by jahvi** [comment]
I see, so you mean for example instead of having product keys in indexedDB as `sku$$MP01` change it to something like `url$$josie-yoga-jacket` and select based on that?

**Comment by ngeleedst** [comment]
Any updates on this request?

**Comment by Cyclonecode** [comment]
I am also wondering about this and if there are any updates on this issue?

**Comment by jonathanselander** [comment]
What about the current inconsistency between vsf and the underlying platform managing URLs, redirects, and what admins assume?

**Comment by pkarw** [comment]
Any feedback will be much appreciated: https://github.com/DivanteLtd/vue-storefront/pull/2401

**Comment by ResuBaka** [comment]
I have test this with an magento 1 store and the urls in category are /sku/url_key/ and in search they are /url_path?sku and when i try to go to a product like example http://localhost:3000/Aufschnittmaschine-ASM-300?childSku i get the error "The product, category or CMS page is not available in Offline mode. Redirecting to Home.".

Is there anything i am missing? I am an the latest develop and have useUrlDispatcher and useShortCatalogUrls set to true.

**Comment by Cyclonecode** [comment]
@ResuBaka - This sounds more like you have some problems with your configuration. Can you verify that vue-storefront can successfully connect to vue-storefront-api and that the vue-storefront-api actually can access elasticsearch?

**Comment by pkarw** [comment]
I belive You should have `useShortCatalogUrls` set to false

**Comment by ResuBaka** [comment]
When I disable useShortCatalogUrls then the product url does work. But for I want to have both at the same time. Or is it not intended to work together?

**Comment by pkarw** [comment]
It's not. Please set the `product.url_path` or `category.url_path` to whatever value you need and it will be Your url :) as simple as that :) so it's much more powerfull than `useShort...`

**Comment by DaanKou** [comment]
@pkarw what do exactly mean with setting the ‘product.url_path’ and ‘category.url_path’ to any value? As these properties are now already filled by Mage2VueStorefront?

**Comment by pkarw** [comment]
Yes, these fields are set by mage2vuestorefornt and magento2-vsbridge-indexer and are used to map the urls
