### ISSUE TITLE
Vue-storefront running but error on homepage

### ISSUE THREAD

**Issue by Decntdefalt** [DivanteLtd/vue-storefront#2023]
## Current behavior
When running yarn build/yarn start/yarn dev on storefront and api folders, everything seems to be running. But I'm still getting error on https://hoversport.no/

## Expected behavior
It should load the standard vue-storefront images and products on frontpage/homepage

## Steps to reproduce the issue
Yarn build vue-storefront-api folder
Yarn start vue-storefront-api folder
Yarn build vue-storefront folder
Yarn start vue-storefront folder
Yarn dev vue-storefront folder

## Can you handle fixing this bug by yourself?
No

## Enviroment details
- Browser: Chrome
- OS: Debian 9 on bitnami
- Node: v11.2.0

**Comment by DavidRouyer** [comment]
Do you have an error on the backend?
Please try with node 10, we haven't tested it yet on node 11.

**Comment by Decntdefalt** [comment]
> Do you have an error on the backend?
> Please try with node 10, we haven't tested it yet on node 11.

No error. Absolutely everything is running in the backend. I've set up the storefront on my mac countless times with no problem. But I will try I will downgrade to 10 and see if that works.

**Comment by Decntdefalt** [comment]
> Do you have an error on the backend?
> Please try with node 10, we haven't tested it yet on node 11.

I downgraded to 10 and absolutely everything is running. 

Still getting error on homepage.

**Comment by pkarw** [comment]
You should have some error messages in the server console - 99% seems like no connectivity to Vue-storefont-api from the Vue-storefront server app

**Comment by Decntdefalt** [comment]
> You should have some error messages in the server console - 99% seems like no connectivity to Vue-storefont-api from the Vue-storefront server app

My apologies. You're 100%, I haven't installed the API properly..

**Comment by Decntdefalt** [comment]
Dude, I am so close to getting there. The last problem I have to get my shop up and running is to get the external checkout working properly.

Click on https://hoversport.no/p/Elscooter/elscooter-1 and add it to the cart, you get directed to my external checkout, but damn it, I can not get to a checkout and it seems like Storefront is not synchronizing the added product in the cart with my Magento instance.

Do you have any advice or tips on how to fix it? Last problem I have to 100% get it through.

I hired another developer for 150 USD to get some troubleshooting - which sucked but totally worth it, but learning by doing I guess since I only have 2 months of real development experience.

Btw, we have a storefront running on https://techdrones.no/ and we're selling drones like crazy. My former colleague Mikael from Sweden which solved a caching problem with the storefront helped me set it up. I think they went down and visited you guys recently.

But this is my first time setting it up alone, so I hope you could give me some tips on how to solve my last problem.

**Comment by pkarw** [comment]
That's awesome :) You should definitively take a look at https://divanteltd.github.io/vue-storefront/guide/integrations/totals-sync.html#cart-and-totals-sync

You need to set the Magento2 API credentials (oauth secrets) in the `vue-storefront-api` config file PLUS set proper options in VS config (`cart.synchronize` to `true`)

**Comment by Decntdefalt** [comment]
Thanks!


You wouldn't know in which file I'd be able to change the currency sign?
