### ISSUE TITLE
Long menu styles

### ISSUE THREAD

**Issue by mdanilowicz** [DivanteLtd/vue-storefront#2029]
## Current behavior
When we have a too long menu, there is a problem with styles

## Expected behavior
The menu should look good regardless of the length

## Steps to reproduce the issue
Create long submenu

## Environment details
All browsers

## Additional information
![2018-11-27_13h01_07](https://user-images.githubusercontent.com/7597086/49080660-a6817500-f244-11e8-87cc-15d46786bda6.png)

**Comment by filrak** [comment]
I was unable to reproduce with some items added to left menu. Can you be a little bit more specific in reproduction steps? ;)

**Comment by filrak** [comment]
Fixed ;)

**Comment by mdanilowicz** [comment]
There is still a problem with the menu

**Comment by filrak** [comment]
You're right ;) Now its fix sure fixed  with https://github.com/DivanteLtd/vue-storefront/commit/ca4ac1ab7b301cee0e937dc11d523647f0bb309d ;)
