### ISSUE TITLE
Third-party payment providers integration

### ISSUE THREAD

**Issue by kovinka** [DivanteLtd/vue-storefront#2030]
## What is the motivation for adding / enhancing this feature?
Currently VS retrieves the list of all available methods and displays them on checkout Payment step. 
When the customer chooses some payment method and completes the checkout, VS creates the order in Magento. But in my case to complete the order, the customer needs to be redirected to the providers payment webiste (Magento 2 payment module logic), enter card data, pay and depending on the result - be redirected back to the VueStorefront (Thank you or Failure page). 

## What are the acceptance criteria 
The customer can purchase the order with full payment process integration (similar to Magento logic).

## Can you complete this feature request by yourself?
yes, but probably need some support

**Comment by pkarw** [comment]
Please take a look at:
https://github.com/DivanteLtd/vue-storefront/issues/2008

and: https://github.com/develodesign/vsf-payment-paypal

**Comment by kovinka** [comment]
@pkarw thanks, i think we can close the ticket now
