### ISSUE TITLE
docker-compose up windows 10 pro error

### ISSUE THREAD

**Issue by joshicraft** [DivanteLtd/vue-storefront#2032]
## Current behavior
When following the [Windows Installation guide](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Installing%20on%20Windows.md) Im getting the following error at the point when running _docker-compose up_

`ERROR: Service 'es1' failed to build: Get https://docker.elastic.co/v2/: dial tcp: lookup docker.elastic.co on 192.168.65.1:53: no such host`

## Expected behavior
docker-compose up should run successfully

## Environment details
- OS: Windows 10 Pro
- Node: 10.13.0
- Docker 18.09.0, build 4d60db4

## Additional information
I've installed docker for windows and have access to the GUI. running docker --version givens me the current version. I'm very new to Docker so its a bit confusing.

**Comment by pkarw** [comment]
This seems like an issue not rated to Vue Storefront itself but rather Docker (seems like it can not download some images)

**Comment by joshicraft** [comment]
Changing the docker Daemon registry to localhost:5000 seemed to have fixed the problem. This is not a good solution but it works.
