### ISSUE TITLE
Refactor `afterRegistration` to support `context` not just `isServer`

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2038]
## What is the motivation for adding / enhancing this feature?

We should redefine module entry from `export function afterRegistration(Vue, config, store, isServer) {`

to more generic:

`export function afterRegistration(Vue, config, store, { isServer, ...  })`

This will let us extend the parameters passed to the modules. For example we can pass there `ssrContext` - https://github.com/DivanteLtd/vue-storefront/blob/299182e95a572b5d6ea7be11fa8b9099c89fed70/core/app.ts#L78 to allow module builders to add the expressJS level server side routes (which is kinda cool!)

**Comment by filrak** [comment]
Will be in core tomorrow ^^

**Comment by pkarw** [comment]
I belive this one is done @filrak ?
