### ISSUE TITLE
Load Material icons asynchronously

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#2060]
## What is the motivation for adding / enhancing this feature?

Better performance. According to LH audit we can gain some additional performance by doing this.

## What are the acceptance criteria 

- Material Icons are loaded asynchronously
# Additional information

**Comment by JKrupinski** [comment]
I can try this one

**Comment by patzick** [comment]
Thanks @JKrupinski ! :)

**Comment by JKrupinski** [comment]
You're welcome :)
