### ISSUE TITLE
Magento2 data import doesn't take configuration from local.json

### ISSUE THREAD

**Issue by Tjitse-E** [DivanteLtd/vue-storefront#2073]
## Current behavior
Quote from the docs:
> Magento2 data import is now integrated into vue-storefront-api for simplicity. It's still managed by the mage2vuestorefront - added as a dependency to vue-storefront-api.

The problem is that you still need to customize the configuration file in mage2vuestorefront. Now located in: `~/vue-storefront-api/node_modules/mage2vuestorefront/src/config.js`. The docs don't mention this.  

## Expected behavior
IMHO, the configuration for mage2vuestorefront should be located in the `config` folder of the vue-storefront-api

## Steps to reproduce the issue

1. Install Vue storefront
2. Connect to a Magento 2 instance
3. Change elastic/host settings in vue-storefront-api/config/local.json. In my case i've changed the Elastic host.
4. Run `yarn mage2vs import`
5. Notice that the custom settings from step 3 aren't used. Instead the config in this location is used `~/vue-storefront-api/node_modules/mage2vuestorefront/src/config.js`

## Repository
https://github.com/DivanteLtd/mage2vuestorefront

# Can you handle fixing this bug by yourself?

No, we're trying to finish a Vue Storefront project before the end of the year :)

## Additional information
[Link to relevant the Vue storefront documentation](https://divanteltd.github.io/vue-storefront/guide/installation/magento.html#integrating-magento2-with-your-local-instance)

**Comment by pkarw** [comment]
@Tjitse-E it’s taking the config from Vue-storefront-api/config/local.json but not the full config - just the Magento2 api, the rest is passed to mage2vs via ENV variables set in here:
https://github.com/DivanteLtd/vue-storefront-api/blob/258cc2a2f2b0f531f402737a6032e1118658de51/scripts/mage2vs.js#L107

Please let me know about Your use case, which properties are missed in there? 

I think we should do two things:
- let the user to set the properties via command line parameters of “npm run mage2vs import” - either using Vue-storefront-api ENV variables (commandline context) - which is also fine.
- load the configuration from config/local.json
- check mage2vuestorefront if some of the options are not possible to override via ENV (afaik all of them are open for ENV variables: 
https://github.com/DivanteLtd/vue-storefront-api/blob/258cc2a2f2b0f531f402737a6032e1118658de51/scripts/mage2vs.js#L107)

The conclusion: the communication between Vue-storefront-api + mage2vuestorefront is in this mode done via ENV variables, let’s make sure user can modify them via Vue-storefront-api config file + commandline arguments (for on-demand calls)

**Comment by pkarw** [comment]
@patzick can You please take care of this one as well?

**Comment by Tjitse-E** [comment]
@pkarw  in my use case I had to modify the elastic host directly here https://github.com/DivanteLtd/mage2vuestorefront/blob/master/src/config.js#L30, but the same setting is also configured in the API local.json: https://github.com/DivanteLtd/vue-storefront-api/blob/master/config/default.json#L11

**Comment by pkarw** [comment]
You're right, DATABSE_URL is currently missed in the `mage2vs`. Thanks! @patzick could You please fix this ?
