### ISSUE TITLE
Meta tile and meta descriptions missing in category object

### ISSUE THREAD

**Issue by Tjitse-E** [DivanteLtd/vue-storefront#2074]
## Steps to reproduce the issue

1. Add meta_title and meta_description to local.json in vue-storefront-api:

```
  "entities": {
    "category": {
      "includeFields": [
        "meta_description",
        "meta_title",
        "children_data",
        "id",
        "children_count",
        "sku",
        "name",
        "is_active",
        "parent_id",
        "level",
        "url_key",
        "description",
        "image"
      ]
    },
```

2. Add meta_title and meta_description to local.json in vue-storefront:

```
    "category": {
      "includeFields": [ "meta_description", "meta_title", "children_data", "id", "children_count", "sku", "name", "is_active", "parent_id", "level", "url_key", "product_count", "p
    },
```

3. Rebuild vue-storefront and vue-storefront-api.
4. Reindex via mage2vuestorefront:
```
node --harmony cli.js fullreindex
node --harmony cli.js categories --removeNonExistent=true --extendedCategories=true
```
5. Clear browser data

## Current behavior
Visit a frontend category and check the category computed property. The meta title and description are missing.

![banken 2018-12-10 18-05-07](https://user-images.githubusercontent.com/14849044/49748633-86bb6980-fca6-11e8-8696-a33ece4758b2.png)

## Expected behavior
After adding the (category) meta_title and meta_description these attributes should be available in the category object

# Can you handle fixing this bug by yourself?

No, i'm also not sure that this is a bug. Maybe i'm doing something wrong?

## Environment details

- Vue Storefront (API): 1.6
- Mage2vuestorerfront: master branch.
- Browser: Chrome Mac v70
- OS: Ubuntu 16
- Node: v8.14.0

## Additional information
Related issue: https://github.com/DivanteLtd/vue-storefront/issues/1383

**Comment by pkarw** [comment]
Currently the Magento meta_* fields are not used (we do generate meta from description and title fields) in Category.js (either in Product.js) but I belive this can Ben easily fixed - @patzick can you take a look at it?

**Comment by Tjitse-E** [comment]
@pkarw i've checked with Kibana, and I've noticed that some of the categories indeed have meta_title and meta_description fields now, and they are also available in the category object. However, this isn't the case for all the categories, in some categories the data is still missing. Maybe I will have to completely destroy and rebuild the elastic indexes? What would be the best way to do this?

**Comment by qiqqq** [comment]
@Tjitse-E I checked this issue and in my opinion passing data from elasticsearch to VS store works ok. I added some meta_title and meta_description fields to categories and products and this shows in vuex and in computed properties eg: https://prnt.sc/m5ez7l

Steps that you did are ok and this should works so in my opinion there is something wrong with elasticsearch indexes but I havn't knowled to help with ES.

**Comment by qiqqq** [comment]
I changed the generation of title and description meta tags. Now this tags will be generated based on meta_title and meta_description fields if this fields occurs.

https://github.com/DivanteLtd/vue-storefront/pull/2158
