### ISSUE TITLE
JSON data is getting huge due to Categories. 

### ISSUE THREAD

**Issue by jorkvist** [DivanteLtd/vue-storefront#2076]
## Current behavior
With around 500 categories under 6 main nodes divided into around 15 sub-categories with multiple sub-levels. The current implementations of the Category JSON data loaded in the index document makes each category be listed in level 1. Where all the 500 categories is written out and for each category there is a node called children_data where all the nested categories is written out again. This makes the part of the JSON for only the Categories over 2mb (in the index document). 

## Expected behavior
A more efficient way of handling this part of the Category JSON data.

## Steps to reproduce the issue
Check the JSON in the index document of the demo of vue storefront, the current demo data isn't making this as a big issue due to low number of categories. But for eCommerce sites with a bigger amount of categories the current implementation is not suitable. For each category added in a higher level, the JSON is growing exponentially. 

# Can you handle fixing this bug by yourself?
NO

**Comment by pkarw** [comment]
Good idea, we should rewrite the SidebarMenu component to let the navigation progressively download subcategories and load just one or two levels with SSR

**Comment by pkarw** [comment]
I'm working on it

**Comment by pkarw** [comment]
@jorkvist fixed in develop branch
