### ISSUE TITLE
Refactor core/store/index.js - move the localForage references to modules

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2081]
## What is the motivation for adding / enhancing this feature?

This method should be decentralized to modules:
https://github.com/DivanteLtd/vue-storefront/blob/095e5301b8d50c0c9d77694189e00f0f64aa5682/core/store/index.ts#L139

**Comment by filrak** [comment]
I made a duplicate of this issue. Tomek Kikowski is working on It
