### ISSUE TITLE
Checkout refresh redirects to homepage

### ISSUE THREAD

**Issue by ThijsVanDenWollenberg** [DivanteLtd/vue-storefront#2082]
## Current behavior
Doing a refresh while in the checkout causes a redirect to the homepage

## Expected behavior
Checkout page is reloaded

## Steps to reproduce the issue
Add product to shopping cart
Navigate to checkout page
Any where in checkout process refresh the page
You are redirected to homepage

# Can you handle fixing this bug by yourself?
NO

## Environment details

- Browser: Google Chrome Version 70.0.3538.110 (Official Build) (64-bit)
- OS: Mac OS Mojave version 10.14.1
- Node: v8.11.1

## Additional information
-

**Comment by filrak** [comment]
Hey, you can disablke this behavior by commenting out `if (context) context.server.response.redirect('/')` in `Checkout.js` `asyncData`

**Comment by lsimone** [comment]
Hi! 
why don't you remove that LOC, then? 
IMHO it's not a desired behavior, it's misleading and I (as VS user) spent time to find out why this was happening and how to avoid it.
I can open a PR if you agree

**Comment by hopdq91** [comment]
Hey guys,
I still get this issue when refresh checkout page by press F5 or F6 then Enter.
Do you have any suggestion for that?

My VSF version:
1.11.2

- Browser: Google Chrome Version 83.0.4103.106 (Official Build) (64-bit)
- OS:  Ubuntu 18.04.4 LTS
- Node: v11.5.0
