### ISSUE TITLE
Service worker error when start application

### ISSUE THREAD

**Issue by parnus01** [DivanteLtd/vue-storefront#2087]
when i landing to  https://localhost:3030/
console out error 
`Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode`

i don't know what wrong in setup , i start all container done and already sync data to elasticsearch.

**Comment by filrak** [comment]
Using https on localhost may be a cause. Can you check if it's the same without ssl?

**Comment by parnus01** [comment]
now it work by restart everything. Another question i have error when i place order request api return error 500 , Error Place Order , how can i investigate that isssue

**Comment by pkarw** [comment]
Please do check the vsapi console output error log

**Comment by parnus01** [comment]
`{code: 500, result: "Error: Error placing an order"}
code: 500
result: "Error: Error placing an order"`

**Comment by pkarw** [comment]
I meant vue-storefront-api console there should be details about the reason of this error that could be some Magento2 API subsequent errors

**Comment by parnus01** [comment]
i never know it has console api , how can i acces ?
