### ISSUE TITLE
Category Page does not remember state

### ISSUE THREAD

**Issue by revlis-x** [DivanteLtd/vue-storefront#2090]
## Current behavior
When scrolling down a category more products are lazily pulled in. When I click on a product which is not in the first initially loaded bunch to view it and then go back to the category listing I end up at the bottom of the initially loaded products and have to scroll down and reload more products again to wherever I was before.

## Expected behavior
When using back button on article page I get to the exact previous state with all previously loaded products with the correct scroll position.

## Steps to reproduce the issue
1. Scroll to the end of /c/women-20
2. Click last product
3. Click Back Button in Browser

# Can you handle fixing this bug by yourself?
Unfortunately not.

**Comment by filrak** [comment]
imho should land in 1.8

**Comment by filrak** [comment]
@revlis-x I'll take it for January milestone

**Comment by pkarw** [comment]
Closing this one as it will be solved with https://github.com/DivanteLtd/vue-storefront/issues/1104
