### ISSUE TITLE
Loading thumbnail image in gallery (configurable product)

### ISSUE THREAD

**Issue by mdanilowicz** [DivanteLtd/vue-storefront#2096]
## Current behavior
As a placeholder for images, we use the main product image. It's problematic especially when we show all gallery images as thumbnails

https://github.com/DivanteLtd/vue-storefront/blob/dfbe73f2ffeab38bce4ac3e219db6a09a257b261/core/modules/catalog/helpers/index.ts#L536

## Expected behavior
We should see proper image or placeholder with logo

# Can you handle fixing this bug by yourself?
No - decision needed

**Comment by filrak** [comment]
i believe @pkarw was working on this

**Comment by pkarw** [comment]
I don't exactly get the problem we must discuss this @mdanilowicz by the next chance we're on Hangout

**Comment by patzick** [comment]
It has been fixed with #2481
