### ISSUE TITLE
External Cart Syncronization works only in one way

### ISSUE THREAD

**Issue by valeriish** [DivanteLtd/vue-storefront#2105]
## Environment details
- Vue-storefront v1.6
- Magento v2.2.6
- External Checkout Module

## Steps to reproduce the issue

1. Add some products in to cart on VSF side
2. Go to Magento Cart page
3. Make some changes in products (change qty / remove product)
4. Go back to VSF

## Expected behavior
Changes applied on Magento side are also applied to VSF cart

## Current behavior
VSF pulls changes of Magento Cart but does not apply them and sends previous state to Magento

# Can you handle fixing this bug by yourself?
YES

BUG: force_client_state flag is ignored in servercartAfterPulled method

**Comment by pkarw** [comment]
Thanks, please propose the PR with fix :)
