### ISSUE TITLE
Route to robots.txt 

### ISSUE THREAD

**Issue by YouMakeMeHappy** [DivanteLtd/vue-storefront#2110]
How to add route to robots.txt file?

I have a file in root directory, but then I go to MY_SITE.com/robots.txt I got "page-not-found".

**Comment by pkarw** [comment]
You should add this file on proxy layer in front of vs (let’s say nginx) - https://divanteltd.github.io/vue-storefront/guide/installation/production-setup.html

You can also use Advanced Content Output features: 
https://divanteltd.github.io/vue-storefront/guide/extensions/extending-server-side-routes.html
https://divanteltd.github.io/vue-storefront/guide/core-themes/layouts.html#how-it-works

**Comment by filrak** [comment]
@YouMakeMeHappy it's already there on develop branch and will land in 1.7

Please take a look here https://github.com/DivanteLtd/vue-storefront/blob/develop/src/server/robots.js

**Comment by SGmuwa** [comment]
All links is broken
