### ISSUE TITLE
Replicating project folder for development of other shops

### ISSUE THREAD

**Issue by Decntdefalt** [DivanteLtd/vue-storefront#2114]
I set up a webshop with vue-storefront and I'm trying to setup another one.

Logima is the new webshop I'm trying to set up, hoversport is the existing one.

API for logima.io is running on
127.0.0.1:8081 0.0.0.0:* LISTEN 17530/.node.bin
Logima.io nginx is running on
0.0.0.0:81 0.0.0.0:* LISTEN 17482/nginx: master
Logima vue-storefront root folder is running on
127.0.0.1:3030 0.0.0.0:* LISTEN 18740/.node.bin

Meanwhile hoversport.no ports are in the same following order
127.0.0.1:8080 0.0.0.0:* LISTEN 19336/node /opt/bit
0.0.0.0:80 0.0.0.0:* LISTEN 17482/nginx: master
127.0.0.1:3000 0.0.0.0:* LISTEN 19252/PM2 v3.2.2: G

Every time I rebuild database or build API/root with pm2 comands or yarn build/yarn starts etc... it seems that the original project "hoversport.no" seems to be affected when I do changes in the duplicated project "logima.io", even though I've changed configurations. How do I go about this to fix it? They're on the same server so it should work, just not sure which file I need to modify since I've modified config files in API and Storefront folders, and ports are different.

**Comment by Decntdefalt** [comment]
This problem is initially fixed, but not by me. Still left with a big question on how this can happen, perhaps too much cache? How to go about cleaning cache for different types?

**Comment by pkarw** [comment]
Please try to run `yarn pm2 reload all` to re-load the new code for pm2. Please also read a pm2 docs on http://pm2.keymetrics.io/docs/usage/quick-start/ as I'm aware that it can be a little bit confusing (how pm2 works) if You haven't had experience with it before
