### ISSUE TITLE
Product attributes on product page: Extra space after every comma

### ISSUE THREAD

**Issue by phoenixdev-kl** [DivanteLtd/vue-storefront#2124]
## Current behavior
Every product attribute value, which is a string and contains a comma, renders with an extra space after the comma in the front end. So for example "1,6" renders as "1, 6" or "Haken Zamak chrom matt  ø 1,6 cm, h 8,7 cm" renders as "Haken Zamak chrom matt  ø 1, 6 cm,  h 8, 7 cm". This behavior makes sense IMHO only for (multi)select attributes.

## Expected behavior
Non-(multi)select attributes should output their value as it is, without extra space.

## Steps to reproduce the issue
As it would be a pain to setup your system with according product data you might want to set a breakpoint in core/modules/catalog/components/ProductAttribute.ts after line 22
```javascript
let parsedValues = this.product[this.attribute.attribute_code]
```
and while debugging set the value of _parsedValues_ to lets say "1,6", "Haken Zamak chrom matt  ø 1,6 cm, h 8,7 cm" or whatever string that contains a comma.

## Repository
https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/catalog/components/ProductAttribute.ts

## Can you handle fixing this bug by yourself?
MAYBE, depends if the following is a suitable approach. I would
- add "frontend_input" to entities.attribute.includeFields in config/default.json and
- in core/modules/catalog/components/ProductAttribute.ts the following before line 27
```javascript
        if (this.attribute.frontend_input !== 'multiselect' && this.attribute.frontend_input !== 'select') {
          return parsedValues
        }
```

## Environment details
- Browser: Google Chrome 71.0.3578.98
- OS: macOS 10.14.2 (18C54) Mojave
- Node: 5.6.0

## Additional information
- VSF connected to Magento 1
- Dockerized

**Comment by pkarw** [comment]
Thanks! The proposed approach is the right one. Please add the field in “default.json” and propose a pull request. Please use the “develop” branch as a source as there could be some conflicts with “master” config files at this point.

Thanks a lot!
