### ISSUE TITLE
Braintree Module

### ISSUE THREAD

**Issue by danrcoull** [DivanteLtd/vue-storefront#2129]
## What is the motivation for adding / enhancing this feature?
There is no default online order module for payment gateways a recent project required braintree as a gateway, so ive implemented the braintree dropin to the checkout process, that works with magento 2 default braintree module, for both auth and auth and capture. 

Works by creatting the gateway and then creating a payment nonce to subit with additional data. 

# Can you complete this feature request by yourself?
yes see [https://github.com/danrcoull/vsf-payment-braintree](https://github.com/danrcoull/vsf-payment-braintree)

**Comment by pkarw** [comment]
This is awesome! @filrak we should definitely share it on our official SM

**Comment by pkarw** [comment]
... and add to the docs link to it and to the awesome list as well

**Comment by pkarw** [comment]
I've added https://github.com/frqnck/awesome-vue-storefront/pull/5 + will add it to our docs

**Comment by pkarw** [comment]
I've added it to the docs as well :)

**Comment by danrcoull** [comment]
Thanks :D
