### ISSUE TITLE
Use separate setting for api url

### ISSUE THREAD

**Issue by Cyclonecode** [DivanteLtd/vue-storefront#2131]
## What is the motivation for adding / enhancing this feature?

The configuration file uses absolute paths for each api endpoint. For instance:

```
  "cart": {
    "create_endpoint": "https://demo.vuestorefront.io/api/cart/create?token={{token}}",
    "updateitem_endpoint": "https://demo.vuestorefront.io/api/cart/update?token={{token}}&cartId={{cartId}}",
    "deleteitem_endpoint": "https://demo.vuestorefront.io/api/cart/delete?token={{token}}&cartId={{cartId}}",
    "pull_endpoint": "https://demo.vuestorefront.io/api/cart/pull?token={{token}}&cartId={{cartId}}",
    "totals_endpoint": "https://demo.vuestorefront.io/api/cart/totals?token={{token}}&cartId={{cartId}}",
    "paymentmethods_endpoint": "https://demo.vuestorefront.io/api/cart/payment-methods?token={{token}}&cartId={{cartId}}",
    "shippingmethods_endpoint": "https://demo.vuestorefront.io/api/cart/shipping-methods?token={{token}}&cartId={{cartId}}",
    "shippinginfo_endpoint": "https://demo.vuestorefront.io/api/cart/shipping-information?token={{token}}&cartId={{cartId}}",
    "collecttotals_endpoint": "https://demo.vuestorefront.io/api/cart/collect-totals?token={{token}}&cartId={{cartId}}",
    "deletecoupon_endpoint": "https://demo.vuestorefront.io/api/cart/delete-coupon?token={{token}}&cartId={{cartId}}",
    "applycoupon_endpoint": "https://demo.vuestorefront.io/api/cart/apply-coupon?token={{token}}&cartId={{cartId}}&coupon={{coupon}}"
  },
``` 

Wouldn't it be more convenient to set the base url for the api in a separate configuration entry and then use relative paths for all endpoints? Something like this:

```
  "api": {
    "url": "https://demo.vuestorefront.io/api/"
  },
  "cart": {
    "create_endpoint": "cart/create?token={{token}}",
    "updateitem_endpoint": "cart/update?token={{token}}&cartId={{cartId}}",
    "deleteitem_endpoint": "cart/delete?token={{token}}&cartId={{cartId}}",
    "pull_endpoint": "cart/pull?token={{token}}&cartId={{cartId}}",
    "totals_endpoint": "cart/totals?token={{token}}&cartId={{cartId}}",
    "paymentmethods_endpoint": "api/cart/payment-methods?token={{token}}&cartId={{cartId}}",
    "shippingmethods_endpoint": "cart/shipping-methods?token={{token}}&cartId={{cartId}}",
    "shippinginfo_endpoint": "cart/shipping-information?token={{token}}&cartId={{cartId}}",
    "collecttotals_endpoint": "cart/collect-totals?token={{token}}&cartId={{cartId}}",
    "deletecoupon_endpoint": "cart/delete-coupon?token={{token}}&cartId={{cartId}}",
    "applycoupon_endpoint": "cart/apply-coupon?token={{token}}&cartId={{cartId}}&coupon={{coupon}}"
  },
````

Not really sure that the above is a good idea so this is more a thought and a question. I guess there even might be a good reason to use absolute urls for each endpoint.

## What are the acceptance criteria 

- When the base api url can be set in a separate configuration option.

# Can you complete this feature request by yourself?

YES

**Comment by Cyclonecode** [comment]
Agree and I understand that it will take some effort to actual change everything and at the same time make sure so old configuration files would work. I just thought about this from the beginning since it felt like I was repeating myself when changing the domain used for the api and so on. There is not really any reason to do this at the moment, but if you just had started working on this I had voted for using a separate entry for the base api =)

**Comment by pkarw** [comment]
Sure, I'm marking this as a feature request

**Comment by pkarw** [comment]
It has been proposed by @BartoszLiburski - not sure if it has been finally merged in ...

**Comment by Cyclonecode** [comment]
I don't see that this is merged?

**Comment by daksamit** [comment]
I think, it should be more like option than standard. What if we want point to external api like:
```
  "api": {
    "url": "https://demo.vuestorefront.io/api/"
  },
  "cart": {
    "create_endpoint": "cart/create?token={{token}}",
    ...
    "deletecoupon_endpoint": "https://demo.anotherstore.io/api/cart/delete-coupon?token={{token}}&cartId={{cartId}}",
    "applycoupon_endpoint": "https://demo.anotherstore.io/api/cart/apply-coupon?token={{token}}&cartId={{cartId}}&coupon={{coupon}}"
  },
```

We should check if endpoint starts with `https://` otherwise use declared api.url as prefix.

**Comment by pkarw** [comment]
@daksamit it could make sense; mabye just propose aPoC?

Definitely we shouldn’t change the current behavior - we can add this new endpoint etc but as an option

**Comment by daksamit** [comment]
Ya, when we call endpoint, maybe sth like, instead directly `rootStore.state.config.orders.endpoint` :
```
import { callApi }  from '@vue-storefront/core/helpers'
...
const task: any = await TaskQueue.execute({ url: callApi('orders.endpoint'), // sync the order
...
```
then, we check endpoints from config and return the right endpoint.
