### ISSUE TITLE
Service worker only generated for production

### ISSUE THREAD

**Issue by Cyclonecode** [DivanteLtd/vue-storefront#2142]
## Current behavior
When running in dev mode with a valid SSL certificate I receive the following error in the console: 

```
The script resource is behind a redirect, which is disallowed.
Failed to load resource: net::ERR_UNSAFE_REDIRECT
```

Looking at the `core/scripts/server.js`:

```
app.use('/service-worker.js', serve('dist/service-worker.js', {
  setHeaders: {'Content-Type': 'text/javascript; charset=UTF-8'}
}))
```

But only seems to be generated when building for production so when running in development of course I get a redirect to the not found page which causes the above error message.

## Expected behavior
No error message should be displayed when trying to load the `service-worker.js` file under development.
I guess either one could check which environment node is running under and if not production skip register the service worker or always generate a service worker under the `dist` folder?

## Repository

# Can you handle fixing this bug by yourself?

## Environment details

- Browser: 
- OS: 
- Node:

**Comment by pkarw** [comment]
It's been fixed 2 days ago by me in "develop" - please check :)

**Comment by Cyclonecode** [comment]
@pkarw - Ah nice. i'm still using vs 1.5.0 and I am not really able to switch at the moment and that's the reason I didn't notice this =)

**Comment by pkarw** [comment]
OK, You can add just "yarn build:sw" to the "yarn dev" chain in package.json and that's all :)

**Comment by Cyclonecode** [comment]
@pkarw - Yes I did and it seems to be working as expected - thank you very much =)
