### ISSUE TITLE
Menu button not working on AMP

### ISSUE THREAD

**Issue by jorkvist** [DivanteLtd/vue-storefront#2160]
## Current behavior
Clicking the menu button on a AMP page does not open any menu. Actually nothing happens.  https://demo.vuestorefront.io/amp/c/women-20

## Expected behavior
Menu should open.

## Steps to reproduce the issue
Goto: https://demo.vuestorefront.io/amp/c/women-20 and click the left menu button.

## Repository

# Can you handle fixing this bug by yourself?
NO

## Environment details
- Browser: Chromes Latest
- OS: Mac OS

**Comment by gk-daniel** [comment]
@jorkvist Is this issue still relevant? Since locally the amp page does not exist
