### ISSUE TITLE
Add an example how to add custom REST backend

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2166]
## What is the motivation for adding / enhancing this feature?

We do have the [`searchAdapter`](https://github.com/DivanteLtd/vue-storefront/tree/develop/core/store/lib/search/adapter) abstraction layer for API backends. Would be great to add the `simplerest` API backend that DOES NOT require elasticSearch.

I mean - we should create a simple `vue-storefront-api` like API which is accepting the [`QueryObject`](https://github.com/DivanteLtd/vue-storefront/blob/develop/core/store/lib/search/adapter/api/elasticsearchQuery.js) and returns some items from database + implement the rest methods that we have there. Currently the REST adapter transforms the query to `elasticSearchQuery` to comply with Elastic DSL. The idea is to not do this as our QueryObject is much simpler than Elastic DSL. For [example the `graphQL`](https://github.com/DivanteLtd/vue-storefront/tree/develop/core/store/lib/search/adapter/graphql) adapter doesn't transorm the query but rather sends the query object as a part of gql query

The idea is to replace the [vue-storefront-integration-boilerplate](https://github.com/DivanteLtd/vue-storefront-integration-boilerplate) with something simpler.

## What are the acceptance criteria 

- simple REST API that can be a base for further 3rd party integrations

**Comment by CodeSkills** [comment]
I have to do some tweaks before publishing it within some repo. I will do so when someone PMs me that they want to continue or when I get time to do so. So feel free to PM me anyone if interested.

**Comment by pkarw** [comment]
I'm on this!
https://github.com/DivanteLtd/vue-storefront-simple-api

**Comment by pkarw** [comment]
Real life exmaple of this:
https://github.com/cristian-g/vue-storefront/compare/5c3f4aa2f827b4910248f4a666b24e93ba5d5248...develop

**Comment by sandermangel** [comment]
@pkarw was this finished? Can we add the "real life example" to the README maybe? :)

**Comment by pkarw** [comment]
It hasn’t been finished yet :/ let’s keep it open

**Comment by OnlyC** [comment]
This is what I'm looking for. Wanted to implement VSF to my ERP backend a year ago but building the API with elasticSearch was too complicated for me.
