### ISSUE TITLE
Remove Elastic DSL / bodybuilder from frontend

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2167]
## What is the motivation for adding/enhancing this feature?

This is related to #2166 
`bodybuilder` is about 200KB - and in fact the Elastic query DSL could be constructed 100% in the `vue-storefront-api`

In that case the [catalog.js](https://github.com/DivanteLtd/vue-storefront-api/blob/290b18c29996d0033d1f97d893fe9bf22e674e37/src/api/catalog.js#L81) endpoint no longer will be raw proxy but it will do [the logic which is currently done on frontend](https://github.com/DivanteLtd/vue-storefront/blob/develop/core/store/lib/search/adapter/api/elasticsearchQuery.js).

So, the thing is that `vue-storefront-api` should get the [simple query object](https://github.com/DivanteLtd/vue-storefront/blob/develop/core/store/lib/search/searchQuery.js) and build DSL itself. It will also make `vue-storefront-api` ... in fact simpler. Because being partially a proxy to Elastic and partially a REST API isn't easy to understand.

## What are the acceptance criteria 

- bodybuilder removed from `vue-storefront` dependencies
- we should have this as an `config` option - as some other implementations can base even directly on `bodybuilder` we should have an option in both: `vue-storefront` and `vue-storefront-api` configs to switch this new mode on/off (default is: on)

@patzick and @mdanilowicz let me know what do You think on that?

**Comment by patzick** [comment]
I would consider Elasticsearch JS library for that as replacement for bodybuilder.
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/introduction.html

**Comment by pkarw** [comment]
We removed elasticsearch-js as a bundle size optimization - it's not a way to go for sure.

**Comment by pkarw** [comment]
Its all about sending the SearchQuery object in plain json to /api/catalog and then construct elasticsearch query in API instead of constructing it in the client.

The SearchAdapter and ElasticsearchQuery classes should be refactored simplified 
It should be kept as an option to have the current behavior (building queries in client) for backward compatibility but it should be disabled by default

**Comment by pkarw** [comment]
@andrzejewsky can you please take care of this one after finishing the tasks from 1.22 please?

**Comment by andrzejewsky** [comment]
@pkarw yeah, sure 🎉
