### ISSUE TITLE
Minify html + css

### ISSUE THREAD

**Issue by jorkvist** [DivanteLtd/vue-storefront#2182]
## What is the motivation for adding / enhancing this feature?
The current index document is pretty long and just minify/compress the output of html and css in the document will save around 80% of the document size. 

# Can you complete this feature request by yourself?
NO

## Additional information
Tested to paste the html document here: https://htmlcompressor.com/compressor/
And it gave a 88% saving when compressed.

**Comment by pkarw** [comment]
the simplest solution is to enable gzip in the proxy but we can also use some express.js proxy

**Comment by pkarw** [comment]
https://www.npmjs.com/package/express-minify

We should use it only in the production mode

**Comment by filrak** [comment]
@patzick afaik you've done it?

**Comment by patzick** [comment]
@filrak we we have less data now in html and css on SSR, but is still could be minified on server render output. I'll assign myself to to this

**Comment by pkarw** [comment]
Plus - gzip / brotli also as a Express.js middlewares as we discussed

**Comment by pkarw** [comment]
These middlewares should be available to disable/enable via `config.server.enableOutputCompression`, `config.server.enableOutputMinify` ...

We can also consider the Webpack plugin for static files (CSS) minimization

Please make sure this mechanism is supporting Output caching
