### ISSUE TITLE
"Error placing an order" on Checkout

### ISSUE THREAD

**Issue by kovinka** [DivanteLtd/vue-storefront#2195]
## Current behavior
while placing an order, Magento 2 looks like quote sometimes is not saved/updated at that moment. As result API returns 500 error in `api/order/create` response "Error: Error placing an order"

http://demo.vuestorefront.io

<img width="1430" alt="screen shot 2019-01-15 at 10 33 34 am" src="https://user-images.githubusercontent.com/10535709/51176937-ea007300-18c6-11e9-8016-df5b5644b131.png">

<img width="1465" alt="screen shot 2019-01-15 at 10 33 56 am" src="https://user-images.githubusercontent.com/10535709/51176947-f08eea80-18c6-11e9-8680-af6a47035eb4.png">

## Steps to reproduce the issue
Add product to cart, directly proceed to checkout and click on "Place order" button. 

## Repository
master branch

## Can you handle fixing this bug by yourself?
no

## Environment details

- Browser: Chrome 71
- OS: MacOS Mojave 10.14.2
- Node: v8.12.0

## Additional information

**API logs:**
```
debug: Response received.
GET /api/cart/payment-methods?token=&cartId=Pw8pGGQ1z1GfIiv6NNbtmaTJlJzOtEmi 200 3481.787 ms - 410
debug: Response received.
error: API call failed: Shipping method is not applicable for empty cart
POST /api/cart/shipping-information?token=&cartId=Pw8pGGQ1z1GfIiv6NNbtmaTJlJzOtEmi 500 3832.740 ms - 72
debug: Response received.
GET /api/stock/check?sku=100759 200 2050.692 ms - 644
debug: Response received.
POST /api/cart/update?token=&cartId=Pw8pGGQ1z1GfIiv6NNbtmaTJlJzOtEmi 200 5066.396 ms - 160
```
Cannot see any logs in Magento 2 instance connected to this error.

There is similar problem that is connected to current behavior - shipping methods are not loaded and default "DPD Courier" id displayed. After returning to non-checkout page and proceeding to Checkout - default shipping method is replaced with methods from Magento.

Local environment:

<img width="1418" alt="screen shot 2019-01-15 at 1 19 06 pm" src="https://user-images.githubusercontent.com/10535709/51177489-62b3ff00-18c8-11e9-8dbd-754301739833.png">

<img width="1455" alt="screen shot 2019-01-15 at 1 19 23 pm" src="https://user-images.githubusercontent.com/10535709/51177516-72cbde80-18c8-11e9-9d4f-15d930754229.png">

`"directBackendSync": true` in VS and `"useServerQueue": false` in API

**Comment by patzick** [comment]
Hey @kovinka , yesterday we've updated master branch with 1.7 release. I cannot replicate your case. Could you check if it's still an issue for you?

**Comment by kovinka** [comment]
@patzick, cannot check, looks like some problems on https://demo.vuestorefront.io/, cleared all caches, but cannot open any page
<img width="960" alt="screen shot 2019-01-16 at 2 17 32 pm" src="https://user-images.githubusercontent.com/10535709/51248661-86934580-1999-11e9-906a-8d44271362f6.png">

**Comment by patzick** [comment]
Looks definitely like cache problem, because current files hash is `9e0d450bd6af8bbf9528`

Could you try again? Please go to `Application -> Clear storage -> Clear site data` and run `Ctrl+f5`/`CMD+r`

**Comment by kovinka** [comment]
@patzick, done, also tried to open in incognito mode, hash is is correct 
<img width="1042" alt="screen shot 2019-01-16 at 2 31 41 pm" src="https://user-images.githubusercontent.com/10535709/51249347-ab88b800-199b-11e9-9934-4016fdd80480.png">

**Comment by kovinka** [comment]
Clicking on "Place the order" does nothing on orderReview step after placing the order and returning to checkout again, after reloading the page - button can be clicked (i think because of PR https://github.com/DivanteLtd/vue-storefront/pull/2133), @patzick could you please check it and after that i can try to reproduce it again

**Comment by pkarw** [comment]
@kovinka is this  still a case?

**Comment by kovinka** [comment]
@pkarw 
as for checkout - yes, the "Place order" button still does nothing for 2nd checkout process. 
Steps: 
- add item, proceed to checkout, choose "Check/money order", place order
- don't reload the page, return to any product, add it to cart, proceed to checkout, don't switch between payment methods (Check/money order should be selected) and try to place order - no action.

as for "error while placing order" - will check again, it reproduces not every time.

**Comment by pkarw** [comment]
@patzick it would be great to check this before Wednesday

**Comment by patzick** [comment]
@kovinka thanks, you're right. #2505 will solve this problem
