### ISSUE TITLE
Wrong category is matched

### ISSUE THREAD

**Issue by jorkvist** [DivanteLtd/vue-storefront#2211]
## Current behavior
I use useMagentoUrlKey=true. Issue is that wrong category is matched when i click a category in the menu. I have multiple categories with url_key something like: "XXXXXX", "AA-XXXXXX", and "BB-XXXXXX". When i click the link of "XXXXXX" it loads category "AA-XXXXXX".

Seams like the issue is this one that is running when i click a category:
{“query”:{“bool”:{“filter”:{“bool”:{“must”:[{“terms”:{“url_key”:[“XXXXXX”]}},{“terms”:{“is_active”:[true]}}]}}}}}

The response here is a json answers for all of "XXXXXX", "AA-XXXXXX", and "BB-XXXXXX". Where "AA-XXXXXX" is the first in the response, so it get shown as the category. Where another category is meant to be loaded.

## Expected behavior
Correct category loaded

## Repository
1.7 

# Can you handle fixing this bug by yourself?
No

## Environment details
- Browser: Chrome Latest
- OS: osx

**Comment by pkarw** [comment]
This has been fixed today
