### ISSUE TITLE
SSR problem on checkout page

### ISSUE THREAD

**Issue by vue-kacper** [DivanteLtd/vue-storefront#2216]
## Current behavior
App crash on page reload (checkout page)

## Expected behavior
Render checkout page or redirect to homepage without errors in console

## Steps to reproduce the issue
Visit (as guest): https://demo.vuestorefront.io/
Add product to cart
Proceed to checkout
When you are on "https://demo.vuestorefront.io/checkout" refresh page
You will be redirected to homepage (check error in console) store UI like menu etc. won't be functional

## Environment details
- Browser: Latest Chrome
- OS: Win 10
- Node: Latest LTS

## Additional information
![image](https://user-images.githubusercontent.com/42430550/51278735-ad726b80-19db-11e9-90e0-7236fffd2639.png)

Related issue: https://github.com/DivanteLtd/vue-storefront/issues/1642

**Comment by pkarw** [comment]
I had very similar issue and it was cache related - I mean I cannot reproduce this one - there is a checkout redirect to home page but everything works just fine. In ma case doing Clear Storage helped for that

**Comment by vue-kacper** [comment]
@pkarw I've reproduced this issue on 3 different win 10 machines (chrome 71) (https://demo.vuestorefront.io) I'm sure it's not a cache problem. Maybe it's Vue.js core problem connected with windows platform. Please check it on BrowserStack

**Comment by pkarw** [comment]
Sure; have You tested it on localhost + incognito window as well?
I've observed and noted some maybe related issue - when you've got products in the cart and doing ctrl+f5 Vue is generating the hydration issue as we're loading cart (car/load call) before the site has been hydrated; the problem doesn't exist when the shopping cart is empty @patzick - You've got this issue on Slack from me :)

**Comment by vue-kacper** [comment]
@pkarw I'm testing it right now and:

There is no problem on local env (yarn dev)

Problem appears only on production build (yarn build && yarn start)

Confirmed in icognito mode on localhost as well (latest, clean develop branch)

**Comment by ananth-iyer** [comment]
@pkarw Same error occurred on [demo.vuestorefront.io](demo.vuestorefront.io):
1. Login with test customer
2. Added items in cart
3. Clear browser cache - test on both normal & private browser window
4. Login to test customer
5. Page refresh - same console error
**DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.**

#### Actual Result
1. Header button not working
2. Click on product on homepage - working but showing same error on every page

**Comment by pkarw** [comment]
Thanks! @patzick and @vue-kacper please make sure that Kacper’s solution solves this issue and if so please do a hotifx

**Comment by grimasod** [comment]
Does the hotfix completely resolve this issue in the default theme? I applied it to our custom theme, but the problem is still there. It's new in 1.7 and prevents us from upgrading. In dev mode it seems to be the same issue that gives the common Vue error: 

> The client-side rendered virtual DOM tree is not matching server-rendered content

In our theme, we use a lot of "v-if" to minimize unnecessary DOM nodes for various display sizes

**Comment by grimasod** [comment]
Just to confirm, as @ananth-iyer describes, the issue still exists on https://demo.vuestorefront.io/

- It only happens for logged-in users.
- It's not necessary to navigate to the checkout. Just reload the home page after logging in.

**Comment by pkarw** [comment]
@vue-kacper can You please check it and close if it's done?
