### ISSUE TITLE
Move store/lib/search to core/lib/search

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#2225]
## What is the motivation for adding / enhancing this feature?

As we are slowly getting rid of vs store package all the content from store/lib should be moved to core/lib folder. Since this one is pretty huge and have many imports it's a separate task

## What are the acceptance criteria 

- `store/lib/search` is moved to `core/lib/search`
- all imports are corrected

**Comment by lukeromanowicz** [comment]
@filrak 
What do we do with store/lib/search.ts and store/lib/types/search? Moving first one is obvious but types don't really match core/lib pattern
