### ISSUE TITLE
Move store/types to core/types and use named exports

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#2226]
## What is the motivation for adding / enhancing this feature?

In the process of getting rid of content from core/store types should moved and merged with core/types folder. We should also use named export instead of default one to have consistant naming across whole application

## What are the acceptance criteria 

- Types from `core/store/types` are moved to `core/types`
- Types with default export are using named export now
- all import pathes are corrected

**Comment by kruchy8** [comment]
I'll try it

**Comment by lukeromanowicz** [comment]
@kruchy8 please ignore core/store/types/search as they were merged to core/store/search in #2225

**Comment by kruchy8** [comment]
@ lukeromanowicz I have already moved it into another folder, do you want me to revert this changes?
@filrak please include my account into collaborators

**Comment by lukeromanowicz** [comment]
@kruchy8 well... the conflict is certain, the question is who's gonna resolve it :)

**Comment by kruchy8** [comment]
I'm leaving it up to you guys

**Comment by lukeromanowicz** [comment]
@kruchy8 let's leave your version of code, I'll fix mine

**Comment by kruchy8** [comment]
👍
