### ISSUE TITLE
Optimize the bundle size

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2232]
## What is the motivation for adding / enhancing this feature?

This is an open task. Each lib removed/replaced to make the overall bundle size smaller - is a win in here :)

**Comment by lukeromanowicz** [comment]
I'm on it :)

**Comment by pkarw** [comment]
I'd like us to focus on this task. My ideas of simple ways to optimize the bundle size:
1. Disable non-used modules
- `src/amp-renderer`
- `src/google-tag-manager`
- `src/hotjar`
- `src/google-analytics`
- `core/offline-order` (+ remove all dependencies + move all offline orders logick into this module prior to disabling it :) )
2. Remove `localForage` - we're now using only LocalStorage and it's pretty limited usage. The `storage.ts` is a good place to start - it's a proxy over localForage. We can change the proxied calls from `localForage.setItem` to `localStorage.setItem` etc. -> https://bundlephobia.com/result?p=localforage@1.7.3
4. Remove `apollo-client` references when project is not using graphQL driver (`config.server.api != graphql`) - it should be somehow done dynamically or simply separate all the logick of apollo to another core/module to not let webpack to include apollo https://bundlephobia.com/result?p=apollo-client@2.6.4, https://bundlephobia.com/result?p=vue-apollo@3.0.0, https://bundlephobia.com/result?p=graphql@14.5.8
5. Remove `bodybuilder` by moving the query language to `vue-storefront-api` - https://github.com/DivanteLtd/vue-storefront/issues/2167
6. Scan the bundle with https://bundlephobia.com/ or `webpack-bundle-analyzer`
7. Remove `vue-carousel` - https://bundlephobia.com/result?p=vue-carousel@0.18.0
8. Remove all unused imports

**Comment by pkarw** [comment]
https://www.dropbox.com/s/lktr1cttl2gojwo/Screenshot%202019-10-24%2010.58.53.png?dl=1

The `src/modules` it's really huge - it's not worth the size: https://github.com

Bundle overview:
https://www.dropbox.com/s/yn761a68sncvlqn/Screenshot%202019-10-24%2010.57.48.png?dl=1

**Comment by pkarw** [comment]
![Screenshot 2019-10-24 11 04 02](https://user-images.githubusercontent.com/211899/67470433-013a7100-f64e-11e9-9a86-88ad060c21c1.png)

**Comment by pkarw** [comment]
bodybuilder+graphql = 500kB

**Comment by pkarw** [comment]
[x] `graphql` is already loaded dynamically

**Comment by pkarw** [comment]
[x] `bodybuilder` has been removed as a part of #2167

**Comment by gibkigonzo** [comment]
WIP - Remove localForage
I will try to move it to separate package and remove all timeouts from `storage.ts`
