### ISSUE TITLE
Service worker is to eager to load .js and .gz

### ISSUE THREAD

**Issue by jorkvist** [DivanteLtd/vue-storefront#2254]
## Current behavior
SW loads both .js and js.gz version:
![image](https://user-images.githubusercontent.com/5425824/51394357-7d8daa00-1b3a-11e9-9632-007c48f90d2c.png)

## Expected behavior
Just load one version of the file

## Steps to reproduce the issue
First load of a page. 

## Repository
1.7

# Can you handle fixing this bug by yourself?
NO

## Environment details
- Browser: chrome latest
- OS: mac os
- Node: 

## Additional information
Tested on https://stage.ribatex.se/ 
Also the .gziped version looks a bit wierd in devtools and missing "encoding type": gzip 
![image](https://user-images.githubusercontent.com/5425824/51394610-0b699500-1b3b-11e9-8c64-820f59b138ca.png)

**Comment by pkarw** [comment]
@patzick is this fixed already?

**Comment by hdlion** [comment]
Filterout the files you dont need. Solution is here.

workbox.precaching.precacheAndRoute((self.__precacheManifest || []).filter((e) => {
  if (
    e &&
    e.url &&
    e.url.match &&
    e.url.match(/(assetlinks.json|offline.html.br|manifest.json|.js.br|.css.br|.jpg|.png|.svg|.webp|.gif|.ico|.woff2)/)
  ) {
    return true;
  }
  return false;
}));
