### ISSUE TITLE
Clear Filter Button not working

### ISSUE THREAD

**Issue by revlis-x** [DivanteLtd/vue-storefront#2262]
## Current behavior
In the mobile view of the filters, there is a "Clear"-Button to reset the filters. Clicking this returns a 500 Server Error from vsf-api and filters are not reset.

## Expected behavior
Category is reset to non-filtered view.

## Steps to reproduce the issue
This is reproducable on https://demo.storefrontcloud.io
-> click filter reset button on mobile view.

# Can you handle fixing this bug by yourself?
Unfortunately not.

## Additional information
Request goes for example to `https://demo.storefrontcloud.io/api/catalog/vue_storefront_catalog/product/_search?size=50&from=0&sort=&_source_exclude=description,sgn,*.sgn,msrp_display_actual_price_type,*.msrp_display_actual_price_type,required_options&_source_include=type_id,sku,name,tax_class_id,special_price,special_to_date,special_from_date,price,priceInclTax,originalPriceInclTax,originalPrice,specialPriceInclTax,id,image,sale,new,configurable_children.image,configurable_children.sku,configurable_children.price,configurable_children.special_price,configurable_children.priceInclTax,configurable_children.specialPriceInclTax,configurable_children.originalPrice,configurable_children.originalPriceInclTax,configurable_children.color,configurable_children.size,configurable_children.id,configurable_children.tier_prices,product_links,url_key,status,tier_prices&request=undefined`

Problem seems to be caused by `request=undefined` param.

**Comment by vue-kacper** [comment]
@pkarw done :)
