### ISSUE TITLE
Error in GraphQL doc

### ISSUE THREAD

**Issue by aimeos** [DivanteLtd/vue-storefront#2277]
Link for "to create your own adapter" returns als 404 in https://docs.vuestorefront.io/guide/basics/graphql.html

**Comment by carmanchris31** [comment]
@aimeos Does this mean there's development for an aimeos adapter underway? I tried searching but only came upon this.

**Comment by aimeos** [comment]
@carmanchris31 We well definitively build a GraphQL interface for Aimeos. It's unclear if there will be an adapter for vue-storefront because vue-storefront is implemented extremely tight to the Magento data model. This makes it very difficult to integrate of what Aimeos is capable. Maybe if @pkarw and @filrak would switch to a much more general data model for vue-storefront.
