### ISSUE TITLE
Large store times out during initial elastic search import.

### ISSUE THREAD

**Issue by dambrogia** [DivanteLtd/vue-storefront#2284]
## Current behavior

I'm working on migrating a large M2 store that has ~300k products. During the initial setup for M2, the elastic search import takes so long that my terminal session times out and the task stops. I can not run the `yarn installer` command all the way through to completion.

## Expected behavior

I would expect to run the command and receive a successful response. Even a simple  `$? == 0` would be fine. 

## Steps to reproduce the issue

    yarn; yarn installer;
    ? Would you like to use https://demo.vuestorefront.io as the backend? No
    ? Please provide Git path (if it's not globally installed) git
    ? Please provide path for installing backend locally ../vue-storefront-api
    ? Choose path for images endpoint Custom url
    ? Please provide path for images endpoint https://<media_url>
    ? Please provide your magento url https://<base_url>
    ? Would You like to perform initial data import from Magento2 instance? Yes
    ? Please provide the url to your magento rest api https://<base_url>/rest
    ? Please provide your consumer key <consumer_key>
    ? Please provide your consumer secret <consumer_secret>
    ? Please provide your access token <access_token>
    ? Please provide your access token secret <access_token_secret>

    Trying to create log files...
    info: Winston logging library initialized.

    Validating magento integration configuration...
    debug: Calling API endpoint: GET https://<base_url>/rest/V1/categories token:
    info:  url=https://<base_url>/rest/V1/categories, method=GET, Authorization=OAuth oauth_consumer_key="<consumer_key>", oauth_nonce="<nonce>", oauth_signature="<sig> %3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1548442802", oauth_token="<token>", oauth_version="1.0", json=true, body=undefined
    debug: Response received.

    Cloning backend into '../vue-storefront-api'...

    Trying change directory to '../vue-storefront-api'...

    Working in directory '/var/www/vue-storefront-api'...

    Installing backend npm...

    Creating backend config 'config/local.json'...

    Starting docker in background...

    Importing data from magento into ElasticSearch...
    packet_write_wait: Connection to <remote_ip> port 22: Broken pipe

## Repository

Private.

# Can you handle fixing this bug by yourself?

Yes: 
I Think it would be nice to have CLI arguments/options to pass in so this could be run in the background included with `nohup` or a process manager of someones choice. Process Manager would be out of the scope of this issue. 

Further more: 
The following issues speaks about Single Responsibility Principle (#28) and I think that would help out with this issue as well. There are multiple classes in this file ~865 line file and it would nice to see them broken out and separated. 

Questions: 
As a newbie to this repo, does this script have tests? Where can they be found and how can I contribute to them?

## Environment details

- Browser: 
- OS: 
- Node: 
Ubuntu 18.04, Node 8.14.0

**Comment by pkarw** [comment]
Hi! Thanks for pointing this out!

Please feel free to improve our installer + run the import process in the background; that's correct it could be executed thru `nohup` or whatever as it might take a lot of time.

The installer doesn't have tests yet. Some of the modules already have tests (`core/modules/*/test`) - and You can also find the `e2e` tests on Cypress.
