### ISSUE TITLE
[demo] Problem with API responses on checkout page

### ISSUE THREAD

**Issue by vue-kacper** [DivanteLtd/vue-storefront#2290]
## Current behavior
VSF api responds with 500 Internal Server Error status on checkout page

## Expected behavior
VSF api shouldn't responds with 500 Internal Server Error code. 

## Steps to reproduce the issue

Visit: **https://test.storefrontcloud.io**
Add product to cart
Click "Go to checkout"
Observe console "network" tab - POST request to "api/cart/shipping-information" responds with 500 error code
Observe console "network" tab - POST request to "api/cart/payment-methods" responds with 500 error code

Visit: **https://demo.vuestorefront.io**
Add product to cart
Click "Go to checkout"
Observe console "network" tab - GET request to "/api/cart/pull" responds with 500 error code

**Comment by pkarw** [comment]
I don’t have it - it could be a temporary problem with magento instance. If you’re stil having this issue please paste the error messages from these failing endpoints please

**Comment by vue-kacper** [comment]
@pkarw I think it's magento issue but we should handle this type of errors better at vsf api layer

https://youtu.be/4Qu0UbRbnl8

**Comment by pkarw** [comment]
Thanks, now I get it. We need some magento expert help then - probably Agata. It seems like sometimes Magento quote (shopping cart) is getting into wrong state; we need to debug it

**Comment by pkarw** [comment]
Not sure how should be handle these dynamic request errors differently; any suggestions?

**Comment by vue-kacper** [comment]
It looks like magento 500 status code responses are gone on demo :) I think we should leave them as they are for now. Since those errors are dynamic we don't have much control here

**Comment by gabrielecontitaguali** [comment]
Hi, I'm encountering the same 500 error in my installation both for shipping information and payment-methods.

In addiction to this then the order can't be placed. 
In some forum I read about opcache can cause the issue?

any update from you?
