### ISSUE TITLE
Configure demo-magento2.vuestorefront.io synchro for orders + products

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#230]
... and check promo prices and taxes configuration

**Comment by karolbzik** [comment]
@pkarw are "promo prices" and "taxes" working in the current integration of Vue Storefront with Magento2 on the demo?

**Comment by pkarw** [comment]
No, and they won't till 0.3 or 0.4; right now I'm event not starting the topic because it's quite sophisticated one
