### ISSUE TITLE
User authentication on SSR

### ISSUE THREAD

**Issue by vue-kacper** [DivanteLtd/vue-storefront#2303]
## What is the motivation for adding / enhancing this feature?

Right now our SSR HTML markup and SSR vuex state is only available for unauthenticated user. The problem starts when we want to render page with authenticated user specific features - for example user account menu. Those right now can be build only on client side, otherwise we will get HTML markup mismatch error, 

It would be nice to to store hashed JWT in cookies - then SSR can access this, authenticate user via VSF api and then populate vuex state with user data.

Benefits? Full SSR markup will be available both for guest and authenticated user specific pages.

**Comment by pkarw** [comment]
Its doable however it will make VS pretty hard to scale horizontally- with session less architecture it’s trivial. So if we’d like to have it it should be optional
