### ISSUE TITLE
Category page show wrong count "50 Items"

### ISSUE THREAD

**Issue by jorkvist** [DivanteLtd/vue-storefront#2304]
## Current behavior
When browsing a category page with more than 50 product on mobile the "X Items" in top of the page always is "50 Items", even if it more products than 50 items. It uses {{ productsCounter }}. If you change it to {{ productsTotal }} you will get the correct number of items on the current category. 

## Repository
1.7.0 

# Can you handle fixing this bug by yourself?
No

## Environment details
- Browser: Chrome mobile

**Comment by jorkvist** [comment]
Also, "items" is a static text.

**Comment by renatocason** [comment]
Hi @filrak ,

I'm looking into this, can you assign it to me?

Thanks,
Renato
