### ISSUE TITLE
Sticky notifications - hasNoTimeout without function

### ISSUE THREAD

**Issue by phoenixdev-kl** [DivanteLtd/vue-storefront#2307]
## Current behavior
After removing a product from micro cart, the notification "Are you sure you would like to remove this item from the shopping cart? CANCEL / OK" appears for a couple of seconds and then disappears, product stays in cart.
This behavior is not "wrong". But in core/compatibility/components/blocks/Microcart/Product.js we pass parameter *hasNoTimeout*: true when creating this notification.

## Expected behavior
IMO either this notification should be sticky (is visible until user chooses either CANCEL or OK) or we remove this parameter as it is misleading (no change in behavior).

## Steps to reproduce the issue
1. Go to https://demo.vuestorefront.io/
2. Add product to cart
3. Open micro cart
4. Click "Remove" link

## Repository
https://github.com/DivanteLtd/vue-storefront/blob/5d380d4278c0c1d4eecedc96ad40926525786d7f/core/compatibility/components/blocks/Microcart/Product.js#L32

## Can you handle fixing this bug by yourself?
YES

**Comment by pkarw** [comment]
Thanks! If You could fix this and prepare a PR - that will be awesome!
