### ISSUE TITLE
vsf-core as dependence

### ISSUE THREAD

**Issue by bratok** [DivanteLtd/vue-storefront#2308]
## What is the motivation for adding / enhancing this feature?

Now my custom theme, that implements custom business logic and UI, placed in src/themes. 
And root project folder has structure described [here](https://docs.vuestorefront.io/guide/basics/project-structure.html#using-git-for-custom-development). That is my project repository should contain all code with vcs-core. It looks redundant and increase volume of my repository.

Or  maybe i don't understand something to end?

I think the more convenient way is create template project with default folder structure and package.json without /core/* files, and move vsf-core as dependency in package.json

## What are the acceptance criteria 

- git clone "template project repo"
- yarn install
- yarn installer 

"yarn installer" must start instalation dialog   
After that  i dont have core/* files in project root folder.

## Additional information

For example, such an approach  used in projects based on  Symfony framework

**Comment by pkarw** [comment]
Thanks! We’ve got it on our roadmap! However now we’re  focused on Theme 2.0 which is priority for VS 2.0; we’ll try to have this boilerplate/npm dependency as well included in 2.c
