### ISSUE TITLE
Landing page - demo signup form

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#231]
This become a crucial task as we're getting to release the public demo starting 16th nov
We have to have Unbounce form there

**Comment by karolbzik** [comment]
@filrak when would you be able to work on the landing page? I will set a deadline for the design from my side based on your availability.

**Comment by karolbzik** [comment]
@filrak here you can find updated design of the landing page (I've added the visualization, screens in the design section, image for the technology section, a few changes in the footer) and the design for a pop-up with the demo signup form.

![landing page](https://user-images.githubusercontent.com/18116406/32691762-df5c32c0-c70c-11e7-8937-39e516fba13d.png)

<img width="1440" alt="landing page pop-up" src="https://user-images.githubusercontent.com/18116406/32691764-e3195ffa-c70c-11e7-916d-31689c90d934.png">

The design with all assests is available in the file from Figma.

The screen with the player in the top will contain the animated gif or video file, after clicking the player button it should run the annimation like here https://autopilothq.com/. 
Should I upload the video file to the Vimeo or YouTube?

**Comment by karolbzik** [comment]
@filrak we need to integrate the form in the pop-up with the HubSpot.
