### ISSUE TITLE
No possibility to add review

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2313]
## Current behavior
Lack of possibility to add review

## Expected behavior
There should be possibility to add new review

## Steps to reproduce the issue
1. Open any product page 
2. Scroll to Reviews section
3. Fill fields with correct data
4. Click on button **Add review**

See example:
![image](https://user-images.githubusercontent.com/47220013/52074700-c279fd80-258a-11e9-965d-32c3019437b6.png)

## Environment details
https://demo.storefrontcloud.io

**Comment by filrak** [comment]
@pkarw this is something I also noticed recently. Is it bd reviews are disabled in magento?

**Comment by ibugaj** [comment]
I don't know why, but for my issue still exist. 
I checked on some products and before I removed storage

**Comment by pkarw** [comment]
Could You please provide a SKU of problematic products?

**Comment by ibugaj** [comment]
Yes, sure, for example SKU: MJ12-XS-BLACK
I checked it one more time now and still problem is

**Comment by juliankoehn** [comment]
Are you on a local installation? Did you set the Reviews api path within your local config?

**Comment by ArturDivante** [comment]
There is still a problem with review form. Tried to add it for many diffrent products, on all instances (demo, next, test). List of example tested products SKU is below, but so far fail rate is at 100% :) 

WS01-XS-BLACK
MT10-XS-YELLOW
WS08-XL-RED
24-WG080
24-MG01

Tried as logged in user and logged out
Tried on desktop (Chrome, Edge, Firefox) and mobile (android chrome, iOS Safari)

Couldn't send a single review, every time the same error @ibugaj reported. 
![review error1](https://user-images.githubusercontent.com/47415585/54362499-54385880-4669-11e9-8380-f7d79c51a2a2.PNG)
![review error2](https://user-images.githubusercontent.com/47415585/54362512-58fd0c80-4669-11e9-952f-0ca8862eb038.PNG)
