### ISSUE TITLE
In Shipping section no validation for some fields.

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2317]
## Current behavior
In Shipping section no validation for some fields.
## Expected behavior
There should be right validation for fields, to user could enter correct data
## Steps to reproduce the issue
1. Add some product to the Cart
2. Go to checkout
3. Fill fields in Personal Details section
4. Click **Continue to shipping** button
5. Fill fields in Shipping section, but in fields: **Street name**, **City** provide numbers and in **Zip-code**, **Phone number** provide letters.
6. Click on **Continue to payment** button

## Environment details
https://demo.storefrontcloud.io

## Additional information
**Phone number** fields isn't mandatory, but I think that if user filled it, then should be validation for this field

**Comment by vue-kacper** [comment]
@pkarw I think we can close this one

**Comment by pkarw** [comment]
Thanks
