### ISSUE TITLE
[default] Problem with "about us" static page

### ISSUE THREAD

**Issue by vue-kacper** [DivanteLtd/vue-storefront#2320]
## Current behavior
We can enter empty "Aubout us" page from sidebar links but after refresh we get "We can't find the page"

![image](https://user-images.githubusercontent.com/42430550/52080900-2acfdb80-2599-11e9-9289-e6e7f2b97f7e.png)

## Expected behavior
"About us" page link sould render static page or it should be removed

## Steps to reproduce the issue
Visit: demo.storefrontcloud.io as a guest
Click on menu
Select "Track my order"
Click on "About us" sidebar link
Refresh page

**Comment by filrak** [comment]
Should be lack of proper link in static.vue

**Comment by lorenaramonda** [comment]
I'm gonna do this one! 🙋

**Comment by lorenaramonda** [comment]
PR here: https://github.com/DivanteLtd/vue-storefront/pull/2325
