### ISSUE TITLE
Using multiple filters combination on category page doesn't work

### ISSUE THREAD

**Issue by vue-kacper** [DivanteLtd/vue-storefront#2322]
## Current behavior

Using specific combination of filters on category page doesn't show proper results

## Expected behavior

Filter function should show proper results

## Steps to reproduce the issue

Visit URL: https://demo.storefrontcloud.io/c/tops-21

**Base state:**

![image](https://user-images.githubusercontent.com/42430550/52091686-92941f80-25b5-11e9-853c-a3d8d91556e4.png)

**Apply "Erin Recommends" "Yes" filter:**

![image](https://user-images.githubusercontent.com/42430550/52091729-b6effc00-25b5-11e9-84a3-147c3a5f2659.png)

**Now apply "Purple" color filter:**

![image](https://user-images.githubusercontent.com/42430550/52091788-e7379a80-25b5-11e9-8d6a-3d42f42d029e.png)

We should see on a results list at least "Breathe-Easy Tank" product because is both "Purple" and "Erin Recommends".

But instead we gets empty results list:

![image](https://user-images.githubusercontent.com/42430550/52091945-5f05c500-25b6-11e9-99e8-1b26573da0d9.png)

**Comment by jahnni** [comment]
we're trying this

**Comment by jorkvist** [comment]
What about this one? 
https://github.com/DivanteLtd/vue-storefront/pull/2180

**Comment by jorkvist** [comment]
@pkarw ok then the labels on this issue is wrong :D

**Comment by pstuifzand** [comment]
I did some digging and found that the "erin recommends" attribute is send to ElasticSearch as "erin_recommends_options". Removing the "_options" part from the string will return the right results.
I haven't been able to find where this name is added to the query.

**Comment by Zyles** [comment]
The filtering needs to be dynamic. Removing filters that are not applicable once you dig deeper.

Like first selecting "Jackets", and there are no green or yellow jackets, those colors need to be removed in the filter list until you uncheck "Jackets" again.

Otherwise users could select "Jackets" then click "yellow" and get 0 results.

**Comment by alinadivante** [comment]
@patzick please remember that only one option in Erin Recommends should be possible to choose
