### ISSUE TITLE
RWD - Fix the layout for category if there is < 3 products

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#233]
https://www.dropbox.com/s/r4ep060n6rstxx9/Zrzut%20ekranu%202017-11-04%2018.18.40.png?dl=0

**Comment by karolbzik** [comment]
@patrykpiston products should be aligned to the left.
![18](https://user-images.githubusercontent.com/18116406/32465247-1997d4f8-c343-11e7-9e94-049aafe91b42.png)
