### ISSUE TITLE
Lack of Clear button on Filters (desktop)

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2342]
## Current behavior
Lack of Clear button on Filters (desktop)

## Expected behavior
There should be Clear button 

## Steps to reproduce the issue
1. Go to any Category of products
2. Choose some attributes on Filter

![image](https://user-images.githubusercontent.com/47220013/52164692-9fb82800-26f5-11e9-947a-49819ecd1fd0.png)

## Environment details
https://demo.storefrontcloud.io

## Additional information
This button will be useful to easier changing user's choices

**Comment by DaanKouters** [comment]
@patzick i'll pick this issue

**Comment by pkarw** [comment]
@patzick the button works fine but it’s visible when you got back from PDP however none of the filters are applied - that’s misslewding and it’s probably connected with the Iga’s issue about the filters state - seems like we just need to execute an event to run the products query - currently it’s executed with base Filter instead

**Comment by ibugaj** [comment]
Yes, I confirmed what @pkarw wrote - Clear button is and works, but there is problem with stated filters.
I noticed, that problem is with Colors, not Sizes, because if user choose Size and go on any PDP, then go back on PLP, then products are filtered according with it.
