### ISSUE TITLE
Lack of possibility to change color or size, when product is in the Cart

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2346]
## Current behavior
Lack of possibility to change color or size, when product is in the Cart

## Expected behavior
User should has possibility to change color or/and size, when product is in the Cart

## Steps to reproduce the issue
1. Go to the Cart, when user has at least one product inside.
2. Click on Edit next to this product

**Comment by RakowskiPrzemyslaw** [comment]
@pkarw Im working on this

**Comment by idodidodi** [comment]
I am working on it.

**Comment by alinadivante** [comment]
I need small fix for this feature @andrzejewsky 😋 
After opening the edit mode and closing the cart (by clicking left side area) and reopening it - the edit mode is still open.
Can we close the editing mode by clicking outside the modal? :) 


![image](https://user-images.githubusercontent.com/36628922/61632931-52714800-ac8e-11e9-9269-7f98e378a77e.png)

**Comment by andrzejewsky** [comment]
@alinadivante sure, I'll add this fix in this PR: https://github.com/DivanteLtd/vue-storefront/pull/3261 because it seems to be quick.

**Comment by andrzejewsky** [comment]
The issue with closing edit mode in the cart mentioned by @alinadivante above was fixed in #3261
