### ISSUE TITLE
Track my orders page is available for not logged user

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2347]
## Current behavior
_Track my orders_ page is available for not logged user, it directed on https://demo.storefrontcloud.io/order-tracking

## Expected behavior
In my opinion this case should behave like _My account_ page so show notification "You need to be logged in to see this page"

## Steps to reproduce the issue
1. Be on Home page as not logged user
2. Click on _Track my orders_ (from Footer or hamburger menu)

## Environment details
https://demo.storefrontcloud.io/

**Comment by pkarw** [comment]
This is just a static page - I suggest removing the link from the footer.

**Comment by ibugaj** [comment]
Verified
