### ISSUE TITLE
Register new account permits on two-letter First name

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2348]
## Current behavior
Creating new account permits on two-letter First name, but on Checkout this field is valid, see:

![image](https://user-images.githubusercontent.com/47220013/52165449-32aa8f80-2701-11e9-9a68-d1583503d66e.png)

## Expected behavior
There shouldn't be discrepancies between the field on account creation and Checkout

## Steps to reproduce the issue
1. Go to Register an account
2. Fill obligatory fields, but in First name field provide only two letters
3. Finish creating account
4. Buy some product - go to checkout and see on Personal Detalis

## Environment details
https://demo.storefrontcloud.io

**Comment by pkarw** [comment]
Please check the Ajv JSON validation schema (which is placem in the vue-Storefront-api) if it nas the same length set for this field: 
https://github.com/DivanteLtd/vue-storefront-api/blob/develop/src/models/ -> `.schema.json`

**Comment by pkarw** [comment]
Please also do check the Order flow afterward (if server isn’t returning any avalidation error)

**Comment by ibugaj** [comment]
verified
