### ISSUE TITLE
Add "Thank you page" after order is sent to the server

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#235]
Do we have designs for that?

**Comment by karolbzik** [comment]
Under construction, however, it will be a very simple one, based on the design of static page:
![thank you page unfinished](https://user-images.githubusercontent.com/18116406/32465073-8df19d9e-c342-11e7-8656-89c9a710bb32.png)

**Comment by pkarw** [comment]
@filrak we have to have this thank you page after order is placed

**Comment by filrak** [comment]
For now there is a simple thank you page on checkout, @karolbzik if that's ok for now please close the issue
