### ISSUE TITLE
User address id can’t be of type string

### ISSUE THREAD

**Issue by ddomurad** [DivanteLtd/vue-storefront#2356]
## Current behavior
While developing EPiServer Commerce backend API for vue-storefront, I found out that VSF doesn't properly handles addresses, when the address.id field is of type string. 

Example GET /user/me?token=….:
RESPONSE:
```
{
	"code": 200,
	"result": {
		"addresses": [
			{
				"city": "Krakow",
				"country_id": "PL",
				"customer_id": "44",
				"default_shipping": true,
				"firstname": "FirstName",
				"id": "444", //<----  address id of type string 
				"lastname": "LastName",
				"postcode": "12-345",
				"region": {
					"region": "Malopolska"
				},
				"street": [
					"Test Street",
					"8"
				],
				"telephone": "111222333"
			}
		],
		"created_at": "Mon, 04 Feb 2019 09:27:05 GMT",
		"created_in": "Default Store View",
		"default_shipping": "444", //<----  address id of type string 
		"disable_auto_group_change": 0,
		"email": "test@test.com",
		"firstname": "TestName",
		"group_id": 1,
		"id": "44",
		"lastname": "TasetLastName",
		"store_id": "Test Store",
		"updated_at": "Mon, 04 Feb 2019 09:27:05 GMT",
		"website_id": 1
	}
}
```

Under Homepage/My Account/ My shipping details, no shipping information is visible:

Console output while opening shipping details:

> vue.runtime.esm.js:588 [Vue warn]: Error in render: "TypeError: Cannot read property 'firstName' of undefined"
> 
> found in
> 
> ---> <MyShippingDetails> at src/themes/default/components/core/blocks/MyAccount/MyShippingDetails.vue
>        <MyAccount> at src/themes/default/pages/MyAccount.vue
>          <DefaultLayout> at src/themes/default/layouts/Default.vue
>            <App> at src/themes/default/App.vue
>              <Root>
> warn @ vue.runtime.esm.js:588
> logError @ vue.runtime.esm.js:1732
> globalHandleError @ vue.runtime.esm.js:1727
> handleError @ vue.runtime.esm.js:1716
> Vue._render @ vue.runtime.esm.js:4534
> updateComponent @ vue.runtime.esm.js:2783
> get @ vue.runtime.esm.js:3137
> run @ vue.runtime.esm.js:3214
> flushSchedulerQueue @ vue.runtime.esm.js:2976
> (anonymous) @ vue.runtime.esm.js:1832
> flushCallbacks @ vue.runtime.esm.js:1753
> module.exports @ _invoke.js:5
> queue.(anonymous function) @ _task.js:35
> run @ _task.js:21
> listener @ _task.js:25
> 
> vue.runtime.esm.js:1736 TypeError: Cannot read property 'firstName' of undefined
>     at Proxy.render (MyShippingDetails.vue?./core/node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options:429)
>     at VueComponent.Vue._render (vue.runtime.esm.js:4532)
>     at VueComponent.updateComponent (vue.runtime.esm.js:2783)
>     at Watcher.get (vue.runtime.esm.js:3137)
>     at Watcher.run (vue.runtime.esm.js:3214)
>     at flushSchedulerQueue (vue.runtime.esm.js:2976)
>     at Array.eval (vue.runtime.esm.js:1832)
>     at flushCallbacks (vue.runtime.esm.js:1753)
>     at module.exports (_invoke.js:5)
>     at queue.(:3000/anonymous function) (webpack:///./node_modules/core-js/modules/_task.js?:35:7)
> logError @ vue.runtime.esm.js:1736
> globalHandleError @ vue.runtime.esm.js:1727
> handleError @ vue.runtime.esm.js:1716
> Vue._render @ vue.runtime.esm.js:4534
> updateComponent @ vue.runtime.esm.js:2783
> get @ vue.runtime.esm.js:3137
> run @ vue.runtime.esm.js:3214
> flushSchedulerQueue @ vue.runtime.esm.js:2976
> (anonymous) @ vue.runtime.esm.js:1832
> flushCallbacks @ vue.runtime.esm.js:1753
> module.exports @ _invoke.js:5
> queue.(anonymous function) @ _task.js:35
> run @ _task.js:21
> listener @ _task.js:25`

When the type of address.id is a number, the problem doesn't show up. 

## Expected behavior
Vue-Storefront should accept address.id field to be of type string.

**Comment by pkarw** [comment]
Done with https://github.com/DivanteLtd/vue-storefront/issues/2356
