### ISSUE TITLE
Cutted Country name on Checkout

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2361]
## Current behavior
Cutted Country name
![image](https://user-images.githubusercontent.com/47220013/52220534-60c5d600-289f-11e9-82d7-7890eb113c69.png)

## Expected behavior
Country field should be properly visable. 

## Steps to reproduce the issue
1. Add some product to the Cart
2. Go to checkout
3. Fill fields for sections 1. Persolnal Detalis and 2. Shipping with correct data
and fill also Payment section
4. See on Contry field (when it is filled) 

## Environment details
https://test.storefrontcloud.io/

**Comment by pkarw** [comment]
It’s kind of general issue with combo fields 
![77f340a9-7af1-4c0f-8459-170ea4955047](https://user-images.githubusercontent.com/211899/52230139-f28d0d80-28b6-11e9-9907-7fa4e200d85b.png)

**Comment by ibugaj** [comment]
Verified
