### ISSUE TITLE
Depreciate asyncDataLoader

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#2362]
## What is the motivation for adding / enhancing this feature?

With new addition to Vue 2.6 it's no longer needed
![image](https://user-images.githubusercontent.com/15185752/52221645-e3e82b80-28a1-11e9-86b0-4c6606168e2b.png)
https://ssr.vuejs.org/api/#serverprefetch

**Comment by pkarw** [comment]
Wow! Awesome, finally!
Are we updating to 2.6 right away? With the 1.8 release?

I won’t depreciate it anyway as it has some more features. However, for this particular case / true, it makes no sense to use it :-)

**Comment by filrak** [comment]
Imho we should depreciate it and introduce a new feature to Hook i to Express (using same feature as right now with server routes) to not mix conventions.
@patzick wdyt?

**Comment by filrak** [comment]
And Yes we should update with 1.8.its 100% backward compatible

**Comment by pkarw** [comment]
Ok please do update Vue; I’ll add deprecation notice to the module

**Comment by patzick** [comment]
Guys, we haven't released that feature yet. Shouldn't we just remove this instead of releasing new deprecated module if we're sure that we don't want it? :)

**Comment by pkarw** [comment]
I want it :)

**Comment by patzick** [comment]
okaay, i clearly misunderstood your discussion ;)
