### ISSUE TITLE
My account menu for logged user should curl up after click on any position

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2363]
## What is the motivation for adding / enhancing this feature?
I think that it will more comfortable for user, when he developed **My account menu** (in right top corner) and chose any option, for example **My newsletter**, then he should be redirected on this page (it works properly) but menu should curl up.

![image](https://user-images.githubusercontent.com/47220013/52234344-b57a4880-28c1-11e9-9aaa-ace4cdca54fe.png)

## What are the acceptance criteria 
My account menu (for logged user)  should will curl up, when user click on any position in this menu.

## Additional information
It works like that for example for Facebook ;)

**Comment by pkarw** [comment]
It was just like that till 1.6 :)

**Comment by ibugaj** [comment]
verified
