### ISSUE TITLE
Lack of Compare feature on Mobile

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2370]
## Current behavior
Lack of Compare feature on Mobile

## Expected behavior
Compare feature on Mobile

## Steps to reproduce the issue
1. Go on any product page on Mobile
2. Click **Add to compare**

## Environment details
https://test.storefrontcloud.io/

**Comment by pkarw** [comment]
We can skip Compare on Mobile at all - it makes no sense to have it there

**Comment by ibugaj** [comment]
OK, cool, I was not sure;)
