### ISSUE TITLE
Add Nosto support

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2380]
## What is the motivation for adding / enhancing this feature?

Add Nosto Product recommendations support thru their JavaScript API: 
https://developer.nosto.com/

## What are the acceptance criteria 

- `NostoRecommendations` component added as a VS Module
- `NostoRecommendations` component used on Category and Product page

**Comment by pkarw** [comment]
Info from Nosto folks (let me know if You'd like to be connected):

> In terms of Vue Storefront, we have discussed this internally and it seems that with our GraphQL setup we can implement with quite a little friction anyway. Here are our docs - https://github.com/Nosto/techdocs/wiki/VueJS
> 
> . You can access a Nosto dev/sandbox account by following the link you have been sent. Select the "test/dev" account option when prompted and you will be able to play around with Nosto linked to a test side.
> 
> If you need an API key, you can request one via the chat support in the Nosto dashboard. Just mention you are testing PWA and would like access to GraphQL :D
> 
> Please let me know if you have any questions, if we have a customer in mind we can certainly organise a call around the scope of the project as well.
>

**Comment by janmyszkier** [comment]
this is connected to #363 (and possibly a duplicate)
