### ISSUE TITLE
Add Klarna Checkout

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2382]
## What is the motivation for adding / enhancing this feature?

Add the Klarna Checkout API integration:
https://developers.klarna.com/api/

## What are the acceptance criteria 

- Klarna Checkout integrated similarily like Payment Request API - #2184 
- ...

**Comment by gabwik** [comment]
Kodbruket will start doing this.

**Comment by Decntdefalt** [comment]
Any updates on this? Waiting like it's Christmas here!

**Comment by gabwik** [comment]
It is going well. Hope it will be a beta in the end of the week.

**Comment by cnviradiya** [comment]
@gabwik 
May I know when Klarna Checkout will be available?
Because we have already made its initial stage.

**Comment by gabwik** [comment]
@cnviradiya It will be released tomorrow on the Hackathon in Stockholm.

**Comment by cnviradiya** [comment]
@gabwik 
Okay, Thank you

**Comment by gabwik** [comment]
https://github.com/kodbruket/vsf-payment-klarna

@cnviradiya and @Decntdefalt

**Comment by LogimaeCommerce** [comment]
> https://github.com/kodbruket/vsf-payment-klarna
> 
> @cnviradiya and @Decntdefalt

Great job! This is a game changer for a lot of Scandinavian clients :)

**Comment by Decntdefalt** [comment]
> https://github.com/kodbruket/vsf-payment-klarna
> 
> @cnviradiya and @Decntdefalt

Great job! This is a game changer for a lot of Scandinavian clients :)
