### ISSUE TITLE
New case with two-letter First name

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2389]
## Current behavior
When logged user check **Use my billing dat**a in **Payment** section in Checkout, then there is validation on two letters in First Name field, although it is filled with 2 letters.

![image](https://user-images.githubusercontent.com/47220013/52430696-fadb8780-2b06-11e9-86e2-eb80790c3d8a.png)

## Expected behavior
There shouldn't be discrepancies between Name fields on Checkout

## Steps to reproduce the issue
* Be a logged user
* Add some product to the Cart
* Go to checkout
* Fill fields for sections 1. Persolnal Detalis and 2. Shipping with correct data
* Go to Payment section and check checbox **Use my billing dat**a 
* Fill First Name field with 2 letters

## Environment details
https://test.storefrontcloud.io/

**Comment by ananth-iyer** [comment]
@patzick I have fixed the issue in https://github.com/DivanteLtd/vue-storefront/pull/2403 PR

**Comment by ibugaj** [comment]
verified
