### ISSUE TITLE
Name of Country field on Checkout is shifted to the right side.

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2390]
## Current behavior
Name of Country field on Checkout is shifted to the right side.

![image](https://user-images.githubusercontent.com/47220013/52432633-37a97d80-2b0b-11e9-84ac-ba1ee0f8dd07.png)

## Expected behavior
Name of Country field  should be shifted to the left side, like it is on Chrome browser:

![image](https://user-images.githubusercontent.com/47220013/52433303-121d7380-2b0d-11e9-8a72-0ed89ae362c5.png)

## Steps to reproduce the issue

* Add some product to the Cart
* Go to checkout
* See on Country fields (in Shipping and Payment section)

## Environment details
Mozilla Firefox Version 64.0.2    /    Microsoft Edge
https://test.storefrontcloud.io/

## Additional information
**Issue is on Mozilla browser and Microsoft Edge**, and it is alike for logged user as not logged, and alike for filled and empty Country field.

**Comment by ananth-iyer** [comment]
@pkarw @ibugaj I am working on this issue.

**Comment by ananth-iyer** [comment]
https://github.com/DivanteLtd/vue-storefront/pull/2402 PR will fix the label issue on Checkout page also. `<BaseSelect>` component is being used for Country field.

**Comment by patzick** [comment]
@ananth-iyer thanks!

**Comment by ananth-iyer** [comment]
@patzick Should I change under [1.9.0] in develop branch?

**Comment by ibugaj** [comment]
verified
