### ISSUE TITLE
Add Typescript support for VS modules installed with Yarn/NPM 

### ISSUE THREAD

**Issue by Tjitse-E** [DivanteLtd/vue-storefront#2395]
## What is the motivation for adding / enhancing this feature?
We've just ported the external checkout from Filip to a [VS module](https://github.com/Vendic/vsf-external-checkout). But I noticed that installing the module with yarn isn't working, because of the Typescript files included in the module, or a missing configuration file in the module. Anyway, these modules are currently not bundled correctly by Webpack.

## What are the acceptance criteria 
- VS should compile VS modules (with prefix `vsf-*`) that are installed with Yarn/NPM and contain Typescript.
- If extra module configuration is needed, add it to  `src/modules/module-template`

# Can you complete this feature request by yourself?
No

### Extra info
- Tested on VueStorefront 1.8

**Comment by pkarw** [comment]
Maybe we should add the TS support to all `vsf-*` named modules?

**Comment by Tjitse-E** [comment]
@pkarw even better. I'll add it to the feature request

**Comment by pkarw** [comment]
@patzick can You check this one as well?
