### ISSUE TITLE
No quantity up/down buttons in product page and cart - Edge

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2398]
## Current behavior
Quantity field does not have up and down buttons **in Edge browser**. You can still increase and decrease quantity by clicking the field and using up/down arrow keys or numbers. 

## Expected behavior
After moving mouse button over quantity field (on product page) or after clicking edit button (in cart), up and down buttons should appear and alow to set desired quantity by clicking them. 

## Steps to reproduce the issue
**Scenario 1 (product page):**
1. Open https://demo.storefrontcloud.io or https://test.storefrontcloud.io on **Edge browser**
2. Open any product page
3. Move mouse cursor over quantity field
![productpage](https://user-images.githubusercontent.com/47415585/52476907-7b01fb80-2ba0-11e9-8a65-525f2c16ff8f.PNG)

**Scenario 2 (cart):**
1. Open https://demo.storefrontcloud.io or https://test.storefrontcloud.io on **Edge browser**
2. Add any product to the cart 
3. Open cart
4. Click edit button next to the product
![cartpage](https://user-images.githubusercontent.com/47415585/52476922-86552700-2ba0-11e9-8dde-76a9a593b128.PNG)

# Can you handle fixing this bug by yourself?
NO.

## Environment details
- https://test.storefrontcloud.io, https://demo.storefrontcloud.io
- **Browser: Edge 17, Edge 18 (18 via browserstack)**
- OS: Win10

**Comment by pkarw** [comment]
@patzick please do close this one if is it ready (I think it is :))

**Comment by patzick** [comment]
Yes, it is:)

**Comment by ibugaj** [comment]
@pkarw @patzick @ArturDivante  I already reproduced this bug on Microsoft Edge HTML 17.17134

**Comment by patzick** [comment]
@ibugaj @ArturDivante @pkarw 
Guys, i'm not sure we should change that in this case. It's the internal Edge behavior that numeric fields don't support spinner controls.
There is an issue for that: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6762219/ and they are not in hurry to change that, but i think if someone is using Edge, then is used to have numeric fields without spinners.

Please share your opinion, but if we decide to change that field i think this should be as feature request in next versions than bug.

**Comment by pkarw** [comment]
I think we can ignore this one for now - it's a minor issure related only to Edge

**Comment by ibugaj** [comment]
I also think that it doesn't matter, especially that this browser is not so popular;)
