### ISSUE TITLE
Country* field name is missplaced in shipping details - Edge 17 and Firefox

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2399]
## Current behavior
Country* field description is displayed next to the dropdown list

## Expected behavior
Country* field description should be displayed above the dropdown list

## Steps to reproduce the issue
1. Create account and login
2. Go to my account > My shipping details
3. Click 'Edit your shipping details'
![country1](https://user-images.githubusercontent.com/47415585/52479860-51e66880-2baa-11e9-8b70-02879b3f23f1.png)

Same problem appears in this form during order placement: 
![country](https://user-images.githubusercontent.com/47415585/52479859-514dd200-2baa-11e9-8cff-15ef4fdf6ca3.png)

## Can you handle fixing this bug by yourself?
no

## Environment details
- Browser: Edge 17, Firefox 65
- OS: Win10

#Additional informations:
Chrome, Opera and Edge 18 seem to display it correctly

**Comment by ananth-iyer** [comment]
@pkarw I am working on this issue.

**Comment by patzick** [comment]
Closed by work of @ananth-iyer, thanks!
