### ISSUE TITLE
In Magento order placed twice most of the time

### ISSUE THREAD

**Issue by anantsunny** [DivanteLtd/vue-storefront#2405]
## Current behavior
Order is placed twice in Magento for most of the orders in production. But it is working fine in local environment. 

## Steps to reproduce the issue
Add any product to cart.
Place order as guest user.
Order placed is successful.
I can see same order twice in my magento admin.

## Environment details

- Browser: Chorome
- OS: Windows , Andriod
- Node: 8.11

**Comment by pkarw** [comment]
Please provide us with more details: VS version, dev tools network console trace + please check if you can reproduce this issue on demo.storefrontcloud.io

**Comment by pkarw** [comment]
OK! I've found and fix the error: https://github.com/DivanteLtd/vue-storefront/releases/tag/v1.8.1

Please retest

**Comment by anantsunny** [comment]
Thank you. Its working fine now
