### ISSUE TITLE
Add method to check if module is already registered

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2406]
## What is the motivation for adding / enhancing this feature?

We don't have a public method in `VueStorefrontModule` interface to check if the module has been already registered + list the registered modules.

It could be useful. For example, I wanted to check in `payment-backend-methods` if the ``payment-cash-on-delivery` has been registered and there was no way to do so

**Comment by filrak** [comment]
it's alreadya dded

**Comment by pkarw** [comment]
Where? :)

**Comment by filrak** [comment]
https://github.com/DivanteLtd/vue-storefront/blob/master/core/lib/module.ts#L54

**Comment by filrak** [comment]
also https://github.com/DivanteLtd/vue-storefront/blob/master/core/lib/module.ts#L40

**Comment by pkarw** [comment]
This is private

**Comment by filrak** [comment]
You're right. It was meant for internal use to avoid dependencys over modules but it can easly be moved outside and exported. 

Will do it along with factory method refactor ok?

**Comment by pkarw** [comment]
Perfect!
