### ISSUE TITLE
Adjust the lazy loading

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#241]
First 6-9 images should be pre-loaded so: not add vue-lazyload to them OR adjust the timespan if it's possible

I mean - on Category page

**Comment by patrykpiston** [comment]
No problem, we can load the first 6 or so images as usual, the rest will be
lazy loaded. I'm on it

**Comment by karolbzik** [comment]
@patrykpiston @pkarw are not visible slides also lazy loaded?
