### ISSUE TITLE
Wrong color for picture of product

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2419]
## Current behavior
Wrong color for picture of product

![image](https://user-images.githubusercontent.com/47220013/52577238-f45c5100-2e21-11e9-8f4b-3447915f9f84.png)

## Expected behavior
Right color of product on picture.

## Steps to reproduce the issue
1. Go to any category of products
2. Choose any color in Filters, for example green
3. Click on any product to open its PDP

## Environment details
https://test.storefrontcloud.io/

## Additional information
This issue is reproducible not in every case. I found it for product with SKU: WH11-XS-Green 
Futhermore: when I open dev console then color is changed on different and when I closed it, then it back for last color.
WHAT ELSE: when user choose some color on filter, open any PDP, then back to PLP and choose again the same color on filter, then products on page are reload, but color isn't changed for them - user must click again on this color in filter to change it.

**Comment by DaanKouters** [comment]
@patzick i'll take a look at this

**Comment by ibugaj** [comment]
Verified and main issue is solved, but there is still problem, when user choose any color on filter, next open any PDP, then back to PLP and choose again **the same** color on filter, then products on page are reload, but color isn't changed for them - user must click again on this color in filter to change it.

**Comment by DaanKouters** [comment]
Ah, i see what you mean. But i'm positive this is another issue and not related with this original issue.
But of course i leave this decision to Vue Storefront core team members.

**Comment by ibugaj** [comment]
So should I open new issue for this?:)

**Comment by pkarw** [comment]
@ibugaj do open a new one, please
