### ISSUE TITLE
Add product and content carousel

### ISSUE THREAD

**Issue by StefGeraets** [DivanteLtd/vue-storefront#2420]
## What is the motivation for adding / enhancing this feature?
Replacing vue-carousel. It was removed in 1.7 because it didn't work with ssr.

## What are the acceptance criteria 
- Has to work with SSR
- Needs to support product cards as content
- Optional as product photo gallery

# Can you complete this feature request by yourself?
Gonna try, not sure at this point

**Comment by filrak** [comment]
The reason was bc it was bad to performance. If we want to introduce a carousel it should probably be out own minimal mechanism
