### ISSUE TITLE
Country field is filled by first counry from the list

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2428]
## Current behavior
Country field is filled by first counry from the list and cover placeholder - on Payment section, when user uncheck checkbox to copy data

![image](https://user-images.githubusercontent.com/47220013/52652661-d872b100-2eee-11e9-9105-e3637f36a1b7.png)

## Expected behavior
Country field should be empty
## Steps to reproduce the issue
* Add some product to the Cart
* Go to checkout
* Fill fields in **Personal details** and **Shipping** sections
* Go to **Payment** section:
when fields in this section are empty then check _Copy address data from shipping_ or _Use my billing data_ (it is for looged user) and then uncheck it

## Environment details
https://test.storefrontcloud.io/
## Additional information
This issue is for unlogged and also for logged users

**Comment by RakowskiPrzemyslaw** [comment]
@pkarw Im working on this

**Comment by patzick** [comment]
Closed by #2430

**Comment by ibugaj** [comment]
I verfied this issue and it is still. I cleaned storage data, but problem still occurs

**Comment by patzick** [comment]
that's because this has not been deployed yet
so I think also about #2439
