### ISSUE TITLE
Inverted filtering results on category pages

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2435]
## Current behavior
Filter marked as ON has no effect
Filter marked as OFF is applied to displayed results

## Expected behavior
Filters should be marked as ON and work at the same time

## Steps to reproduce the issue
1. Go to https://test.storefrontcloud.io/
2. Open any category page
3. Pick a filter (i.e. color) and leave it marked
4. Go to any other page (i.e. Home Page)
5. Go back to the same category page
6. Click the same filter you just used

Filter OFF:
![filteroff](https://user-images.githubusercontent.com/47415585/52793233-92902700-306d-11e9-8ac9-4f8bfefe13e7.PNG)
Filter ON:
![filteron](https://user-images.githubusercontent.com/47415585/52793234-9328bd80-306d-11e9-8b05-ceb51ca1a925.PNG)

## Can you handle fixing this bug by yourself?
no

## Environment details

- Browser: Chrome, Firefox, Opera, Edge
- OS: Win10

## Additional information
Same behavior for sure applies to price filter, and proopably to other filters as well

**Comment by pkarw** [comment]
@patzick this is the issue with filters I’ve mentioned elsewhere
