### ISSUE TITLE
User can add to cart 0 qty product

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2437]
## Current behavior
User can add to cart 0 qty product (with price 0), has noification 'Product has been added to the cart!" - but in Cart 1 product appears

![image](https://user-images.githubusercontent.com/47220013/52811574-ba938080-3095-11e9-9c32-78df408c654c.png)

## Expected behavior
There should be no possibility to change qty of product on 0.
## Steps to reproduce the issue
1. Open any Catalog page
2. Click on any product
3. On product page change qty on 0
4. Click Add to cart
5. Go to Cart

## Environment details
https://test.storefrontcloud.io/

## Additional information
I checked that user can also fill Qty field by negative number (after that the price displayed as negative.)
Issue also on mobile.

**Comment by RakowskiPrzemyslaw** [comment]
@ibugaj I'll take care of that

**Comment by ibugaj** [comment]
Tested - Issue solved. For now even if user try to fill qty manually, then he get notification "_Quantity must be above 0_" - thanks for this solution :)
@patzick It will be good add it also on Cart, because when user open cart and try to change qty manually then there isn't notification "_Quantity must be above 0_" and user can left 0 or for example -2 in qty field (but the price works like for one product, and if user go to checkout then system will correct quantity on 1)
In Cart:
![image](https://user-images.githubusercontent.com/47220013/53431914-d4b45380-39f1-11e9-9ef2-09e91a603a03.png)
In PDP:
![image](https://user-images.githubusercontent.com/47220013/53431998-f7df0300-39f1-11e9-8e60-59244319aed9.png)
