### ISSUE TITLE
Cannot edit previous steps in checkout

### ISSUE THREAD

**Issue by smorincaron** [DivanteLtd/vue-storefront#2438]
## Current behavior
First two steps might result in not being editable when going back and forth in steps
![capture d ecran 2019-02-14 a 15 46 19](https://user-images.githubusercontent.com/7874374/52816652-b8b6c680-306f-11e9-8d8c-52657a5ff7d2.png)

## Expected behavior
We should still be able to edit the previous steps

## Steps to reproduce the issue
1. Add product to cart and proceed to checkout page
2. Fill first and second step (even third if you want to bug second step as well)
3. From step 3, Click on "Edit personal details"
4. Click on "Edit shipping"

The first step is no longer available for edit.

## Repository
Related to isFilled variable
https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/checkout/components/PersonalDetails.ts

## Can you handle fixing this bug by yourself?
NO

## Environment details
- Browser: Chrome Version 72
- OS: Mac OS 
- Reproduced on https://demo.storefrontcloud.io/checkout

## Additional information
Related to isFilled variable
https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/checkout/components/PersonalDetails.ts
The value isFilled only changed on step edit or next step button.
Should be changed to ensure if edit is clicked on another step, the edited step should be completed or we need to save the step before editing a new one.

**Comment by filrak** [comment]
I'll take care of this one

**Comment by ArturDivante** [comment]
Bug was fixed for step 1. But I am still able to recreate bug for step 2:

Steps to reproduce:
1. Add product to cart and proceed to checkout page
2. Fill first, second and third step. 
3. From step 4, click "Edit Shipping"
4. Click "Edit Payment" 

Step 2 is grayed and impossible to edit directly.
![step2bugged](https://user-images.githubusercontent.com/47415585/53489921-9c188680-3a92-11e9-86bf-eeb5982a1553.PNG)

Problem can be bypassed by going back  to step one and continue from there, but still it should be posiible to navigate between steps freely.

**Comment by patzick** [comment]
im leaving `need confirmation` label, but this should be tested after merging #2511

**Comment by patzick** [comment]
Merged and deployed - ready for tests
