### ISSUE TITLE
Version number and build date on site

### ISSUE THREAD

**Issue by patzick** [DivanteLtd/vue-storefront#2439]
We should add somewhere on site version number and build date, to let everyone (especially testers) to know which version they are using.
That will prevent from testing not deployed yet features.

**Comment by patzick** [comment]
We have to remember to change it also here.
https://github.com/DivanteLtd/vue-storefront/blob/8978d68f8ea0303207cca58750e06ad120a8138f/core/app.ts#L68

**Comment by pkarw** [comment]
Lerna is updating package.json with curent version number when publishing to npm - I believe we should take it from there

**Comment by patzick** [comment]
yes, exactly version should be from package.json
also build date is very useful for final testing issues on develop, because there is no version change then
