### ISSUE TITLE
Cannot add 3rd party plugins to theme

### ISSUE THREAD

**Issue by praneethmendu** [DivanteLtd/vue-storefront#2440]
## Current behavior

According to the documentation to import 3rd party themes I have to register it in /src/themes/default/plugins/index.js , which I have tried to do 

```
import Vue from 'vue';
import Toasted from 'vue-toasted';
// import other plugins

Vue.use(Toasted);
// other plugins
```
But when I am trying to access it in src/themes/default/pages/Product.vue using 
```
  mounted () {
    Vue.toasted.show('hola billo');
  }
```
it throws
```
vue.runtime.esm.js:588 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'show' of undefined"

found in

---> <Product> at src/themes/default/pages/Product.vue
       <DefaultLayout> at src/themes/default/layouts/Default.vue
         <App> at src/themes/default/App.vue
           <Root>
```

I have had the same experience with other plugins I have tried namely 
## Expected behavior

the plugin should be registered
## Steps to reproduce the issue

install any plugin and add the above code

# Can you handle fixing this bug by yourself?

No

## Environment details

- Browser: Chrome Version 72.0.3626.109
- OS: ubuntu 18.10 (tried on win 10 too)
- Node: 10.15.1

## Additional information
I noticed that there was no plugin folder in theme but there is one in compatibility so maybe this is a deprecated way, Id love to change the documentation to reflect the changes in that case.

**Comment by filrak** [comment]
Hey, the docs should be more strict about this, I'll make an issue and adjust them.
I already answered you on stackoverflow but you already did it right ( `theme/index.js` ) The missing part is just checking if the plugin is registered only on client side since it highly relies on `window` object
