### ISSUE TITLE
Links in footer to static pages bug

### ISSUE THREAD

**Issue by jorkvist** [DivanteLtd/vue-storefront#2452]
## Current behavior
Its a bit hard to test on demo.vuestorefront due to same content on a lot of the static pages. But i see this behavior on my local, when i click on a link in the footer to a static page: As a visitor i see the new page, but if Im already is on a static page, the footer links is not updating anything else then the heading of the page. However, the left menu under the static pages is working as intended. 

## Expected behavior
The visitor should see the correct static page, even if they are on a static page. 

## Environment details
- Browser: Chrome latest

**Comment by filrak** [comment]
the truth is we only have one static page and all of them are linking to this one, this is why you don't see any change. Not sure if we should add other pages @pkarw

**Comment by pkarw** [comment]
This is the second bug report for the same thing so the answer is: yes we should take care of that once and for all

**Comment by jorkvist** [comment]
@filrak yes, but when i have different content it still shows the same page(/loaded content)from the links from the footer when i already standing on a static page. It just updates the {{ page.title }} but not the activeComponent (<component :is="activeComponent" />).

**Comment by gabrielecontitaguali** [comment]
@jorkvist you can try something like this adding a watch on route change

`import { currentStoreView } from '@vue-storefront/core/lib/multistore'  
watch: {
    '$route.name': function () {
      this.activeComponent = this.navigation.find(nav => nav.link === this.$route.path) ? this.navigation.find(nav => nav.link === this.$route.path).component : null
    }
  },`

**Comment by filrak** [comment]
already on it
