### ISSUE TITLE
api/order return 500 "ch.charCodeAt is not a function"

### ISSUE THREAD

**Issue by gabrielecontitaguali** [DivanteLtd/vue-storefront#2453]
## Current behavior
When placing an order the order is not placed an notification reports "THE ORDER CAN NOT BE TRANSFERED BECAUSE OF SERVER ERROR. ORDER HAS BEEN QUEUED"

## Expected behavior
Order should be placed and success notification

## Steps to reproduce the issue
-add product to cart
-go to checkout
- fill details
-choose cash on delivery
-submit order

## Repository

# Can you handle fixing this bug by yourself?
No

## Environment details

- Browser: All
- OS: Ubuntu 18.04
- Node: 8.12

## Additional information

it seems like the vue-18n is causing issue 

>  Uncaught (in promise) TypeError: ch.charCodeAt is not a function
    at getPathCharType (vue-i18n.esm.js:732)
    at parse$1 (vue-i18n.esm.js:848)
    at I18nPath.parsePath (vue-i18n.esm.js:888)
    at I18nPath.getPathValue (vue-i18n.esm.js:902)
    at VueI18n._interpolate (vue-i18n.esm.js:1096)
    at VueI18n._translate (vue-i18n.esm.js:1226)
    at VueI18n._t (vue-i18n.esm.js:1250)
    at VueI18n.t (vue-i18n.esm.js:1271)
    at eval (task.ts:145)

**Comment by pkarw** [comment]
Please do check us with the `vue-storefront-api` console output for these issues

**Comment by gabrielecontitaguali** [comment]
Hi Piotr, we can close this issue. The problem was related to my custom magento 2 payment module.

I could find error in magento/var/report/api folder and once the magento module was fixed the order api started working again. 
Strange behavior of vs-api though...

**Comment by pkarw** [comment]
OK, thanks!
