### ISSUE TITLE
Remove AsyncDataloader

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#2455]
## What is the motivation for adding / enhancing this feature?

We should use native serverPrefetch

## What are the acceptance criteria 

- ...
- ...

# Can you complete this feature request by yourself?

**Comment by pkarw** [comment]
I don't agree that we should remove it at all. This is pretty useful module not only for the asyncData replacement.

However - I agree that we should use `serverPrefetch` wherever we can

**Comment by pkarw** [comment]
I'm moving this one to waiting list
