### ISSUE TITLE
adjustment width of box for options in Erin Recommends

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2458]
## Current behavior
I suggest to change width of box with word "No" on the same like for "Yes" in section Erin Recommends on Filters.
In me feeling, it isn't look good with this difference, see:
![image](https://user-images.githubusercontent.com/47220013/53044996-cf548780-348c-11e9-9966-a790d3d43141.png)

## Expected behavior
Better look for Erin Recommends section

## Steps to reproduce the issue
1. Open any PLP page
2. See on Filters

## Environment details
https://test.storefrontcloud.io

**Comment by pkarw** [comment]
I think  that we should rather display these type of "Tag-a-like" filters without the line break. The options are text so we never know the width that fits all the options. But keeping them one after another we'll get better looking effect for sure

**Comment by patzick** [comment]
with this issue there are there are two more UI improvements to test:

1. To large quantity input on mobile view
![image](https://user-images.githubusercontent.com/13100280/53695137-178e7680-3db8-11e9-86e8-8232d35382ad.png)


2. bad margin on product tile with smaller resolutions
![image](https://user-images.githubusercontent.com/13100280/53695134-0ba2b480-3db8-11e9-9fbd-a9eaadf556b4.png)

this is resolved in second PR - #2531
