### ISSUE TITLE
Unified SSR checking way

### ISSUE THREAD

**Issue by lukeromanowicz** [DivanteLtd/vue-storefront#2468]
## What is the motivation for adding / enhancing this feature?
Currently, we are using multiple ways of checking if the code is running in SSR including:
* `isServer` in  `@vue-storefront/core/helpers`
* `typeof window === 'undefined'`
* `Vue.prototype.$isServer`
* Passing though parameters i.e. in server registration 
and possibly others.

I suggest to use `isServer` from `@vue-storefront/core/helpers` as the only way to check the environment type as it is the easiest way to mock in tests and allows us to add some enhancements in the future if needed.

## What are the acceptance criteria 
- everywhere in the code we are using `isServer` in `@vue-storefront/core/helpers` as the way to check if the runtime environment is `server` or not
- isServer in module registration hooks is deprecated and shall throw logger.warn when reading its value. Should be removed in a couple of versions as redundant.

# Can you complete this feature request by yourself?
Yes

**Comment by vue-kacper** [comment]
I agree

**Comment by pkarw** [comment]
Fixed in my PR: https://github.com/DivanteLtd/vue-storefront/pull/2446

I need to change some other minor things and it will be ready the next week
