### ISSUE TITLE
Color of the filtered products doesn't complies with the imposed

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2471]
## Current behavior
When user choose any color on filter, next open any PDP, then back to PLP and choose again **the same** color on filter, then products on page are reload, but color isn't changed for them - user must click again on this color in filter to change it.
## Expected behavior
Color of the filtered products complies with the imposed.

## Steps to reproduce the issue
* Go to any category of products
* Choose any color in Filters, for example green
* Click on any product to open its PDP
* Back to PLP and choose again **the same** color on filter

## Environment details
https://test.storefrontcloud.io/

**Comment by pkarw** [comment]
I've got the same - the state of filters is kept between PDP and PLP but the filters are not applied properly

**Comment by ibugaj** [comment]
Verified fix
