### ISSUE TITLE
Incompatible product description with a picture

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2473]
## Current behavior
When user scroll to next pictures then see product in the rest of available colors, but in description there is still name of first color, what can confuse user
## Expected behavior
Product description (color) should be compatible with a picture.
## Steps to reproduce the issue
* Open any PDP
* Click on arrow on main picture to see next picture

## Environment details
https://test.storefrontcloud.io

## Additional information
I'm not sure if it is properly behavior, but for me it is not good when user see picture of product in one color and description in another.

**Comment by ibugaj** [comment]
![gallery](https://user-images.githubusercontent.com/47220013/53119134-0ab78a80-354f-11e9-8f45-afe12e9e5c3d.gif)

**Comment by vue-kacper** [comment]
I think this is intentional. Photo gallery (carousel) is configurable, so we can choose to combine all photos from different configurable products or to show only color-specific ones per configurable product.

I don't think swiping photos should be responsible for switching configurable options.

**Comment by ibugaj** [comment]
OK,sure,  I understand

**Comment by patzick** [comment]
i agree with @vue-kacper - only directly changed product options should do that
