### ISSUE TITLE
Extend modules interface with `afterInitialState`

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2487]
## What is the motivation for adding / enhancing this feature?

Currently, there is no way to access the `__INITIAL_STATE__` from the module hooks. Module hooks are executed by `app.ts` - before the `client-entry.ts` runs the `replaceState`. Therefore if there is any logic in the module dependent on __INITIAL_STATE__ You just can't rely on it

Because of that, I've had to put the `url/registerDynamicRoutes` call into client-entry.ts -> https://github.com/pkarw/vue-storefront/blob/92bb3da17aa88e6d79474ae1849f37c2659be6ea/core/client-entry.ts#L29

I'd really prefer to not add event bus event for this case :D

## What are the acceptance criteria 

- To show the best way to use __INITIAL_STATE__ from the module level as soon as its' available

**Comment by pkarw** [comment]
Modules maybe should be just registered after initial state is available - in that case we won't need any additional hook

**Comment by filrak** [comment]
Yeah they can be safely registered later

**Comment by pkarw** [comment]
Could You then just try to move it for later?
