### ISSUE TITLE
[docs] Missing links for basics/configuration

### ISSUE THREAD

**Issue by daksamit** [DivanteLtd/vue-storefront#2490]
## Current behavior
Following links are redirect to 404 under [documentation](https://docs.vuestorefront.io/guide/basics/configuration.html) - 'Configuration file explained'.
1. [catalog](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/GraphQL%20Action%20Plan.md) - 'GraphQL' section
2. [core/store/lib/multistore.ts](https://github.com/DivanteLtd/vue-storefront/blob/master/core/store/lib/multistore.ts) - 'Default store code' section
3. The same for [core/store/lib/multistore.ts](https://github.com/DivanteLtd/vue-storefront/blob/master/core/store/lib/multistore.ts) and [core/store/lib/taxcalc.ts](https://github.com/DivanteLtd/vue-storefront/blob/master/core/store/lib/taxcalc.ts) - 'Store views' sections
4. All links at 'Entities', 'Cart', 'Products' sections are incorrect.
5. And again 'Taxes' for [core/store/lib/taxcalc.ts](https://github.com/DivanteLtd/vue-storefront/blob/master/core/store/lib/taxcalc.ts)
6. Last section 'Query' for ' format of the query has been described' [here](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/data/ElasticSearch%20Queries.md) link

## Expected behavior
Some links are fixable, but I'm not sure if all of them.

## Steps to reproduce the issue
Click links at [documentation](https://docs.vuestorefront.io/guide/basics/configuration.html) 

## Repository
[@vue-storefront/docs](https://github.com/DivanteLtd/vue-storefront/tree/master/docs)

# Can you handle fixing this bug by yourself?
YES

## Environment details
- Browser: Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- OS: Mint 18.2 sonya

## Additional information
I can fix most of them, but i'm not sure about 'core/store/lib/taxcalc.ts', Did you mean [tax.ts](https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/catalog/helpers/tax.ts).

And last question: [src/extensions](https://github.com/DivanteLtd/vue-storefront/blob/master/src/extensions/index.ts) under 'Mailchimp section' - should it be [src/extensions](https://github.com/DivanteLtd/vue-storefront-api/tree/master/src/api/extensions) ?

**Comment by pkarw** [comment]
Cool! Please go on with the fixes.

Answers:
1. Yes, tax.ts
2. Yes, however it would be great to eventually port these extensions to modules (from 1.6 extensions are deprecated)

**Comment by daksamit** [comment]
And, at [documentation](https://docs.vuestorefront.io/guide/basics/configuration.html) what links should be replaced for: 
1. 'Please check the core/service-worker/order.js for reference' redirects to [core/service-worker/order.js](https://github.com/DivanteLtd/vue-storefront/tree/master/core/service-worker/order.js) - Orders section
2. GraphQL section - [catalog](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/GraphQL%20Action%20Plan.md)
3. Queries section - [here](https://github.com/DivanteLtd/vue-storefront/blob/develop/doc/data/ElasticSearch%20Queries.md)

Moreover, maybe not this issue related, but [PULL_REQUEST_TEMPLATE](https://github.com/DivanteLtd/vue-storefront/blob/master/.github/PULL_REQUEST_TEMPLATE.md) under 'Contribution and currently important rules acceptance' has incorrect links.
I suggest following links:
- [contribution rules](https://docs.vuestorefront.io/guide/basics/contributing.html)
- [TypeScript Action Plan](https://docs.vuestorefront.io/guide/basics/typescript.html) (404 old one)
- [Vue Storefront Modules](https://docs.vuestorefront.io/guide/modules/introduction.html) (404 old one)
```
- [ ] I read and followed [contribution rules](https://docs.vuestorefront.io/guide/basics/contributing.html)
- [ ] I read the [TypeScript Action Plan](https://docs.vuestorefront.io/guide/basics/typescript.html) and adjusted my PR according to it
- [ ] I read about [Vue Storefront Modules](https://docs.vuestorefront.io/guide/modules/introduction.html) and I am aware that every new feature should be a module
```
