### ISSUE TITLE
Add a way to extend server middlewares + access server context from modules

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2494]
## What is the motivation for adding / enhancing this feature?

Currently, there is no way to access server context from modules - either add Express middlewares. Therefore sometimes we need to use [ugly workarounds](https://github.com/pkarw/vue-storefront/blob/bbc1a8e89a87c9aebf549def694e634dd97de21f/core/modules/url/router/beforeEach.ts#L58) to do simple things like server-redirect.

The `Vue.prototype.$ssrRequestContext` is a pretty powerful tool:

```js
    const context = {
      url: req.url,
      output: {
        prepend: (context) => { return '' }, // these functions can be replaced in the Vue components to append or prepend some content AFTER all other things are rendered. So in this function You may call: output.prepend() { return context.renderStyles() } to attach styles
        append: (context) => { return '' },
        appendHead: (context) => { return '' },
        template: 'default',
        cacheTags: null
      },
      server: {
        app: app,
        response: res,
        request: req
      },
      meta: null,
      vs: {
        config: config,
        storeCode: req.header('x-vs-store-code') ? req.header('x-vs-store-code') : process.env.STORE_CODE
      }
    }
```

The `server` section is all ExpressJS. So you can easily add middlewares to `context.server.app` or add response headers to `context.server.response`.

Would be great to have some access to this object from inside modules. Of course accessing it makes only sense when `isServer` is true.

**Comment by AGPDev** [comment]
some news about this ?

**Comment by pkarw** [comment]
I've assigned this one to both of you @filrak and  @andrzejewsky as it's related to new modules architecture merged in two weeks ago

The goal is to have the ability to add the `express.js` middlewares - BUT with support to ES6 and ll the vuex modules :) 

It shouldn't be so hard as the `context.server..app` is just the express.js app and it's passed from [`core/server` to the vue.js app](https://github.com/DivanteLtd/vue-storefront/blob/88b101e309483fa0efb17cbb7dfbfd00b6e63024/core/scripts/server.js#L179)

**Comment by filrak** [comment]
I'll talk to @andrzejewsky about this. It's actually a part of new modules API rfc https://github.com/DivanteLtd/vue-storefront/issues/3144#issue-460588876

**Comment by filrak** [comment]
@AGPDev on it ;)

**Comment by pkarw** [comment]
Temporarily done with https://github.com/DivanteLtd/vue-storefront/pull/3518 - can be extended in the future
