### ISSUE TITLE
state.ts not bind to store index

### ISSUE THREAD

**Issue by dimasch** [DivanteLtd/vue-storefront#2496]
## Current behavior
Current state of undefined

## Expected behavior
Using reactive state as expected by getters

## Steps to reproduce the issue
Add to state some variables and try to use it via getters

## Repository
1) https://github.com/DivanteLtd/vue-storefront/blob/4874488049efcc401119f5995af9afe71650d31f/src/modules/module-template/store/index.ts#L8
2) https://github.com/DivanteLtd/vue-storefront/blob/4874488049efcc401119f5995af9afe71650d31f/src/modules/module-template/store/state.ts#L4

**Comment by filrak** [comment]
Can you give more details? Where should i use the state? It works for me in theme

**Comment by dimasch** [comment]
@filrak For me working after add state to `index.ts`

```
export const module: Module<ExampleState, any> = {
  namespaced: true,
  state: { example: '' }
  mutations,
  actions,
  getters
}
```

Before not working....all from state variables undefined.

**Comment by pkarw** [comment]
Thanks!
