### ISSUE TITLE
Not working read graphql query from custom files 

### ISSUE THREAD

**Issue by dimasch** [DivanteLtd/vue-storefront#2497]
## Current behavior
`query: require('./queries/testentity.gql'),`
read to tockenized object by ES6 standart

## Expected behavior
For graphql need string format for request queries

## Repository
https://github.com/DivanteLtd/vue-storefront/blob/4874488049efcc401119f5995af9afe71650d31f/src/modules/sample-custom-entity-graphql/hooks/afterRegistration.ts#L23

## Additional information
I use workaround and write custom `searchAdapter` for resolve it:
https://github.com/develodesign/vsf-wp/blob/d39962cd511fea8f3a571ed044be992824be4c1e/store/actions.ts#L16

**Comment by pkarw** [comment]
@yuriboyko can You please help us in here? :)

**Comment by yuriboyko** [comment]
@pkarw 
will try to check but probably tomorrow, have urgent task now

**Comment by phoenixdev-kl** [comment]
IMHO this issue got already solved by https://github.com/DivanteLtd/vue-storefront/pull/2404

**Comment by pkarw** [comment]
Closing due to long inactivity
