### ISSUE TITLE
Getting different CMS blocks on different pages is not working

### ISSUE THREAD

**Issue by revlis-x** [DivanteLtd/vue-storefront#2499]
## Current behavior
The logic for fetching CMS blocks in `core/modules/cms/store/block/actions.ts` goes straight to cache if at least ONE block is already in it even if the requested block is not in cache resulting in an error. Same thing with CMS Pages.

```
if (skipCache || (!state.items || state.items.length === 0))

```

## Expected behavior
Only load block from cache, if the requested block is present in cache.

## Steps to reproduce the issue
1. Have 2 different CMS blocks included in 2 different pages.
2. Go to first Page: CMS Block is loaded and stored in VUEX 
3. Go to second page (no hard reload): Second CMS Block is requested from Store although it is not in there.

**Comment by pkarw** [comment]
@anqaka could You please take a look at this issue?

**Comment by anqaka** [comment]
I'll try to fix it this week, sorry for delay.

**Comment by anqaka** [comment]
@filrak @pkarw I look into the code and I cannot check the case where there is some CmsBlock displayed in Vuex state. Even if we add 2 cms blocks on one page, on the beginning on the `single` action, the state.items it's empty. Like cashe dosn't work here.  I don't know how to resolve this isue

**Comment by pkarw** [comment]
Yeah, I believe that `if (skipCache || (!state.items || state.items.length === 0))` is kind of premature optimization and therefore should be simply removed

**Comment by patzick** [comment]
Thanks @qiqqq !
