### ISSUE TITLE
[Desktop] Number of items on PLP 

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2504]
## What is the motivation for adding / enhancing this feature?
Will be useful if on PLP will be number of displayed items products

## What are the acceptance criteria 
Number of displayed items products on PLP

## Additional information
This feature is on Mobile and I think that it useful for user:
![image](https://user-images.githubusercontent.com/47220013/53354494-2643dc00-3927-11e9-9576-2e5cbbf46bde.png)

**Comment by awierzbiak** [comment]
Working on it.

**Comment by patzick** [comment]
Thanks @awierzbiak ! :)
