### ISSUE TITLE
Replace rootstore.state.config with just a module

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#2506]
## What is the motivation for adding / enhancing this feature?

It's not a state per se and this properties don't need to be reactive.

**Comment by pkarw** [comment]
Please just remember that we must maintain the backward compatibility as a lot of 3rd party modules and themes are using `rootStore.state.config`

Acceptance criteria:
- `dynamicConfigReaload` is supported -[ more on how it works](https://docs.vuestorefront.io/guide/basics/configuration.html#server)
- config object can be replaced/modified runtime

**Comment by bratok** [comment]
Hi, colleagues.
In some  core modules i see using rootStore to dispatch actions.

Example:
...
addItem ({commit}, product) {
    commit(types.COMPARE_ADD_ITEM, {product})
    rootStore.dispatch('notification/spawnNotification', { 
...

why you don`t use dispatch function from context?
Example:
...
addItem ({commit, dispatch}, product) {
    commit(types.COMPARE_ADD_ITEM, {product})
    dispatch('notification/spawnNotification', { 
...

is rootStore.dispatch not equal context.dispatch?

**Comment by pkarw** [comment]
Yes, it should get refactored to dispatch() - rootStore shouldn’t be used across view modules

**Comment by bratok** [comment]
Ok, thanks for the quick reply.

what about rootStore.state? Is it equal context.rootState?
