### ISSUE TITLE
Add Support to run tests in docker

### ISSUE THREAD

**Issue by Cyclonecode** [DivanteLtd/vue-storefront#2521]
## What is the motivation for adding / enhancing this feature?
The docker container does not include the needed dependencies for cypress. So, no tests can be run at this point.

## What are the acceptance criteria 
- When we can use cypress to run tests in the docker container.

# Can you complete this feature request by yourself?
Yes

## Additional information
I think switching to `jessie` instead of `alpine` would be a solution and then update the docker file to install the dependencies for cypress, using apt, which can be found here: https://docs.cypress.io/guides/guides/continuous-integration.html#Advanced-setup

**Comment by juho-jaakkola** [comment]
Why would jessie be better than alpine?

**Comment by Cyclonecode** [comment]
If I remember correctly the dependencies for cypress was not available for alpine.

**Comment by juho-jaakkola** [comment]
Alpine indeed does not have all the dependencies recommended by the Cypress documentation:

```
RUN apk add xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
 ---> Running in 1712070bdd41
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  libasound2 (missing):
    required by: world[libasound2]
  libgconf-2-4 (missing):
    required by: world[libgconf-2-4]
  libgtk2.0-0 (missing):
    required by: world[libgtk2.0-0]
  libnss3 (missing):
    required by: world[libnss3]
  libxss1 (missing):
    required by: world[libxss1]
```

**Comment by juho-jaakkola** [comment]
I was able to create an experimental Docker image on top of `debian:jessie`, and successfully run the tests in it:

![Screenshot 2019-05-15 at 8 16 46 AM](https://user-images.githubusercontent.com/883920/57752931-fd8fdf00-76ea-11e9-9535-8bb8d237c473.png)

But now I'm wondering whether there is any point in running e2e tests unless we also have an instance of both Vue Storefront API and Magento running within the same container (or somewhere else as long as the container has access to them?).

Any ideas?

**Comment by juho-jaakkola** [comment]
The workaround in my project is currently that only the VSF branches are being run inside containers, and they all connect to a separate external VSF-API instance.
