### ISSUE TITLE
Refreshing page causes that images blinking for moment on other ones

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2523]
## Current behavior
Refreshing page causes that images blinking for moment on other ones

## Expected behavior
Images shouldn't blinking on other when user refresh page
## Steps to reproduce the issue
1. Open any category of products
2. Refresh page

## Environment details
https://test.storefrontcloud.io

**Comment by ibugaj** [comment]
![blinking](https://user-images.githubusercontent.com/47220013/53660627-996a8c80-3c5e-11e9-98b3-2d4b0a5e8481.gif)

**Comment by pkarw** [comment]
Looks like CSR product/list returns different products or just in different order. BUT: when products has been queried in the SSR there should be no additional cal CSR

We must check it to make sure about the reason of this strange vehavior

**Comment by pkarw** [comment]
By some reason the CSR query is being executed: https://www.dropbox.com/s/pof6h2gtamzoy64/Screenshot%202019-03-01%2020.47.20.png?dl=0

**Comment by pkarw** [comment]
This issue doesn't exist in the 1.8.0 (on demo)

**Comment by pkarw** [comment]
Moreover, it's executed twice in the CSR by some reason :https://www.dropbox.com/s/ltdc1307ec0n6yr/Screenshot%202019-03-01%2020.57.57.png?dl=0

**Comment by pkarw** [comment]
This is related to `resetAllFilters` - https://www.dropbox.com/s/kag04gunonzdqvi/Screenshot%202019-03-01%2021.02.18.png?dl=0

**Comment by pkarw** [comment]
@patzick  -> I belive that You should add the `if (this.hasActiveFilters) {` condition to `resetAllFilters` - because after SSR there are no active filters (this is only true before we merge in https://github.com/DivanteLtd/vue-storefront/pull/2180 - but I think that with #2180 `resetAllFilters` no longer will be needed)

Please do test it and fix if this is good idea

**Comment by pkarw** [comment]
There is still some issue with switching categories; when You set the filter and choose different category filters are not reset (which is probably OK as there is no `mounted()` hook called in this case) - however, on the demo instance - the filters have been reset
