### ISSUE TITLE
[RFC] Replace asyncData with serverPrefetch

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2525]
## What is the motivation for adding / enhancing this feature?

We should replace `asyncData` with [`serverPrefetch`](https://ssr.vuejs.org/api/#serverprefetch) in the `core/pages`

This is probably not urgent as `serverPrefetch`  it's just "asyncData on steroids". However, it probably allows us to simplify and refactor [`Product.js:asyncData`]() and [`Category:asyncData`](https://github.com/DivanteLtd/vue-storefront/blob/40840ecbe5b1ffa9e83e72cf20f41b3448bb874c/core/pages/Category.js#L84) that is currently a little bit messy and duplicated with the `validateRoute` in both: [Category](https://github.com/DivanteLtd/vue-storefront/blob/40840ecbe5b1ffa9e83e72cf20f41b3448bb874c/core/pages/Category.js#L229) and [Product](https://github.com/DivanteLtd/vue-storefront/blob/40840ecbe5b1ffa9e83e72cf20f41b3448bb874c/core/pages/Product.js#L93)

## What are the acceptance criteria 

- The data fetching methods: `validateRoute` and `asyncData` unified to a single one,
- Data fetching schema works exactly the same way as it's working now - single fetch if SSR request (no additional CSR request), single fetch when CSR request
- `asyncData` methods kept as a backward compatibility
- currently, we do have access to `ssrContext` in the `asyncData` - by the time of this refactoring we should have the [option to add custom middlewares](https://github.com/DivanteLtd/vue-storefront/issues/2494) already in place

**Comment by pkarw** [comment]
This task should be done after #2446 merged in, not earlier - to avoid conflicts

**Comment by filrak** [comment]
Also in this case we should get rid of things like `preAsyncData` and multiple `asyncData` invocations for core/theme components modifying each other. Imho we should seek for a more elegant solution to modify asyncData calls.

**Comment by pkarw** [comment]
After product + category page refactor I'm not sure but maybe we should move the SSR data fetching logic all to this?
