### ISSUE TITLE
No such entity with CartID = X

### ISSUE THREAD

**Issue by jorkvist** [DivanteLtd/vue-storefront#2540]
## Current behavior
When a cart is existing in Vue storefront but not in Magento. The application throws an error. It happens for me fx when a customer completes a purchase (with the checkout hosted in magento) and then goes back to Vue Storefront. 
![screenshot_20190225-192300](https://user-images.githubusercontent.com/5425824/53734381-1d518e00-3e84-11e9-8d3f-82c0cc1adac8.jpg)
![screenshot_20190225-192626](https://user-images.githubusercontent.com/5425824/53734382-1d518e00-3e84-11e9-8819-9ee35708cbaf.jpg)

## Expected behavior
Need to be sure that if a cart is existing in Vue Storefront but not in Magento that the cart it's created in Magento again so the end user dosen't get error messages. (Cart in Magento is not saved forever)

## Steps to reproduce the issue
Remove the Cart someway in Magento (Fx complete a purchase, wait or flush them) and then try do add / update cart in Vue Storefront. 

## Repository
1.7

# Can you handle fixing this bug by yourself?
No

## Environment details
- Browser: Chromes
- OS: MacOSX
- Node: 

## Additional information
From #help 
"pkarw (Core Team)   [6 days ago]
I believe he/she must rel-login to refresh the cart is related to his/her account. Probably you should also create an issue for that and we should refresh the cart is after X hours of inactivity (?). Currently then the cart is is stored in the local storage is being kept there forever - I mean assuming that only Vs is working on this is. If the quote has been closed on magento/admin then it’s no longer valid and Vs is not refreshing it which is kind of issue probably"

**Comment by pkarw** [comment]
Related to #2592

**Comment by pkarw** [comment]
It's  been fixed with #2592
