### ISSUE TITLE
yarn tests:unit - invalid config file

### ISSUE THREAD

**Issue by daksamit** [DivanteLtd/vue-storefront#2542]
## Current behavior
![image](https://user-images.githubusercontent.com/7165997/53738786-6ad3f800-3e90-11e9-866b-fc1f696f782a.png)

## Expected behavior
Unit tests should work,
configuration file should be adjust to typescript.

## Steps to reproduce the issue
Just type `yarn tests:unit`

## Repository
https://github.com/DivanteLtd/vue-storefront

# Can you handle fixing this bug by yourself?
NO

## Environment details

- Node: v8.15.0

**Comment by lukeromanowicz** [comment]
Jest based unit tests proposed in #2305 have been merged yesterday and will be published in VS 1.9. For now, you can check them out on develop branch.

https://github.com/DivanteLtd/vue-storefront/pull/2414
