### ISSUE TITLE
Documentation theme core components explained wrong

### ISSUE THREAD

**Issue by haukebri** [DivanteLtd/vue-storefront#2546]
## Current behavior
The current explanation on https://docs.vuestorefront.io/guide/core-themes/core-components.html states, that core components are for business logic only and should be imported as mixins. But that is not the case for the current default theme. There core components are regular components with a template and style.

## Expected behavior
The doc should mirror the logic used within the code. 

## Steps to reproduce the issue
Just visit the doc page: https://docs.vuestorefront.io/guide/core-themes/core-components.html

# Can you handle fixing this bug by yourself?
NO

## Environment details
No details for the doc.

## Additional information
It feels like the page contains information about the modules?

**Comment by filrak** [comment]
@kkdg I'm assigning this issue to you :)

**Comment by kkdg** [comment]
@filrak got it, working on it.
