### ISSUE TITLE
RWD - Adjustments for the product slider feature on the homepage

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#255]
The original project of the feature:
![zrzut ekranu 2017-11-06 o 21 41 35](https://user-images.githubusercontent.com/18116406/32462949-8b55a82a-c33b-11e7-9b0a-8673bdcbe10d.png)

The feature applied currently on the homepage:
![14](https://user-images.githubusercontent.com/18116406/32463363-f13bf24c-c33c-11e7-8f67-12b2e612a4e1.png)

Please add these improvements:
- change the title to "New Luma Yoga Collection"
- ass "see all in the collection" link ![zrzut ekranu 2017-11-06 o 21 49 31](https://user-images.githubusercontent.com/18116406/32463200-641a328e-c33c-11e7-870e-0621bfb0aed4.png)
- reduce padding in the bottom, adjust the height of the widget as it's set on the project (420px);
- apply only 1 raw, also in the mobile, products shouldn't be listed in the form of the grid with multiple rows;
- add slider capabilities so as a Customer I should be able to slide the feature to the left/right and see 4 more products
- add "almost visible products" to the left and right of the slider (they suggest the slider capabilities) ![zrzut ekranu 2017-11-06 o 21 52 58](https://user-images.githubusercontent.com/18116406/32463345-df5c2920-c33c-11e7-8339-162f402d3b7d.png)

**Comment by pkarw** [comment]
@Aekal could you take care of this one?

**Comment by karolbzik** [comment]
@Aekal could you add slider to the feature?
![vs2](https://user-images.githubusercontent.com/18116406/33650329-cdc95174-da61-11e7-8916-ecd5a493f43f.gif)

**Comment by pkarw** [comment]
@filrak please take care of this one Ok?

**Comment by filrak** [comment]
@pkarw ok ;)

**Comment by filrak** [comment]
@karolbzik the slider works like in the gif,   "see all in the collection"  link remained and the task is ready ;)
