### ISSUE TITLE
Fixed Default property issue for the col-xs-* CSS classes

### ISSUE THREAD

**Issue by cnviradiya** [DivanteLtd/vue-storefront#2550]
## Current behavior
As I seen there are misbehaviour with the default theme col-xs-* classes due to missing default property.

## Expected behavior
Ex. **Registration Popup**
http://www.screencast.com/t/V2V3ilebw

## Steps to reproduce the issue
Ex. **Registration Popup**
http://www.screencast.com/t/7Gmvp95UjhB

## Repository

# Can you handle fixing this bug by yourself?
Yes

## Environment details

- Browser: Chrome
- OS: Ubuntu 18
- Node: 8.10.0

## Additional information
N/A

**Comment by patzick** [comment]
Thank you @cnviradiya!
