### ISSUE TITLE
Newsletter feature not working at all

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#2558]
Test
- profile
- indiv components
- api

**Comment by mdesmet** [comment]
Hi,

Is this the mailchimp integration or rather integration with magento 2?

Maybe we can provide generic components and do the integration with either magento2 or maichimp in vue-storefront-api?

I'm actually working right now on mailchimp but also looking at replacing mailchimp with standard magento 2 functionality.

**Comment by pkarw** [comment]
Related to #2754

**Comment by alinadivante** [comment]
@patzick  @mdesmet hello guys, I tested newsletter on develop branch, but unfortunately it doesn't work..
When I try update my preferences I have errors in dev console.
![image](https://user-images.githubusercontent.com/36628922/58405620-29ef1800-8068-11e9-8049-1c9923c4f057.png)
Also when I use "Subscribe" button.

**Comment by mdesmet** [comment]
@alinadivante: I will have a look tonight.

**Comment by GabiDivante** [comment]
hi @mdesmet @patzick I tested changes on develop branch and an error appears when I try to subscribe newsletter from the footer or by changing preferences in my account (link to localhost)
![Selection_071](https://user-images.githubusercontent.com/49188852/58947926-4cc8ad00-8789-11e9-9e0e-22b98067326d.png)

**Comment by pkarw** [comment]
@GabiDivante this feature requies the latest / develop version of `vue-storefront-api` deployed - which is not currently available on any public demo instance. SO the question is if You're using the local api in order to test it out?

**Comment by mdesmet** [comment]
@GabiDivante, @pkarw : i'll retest this one. To be honest, i didn't retest the frontpage newsletter subscription with last changes.

**Comment by GabiDivante** [comment]
@pkarw  I wasn't using the local API so probably that's the cause.  @mdesmet that would be great, subscription from the front page for logged in users should work in the same way as changing subscriptions status in my account.

**Comment by pkarw** [comment]
@mdesmet can You Please update us with the status?

**Comment by mdesmet** [comment]
Hi, it's working for me. I'm able to subscribe from the front page, so probably indeed it was not linking to the new api.
