### ISSUE TITLE
My orders in my profile not refreshed after putting an order

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#2559]
## Current behavior
After order is placed as a user when we navigate to My profile -> My orders order is not visible
## Expected behavior
It should be displayed right after placing
## Steps to reproduce the issue
1. Place the order as logged in user
2. Go to my orders section of profile
3. Order is not visible
4. It's visible after refresh

## Repository

# Can you handle fixing this bug by yourself?

Yes but feel free to pick

**Comment by jszczech** [comment]
I'll take care of it

**Comment by pkarw** [comment]
@jszczech how about this issue? Let us know if You need any assistance
