### ISSUE TITLE
Search component not showing results if the're  < 3 letters

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#2561]
## Current behavior
Search component is showing 'No results found' if we type less than 3 letters.

## Expected behavior
Since it's just a minimum number of letters to show results we shouldn't give any information about them. Only validation.

## Steps to reproduce the issue
1. Go to the search component
2. Type < 3 letters
3. 'No results found' should appear

**Comment by robwozniak** [comment]
I'll take care of it

**Comment by patzick** [comment]
Closing, thanks @robwozniak ! :)
