### ISSUE TITLE
Calling custom attribute outside product.vue 

### ISSUE THREAD

**Issue by michhy** [DivanteLtd/vue-storefront#2563]
Hello

Apart from product.vue, can I call custom attribute data from other pages like product tile, microcart and checkout page too?

I have an attribute called 'subtitle' and would it to show on other pages under each product too.

Thanks in advance! :)

**Comment by michhy** [comment]
Found out the way! Silly me.
Just import from local.json by adding specific custom attribute name e.g. subtitle in the productlist section, and call in certain page by {{ product.subtitle }}, that simple!

**Comment by thonglm122** [comment]
Hello, How can I add custom attribute in category filter?
