### ISSUE TITLE
"Unable to preventDefault inside passive event listener invocation." Product gallery when enabling drag

### ISSUE THREAD

**Issue by hoaeuro93** [DivanteLtd/vue-storefront#2572]
"Unable to preventDefault inside passive event listener invocation." Product gallery when enabling drag

**Comment by filrak** [comment]
We have passive listeners enabled to improve scrolling performance. You can easly get rid of this behaviour by removing this line in `index.js` file fo your theme`

````js
import '@vue-storefront/core/lib/passive-listeners'

````
