### ISSUE TITLE
Custom color swatch

### ISSUE THREAD

**Issue by Decntdefalt** [DivanteLtd/vue-storefront#2579]
Hex color swatches are nicely showing up. But not sure why custom swatches by uploaded images are not.

How to make custom swatches appear?

<img width="569" alt="Screen Shot 2019-03-11 at 05 40 22" src="https://user-images.githubusercontent.com/41927878/54091884-56c45500-43c0-11e9-960e-b7fe6f3fcc08.png">

Thanks!

**Comment by pkarw** [comment]
Unfortunately, we can't easily get the color swatches from Magento using API; We can possibly do this with https://github.com/DivanteLtd/magento2-vsbridge-indexer @afirlejczyk can You please take a look at this and propose some solution? I mean: we should probably put the swatches into attribute metadata and use it in VS frontend (currently we're just mapping the attribute label not using any other metadata)

For now, You can use the [config](https://github.com/DivanteLtd/vue-storefront/blob/974c5293cdf1a3a5d322228d2c53d023be2f599c/config/default.json#L270) based mapping to map the color labels to specific color hex values. Not optimal, but works :)

**Comment by pkarw** [comment]
Related to: https://github.com/DivanteLtd/magento2-vsbridge-indexer/issues/15

**Comment by Decntdefalt** [comment]
> Unfortunately, we can't easily get the color swatches from Magento using API; We can possibly do this with https://github.com/DivanteLtd/magento2-vsbridge-indexer @afirlejczyk can You please take a look at this and propose some solution? I mean: we should probably put the swatches into attribute metadata and use it in VS frontend (currently we're just mapping the attribute label not using any other metadata)
> 
> For now, You can use the [config](https://github.com/DivanteLtd/vue-storefront/blob/974c5293cdf1a3a5d322228d2c53d023be2f599c/config/default.json#L270) based mapping to map the color labels to specific color hex values. Not optimal, but works :)

Sorry for the late reply. I will try to play around with it and find a way, will post a solution if I can get there :D
