### ISSUE TITLE
When the Microcart is open and you click any option from menu (eg. "Men") ...

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#258]
... microcart should close then but it doesn't :)

**Comment by pkarw** [comment]
![zrzut ekranu 2017-11-07 08 35 40](https://user-images.githubusercontent.com/211899/32482164-c29872da-c396-11e7-9d3c-c9c2cb7249f3.png)

**Comment by karolbzik** [comment]
This issue is related to https://github.com/DivanteLtd/vue-storefront/issues/259 and https://github.com/DivanteLtd/vue-storefront/issues/263.
