### ISSUE TITLE
Wishlist and compare list are not cached properly 

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2580]
## Current behavior
After refreshing pare or restarting browser, wishlist and compare list are empty

## Expected behavior
Content of wishlist and compare list should be cached and still available after refresh or browser restart

## Steps to reproduce the issue
1. Open http://test.storefrontcloud.io
2. Add any product to wishlist and compare list
3. Refresh page (F5)

## Repository
http://test.storefrontcloud.io

## Can you handle fixing this bug by yourself?
no

## Environment details

- Browser: All (tested on Chrome, Firefox, Opera, Edge and Safari - desktop and mobile)
- OS: All (Tested on win10, macOS + android and iOS on mobile)

## Additional information
Cart seems unaffected.

**Comment by pkarw** [comment]
@filrak how about thi one?
