### ISSUE TITLE
Colors and custom options not working together

### ISSUE THREAD

**Issue by ghost** [DivanteLtd/vue-storefront#2581]
I've installed VSF 1.9 around 4 times with the following environment:

Elasticsearch 5.6.0
NodeJS 8.0.0 / 10.9.0 (Currently 10.9.0)
Redis 5.03
Yarn 1.13.0
NPM 6.2.0
Magento 2.3

Everything works great. The problem is when enabling custom options for a Magento product, the colors will disappear.

<img width="1155" alt="Screen Shot 2019-03-12 at 04 30 22" src="https://user-images.githubusercontent.com/41927878/54156304-f8ab7680-4480-11e9-84f1-b81d9a9df021.png">

and when hard reloading the page

<img width="1343" alt="Screen Shot 2019-03-12 at 04 30 54" src="https://user-images.githubusercontent.com/41927878/54156354-02cd7500-4481-11e9-9e2a-cf6a4a3b8aee.png">

Then checking console: vue.runtime.esm.js:1878 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

So I'm wondering, is there something conflicting with the node version I'm running and if so what is the optimal versions for my envronment I should run in order not to experience issues with VSF?

The only difference is, when I disable the custom options, colors will appear and there will be no errors in the console. 

**Edit**: Fresh install without any of my configurations (theme) and still facing the same issue.

**Comment by Decntdefalt** [comment]
My apologies, issue with the theme I've developed.. I did a fresh install without my theme to confirm this.

**Comment by pkarw** [comment]
This is probably due to some SSR related issue (with one of the components). Did You create a theme with some previous version of VS (lets' say 1.7) and did an upgrade?
Can You check if in the dev console there are any other issues (development mode, not production)?

@patzick

**Comment by revlis-x** [comment]
Afaik Custom Options are currently not supported on Configurable Products (which is a pity). I opened the same issue #2141  a while ago.

**Comment by pkarw** [comment]
@Decntdefalt could You please provide us with the database dump to let us work on the same data? vue-storefront-api public endpoint with Your data set will be enough (or .json dump)
