### ISSUE TITLE
Confusing / overcomplicated calculations in cart

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2584]
## Current behavior
Few diffrent numbers / prices are presented to customer - they seem to be unrelated to each other

## Expected behavior
Prices are displayed in simple and understandable way

## Steps to reproduce the issue
1. Open https://demo.storefrontcloud.io/ or https://test.storefrontcloud.io/
2. Add any product to cart
3. Open cart

![total](https://user-images.githubusercontent.com/47415585/54198967-0d5f2d00-44c8-11e9-9364-8cd3f8f866b7.PNG)

## Analysis
Currently, prices displayed seem to be calculated in this way:

Netto(net price) = price from magento (not displayed anywhere) - here its 40$
Shipping = 5$ (fixed)
Discount = Netto x 0.15 (15% cart discount set in Magento)
Tax = (Netto - Discount) x 0.23 (23% tax rate set in Magento)
Subtotal (price displayed in PLP, PDP and cart) = Netto x 1.23
Red (recuded price in cart) = Subtotal - Discount
Grand Total = Netto + Tax + Shipping - Discount

**Problem:** Currently, if discount is active, Subtotal and Red prices are misleading, as they are not used anywhere in final price calculation. While they are displayed in PLP, PDP and cart, they have nothing to do with final amount of money payed by customer.

**Reason:** For the purpose of **Grand total** calculation, **Tax** is based on reduced price. However, for calculating Subtotal price, tax is added to full netto price.

**Solution** Assuming all caculations are correct, we should consider diffrent set of displayed data (or description), so customer will always know how much he will pay and where are those numbers (i.e. tax and discount) coming from.

**Comment by pkarw** [comment]
This is 100% configurable in the Magento (and we get it from Magento totals enpoint in the final form). Probably it needs to investigate the proper M2 config regarding the totals
