### ISSUE TITLE
Add 'Clear cart' button

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2587]
## What is the motivation for adding / enhancing this feature?
Currently, customer can remove products from the cart, one at a time. Thats enough if he has one or two products he wants  to remove.  However, if he has many more, and completely changes his mind about products he wants to buy, whole process takes significantly long time, especially when "remove from cart" button is kinda small, and every single remove action needs separate confirmation.  One button that allows for instant clear cart and start new shopping, is quite common in ecommerce. 

## What are the acceptance criteria 
- If there are any products in cart, new "clear cart" button is displayed in cart window
- Clicking it removes all products from cart (after confirmation popup, to prevent accidental use)

## Can you complete this feature request by yourself?
no

**Comment by jablpiotrek** [comment]
I'll start it.

**Comment by jablpiotrek** [comment]
https://github.com/DivanteLtd/vue-storefront/pull/2621

**Comment by patzick** [comment]
Thanks @jablpiotrek !

**Comment by ArturDivante** [comment]
Button works correctly, but from UX perspective it's location in a bit unfortunate. IMHO bare minimum should be to separate it from 'Instant checkout' button. But in long term perspective, best place for this button would be in the upper part of MicroCart window.  Currently user with any products in the cart (even two, depending screen parameters) needs to scroll don microcart even to realize that this button exist. In most cases users will just manually remove prducts rather than scrolling down to find '"clear Cart' below chechout options.
