### ISSUE TITLE
The top should be below the sidebar cart, the fixed menu overlays "x" option of shopping cart

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#259]
![zrzut ekranu 2017-11-07 08 36 56](https://user-images.githubusercontent.com/211899/32482200-de03c98e-c396-11e7-9e8e-ad5455fa98c1.png)
should always be on top

**Comment by karolbzik** [comment]
The top should be below the sidebar cart.

![20](https://user-images.githubusercontent.com/18116406/32483981-8a120ad6-c39e-11e7-856b-a03329236dbc.png)

**Comment by karolbzik** [comment]
@filrak this is related to https://github.com/DivanteLtd/vue-storefront/issues/263, both sidebar cart and sidebar menu should be above the top.

**Comment by Aekal** [comment]
@karolbzik It looks like both sidebars are above the top already, this issue can be closed.
