### ISSUE TITLE
Cart token is not refreshed even when invalid

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2592]
## Current behavior

![Screenshot 2019-03-14 09 17 10](https://user-images.githubusercontent.com/211899/54341534-58994d00-463a-11e9-9428-8819a76f3e92.png)

There are some certain situation where the current shopping cart (stored in the localStorage `shop/carts/current-cart-token`) is no longer valid. For example, the quote has been closed server side.

In this case the `shipping-methods` and `payment-methods`, `totals` all subsequent calls return an issue like `{"code":500,"result":"No such entity with cartId = null"}`

In this situation the solution is to clear the local storage - as after that the new shopping cart id will be retrieved.

We should re-create shopping cart (to get new token/id automatically).

An example on how can we recreate the cart:
https://github.com/pkarw/vue-storefront/blob/f90f64de9cb3ce02e0f5c92d6ceba51014a066ca/core/modules/cart/store/actions.ts#L662

## Steps to reproduce the issue

This issue is not occurring all the time - to be honest, it's pretty hard to recreate it. I used to have when I've logged in as a user after 5-6months of inactivity. The user account has some quote id assigned (like 5561) which has been no longer valid.

We can probably reproduce this issue by manually setting the `localStorage` key  `shop/carts/current-cart-token` to random value and testing the subsequent cart synchronization logic

**Comment by pkarw** [comment]
Moreover we need to fix `cart/actions.ts:411` to better handle the issue (as on screenshot)

**Comment by michhy** [comment]
Hi Piotr 
I found the way to recreate this issue:
just remake order > clear cart > remake order again for a few times
it also leads to shipping method and payment method loading errors.

**Comment by michhy** [comment]
I found out the way to fix it:

in core/modules/cart/store/action.ts, 
in the function "clear (context)"
remove the line 
`context.commit(types.CART_LOAD_CART_SERVER_TOKEN, null)`
add this line instead
`context.commit(types.CART_SAVE, [])`

this basically avoid the token error (originally it turn the cart token to null, and 'remake order' won't generate the new token for the cart, leads to the error 'no such entity with cartID = null'); 
and the added line will remove all the cart items in server side instead of just cart (
without this added line, after 'remove cart' and if you click 'back' from the browser, the cart will load again as the server didn't know you have removed the cart items.

**Comment by pkarw** [comment]
@michhy with the proposed fix it might happen that we'll clear the server side cart BEFORE order was being transferred to Magento and being placed -> Risky.

Shouldn't we instead call `cart/serverCreate` in here to make sure cart token isn't empty? Probably we need

**Comment by michhy** [comment]
@pkarw  Yea, you are right.
now I edit the function code like this:
`clear (context) {
    context.commit(types.CART_LOAD_CART, [])
    // context.commit(types.CART_SAVE, [])
    context.commit(types.CART_LOAD_CART_SERVER_TOKEN, null)
    if (rootStore.state.config.cart.synchronize && !rootStore.state.config.orders.directBackendSync) {
      rootStore.dispatch('cart/serverCreate', { guestCart: !rootStore.state.config.orders.directBackendSync }, {root: true}) // guest cart when not using directBackendSync because when the order hasn't been passed to magento yet it will repopulate your cart

    } else {
      rootStore.dispatch('cart/serverCreate', { guestCart: true }, { root: true })
    }
  },`

and it seems fine, fixed the cartID token issue and also clear the cart item from server.

**Comment by pkarw** [comment]
OK, cool - could You propose a PR with this fix please?

**Comment by michhy** [comment]
@pkarw  it might sounds ridiculous, this is my first time working on github projects, I even donno how to fork my project and merge the updates, I did it all by copy and paste (compare my old code and embed the updates)....  :'(
Do you have any github tutorial that I can follow the steps?

Thanks :P

**Comment by pkarw** [comment]
I think this one could be helpfull: https://help.github.com/en/articles/creating-a-pull-request
