### ISSUE TITLE
Payment.vue issue when no address set

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2593]
## Current behavior

![Screenshot 2019-03-14 09 30 31](https://user-images.githubusercontent.com/211899/54350519-cbf88a00-464d-11e9-8190-0cc53aaddb43.png)

## Expected behavior

No error.

## Steps to reproduce the issue

I've logged in as a user who has no address assigned; then added the product to cart and "Go To Checkout". Then this error appeared.

**Comment by kziuzial4w** [comment]
My issue.
