### ISSUE TITLE
Error CONNECTION_REFUSED on attempt to add review

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2594]
There is still a problem with review form

## Related issue
#2313  

## Current behavior
Error messag appears on the front and in console

## Expected behavior
Review is correctly added

![review error1](https://user-images.githubusercontent.com/47415585/54363135-9910bf00-466a-11e9-8774-8fee5992993e.PNG)
![review error2](https://user-images.githubusercontent.com/47415585/54363136-9910bf00-466a-11e9-9bbd-5ee2373aadf6.PNG)

## Steps to reproduce the issue
1. Open any product page
2. Scroll down to "add review" form
3. Fill all fields and click "Add review"

## Repository
https://demo.storefrontcloud.io/
https://next.storefrontcloud.io/
https://test.storefrontcloud.io/

# Can you handle fixing this bug by yourself?
no

## Environment details
Tested on Chrome, Firefox, Edge/windows, Chrome/android and safari/iOS
Problem occurs everywhere. 

## Additional information
List of example tested products SKU is below, but so far fail rate is at 100% :)

WS01-XS-BLACK
MT10-XS-YELLOW
WS08-XL-RED
24-WG080
24-MG01

Tried as logged in user and logged out, from many devices. Couldn't send a single review.

**Comment by pkarw** [comment]
By some reason the wrong URL is set for reviews_endpoint

**Comment by pkarw** [comment]
It was configuration issue with cloud instances. There was the `reviews.create_endpoint` missing. I've just added it and it will be fixed after @patzick deploy the `test`, `next`, and `demo` instances. I've added this property to the new instance template as well

@patzick I've changed the local.json by adding:
```
,
    "reviews": {
      "create_endpoint": "https://demo.storefrontcloud.io/api/review/create"
    }
```

https://code.storefrontcloud.io/Divante/next-storefrontcloud-io/blob/master/config/local.json#L9
https://code.storefrontcloud.io/Divante/test-storefrontcloud-io/blob/master/config/local.json#L9
https://code.storefrontcloud.io/Divante/demo-storefrontcloud-io/blob/master/config/local.json#L9
