### ISSUE TITLE
"multisiteCommonCart": true has no effect.

### ISSUE THREAD

**Issue by thomasthune** [DivanteLtd/vue-storefront#2595]
## Current behavior
Setting "multisiteCommonCart": true, has no effect

## Expected behavior
Setting "multisiteCommonCart": true, should force the user to have different carts on the different stores respectively

## Steps to reproduce the issue
Setup multistore environment with: 
"multisiteCommonCart": true

Visit each store, observe localStorage in devtools, only "default" non-prefixed cart storage will be visible:
![screenshot-1552651974](https://user-images.githubusercontent.com/16956328/54430527-2a903780-4724-11e9-9084-b17206d04dfe.png)

## Repository
@vue-storefront: v.1.8.3

# Can you handle fixing this bug by yourself?
No, not at the moment

## Additional information
The initializing of $db.cartsCollection is run in the beforeRegistration hook in the cart module. This happens as part of createApp (core/app.ts) and during this the currentStoreView is always initialized with null.
Later during bootstrap, either client-entry og server-entry the storeview is changed, with prepareStoreView.
Only problem is that the $db.cartsCollection isnt updated, since the beforeRegistration hook is not fired again after createApp().

Like with the syncTask storage it should be initialized when the store changes (core/lib/multistore.ts:76). 
There are a couple of modules who would rely on this behaviour: cms, user, cart, compare, checkout.

**Comment by filrak** [comment]
On it ;)
