### ISSUE TITLE
Installer enhancements

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#260]
The new installer is cool, though it may be even better :)

1. Let's give the user OPTION not INPUT for the image backend (https://demo.vuestorefront.io/img OR http://localhost:8080/img); this should be an OPTION when user selected to install the backend at first; if he/she is using remote backend of course we're limited to give an INPUT option here because we're not sure if local backend is available

2. Please add "npm run all" + one liner about it in the "Thank you screen"; this is for running docker, api and frontend; because after finished installation users may struggle to run it once again :)

3. I'm affraid that after I've given "localhost:8080/img" as image backend it automatically added https:// - which is wrong (should be http://)

4. Please provide the "npm run restart-all" OR "npm run stop-all" option to restart the whole env - after for example some config tweaks - this is low prio. you probably should store process pids in that case

**Comment by madonzy** [comment]
@pkarw PR: https://github.com/DivanteLtd/vue-storefront/pull/266

**Comment by pkarw** [comment]
Closing for now
