### ISSUE TITLE
VSF modules can't extend router

### ISSUE THREAD

**Issue by vue-kacper** [DivanteLtd/vue-storefront#2601]
## Current behavior

This is example route added by "raw-output-example" module:

https://**demo**.vuestorefront.io/no-js.html   ---> It works
https://**next**.storefrontcloud.io/no-js.html ---> Doesn't work

## Expected behavior

Modules should be able to extend router and add new routes

## Steps to reproduce the issue

Problem appears on "develop" branch:

https://next.storefrontcloud.io/no-js.html

**Comment by pkarw** [comment]
Thanks! Another one related to UrlDispatcher :)
