### ISSUE TITLE
Vue Storefront import from Magento 2.3 very heavy

### ISSUE THREAD

**Issue by Ale763** [DivanteLtd/vue-storefront#2603]
## Current behavior

I am currently testing the framework without any modifications, just the clean install of the framework on a clean server. 

My setup consists of 2 different debian servers. One serving Vue Storefront (vue-storefront + vue-storefront-api)

 and the other serving Magento 2.3. The installation steps from the tutorials were followed to install and configure Vue Storefront with Magento. Both servers have 4GB of RAM and have 2vCPUs. Both servers are set up inside a Vagrant box.

In the development setup, when importing the data with the vue-storefront-api there is an enormous amount of requests to the Magento 2 REST API. This causes my Magento server to spawn a lot of workers for php-fpm. I had to raise the amount of workers from 50 to 150, because the import kept failing for random products. The error was not very clear (HTTP Error undefined), but I was able pinpoint the problem with some help. 

After fixing this problem I tried to run the import again and it caused my Magento server to run out of memory. An htop revealed that all the resources of the server were requested by php-fpm (see screenshot)
![image](https://user-images.githubusercontent.com/13874391/54514565-c99e7480-495a-11e9-8f6a-d1e5bef04f59.png)

To solve this, the Magento server had to be upgraded from 4GB and 2 vCPUs to 8GB and 4vCPUs. This seems a bit overkill considering it's just a clean install of the framework doing an import.

## Expected behavior

I expect the import succeeding whithout problems on my server setup (debian with 4GB and 2vCPUs inside Vagrant box). 

## Steps to reproduce the issue

I just did a clean development install, as described in the documentation. Both the Magento and Vue Storefront servers are set up inside a Vagrant Box with 4GB of RAM and 2 vCPUs. I just ran the installer and inserted all the correct credentials and information requested by the installer. The requested dependencies are also

When importing the data, the Magento server has to work very hard to keep up with the requests from the vue-storefront-api. The php-fpm (php version 7.2) workers were raised from 50 to 150 workers to solve the issue of various products not containing all the correct information. This also causes Vue Storefront to become very unstable (e.g. because prices or size-variants are missing adding a product to the cart raises an error that a variant must be chosen. Obviously this is impossible because the data is not present). After this modifcation to the Magento server I tried installing it again, but this time my Magento server ran out of memory. As the htop revealed, the import requests a lot of resources from the server, which causes it to run out of memory.

php-fpm information:
[www.conf.txt](https://github.com/DivanteLtd/vue-storefront/files/2977164/www.conf.txt)
[php-fpm.conf.txt](https://github.com/DivanteLtd/vue-storefront/files/2977165/php-fpm.conf.txt)

# Can you handle fixing this bug by yourself?

NO

## Environment details

- Browser: All browsers
- OS: Debian inside a Vagrant box
- Node: v10.15.2
- Code Version: Master branch commit 974c5293
- Magento: 2.3

**Comment by pkarw** [comment]
Hi there! `mage2vuestorefront` isn't the most optimal indexer - that's true; it's running categories import in parallel so it could end-up with multiple fpm processes on the magento side. Please consider using the https://github.com/DivanteLtd/magento2-vsbridge-indexer - which has been designed to solve this and other kind of performance issues
