### ISSUE TITLE
Product SKU in wishlist should be more visible

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2606]
## Current behavior
Product SKU displayed in wishlist is almost invisible

![wishlistSKU](https://user-images.githubusercontent.com/47415585/54605630-fbdacf80-4a49-11e9-96fe-c51e64fced62.PNG)

## Expected behavior
If product SKU is needed in that window, it should be reasonably visible (darker?)

## Steps to reproduce the issue
1. Add any product to wishlist
2. Open wishlist sidebar

## Repository
https://demo.storefrontcloud.io/

## Can you handle fixing this bug by yourself?
no

## Environment details
- Browser: all
- OS: all

## Additional information
Single product can be added to wishlist many times - once for every size and color combination. SKU reflects those diffrences, so it should still be displayed here. However, currently font color is so bright, its barely readable on the white background.

**Comment by patzick** [comment]
Thanks @PanMisza !
