### ISSUE TITLE
'Product added to cart' popup appears only once per product

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2610]
## Current behavior
Green confirmation popup 'Product has beed added to cart' is displayed only once. 

## Expected behavior
Confirmation popup should appear every time product is added to cart. 

## Steps to reproduce the issue
1. Open any product page
2. Add product to cart
3. Add the same product again, __without changing size or color__

## Repository
https://demo.storefrontcloud.io/

## Can you handle fixing this bug by yourself?
no

## Environment details
- Browser: many
- OS: many

## Additional information
Adding diffrent products (even if its only size or color diffrence) will always trigger popup. But every time we add excalty the same product we already have in cart, confirmation is not displayed

**Comment by pkarw** [comment]
Yes, there is code rule for this situation in case multiple notification with the same msg are stocked - we’re comparing the last msg when it’s exactly the same as current one no message is being shown. We probably need to change this condition to check if the prev message is still visible; if it’s not then it’s safe to show it again

**Comment by JKrupinski** [comment]
I'll try this one
