### ISSUE TITLE
Unnecesary options inside categories in hamburger menu

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2612]
Pieces of customer (my account) menu are replicated inside categories of hamburger menu, when customer is logged in.  

## Steps to reproduce the issue
1. Login to customer account
2. Open hamburger menu > Women / Men / Gear / Training

## Current behavior
Categories contains set of extra links, under their sub-categories:
Women:
- My Orders
- My Loyalty Card
- My Product Reviews 

Men:
- My Orders
- My Loyalty Card
- My Product Reviews 

Gear:
- My Loyalty Card
- My Product Reviews 

Training:
- My Newsletter
- My Orders
- My Loyalty Card
- My Product Reviews 

## Expected behavior
IMHO those links are unnecesary in hamburger menu, making it less clear. However if there is a reason to have them in menu, they shouldd be available from main menu, not stored inside categories. 

## Repository
https://demo.storefrontcloud.io/

## Can you handle fixing this bug by yourself?
no

**Comment by bartdominiak** [comment]
Yeah, it shouldn't be here, but there is one reason to keep this data inside hamburger menu - Mobile users (0-767px). So, we've 2 options:

1) Keep this data in Hamburger menu for mobile users, but move it to seperate category (like "My Account")
2) Delete this data from hamburger menu, change visibility of "My Account" button also for small devices. (currently is hidden on mobile devices)

Please @filrak can you confirm which option should we take, and I'll provide a PR for that.

**Comment by Januszpl** [comment]
@bartdominiak as far as I see it just need be removed from showing in subcategories. 
"My account" is visible in opened menu on mobile devices 
<img width="293" alt="3773b21170c93793793a15533f89713c" src="https://user-images.githubusercontent.com/7412776/54755699-4a60a900-4bc5-11e9-8b69-30ef3bd5a1e5.png">

After clicking My Account user can open it and see all this links - this is ok
<img width="552" alt="27b79b8b619975f385096968509e0018" src="https://user-images.githubusercontent.com/7412776/54755686-3fa61400-4bc5-11e9-8351-f52bfa743ff9.png">

But opening subcategory like women (other categories) shows some of this "my account" links that should be removed (not visible here)
<img width="478" alt="c6ae4fc70971a4aa1b288cfda44eaf31" src="https://user-images.githubusercontent.com/7412776/54755786-7ed46500-4bc5-11e9-8a05-035d9e7d9b11.png">
