### ISSUE TITLE
Show discount on product page

### ISSUE THREAD

**Issue by KarolaMikula** [DivanteLtd/vue-storefront#2615]
## What is the motivation for adding / enhancing this feature?

I have lower price after adding a product to the shoping cart. Would it be possible to see discount on the product page before adding to shoping cart. There is some misinformation about actual price of the product.

## What are the acceptance criteria 

- Product discount should be show on the product page

# Can you complete this feature request by yourself?
NO

## Additional information

![image](https://user-images.githubusercontent.com/48774235/54723427-cfb57080-4b67-11e9-96b8-640668b49159.png)
![image](https://user-images.githubusercontent.com/48774235/54723469-efe52f80-4b67-11e9-8b15-e777c2142fbf.png)

**Comment by Januszpl** [comment]
@KarolaMikula I guess it depends. At least in M2 we have catalog price rules where discount are visible on catalog/product pages or cart rules where discount apply only in the cart. Someone need to check how it is done in VSF. (perhaps me tomorrow)

**Comment by ArturDivante** [comment]
Take a look into #2584 

I investigated payment system there. From the cart perspective, but I belive it will give you some insight about how the prices are calculated.

**Comment by pkarw** [comment]
If there is a catalog pricing rule the discount is displayed; we can't access shopping cart rules (this particular case) to show the price after product has been added to cart

Closing for now
