### ISSUE TITLE
Unable to scroll sidebar menu

### ISSUE THREAD

**Issue by PanMisza** [DivanteLtd/vue-storefront#2627]
## Current behavior
I'm unable to scroll sidebar menu (eg. on mobile with horizontal orientation).

## Expected behavior
Scrollable sidebar menu.

## Steps to reproduce the issue
Just try to scroll on mobile with horizontal orientation.

## Repository

# Can you handle fixing this bug by yourself?
YES

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by mkaczmarekl4w** [comment]
On it

**Comment by PanMisza** [comment]
@mkaczmarekl4w 
I fixed that. I assigned myself to this task after opening it :)

**Comment by mkaczmarekl4w** [comment]
Ahh sorry @PanMisza , I didn't notice that you were working on this issue.
It's my first contribution PR, could you let me know if I done it in the correct way?

**Comment by PanMisza** [comment]
@mkaczmarekl4w 
Looks great, but we should keep the top section with close button always visible - I think it's more UX friendly.
