### ISSUE TITLE
Display red box with "You need to be logged in to see this page"

### ISSUE THREAD

**Issue by adrian-chlebowski** [DivanteLtd/vue-storefront#2631]
## Current behavior
If click "My Account" in menu then display login popup and red box with message"You need to be logged in to see this page".

![image](https://user-images.githubusercontent.com/1045581/54777042-b668fe80-4c11-11e9-9385-43b099fbd1fb.png)

## Expected behavior

Not display red box for login popup.

![image](https://user-images.githubusercontent.com/1045581/54777286-4f981500-4c12-11e9-91f1-746dc202ea42.png)

## Steps to reproduce the issue

Click menu and link "My Account".

## Repository

# Can you handle fixing this bug by yourself?

YES

## Environment details

- Browser: Chrome 72
- OS: Windows 7
- Node: 9.11.1
- Code Version: master

**Comment by pkarw** [comment]
We can probably add a config variable for the behavior here as this could be expected behavior for some users (giving the end user the context: I've clicked My account -> redirected to Login page -> this notification just answers why did this happen)

**Comment by gdomiciano** [comment]
I will start it :)

**Comment by patzick** [comment]
Thanks @gdomiciano !
