### ISSUE TITLE
Logged-in user's shipping address is not saved when placing order with registration

### ISSUE THREAD

**Issue by michhy** [DivanteLtd/vue-storefront#2636]
## What is the motivation for adding / enhancing this feature?
Customer who filled in the shipping address, and checked the box createing account, would expect the shipping address saved for future use. Even customer saved their shipping address in user > my shipping adress section on topbar, the shipping address is not copying to their checkout page. 

## What are the acceptance criteria 

- ...Save shipping address in customer's account if they chosed to register account during check out;
- ...customer saved shipping address should copy to the check out page everytime they check out.

# Can you complete this feature request by yourself?
 trying, not sure

**Comment by alinadivante** [comment]
- [ ] → Save shipping address in customer's account if they choose to register account during check out; - **fixed** 
- [ ] → customer saved shipping address should copy to the check out page everytime they check out. - **it doesn't work** Saved shipping address is not automatically copied to the checkout

**Comment by pkarw** [comment]
@iwonapiotrowska can you please take care of this one?

**Comment by pkarw** [comment]
@przspa I've assigned this issue to you if it won't be a problem?

**Comment by pkarw** [comment]
@przspa i just wanted to check the status?;)

**Comment by przspa** [comment]
@pkarw for me  

> customer saved shipping address should copy to the check out page everytime they check out. - it doesn't work Saved shipping address is not automatically copied to the checkout

is worked, I can't replicate these issues or not know how it's should work @alinadivante can you check it or tell me more about these issues

**Comment by pkarw** [comment]
@przspa the issue here is that when localStorage is cleared out the data is not being copied from data loaded from Magento (when user logs in we load `api/user/me` that should consist of addresses)
