### ISSUE TITLE
Clicking on the 'Add to Cart' button multiple times quickly for an item that wasn't previously in cart messes up the count of the cart items.

### ISSUE THREAD

**Issue by chygoz2** [DivanteLtd/vue-storefront#2639]
## Current behavior
For a product that isn't already in cart, when the **Add to cart** button is clicked multiple times quickly without changing the quantity of the item via the quantity field, the count of items in the cart is usually more than what is expected after the cart sync with the server is completed. 

If the cart is eventually converted to an order, there is also the tendency for the order to contain the same product as more than one line item.

## Expected behavior
The quantity of a product in cart should be the same as the number of times the add to cart button is clicked for that product, provided that the quantity of the product isn't changed via the quantity field.

## Steps to reproduce the issue

1. Open the product detail page of a product that isn't already in cart
2. Click the **Add to cart** button multiple times (click it at least 5 times in a second), leaving the quantity field unchanged.
3. Watch the count of the items in cart for that product

# Can you handle fixing this bug by yourself?
YES

## Environment details

- Browser: Google Chrome Version 73.0.3683.86 (Official Build) (64-bit)
- OS: Windows 10 Pro
- Node: v10.13.0
- Code Version: Master

## Additional information
Investigation revealed that this is due to the content of the request body sent to update an item's quantity on the server in the **servercartAfterPulled** action of the **cart** module. By clicking on the **Add to cart** button quickly multiple times, the request sent to the server causes the server to create the product in cart multiple times with different **server_item_id**

**Comment by pkarw** [comment]
Hi! Thanks for pointing this our, PR with a fix is more than welcome :)

**Comment by pkarw** [comment]
This should've been fixed by #2887 - can You please test it QA team? :)

**Comment by alinadivante** [comment]
@pkarw Please look at the counter on my gif.. 
![my](https://user-images.githubusercontent.com/36628922/58792490-9633c380-85f4-11e9-828c-d43ca24dccf8.gif)

**Comment by pkarw** [comment]
Fixed in the #2887

**Comment by alinadivante** [comment]
I like this solution, which disable button for one moment on click to prevent multiple submits :)
It works! I added to my cart exactly as many items as I wanted
