### ISSUE TITLE
`Sort by` on Safari

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2642]
## Current behavior

The styling is broken 
![Screenshot 2019-03-23 11 09 04](https://user-images.githubusercontent.com/211899/54864784-42873d00-4d5c-11e9-9ae3-c6eae8cfb564.png)

## Repository

# Can you handle fixing this bug by yourself?

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by patzick** [comment]
@PanMisza how is going on with this one?
Please remember to create branch for this from `release/1.9` branch:)

**Comment by haukebri** [comment]
I just fixed that - it was just a missing style.

**Comment by patzick** [comment]
Thanks @haukebri ! :)
