### ISSUE TITLE
Force sorted translations

### ISSUE THREAD

**Issue by lukeromanowicz** [DivanteLtd/vue-storefront#2657]
## What is the motivation for adding / enhancing this feature?
I suggest sorting alphabetically currently existing translations + check if they are sorted correctly in CI.

It will be easier to find which messages have missing translations and what are the new translations comparing to a previous version.

## What are the acceptance criteria 
- sort all translations with `sort` command (you can combine it with  `find` to automatically do it for you)
- add checking in CI if all translations are sorted using command from the point above combined with `sort -c (FILE)` (it returns 0 if all is sorted or 1 if there are disorders).

# Can you complete this feature request by yourself?
- [x] YES
- [ ] NO

# Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by lukeromanowicz** [comment]
What do you guys think @pkarw @patzick @filrak ?

**Comment by patzick** [comment]
most of translations are theme specific - i'd move them there and leave only core needed translations.

**Comment by lukeromanowicz** [comment]
@patzick yes, that's another issue to take care of. Do we want to do so in this issue or separate it?

**Comment by filrak** [comment]
@lukeromanowicz do you still want to take care of this?

**Comment by lukeromanowicz** [comment]
@filrak I've been very busy recently. If you would like to take it, please, go ahead.
