### ISSUE TITLE
Load more in Search Results not working

### ISSUE THREAD

**Issue by revlis-x** [DivanteLtd/vue-storefront#2659]
## Current behavior
When there are more search results then the initial batch a "Load more"-button is displayed, but clicking it does nothing. Seems vue-storefront-api response is not returning more products.

// EDIT: Problem only occurs, if you type the search term really fast (which triggers a lot of requests in short time). Request for more products then somehow has the wrong offset (e.g. from=36 instead of 18).

## Expected behavior
Load more products and append them to the list.

## Steps to reproduce the issue
1. Go to https://demo.storefrontcloud.io
2. Search for 'Shorts' (type fast)
3. Click 'Load more' button

# Can you handle fixing this bug by yourself?
NO

# Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.

https://demo.storefrontcloud.io
https://test.storefrontcloud.io
https://next.storefrontcloud.io

**Comment by patzick** [comment]
Thanks @Flyingmana!
