### ISSUE TITLE
Copy address data from shipping is not persistent

### ISSUE THREAD

**Issue by lukeromanowicz** [DivanteLtd/vue-storefront#2661]
## Current behavior
The billing address doesn't mirror changes done to the shipping address

## Expected behavior
The billing address should automatically be updated to mirror changes done to the shipping address.

## Steps to reproduce the issue
1. Add a product to cart
2. Go to checkout
3. Enter shipping address
4. Check the "Copy address" checkbox
5. Modify your shipping address
6. The billing address doesn't mirror changes done to the shipping address

# Can you handle fixing this bug by yourself?

- [x] YES but not anytime soon. Feel free to fix it
- [ ] NO

# Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 72 
- OS: Ubuntu 18.04 
- Node: 8.x 
- Code Version: master

**Comment by haukebri** [comment]
Working on this.
