### ISSUE TITLE
Subcategories order in SidebarMenu is broken after category page reload

### ISSUE THREAD

**Issue by nikblack** [DivanteLtd/vue-storefront#2665]
## Current behavior
Subcategories in SidebarMenu change order after selecting one of subcategories(not first) and  reload category page.
 It looks like selected subcategory stays in cache and after reload always displays first, ignoring real order.

## Expected behavior
Subcategories order should persist after selected subcategory's page reload.

## Steps to reproduce the issue

1. Open SidebarMenu
2. Select one of categories
3. Select one of category's subcategory (not first)
4. Select "View All"
5. Reload subcategory's page
6. Open SidebarMenu again and navigate to category from step 2
7. Compare order of subcategories after step 2 and now. Selected on step 2 subcategory became first in list. Also reproduces from deeper level of hierarchy.

Video with issue reproducing was attached.

## Repository
https://demo.storefrontcloud.io

# Can you handle fixing this bug by yourself?
- [x] NO

# Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Google Chrome (Version 73.0.3683.86), Safari (Version 11.1.2)
- OS: macOS High Sierra (Version 10.13.6)

[Vue_St_categories_nav_reload_bug.zip](https://github.com/DivanteLtd/vue-storefront/files/3018717/Vue_St_categories_nav_reload_bug.zip)

**Comment by pkarw** [comment]
This is probably related to `category/list` which is getting the list of categories from memory the second time. In both cases, we should probably add the JS (client side) sort 
- here: https://github.com/DivanteLtd/vue-storefront/blob/68fcc9e145d53f3aa3ef0e05f79abcf64bc847d6/core/modules/catalog/store/category/actions.ts#L66

- ... and here: https://github.com/DivanteLtd/vue-storefront/blob/68fcc9e145d53f3aa3ef0e05f79abcf64bc847d6/core/modules/catalog/store/category/actions.ts#L72

we should do sth like: ```
resp.items.sort((catA, catB) => {
  if (catA.hasOwnProperty('position') && catB.hasOwnProperty('position')) {
  if (catA.position < catB.position)
      return -1
   if (catA.position > catB.position)
      return 1
 }
   return 0

})
````

**Comment by pkarw** [comment]
@lukeromanowicz it's not maybe urgent - but still worth fixing :)
