### ISSUE TITLE
vue-storefront got error in lastest updates pull

### ISSUE THREAD

**Issue by rebinti** [DivanteLtd/vue-storefront#2676]
Error :

ERROR in /var/www/html/vue-storefront/core/helpers/index.ts
./core/helpers/index.ts
[tsl] ERROR in /var/www/html/vue-storefront/core/helpers/index.ts(165,33)
      TS2339: Property 'observable' does not exist on type 'VueConstructor<Vue>'.

**Comment by rebinti** [comment]
# I have switched the tags(branch) version in to v1.8.2.. Now its working fine. I think the latest version have some issues.. it's not stable now

**Comment by patzick** [comment]
Hey @rebinti, could you switch to 1.8.4 and check if problem you have appears there?
It also looks like you haven't run `yarn` command after switching versions.
Let me know if this helped you.

**Comment by rebinti** [comment]
Now I create a new local git repository (branch : vuestorefront) for this. Now I tried to build storefront in my local.. but got above error. but works fine in server.  Any idea?

**Comment by rebinti** [comment]
@patzick  I have used same repository for local and server

**Comment by rebinti** [comment]
Now in our last commit seems 

below

"remove . inactive core member ;<"

commit ID : 489eefb5a1c0d781bc48c3f7e94bc6f7735e68e7

is there any additional pull required

**Comment by pkarw** [comment]
Hi @rebinti is this issue still valid?
