### ISSUE TITLE
integration with endless-commerce

### ISSUE THREAD

**Issue by ehartford** [DivanteLtd/vue-storefront#2677]
## What is the motivation for adding / enhancing this feature?
I want to run [endless-commerce](https://github.com/endless-commerce/endless) backend with vue-storefront frontend

## Can you complete this feature request by yourself?
I don't know.  Is it possible?

**Comment by filrak** [comment]
If you want to make this integration by yourself please check this repo: https://github.com/DivanteLtd/vue-storefront-integration-boilerplate

**Comment by ehartford** [comment]
I will return when I have a contribution to this effect, thank you.
