### ISSUE TITLE
Wrong use of v-model in BaseCheckbox.vue

### ISSUE THREAD

**Issue by haukebri** [DivanteLtd/vue-storefront#2678]
## Current behavior
The change event for the checkbox never gets emitted correctly to the parent component so that when it’s used with v-model, nothing happens.

On every use of that component, the variable gets changed externally by a click event, not the v-model.

## Expected behavior
The v-model should change the variable on its own. There is no need to have a click event.

## Steps to reproduce the issue
Code example of desired result: https://codesandbox.io/s/5w6613qyzx
(remove the `$event.target.checked` and model from BaseCheckbox.vue to see the current status (not working without click event))

## Repository
https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/components/core/blocks/Form/BaseCheckbox.vue

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
I am not too sure. It's either develop or RC.

## Environment details
- Browser: Chrome
- OS: OSX
- Node: 11.10
- Code Version: develop

**Comment by haukebri** [comment]
This Merge Request is branched from develop. I think this is just an improvement, not a bug per se.

**Comment by patzick** [comment]
Great job @haukebri, this is a nice improvement!:)
