### ISSUE TITLE
Issue with #2611 - products cachig

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2682]
## Current behavior

@patzick it shouldn’t be category/products executed in beforeRouteEnter but just category/list with “updateState: false” I belive -  because category/products  executes two requests - it should just execute the second one with include/excludeFields set to null - just the caching request. The first request modified current product list which causes blinkin - confirmed on next and demo

## Expected behavior

We shouldn’t refresh the UI with this caching request we need to just load the product list and put it to localStorage

## Steps to reproduce the issue

Refresh any category page in full refresh (SSR) - it loads fine but then the product list is being immediately refreshed again

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
I belive we should replace the `category/products` calla [in here](https://github.com/pkarw/vue-storefront/blob/be69f5fec7171bf7a04f254f215c8fd19fca5095/core/pages/Category.js#L124) to [`product/list`](https://github.com/pkarw/vue-storefront/blob/be69f5fec7171bf7a04f254f215c8fd19fca5095/core/modules/catalog/store/category/actions.ts#L346) call like in two-stage caching schema.

it's important to keep:
- the filters exactly the same like in SSR (shouldn't be a problem - in SSR they're currently always empty) + sort field,
- the `includeFields` and `excludeFields` should be set to `null` 
- the `updateState` should be set to `false`

By this change we limit the number of requests to 1 and will not alter the Vuex state, therefore there will be no `blinking` efects and by the `includeFields` and `excludeFields` set to `null` we'll cache the products in the localStorage

**Comment by pkarw** [comment]
I've probably fixed it in https://github.com/DivanteLtd/vue-storefront/pull/2724 - please do check and backport if necessary or move #2611 to 1.10

**Comment by pkarw** [comment]
@ArturDivante @GabiDivante @alinadivante - please do test https://github.com/DivanteLtd/vue-storefront/pull/2724 in regards  to #2611 (not yet merged to develop)

**Comment by pkarw** [comment]
I did backport the cache prefetching to 1.9

**Comment by alinadivante** [comment]
no blinking effects on release1.9 :)
