### ISSUE TITLE
Switching between login and register form needs 2nd attempt

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2693]
## Current behavior
1. First click on 'or register an account' link is not opening registration form
2. Small validation error 'Field is required' is displayed under email field. 
3. Second click on the link will open correct form

## Expected behavior
1. Registration form should be opened on 1st click

## Steps to reproduce the issue
1. Open https://demo.storefrontcloud.io/
2. Click My Account button to open login  popup
3. Click 'or register an account' link

## Can you handle fixing this bug by yourself?
No

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Bug is reproducable on every environment, but its easiest on https://demo.storefrontcloud.io/

## Environment details
- Browser: many
- OS: Win10->

## Additional information
1. Reproducing this issue might be tricky. Refreshing page is not always enough. I had highest reproduction rate by closing and lauchning fresh browser instance - but still not 100%
2. Occasionaly, same error appears in diffrent direction - when we use 'or login to your account' link from registration popup. 

![loginRegister](https://user-images.githubusercontent.com/47415585/55733252-ca886a80-5a1d-11e9-9714-ca08b6629a7d.PNG)

**Comment by rio-karim** [comment]
Happy to take a look at this.

**Comment by SylarRuby** [comment]
> Happy to take a look at this.

How you on this? Winning?

**Comment by SylarRuby** [comment]
I'm not an expert here but I've noticed the use of `$touch()` being used on an `input` with `:validation` also with `focus`. To me, all cannot be mixed. I've removed `focus` on both `Register.vue` and `Login.vue`. See my [branch](https://github.com/SylarRuby/vue-storefront/tree/remove-focus-on-model-%232693)

**Comment by rio-karim** [comment]
> I'm not an expert here but I've noticed the use of `$touch()` being used on an `input` with `:validation` also with `focus`. To me, all cannot be mixed. I've removed `focus` on both `Register.vue` and `Login.vue`. See my [branch](https://github.com/SylarRuby/vue-storefront/tree/remove-focus-on-model-%232693)

Trying to observe the change in Auth States but doesn't seem to fire those methods when the issue throws. Does removing focus attr on the Login and Register fix this issue?

**Comment by SylarRuby** [comment]
Yes. I dont have a live demo but you can clone down my repo. Use [this branch](https://github.com/SylarRuby/vue-storefront/tree/remove-focus-on-model-%232693)

**Comment by rio-karim** [comment]
Cool stuff, don't forget to put in the PR :)

**Comment by ArturDivante** [comment]
Main problem fixed.  Good job! :)
