### ISSUE TITLE
homepage and category page load /page-not-found

### ISSUE THREAD

**Issue by wh00527** [DivanteLtd/vue-storefront#2698]
## Current behavior

When load homepage or category page. It will get a request to /page-not-found. Page will reload twice. 

## Expected behavior

Don't random load /page-not-found

## Repository

my local 

## Can you handle fixing this bug by yourself?

- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
developer

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome
- OS: MAC-OS Mojave 10.14.1
- Node: 10.2.1
- Code Version: 1.8.2

**Comment by pkarw** [comment]
Could You please make sure that this issue still occurs in the 1.8.4 / 1.9.0.rc-2? Please provide us with more information about the URL's that causes this issue etc

**Comment by dennisotugo** [comment]
@wh00527 Do you by any chance have defaultStoreCode set?
