### ISSUE TITLE
Popup login state is not reset when it is closed

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2699]
## Current behavior
After entering the login pop-up and then
  -> switching to password reset view, 
  -> closing the popup 
  -> the next time you enter the pop-up window, the password reset view opens. 
_Analogously with switching from login popup to registration view._ 

## Expected behavior
Popup state should be reset after closing.
  -> the next time you enter the pop-up window, the login view opens. 

## Steps to reproduce the issue

1. Open https://demo.storefrontcloud.io/
2. Click My Account icon to open login popup
3. Click 'Forgot the password' link
4. Close reset password popup
5. Click My Account icon to open login popup again

## Can you handle fixing this bug by yourself?

- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: many
- OS: Windows 10

**Comment by GabiDivante** [comment]
@MikeSheward This issue still appears for mobile devices. Available to check on https://demo.storefrontcloud.io/

**Comment by aniamusial** [comment]
@GabiDivante I've fixed it, PR in progress :)
