### ISSUE TITLE
Incomplete category load depending on zoom level

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2704]
## Steps to reproduce the issue
1. Open https://demo.storefrontcloud.io/ on fresh browser instance
2. Open women category
3. Adjust browser zoom level to 100%
4. Scroll category down to the moment when it should load additional products

## Current behavior
On certain zoom levels, category page wont load aditional products

## Expected behavior
Product list is updated properly on every zoom level

## Reproducibility
Bug must be related with displayed content. On my Screen (1980 x 1920) it occurs i.e. on 100% zoom level, and 75%, while on 90% and 80% additinal products load correctly

To test diffrent setups:
1. Refresh category page - it will contain only 50 products again
2. Set desired zoom level (ctrl + mouse scroll up/down)
3. Scroll down category page to the bottom

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome, Firefox, Opera
- OS: Win10

## Additional information
Similar problem in the same place (but for offline mode) was fixed in #2569

**Comment by pkarw** [comment]
I believe it's not a bug. But it needs confirmation from @patzick  The lazy loading depends on the number of visible products.

I've just checked it in zoom 50% and 100% - Women category - there is one single additional page to be loaded (and it's loaded in my case)

[The lazy loading algorithm](https://github.com/pkarw/vue-storefront/blob/be69f5fec7171bf7a04f254f215c8fd19fca5095/core/pages/Category.js#L157):
<img width="536" alt="Screenshot 2019-04-11 20 16 10" src="https://user-images.githubusercontent.com/211899/55981317-a71c2480-5c96-11e9-8adf-b003312e16de.png">

**Comment by ArturDivante** [comment]
@pkarw 
Problem is, on certain display settings (not really edge cases) additional products wont loead at all, even when you scroll down to the bottom of PLP. 

The numbers may vary. Today im testing on laptop (screen also 1920 x 1080, but diffrent size), and bugged setting are diffrent:

67% - bugged
75% - loads correctly
80% - loads correctly
90% - bugged
100% - loads correctly
110% - bugged

If needed, I can investigate more browser / zoom level combinations to provide more data. 

But despite the reason, from the user perspective (both customer and shop owner) situation, when only some products from the category are displayed (and user is not even aware of that) is not acceptable.
