### ISSUE TITLE
No visible products or categories in menu on the home page

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2705]
## Current behavior

1. After entering the homepage you will not see any products in the 'Everytihng new' section. 
2. After expanding the hamburger menu, the product categories are not visible.

## Expected behavior

1. After entering the homepage you will see eight products in the 'Everytihng new' section. 
2. After expanding the hamburger menu, the product categories are visible (Women, Men, Gear, Training).

## Steps to reproduce the issue

1. Open https://test.storefrontcloud.io/
2. Click on hamburger menu to see products categories
3. Close hamburger menu
4. Scroll down home page to 'Everything new' section

## Can you handle fixing this bug by yourself?

- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome
- OS: Windows 10

## Additional information

You can get to the product list by clicking on any category on the home page (Office casual, Shine on, Spring is coming). 
If you then go to the main page, invisible products and part of categories in the menu will appear (those you have previously visited).
So this bug can be reproduced only by going to the website with the cleared cache.

**Comment by pkarw** [comment]
This issue was related to wrongly cached state of `test.storefrontcloud.io`. I've rebuilt `test-storefrontcloud-io` instance

**Comment by alinadivante** [comment]
@patzick @pkarw we have again the same problem on test

**Comment by pkarw** [comment]
Looks like the database needs to be restored @patzick

**Comment by pkarw** [comment]
@patzick by some reason all the API requests returns 502 error on test.storefrontcloud.io/api

**Comment by pkarw** [comment]
Will be fixed by @patzick with the next deployment. Closing for now - this is no software bug
