### ISSUE TITLE
Problem with Magento 2 Tier Pricing

### ISSUE THREAD

**Issue by Ale763** [DivanteLtd/vue-storefront#2708]
## Current behavior

When working with Magento 2 Tier Pricing I noticed the correct price for a given customer group is shown, **only when the item is added to the cart** (not in the catalog or product detail page). 

Also when updating the price in Magento, there is some very buggy behaviour. Everything seems to work just fine, till you are offline. When you are offline and add the product, whose price has changed, to the cart, the old price is shown. I checked with the vue developer plugin in chrome to inspect the state of the product (vuex bindings - originalProduct) and it turns out it still has the old price. Also I don't see any of the Tier Prices.

## Expected behavior

- Tier Prices change and show based on customer group
- Price update is reflected on all the pages (old state has to be refreshed)

## Steps to reproduce the issue

I used 2 Customer Groups for the product "Joust Duffle Bag". 
The product had 3 prices:
- Default: 90
- NOT LOGGED IN: 50
- VS: 20
Then I changed the prices:
- Default: 100
- NOT LOGGED IN: 60
- VS: 30

1. Open the product while not logged in (only new default price is shown in catalog)
2. Add item to cart (in cart correct new price is shown for group NOT LOGGED IN)
3. Log in with an account from the group VS
4. Product has new default price is in catalog (correct new price again only in cart)

I tried the same, both logged in and not logged in, but this time while offline. This time I got the old default price of 90 (which was the only state I could find about the product with the Vue Developer extension in Chrome).

## Can you handle fixing this bug by yourself?
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome, Brave, Chrome Canary
- OS:OSX Mojave
- Node: 6.9.0
- Code Version: 83dbcfff1eac27ae0606debcb0cf1f97c7a86aed

**Comment by pkarw** [comment]
Hi there! By default tier prices are disabled by the default config. Please make sure You've got it enabled - reference config line: https://github.com/pkarw/vue-storefront/blob/be69f5fec7171bf7a04f254f215c8fd19fca5095/config/default.json#L414

**Comment by Ale763** [comment]
I followed the documentation to enable them. I have all prices synced with Magento.

**Comment by pkarw** [comment]
OK, thanks for the info. @mdanilowicz could You please take a look at this issue?

**Comment by Ale763** [comment]
I forgot to mention the problem resolves itself after doing a new import, but that can't be a valid solution. Prices can be changed quite often and it's not always possible to do a full import. Right?

**Comment by pkarw** [comment]
Hi @Ale763 please do try [delta indexer](https://github.com/DivanteLtd/mage2vuestorefront#delta-indexer)

**Comment by Ale763** [comment]
I can't test it right now. I'll do it this afternoon. How would I automate it? Shouldn't this be done automatically after a price change?

**Comment by pkarw** [comment]
Please read the mage2vs on ondemand indexer, delta indexer (that can be set in crontab) + take a look at the: https://github.com/DivanteLtd/magento2-vsbridge-indexer

**Comment by pkarw** [comment]
I'm closing the issue for now let me know if the problem still exists so it need to be reopened @Ale763

**Comment by Ale763** [comment]
Sorry I haven't had the time to test it on friday. I'll certainly do it tomorrow.

**Comment by Ale763** [comment]
I'm having issues installing the indexer. Any ideas?
![image](https://user-images.githubusercontent.com/13874391/56111024-d496f580-5f56-11e9-9509-3da042839db8.png)

**Comment by Ale763** [comment]
I'm having trouble installing the indexer. I had to configure Magento to use elasticsearch 5.4.0 instead of Mysql. Now I get an error `Incorrect theme identification key` when running `bin/magento setup:upgrade`. Any suggestions?
![image](https://user-images.githubusercontent.com/13874391/56130214-96182f80-5f84-11e9-840b-59c37e4137d8.png)

**Comment by Ale763** [comment]
I think I figured out why the Tier Prices are not showing correctly. The call to retrieve the product data on the product page (`V1/products-render-info?searchCriteria=&searchCriteria[filter_groups][0][filters][0][field]=sku&searchCriteria[filter_groups][0][filters][0][value]=24-MB01%2C&searchCriteria[filter_groups][0][filters][0][condition_type]=in&storeId=1&currencyCode=USD` - don't mind the actual values) is being made with the Magento Guest REST API, this means the call is being made as a user that is not logged in (anonymous user). That's why the price for the "NOT LOGGED IN-users" was showing earlier (60$). I changed the group from NOT LOGGED IN to general and suddenly the regular price was showing (100$).

As I see it there could be 2 solutions:
- If the API supports it, an additional parameter should be added to reflect the customer group. This way the correct price for the customer group should be returned by the Magento API.
- The data should be retrieved in a different way (e.g. all the product data can be retrieved with the SKU). This returns all the data for the product (which could be too much, but makes it possible to choose the correct data)
