### ISSUE TITLE
Picture doesn't change when switching between the product's color variants

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2709]
## Current behavior

Browsing the color versions does not change the image of the product.

## Expected behavior

Browsing the color versions changes the picture of the product (selected  color version is shown in the picture).

## Steps to reproduce the issue

1.  Go to https://test.storefrontcloud.io/
2. Click on category link Office casual 
3. Go to any product page
4. Click on any other product colour version

## Can you handle fixing this bug by yourself?

- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome
- OS: Windows 10

**Comment by pkarw** [comment]
I can confirm the issue on test (however it apparently doesn't exist on next and demo instances):
<img width="474" alt="Screenshot 2019-04-11 20 06 57" src="https://user-images.githubusercontent.com/211899/55980794-84d5d700-5c95-11e9-8823-12882e178087.png">

Maybe we should start with restoring the most recent database dump first

**Comment by GabiDivante** [comment]
@pkarw there is still a problem with changing pictures for colors but only when you choose a different size than xs

**Comment by pkarw** [comment]
I belive it's not yet been deployed. Or maybe have You checked it locally?

**Comment by GabiDivante** [comment]
@pkarw  Yes, I checked it locally on branch bugfix/2709

**Comment by pkarw** [comment]
OK, it needs to be re-checked by @patzick then
