### ISSUE TITLE
mage2vs cannot import magento 2.3.1 data 

### ISSUE THREAD

**Issue by michhy** [DivanteLtd/vue-storefront#2711]
## Current behavior

In local machine I have magento 2.3.0 installed and data can be imported smoothly by running mage2vs to VSAPI. 
However in server I have magento 2.3.1 installed and it always return 'API call failed: The consumer isn't authorized to access Magento' for all the datas.
I tried to turn on 'store > configuration > services > magento API > Allow Anonymous Guest Access', and succeed to import categories and productcategory, not the others.

It looked to me magento did not regconize mage2vs is not guest, not recognizing the keys tokens. (I have checked more than hundred times that the 4 keys tokens are correct)

## Expected behavior

Import all required data from magento 2.3.1 rest API smoothly

## Steps to reproduce the issue

Try fetch data from a magento 2.3.1 rest API

## Can you handle fixing this bug by yourself?

- [ ] YES
- NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
Hi there! Could You attach a screen of Your Magento integration setup - the Permissions tab for this enabled integration?

Please do also paste the vs-api config / magento2 section for double checking the config.

We haven’t observed this kind of problems on 2.3 - the only thing that wasn’t working properly was MSI support

**Comment by michhy** [comment]
Dear Piotr,
Here's the screencaps:
#1 all the other check boxes are clicked
![螢幕截圖 2019-04-12 下午12 43 47](https://user-images.githubusercontent.com/37435427/56012993-6c130300-5d21-11e9-9939-6e653f9ce0eb.png)

#2 vs-api local.json
![螢幕截圖 2019-04-12 下午12 47 14](https://user-images.githubusercontent.com/37435427/56013020-84831d80-5d21-11e9-928c-6ad44ad5d453.png)

#3 try running mage2vs/src/test_multistore.sh
![螢幕截圖 2019-04-12 下午12 46 52](https://user-images.githubusercontent.com/37435427/56013041-9cf33800-5d21-11e9-8cd9-81be0d50530e.png)

Thank you!

**Comment by pkarw** [comment]
Hi, the error message points to invalid permissions to "Categories" resource - on the screen i don't see categories checked (due to limited screenshot area I belive) - make sure it's been checked along with the "Sales" section

**Comment by michhy** [comment]
Dear Piotr,

No no, I tried to check all and still give the same error. (I've been fighting with this error for whole day and pretty sure its not becoz I missed checking boxes)

I just installed a fresh 2.3.0 magneto on server, and everything works fine again.

It must dealing with some fixing in RestAPI of 2.3.1.

See anyone have tried the same situation.

**Comment by mdesmet** [comment]
Hi Michhy, I'm on magento 2.3.1 and have no problems with permissions as you have.

**Comment by michhy** [comment]
Dear Mdesmet
Thanks, I will try installing 2.3.1 again and test later.
