### ISSUE TITLE
ES Queries silently ignore connection errors

### ISSUE THREAD

**Issue by lukeromanowicz** [DivanteLtd/vue-storefront#2712]
## Current behavior
The error that is thrown while connecting to ES is silently ignored. It works fine for offline mode but also makes debugging extremely hard i.e. when the SSR does not have access to vhost of API

https://github.com/DivanteLtd/vue-storefront/blob/159357fba37e1c9eecc1c4f128120d6964a64f24/core/lib/search.ts#L86-L114

## Expected behavior
Some sort of debug information should be thrown in SRR when there is connection error while reaching querying ES

## Steps to reproduce the issue

* set address of ES to be a vhost
* enter a random page with empty SSR cache
* SSR will try to reach ES but it will throw ENOTFOUND that is not showing up in any logs.

## Can you handle fixing this bug by yourself?

- [x] YES, but not anytime soon. Fill free to fix it
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by lukeromanowicz** [comment]
The issue is caused by using logger that is muted on SSR, now the question is - what do we do about it? @pkarw @filrak 

https://github.com/DivanteLtd/vue-storefront/blob/159357fba37e1c9eecc1c4f128120d6964a64f24/core/lib/logger.ts#L68-L78

**Comment by pkarw** [comment]
@lukeromanowicz it's safe to let the debug messages pop up in SSR as long as there is no production mode on

**Comment by lukeromanowicz** [comment]
Will be fixed in #2717
