### ISSUE TITLE
Infinite loop on multi-store site after Account page reload

### ISSUE THREAD

**Issue by grimasod** [DivanteLtd/vue-storefront#2713]
## Current behavior

Reloading any my-account url on a multi-store site causes an infinite redirect loop and constant requests to the server

## Expected behavior

A single reload

## Steps to reproduce the issue

1. In a browser tab, go to https://demo.storefrontcloud.io/de/
2. Login (roni_cost@example.com, roni_cost3@example.com)
3. Navigate to any Account page, eg My Orders
4. Reload the page using the browser Reload button
5. Observe the infinite reload

Make sure to close the browser tab to prevent server overload!

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

Well, maybe. I'm trying but haven't found a proper fix yet and don't have any more time today.

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 73
- OS: Mac OS
- Node: 8.11.4
- Code Version: 1.8.4, 1.9

## Additional information

The problem is in vue-storefront/core/modules/user/router/beforeEach.ts
```
next('/')
setTimeout(()=> {
  router.push(to.path)
}, 0)
```

Redirecting to '/' on a multi-store site always causes problems. I'm not sure exactly what's happening here, but I'm pretty sure this is where the problem is.

In this case, the current store is not set at this stage, so using `localizedRoute('/', currentStoreView().storeCode)` is not useful.

**Comment by pkarw** [comment]
We should probably move this redirect to `beforeResolve` as `storeCode` is checkd in `client-entry.js` beforeResolve as well; https://github.com/pkarw/vue-storefront/blob/be69f5fec7171bf7a04f254f215c8fd19fca5095/core/client-entry.ts#L85

The other option is to add the module based hook after the app is ready (multistore set, translations loaded etc) - currently we don't have an option to bind to such an event @filrak @patzick

**Comment by alinadivante** [comment]
@patzick on https://next.storefrontcloud.io/de/my-account still user is redirect to Home page

**Comment by pkarw** [comment]
@alinadivante if only with Ctrl+f5 - page refersh, then fine. If the redirect occurs while clicking the option in menu (CSR) then it's a bug. My account IS NOT supported in SSR

**Comment by alinadivante** [comment]
@pkarw it works perfect now on https://next.storefrontcloud.io/my-account so @patzick will improves it also for https://next.storefrontcloud.io/de/my-account

**Comment by pkarw** [comment]
OK :)

**Comment by patzick** [comment]
Corrected in newest RC deploy:)

**Comment by alinadivante** [comment]
nice! :) thanks @patzick
