### ISSUE TITLE
User account menu is displayed as a subcategory - wrong level

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2725]
## Current behavior

![Screenshot 2019-04-14 09 44 14](https://user-images.githubusercontent.com/211899/56089880-1c0b7c00-5e9a-11e9-813c-21d1492c4a22.png)

## Expected behavior

This menu should be displayed at Sidebar's root level only
## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by ArturDivante** [comment]
@pkarw issue was already reported, fixed and merged in 1.10.0-rc.1  :)
#2612 
#2625
