### ISSUE TITLE
Enable the price ranges to be configured in local.json

### ISSUE THREAD

**Issue by kirillreo** [DivanteLtd/vue-storefront#2728]
I need to use price range as custom.
For example:
0-1000,
1000-5000,
5000-25000,
Now price range in code is hardcode
0-50
50-100
100-150
150-

There is that hardcode:

[core/lib/search/adapter/api/elasticsearchQuery.js](https://github.com/DivanteLtd/vue-storefront/blob/master/core/lib/search/adapter/api/elasticsearchQuery.js)
`  // Add aggregations for catalog filters
  const allFilters = searchQuery.getAvailableFilters()
  if (allFilters.length > 0) {
    for (let attrToFilter of allFilters) {
      if (attrToFilter.scope === 'catalog') {
        if (attrToFilter.field !== 'price') {
          let aggregationSize = { size: config.products.filterAggregationSize[attrToFilter.field] || config.products.filterAggregationSize.default }
          query = query.aggregation('terms', getMapping(attrToFilter.field), aggregationSize)
          query = query.aggregation('terms', attrToFilter.field + optionsPrfeix, aggregationSize)
        } else {
          query = query.aggregation('terms', attrToFilter.field)
          query.aggregation('range', 'price', {
            ranges: [
              { from: 0, to: 50 },
              { from: 50, to: 100 },
              { from: 100, to: 150 },
              { from: 150 }
            ]
          })
        }
      }
    }
  }`

How can I make price ranges as custom?

**Comment by pkarw** [comment]
Hi there! Good point. It’s a pretty cool idea for a new feature and contribution; happy to merge it to the core
