### ISSUE TITLE
Selected filters are reset - after going to the product page and then going back to the products list

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2732]
## Current behavior

If I choose some filters (for example red, size s) and 
-> then go to the product page 
-> then after going back to the list of products **choosed filters are not remembered.**

![Selectedfiltersarereset](https://user-images.githubusercontent.com/49188852/56129477-797af800-5f82-11e9-8e7e-3e99fdf81ecf.gif)

## Expected behavior

If I choose some filters (for example red, size s) and 
-> then go to the product page 
-> then after going back to the list of products **earlier  choosed filters are remembered.**
**So I can continue to browse the list of products that interest me.**

## Steps to reproduce the issue

1. Go to https://demo.storefrontcloud.io
2. Open hamburger menu and go to Women category -> View all
3. Select filters - for ex: color - red, price - $50-100
4. Choose any product - go to product page
5. Go back to the products list

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 73
- OS: Windows 10

**Comment by pkarw** [comment]
This has just been fixed by #2724 (it’s waiting for being merged to develop and deployed to test)
