### ISSUE TITLE
Showing number of available products 

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2733]
## What is the motivation for adding / enhancing this feature?

When a customer wants to order several pieces of a given product, for ex 10, and this quantity is not available - he must try one by one to determine how many items he can order. 

![Showingnumberofavailableprod](https://user-images.githubusercontent.com/49188852/56132412-302ea680-5f8a-11e9-8b19-4969f74acaa1.gif)

In the message about the lack of a product:
_"We don't have as many "product-name" as you requested"_
we can add the information _"We currently have: (available quantity)"_.
Thanks to this, the customer will know how many pieces he can order

## What are the acceptance criteria 

- [ ] When I try to add an unavailable quantity of product to the shopping cart, a message appears: _"We don't have as many "product-name" as you requested. We currently have: (available quantity)"_.

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
The number should be taken from the stock/check view action - asynchronously called after entering the product page. We should not take it from the elasticsearch as there is no guarantee it’s got a current value

**Comment by collymore** [comment]
This has been fixed in today's hackathon, will get the PR done shortly

**Comment by lukeromanowicz** [comment]
@collymore How it's going with the fix?

**Comment by pkarw** [comment]
I think we should just add a label like: "Quantity (50 available)" by the input field. It should be taken from the `stock/check` request
