### ISSUE TITLE
How to make apk for Vue-Storefront? Is there any straight forward way to make it?

### ISSUE THREAD

**Issue by ArnabBanerjee** [DivanteLtd/vue-storefront#2734]
## What is the motivation for adding / enhancing this feature?

I have tried to convert it by using 'Native-Vue' and got success 90% as Current Version of Native-Vue(2.0) only support manual routing so I have changed the vue storefront routing section. so is there any straight forward way then it will be much easy to convert to apk and time saving also
## What are the acceptance criteria 

- [
 1. Maintain single version of code for web, apk
 2. single command build
 ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by lukeromanowicz** [comment]
Cordova is probably a way to go in this case

**Comment by ArnabBanerjee** [comment]
I have never used Cordova, so it is possible to make vuestore front apk using Cordova.Thanks for the help, if I face any difficulty to make make the apk then is it ok if I ping you again?
 
 
  On Tue, 16 Apr 2019 at 1:21 PM, Łukasz Romanowicz<notifications@github.com> wrote:   
Cordova is probably a way to go in this case

**Comment by lukeromanowicz** [comment]
Me neither :-)  I've just heard from a few colleagues in the past that it's a reliable solution when it comes to converting SPA to android/ios app.

**Comment by Jensderond** [comment]
Maybe this could help.
https://docs.pwabuilder.com/jekyll/update/2018/02/03/how-to-package-android.html

**Comment by mkastaneda** [comment]
Would like to share our experience with this.

We have deployed a Magento 1/VueStrorefront instance for a large eCommerce retailer México under an Apache Cordova mobile app  (Android/IOs) . The PWA is traditionally mounted on a web server (node/yarn) which the app basically fetches the PWA content on a WebView iframe and the native Cordova side interacts directly with the PWA through postMessages for features like: bar code scanner and push notifications with Firebase. Works fine, except that if the PWA is down, the app is down too. (we loaded an offline static version of the PWA with wget, which is loaded in case server conection fails, workaround ...)

We are considering moving the PWA within the apk bundle, meaning a serverless PWA emdeded in the app's WebView. The only chalenge here is to get the PWA to build locally and generate all the required assets under the cordova project so it can be rendered locally.

This is the architecture so far (sorry but it's in Spanish):

![image](https://user-images.githubusercontent.com/13582943/85799129-55798180-b704-11ea-8bee-9c772ccb08dd.png)
 
During my research, found these:

**CordoVue:**
https://vuejsfeed.com/blog/cordovue-apache-cordova-app-with-vue-js

**Cordava + Vue + Webpack:**
https://itnext.io/make-hybrid-platform-cordova-vue-webpack-2fb7031c4f9b

Before making further tests, do you guys think this is possible ?

From a theoretical point of view, I think it is. Would these tools correctly build the PWA ? Any **risks** that you see here ? at the end is about the generate the required HTML/Javascript/CSS files so you can bundle it on the Cordova project and get executed by the browser. Which is what basically cross-env/yarn/webpack do.

Any ideas are well appreciated.
