### ISSUE TITLE
Unexpected window.localStorage use in user module actions

### ISSUE THREAD

**Issue by Zulcom** [DivanteLtd/vue-storefront#2735]
## Current behavior

https://github.com/DivanteLtd/vue-storefront/blob/6a81be54dc088654b717d0cc624a90acf487a489/core/modules/user/store/actions.ts#L17-L23

## Expected behavior
Don't break abstraction level, use `Vue.prototype.$db.usersCollection`

## Steps to reproduce the issue

1. Set default driver for user storage as `INDEXEDDB`
2. Set breakpoint to referenced code line
3. Make user register action
4. See how action tries to get current-user from localStorage instead of expected `INDEXEDDB`

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Opera 60
- OS: Windows 10 x64
- Node: 10.15.3
- Code Version: develop c5d6e8a

**Comment by pkarw** [comment]
Thanks! In fact It should be changed
