### ISSUE TITLE
Ordering 'out of stock' products in offline mode - error

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2740]
## Related issues
#2044

## Steps to reproduce the issue
1. Go to https://demo.storefrontcloud.io/
2. Open women category
3. Turn to **offline mode**
4. Open https://demo.storefrontcloud.io/p/WT06/chloe-compete-tank/WT06 (example of a product we know is out of stock by default)
5. Add Product to cart in  blue/XS (default) version (example of out-of-stock product version)
6. Go to checkout and place an order - it will be put on hold until you come back online
7. Turn to online mode again

## Current behavior
1. Success page is displayed - user is informed, **that order was successfully placed**
2. Group of 500 errors is displaye in console
3. Order is not placed

![Offline Order 0](https://user-images.githubusercontent.com/47415585/56195631-a20ffa00-6035-11e9-84cc-94c0b8683a9a.PNG)
![Offline Order 1](https://user-images.githubusercontent.com/47415585/56195632-a20ffa00-6035-11e9-914a-21eb1fcc1027.PNG)
![Offline Order 2](https://user-images.githubusercontent.com/47415585/56195633-a2a89080-6035-11e9-8897-6f7010d95499.PNG)

## Expected behavior
Assuming its impossible to check stock status before, we should at least display proper error message on front - currently user is convinced, that he placed an order. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: many
- OS: Win10

**Comment by pkarw** [comment]
As for now we should better handle the ThankYouPage + display the proper error message in that case

**Comment by lukeromanowicz** [comment]
@pkarw extracting order synchronization to a visual layer and notifying a user about successful/unsuccessful order placement when he's back online would be a great feature and simplify solutions to a lot of similar issues to this one. Same goes for products that have additional business validation, invalid address fields, expired coupons etc. If you think it's a viable set of features then we should extract that to a separate FR, I belive.

**Comment by pkarw** [comment]
@lukeromanowicz yes, that makes perfect sense to me. We should have this kind of general error handler in here. So I belive you could create such a feature request and maybe close this issue with it

**Comment by lukeromanowicz** [comment]
@pkarw I elaborated my idea in #2753. If it's similar to what you have in mind

**Comment by pkarw** [comment]
As a workaround for currently not having the #2753 implemented  we can use the Popup UI from the https://github.com/DivanteLtd/vue-storefront/tree/master/core/modules/offline-order - to just display the details of the order that can't be sent from the queue. In case of any of validation / server error we should just to:
-  display the order details + validation / stock / other error messages we got from the `vue-storefront-api`
- remove it from the queue (for not being processed by https://github.com/DivanteLtd/vue-storefront/blob/76a75759550ec2b7dd9642eb3b281566c1590dc5/core/client-entry.ts#L171).

Then we can deal with #2753 and optimize the UX
