### ISSUE TITLE
Validation of fields 'company name' and 'tax' in checkout doesn't work correctly

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2741]
## Current behavior

Filling the form after marking checkbox "I want to generate an invoice for the company" always results in the validation message "Field is required":
-> each time for field "company name" 
-> and when trying to fill in the "tax" field - if it was left empty before. 
As a result, you can't go to "Review Order".

![companyname_tax_validation](https://user-images.githubusercontent.com/49188852/56196806-d97fa600-6037-11e9-9932-9b641777f2a0.gif)

## Expected behavior
Validation of fields "company name" and "tax" is working correctly:
-> if correct data were provided there is no validation message shown,
-> if field was left empty or wrong data were provided - validation message is shown.

## Steps to reproduce the issue

1. Go to https://test.storefrontcloud.io
2. Add any product to the cart
3. Go to checkout
4. Provide personal deatils
5. Continue to shipping and provide shipping details
6. Continue to payment
7. Provide address data
8. Mark checkbox "I want to generate an invoice for the company"
9. Fill in the form by providing correct company name and tax number
10. Unmark checkbox and mark it again
11. Click on company name field, leave it empty and then click on tax number field and also leave it empty
12. Fill in the form by providing correct company name and tax number

## Can you handle fixing this bug by yourself?

- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 73
- OS: Windows 10

**Comment by pkarw** [comment]
Related to #2742

**Comment by dimasch** [comment]
I checked on `Chrome 74` and `Windows 7`. Not reproduce, worked as expected.
![checkout-validation](https://user-images.githubusercontent.com/414067/57321333-28d66500-7112-11e9-9fdf-7bdaebf3695d.gif)

Possible need exactly `Windows 10`

**Comment by pkarw** [comment]
@dimasch Please test it out on 1.10 (develop branch) - it supposedly occurs only there

**Comment by dimasch** [comment]
@pkarw  Yes, on develop branch reproduced.
I will to fix it.
![2019-05-08_10-35-39](https://user-images.githubusercontent.com/414067/57354693-383ec800-717d-11e9-9f3d-e9bcdff83e19.png)

**Comment by pkarw** [comment]
OK cool. Please make sure the checkboxes in the `My Account` (all sections) work properly as well. I'm affraid there was a change regarding BaseCheckbox.vue that involves thsese kind of issues

**Comment by dimasch** [comment]
Reproduced on `Chrome 74`, `MacOS` (not depends on OS)

**Comment by dimasch** [comment]
@pkarw PR ready!

**Comment by patzick** [comment]
Thanks @dimasch ! :)

**Comment by GabiDivante** [comment]
@dimasch I checked the changes, now everything works fine when filling in the form, but I still get this problem when I choose the option **"Copy address data from shipping"** - please check that. 
Also, the related problem appears for selecting "use my billing data" - described in a comment for issue #2730
