### ISSUE TITLE
Order ID displayed in 'My orders' identical to the order ID in Magento

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2743]
## What is the motivation for adding / enhancing this feature?

Currently, order ID displayed in 'My orders' is different from order ID in Magento. It is confusing for the customer when he sees one order ID in 'My orders' and gets a different one in the email order confirmation from Magento. 

## What are the acceptance criteria 

- [ ] Order ID displayed in My orders is the same as in Magento Orders list.

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by GabiDivante** [comment]
@mdesmet @pkarw we need to add the correct Order ID on the order summary page as well
![Selection_027](https://user-images.githubusercontent.com/49188852/57541555-928f8280-734f-11e9-8a5c-096b32bd9deb.png)

**Comment by mdesmet** [comment]
HI Gabi, I mentioned that open issue on the fix indeed. I'll have a look at it tomorrrow, must be not too hard to fix.

**Comment by GabiDivante** [comment]
@mdesmet Great! Thank you :)

**Comment by pkarw** [comment]
@mdesmet please just change the orderData.entity_id to orderData.increment_id and You’re there

**Comment by mdesmet** [comment]
@pkarw : from what I remember it was more complicated, the magento api returns only the internal id (see o2m.js).

**Comment by pkarw** [comment]
You might be right...

**Comment by mdesmet** [comment]
I don't really have time now to solve it right now, working on another project but here is my analysis:

We would have to extend the magento2-rest-client with support for retrieving the order based on the increment id returned by the order creation endpoint. See this Stack exchange with the solution: https://magento.stackexchange.com/questions/210000/retrieve-entity-id-from-rest-api-using-order-id

Then we can call this api in the o2m.js and change the bakendOrderId to the correct order id.

**Comment by Flyingmana** [comment]
shouldnt this be more of a cosmetic then a functional change?
vue-storefront is intended to connect with different systems, and its common that an Order has an entity ID, but exposes a different ID to the customer, which often allows more flexibility.

So it may make sense, that vue-storefront adds a new property to differentiate between entity_id and shown order_id

**Comment by mdesmet** [comment]
I wish it was just a cosmetic change but the response from the order endpoint only returns the internal increment id, no other properties, so we have to get the external order id somewhere else. IMHO the analysis still stands.

**Comment by patzick** [comment]
Thanks @Flyingmana !

**Comment by GabiDivante** [comment]
@Flyingmana I'm testing this solution on the branch develop and still order id on the thankyou page is different than in my orders

**Comment by patzick** [comment]
i've spoken with Gabi, i merged that to separate branch to faster merge that huge abount of PRs, no worries here :)

**Comment by mdesmet** [comment]
@patzick: I meant to comment on this one, actually this change doesn't work as orderData.increment_id is not defined at that point. We have to fetch it from magento api. @Flyingmana  is on it already.

**Comment by Flyingmana** [comment]
added this fetch via https://github.com/DivanteLtd/vue-storefront-api/pull/258

**Comment by alinadivante** [comment]
@Flyingmana could you look at this feature request #3082  ? :)
