### ISSUE TITLE
Shipping charge remains unchanged after selecting different shipping method on checkout

### ISSUE THREAD

**Issue by michhy** [DivanteLtd/vue-storefront#2744]
## Current behavior

I hv activated two shipping method in magento, in vsf it display the two shipping methods correctly. However when selecting the non-default one, the shipping cost above the total does not change.
When proceed to payment it selected the default shipping method again.

** I tried to add '.native ' at line 88 shipping.vue
(@change="$v.shipping.shippingMethod.$touch();)
like how you guys fixed shipping country bug, but no luck.

## Expected behavior

Shipping charge changes upon shipping method selection

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
Thanks for pointing this out! Please select on which version have You got this issue: demo/next/test?

**Comment by michhy** [comment]
I am debugging base on 1.8.3, with magento 2.3.0. 

I checked by console.log the 'currentShippingMethod' variable in vsf/core/modules/checkout/components/shipping.ts,  the shipping method is not changed by the @change function by selection (changeShippingMethod triggered from theme/compoents/core/blocks/Checkout/Shipping.vue), it still showing the default selected shipping method.

**Comment by pkarw** [comment]
Could you Please check 1.8.5 and 1.9.0? There were fixed around shoppingu methods i guess

**Comment by michhy** [comment]
Hello, 
Sorry I found out I have forgotten to add the method to local.json in vue-storefront/config.
I did update my code upon to the newest version. 

Sorry for the trouble! 
Thanks a lot!

**Comment by michhy** [comment]
something to add before I close this issue.
I found out the bug due to vuetique theme, shipping.vue
i changed the radio button code to default theme's one and it works again.

**Comment by pkarw** [comment]
Thanks! Could you please create an issue in the https://github.com/AbsoluteWebServices/vuetique-theme? Thanks a lot!

**Comment by michhy** [comment]
Sure sure!
