### ISSUE TITLE
how to define categories in sidebarMenu.vue

### ISSUE THREAD

**Issue by hosseinmirhosseini76** [DivanteLtd/vue-storefront#2748]
## Current behavior

categories: [{
        id: 13,
        parent_id: 11,
        name: 'Bottoms',
        is_active: true,
        position: 2,
        level: 3,
        product_count: 0,
        children_count: 2,
        children_data: [
          {
            id: 18,
            parent_id: 13,
            name: 'Pants',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 156,
            children_data: []
          },
          {
            id: 19,
            parent_id: 13,
            name: 'Shorts',
            is_active: true,
            position: 2,
            level: 4,
            product_count: 148,
            children_data: []
          }
        ],
        tsk: 1505573191094
      }
      ]

I put this in data section in my sidebarMenu.vue, but it show only the first level of it!

how could show my categories in sidebar?

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
Please take a look at the https://github.com/DivanteLtd/vue-storefront/pull/2100

You could turn off dynamic categories prefetching Or return the subcategories from the backend (if dynamic prefetching is enabled)

By default VS is querying Elastic Search when You click the category to get subcategories for this parent one.

**Comment by hosseinmirhosseini76** [comment]
So, how can I "turn off dynamic categories"?

and where should initialize the categories?

**Comment by pkarw** [comment]
Hey! Please do check the description and code changes of  the PR https://github.com/DivanteLtd/vue-storefront/pull/2100

We don’t have any better docs on that yet :-/
