### ISSUE TITLE
After logging in when placing an order, products previously added to the basket are automatically added to the current order

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2749]
## What is the motivation for adding / enhancing this feature?

Currently, a customer who:
-> added selected products to the basket,
-> went to checkout,
-> then logged in to his account (from the personal details step)
has automatically added to the current order, **products that were previously in his basket** (which he added to the cart during the previous visit).
The customer may purchase more products by mistake. To remove unwanted products, he must go back to the cart and then go back to the checkout again.

## What are the acceptance criteria 

- [ ] When the customer logs in when placing an order - the products previously added to the cart are not added to his order.

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
cart/serverPull shouldn’t be called after user logs in in the checkout (otherwise it should work as it is right now without changes)
