### ISSUE TITLE
'Instant checkout' sends doubled names and adresses

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2750]
## Steps to reproduce the issue
1. Go to https://test.storefrontcloud.io/
2. Add any product to cart
3. Open cart
4. Click 'Instant checkout' and fill necessary data
5. Send order
6. Check confirmation mail
7. Check order details in magento

## Current behavior
Data send with order contains doubled first name, last name and adress line 

![magento](https://user-images.githubusercontent.com/47415585/56295050-702d8f00-612c-11e9-9ee4-59e697edc37c.PNG)
![mail](https://user-images.githubusercontent.com/47415585/56295051-702d8f00-612c-11e9-97db-42e6ff00089d.PNG)

## Expected behavior
Order is send with correct data

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome
- OS:  Win10

## Additional information
Orders placed with the same data but trough regular checkout, don't cause this problem

**Comment by kipotlea** [comment]
Hi @ArturDivante , what VSF version do you use on this https://test.storefrontcloud.io ?
