### ISSUE TITLE
New zoom effect for product gallery images.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2755]
## What is the motivation for adding / enhancing this feature?
 Someone wrote that product detail image zoom functionality is not ux friendly. 
We could change the zoom so that users can see a larger zoom, more details of the image, using a magnifier icon. See example:
![image](https://user-images.githubusercontent.com/36628922/56338739-90506300-61ab-11e9-8825-f916ce945c66.png)

## What are the acceptance criteria 
User should see every details of product.
To displaying zoomed image just hover mouse on image.

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by MikeSheward** [comment]
I'll have a go at this !
