### ISSUE TITLE
Inconsistent behaviour of picture slider od PDP

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2757]
## Current behavior
Picture slider mechanism needs to be triggered by 1st use of side arrows icons. Until then, clicking on color buttons or small icons in the bottom of the picture, will result in simple picture swtich, without sliding animation. After first use, every method of picture browsing will be using sliding animation.  

## Expected behavior
When using arrow buttons - animation should always be played
When using color icons - pictures should always be switched without animation

## Steps to reproduce the issue
1. Go to https://next.storefrontcloud.io/
2. Open procudt page with few pictures available
3. Switch between pictures using color icons
4. Switch between pictures using arrow icons on the sides
5. Now again switch between pictures using color icons (or small circle icons in the bottom)

See the video:
![Slider Trigger](https://user-images.githubusercontent.com/47415585/56348963-d1ef0700-61c7-11e9-9b56-d66285d3d2e2.gif)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: chrome, Opera, FF, Edge
- OS: Win10

**Comment by pkarw** [comment]
Thanks, @ArturDivante. 

_**Acceptance criteria:**_
The animation should be played only with the switch using the arrows; clicking on product configurable options should always  - just switch the images without any animation efects.

**Comment by ArturDivante** [comment]
Thank you, @pkarw 
I edited expected behaviour section acording to your comment. One last thing we propably need to decide (or clarify) and post here is bhavior after clicking small circle icons from the bottom of the picture. animation or simple switch?

**Comment by pkarw** [comment]
Thanks! Yes, the simple switch should be ok with xlixkjng theme bullets

**Comment by RGijsberts** [comment]
in the vue-carousel documentation it says you should be able to navigate to a slide without the animation with this: navigateTo(index, false) but I can't get this to work.

**Comment by alinadivante** [comment]
When using arrow buttons or  circle icons - animation is played
When using color icons - pictures are switched without animation

**Comment by pkarw** [comment]
@alinadivante @przspa does this comment mean it works just fine?

**Comment by alinadivante** [comment]
Yes @pkarw I tested changes on stabilisationfix/#2757 branch and I added label here #3015 
I forgot to mark this issue
