### ISSUE TITLE
Adjust Introduction to medium post

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#2758]
https://medium.com/the-vue-storefront-journal/introduction-to-vue-storefront-a-quick-getting-started-guide-d119023ed67d

https://docs.vuestorefront.io/guide/#what-is-vue-storefront

TODO:
- Create "General information" label for docs category
- Adjust the linked doc to medium post

**Comment by filrak** [comment]
@pkarw  This is taken by our docs team as first issue to get familair with vuepress - i just need to wait till they confirm collaboration to assign

**Comment by follypimpin** [comment]
@filrak Do you mind being more specific with what to do as regards this issue. Its a bit vague, do you want a category "General Information" label just like the rest or is it meant to be a section in the blog or docs, a little bit more information will be highly appreciated.

**Comment by geektutor** [comment]
Hello,

By adjusting the medium link, should the link at the header be changed to this one here - https://medium.com/the-vue-storefront-journal/introduction-to-vue-storefront-a-quick-getting-started-guide-d119023ed67d

**Comment by filrak** [comment]
@follypimpin sorry this issue was meant for our docs team

**Comment by kkdg** [comment]
Hi @filrak I joined by @pkarw. I will start the job very soon in 1 or 2 days. 
As far as I understand you want to revamp the official VueStorefront docs as the same with the one in the Medium link?

**Comment by geektutor** [comment]
> Hello,
> 
> By adjusting the medium link, should the link at the header be changed to this one here - https://medium.com/the-vue-storefront-journal/introduction-to-vue-storefront-a-quick-getting-started-guide-d119023ed67d

@filrak I havent had a reply yet?
