### ISSUE TITLE
Page is unavailable after refreshing in offline mode.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2768]
## Current behavior
When user gets into offline mode and refreshes the page being viewed, then page is unavailable → INTERNET_DISCONNECTED

## Expected behavior
Viewed pages are cached and should be available after refreshing the page.

## Steps to reproduce the issue
1. Go to https://test.storefrontcloud.io/
2. Open any category page or product 
3. Turn to offline mode
4. Refresh page

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
If browsing in the CSR we need to prefetch the full `/p/....` page url to cache it in serviceworker - otherwise the page isn't cached indeed for full refresh

**Comment by pkarw** [comment]
I've changed to feature request as this behavior isn't anything broken - it was always like this :)

**Comment by lukeromanowicz** [comment]
We were not able to reproduce it
