### ISSUE TITLE
Re-use category breadcrumbs for products in the offline-mode

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2770]
## Current behavior
Sometimes bread crumbs path is broken (just only name of product is displayed) in offline mode.

![ezgif com-gif-to-mp4](https://user-images.githubusercontent.com/36628922/56575766-ea479300-65c6-11e9-8332-613aebb931f2.gif)

## Expected behavior
The full bread crumbs should always be displayed.

## Steps to reproduce the issue
1. Go to https://test.storefrontcloud.io/ _ (localhost, branch: develop) _
2. Open any product from ** Everything new ** section
3. Turn to offline mode
4. Look at bread crumbs
5. Come back to Home page
6. Again open the product and look at bread crumbs

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
After 1.8 breadcrumbs in CSR mode are loaded async (additional network call is being made) - so without the network connectivity, we can't fetch it. We could add an improvement to cache the full breadcrumb from the product list level however it would be very inefficient (to fetch all the subsequent categories); the other option is to **re-use the current category path (category breadcrumb) in the `product/setupBreadcrumbs` action - and this is the preferred solution**

**Comment by alinadivante** [comment]
@pkarw and do you know why on demo is also problem with bread crumbs (in online mode)? But here the product name is missing
![image](https://user-images.githubusercontent.com/36628922/56578398-e3704e80-65cd-11e9-90ac-99761d9f6e96.png)

**Comment by pkarw** [comment]
It was fixed from 1.9 (next and test)

**Comment by alinadivante** [comment]
great

**Comment by pkarw** [comment]
It should be changed in here: https://github.com/DivanteLtd/vue-storefront/blob/c0c6105a28a988247bbbdcd0f5fac7f58226cedf/core/modules/catalog/store/product/actions.ts#L67 - having a second option if `category/list` fails; we could probably just add a call to `              setBreadcrumbRoutesFromPath(context.rootGetters['category/getCurrentCategoryPath'])` before calling `category/list` as the `category/getCurrentCategoryPath` is the current category path - set on category page

**Comment by pkarw** [comment]
The other way to go is to modify the `vue-storefront-api` to setup the breadcrumbs server-side; I mean to move the logic of https://github.com/DivanteLtd/vue-storefront/blob/c0c6105a28a988247bbbdcd0f5fac7f58226cedf/core/modules/catalog/store/product/actions.ts#L43 to `vue-storefront-api`
