### ISSUE TITLE
The order cannot be placed

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2771]
## Current behavior

Currently, there is no possibility to place an order. Message appears:
The order can not be transferred because of the server error. Order has been queued.
![Peek 2019-04-23 13-34](https://user-images.githubusercontent.com/49188852/56578027-e28aed00-65cc-11e9-8944-f66acf8f7b44.gif)

## Expected behavior

After passing all the steps in the checkout and correct completion of the forms, click on 'Place the order' creates a new order.

## Steps to reproduce the issue

1. Go to https://next.storefrontcloud.io/
2. Add any product to the cart
3. Go to checkout
4. Fill in all steps with correct data
5. Click on 'Place the order'

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 73
- OS: Ubuntu 18.04.2 LTS

**Comment by pkarw** [comment]
It is probably related to validation issues

**Comment by pkarw** [comment]
If so, then we could start with the better error handling - showing details which field is causing the issue + trying to sync the validation

**Comment by pkarw** [comment]
Related to #2653 and #2740

**Comment by pkarw** [comment]
API returns 500 server error:

```
SyntaxError: Invalid regular expression: /[\p{L}\d_]+/: Invalid escape
    at new RegExp (<anonymous>)
    at getRegExp (/var/www/node_modules/ajv-keywords/keywords/regexp.js:15:26)
    at Ajv.inline (/var/www/node_modules/ajv-keywords/keywords/regexp.js:7:14)
    at Object.useCustomRule (/var/www/node_modules/ajv/lib/compile/index.js:279:25)
    at Object.generate_custom [as code] (/var/www/node_modules/ajv/lib/dotjs/custom.js:32:24)
    at Object.generate_validate [as validate] (/var/www/node_modules/ajv/lib/dotjs/validate.js:342:35)
    at Object.generate_properties [as code] (/var/www/node_modules/ajv/lib/dotjs/properties.js:194:26)
    at Object.generate_validate [as validate] (/var/www/node_modules/ajv/lib/dotjs/validate.js:342:35)
    at Object.generate_items [as code] (/var/www/node_modules/ajv/lib/dotjs/items.js:76:26)
    at Object.generate_validate [as validate] (/var/www/node_modules/ajv/lib/dotjs/validate.js:342:35)
```

**Comment by lukeromanowicz** [comment]
This is working fine on the latest develop for both API and VSF for the following address:
```
city: "Aaa"
country_id: "PL"
email: "lromanowicz+test2@divante.pl"
firstname: "Aaa"
lastname: "Aaa"
postcode: "11-111"
region_code: ""
region_id: 0
street: ["Aaa", "123"]
telephone: "111111111"
```
I believe that there might be an issue with babel.conf.js in the configuration of next.storefrontcloud.io. @patzick could you back me up with this one, please?

**Comment by lukeromanowicz** [comment]
It looks like it was working in NodeJs 10 (which is default nodejs for API), but it wasn't working on older NodeJs 8. Will be fixed in https://github.com/DivanteLtd/vue-storefront-api/pull/224

**Comment by kipotlea** [comment]
hi @GabiDivante , what plugin do you use to make GIF like this?

[https://user-images.githubusercontent.com/49188852/56578027-e28aed00-65cc-11e9-8944-f66acf8f7b44.gif](url)

**Comment by GabiDivante** [comment]
hi @kipotlea I use Peek https://github.com/phw/peek
