### ISSUE TITLE
The ability to add a product to 'wishlist' or 'be compared' from the product list view

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2773]
## What is the motivation for adding / enhancing this feature?

The customer can browse products faster by adding them directly to the wishlist or to the comparison from the products list (without going to each products page).

## What are the acceptance criteria 

We can add visible buttons next to each product or buttons may be visible after hovering over the product photo. 
The buttons may look like the ones used on the product page.
The implementation must be consistent with the prepared project:
@StasiekDivante please prepare the visualization.

- [ ] Clicking on the appropriate button will add the product to your wishlist or for comparison.
- [ ] The 'add to compare' button is visible only on the desktop view.

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by Jensderond** [comment]
I don't think this is necessary to do when a new default theme is coming in the near future

**Comment by alinadivante** [comment]
I don't think so it would be a good idea to display these icons on product images in Compare lis![image](https://user-images.githubusercontent.com/36628922/61634470-b0ebf580-ac91-11e9-8964-2def902129e2.png)

Products from wishlist don't have and it is okay. 

And one more thing: When I add product to Compare list/Wishlist from Home Page and I will open product page - Add to favorite / Add to compare options will still be available.

@StasiekDivante what you think about current solution for _
The ability to add a product to 'wishlist' or 'be compared' from the product list view_ ? 
![image](https://user-images.githubusercontent.com/36628922/61634933-bac22880-ac92-11e9-8bc3-1fa8c4f3f196.png)

Maybe better option will be to display these icons permanently, but for example, empty heart - when you add it to your favorites - it will fill up?

**Comment by Michal-Dziedzinski** [comment]
@alinadivante imo it's nice feature when you can add something to wishlist directely from compare :)

**Comment by alinadivante** [comment]
ok, so maybe we just need new design to improve the user experience :)

**Comment by pkarw** [comment]
@alinadivante and @Michal-Dziedzinski I just wanted to be sure: what are the next steps in order to have this feature `QA-accepted`?

**Comment by alinadivante** [comment]
@Michal-Dziedzinski imho we have to fix: 

>  When I add simple product to Compare list/Wishlist from Home Page and I will open product page - _Add to favorite / Add to compare_ options will still be available.

→ there should be Remove from wishlist/compare list option visible

**Comment by Michal-Dziedzinski** [comment]
@alinadivante  @ArturDivante @pkarw  #3293 should fix that
