### ISSUE TITLE
PDP. Customizable Options - bugs

### ISSUE THREAD

**Issue by afirlejczyk** [DivanteLtd/vue-storefront#2781]
For test purpose, I update product 24-MB05, but changes are not visible yet on vsf demo (only on magento).
http://demo-magento2.vuestorefront.io/catalog/product/view/id/4

## Current behavior
1. Option type - checkbox
- When clicking on one of the option, it select all of the options.
Related to #2089
2. Option type - field (text field)
- Price doesn't change after entering text (on Magento it is working)

**Comment by pkarw** [comment]
Related to: #2141 and #2089

**Comment by andrzejewsky** [comment]
@gibkigonzo can you check if this occurs in the 1.11?

**Comment by gibkigonzo** [comment]
@andrzejewsky yes, it still occurs. I will check where is the problem
