### ISSUE TITLE
Incorrect hover activity on the 'filter by categories' in the search view on mobile 

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2783]
## Current behavior

On mobile devices after clicking on the chosen filter, and then clicking on it to switch it off, the hover remains visible. This may confuse the user which filters are currently being applied.
![Peek 2019-04-24 10-52](https://user-images.githubusercontent.com/49188852/56646122-3a822c00-667f-11e9-86e1-f5ef3a4684a3.gif)

## Expected behavior

After clicking on the chosen filter to switch it off, hover should disappear. 

## Steps to reproduce the issue

The problem appears on https://demo.storefrontcloud.io/ and https://next.storefrontcloud.io

1. Go to https://demo.storefrontcloud.io/ on a mobile device 
2. Open search window by clicking on the loupe 
3. Type a word, for example, 'top'
4. Click on any filter
5. Unclick chosen filter

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome, Firefox
- OS: Android, v7 on Samsung Galaxy S8

**Comment by idodidodi** [comment]
I am working on it

**Comment by patzick** [comment]
Thanks @idodidodi! :)
