### ISSUE TITLE
The ability to return to the search results from the product page

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2787]
## What is the motivation for adding / enhancing this feature?

Currently, using the search function may be impractical:
-> customer searches for products that interest him
-> filters them as needed
-> browses the list of results
-> wants to view the details of one of the products and goes to the product page
-> tries to return to the search results by clicking on the arrow
-> **is moved to the home page.**
**The customer should be able to return to the search results so that he can continue to browse them.**

This feature will particularly change the user's experience **on the mobile version**, where the search results look like a separate page and going to the product page does not suggest losing them.

![Peek 2019-04-24 13-48](https://user-images.githubusercontent.com/49188852/56657210-bb4d2200-6697-11e9-8f5d-5f92b5a4d127.gif)

## What are the acceptance criteria 

- [ ] After going to the product page, the customer can return to the search results so he can continue to browse them.

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by webdiver** [comment]
[vs-hackathon] I tackle this one.

**Comment by webdiver** [comment]
Since there is no "Arrow-Back" anymore (as fas as I see), I implemented a solution, where the search will be stored in `user/recent_search` and after re-opening the search, the user sees the same results as before.

**Comment by patzick** [comment]
Thanks @webdiver ! :)
