### ISSUE TITLE
Define optional attributes

### ISSUE THREAD

**Issue by janmyszkier** [DivanteLtd/vue-storefront#2792]
This originally requested with a bigger scope in #2231 but one of the tasks can still be done.

 - [ ] Would be great if the end the [Product.ts](https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/catalog/types/Product.ts) type got updated marking the ? TypeScript notation - not required fields - where suitable.

**Comment by ZeevGerstner** [comment]
Can you tell whats the required fields so I can update the file?

**Comment by janmyszkier** [comment]
@ZeevGerstner I think you can use boilerplate products/index element for that:
https://github.com/DivanteLtd/vue-storefront-integration-boilerplate/blob/master/1.%20Expose%20the%20API%20endpoints%20required%20by%20VS/Required%20API%20specification.md#get-vsbridgeproductsindex
I recently updated it by removing attributes never mentioned in the code.
So: if anything is not in the boilperplate products/index it's definitely an optional argument.

**Comment by basvanpoppel** [comment]
@pkarw @janmyszkier i believe this issue can be closed, as the related PR is already merged to development branch.

**Comment by pkarw** [comment]
Thanks!
