### ISSUE TITLE
Provided docker environment not working out of box

### ISSUE THREAD

**Issue by benjick** [DivanteLtd/vue-storefront#2793]
## Current behavior
Doesn't display any products while running the UI in docker

## Expected behavior
Should display products

## Steps to reproduce the issue
```sh
git clone https://github.com/DivanteLtd/vue-storefront.git vue-storefront
cd vue-storefront
yarn
yarn installer # all default choices
# Visit http://localhost:3000 - products are shown
killall node
docker-compose up
# Visit http://localhost:3000 - no products are shown
```

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Firefox 66
- OS: OSX 10.14.3
- Node: v10.15.3 (inside the Docker container)
- Code Version: `ae6ba30618da6f417ecc9ae47c346337f3bfbf79` (currently `master`)

**Comment by pkarw** [comment]
Have You installed the API locally? If so - then please note that:
- the installer is not running the API / vs via docker
- so `killlall` killed both,
- by running `docker-compose up` You did run just the front-app (You should execute exactly the same command within the `vue-storefront-api` folder)

Of course, it would be nice to keep this process simpler for the user - please go on and propose some changes regarding it or maybe just the docs update?

**Comment by benjick** [comment]
@pkarw No, the default choices are these:

```
? Would you like to use https://demo.vuestorefront.io as the backend? Yes
? Please provide path for images endpoint https://demo.vuestorefront.io/img/
```

**Comment by pkarw** [comment]
Oh, in that case, it should work out of the box. Are You using VS 1.8.5 or 1.9 (or even 1.10 -> `develop` branch?)

**Comment by benjick** [comment]
@pkarw I'm using current master (`ae6ba30618da6f417ecc9ae47c346337f3bfbf79`), so I guess that's 1.8.5

**Comment by pkarw** [comment]
@lukeromanowicz and @patzick it should be checked before 1.9.0 release in that case

**Comment by lukeromanowicz** [comment]
I've tested it on 1.8.5 following the standard (non-legacy) way of https://docs.vuestorefront.io/guide/installation/linux-mac.html#install-the-vue-storefront-api and products are always there. Do you have any errors? What url is your app making requests to?

**Comment by benjick** [comment]
@lukeromanowicz did you try to reproduce the steps I wrote or do you mean the way in the documention always work? It works fine when the installer starts the node application but the provided docker environment does not work out of box.

I can't check right now but I will update asap

**Comment by patzick** [comment]
I've watched this yesterday and let luke to double check, we couldn't reproduce this. Please try on current release branch and let us know. I'm moving this for now to 1.9.1 to have focus on that in near future. Please let us know if is it still an issue.

**Comment by lukeromanowicz** [comment]
@benjick I mean that I checked if installing steps from the guide are still working and yes, they are. The only thing I had to do was adjust the container name in migration/restore commands which is further in the guide than the issue you described.

![image](https://user-images.githubusercontent.com/46789227/56787248-3af40180-67fc-11e9-9008-b031f3caca70.png)


Following the commands you've posted gives me the same result. All products are there, no matter if hosted on docker environment or locally. Your issue sounds like you have some sort of connectivity problem with the remote API. Changing logging settings to log everything and checking the results would also be helpful. Could you, please, try debugging your issue starting from there?

**Comment by pkarw** [comment]
Maybe the docker container doesn’t mount the config/local.json (?) it should lead to the problem described in here - as Max wrote he’s using demo.vuestorefornt... so shouldn’t have anything to be restored

**Comment by benjick** [comment]
I will do a test on another machine just to make sure, I'll open it again if the problem persists
