### ISSUE TITLE
Content lost for product description

### ISSUE THREAD

**Issue by chuanman2707** [DivanteLtd/vue-storefront#2800]
## Current behavior

This is some of my magento product details page, with long description.
<img width="525" alt="Screen Shot 2019-04-25 at 3 41 48 PM" src="https://user-images.githubusercontent.com/29907469/56723203-b4dfa880-6772-11e9-8580-c2423614522c.png">

After I do `yarn mage2vs import` and `yarn db rebuild`
this is the VSF product page i got
<img width="944" alt="Screen Shot 2019-04-25 at 3 44 13 PM" src="https://user-images.githubusercontent.com/29907469/56723339-f53f2680-6772-11e9-8b66-71b533bbb2eb.png">

If I check elasticsearch database with `curl -XPOST 'localhost:9200/vue_storefront_catalog/product/_search'`
I can see all the text needed there.

## Expected behavior

VSF should display all the product details similar to magento

## Can you handle fixing this bug by yourself?
I'm not sure, i'm trying.

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

This is for stable version.
## Environment details

- Browser: Chrome
- OS: OSX

**Comment by pkarw** [comment]
We're using the `product.description` for this text:

```
            <div
              class="lh30 h5"
              itemprop="description"
              v-html="product.description"
            />
```

Please do make sure if Your content is in this field or please modify the theme to use the proper one.

https://github.com/DivanteLtd/vue-storefront/blob/76a75759550ec2b7dd9642eb3b281566c1590dc5/src/themes/default/pages/Product.vue#L202

**Comment by chuanman2707** [comment]
I figured out instead of writing text on magento description, i use short description, that why the text show normal on magento frontend but doesn't show up on VSF frontend.
