### ISSUE TITLE
Add back button arrow on Order details page.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2802]
## What is the motivation for adding / enhancing this feature?
Make navigation easier on the orders page. Users pressing arrow/back button can return from the order details view to the full list of all orders.

## What are the acceptance criteria 
Add back button on Order details page.

![image](https://user-images.githubusercontent.com/36628922/56735739-9673b000-6766-11e9-9e82-a8040eebaf21.png)

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
@StasiekDivante could You please come up with the UX design for this button please?

**Comment by alinadivante** [comment]
I think we can use the same arrow like on product details page
![image](https://user-images.githubusercontent.com/36628922/56736231-e8690580-6767-11e9-8f38-75460ac56211.png)
https://demo.storefrontcloud.io/p/MP01/caesar-warm-up-pant/MP01

**Comment by StasiekDivante** [comment]
@alinadivante good idea, let's do that!

**Comment by RGijsberts** [comment]
i would like to get busy with this

**Comment by pkarw** [comment]
Cool! Go on @RGijsberts

**Comment by RGijsberts** [comment]
> @alinadivante good idea, let's do that!

Should the arrow be placed as in the screenshot above, on the right side next to the order details ?

**Comment by alinadivante** [comment]
@RGijsberts what u think about this place?
![image](https://user-images.githubusercontent.com/36628922/56805719-2fb7ca80-682a-11e9-9e82-58896de47523.png)
(I moved order number to the right)

**Comment by RGijsberts** [comment]
> @RGijsberts what u think about this place?
> ![image](https://user-images.githubusercontent.com/36628922/56805719-2fb7ca80-682a-11e9-9e82-58896de47523.png)
> (I moved order number to the right)

That makes sense, I will place it there.
