### ISSUE TITLE
Lack of back button on product page (test&next environment)

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2804]
## Current behavior
There is no back button on product page on the latest version.
Compare demo environment with next 
https://demo.storefrontcloud.io/p/WS09/tiffany-fitness-tee/WS09
→
https://next.storefrontcloud.io/women/tops-women/tees-women/tees-25/tiffany-fitness-tee-1513.html?childSku=WS09

**Back button** is replaced with**hamburger menu**.

![image](https://user-images.githubusercontent.com/36628922/56788763-9a541080-6800-11e9-9377-895d732d214e.png)

## Expected behavior
There should be back button.

## Steps to reproduce the issue
1. Open any product page on https://next.storefrontcloud.io/
2. Look at the header
3. Try to Find back button (arrow)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
@patzick i belive we should maybe include this one in 2.9 - it’s probably related to url dispatcher changes (?)

**Comment by patzick** [comment]
I'm not sure if i remember it correctly, but this might be done intentionally. Because for example when you're going to product page and want to change category you wouldn't have this possibility. You can always go back through breadcrumbs, menu also is kept in current category so you can also easily change subcategories. In my opinion menu should be accessible for user.
What do you think @alinadivante, @pkarw , @filrak ?

**Comment by pkarw** [comment]
You’re right I remember there was such a change introduced during one of the jackafhona 
To keep the proper UX we should display this arrow only in the situation when user entered the product page from category (with filters set etc) and would like to get back to check another product for the filtered list. For sure it shouldn’t be there when just clicking between individual products

@StasiekDivante to be asked and to propose solution - @alinadivante yoire an owner of this change please make sure the UX is at the proper level

**Comment by alinadivante** [comment]
@patzick  I didn't know about this, but yes, I agree with you @patzick and @pkarw it makes sense!

**Comment by StasiekDivante** [comment]
@pkarw @alinadivante we should always keep the arrow, as we want to build experiences as close as possible to the native applications. I would keep both, the back arrow and the hamburger menu upon entering from any path

**Comment by alinadivante** [comment]
Probably it is the best solution. Could you show us design with two buttons, @StasiekDivante ?

**Comment by alinadivante** [comment]
@StasiekDivante Can you take care of it?
Because now we have again problem with this issue #2732

**Comment by StasiekDivante** [comment]
![asdf](https://user-images.githubusercontent.com/37068687/57223064-1de1de80-7005-11e9-8d0d-e78597301190.png)
here you go @alinadivante

**Comment by alinadivante** [comment]
@StasiekDivante okay, but please change the order of the buttons :)

**Comment by StasiekDivante** [comment]
I wouldn't to that, this order is the standard

**Comment by alinadivante** [comment]
We discussed with @patzick about this idea and for now... I close this ticket : D
