### ISSUE TITLE
Incorrect status filter in Related Products query

### ISSUE THREAD

**Issue by RGijsberts** [DivanteLtd/vue-storefront#2805]
## Current behavior
The related products query returns products with status 0, 1 and 2. Only 1 and 2 are used in Magento which represent enabled and disabled. I'm not sure that 0 stands for.
We ran into the problem where a disabled product was displayed in the related products area. Clicking on this product returned an error as the product was not meant to be viewed.

## Expected behavior
The expected behaviour is that only enabled products, with status:1, should be returned by the query.

## Steps to reproduce the issue
I can't find this specific related products module on the demo shop so I can't deliver the steps to reproduce. 

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [X] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome, Version 73.0.3683.86
- OS: MacOS 10.14.4
- Node: node v8.16

## Additional information
The related products query filters products with status 0, 1 and 2. 1 and 2 are used in Magento for enabled and disabled but what is 0 used for? In any case you would want only enabled products to be displayed as related products else you'll receive an error for clicking on a disabled product.

**Comment by pkarw** [comment]
Thanks! Feel free to propose a PR with a fix for that
