### ISSUE TITLE
Add 'clear wishlist' button. 

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2806]
## What is the motivation for adding / enhancing this feature?
Similar to clear cart button - currently if user has many products in their wishlist, and want to start fresh, he needs to remove them one by one. Possibility to clear whole wishlist with two clicks (click button + confirmation) would be nice improvement. Adding product to wishlist means less commitment that adding them to cart - so many users tend to add a lot of products to their wishlists. 

## What are the acceptance criteria 
- [ ] - New 'Clear wishlist' Button is displayed in the upper right part of wishlist sidebar
- [ ] - Location and button design should be identical as 'Clear cart' button introduced in #2587
- [ ] - Clicking this button should result in displaying confirmation popup, and after confirmation - clearing wishlist. 

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information
Adding and moving 'clear cart' button to the correct location, should be a good example of how to proceeed:

#2587
#2765

**Comment by patzick** [comment]
Thanks @aniamusial !:)
