### ISSUE TITLE
After refresh My account page user is redirected to Home Page

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2809]
## Current behavior
The user browsing the sub-pages of My account, if he refreshes any of them, he will be redirected to the Home page.
![my_account](https://user-images.githubusercontent.com/36628922/56797487-17898080-6815-11e9-8003-fa27fe0ac9bd.gif)

## Expected behavior
After refresh page user should remain on the same page.

## Steps to reproduce the issue
1. Go to My account (open any sub-page)
2. Refresh page

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
My Account doesn't work in SSR mode - this is intended behavior.
