### ISSUE TITLE
Add 'Show results' button to filters view on mobile

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2811]
## What is the motivation for adding / enhancing this feature?

The filters for the list of products in the mobile view are visible in the sliding side tab.
So, the user can not see that by selecting filters the list of products automatically updates.
Switching to filter results by clicking 'x' is not intuitive. 'X' is also not visible when scrolling filters down.
![Peek 2019-04-26 11-40](https://user-images.githubusercontent.com/49188852/56799146-946a2980-6818-11e9-8819-709e6e02f63b.gif)

## What are the acceptance criteria 

- [ ] Under the list of filters, the 'Filter' button is visible, which closes the filter sidebar.
- [ ]  "Clear" button is changed according to the prepared design 

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
@StasiekDivante we need You UX support with this one

**Comment by StasiekDivante** [comment]
@GabiDivante I would add "Filter" button on the bottom on the screen and fix it's position. Also I would remove some visual weight from the "clear" button as it guides users to incorrect bahaviour

![filters](https://user-images.githubusercontent.com/37068687/56949163-70695980-6b32-11e9-8ef4-882b1fd1a225.png)

**Comment by GabiDivante** [comment]
@StasiekDivante great, let's do this that way! Thank you :)

**Comment by patzick** [comment]
Thanks @965750!

**Comment by alinadivante** [comment]
@965750 Please add new PR and as we discussed - add icon next to Clear fillers :)

**Comment by 965750** [comment]
@patzick @alinadivante @pkarw here's new PR with icon added https://github.com/DivanteLtd/vue-storefront/pull/2996
