### ISSUE TITLE
Page is zoomed after sorting on product list (iPhone)

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2815]
## Current behavior

On iPhone after selecting the sorting option, the page is zoomed.
![Peek 2019-04-26 13-26](https://user-images.githubusercontent.com/49188852/56804875-7b1ca980-6827-11e9-883f-99456a8472a6.gif)
Zoom can only be changed by pinching. 

## Expected behavior

The page shouldn't be zoomed after 'sort by' selection. 

## Steps to reproduce the issue

1. Go to https://demo.storefrontcloud.io/ on iPhone (Safari or Chrome)
2. Click on the hamburger menu
3. Choose any category
4. Click on 'Sort by' and choose any sorting option

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Safari, Chrome
- OS: iOS, v11
iPhone X

**Comment by VictorKadup** [comment]
i will take care of it

**Comment by patzick** [comment]
Thanks @VictorKadup ! :)
