### ISSUE TITLE
Remove some text from Order confirmation page and create new button

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2818]
## What is the motivation for adding / enhancing this feature?
Too much, unnecessary text on Order confirmation.

We have form "What we can improve?",  so following text: 

> "E-mail us at demo@vuestorefront.io with any questions, suggestions how we could improve products or shopping experience"

is usless.

Also this information is unnecessary
 
> Your Account
You can log to your account using e-mail and password defined earlier. On your account you can edit your profile data, check history of transactions, edit subscription to newsletter.

## What are the acceptance criteria 

Replace mentioned text with new button "Return to shopping"

![image](https://user-images.githubusercontent.com/36628922/56807786-0ef27380-6830-11e9-9b57-3e0348899d8f.png)

I prepared design proposal:
![image](https://user-images.githubusercontent.com/36628922/56808829-b96b9600-6832-11e9-8117-f0a79938ca2c.png)

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by ZeevGerstner** [comment]
I will add this feature

**Comment by patzick** [comment]
Thanks @ZeevGerstner ! :)

**Comment by alinadivante** [comment]
Thank u @ZeevGerstner

**Comment by ZeevGerstner** [comment]
Glad to help :) Did you guys merged this to the master?
