### ISSUE TITLE
Attributes value & ID as string

### ISSUE THREAD

**Issue by OnlyC** [DivanteLtd/vue-storefront#2836]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	
My backend is an ERP in python & Mariadb. It's using name as ID. Ex:
- ITEM-01234 (order ID)
- SO-01324 (sales order ID)
- Product attributes: {name: 'Color', options: [ {name: 'Orange', abbr: 'ORG'}, {name: 'Blue', abbr: 'BLU'} ]
...
The name of the color is the ID. There's no Integer/Auto-increment ID.

## Keep the problem description concise and include:
I'm using node_app & exposing api endpoints for it to get data.
In the docs, the attributes value must be in Integer & that's what I don't have.

How can I solve this?
Will there be a problem with Order or Product as they're also a String ID, not Integer ID?

**Comment by pkarw** [comment]
Hi @OnlyC thanks for contacting us. That's true, by default the options need to be integers - and You need to have the `attribute` entity filled for each individual attribute with the meta-data dictionary (type, available options etc).

HOWEVER - there is an option to just use the string values as well. Vue Storefront filters and configurable options can work without integer-based attributes. This is the mode we used with the [bigcommerce2vuestorefront](https://github.com/DivanteLtd/bigcommerce2vuestorefront/blob/42efbb05aef1f37bfb944910b662d39c5de5e37a/src/templates/product.js#L74). Please take a look at the [`populateProductConfigurationAsync`](https://github.com/DivanteLtd/vue-storefront/blob/54c19a6a7ac1af8e5d8ae098cd86b92fd804b8b2/core/modules/catalog/helpers/index.ts#L361) as well.

Basically it means that:
- you might have the attributes in a form of: `product.color: "Gray"` - filters will work without any problem,
- you might have the configurable options in a form of `product.configurable_options = { // TODO: we need to populate product's : product.color_options and product.size_options to make forntend filters work properly
            id: po.id,
            attribute_code: 'prodopt-' + po.id, // this is virtual attribute_code - the attribute doesn't have to exist
            product_id: output.id,
            label: po.display_name,
            position: po.sort_order,
            frontend_label: po.display_name,
            values: po.option_values.map(ov => {
              return {
                label: ov.label,
                default_label: ov.label,
                order: ov.sort_order,
                value_index: ov.id, // it's not parsed to int anywhere in the code - so can be just a unique value of any type (I guess :D :D )
                value_data: ov.value_data
              }
            })
          }`

**Comment by pkarw** [comment]
Functions to debug in case of problems:
- `populateProductConfigurationAsync`
- `findConfigurableChildAsync`
- `configureProductAsync`

All from the: https://github.com/DivanteLtd/vue-storefront/blob/54c19a6a7ac1af8e5d8ae098cd86b92fd804b8b2/core/modules/catalog/helpers/index.ts#L446

**Comment by pkarw** [comment]
@OnlyC how are things? :)

**Comment by OnlyC** [comment]
Hi @pkarw 
I'm still trying to understand how things work & correcting data structure.
I managed to get categories into vuex. products->list still empty.

**Comment by pkarw** [comment]
Ok, im closing this issue for now please do contact us if can somehow help with the other things
