### ISSUE TITLE
Extract all search queries to API

### ISSUE THREAD

**Issue by lukeromanowicz** [DivanteLtd/vue-storefront#2837]
## What is the motivation for adding / enhancing this feature?
1. will make the client lighter by removing unnecessary code possibly along with some dependencies
2. will make the environment more secure by restricting access to ElasticSearch
3. will simplify the vsf code it terms of maintenance and improve platform agnosticism 

## What are the acceptance criteria 
- search queries are stored in ES instead of hardcoded/generated in vsf 
- new search queries have simplified endpoints in API which allow querying specific information with short and simple http requests.
- all relevant configurations are moved from vsf to vsf-api

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information
It only makes sense to implement it as BC (instead of keeping both ways still available and make things even worse this way).

**Comment by pkarw** [comment]
Related to #2166 and #2167 -> more to this one

**Comment by cristian-g** [comment]
Hi! Which branch is being used for the development of this feature request?

**Comment by lukeromanowicz** [comment]
@cristian-g As the Release Cycle section says, it should be based on develop but it looks like nobody is currently working on this one.

**Comment by cristian-g** [comment]
Yes @lukeromanowicz but as @pkarw started something related to this some time ago (https://github.com/pkarw/vue-storefront/tree/feature/2166_simple_backend), are contributions expected to be forks from pkarw/vue-storefront or from DivanteLtd/vue-storefront? Maybe contributors can fork pkarw/vue-storefront, commit to 2166_simple_backend and the @pkarw could merge that to DivanteLtd/vue-storefront (just an idea!)

**Comment by pkarw** [comment]
This will be done with #3337
