### ISSUE TITLE
Dynamic import doesn't work in tests.

### ISSUE THREAD

**Issue by lukeromanowicz** [DivanteLtd/vue-storefront#2851]
## Current behavior
Dynamic import is not supported in unit tests written in javascript (not typescript).

## Expected behavior
Dynamic import should work and be mockable just like a regular import.

## Steps to reproduce the issue
Create a file called test.js with dynamic import:
```
export default async () => {
  const isServer = (await import('@vue-storefront/core/helpers')).isServer

  return isServer
}
```

And a unit test written in javascript:
```
import testSubject from '../../test'

jest.mock('@vue-storefront/core/helpers', () => ({
  get isServer () {
    return false
  }
}))

describe('test', () => {
  it('should return false', async () => {
    const result = await testSubject()

    expect(result).toBe(false)
  })
})
```

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by filrak** [comment]
If it's not there on Monday  please change milestone to next one
