### ISSUE TITLE
Listening to "application-after-init" in module's afterRegistration hook not possible

### ISSUE THREAD

**Issue by phoenixdev-kl** [DivanteLtd/vue-storefront#2852]
## Current behavior
The code, which should get executed on "application-after-init" event, for example in module "sample-custom-entity-graphql", is never reached. The following error can be found in server console after enabling the example module:
```
Error during render : /error
TypeError: Vue.$on is not a function
    at Object.afterRegistration (src/modules/sample-custom-entity-graphql/hooks/afterRegistration.ts:12:6)
    at VueStorefrontModule.module.exports../core/lib/module/index.ts.VueStorefrontModule.register (core/lib/module/index.ts:119:20)
    at server-bundle.js:1449:45
    at Array.forEach (<anonymous>)
    at registerModules (core/lib/module/index.ts:18:10)
    at server-bundle.js:271:109
    at step (node_modules/tslib/tslib.es6.js:97:0)
    at Object.next (node_modules/tslib/tslib.es6.js:78:44)
    at fulfilled (node_modules/tslib/tslib.es6.js:68:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Expected behavior
Debug output `Example of custom entity graphql extension` in console.

## Steps to reproduce the issue
1. Add example module to `src/modules/index.ts`:
```javascript
import { SampleCustomEntityGql } from './sample-custom-entity-graphql'
...
export const registerModules: VueStorefrontModule[] = [
  ...,
  SampleCustomEntityGql
]
```
2. Run `yarn dev`
3. Open http://localhost:3000/
4. Check server console

## Repository
https://github.com/DivanteLtd/vue-storefront/commits/develop

## Can you handle fixing this bug by yourself?
- [x] YES
- [ ] NO
- [ ] MAYBE

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to?
- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Google Chrome 73.0.3683.103
- OS: macOS Mojave (10.14.4)
- Node: 10.6.0
- Code Version: https://github.com/DivanteLtd/vue-storefront/commit/d8c986ce0823b92c381bec25505cb179fd2c5b1e

### Explanation of the issue
Function **afterRegistration** receives the Vue constructor:
https://github.com/DivanteLtd/vue-storefront/blob/b4bb0943686efd432fce5ca191ab356c09014094/src/modules/sample-custom-entity-graphql/hooks/afterRegistration.ts#L11
https://github.com/DivanteLtd/vue-storefront/blob/cbf7b5203989bbc122b430a1456f4c5cd4f51283/core/lib/module/index.ts#L119
https://github.com/DivanteLtd/vue-storefront/blob/cbf7b5203989bbc122b430a1456f4c5cd4f51283/core/lib/module/index.ts#L84-L89

But the Vue constructor doesn't have method $on, therefore the error in console occurs
https://github.com/DivanteLtd/vue-storefront/blob/b4bb0943686efd432fce5ca191ab356c09014094/src/modules/sample-custom-entity-graphql/hooks/afterRegistration.ts#L12

#### Use the event bus
Use the bus to emit the event in app.ts
https://github.com/DivanteLtd/vue-storefront/blob/cbf7b5203989bbc122b430a1456f4c5cd4f51283/core/app.ts#L119
```javascript
Vue.prototype.$bus.$emit('application-after-init', app)
```
And listen to the bus in module's afterRegistration.ts
https://github.com/DivanteLtd/vue-storefront/blob/b4bb0943686efd432fce5ca191ab356c09014094/src/modules/sample-custom-entity-graphql/hooks/afterRegistration.ts#L12
```javascript
Vue.prototype.$bus.$on('application-after-init', async () => {
```
#### Pass the app to the module
Instead (or as an addition to?) the Vue constructor pass the app instance to the hook
https://github.com/DivanteLtd/vue-storefront/blob/cbf7b5203989bbc122b430a1456f4c5cd4f51283/core/app.ts#L110-L113
```javascript
  const appContext = {
    isServer,
    ssrContext,
    app
  }
```
https://github.com/DivanteLtd/vue-storefront/blob/cbf7b5203989bbc122b430a1456f4c5cd4f51283/core/lib/module/index.ts#L18
```javascript
modules.forEach(m => m.register(app)) 
```
https://github.com/DivanteLtd/vue-storefront/blob/b4bb0943686efd432fce5ca191ab356c09014094/src/modules/sample-custom-entity-graphql/hooks/afterRegistration.ts#L12
```javascript
app.$on('application-after-init', async () => {
```

### See also / Related?
https://github.com/DivanteLtd/vue-storefront/issues/2760

**Comment by filrak** [comment]
This problem is directly caused by the fact that we are using root Vue instance instead of Event Bus to emit `application-after-init`event so first solution you proposed is the right one. It's obviously a bug,  not intended behavior. 

Do you want to take care of this issue?

**Comment by phoenixdev-kl** [comment]
Yeah, will be glad to take care of it.
