### ISSUE TITLE
Improve translations by using named fomatting

### ISSUE THREAD

**Issue by phoenixdev-kl** [DivanteLtd/vue-storefront#2854]
## What is the motivation for adding / enhancing this feature?
Translation strings which are composed of multiple pieces like for example
https://github.com/DivanteLtd/vue-storefront/blob/38fb1579c60d1aa352d353c06c1f0d9af7f79937/src/themes/default/components/core/GenericSelector.vue#L6 or
https://github.com/DivanteLtd/vue-storefront/blob/6995f88dab30cbd2a10dcd6874891f6566124320/src/themes/default/components/core/ColorSelector.vue#L5
force the pieces to be composed in this exact order. So, for example first "Select " and then always followed by the label. Considering the following German translation, this results in "Auswählen Größe" which sounds really stupid as it is simply incorrect grammar:
- "Select " translated with "Auswählen "
- _label_ having a value of "Größe"

Correct would be "Größe auswählen".

## What are the acceptance criteria
A translation string needs to be able to define the order of how the pieces get put together.

## Can you complete this feature request by yourself?
- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to?
- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information
I propose that all translations which are composed of multiple strings/translations use [named formatting](http://kazupon.github.io/vue-i18n/guide/formatting.html#named-formatting). This feature is already available (vue-i18n), only need to refactor existing code to take advantage of it.
Translations for the above mentioned examples would look like this:
```
"Select {label}","{label} auswählen"
"Select color {label}","Farbe '{color}' auswählen"
```

**Comment by phoenixdev-kl** [comment]
I'd offer to take this issue over but don't know how to assign it to me.

**Comment by ca1zr** [comment]
In general I suggest the translations should be in the **formal** instead of **informal** way.

**Comment by phoenixdev-kl** [comment]
Hi @ca1zr, is your last comment just a general statement regarding translations? If it has to do with the approach requested in the initial description then I'm not quite sure if I get the link ... could you clarify more how it relates to named formatting?

**Comment by ca1zr** [comment]
Hi @phoenixdev-kl, it was a general request. Some translations sound pretty weird and choppy, so  named formatting is a good thing.

**Comment by pkarw** [comment]
@phoenixdev-kl this is a pretty good idea, why not to implement it to 2.0?

**Comment by phoenixdev-kl** [comment]
@pkarw great! sorry, the process is unfortunately not clear to me. if this feature is planned for 2.0, from which branch do i create a branch in my fork (release/v2.0 or develop)? and when the refactoring is finished, am i supposed to create the pull request in release/2.0?
