### ISSUE TITLE
No product thumbnail/image

### ISSUE THREAD

**Issue by stkac** [DivanteLtd/vue-storefront#2855]
Hi, using docker and my own Magento instance I connect successfully but don't get the  thumbnail/image product...
 
Some idea? 

## Current behavior
![image](https://user-images.githubusercontent.com/41887474/57160627-979d8080-6de9-11e9-9877-a4b0fd836a0a.png)

**docker logs**

```
19:21:31 2|server   | 2019-05-03 19:21:31: whole request [/page-not-found]: 171ms
19:21:31 2|server   | 2019-05-03 19:21:31: whole request [/page-not-found]: 182ms
19:21:31 2|server   | 2019-05-03 19:21:31: whole request [/page-not-found]: 137ms
19:21:31 2|server   | 2019-05-03 19:21:31: whole request [/page-not-found]: 144ms

```
thanks in advance,

**Comment by pkarw** [comment]
It looks like some the JavaScript files can’t be loaded (not sure why) - therefore the lazy load component is not able to load the proper images

**Comment by stkac** [comment]
hi @pkarw, thanks for look my issue, can you see this error in this url:  https://infinitelove.to

**Comment by mdanilowicz** [comment]
It looks like a problem with Nginx configuration. 
`https://infinitelove.to/img/310/300/resize/w/b/wb02-green-0.jpg` -> `https://infinitelove.to/page-not-found`

https://docs.vuestorefront.io/guide/installation/production-setup.html#nginx

Make sure that you have this proxy.

```
location /img/ {
  proxy_pass http://localhost:8080/img/;
}
```

**Comment by stkac** [comment]
@mdanilowicz @pkarw 


**Before**
![image](https://user-images.githubusercontent.com/41887474/57176841-5fd02080-6e5d-11e9-9364-a8d98282e2ba.png)


**After**
![image](https://user-images.githubusercontent.com/41887474/57176835-547cf500-6e5d-11e9-9ac2-f44cc37872dc.png)

**Done!**
![image](https://user-images.githubusercontent.com/41887474/57177086-b2f7a280-6e60-11e9-8f23-dbeae0e756ba.png)
