### ISSUE TITLE
Category filter for filtering product attributes with 'yes or no' value

### ISSUE THREAD

**Issue by michhy** [DivanteLtd/vue-storefront#2857]
## Prerequisites
I tried to activate the custom filter, I can even log the new filter 'SF' is being loaded, 
but its not shown on the filter sidebar. 
Basically I want to create a few specific attribute filters, for filtering if any product's specific attribute is '1' / true.

Example: https://www.pureformulas.com/food/category/nuts-and-seeds.html

Please see the screenshot below.

Please answer the following questions for yourself before submitting an issue.  
- [v ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	

# Can't find what you're looking for?

## Keep the problem description concise and include:
- [ ] A brief description of the problem,
- [ ] Where the problem is occurring,
- [ ] The length of time the problem has been occurring,
- [ ] The size of the problem.

## Additional information

![螢幕截圖 2019-05-05 下午2 29 27](https://user-images.githubusercontent.com/37435427/57190715-55428380-6f50-11e9-9705-2212df511fbb.png)
Log showing it actually loaded 'SF' into the filter, but it cannot display.

![螢幕截圖 2019-05-05 下午2 30 05](https://user-images.githubusercontent.com/37435427/57190716-55db1a00-6f50-11e9-981b-852774a1d940.png)

in magento it is showing.

**Comment by pkarw** [comment]
Hi! Have You added this attribute to “defaultFilters” in the config/local.json?
Filters are not yet automatically loaded and need to be explicitly listed in the config

**Comment by michhy** [comment]
Hi @pkarw. Yes I have added to "defaultFilters" in config/local.json. it is loaded but with no arrays. (I have logged in the screenshot)

**Comment by pkarw** [comment]
Ok please set the type of this attribute to “keyword” in the vs-api/config/product.*.schema.json and run “yarn db rebuild” then check the results once again

**Comment by michhy** [comment]
Hi @pkarw  I have added "SF": {"type": "keyword"}, under properties in elastic.schema.product.json in vs-api/config/, the result still the same.

![螢幕截圖 2019-05-08 下午7 16 56](https://user-images.githubusercontent.com/37435427/57371826-6694c580-71c6-11e9-8778-25fe2918d122.png)
![Uploading 螢幕截圖 2019-05-08 下午7.19.13.png…]()
![Uploading 螢幕截圖 2019-05-08 下午7.20.22.png…]()

**Comment by michhy** [comment]
Hi I have solved it. I need to put 'interger' instead of 'keywords' for the type of attribute in  elastic.schema.product.json.
after putting: "sf": {"type": "integer"}, and run the rebuild again, it works.
Thanks a lot.
