### ISSUE TITLE
No placeholders in gallery - offline mode

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2863]
## Related issues
#2557

## Current behavior
If given product was not opened before going offline, then gallery opened in offline mode will contain no pictures (except default one) or __placeholders__  , just ugly missing-graphics-icon :) 

![noplaceholder2](https://user-images.githubusercontent.com/47415585/57284427-6eaf1100-70b1-11e9-92c3-9660307cecde.PNG)

## Expected behavior
Pictures or placeholreds should be displayed instead. 

## Steps to reproduce the issue
1. Open demo.storefrontcloud.io
2. Open some cataegory pages and product pages
3. Turn offline
4. Navigate to page of product you didn't load before going offline 
5. Open picture gallery
6. Switch to non-default photo

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Many - desktop and mobile
- OS: Win10, android

## Additional information
I given product page was loaded before going offline, pictures and thumbnails in gallery will be displayed correctly.

**Comment by pkarw** [comment]
This ja not na issue - Iran improvement.
We should show other images in offline mode at all. There should be just one single picture without the gallery at all (as it was prior to 1.8)

**Comment by pkarw** [comment]
We do have the same behavior with online mode / placeholder is not visible while picture is being loded

**Comment by pkarw** [comment]
We do have the same behavior with online mode / placeholder is not visible while picture is being loaded

**Comment by pkarw** [comment]
We should keep only one single picture in the offline mode without the Gallery component at all.

**Comment by patzick** [comment]
@przspa please take a look if your component is used here. Also in offline mode there should not be zoom option.

**Comment by benoitemile** [comment]
> We should keep only one single picture in the offline mode without the Gallery component at all.

Hello, could you please explain why ?
In a flaky connection, (talking about being in transports with online/offline switching) when using site you're viewing gallery component with vue carousel slider and images; suddenly, you're offline and switched to a single image where client already downloaded images; then you come back online and get the carousel back again.
Isn't it confusing for the end user ?

Why not showing placeholder images for non-previously-loaded images ? keeping the experience the same ?

**Comment by pkarw** [comment]
It was done on purpose. If we don;'t have the images (offline mode) it makes a little sense for the user to show the gallery - it's pretty much frustrating to swipe off empty placeholders in the end
