### ISSUE TITLE
Add a sticky Scroll To Top button

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2864]
## What is the motivation for adding / enhancing this feature?
This feature gives better navigation and allow users to easily scroll back to the top of category page with one click of the button. 

## What are the acceptance criteria 
Add sticky "Scroll to top" button on category page.

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by RGijsberts** [comment]
I will work on this

**Comment by pkarw** [comment]
@RGijsberts it seems like it's already done: https://github.com/DivanteLtd/vue-storefront/pull/2866

**Comment by RGijsberts** [comment]
> @RGijsberts it seems like it's already done: #2866

I missed that, nice!
