### ISSUE TITLE
Wishlist not sync to server at the moment

### ISSUE THREAD

**Issue by michhy** [DivanteLtd/vue-storefront#2865]
## Prerequisites
If I add products to wishlist, and log in in another machine, the list is not loaded.
Is the wishlist only saved by cookie cache, but not syncing to server at the moment?

Please answer the following questions for yourself before submitting an issue. 
- [v ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	

# Can't find what you're looking for?

## Keep the problem description concise and include:
- [ ] A brief description of the problem,
- [ ] Where the problem is occurring,
- [ ] The length of time the problem has been occurring,
- [ ] The size of the problem.

**Comment by pkarw** [comment]
No, it's not synced at the moment as Magento2 was missing the wishlist API endpoints. There is an open Feature Request on that: https://github.com/DivanteLtd/vue-storefront/issues/709
