### ISSUE TITLE
Change Linting 

### ISSUE THREAD

**Issue by ResuBaka** [DivanteLtd/vue-storefront#2867]
# Linting for debugger statements.  

Here we only check for debugger in the build process.  
But we should move it to an early stage to catch it early. 

So my thought would be to change the debugger rule to an warning while developing.

Which would be this 
```
'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0
```
to that.
```
'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 1
```

**Comment by lukeromanowicz** [comment]
@pkarw @filrak @patzick
