### ISSUE TITLE
Missing information about shipping method in Shopping summary

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2869]
## Steps to reproduce the issue
1. In Magento Admin set Flat Rate: Disabled and Free Shipping: Enabled (pay attention to the Minimum Order Amount)
2. Find cheaper product than Minimum Order Amount from Free Shipping method and add it to cart
3. Open the cart and look at Shopping summary
4. Go to checkout and look at Order Summary
5. Return to Shopping cart and again check Shopping summary

## Current behavior
If you add product and open cart, then u don't see shipping method. Only after going to the checkout (or if you return back to the cart) you will see current shipping method → DPD Courier.

![shipping_method](https://user-images.githubusercontent.com/47415585/57360834-6c18ee00-717b-11e9-88bd-30d1f3bf3f84.gif)

## Expected behavior
Shipping method should be visible on the cart.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
We must load the shipping methods `before` sending the totals request + using the `cart/refreshTotals` instead of `cart/serverTotals` no matter what. `cart/serverTotals` is not applying the shipping information -> https://github.com/DivanteLtd/vue-storefront/blob/86b6eee59450209f871e170d47c75a8b62859c0d/core/modules/cart/store/actions.ts#L443

**Comment by pkarw** [comment]
Fixed in the https://github.com/DivanteLtd/vue-storefront/pull/2887

**Comment by alinadivante** [comment]
@pkarw  I checked it on release/2513 but still I'm able to reproduce this issue.
I need to switch to other tab in my browser and return to Shopping cart to view DPD Courier information (for products with a lower price than the minimum order amount for free shipping)

**Comment by pkarw** [comment]
Ok, which product should I add to cart to reproduce this one on my env?

**Comment by alinadivante** [comment]
@pkarw Simply add a product under $ 20, e.g. Sprite Foam Yoga Brick

**Comment by pkarw** [comment]
OK, it seems like for this product Magento is returning empty shipping methods list: https://www.dropbox.com/s/lphljlvdq3hx51k/Screenshot%202019-05-31%2009.22.15.png?dl=0

I've changed the business logic to calculate the totals without the shipping info

**Comment by alinadivante** [comment]
@pkarw Now Shipping & Handling is immediately displayed, but the minimum order amount for free shipping is not taken into account

**Comment by pkarw** [comment]
We got the values from Magento: 

```
Response for: 1559741573870-efe811c2-324f-f022-34e8-60904ab82a5c = {"payment_methods":[{"code":"authorizenet_directpost","title":"Credit Card Direct Post (Authorize.net)"},{"code":"cashondelivery","title":"Cash On Delivery"}],"totals":{"grand_total":113,"base_grand_total":138.99,"subtotal":113,"base_subtotal":113,"discount_amount":0,"base_discount_amount":0,"subtotal_with_discount":113,"base_subtotal_with_discount":113,"shipping_amount":0,"base_shipping_amount":0,"shipping_discount_amount":0,"base_shipping_discount_amount":0,"tax_amount":25.99,"base_tax_amount":25.99,"weee_tax_applied_amount":null,"shipping_tax_amount":0,"base_shipping_tax_amount":0,"subtotal_incl_tax":138.99,"shipping_incl_tax":0,"base_shipping_incl_tax":0,"base_currency_code":"USD","quote_currency_code":"USD","items_qty":2,"items":[{"item_id":114330,"price":21,"base_price":21,"qty":1,"row_total":21,"base_row_total":21,"row_total_with_discount":0,"tax_amount":4.83,"base_tax_amount":4.83,"tax_percent":23,"discount_amount":0,"base_discount_amount":0,"discount_percent":0,"price_incl_tax":25.83,"base_price_incl_tax":25.83,"row_total_incl_tax":25.83,"base_row_total_incl_tax":25.83,"options":"[]","weee_tax_applied_amount":null,"weee_tax_applied":null,"name":"Sprite Yoga Strap 10 foot"},{"item_id":114331,"price":92,"base_price":92,"qty":1,"row_total":92,"base_row_total":92,"row_total_with_discount":0,"tax_amount":21.16,"base_tax_amount":21.16,"tax_percent":23,"discount_amount":0,"base_discount_amount":0,"discount_percent":0,"price_incl_tax":113.16,"base_price_incl_tax":113.16,"row_total_incl_tax":113.16,"base_row_total_incl_tax":113.16,"options":"[]","weee_tax_applied_amount":null,"weee_tax_applied":null,"name":"Dash Digital Watch"}],"total_segments":[{"code":"subtotal","title":"Subtotal","value":113},{"code":"shipping","title":"Shipping & Handling","value":0},{"code":"tax","title":"Tax","value":25.99,"area":"taxes","extension_attributes":{"tax_grandtotal_details":[{"amount":25.99,"rates":[{"percent":"23","title":"VAT23-PL"}],"group_id":1}]}},{"code":"grand_total","title":"Grand Total","value":138.99,"area":"footer"}]}}
```

**Comment by alinadivante** [comment]
@pkarw but if I see it well then it's order for a higher value of $ 20, so it should be free shipping.
What about cheaper products like **Overnight Duffle** SKU: 24-WB07 ?
![image](https://user-images.githubusercontent.com/36628922/59013869-74784d80-883b-11e9-822f-0b4c2d9df1fd.png)

**Comment by pkarw** [comment]
I don't have control over this :-( We just set the cart server side and get the totals back from Magento :-( They (Magento backend) now about the order value ;P

**Comment by alinadivante** [comment]
Ok, I understood, I just wanted to make sure it was not our fault :)

**Comment by pkarw** [comment]
Hopefully not! :D :D
