### ISSUE TITLE
Fix product page photo animation

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#287]
Right now, because photo has been changed to higher res during the animation we do have blinking effect or blank photo effect (eventually photo is loaded)

The higher res should be loaded just after the animation (we can use callback of transition component) or to disable the animation at once

**Comment by pkarw** [comment]
@filrak can you take a look at it after finishing checkout please?

**Comment by mercs600** [comment]
@pkarw I think https://github.com/DivanteLtd/vue-storefront/pull/288 should fix it.

**Comment by pkarw** [comment]
@mercs600 thanks, it's fine now!
