### ISSUE TITLE
|$NaN is displayed as the shipping method

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2881]
## Steps to reproduce the issue
1. In Magento set only one of Shipping Methods enabled (**but not** Flat Rate), for example enable:
**Table Rate**
2. Add any product to cart and go to checkout
3. Fill in all required fields, **but don't choose shipping method!** 
4. Click "Continue to payment"

## Current behavior
Customer is able to continue, without choosing shipping method.
|$NaN  is displayed as shipping method

![image (2)](https://user-images.githubusercontent.com/47415585/57437118-671e7200-7241-11e9-9d3c-e51483f6da79.png)

![shippingmethod](https://user-images.githubusercontent.com/47415585/57437230-a51b9600-7241-11e9-8f3a-7a6de4066d73.gif)

## Expected behavior
If only one shipping method is available, then it should be chosen by default.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome 73.0.3683.103
- OS: Windows 10 Pro
- Code Version: v1.9.0

**Comment by glevhen** [comment]
@alinadivante @pkarw  it's not bug, you just should update your config/default.json or config/local.json and set is as a default, vs takes shipping methods from config file not from magento
replace shipping node via
`
"shipping": {
    "methods": [
      {
        "method_title": "Title",
        "method_code": "bestway",
        "carrier_code": "tablerate",
        "amount": 0,
        "price_excl_tax": 0,
        "price_incl_tax": 0,
        "default": true,
        "offline": true
      }
    ]
  },
`
something like this
![image](https://user-images.githubusercontent.com/16398798/58718228-c2bdc480-83d5-11e9-98bc-a2c794af126d.png)

**Comment by alinadivante** [comment]
Ok, I changed the local configuration and you're right @glevhen, but anyway, I think that displaying $NaN in this situation is not right

**Comment by pkarw** [comment]
Fixed with the #2887

**Comment by alinadivante** [comment]
@pkarw above problem doesn't exist anymore, but when I enable only Table rate - I can't place order.
See errors:
![image](https://user-images.githubusercontent.com/36628922/59012413-b30c0900-8837-11e9-864e-f2606ab35b76.png)

(for Flat rate or Shipping free it is okay)

**Comment by pkarw** [comment]
Thanks, Alina! No idea why is that :-( Let's check it - maybe the reason is that the options isn't properly set while there is only one -  wrong default option set

**Comment by alinadivante** [comment]
**Steps to reproduce:**

1. In Magento Panel, set **Table Rate**  Shipping Method enabled  
2. Add any product to cart and go to checkout
3. Fill in all required fields and choose **Table Rate**  in Shipping Methods section
5. Try to place order

**Comment by alinadivante** [comment]
@Eugene you can check now this problem on https://test.storefrontcloud.io/

**Comment by glevhen** [comment]
@alinadivante will check

**Comment by glevhen** [comment]
@alinadivante seems it's again something wrong with your configurations, did you properly config magento/vsf-api? Did you run reindexing after you did changes in magento configurations? I see this error
`{code: 500, result: "Carrier with such method not found: bestway, tablerate"}` which caused the follow error when you try make an order `{"code":500,"result":"Error: Error while adding shipping address"} `
we use tablerate shipping method for our project and don't have any issues with it, so it seems like of the issue of your backend configurations

**Comment by pkarw** [comment]
Not sure why we had this error in Magento - but for Flatrate/Fixed it worrks just fine :/

**Comment by pkarw** [comment]
But probably: just probably - no rates have been imported for specific coutnry

**Comment by alinadivante** [comment]
yeah, it works! I checked tablerates.csv file and I chose specific country and I placed the order without errors! :)

**Comment by GabiDivante** [comment]
@pkarw there is still a problem - sometimes when I'm changing the country, the shipping method is not automatically chosen
![Peek 2019-06-18 12-23](https://user-images.githubusercontent.com/49188852/59674769-42b0a080-91c4-11e9-8e97-289b523a0d22.gif)

I can propose the solution implemented by @aniamusial  in our other project - button "continue to payment " is not active until any shopping method is chosen, what do you think?

**Comment by pkarw** [comment]
Fixed

**Comment by pkarw** [comment]
This is a good idea. We should apply both: #3073 and #3071

**Comment by patzick** [comment]
@pkarw please do not close issues with not merged PRs
