### ISSUE TITLE
Subscribe button - wrong size on tablet res.

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#2886]
## Current behavior

It's just a UI glitch - the width of Subscribe button need to be fixed

<img width="893" alt="Screenshot 2019-05-12 09 09 03" src="https://user-images.githubusercontent.com/211899/57578985-d68c9f80-7495-11e9-8b10-eb991915eb81.png">

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by patzick** [comment]
Thanks @exlo89! :)
