### ISSUE TITLE
Incorrect value of the reduced price in the cart

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2892]
## Current behavior

![Selection_031](https://user-images.githubusercontent.com/49188852/57618504-e84c7080-7583-11e9-85da-d27f8d705f60.png)

Currently, then reduced price visible in the cart is not correctly calculated:
**Reduced price = (net price * discount) + (net price * tax)**

**For example:**
Net product price is 24, tax (23%) is 5.92 - so the full price of the product is 29.92.
The customer adds a **50%** discount coupon.
Reduced price = (24 * 0,5) + (24 * 0,23) = 12 + 5,92 = 17,92

**Despite this, all values ​​shown in the summary are correct, the client pays the correct amount.**

## Expected behavior

The tax value should also be reduced by the discount.
**Reduced price = (net price * discount) + ((net price * discount) * tax)**
So the tax after the reduction is 2.76, and the correct reduced price of the product is 14.76.

## Steps to reproduce the issue

1. Go to https://demo.storefrontcloud.io/
2. Add any product to the cart
3. Apply discount code 'mmtest' (-50% discount)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 73
- OS: Ubuntu 18.04 LTS

## Additional info 
The same happens when any other discount rule is applied (any cart or catalog price rule).

**Comment by pkarw** [comment]
I'd suggest starting checking how `Microcart/Product.vue` displays the special prices - then go thru `taxcalc.js` to check  if we don't have a flaw there; checking the Magento2 tax settings would be also recommended

**Comment by pkarw** [comment]
Fixed! :)

**Comment by GabiDivante** [comment]
@pkarw It works fine :) Though, I haven't thought about the order summary in the checkout, we have to change it the same way
![Selection_038](https://user-images.githubusercontent.com/49188852/58004539-be470100-7ae3-11e9-86cd-8b1935f0f972.png)
By the way, take a look at my comments in #2874 - we have to solve the problem of displaying reduced prices (or correct value of discount) in instant checkout.
