### ISSUE TITLE
Changing the quantity of the product in the cart doesn't change its price (offline mode)

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2896]
## Current behavior

In offline mode, changing the quantity of the product in the cart does not change its price. Grand total is changing properly. 
Gif:  https://drive.google.com/file/d/1nxMzu9E0AOw-knQF3EGhUqCfjqlOI6I3/view?usp=sharing

## Expected behavior

In offline mode, changing the quantity of the product in the cart change its price as well.

## Steps to reproduce the issue

1. Go to branch develop
2. Add any product to cart
3. Change the Qty and look at how Product price and Grand total are changing
4. Go to offline mode
5. Change the Qty and look at how Product price and Grand total are changing

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome73
- OS:Ubuntu 18.04 LTS

## Additional information

This issue doesn't appear on demo. Maybe related to #2828

**Comment by pkarw** [comment]
Change the `Microcart/Product.vue` and how it handles the offline mode

**Comment by GabiDivante** [comment]
@pkarw Here, I have also forgotten about the order summary in the checkout - the quantity of the product is correct but the price is not.
![Peek 2019-05-20 10-49](https://user-images.githubusercontent.com/49188852/58008573-f999fd80-7aec-11e9-9178-0c72b0a6d8b0.gif)

**Comment by pkarw** [comment]
Thanks! Fixed on branch https://github.com/DivanteLtd/vue-storefront/pull/2887
