### ISSUE TITLE
Products removed from the cart in the offline mode are re-added to the cart after going back to online mode

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2898]
## Current behavior

Products removed from the cart in the offline mode are re-added to the cart after going back to online mode
![Peek 2019-05-14 13-09](https://user-images.githubusercontent.com/49188852/57694590-67a57700-764c-11e9-8ec7-cbd97971d99c.gif)

## Expected behavior

Products removed from the cart in the offline mode are not re-added to the cart after going back to online mode. The customer sees the same cart state as in offline mode. 

## Steps to reproduce the issue

1. Go to https://demo.storefrontcloud.io
2. Go to any product page
3. Add a few products to the cart
4. Switch to the offline mode
5. Remove some of the products from the cart
6. Switch back to the online mode
7. Check your cart 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 73
- OS: Ubuntu 18.04 LTS

**Comment by pkarw** [comment]
It might be like this! We should run the `cart/serverPull` with the `forceClientState=true` when user switched back online

**Comment by pkarw** [comment]
https://github.com/DivanteLtd/vue-storefront/blob/41ee559a8cf691a19a24ff057f1c7d8f664e37c1/core/modules/offline-order/helpers/onNetworkStatusChange.ts#L13

**Comment by alinadivante** [comment]
Verified on bugfix/2898
