### ISSUE TITLE
There is problem with displaying available products when "listOutOfStockProducts": false

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2905]
## Steps to reproduce the issue

1. Change "listOutOfStockProducts":  from true to **false** in local.json file
2. Run VSF locally and click on "Tiffany Fitness Tee" from Everything new section 
3. Click on **Tees** in breadcrumbs to open sub-category
→  Default Category / Women / Tops / Tees 
4. Again open Tiffany Fitness Tee product 
5. Refresh the page

## Current behavior
There is problem with displaying available products.
"No available product variants" information is displayed on product page, but when I refresh page then I see two variants of my product.
![listOutOfStockProducts](https://user-images.githubusercontent.com/49188852/57758742-b1e43200-76f8-11e9-8a2c-776795f12176.gif)

## Expected behavior
Only available products should be displayed.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
This is the correct behavior. The variants stock is synced asynchronously when browsing thru products catalog. If there would be the dynamic `magento2-vsbridge-indexer` running in the background this situation wouldn't have happened. I mean - the products on the list are displayed based on ElasticSearch stock data. If it's not updated - there could be a situation that products avaialble in the Elastic are no longer available in Magento - the situation You've reported.
