### ISSUE TITLE
Category page is not available when "useShortCatalogUrls" is set on true

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2907]
## Steps to reproduce the issue
1. Open local.json and set **_true_** for "useShortCatalogUrls"
2. Save changes and run VSF locally 
3. Click on banners from Homepage 
4. Go to Women category → view all

## Current behavior
"The product, category or CMS page is not available in Offline mode. Redirecting to Home."
I can't go to the main categories, because there are probably hardcoded redirects to addresses, like: http://localhost:3000/c/ women-20 (and I set options for URL generation without prefixes / p / and / c /).

![image](https://user-images.githubusercontent.com/36628922/57830010-106ce700-77b1-11e9-8ed3-99cdd517669c.png)

## Expected behavior
I should be redirected to desired category page, with properly URL.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
This is not an issue. This mode is not compliant with the `useUrlDispatcher`. @kkdg please make sure we have a note on that in our docs (https://github.com/DivanteLtd/vue-storefront/blob/master/docs/guide/basics/configuration.md) 

It was mentioned in the https://github.com/DivanteLtd/vue-storefront/blob/master/docs/guide/basics/url.md - however, it's not visible enough :/

**Comment by kkdg** [comment]
@pkarw noted, this will be documented at *Chapter 7. Common pitfalls* Thanks!
