### ISSUE TITLE
Some structured data not available in product view

### ISSUE THREAD

**Issue by pmaojo** [DivanteLtd/vue-storefront#2910]
## Current behavior

Current missing fields on Structured Data

![Captura de pantalla 2019-05-16 a las 13 11 04](https://user-images.githubusercontent.com/411551/57852881-3b206500-77dc-11e9-9d42-1d9c9ae1fe6e.png)

## Expected behavior

Add all possible fields. url, image..

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [X] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
Hi @pmaojo could You please be more specific? :-) What do You mean by this and how do You see the actionable items regarding these fields? Adding the fields to Product page?

**Comment by pmaojo** [comment]
If you open https://search.google.com/structured-data/testing-tool/?hl=es#url=https%3A%2F%2Fdemo.storefrontcloud.io%2Fwomen%2Ftops-women%2Ftees-women%2Ftees-25%2Ftiffany-fitness-tee-1513.html%3FchildSku%3DWS09 Google warns that there is some info about the product that is not shared as structured data.

**Comment by pmaojo** [comment]
Well, this is not a bug really, 
It could be an enhancement, so its a feature request.

**Comment by pkarw** [comment]
OK, now I get it so it's all about setting up the proper micro-schema / metadata

**Comment by cewald** [comment]
We try to fill in the missing data.
Not all suggestions could be fulfilled with the demo data, but at least some.

**Comment by patzick** [comment]
Thanks @cewald !
