### ISSUE TITLE
Add to cart in a product of "Video Downloads" not working. 

### ISSUE THREAD

**Issue by pmaojo** [DivanteLtd/vue-storefront#2912]
## Current behavior

When click on Add to Cart. An error card promots.

## Expected behavior

Product added to cart or real error displayed.

## Steps to reproduce the issue

Go to https://next.storefrontcloud.io/training/training-9/luma-yoga-for-life-51.html
Click "Add to Cart"

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [X] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome
- OS: OSX
![Captura de pantalla 2019-05-16 a las 14 01 16](https://user-images.githubusercontent.com/411551/57855851-8db14f80-77e3-11e9-81b2-05330bd9c3f3.png)
![Captura de pantalla 2019-05-16 a las 14 01 09](https://user-images.githubusercontent.com/411551/57855852-8db14f80-77e3-11e9-8c9b-c503995b6b8b.png)

**Comment by alinadivante** [comment]
@pmaojo This was due to the wrong product configuration in Magento. Now you can add this product to the cart :)
