### ISSUE TITLE
Improve Size Guide feature to prevent loosing product options selected by user

### ISSUE THREAD

**Issue by pmaojo** [DivanteLtd/vue-storefront#2913]
## What is the motivation for adding / enhancing this feature?

In a product page, If a user selects options( color and size for example) and clicks on "size guide" link: 
- the link to guide is opened on the same window.
- A  sidebar with links is shown atf. In mobile view that sidebar would have to go down, not before content.
- no go back to product button
- if I click back on browser, I see my choices have gone so I have to choose again

## What are the acceptance criteria 

- [ ] user can see size guide without loosing product view and options selected

I think of two alternatives to solve this:
- add target="_blank" to link
- open size guide as a sideslider or popup

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by RGijsberts** [comment]
working on it

**Comment by RGijsberts** [comment]
I will work on this
