### ISSUE TITLE
Tax price fields have wrong naming convention

### ISSUE THREAD

**Issue by fancydev18** [DivanteLtd/vue-storefront#2918]
## Current behavior

Some object attributes don't respect the naming convention used by all others (underscore, not camelCase)
They are:
```
priceInclTax 
priceTax 
specialPriceInclTax 
specialPriceTax
```

## Expected behavior

Respect naming convention used by all others, eg price_incl_tax

## Steps to reproduce the issue

1. Open network inspector
2. Visit
https://demo.vuestorefront.io/gear/gear-3/joust-duffle-bag-1.html

3. See response in
https://demo.storefrontcloud.io/api/catalog/vue_storefront_catalog/product/_search?_source_exclude=%2A.msrp_display_actual_price_type%2Crequired_options%2Cupdated_at%2Ccreated_at%2Cattribute_set_id%2Coptions_container%2Cmsrp_display_actual_price_type%2Chas_options%2Cstock.manage_stock%2Cstock.use_config_min_qty%2Cstock.use_config_notify_stock_qty%2Cstock.stock_id%2Cstock.use_config_backorders%2Cstock.use_config_enable_qty_inc%2Cstock.enable_qty_increments%2Cstock.use_config_manage_stock%2Cstock.use_config_min_sale_qty%2Cstock.notify_stock_qty%2Cstock.use_config_max_sale_qty%2Cstock.use_config_max_sale_qty%2Cstock.qty_increments%2Csmall_image%2Csgn%2C%2A.sgn&from=0&request=%7B%22query%22%3A%7B%22bool%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22terms%22%3A%7B%22category_ids%22%3A%5B4%2C3%5D%7D%7D%2C%7B%22terms%22%3A%7B%22visibility%22%3A%5B2%2C3%2C4%5D%7D%7D%2C%7B%22terms%22%3A%7B%22status%22%3A%5B0%2C1%2C2%5D%7D%7D%5D%7D%7D%7D%7D%7D&size=8&sort=

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
We'll take care of that by the refactoring efforts. We'll apply the following changes:

- `priceInclTax` -> `price_incl_tax`
- `priceTax` -> `price_tax`
- `specialPriceInclTax` - `special_price_incl_tax`
- `specialPriceTax` - `special_price_tax`

We'll keep the older property names as depreciated for some time (would be awesome to add the eslint rule for checking the property names)

**Comment by pkarw** [comment]
Will be closed with #3156

**Comment by alinadivante** [comment]
@pkarw I checked changes on  Bugfix/2918 branch
but there are still names like: priceInclTax, priceTax, specialPriceInclTax, specialPriceTax

https://demo.storefrontcloud.io/api/catalog/vue_storefront_catalog/product/_search?_source_exclude=%2A.msrp_display_actual_price_type%2Crequired_options%2Cupdated_at%2Ccreated_at%2Cattribute_set_id%2Coptions_container%2Cmsrp_display_actual_price_type%2Chas_options%2Cstock.manage_stock%2Cstock.use_config_min_qty%2Cstock.use_config_notify_stock_qty%2Cstock.stock_id%2Cstock.use_config_backorders%2Cstock.use_config_enable_qty_inc%2Cstock.enable_qty_increments%2Cstock.use_config_manage_stock%2Cstock.use_config_min_sale_qty%2Cstock.notify_stock_qty%2Cstock.use_config_max_sale_qty%2Cstock.use_config_max_sale_qty%2Cstock.qty_increments%2Csmall_image%2Csgn%2C%2A.sgn&from=0&request=%7B%22query%22%3A%7B%22bool%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22terms%22%3A%7B%22category_ids%22%3A%5B4%2C3%5D%7D%7D%2C%7B%22terms%22%3A%7B%22visibility%22%3A%5B2%2C3%2C4%5D%7D%7D%2C%7B%22terms%22%3A%7B%22status%22%3A%5B1%5D%7D%7D%5D%7D%7D%7D%7D%7D&size=8&sort=

**Comment by pkarw** [comment]
Hi! Thanks for testing this out! @alinadivante this is intended behavior, there is a `config.tax.deprecatedPriceFieldsSupport` set to `true` in the `vue-storefront-apii` for the backward compatibility purposes. When set to `false` there won't be any of these fields anymore

**Comment by alinadivante** [comment]
Thanks @pkarw ! Please include information such as  **_test instructions_** next time, if there is something what we need to change in config or something like that - let us know! :)
Now I have problem with vue-storefront-api (problem with data migration) I have to wait for @lukeromanowicz time/help ;)
