### ISSUE TITLE
No additional data adapter for category error on api

### ISSUE THREAD

**Issue by heromiyo** [DivanteLtd/vue-storefront#2920]
## Current behavior
I setup storefront and api and connected to my magento instance.
when i do run both storefront and api am getting this error 
on vue-storefront-api

No additional data adapter for category
Entering HmacProcessor::process
![image](https://user-images.githubusercontent.com/39757927/57997118-9795c400-7afd-11e9-8d57-7c7d1d71e9b1.png)

 vue-storefront 
Error: Category query returned empty result url_path = sw.js
    at server-bundle.js:5927:36
    at process._tickCallback (internal/process/next_tick.js:68:7) 
![image](https://user-images.githubusercontent.com/39757927/57997150-b300cf00-7afd-11e9-9de1-e1469418739a.png)

## Expected behavior
expected it to work with categories and not crash

## Steps to reproduce the issue
cd vue-storefront-api
yarn dev 
cd vue-storefront
yarn dev 
connected to latest version of magento

## Repository
working with the master branch of vue-storefront 

## Can you handle fixing this bug by yourself?

-
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
This is not an error. Url Dispatcher tries to find out the category for `sw.js` url path - and the category doesn't exist. Do You have a category with `url_path` = `sw.js`? 

The message from `vue-storefront-api` -> "No additional data adapter for category" is a debug message not an error either

**Comment by pkarw** [comment]
[](url)
