### ISSUE TITLE
After refreshing page, some information disappears from the shopping summary.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2921]
## Relates to:
#2869 

## Steps to reproduce the issue
1. Disable Flat rate Shipping method in Magento panel (set only Free shipping active)
2. Add any product to the cart
3. Open Shopping cart
4. Refresh page
5. Again open Shopping cart

## Current behavior
Some information (Shipping & Handling, Tax and Discount code) are removed from Shopping summary.
![image](https://user-images.githubusercontent.com/36628922/57998855-7b7d2d00-7ad3-11e9-9cf7-0fb47f127f29.png)

(If you switch to another tab in the browser for a moment, all information will be restored after returning to VSF)

![cart](https://user-images.githubusercontent.com/36628922/57998868-8932b280-7ad3-11e9-8763-8e77d258a3bb.gif)

## Expected behavior
All information should be displayed in Shopping summary.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
It's probably fixed with the https://github.com/DivanteLtd/vue-storefront/pull/2887

Can You please check it on the branch?

**Comment by alinadivante** [comment]
Yep, now it works ;)
