### ISSUE TITLE
Trying to setup a multistore environment with multiple urls and stores

### ISSUE THREAD

**Issue by haelbichalex** [DivanteLtd/vue-storefront#2924]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Is there something you don't understand? What is it? Describe it.	

Related issue: #2870 

We are trying to setup a multistore environment based on Magento 2. Important: It's not multi-language, but multi-website, because we also want to share the cart between the shops.

I set up two dev domains `vs.web.guf.t23dev` and `vs.web.piolo.t23dev` to match our stores and the following apache config to set the `x-vs-store-code` variable:

``` apacheconf
SetEnvIf Host vs\.web\.guf\.t23dev MAGE_STORE_CODE=guf
SetEnvIf Host vs\.web\.guf\.t23dev MAGE_IS_GUF=1
SetEnvIf Host vs\.web\.piolo\.t23dev MAGE_STORE_CODE=piolo
SetEnvIf Host vs\.web\.piolo\.t23dev MAGE_IS_PIOLO=1

ProxyPreserveHost On
RequestHeader set x-vs-store-code "guf" env=MAGE_IS_GUF
RequestHeader set x-vs-store-code "piolode" env=MAGE_IS_PIOLO
```

Also here's my `storeViews` setup from `config/local.json`:

``` json
"storeViews": {
    "multistore": true,
    "mapStoreUrlsFor": [],
    "guf": {
      "storeCode": "guf",
      "disabled": false,
      "storeId": 2,
      "name": "Garten und Freizeit",
      "url": "/",
      "elasticsearch": {
        "host": "http://app.guf-storefront-api.t23dev:18080/api/catalog",
        "index": "vue_storefront_catalog_guf"
      },
      "tax": {
        "defaultCountry": "DE",
        "defaultRegion": "",
        "calculateServerSide": true,
        "sourcePriceIncludesTax": false
      },
      "i18n": {
        "fullCountryName": "Germany",
        "fullLanguageName": "German",
        "defaultLanguage": "DE",
        "defaultCountry": "DE",
        "defaultLocale": "de-DE",
        "currencyCode": "EUR",
        "currencySign": "EUR",
        "dateFormat": "HH:mm D-M-YYYY"
      }
    },
    "piolo": {
      "storeCode": "piolo",
      "disabled": false,
      "storeId": 3,
      "name": "Piolo",
      "url": "/",
      "elasticsearch": {
        "host": "http://app.guf-storefront-api.t23dev:18080/api/catalog",
        "index": "vue_storefront_catalog_piolo"
      },
      "tax": {
        "defaultCountry": "DE",
        "defaultRegion": "",
        "calculateServerSide": true,
        "sourcePriceIncludesTax": false
      },
      "i18n": {
        "fullCountryName": "Germany",
        "fullLanguageName": "German",
        "defaultLanguage": "DE",
        "defaultCountry": "DE",
        "defaultLocale": "de-DE",
        "currencyCode": "EUR",
        "currencySign": "EUR",
        "dateFormat": "HH:mm D-M-YYYY"
      }
    }
  }
```

When I log the [storecode](https://github.com/DivanteLtd/vue-storefront/blob/0689665ab0936c1d3dfcc9028dafc57bab4aee4a/core/scripts/server.js#L160) in the `core/scripts/server.js` I also see the correct store_code is set.

Now when I start up the servers and open the application in the browser, I see in the api logs, there are only requests to the `vue_storefront_catalog` index, not to `vue_storefront_catalog_guf`.

I tried to log some details in vue-storefront-api [here](https://github.com/DivanteLtd/vue-storefront-api/blob/master/src/platform/magento2/util.js), but It wouldn't display anything.

___

Can someone explain, what I need to do to get this up and running?
Is a multistore with different urls and shared cart in vs even possible?
Do we maybe need to setup multiple instances of vs and or vs-api?

Regards

**Comment by grimasod** [comment]
In local.json, you need to enter mapStoreUrlsFor with a code for for each store, e.g.
```
"mapStoreUrlsFor": ["guf", "piolo"]
```
That should get you started with requesting the specified index.

We are running a multi-store site on a single domain, so I'm not sure about using different domain names. I guess it will create some challenges, because the browser will treat them as separate sites. The cart can still be synchronized via Magento 2, but not the browser sessions, so users would have to login to each site separately, for example. Also VS will still need the store code to be appended to the URL, in order to determine the current store, like https://example.com/piolo/etc

In the end, it might be easier and cleaner to run 2 instances of VS, if it's only 2. A single instance of VS-API is fine.

Finally, I recommend using Nginx instead of Apache. In my experience, it's much easier and well worth the effort to switch over, even if it takes a little time learning it initially. That's just my personal opinion, of course.

**Comment by haelbichalex** [comment]
Thanks for your answer @grimasod.

> In local.json, you need to enter mapStoreUrlsFor with a code for for each store

Hm, I tried this, didn't change anything though.

> Also VS will still need the store code to be appended to the URL, in order to determine the current store, like https://example.com/piolo/etc

I thought that's what the request header `x-vs-store-code` is for. That's why I set this based on the URL. 

> In the end, it might be easier and cleaner to run 2 instances of VS, if it's only 2. A single instance of VS-API is fine.

Maybe that's the best option, if we're able to synchronize the carts as well. I think Magento does this via the Session ID.
___

Does somebody know if Vue Storefront supports shared carts  in general?

**Comment by pkarw** [comment]
@haelbichalex shared carts are supported by default. It should work as you described with two separate instances.

VS should be able to select the current store via: url, “x-vs-store-code” or env variable

**Comment by pkarw** [comment]
It might be of course an issue with switching the store by http header - it requires some debugging across server-entry and client-entry where the store is set - please feel free to dig a little bit deeper

**Comment by haelbichalex** [comment]
@pkarw allright, I'll try to make it work with two instances then. 👍

**Comment by grimasod** [comment]
By the way, as far as I know, it's still necessary to set "availableStores" and "storeViews" in local.json for VS-API for it to handle multiple stores on the Magento side.

I wasn't aware of the "x-vs-store-code" header, so haven't tried it out
