### ISSUE TITLE
magento2-rest-client shouldn't be required in package.json

### ISSUE THREAD

**Issue by fancydev18** [DivanteLtd/vue-storefront#2927]
# Summary
[summary]: #summary

magento2-rest-client shouldn't be required in package.json

# Motivation
[motivation]: #motivation

vue-storefront should be backend-agnostic. Backend could be magento, vue-storefront-api, bigcommerce or anything else.

# Alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

magento2-rest-client is used only in installer.js validateM2Integration()
Maybe that can be separated in a different script, with it's own requires. It seems best to place it in magento2-bridge, since that's the backend supporting magento.

Thanks!

**Comment by pkarw** [comment]
Thanks. It seems like unnecessary dependency - that’s true. However this dependency isn’t bundled in the app (it’s just used by the installer script). I don’t see much benefits removing this dependency and replacing it with (for example) a direct curl call.
