### ISSUE TITLE
Add to cart fails indefinitely for all products once an existing product in cart is deleted from Magento

### ISSUE THREAD

**Issue by nikhilbansal** [DivanteLtd/vue-storefront#2930]
## Current behavior
Add to cart fails indefinitely for all new products once an existing product in cart is deleted from Magento
{"code":500,"result":"The product that was requested doesn't exist. Verify the product and try again."}

## Expected behavior
Should be able to add other products to cart once an existing product in cart is deleted from Magento

## Steps to reproduce the issue
1. Go to vsf and add one product to cart
2. Go to Magento admin and delete the same product
3. Run mage2vs(optional, doesn't matter)
4. Go to vsf and browse any other product and try adding it to cart and it will fail.

## Repository
This is happening because when we delete the product from Magento, it's not deleted from the quote_item table of Magento.

## Can you handle fixing this bug by yourself?
Yes, need some guidance.

## Environment details
Browser: Version 73.0.3683.103 (Official Build) (64-bit)
OS: Mac OS X
Node: v8.10.0
Magento: 2.3.1
Code Version: latest master

**Comment by pkarw** [comment]
This seems like an Magento issue. Please check magento2 github and create an issue when necessary. If the product is being removed from quote we sync it in VS - by some reason Magento is keeping the non-existing products in the quote and this causes an issue
