### ISSUE TITLE
Replace ElasticSearch with Algolia

### ISSUE THREAD

**Issue by Ravin0319** [DivanteLtd/vue-storefront#2931]
Need your comments/steps to remove ElasticSearch and Replace with Algolia in the entire Store.
https://www.algolia.com/doc/guides/building-search-ui/getting-started/vue/

I spent some time trying to debug the searchPanel and the search.ts file and the functions to understand where the connection is made to Elasticsearch but was not successful.

What i am trying to do is remove ElasticSearch entirely and replace with Algoliasearch without breaking anything. The only difference is the Products data is returned from Algolia API.

is there anything i should also change in the vuestorefront-api ?

Please help!

**Comment by pkarw** [comment]
Would be great to have such a module as an open source. I thought the easiest way would be to create a `src/modules/algolia` module and put the UI components + Vuex store (for querying Algolia) just in there. So not trying to bind Algolia to VS directly but rather connect it as another UI Search feature (changing the Search component in the theme to this new one).

More comprehensive but also more complicated option is to create a copy of `vue-storefront-api/src/api/catalog` endpoint and do there two things: first query Algolia with the search query (unfortunatelly the qureies come with the ElasticSearch DSL format currently so it's need to be somehow parsed) -> execute the search in Algolia -> extend the results with data got from ElasticSearch (query by product ids then - the ids' returned by Algolia). It's maybe not optimal but it won't require much changes on the frontend in the opposite to the option number one.

**Comment by Ravin0319** [comment]
Hi @pkarw 

Many thanks for responding!

I like the first option where the algolia is just a Search module. i will try this now and let you know if i was successful.

How can i connect Algolia data with Vuex store? Do we have docs explaining something similar to this? and what is benefit by doing this?


Also, I am trying to understand what this below line does in file:- 
vue-storefront/core/modules/catalog/components/Search.ts

function/method name: makeSearch()

Stuck at understanding the below line:-
this.$store.dispatch('product/list', { query, start: this.start, size: this.size, updateState: false }).then(resp => {})

Please throw some light on me 😢 

Many Thanks!!

**Comment by pkarw** [comment]
Hi Ravin You should create Your own module with your own view data store and implement your Vuex actions like “agolia/search” instead of “product/list”. You won’t probably need to “touch” elastic endpoints either vs api at all. API requests should be executed only from the vuex actions - in this case vuex actions from your module. Take a look on how “src/module-template” is extending vuex and follow this path

**Comment by Ravin0319** [comment]
@pkarw Thank you, You're inputs helped! 

I was able to create my own module with store/actions to perform API calls and call this from my module ui components.

**Comment by pkarw** [comment]
Thanks for Your feedback. Great to hear that
