### ISSUE TITLE
Make "browse our catalog" as blue link.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2932]
## What is the motivation for adding / enhancing this feature?
When the wish list or shopping cart is empty, the user can start browsing with one click on the "browse our catalog" link, but now we only have the hover effect on it. It will be better to highlight the "browse our catalog" link permanently.

![image](https://user-images.githubusercontent.com/36628922/58157101-ee270d80-7c77-11e9-80f7-313d9e67ba46.png)

## What are the acceptance criteria 
![image](https://user-images.githubusercontent.com/36628922/58157009-bae47e80-7c77-11e9-8373-6b3ffe530131.png)
Let the "browse our catalog" link be blue.

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pmaojo** [comment]
I think this should be applied to all links.
As a standard, I would like the color of all links default _primary_ everywhere and bold.

**Comment by Hackbard** [comment]
I will try to take care of it.

**Comment by patzick** [comment]
Thanks @Hackbard ! ;D
