### ISSUE TITLE
As a user I want to choose number of columns of products I see on the category view

### ISSUE THREAD

**Issue by pmaojo** [DivanteLtd/vue-storefront#2934]
## What is the motivation for adding / enhancing this feature?
[not for mobile]

The number of columns determine two aspects:

- Size of product image thumbnails on the category page. Less columns - bigger images.
- Amount of products displayed. More columns - more products visible.

Could different column layout affect site ROI? It must affect. But there cannot be a generic rule for this, each e-commerce belongs to different markets, different users, different products, this should be adaptative to each business model.

How can we enhance this to develop an intelligent solution that maximizes clicks on products?

v1 - As I user I want to select the number of columns. (this could be a good start)
v1- As I user I want my selection to be remembered

v2- As a product owner I would like to get data on which column configuration got more sells (by cart total), which was the most selected among users, and decide default columns and available numbers.

v3- As a product owner I dream that we could use Tensorflow to bring some machine learning to this and other components.

![Captura de pantalla 2019-05-22 a las 10 39 30](https://user-images.githubusercontent.com/411551/58164539-ec604880-7c7d-11e9-8543-af00f3f02839.png)
## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**### What do you think?**

**Comment by heyfets** [comment]
I'll take it.

**Comment by alinadivante** [comment]
@heyfets  maybe @StasiekDivante will suggest some graphic solution like image-size?
![image](https://user-images.githubusercontent.com/36628922/58329256-705c3100-7e34-11e9-9470-2cfa15c4f0be.png)

**Comment by StasiekDivante** [comment]
@alinadivante not sure what's the issue here, could you elaborate?

**Comment by alinadivante** [comment]
@StasiekDivante  I want to ask if you have any suggestions/ideas how we can do selection options for displaying the number of products columns on the category page?
Which solution is better?
![image](https://user-images.githubusercontent.com/36628922/58537591-71ee7600-81f3-11e9-82a8-856e10020aa6.png)
 or 
![image](https://user-images.githubusercontent.com/36628922/58537615-803c9200-81f3-11e9-8dd4-dc76368228c5.png)

**Comment by StasiekDivante** [comment]
I believe numbers are a better solution here, as the meaning of icons might not be clear in this case

**Comment by pmaojo** [comment]
> I believe numbers are a better solution here, as the meaning of icons might not be clear in this case
I agree

**Comment by alinadivante** [comment]
@vishal-7037 IMHO products column change functionality is located in wrong place and it doesn't look good. Maybe we can move it a little bit closer to Sort by option? (but at the same time remembering about changes from issue #2935 )

**Comment by StasiekDivante** [comment]
@alinadivante could you share a screenshot how it looks now?

**Comment by alinadivante** [comment]
@StasiekDivante  
![image](https://user-images.githubusercontent.com/36628922/58945465-32d89b80-8784-11e9-9c4e-413ad534698d.png)

**Comment by StasiekDivante** [comment]
@alinadivante yeah, just go on and move it closer to **sort by**

**Comment by pmaojo** [comment]
I suggest also aligning both inputs horizontally with the title "Women"

**Comment by StasiekDivante** [comment]
![Screenshot 2019-06-05 at 11 27 41](https://user-images.githubusercontent.com/37068687/58945859-f5c0d900-8784-11e9-9bf5-941e8f7b18f8.png)
Sure thing @pmaojo! I made a simple graphic to help you with this

**Comment by vishal-7037** [comment]
@alinadivante , @StasiekDivante 
Okay, Working on it.

**Comment by pmaojo** [comment]
![Captura de pantalla 2019-06-05 a las 10 30 08](https://user-images.githubusercontent.com/411551/58946034-f5244480-877c-11e9-8fdd-66f9cc6dd199.png)

**Comment by pmaojo** [comment]
@StasiekDivante yes :D

**Comment by StasiekDivante** [comment]
@pmaojo tbh It would be more visually pleasing if you had text lying on one baseline (check img from my previous post), I wouldn't mind underlines going beneath this text baseline 😄

And vertically it's perfect!

**Comment by vishal-7037** [comment]
@StasiekDivante ,
So no need to work on alignment issue. right?

**Comment by StasiekDivante** [comment]
Hey @vishal-7037, this is how it is now:
![is](https://user-images.githubusercontent.com/37068687/58947189-b647bc00-8787-11e9-9f00-b1c72ca4d4be.png)

and that's how it should be:
![should](https://user-images.githubusercontent.com/37068687/58947198-bcd63380-8787-11e9-9d33-c5fd96c0b913.png)

**Comment by vishal-7037** [comment]
@StasiekDivante Okay, Got it.

**Comment by StasiekDivante** [comment]
@vishal-7037 sure, it just needs vertical and horizontal alignment

**Comment by alinadivante** [comment]
@vishal-7037 Please remember to take into account changes regarding: #2935 
Sort by will be looks like on this screenshot
![image](https://user-images.githubusercontent.com/36628922/58948014-7f72a580-8789-11e9-9764-7d5ee0588054.png)

**Comment by vishal-7037** [comment]
@alinadivante, @StasiekDivante I've updated design as per your suggestion and also according to https://github.com/DivanteLtd/vue-storefront/issues/2935

Please review and let me know.

Thank you.

**Comment by alinadivante** [comment]
@vishal-7037 thank u for your fixes :)
