### ISSUE TITLE
Display default "Sort by" criteria on Sort by selector, on category view

### ISSUE THREAD

**Issue by pmaojo** [DivanteLtd/vue-storefront#2935]
## What is the motivation for adding / enhancing this feature?

As I user, before changing sorting criteria I would like to know how is it actually sorted.

## What are the acceptance criteria 

- [ ] display a label with the property used to sort products.

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
Not quite get it - there is a combo box with this: https://www.dropbox.com/s/geguyamqpomebv8/Screenshot%202019-05-22%2013.53.42.png?dl=0

**Comment by alinadivante** [comment]
@pkarw I think that the point is to display information on how the products are sorted by default ;)

**Comment by pmaojo** [comment]
hi! 
Yes, @alinadivante

**Comment by alinadivante** [comment]
Hi guys, "Sort by" label is gone after merge into Develop
![image](https://user-images.githubusercontent.com/36628922/59268309-c3afeb00-8c4c-11e9-8abd-1f63a8f7b277.png)
Could you fix it @cnviradiya ?

**Comment by pkarw** [comment]
I removed it, It looked awfull
