### ISSUE TITLE
Yarn fails on cloned code.

### ISSUE THREAD

**Issue by lucassith** [DivanteLtd/vue-storefront#2938]
## Current behavior
```
 λ yarn
yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error https://tgz.pm2.io/gkt-1.0.0.tgz: Request failed "503 Service Unavailable"
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
error An unexpected error occurred: "ENOENT: no such file or directory, open '/yarn/v4/npm-gkt-1.0.0-405502b007f319c3f47175c4474527300f2ab5ad/node_modules/gkt/.yarn-metadata.json'".
info If you think this is a bug, please open a bug report with the information provided in "/shops/storefront/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

## Expected behavior
Yarn installs all of the dependencies

## Steps to reproduce the issue
https://docs.vuestorefront.io/guide/installation/linux-mac.html#user-friendly-installation

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- OS: Debian 9 Jessie 
- Node: 10.11.0 | Yarn 1.15.2
- Code Version: master

**Comment by lukeromanowicz** [comment]
@lucassith It looks like a temporary pm2 repository issue. It seems to be already working back again. Please try again.
