### ISSUE TITLE
Placeholders are no longer shown

### ISSUE THREAD

**Issue by Jensderond** [DivanteLtd/vue-storefront#2939]
## Current behavior
The [ProductTile.vue](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/components/core/ProductTile.vue) now never shows the placeholder because of `product-image--loaded` always being in the class.

I believe this is related to #2641 .

https://github.com/DivanteLtd/vue-storefront/blob/17b7ab198c516bd9f0738f6d39d3914331cf8792/src/themes/default/components/core/ProductTile.vue#L62

When this value is changed back to `false` the placeholders appear again.

## Expected behavior
Placeholders should be shown.

## Steps to reproduce the issue
This also happens on https://demo.vuestorefront.io/

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by patzick** [comment]
Thanks @Jensderond, i've merged that to 1.9.1

**Comment by pkarw** [comment]
The placeholders are not displayed in the products gallery when clicking related products (CSR) - I wrote more on this issue to You @patzick on Slack

**Comment by patzick** [comment]
This will be fixed with 1.10 and #2925 used everywhere with pictures.
