### ISSUE TITLE
Product does not exist - Magento 2

### ISSUE THREAD

**Issue by bellodaniel** [DivanteLtd/vue-storefront#2941]
## Current behavior

After Integrating Magento with Vue JS, everything looks good. However, I am getting an error when trying to add a product to the cart.
https://cl.ly/995d660fffbc
I get a 'Product not found' error, which is weird because actually, I am at the product page.

## Expected behavior

The add to cart operation should go through I should be able to add a product to the cart and go to checkout.

## Steps to reproduce the issue

Integrate Magento 2 with Vue JS, using this tutorial https://medium.com/the-vue-storefront-journal/vue-storefront-how-to-install-and-integrate-with-magento2-227767dd65b2
Go to the product page and try to 'Add to cart'

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  Chrome, Safari, Firefox(all browsers)
- OS:  MAC 
- Node: 10.15.3
- Code Version: Magento version 2.3.1

**Comment by Jensderond** [comment]
I've never had this error, could you check if there is anything in the logs from the API or the logs of Magento?

**Comment by bellodaniel** [comment]
@Jensderond I am reviewing the Magento logs but I don't see any error related to this:
https://cl.ly/cc93c8532bf1
https://cl.ly/d12ff0bea3b6
Wheres on vue-storefront/var/log the two files vue-storefront.log and vue-storefront-api.log are empty.
I don't see a new log when I try to add to cart on these files. 
The only error I see is this:
https://cl.ly/f985899f7e8c
_{"code":500,"result":"Product with SKU \"1234567\" does not exist"}_
I wonder why it gives an error 500 and it still displays the product on the Frontend.

To note that a friend of mine has the same issue on his local env.

**Comment by pkarw** [comment]
Please just make sure You're connected to the right Magento backend :-) `vue-storefront-api:config/local.json` - magento2 section. Probably You're quering differtent magento backend than You got the prodcuts from

**Comment by bellodaniel** [comment]
@pkarw This is the local.json in this file:
"magento2": {
    "url": "http://dev23.m2.test",
    "imgUrl": "https://dev23.m2.test/pub/media/catalog/product",
    "assetPath": "/../var/magento2-sample-data/pub/media",
    "magentoUserName": "",
    "magentoUserPassword": "",
    "httpUserName": "",
    "httpUserPassword": "",
    "api": {
      "url": "http://dev23.m2.test/rest",
      "consumerKey": "bpcl2q57jg5szebdmaw0kshsq9uezknc",
      "consumerSecret": "dx2oohnk3wemgrh4wz1nhmmmomdhhxof",
      "accessToken": "oio9m3y39uje9o4z2gwp60kq35lqd9k4",
      "accessTokenSecret": "g3n1c9ahpquqfco7ngwf6uz935ox3418"
    }
  },

I still get the error though. 
I wonder, If the Magento backend url would be wrong, the Product would not be rendered on the frontend at all?
