### ISSUE TITLE
Add onboarding pop-up on the demo

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#295]
As we discussed with @pkarw - we will add the onboarding pop-up on the live demo, visible with the first visit and after clicking the info button on the right bottom corner of the screen.

**Comment by pkarw** [comment]
@mercs600 can you take this one? The designs are on FIGMA

**Comment by mercs600** [comment]
@karolbzik "after clicking the info button on the right bottom corner of the screen." Where can I find the info button which you mentioned ?

**Comment by karolbzik** [comment]
@mercs600 just give me 2 days - I will send you the design for this issue ;)

**Comment by pkarw** [comment]
@mercs600 could you add the final onboarding popup using the popup feature you've recently added to close this one?

**Comment by karolbzik** [comment]
@mercs600 here it is:
<img width="1440" alt="ondoarding widget" src="https://user-images.githubusercontent.com/18116406/33956727-c5174d72-e03f-11e7-9174-65d6d23b3435.png">

In Figma file (https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront-Open-Source) under the name "Ondoarding widget".
