### ISSUE TITLE
Automate the build of the documentation

### ISSUE THREAD

**Issue by Jensderond** [DivanteLtd/vue-storefront#2955]
## What is the motivation for adding / enhancing this feature?
When the documentation website is built automatically, people who are new with VSF will be able to always see the most recent docs.

## What are the acceptance criteria 
The workflow of this could be copied from Storefront UI, [see an example here.](https://github.com/DivanteLtd/storefront-ui/pull/100)

- [ ] Automatically built the website (using Netlify or whatever)

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
This is something @kkdg is currently working on :)

**Comment by pkarw** [comment]
@kkdg and @filrak please update us on the progress - I belive there was only the domain issue left?

**Comment by Jensderond** [comment]
I believe this one can be closed @pkarw? 
Or wasn't this part of the move to Zeit

**Comment by pkarw** [comment]
@Jensderond yeah, AFAIK it was! So I’m closing this one :)

**Comment by kkdg** [comment]
@Jensderond  Yep, moving to Zeit has been done, a little more tweak is waiting for full automation. that will be done this week too. Thanks!
