### ISSUE TITLE
Yarn fails to install on cloned code Windows

### ISSUE THREAD

**Issue by PierreVanvolsem** [DivanteLtd/vue-storefront#2962]
## Current behavior

Fails to install/link all dependencies. 

## Expected behavior

Installing without issues.

## Steps to reproduce the issue

https://docs.vuestorefront.io/guide/installation/windows.html#installation-of-vue-storefront
fails a step 4.

## Repository

cloned code of master

## Can you handle fixing this bug by yourself?

- [x] YES
- [X ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- OS: Windows 
- Node: 10
- Code Version: master

## Additional information
<!-- If you think that any additional information would be useful, please provide them 
Trace: 
  Error: EISDIR: illegal operation on a directory, symlink 'D:\VueStorefront\vue-storefront\docs' -> 'D:\VueStorefront\vue-storefront\node_modules\@vue-storefront\docs'

Already tried: yarn install --no-bin-links

**Comment by evanlegamer** [comment]
Have you fixe the problem ? I have exactly the same
