### ISSUE TITLE
Remake order functionality non-deterministic behavior

### ISSUE THREAD

**Issue by Zanuff** [DivanteLtd/vue-storefront#2964]
## Current behavior
Remake order functionality ends up with random number of products in cart if not locked on backend side. Probably due to the asynchronicity of the requests.

## Expected behavior
Remake order functionality should end up with the same number of products in cart after clicking remake order.

## Steps to reproduce the issue
1. Have an account with orders
2. Have an order with multiple products added
3. Go to my orders and click remake order
4. See how the cart id updated several times and end up with different number of tiems and totals

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by alinadivante** [comment]
Something is wrong when I try remake really big order (94 items)..  Look at minicart-counter
![big_order](https://user-images.githubusercontent.com/36628922/58635456-3edcdd00-82ee-11e9-940b-bc13ab875e7e.gif)

**Comment by pkarw** [comment]
Ok, it’s on the branch 2513 right?

**Comment by alinadivante** [comment]
Yes @pkarw - feature/2513

**Comment by pkarw** [comment]
OK, I've refactored it a little bit https://github.com/DivanteLtd/vue-storefront/pull/2887

**Comment by alinadivante** [comment]
Nice job!

**Comment by alinadivante** [comment]
@pkarw I tested it again, after merging, but now I see a problem with a duplicate notification and it takes a while before the user is redirected to the checkout. See my new video.
![big_order](https://user-images.githubusercontent.com/36628922/59360854-25e21c00-8d31-11e9-87ba-73b69d059e33.gif)

Imho there should be loader displayed or information about the processing.

**Comment by pkarw** [comment]
OK, we need to add the check for duplicated notification in the `core/modules/cart/store/actions.ts:583`

**Comment by pkarw** [comment]
I've also got a console error: vuex.esm.js:410 [vuex] unknown action type: cart/getPaymentMethods

**Comment by pkarw** [comment]
Check also the `forceServerSync` when entering Checkout.js. Currently it is set with the remake order - and probable shouldn't be (it will save us on cart sync)

**Comment by pkarw** [comment]
Plus as @alinadivante wrote - adding a popup / blocking loader
