### ISSUE TITLE
UserId not sent when creating account in checkout process

### ISSUE THREAD

**Issue by Zanuff** [DivanteLtd/vue-storefront#2966]
## Current behavior
UserId not sent when creating account in checkout process. The create order request is being sent before the login is over.

## Expected behavior
UserId should be sent when creating account in checkout process. The create order request is sent after the login is over and userId has been acquired.

## Steps to reproduce the issue
1. Got to checkout process while logged out
2. Create login at checkout process
3. Finish the checkout process
4. See that place order request is sending empty UserId in reuqest payload

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by ZeevGerstner** [comment]
I test it now, and I got a userId on request payload when clicked Place the order, after creating new account from checkout like you wrote. Tried to reproduce it like you wrote above. Am I missing something?
