### ISSUE TITLE
Won't display the article images on a listview

### ISSUE THREAD

**Issue by cfritze** [DivanteLtd/vue-storefront#2968]
Won't display the article images on a listview.

Lazyloading will not display the images correctly.

Happen on: PWA Homescreen

Client:
- Pixel 3
- Android 9
- Chrome 74.0.3729.157

Videolink:
http://xuud.de/screenvideo/shopwarepwa.mp4

**Comment by 4aficiona2** [comment]
happens to me too with Chrome version 74.0.3729.169

**Comment by pkarw** [comment]
Hi! Thanks for Your feedback. This issue has been just recently fixed in the “develop” branch (1.10rc1 work in progress)
