### ISSUE TITLE
Using Bootstrap Vue for vue storefront theme

### ISSUE THREAD

**Issue by sree8637** [DivanteLtd/vue-storefront#2977]
Can someone shed some lights on how to use bootstrap vue in storefront. I have installed bootstrap vue inside my theme(copy of default theme) folder, and added import statements on index.js. Then I tried to apply some Bootstrap vue on my layouts, but the styles are not getting applied.

I am new to vue and vue storefront, so i dont know if I have missed some settings or any configurations.

**Comment by pkarw** [comment]
Please check our forum or move this question to it in order to get the quick answer: http://forum.vuestorefront.io

**Comment by wdrdres3qew5ts21** [comment]
Does this problem solve yet because I already ask but I cann't find any solution for this ?
https://forum.vuestorefront.io/t/how-vue-storefront-install-external-vue-component-boostrap-css-framework-work/413
