### ISSUE TITLE
Broken links in documentation: almost all of the Vuex links are broken

### ISSUE THREAD

**Issue by 4aficiona2** [DivanteLtd/vue-storefront#2979]
## Current behavior

Vuex links in documentation are broken.

https://docs.vuestorefront.io/guide/vuex/introduction.html

## Expected behavior

Links work and user won't get an 404 error when clicking the links.

## Steps to reproduce the issue

https://docs.vuestorefront.io/guide/vuex/introduction.html

If I'd knew where to map the links I'd have proposed a solution / fixed the links in this pull request but I'm fairly new to the project and still figuring out how things are related / built. Thanks for reviewing and fixing!

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by 4aficiona2** [comment]
Just found this "This part is depreciated and will be slowly migrated to modules and lib folder" comment in introduction.

Maybe this should be mentioned in the section itself too.
https://docs.vuestorefront.io/guide/vuex/introduction.html

**Comment by pkarw** [comment]
@kkdg could You please fix it?

**Comment by pkarw** [comment]
Related to #2984

**Comment by pkarw** [comment]
@kkdg I think It would be even better to just remove the outdated Vuex docs Asmara for now rather than confuse the user with broken links / outdated specs wdyt?

**Comment by kkdg** [comment]
@pkarw duly noted. It will be updated in the next rollout, I will remove them as appropriate as possible.
