### ISSUE TITLE
Incorrect Docker name used for the vuestorefrontapi yarn restore step

### ISSUE THREAD

**Issue by globaltopmedia** [DivanteLtd/vue-storefront#2980]
## Current behavior
If you follow the manual installation steps as outlined in https://docs.vuestorefront.io/guide/installation/linux-mac.html#install-the-vue-storefront-api
you will get the following error displayed when running the command:

`docker exec -it vuestorefrontapi_app_1 yarn restore
`
Error: No such container: vuestorefrontapi_app_1

## Expected behavior
No error, and the elastic.js restore works correctly.

## Steps to reproduce the issue
docker exec -it vuestorefrontapi_app_1 yarn restore
Error: No such container: vuestorefrontapi_app_1

## Repository
/vue-storefront/blob/master/docs/guide/installation/linux-mac.md

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Stable

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: MacOS 10.14.5
- Node: 
- Code Version:

**Comment by patzick** [comment]
Thanks @globaltopmedia ! :)
