### ISSUE TITLE
docs.vuestorefront.io documentation does not reflect the recent .md doc files on GitHub

### ISSUE THREAD

**Issue by 4aficiona2** [DivanteLtd/vue-storefront#2984]
## Current behavior

The current https://docs.vuestorefront.io/guide/modules/introduction.html does not reflect the most recent version of https://github.com/DivanteLtd/vue-storefront/blob/master/docs/guide/modules/introduction.md. 

## Expected behavior

https://docs.vuestorefront.io/guide/modules/introduction.html and the .md files on GitHub, e.g. https://github.com/DivanteLtd/vue-storefront/blob/master/docs/guide/modules/introduction.md are on par.

## Repository

https://github.com/DivanteLtd/vue-storefront/blob/master/docs/guide/modules/introduction.md

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
Fixed!

**Comment by 4aficiona2** [comment]
Thanks!
