### ISSUE TITLE
Can not change the qty of the product in the cart using arrows (Firefox)

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2988]
## Current behavior

![Peek 2019-05-21 10-27](https://user-images.githubusercontent.com/49188852/58550778-d0751d80-820e-11e9-9978-0baac801c917.gif)
Currently, when I try to change the qty of the product in the cart using arrows - nothing happens. I have to click first on the input and then I can change the qty using arrows. 

## Expected behavior

Product price is changing when I change the qty of the product in the cart using arrows.

## Steps to reproduce the issue

1. Go to https://demo.storefrontcloud.io/ using Firefox browser.
2. Open hamburger menu and choose any category.
3. Choose any product and go to the product page.
4. Add product to the cart.
5. Open the cart sidebar.
6. Try to change the qty of the product using arrows. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Firefox 66
- OS: Windows 10
## Additional information

The problem appears only on Firefox.

**Comment by pkarw** [comment]
@przspa @GabiDivante is it ready to be closed?

**Comment by alinadivante** [comment]
yes, this issue is rady @pkarw
