### ISSUE TITLE
Cookbook 

### ISSUE THREAD

**Issue by kkdg** [DivanteLtd/vue-storefront#2992]
# Summary
[summary]: #summary

Writing a cookbook style guides for Vue Storefront in ./docs folder

# Motivation
[motivation]: #motivation

This helps a lot for new comers to wrap their heads around how to use Vue Storefront to their advantage. 

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation

It explains the step-by-step guides with respect to how to start Vue Storefront from scratch. 
It deals with common issues frequently faced by new comers. 
1. Data Imports
2. Setup Elastic Search
3. Starting from scratch
4. Integration with 3rd party
5. Extend a module
6. Theming
7. Dealing with common mistakes and pitfalls
8. and so on...

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation
This guide follows the proven design for general cookbook which is easy to understand, easy to follow the steps and help users to stay on track with clear solution for certain type of problems. 
It contains 4 ~ 5 sections for each recipe (solution), and a handful recipes comprise a chapter. 
Sections include : 
- Preparation
- Recipe
- Peep into the kitchen (how it works internally)
- Chef's secret (protips)

# Drawbacks
[drawbacks]: #drawbacks

It takes a lot of time to build a cookbook that is relevant. 

# Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

- Cookbook is generally known as the best way for helping newbies and new comers get started at all. 
-  Tutorial is good for helping new comers too but cookbook has a variety of helps in a more structured way. 

# Unresolved questions
[unresolved-questions]: #unresolved-questions

- You may add/remove topics

# Future possibilities
[future-possibilities]: #future-possibilities

We can build a lot more stuff to help new comers and users who lost in the middle.

**Comment by kkdg** [comment]
I am currently working on Data imports. 

Data imports consists of a few recipes including : 
- Introduction (done)
- Data Migration for Elasticsearch (done)
- Data pump (doing)
- Data imports and tools (not done)

**Comment by pkarw** [comment]
I really love this idea. The first cook book also looks great. Would awesome to have at least first one ready for the 1.10 release (19.06.2019) to show the direction. Looking at the progress you currently have it looks like well gonna make it :-)

**Comment by kkdg** [comment]
A little daunting task with the deadline, but let's try and shoot

**Comment by kkdg** [comment]
A little daunting task with the deadline, but let's try and shoot ;)

**Comment by kkdg** [comment]
I am done on Data imports.

Data imports consists of a few recipes including :

Introduction (done)
Data Migration for Elasticsearch (done)
Data pump (done)
--Data imports and tools (canceled)--

You can watch it while it is in progress at here : https://vuepress.andflyaway.now.sh/guide/cookbook/data-import.html

**Comment by kkdg** [comment]
Ch. 3 includes following topics :

0. Introduction (done)
1. Install with Docker (doing)
2. Using Installer
3. Manual Installation
4. Storefront CLI at your service
5. How to debug anything
6. Install Tool Chains

You can watch it while it is in progress at here : https://vuepress.andflyaway.now.sh/guide/cookbook/data-import.html

**Comment by pkarw** [comment]
Cool!

**Comment by kkdg** [comment]
Opened up a trello board for WIPs

https://trello.com/b/f4URVw5e/vuestorefront

**Comment by kkdg** [comment]
Updated contents of cookbook : 

Chapter 1. Data Imports
Chapter 2. Elasticsearch in the context of VS
Chapter 3. Starter pack for new comers (Install)
Chapter 4. Integration with 3rd Party
Chapter 5. Building a Module from scratch
Chapter 6. Theming in depth
Chapter 7. Anti-Patterns & Common Pitfalls
Chapter 8. On DevOps
Chapter 9. Test Driven Development for VS
Chapter 10. Internals internally
Chapter 11. Vue Basics by example of VS
