### ISSUE TITLE
Product Images not visible on PDP

### ISSUE THREAD

**Issue by bellodaniel** [DivanteLtd/vue-storefront#2993]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [ X] I am running the latest version => yes
- [X ] I checked the documentation and found no answer => yes
- [ X] I checked to make sure that this issue has not already been filed => yes
Also asked for help on the slack #help channel.
## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	

I have integrated the Vue storefront with Magento 2. Everything seems to be working fine. However, when I try to migrate the image, I get an error:
{"code":400,"result":"Unable to download the requested image https://dev23.m2.test/pub/media/catalog/product/k/a/kai-greene_1.jpg"}

The Magento image url is correct https://cl.ly/1d9f21ebf6af and assigned on the storefront
https://cl.ly/50fe6578b471
 
# Can't find what you're looking for?

Is there any configuration I am missing here?
This is the actual configs:
"imageable": {
    "namespace": "",
    "maxListeners": 512,
    "imageSizeLimit": 1024,
    "whitelist": {
      "allowedHosts": [".*divante.pl", ".*vuestorefront.io", "localhost", "localhost:8080"],
      "trustedHosts": [".*divante.pl", ".*vuestorefront.io", "localhost", "localhost:8080"]
    },
    "cache": {
      "memory": 50,
      "files": 20,
      "items": 100
    },
    "concurrency": 0,
    "counters": {
      "queue": 2,
      "process": 4
    },
    "simd": true,
    "keepDownloads": true,
    "maxDownloadCacheSize": 1000,
    "tmpPathRoot": "/tmp"
  }

## Keep the problem description concise and include:
- [x] A brief description of the problem,
- [x] Where the problem is occurring,
- [x] The length of time the problem has been occurring,
- [x] The size of the problem.

**Comment by pkarw** [comment]
Please try adding  your domain dev23.m2.local to “allowedHosts” in the config

**Comment by RichPC** [comment]
I was getting a 400 error for images too. After changing my image url to http instead of https the problem went away. My local domain was only using a self signed certificate, so I assume the image proxy refuses to download the image because of the untrusted cert.

**Comment by limajasachin** [comment]
Assign "http://localhost:8080/media/catalog/product" as "imgUrl" in config/local.json file of vue-storefront-api folder and rebuild API docker images.
```
"magento2": {
    "imgUrl": "http://localhost:8080/media/catalog/product",
    "assetPath": "/../var/magento2-sample-data/pub/media",
    "api": {
      "url": "http://your-magento-instance/rest",
      "consumerKey": "<consumerKey>",
      "consumerSecret": "<consumerSecret>",
      "accessToken": "<accessToken>",
      "accessTokenSecret": "<accessTokenSecret>"
    }
  },
```

And Add localhost:8080 in allowed hosts in the config/local.json configuration file as below:

```
"imageable": {
    "maxListeners": 512,
    "imageSizeLimit": 1024,
    "whitelist": {
      "allowedHosts": [
        ".*divante.pl",
        ".*vuestorefront.io",
        **".*localhost:8080"**
      ]
    },
    "cache": {
      "memory": 50,
      "files": 20,
      "items": 100
    },
    "concurrency": 0,
    "counters": {
      "queue": 2,
      "process": 4
    },
    "simd": true
  },
```
