### ISSUE TITLE
Some products added to Shopping cart have a price without tax in offline mode.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#2997]
## Current behavior
Some of available products (e.g. Leah Yoga Top) added to shopping cart, display price without tax in offline mode
![offline_mode](https://user-images.githubusercontent.com/36628922/58683080-6b870800-8373-11e9-94ca-2f312ea2bf7f.gif)

## Expected behavior
The price should always be displayed with tax.

## Steps to reproduce the issue
1, Add any product, for example Leah Yoga Top
2. Open Shopping cart
3. Switch to offline mode

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
Fixed on a branch #2887

**Comment by alinadivante** [comment]
Yes, it works now.
But @pkarw please look at this:
![discount](https://user-images.githubusercontent.com/36628922/58861490-c9d32400-86ae-11e9-94d2-07c4f7a61cdf.gif)
There is only a new price of product, but when I go offline I see also price before the discount.
In my opinion we should displaying previous price and after discount. 
Am I right?

**Comment by pkarw** [comment]
@alinadivante yeah, it should work like this but it's not possible to implement it in a deterministic way. I mean - we get the prices from Magento backend, calculated after all the shopping cart rules. In the offline mode, we're never sure the price after discounts as they can't be calculated. Therefore it's safer to display the prices without the discount
