### ISSUE TITLE
PLEASE HELP!cannot launch the vsf app on server. Localhost:3000 redirecting to /error

### ISSUE THREAD

**Issue by michhy** [DivanteLtd/vue-storefront#3004]
Hello, 
I followed the instruction to setup production site on AWS server,
but failed to show the VSF site.
it keep showing redirection loop 
(if i changed the location in the file inside sites-available to other ports, that will display correctly)
I checked port 3000 is running on my ubuntu server
Not sure what happen. PLEASE HELP!

Thanks
![螢幕截圖 2019-06-01 上午5 45 03](https://user-images.githubusercontent.com/37435427/58736564-e5c99200-8430-11e9-8ee5-b77d392977e1.png)
![螢幕截圖 2019-06-01 上午5 45 12](https://user-images.githubusercontent.com/37435427/58736566-e5c99200-8430-11e9-92db-45acc53e1f5c.png)

**Comment by michhy** [comment]
Please help!

I have tested the app all fine on local machine thus i follow the production guide to launch on server.

Nginx ssl is all set, i have testes myURL.com/api is working fine!
BUT myURL.com/ cause redirect loop.

I do: curl localhost:3000 on server and it returned:

FOUND. Rediecting to /error

Can anyone please help? As i need to launch the shop asap.

Thanks in advance!
It showed the app is built but localhost:3000 is redirecting to /error
![螢幕截圖 2019-06-01 下午12 50 28](https://user-images.githubusercontent.com/37435427/58743871-635ec380-846c-11e9-8563-f985593cce07.png)

in var/v-sf.log it shows the app did complied successfully 
![螢幕截圖 2019-06-01 下午12 52 41](https://user-images.githubusercontent.com/37435427/58743875-796c8400-846c-11e9-9f89-d33671678423.png)

**Comment by pkarw** [comment]
Please make sure Your server app has the connectivity to the ElasticSearch

**Comment by michhy** [comment]
Thank you @pkarw. 
May I have a little bit more information on how to test if elastic search is running?

Thanks so much.

**Comment by michhy** [comment]
Hello.

I have revised the elasticsearch and seems they are all ok in local.json.

But it still redirecting to /error.... 

Please let me know what to check next :(

Thanks a lot for your help!
![螢幕截圖 2019-06-01 下午5 02 22](https://user-images.githubusercontent.com/37435427/58746285-45ef2100-848f-11e9-9fb2-2abc90d40570.png)
![Uploading 螢幕截圖 2019-06-01 下午5.02.36.png…]()

**Comment by michhy** [comment]
I tried to remove the redirect /error from core/scripts/server.js,
and it show cannot GET / on the page.
![螢幕截圖 2019-06-02 下午5 09 53](https://user-images.githubusercontent.com/37435427/58759244-6be0f800-8559-11e9-8991-7c8c3b4b6051.png)


Really stuck at this point, not sure how to make the app live :(

**Comment by michhy** [comment]
I ran Npm run dev and its showing on live.
clearly its not loading the backend.
I am not sure what setup was incorrect...

**Comment by michhy** [comment]
npm is not working now either, it shows up some error:
![螢幕截圖 2019-06-03 下午7 20 42](https://user-images.githubusercontent.com/37435427/58798274-c8fdac00-8634-11e9-8c17-f5de00109e2e.png)

**Comment by Cyclonecode** [comment]
How does your `storeViews` configuration look?

**Comment by michhy** [comment]
Hi @Cyclonecode , 
Please see the attached screenshot, many thanks!

![螢幕截圖 2019-06-03 下午9 32 35](https://user-images.githubusercontent.com/37435427/58805716-34507980-8647-11e9-8e5d-e5b25d44a184.png)

**Comment by Cyclonecode** [comment]
Why have you multistore set to true if you only have a single store? Can you also verify that you are using the same node/npm versions on both local and production environment?

**Comment by michhy** [comment]
Dear @Cyclonecode , Thanks for your reply!

I have upgrade the server node + npm version to sync with my local machine, change  multi storeview to false for now, remove 'dist' for both VS and VSF, yarn build and yarn start for both again.

but the error still showing up....  when I curl localhost:3000
"Found. Redirecting to /error"

**Comment by michhy** [comment]
This is the server log. 
not sure if this causeing it error?
and i donno which file to fix :(

![螢幕截圖 2019-06-03 下午11 28 42](https://user-images.githubusercontent.com/37435427/58813994-7da8c500-8657-11e9-8e47-6318c6544732.png)

**Comment by pkarw** [comment]
Let's move this issue to the forum please :) https://forum.vuestorefront.io
