### ISSUE TITLE
Docker container exits on start while `yarn build:client`

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront#3007]
## Current behavior
The app docker container won't start anymore. It exits after the image build, during the start, while running `yarn build:client`.

Error message:
```bash
@ ./core/app.ts 17:0-44 95:56-66
@ ./core/client-entry.ts
@ multi @babel/polyfill ./core/client-entry.ts

ERROR in /var/www/core/lib/multistore.ts
./core/lib/multistore.ts
[tsl] ERROR in /var/www/core/lib/multistore.ts(137,41)
      TS2345: Argument of type 'object' is not assignable to parameter of type '{ [key: string]: unknown; }'.
  Index signature is missing in type '{}'.

ERROR in /var/www/core/lib/search/adapter/api/searchAdapter.ts
[tsl] ERROR in /var/www/core/lib/search/adapter/api/searchAdapter.ts(74,45)
      TS2345: Argument of type 'HttpQuery' is not assignable to parameter of type '{ [key: string]: unknown; }'.
  Index signature is missing in type 'HttpQuery'.
Child html-webpack-plugin for "index.amp.html":
     1 asset
    Entrypoint undefined = index.amp.html
Child html-webpack-plugin for "index.basic.html":
     1 asset
    Entrypoint undefined = index.basic.html
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
Child html-webpack-plugin for "index.minimal.html":
     1 asset
    Entrypoint undefined = index.minimal.html
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It works without this error if started via `yarn` outside docker.

## Expected behavior
Just build and start the container to run the app in a container.

## Steps to reproduce the issue
```bash
docker-compose --force-recreate --build up
```

## Repository

`develop`

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO  (But I'll try)

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: any
- OS: Ubuntu 18 & OSX with latest docker
- Node: v10.15.3 like in Docker image `node:10-alpine`
- Code Version: develop 8bdb09b33ce7aeb24af21a799bf3460391a653a6

**Comment by pkarw** [comment]
Hi! Thanks for Your input. Could You please provide us with a Pull Request?

**Comment by cewald** [comment]
After some research this morning, I noticed it's caused by the missing `yarn.lock` file in the Docker image. If i add it like `COPY yarn.lock ./` in `docker/vue-storefront/Dockerfile`, it works.

Is I saw in the opened PR's, @Flyingmana already made an PR for this: #3006 
So, if this goes through, this can be considered as done.
