### ISSUE TITLE
Wrong price is displayed for  discount products.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3012]
## Current behavior
After adding discounted product to the cart, there is only a new price (with discount), but when I go offline I see also price before the discount.

![discount](https://user-images.githubusercontent.com/36628922/58869360-5c2ef400-86be-11e9-8a87-a92dca0839d3.gif)

## Expected behavior
We should displaying price without discount.

## Steps to reproduce the issue
1. Add to cart Joust Duffle Bag
2. Open cart
3. Go to offline mode

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
Fixed in the https://github.com/DivanteLtd/vue-storefront/pull/2887

**Comment by alinadivante** [comment]
@pkarw without changes for products with **Special Price** (e.g. Joust Duffle Bag)

**Comment by pkarw** [comment]
Then the product has "static" special price (catalog rule) it could be showed in totals safely. We can't show the dynamic special prices (cart rules)

online mode: 
https://www.dropbox.com/s/u02955txmbkhmpv/Screenshot%202019-06-05%2015.29.42.png?dl=0

offline mode:
https://www.dropbox.com/s/o88dfagx7mhdc5q/Screenshot%202019-06-05%2015.30.30.png?dl=0

This product has special price of 32 - set via catalog rule + applied discount by cart rule (only in online mode): so it works fine :)
