### ISSUE TITLE
Replace EventBus with actions

### ISSUE THREAD

**Issue by lukeromanowicz** [DivanteLtd/vue-storefront#3020]
## What is the motivation for adding / enhancing this feature?
As we are using vuex, there is no point in mixing it with an event bus. We should replace all events with actions while still dispatching events inside these actions for backward compatibility untill the next major release.

## What are the acceptance criteria 
- create actions that will be dispatched instead of events
- replace all events on event bus emitted across the code with actions
- emit old events inside in actions for compatibility reasons, mark those events emissions as deprecated
- rewrite old event observers to actions with the same name as new actions. (When there are multiple actions with the same name, vuex will run them all during single dispatch)

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
As it may sounds easy with the events that have just a single listener (eg. https://github.com/DivanteLtd/vue-storefront/blob/20b693e28eeac810252593e1b42e709cc03701e9/core/modules/order/hooks/beforeRegistration.ts#L19) it's not so easy to replace EventBus for events that have multiple/dynamic listeners.

Let's say the events used by the payments modules (https://github.com/danrcoull/vsf-payment-braintree/blob/d42a2e6f2ccc227aad6c183ea8c089da032a73cb/hooks/beforeRegistration.ts#L25)
