### ISSUE TITLE
Memory leaks related to dynamicConfigReload option.

### ISSUE THREAD

**Issue by dimasch** [DivanteLtd/vue-storefront#3053]
## Current behavior
We see potencial memory leaks on SSR level.

## Expected behavior
GC clean unused memory segments.

## Steps to reproduce the issue
If setup `dynamicConfigReload` to `true` in production mode we see leak of memory
And use `autocannon` for example.
http://dimasch.github.io/yandex-tank-benchmark/

## Repository
Affected all version and branches.

`core/scripts/server.js`

Possible workaround:
```
if (config.server.dynamicConfigReload) {
    const cachedConfigModule = require.cache[require.resolve('config')]
    if (cachedConfigModule) {
      delete cachedConfigModule.parent.children;
      delete cachedConfigModule;
    }
```

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by dimasch** [comment]
I will prepare PR in next time.

**Comment by pkarw** [comment]
CooL! Thanks @dimasch, waiting up for a PR

**Comment by pkarw** [comment]
Hey @dimasch how about the status? :)

**Comment by dimasch** [comment]
Hey @pkarw Today i will prepare PR and check difference. For me need some time :)

**Comment by dimasch** [comment]
@pkarw Done.

**Comment by patzick** [comment]
thanks @dimasch ! Nice job :)
