### ISSUE TITLE
Add sidebar menu toggle button to product page.

### ISSUE THREAD

**Issue by pmaojo** [DivanteLtd/vue-storefront#3056]
## What is the motivation for adding / enhancing this feature?

Thinking about the back button and the lack of menu on Product views.

Scenario:

1- User enters https://next.storefrontcloud.io/women/tops-women/tees-women/tees-25/elisa-evercool-and-trade-tee-1465.html?childSku=WS06 
2- User can click back button (arrow-left icon) and it would on first click do nothing and second click take him out of the shop, bad.
3- User can wish to see a menu of links to browse the page on a standard way, and the hamburger menu is not present.

## What are the acceptance criteria 

On a product page:

- [ ] There is no useless back button if the previous URL is not in our domain, or url was entered manually
- [ ] There is a button to toggle side menu 

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information
I refer to the left arrow on the top left of the screenshot:
![Captura de pantalla 2019-06-14 a las 18 38 39](https://user-images.githubusercontent.com/411551/59527516-b3f60800-8ed3-11e9-80d2-70e8ad456fb1.png)

**Comment by patzick** [comment]
Back button on product page has been removed as it was in 1.9.
There are too many different behaviors, without proper specification of each case there is no point in having it.
