### ISSUE TITLE
Inherit storeview config after base settings in multistore mode 

### ISSUE THREAD

**Issue by lukeromanowicz** [DivanteLtd/vue-storefront#3057]
# Summary
[summary]: #summary

In multistore mode with multiple storeviews on one instance, the config becomes hard to maintain and there are lots of duplications. We need a mechanism settings inheritance from base storeview to child ones. We can either create another storeview which won't be mapped to an url and point other storeviews to inherit its settings or copy settings from default storeview.

# Motivation
[motivation]: #motivation

Multistore setup with many storeviews has lots of duplicated settings that could be inherited to improve maintainability.

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation

The old way we're configuring multistore setup is as follows:
```
    "defaultStoreCode": "",
    "storeViews": {
      "multistore": true,
      "commonCache": true,
      "mapStoreUrlsFor": ["de", "it"],
      "de": {
        "storeCode": "de",
        "disabled": false,
        "storeId": 3,
        "name": "German Store",
        "url": "/de",
        "appendStoreCode": true,
        "elasticsearch": {
          "host": "/api/catalog",
          "index": "vue_storefront_catalog_de"
        },
        "tax": {
          "sourcePriceIncludesTax": false,
          "defaultCountry": "DE",
          "defaultRegion": "",
          "calculateServerSide": true
        },
        "i18n": {
          "fullCountryName": "Germany",
          "fullLanguageName": "German",
          "defaultLanguage": "DE",
          "defaultCountry": "DE",
          "defaultLocale": "de-DE",
          "currencyCode": "EUR",
          "currencySign": "EUR",
          "dateFormat": "HH:mm D-M-YYYY"
        }
      },
      "it": {
        "storeCode": "it",
        "disabled": false,
        "storeId": 4,
        "name": "Italian Store",
        "url": "/it",
        "appendStoreCode": true,
        "elasticsearch": {
          "host": "/api/catalog",
          "index": "vue_storefront_catalog_it"
        },
        "tax": {
          "sourcePriceIncludesTax": false,
          "defaultCountry": "IT",
          "defaultRegion": "",
          "calculateServerSide": true
        },
        "i18n": {
          "fullCountryName": "Italy",
          "fullLanguageName": "Italian",
          "defaultCountry": "IT",
          "defaultLanguage": "IT",
          "defaultLocale": "it-IT",
          "currencyCode": "EUR",
          "currencySign": "EUR",
          "dateFormat": "HH:mm D-M-YYYY"
        }
      }
```
As you can see, there are multiple fields that are having duplicated values across all multistores.
Inheriting these settings from base settings would definitely shorten that up.

## Approach 1.
We can copy all settings from default storeview which currently acts as a fallback to US storeview. Below there is a configuration for two storeviews and it's already long. Imagine how would it look with 10 storeviews that share similar language and tax settings but different product sets.
```
    "defaultStoreCode": "",
    "storeViews": {
      "multistore": true,
      "commonCache": true,
      "mapStoreUrlsFor": ["de", "it"],
      "de": {
        "storeCode": "de",
        "storeId": 3,
        "name": "German Store",
        "url": "/de",
        "elasticsearch": {
          "index": "vue_storefront_catalog_de"
        },
        "tax": {
          "defaultCountry": "DE"
        },
        "i18n": {
          "fullCountryName": "Germany",
          "fullLanguageName": "German",
          "defaultLanguage": "DE",
          "defaultCountry": "DE",
          "defaultLocale": "de-DE"
        }
      },
      "it": {
        "storeCode": "it",
        "storeId": 4,
        "name": "Italian Store",
        "url": "/it",
        "elasticsearch": {
          "index": "vue_storefront_catalog_it"
        },
        "tax": {
          "defaultCountry": "IT"
        },
        "i18n": {
          "fullCountryName": "Italy",
          "fullLanguageName": "Italian",
          "defaultCountry": "IT",
          "defaultLanguage": "IT",
          "defaultLocale": "it-IT"
        }
      }
```

## Approach 2.
We could create a base, unmapped storeview to inherit all the settings from 

```
    "defaultStoreCode": "",
    "storeViews": {
      "multistore": true,
      "commonCache": true,
      "mapStoreUrlsFor": ["de", "it"],
      "base": {
        "disabled": false,
        "appendStoreCode": true,
        "elasticsearch": {
          "host": "/api/catalog",
        },
        "tax": {
          "sourcePriceIncludesTax": false,
          "defaultRegion": "",
          "calculateServerSide": true
        },
        "i18n": {
          "currencyCode": "EUR",
          "currencySign": "EUR",
          "dateFormat": "HH:mm D-M-YYYY"
        }
      },
      "de": {
        "inherit": "base",
        "storeCode": "de",
        "storeId": 3,
        "name": "German Store",
        "url": "/de",
        "elasticsearch": {
          "index": "vue_storefront_catalog_de"
        },
        "tax": {
          "defaultCountry": "DE"
        },
        "i18n": {
          "fullCountryName": "Germany",
          "fullLanguageName": "German",
          "defaultLanguage": "DE",
          "defaultCountry": "DE",
          "defaultLocale": "de-DE"
        }
      },
      "it": {
        "inherit": "base",
        "storeCode": "it",
        "storeId": 4,
        "name": "Italian Store",
        "url": "/it",
        "elasticsearch": {
          "index": "vue_storefront_catalog_it"
        },
        "tax": {
          "defaultCountry": "IT"
        },
        "i18n": {
          "fullCountryName": "Italy",
          "fullLanguageName": "Italian",
          "defaultCountry": "IT",
          "defaultLanguage": "IT",
          "defaultLocale": "it-IT"
        }
      }
```

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation

## Approach 1.1.
In every config to read values, we need to use `storeViewConfig.value || defaultStoreViewConfig.value`. A very ugly way in my opinion but still should be mentioned for the record, I guess.

## Approach 1.2.
We need to merge every storeview config with default storeview values spread across the config file on app startup and every config dynamic reload.

## Approach 1.3.
We need to merge resolved storeview config with default storeview values spread across the config file in 
https://github.com/DivanteLtd/vue-storefront/blob/3908344ddff34c2505af4123c5eeaeff64b1b46b/core/lib/multistore.ts#L52

## Approach 2.1
Same as in 1.2 but this time we need to deep merge two storeview configs (base and target one).

## Approach 2.2
Same as in 1.3. but this time we need to deep merge two storeview configs (base and target one).

# Drawbacks
* additional complication of loading config values

# Unanswered questions:
* Do we allow nested inheritance in approach 2.*? It may lead to creating more complicated and unmaintainable configs than the current approach if abused (used wrongly).

# Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

Keeping it as it is or using a separate tool to hydrate config with appropriate variables (e.g. ansible, environmental variables).

**Comment by lukeromanowicz** [comment]
@pkarw @filrak @patzick @nhp @resubaka, what do you guys think?

**Comment by ResuBaka** [comment]
Wouldn't it be it be easier to say you add a helper in the core which is used to get the config.
What i think it would to is:
First look into the storeview config and check if it can find the value in there when not look into the global scope. 
```typescript
getConfigValue(configPath: string): any {
   let configValue = storeViewConfig.get(configPath)
   if (configValue === undefined) {
    configValue = config.get(configPath)
  } 
  return configValue
}
```

So maybe something like this as idea **3.1**.

Is there some case which does merge the storeconfig into the global config as that would to the job to and would be the fastest and easiest solution to the problem. So you only need to ask the global config for every config value. Can it be that that is some thing like **1.3** or the **2.2** approach?

**Comment by nhp** [comment]
Thanks for bringing this up. What i cannot see in the RFC is the possibility to not only inherit from a default value, if it is set but to also change this default value to a store specific one. Like in your example chaning the currency for a swiss shop to CHF instead of EUR. With all shown approaches I would assume that we would need to move `currency` to the store level then because it is not generally default.

Or would that be part of the "deep merge"  process you mentioned?

**Comment by lukeromanowicz** [comment]
@ResuBaka Sounds like extracting 1.1 to a helper. I'm only concerned that it still requires to check 2 different configs (global and storeview scoped) every time its called. It also requires a lot of changes in multiple places while making getting storeview values chaotic (we would have two ways of retrieving config values for storeviews).

@nhp 2.1 and 2.2 make the inheritance optional in all or nothing way. Just a matter of adding `"inherit": "base_storeview_code"`. In those approaches, everything in specific storeview config including subobjects (i18n, tax, elasticsearch) will get merged accordingly to the settings.

**Comment by lukeromanowicz** [comment]
So, I've created a PR accordingly to the 2.2. approach. Please take a look.

**Comment by lukeromanowicz** [comment]
I've also added loading fallback values from storeview scoped configs to default config so now the default config is global unless overriden in a storeview scoped config.

**Comment by patzick** [comment]
QA - ready for retests. Thanks @lukeromanowicz for feature :)
