### ISSUE TITLE
If you remove a product from your cart causing the current shipping method to become unavailable, the microcart does not properly update the totals

### ISSUE THREAD

**Issue by stevenoddy** [DivanteLtd/vue-storefront#3059]
## Current behavior
We have a fixed rate shipping method, and then a free shipping method available over £100. If you add over £100 to your cart, go to the checkout but then go back to the microcart it shows the free shipping option. If you then remove an item so the cart value becomes less than £100, the shipping-information API call fails with `{"code":500,"result":"Carrier with such method not found: freeshipping, freeshipping"}`

This then means the totals do not change at all on the microcart so the total is a lot higher than it actually is / should be.
<img width="748" alt="Screenshot 2019-06-15 at 18 01 18" src="https://user-images.githubusercontent.com/5173598/59554227-a5712480-8f97-11e9-9194-78d4442beb54.png">

## Expected behavior
I believe removing an item from your cart needs to request the shipping-methods API first, before requesting shipping-information with a shipping method that is actually available so then the totals on the mircocart are able to properly update.

## Steps to reproduce the issue
Create a shipping method in Magento admin over £x value.
Add over £x value to your cart.
Start the checkout and if not by default, select the newly available shipping method.
Go back to the microcart
Remove an item from cart causing you to go below £x

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
Hi there! I belive it has been fixed with the 1.10rc1. Please do check it out on the `develop` or `release/1.10` branches
