### ISSUE TITLE
Display product in all selected categories it belongs to instead of just first category

### ISSUE THREAD

**Issue by michhy** [DivanteLtd/vue-storefront#3066]
## What is the motivation for adding / enhancing this feature?

If a product belongs to more than one category, can it display in all the categories it belongs,
as it is now only displaying in first selected category.

## What are the acceptance criteria 

Display product in all selected categories it belongs to.
- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
Hmm. What do you mean by that? We're displaying the products from all sub-sequent categories (for example when you choose `women` we'll display the products from `women->tops` as well etc.)

**Comment by michhy** [comment]
Hi sorry for my poor expression.

For example my shop is selling food and groceries, for some product like "organic tomato sauce", it belongs to two categories:  "seasoning" and also "organic food".

In magento i can assign multiple categories for one products, and it will display in all assigned categories.

Hope this explains better about the situation.

Thanks a lot :)

**Comment by michhy** [comment]
I Found out the way, thank you :)
