### ISSUE TITLE
Error placing an order

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#3067]
## Current behavior

![Peek 2019-06-18 09-22](https://user-images.githubusercontent.com/49188852/59662341-04f44d80-91ad-11e9-8ddf-75e6630c5be5.gif)
Currently, there is no possibility to place an order on https://next.storefrontcloud.io/
Doesn't matter if the user is logged in or not. Checked on many data sets.
Validation messages appear:
'Error placing an order'
'The order can not be transferred because of server error. Order has been quequed. ' 

## Expected behavior

I can place an order with correct data. 

## Steps to reproduce the issue

1. Go to the category page.
2. Add any product to the cart.
3. Go to checkout.
4. Fill in all sections (personal details, shipping, payment, review order).
5. Click 'Place the order'. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 73
- OS: Ubuntu 18.04 LTS

## Additional information

The same problem appears when I try to place an order using Instant Checkout.

**Comment by patzick** [comment]
Should be good now, i compared jsons in POST, refreshed and redeployed API with current RC and created successfully new order.
