### ISSUE TITLE
No placeholders / no photos for Get Inspire section in offline

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3072]
## Current behavior
No placeholders / no photos for Get Inspire section in offline

![image](https://user-images.githubusercontent.com/36628922/59678369-84454980-91cc-11e9-974d-6608bd1365f9.png)
![image](https://user-images.githubusercontent.com/36628922/59679216-8a3c2a00-91ce-11e9-9067-0eb86a0cc794.png)

## Expected behavior
Pictures or placeholreds should be displayed instead.

## Steps to reproduce the issue
1. Open https://test.storefrontcloud.io
2. Go to any category or product page
3. Switch to offline mode
4. Come back to Home page

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
@przspa we're releasing 1.10rc1 - how about the status for this issue? :)

**Comment by przspa** [comment]
@pkarw I doesn't start yet. But this issue applies to all images in VSF, without product photos of course becouse I fixed this case
