### ISSUE TITLE
Missing translations for multistore - it_IT / de_DE 

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3076]
## Current behavior
1. Order confirmation page - lack of translations
2. Product page:
- Color Black
- Size XS
- Reviews section
- We found other products you might like section
3. Pop-ups:
- "Something went wrong. Try again in a few seconds."
- This product is out of stock.
- "PROCEED TO CHECKOUT"
- "Processing order"
- "We don't have as many "Minerva LumaTech&trade; V-Tee-S-Black" as you requested."
4. Cart:
- Subtotal
- Shipping & Handling (Flat Rate - Fixed)
- Tax
- Grand Total
- Color: Black
- Size: S
- In stock!
- Clear cart
- Discount
5. Checkout
- Subtotal
- Shipping & Handling (Flat Rate - Fixed)
- Tax
- Grand Total
5. My account:
- Homepage / My Account
- My Recently viewed products
6. Wishlist
- Clear wishlist
7. Compare Products
- Homepage / Compare
8. Categories:
- sub-categories names
- Clear filters
- Columns
- Sort by: Latest, Price low to high, high to low,
- X items
- "Please change Your search criteria and try again. If still not finding anything relevant, please visit the Home page and try out some of our bestsellers!"
9. Breadcrumbs
- Homepage / Magazine
- Homepage / Contact
- Homepage / Size guide
- etc
10. Search:
- Filter by categories
- Load more button
11. Error page:
- Something went wrong ...

## Expected behavior
All translations should be in accordance with the language of the store.

## Steps to reproduce the issue
1. Change your config:

- "multistore": false,  → *true*
- "appendStoreCode": true, →  *false*
- "disabled": true. → *false*

2. Go to http://localhost:3000/it/ or http://localhost:3000/de

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by lorenaramonda** [comment]
I fixed a typo on default language as a separate PR -> https://github.com/DivanteLtd/vue-storefront/pull/3596

**Comment by lorenaramonda** [comment]
I guess that trings like `We don't have as many "Minerva LumaTech™ V-Tee-S-Black" as you requested."` are coming directly from Magento/Api so they should come already translated because on the frontend we don't have a placeholder for the product name in that string so it is not possible to localize it.
