### ISSUE TITLE
Categories disappears when user is redirected to error page

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3077]
## Steps to reproduce the issue
1. Go to https://next.storefrontcloud.io/error
2. come back to Home page
3. Press hamburger menu

## Current behavior
Categories disappears when user is redirected to error page.
![error_page](https://user-images.githubusercontent.com/36628922/59743366-3da92b00-9270-11e9-980d-77f204bc8893.gif)

## Expected behavior
All available categories should be displayed in hamburger menu

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by patzick** [comment]
not merged yet and without milestone, reopening

**Comment by alinadivante** [comment]
problem still exist.
And if I refresh page then I'm redirected to https://next.storefrontcloud.io/error

**Comment by pkarw** [comment]
It's something wrong with the `next` instane - the home page (to which `Back` button is redirecting) generates an error - so there is an error loop

**Comment by alinadivante** [comment]
Ok - now it is fixed for Back button (I'm redirected to Homepage and categories are displayed in hamburger menu), but after pressing VSF logo on the error page (I'm redirected to Homepage), but there are no categories in menu

**Comment by pkarw** [comment]
:-(

**Comment by patzick** [comment]
merged, ready for tests
