### ISSUE TITLE
My Account submenu doesn't render properly on Safari (Mac & iPad)

### ISSUE THREAD

**Issue by bobcho** [DivanteLtd/vue-storefront#3087]
## Current behavior

If you go to the hamburger menu icon -> My Account, it appears empty on Safari - the "color" style is not picked up for the list of anchors.

![Screenshot 2019-06-19 at 17 45 24](https://user-images.githubusercontent.com/8062073/59775920-a1584600-92ba-11e9-9a79-56cf4c33ae66.png)

![Screenshot 2019-06-19 at 17 48 54](https://user-images.githubusercontent.com/8062073/59775942-aa491780-92ba-11e9-93f0-3bdadac8c136.png)

When you close the menu and re-open it, the anchors are now visible.

## Expected behavior

I expect to see the My Account sub-menu the first time I open it on Safari:

![Screenshot 2019-06-19 at 17 51 21](https://user-images.githubusercontent.com/8062073/59776090-e4b2b480-92ba-11e9-8772-3e81d8d3f4e5.png)

## Steps to reproduce the issue

As described above - go to https://demo.vuestorefront.io, login to account, go to Menu -> My account with Safari.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Safari Version 12.1.1 (14607.2.6.1.1), but also reproducible with Safari on iPad Pro.
- OS: MacOS, iOS
- Node: 
- Code Version: 

## Additional information

As the issue is only with the My Account sub-menu I assume it has to do with how this particular menu is rendered.

**Comment by pkarw** [comment]
@przspa can you Please update the status of this issue?

**Comment by przspa** [comment]
@pkarw it's ready, I test it now and creating PR

**Comment by patzick** [comment]
Thanks @przspa !

**Comment by bobcho** [comment]
thanks guys!
