### ISSUE TITLE
Add global error handler and renderer

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#309]
https://medium.com/the-vue-point/vue-2-5-released-14bd65bf030b

**Comment by kacperknapik** [comment]
worth noting: https://github.com/vuejs/vue/issues/6953#issuecomment-340335435

**Comment by kacperknapik** [comment]
According to the above comment, we have 2 kinds of errors - for simplicity, let's say, we have `DOM Event` errors, and 'everything else'.
At the moment, `DOM Event` errors, exceptions, etc, are not handled at all, they are silent and we don't know about them. 'Everything else' tho, throws `[Vue warn] ...` to the console. (as far as I know)
Thanks to this new `errorCaptured` hook, we can do something more with those errors (not `DOM Event` ones), but the question is, what do we want to do with them exactly.

I was thinking about the shop having 'dev mode', so we could place those errors to some kind of a HTML container, and show it to the devs. In 'prod mode' tho, errors will not be shown, instead, they could be shown in console only.

**Comment by pkarw** [comment]
OK, i think for now we could make use of: https://stackoverflow.com/questions/31472439/catch-all-unhandled-javascript-promise-rejections 

and 

https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror

BUT it's need to be tested while offline because I'm affraid that elasticsearch-js is raising lot of errors when there is no ElasticSearch enabled which in our case is not an issue (we do have cachced data localy)


To display error page with the details dumped to dev console in that case.


I move it to 0.4 as it's not key for now
