### ISSUE TITLE
Remove the core dependencies

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3094]
## What is the motivation for adding / enhancing this feature?

We should move the `cms`, `compare`, `newsletter`, `recently-viewed`, `social-share` and `wishlist` modules to separate repos + include them in the theme as a package.json dependencies.

All the references to these modules should be removed from the core.

## What are the acceptance criteria 

- [ ] cms moved to separate repo / module and included via theme package.json,
- [ ] compare moved to separate repo / module and included via theme package.json,
- [ ] newsletter moved to separate repo / module and included via theme package.json,
- [ ] recently-viewed moved to separate repo / module and included via theme package.json,
- [ ] social-share moved to separate repo / module and included via theme package.json,
- [ ] wishlist moved to separate repo / module and included via theme package.json,
- [ ] review moved to separate repo / module and included via theme package.json,

So what stays in the core?
- breadcrumbs,
- cart,
- catalog,
- checkout (merged with the order),
- offline-order,
- order,
- mailer, 
- url,
- user.

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
@filrak , @patzick, @lukeromanowicz feedback is appreciated

**Comment by filrak** [comment]
It's blocked by the fact that modules can't be packages. For now it could be only a git submodule

**Comment by pkarw** [comment]
Well, we need to unlock it then :D

**Comment by pkarw** [comment]
@filrak is this done already? I mean you moved some modules out of the core

**Comment by pkarw** [comment]
@andrzejewsky I'm not sure if this will be backward compatible but would simplify the core. If it can't be backward compatible let's don't do it
