### ISSUE TITLE
Refactor the `user` vuex module

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3095]
## What is the motivation for adding / enhancing this feature?

In order to prepare VS for 2.0 release we're refactoring some vuex modules in order to keep the good practices:
- remove state write operations from the actions,
- replace state read operations with vuex getters,
- preferably migrate from events-based logic to vuex actions,
- remove notifications from vuex (`spawnNotification`),
- remove `rootStore` references,
- extract network calls to `data-resolveres` (as introduced in the #2890)

## What are the acceptance criteria 

- [ ] `resetPassword`, `login`, `register`, `update`, `me`, `getOrdersHistory` network calls refactoed to helpers + then to `data-resolvers`
- [ ]  remove `callback_event` event's based logic - use just the `then(helperFnc)` instead
- [ ]  try to remove `spawnNotification` move the notifications one level higher (to the UI)
- [ ] replace all `rootStore` calls with the `context` instead (for example `context.rootState`)
- [ ] remove the calls to `history` and `me` from `login` (it should be extremly simple) - the `sessionAfterAuthorized` should be called instead - by some  observer (plugin?) on the user token
- [ ] replace all `fetch` calls with Task api calls

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by alinadivante** [comment]
@andrzejewsky Two things to fix:
1. When user registers new account, there is info "You are logged in" but he isn't logged in.
![image](https://user-images.githubusercontent.com/36628922/61714625-97af7b80-ad5b-11e9-8d18-964b73cf5820.png)
*Expected results:* 
User should be automatically logged in (it works on https://demo.storefrontcloud.io)

2. When I change manually token in dev console (shop/user/current-token) and open again my account and refresh page - there is info "Consumer is not authorized to access self" but user is still logged in. 
![image](https://user-images.githubusercontent.com/36628922/61714835-17d5e100-ad5c-11e9-8956-b7385182c54e.png)

*Expected results:* 
 shop/user/current-token should be replaced with the valid user token from Magento. 
"Consumer is not authorized to access self" error shouldn't occur.

**Comment by pkarw** [comment]
starting point for this issue (it's not related directly to refactor): https://github.com/DivanteLtd/vue-storefront/blob/76211f7d036a04b6db5eda31d1402753e5c58372/core/lib/sync/task.ts#L78

**Comment by pkarw** [comment]
Related: https://github.com/DivanteLtd/vue-storefront/pull/3237

**Comment by pkarw** [comment]
Please make sure you've got the proper version of `vue-storefront-api` deployed - https://github.com/DivanteLtd/vue-storefront-api/tree/release/v1.10 or https://github.com/DivanteLtd/vue-storefront-api/tree/develop @patzick

**Comment by andrzejewsky** [comment]
Fixed here: #3271 everything should works now.
