### ISSUE TITLE
Order placed in offline mode, without confirmation

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3098]
## Current behavior
My order is automatically placed when I get online, without order confirmation.
![offline_mode](https://user-images.githubusercontent.com/36628922/60011138-6f0f6580-9679-11e9-9f3d-db478ea497cc.gif)

## Expected behavior
"Confirm your order" pop-up should occur, before order will be placed.
If user confirms the order, success page should be refreshed and order ID should be displayed.
If user cancels the order, he should be redirected to Home page.

## Steps to reproduce the issue
0. Open https://next.storefrontcloud.io
1. Add to cart any product
2. Go to checkout
3. Switch to offline mode
4. Try to place the order
5. Switch to online mode (being on Success page)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version: 

## Additional information
If after placing the order, in offline mode, I go to Home page and then I will get online, the "Confirm order" pop-up will appear.

**Comment by pkarw** [comment]
It's not a bug. This feature is not confirming the order if you stayed at the Thank You page - assuming that the intention was to finalize the order and you just lost connection for a moment. If you were on any other url when bringing back the network connectivity: it wll ask you to connfirm the order
