### ISSUE TITLE
Date filter is ignoring the format parameter

### ISSUE THREAD

**Issue by juho-jaakkola** [DivanteLtd/vue-storefront#3102]
## Current behavior

I'm trying to change the format of a date within a template using the `date` filter:
```
<p>{{ item.created_at | date('format as a parameter here') }}</p>
```

But the date filter is in fact not using the parameter at all:
https://github.com/DivanteLtd/vue-storefront/blob/d40ba3b958c26d77d2d4c98bdf403af1ffd19275/core/filters/date.js

And therefore the date is always returned in the same format (e.g. `25.6.2019, 11:50:32`).

## Expected behavior
I should be able to choose the format when using the filter.

## Steps to reproduce the issue
Try to pass any argument to the `date` filter within a template:
```
<p>{{ item.created_at | date('format as a parameter here') }}</p>
```
No matter what you pass in, nothing happens.

## Repository
The latest commit for the file in the current `master` branch: https://github.com/DivanteLtd/vue-storefront/blob/d40ba3b958c26d77d2d4c98bdf403af1ffd19275/core/filters/date.js

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Any
- OS: Any
- Node: Any
- Code Version: v1.9.1

**Comment by grimasod** [comment]
On it
