### ISSUE TITLE
My Account - Profile rewrite

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#3104]
API is complicated and not descriptive (should be easy to use for a developer, right now it's mostly a set of internal helpers made to achieve certain result rather than an API) and it highly relies on event bus. Also logic from components needs to be moved to Vuex.
- Remove event bus and use hooks instead
- Refactor editing user data to Vuex
- Find new API for Vuex
Related to #2696 https://github.com/DivanteLtd/vue-storefront/issues/3103

**Comment by pkarw** [comment]
Closed with the https://github.com/DivanteLtd/vsf-capybara
