### ISSUE TITLE
Add default user's country selection based on browser language

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#312]
https://stackoverflow.com/questions/11826149/is-it-possible-to-determine-the-user-locales-country-as-set-in-the-os-from

**Comment by pkarw** [comment]
https://github.com/DivanteLtd/vue-storefront/pull/311#pullrequestreview-77812774

**Comment by pkarw** [comment]
@Aekal maybe just add the mapping feature we discussed within the PR as for now and when no country is mapped use default from config ?

**Comment by karolbzik** [comment]
@pkarw @Aekal - shouldn't we first add the language versioning (based on language and countries, like here:
![zrzut ekranu 2017-12-05 o 21 55 56](https://user-images.githubusercontent.com/18116406/33630329-41512280-da07-11e7-8e5b-78c84c1f8801.png)

We can add this in the form of pop-up, available through sidebar menu, my account (preferences) and link in the footer. I could add the designs. What do you think?

**Comment by moezzie** [comment]
I just submitted PR #1398 implementing this feature for the checkout and my account pages.
