### ISSUE TITLE
Let CLI create a working VS boilerplate + create boilerplate

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#3136]
When moving VueStorefront to an NPM package we'll have a CLI and wish to have a command to easily create a VueStorefront project.

VueStorefront will be an NPM dependency.

Do we want to ask questions while creating the project such as 
- testing framework
- type of backend (Magento|Shopware|etc)

**Comment by ResuBaka** [comment]
One question that would be great would be to ask the format of the config. 
Like yaml or json as example.

Should i open that as a feature request for version 2.0?
