### ISSUE TITLE
AddToCart button becomes grey out when endpoint is broken

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3150]
## Current behavior
AddToCart becomes grey out when endpoint is broken
![image](https://user-images.githubusercontent.com/36628922/60258296-2b189c80-98d5-11e9-9cc9-c4aba3d39b2b.png)

## Expected behavior
Despite that endpoint  is broken, AddToCart button should be active and an error message should be displayed. (e.g. Something went wrong ...)

## Steps to reproduce the issue
1. Broke "updateitem_endpoint": "https://demo.storefrontcloud.io/api/cart/update
2. Go to product page
3. Try to Add to cart

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by alinadivante** [comment]
Ok, now i get  _"Error with response - bad content-type_" message and Add to cart button is active

**Comment by pkarw** [comment]
Thanks for testing it out :)
