### ISSUE TITLE
Applied discount code is lost when logging in / creating account / placing an order with account creation

### ISSUE THREAD

**Issue by revlis-x** [DivanteLtd/vue-storefront#3153]
## Current behavior
When a user logs in after applying a discount code ("mmtest") in the cart (e.g. log-in on checkout page), the discount code is no longer applied.
Moreover, if the user chooses to create an account during checkout, the order is placed without the applied discount code.

## Expected behavior
Discount code is kept applied when user logs in or creates an account.

## Steps to reproduce the issue
1. Put item into cart and apply discount code "mmtest"
2a. Create or log into existing account -> discount no longer applied 
2b. Create account during checkout -> order is placed without discount

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
Good point! User authorization changes the shopping cartid (if user had the shopping cart assigned in magento) and in this case the discount code needs to be re-applied
