### ISSUE TITLE
Errors in dev console on /cms-block-demo-page-ssr page

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3155]
## Current behavior
Errors in dev console when after opening http://localhost:3000/cms-block-demo-page-ssr page

![image](https://user-images.githubusercontent.com/36628922/60341125-c41ae680-99ad-11e9-891f-14515554cf59.png)

## Expected behavior
Fix all errors

## Steps to reproduce the issue
1. Go to http://localhost:3000/cms-block-demo-page-ssr
2. Look at dev Console

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by alinadivante** [comment]
@pkarw I see in pr that you removed magento-2-cms module, but I'm not quite sure how can I now test issue if this CMS page does no longer exists?

**Comment by pkarw** [comment]
Well :) no page no issue ;) there is the “abouts us” page in demo which is using the currently recommended CMS module
