### ISSUE TITLE
Make image proxy url work with relative base url

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront#3158]
## Current behavior
If you use a relative `images.baseUrl` like `/img/` the path won't be build using the `api.url` config value like in the other endpoint, which forces you to use an absolute url at this point again.

## Expected behavior
Make image proxy url work with a relative base url using the `processURLAddress()` method.

## Steps to reproduce the issue
You can see it with each visible product image.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: all
- OS: all
- Node: default
- Code Version: Known in master and `develop`

## Additional information
Nope

**Comment by pkarw** [comment]
Good point! Thanks!
