### ISSUE TITLE
Sorting at a price in different ranges doesn't work properly

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3163]
## Relates to:
#2890

## Current behavior
Sorting at a price in different ranges doesn't work properly - only the last selected price range is taken into account.

![sortbyprice](https://user-images.githubusercontent.com/36628922/60433037-15241800-9c04-11e9-8f9c-54f9b11c0541.gif)

## Expected behavior
Available products should be displayed according to the selected price ranges.

## Steps to reproduce the issue
1.  Go to any category page, e.g. Men
2. Select Price > $ 50
3. Select also $100-150 and see results

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by alinadivante** [comment]
fixed ! @patzick could you  do the same solution for Erin recommendations?

**Comment by patzick** [comment]
this goes to #2322
