### ISSUE TITLE
Microcart product options for just added product

### ISSUE THREAD

**Issue by Cheeerd** [DivanteLtd/vue-storefront#3164]
When product is added to cart, "product.options" are printed instead of "product.totals.options" until totals are not loaded. And it seems that attribute code (lower first latter) is printed instead of attribute label.

Screenshot from https://demo.vuestorefront.io:
![image](https://user-images.githubusercontent.com/21987340/60448183-ca1efa80-9c2d-11e9-85d3-025f83379e02.png)

Maybe you should not omit configurable_options in cart/addItem action to be able to access option labels in microcart from there. Or should add labels to product.options.

**Comment by pkarw** [comment]
That's for sure a good idea. It requires a change to be made in here: https://github.com/DivanteLtd/vue-storefront/blob/3d1d81c0e1aebfcdeda97ea7fec58b6d3ab8ef29/core/modules/catalog/helpers/index.ts#L385

Probably just a mapping to the `product.configurable_options` - there is already an `option` mapped: https://github.com/DivanteLtd/vue-storefront/blob/3d1d81c0e1aebfcdeda97ea7fec58b6d3ab8ef29/core/modules/catalog/helpers/index.ts#L365

So probably we need just to make use of the `label` property - as it wasn't there when this helper was created :)

**Comment by pkarw** [comment]
@Cheeerd would you like to take care of this one?
