### ISSUE TITLE
Extended stock info access of cart items

### ISSUE THREAD

**Issue by Cheeerd** [DivanteLtd/vue-storefront#3166]
Add possibility to access stock info of cart item, not only is_in_stock.

## What is the motivation for adding / enhancing this feature?
For example, in magento in product settings you can setup backorder property. So if you want in custom theme to print in cart a special label if product will be backordered (stock.qty <= 0 && stock.backorders > 0) you need to access theese properties.

## Can you complete this feature request by yourself?
For now i simply added "stock: event.result" to product object passed to  "cart/updateItem" action in stockAfterCheck event in file core/modules/catalog/store/stock/actions.ts. But i'm not sure either it proper way or not.

#1751 seems related.

**Comment by pkarw** [comment]
Hey! yeah, this makes perfect sense- please propose a PR to the core with this change. Please also take a look at the `filterOutUnavailableVariants` (Find in Files) which may be useful - and it's also updating `product.stock` but not in the cart ([reference code](https://github.com/DivanteLtd/vue-storefront/blob/ae793cbaaa8c992b517e7264f3737afcbb4b625f/core/modules/catalog/helpers/index.ts#L123))

**Comment by Cheeerd** [comment]
Hello, i created pull request.
Also i enabled `products.filterUnavailableVariants` option and tested `filterOutUnavailableVariants`. If qty is zero but backorders are enabled, magento returns is_in_stock = true, so this method does not remove zero quantity childs with backorders.

**Comment by pkarw** [comment]
@Cheeerd cool! Please go forward with next core extensions, you did a great job and cool feedback :) Custom attributes are being indexed - but by default they're indexed as a product/child properties and not under the `custom_attributes` (https://github.com/DivanteLtd/mage2vuestorefront/blob/c71788e1c918225685344657f9d6ca0b2417d801/src/adapters/magento/product.js#L424)

**Comment by Cheeerd** [comment]
I also noticed that when stock item is saved to cache, the backorders property is not saved with it. I think it may be useful to save it too. But im afraid, that vuestorefront could be connected with another backend except magento, and there are this property may not exist or named differently.
https://github.com/DivanteLtd/vue-storefront/blob/84993c719af720042f44bb492f4374527623c003/core/modules/catalog/store/stock/actions.ts#L51

**Comment by pkarw** [comment]
Good point. As long as you keep these minimal fields included it’s safe with other platforms. We’ve just stored the most fundamental data into cache as the rest was not required by the filter out of the stock variants feature

**Comment by pkarw** [comment]
Hi @Cheeerd are you adding this cache extension in here or are we good to close this issue? I’m closing it for now and please do reopen when needed
