### ISSUE TITLE
To check: the number of product queries per CSR category request

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3167]
## Current behavior

I see that 3 product requests  and 2 category requests are being executed by each CSR click for products - https://www.dropbox.com/s/v6xayrafosq6812/Screenshot%202019-07-02%2022.18.07.png?dl=0

Please do check if all of them are necessary? I mean - we should probably have 2 product requests (list + cache (full records))

It's on 1.10rc-1

**Comment by pkarw** [comment]
The second category request is fine - it's for all the parts of the breadcrumb. So the question is for the 3rd product request

**Comment by pkarw** [comment]
Plus: please do remember on adding the support for `includeFields` and `excludeFields` in `loadCategoryProducts` as it's currently missed

**Comment by pkarw** [comment]
I belive that these requests to `category` are not required: https://www.dropbox.com/s/yclq2i7eeyn1fj5/Screenshot%202019-08-01%2012.36.14.png?dl=0 - this shows the network tab for just switching colors; so for sure no category change

**Comment by pkarw** [comment]
I also noticed that `cacheProducts` causes the Elastic error passing empty query (check network tab - there are 3 requests for products (why three?)) when switching the category the third one causes an error

In the effect [static stock prefetching doesn't work](https://github.com/DivanteLtd/vue-storefront/blob/cba50b931e5ce8c930ec4ff91c1b917e7c41c241/core/modules/catalog-next/store/category/actions.ts#L77)

Check it with the following config settings;

```
filterUnavailableVariants = true
configurableChildrenStockPrefetchStatic = true
configurableChildrenStockPrefetchDynamic = false
```

**Comment by pkarw** [comment]
Moreover the condigion [checking the first SSR request](https://github.com/DivanteLtd/vue-storefront/blob/cba50b931e5ce8c930ec4ff91c1b917e7c41c241/src/themes/default/pages/Category.vue#L155) should be changed from:

```js
if (from.name) { // SSR but client side invocation, we need to cache products
``` 

to

```js
    if (!from.name) { // SSR but client side invocation, we need to cache products
```

I've changed in the: #3477

**Comment by pkarw** [comment]
The problem is that `getters.getCategoryFromPath` doesn't support multistore - I mean storeprefixes; https://www.dropbox.com/s/9iearxcl1dmgoda/Screenshot%202019-09-04%2015.48.16.png?dl=0

**Comment by patzick** [comment]
Okay, here's what we've got to change:

1. When page is displayed without chosen filters, we get them from products query
2. When some filters are chosen, then we need to load all category filters
3. After changing some filter, we can change the rest of the displayed filters (they cannot be chosen) based on a returned query

**Comment by pkarw** [comment]
Correct. This change (I mean point 2) is required as before we were no situation that filters were included in the URL
