### ISSUE TITLE
Category products are not displaying in frontend

### ISSUE THREAD

**Issue by ewallkrishnaprakash** [DivanteLtd/vue-storefront#317]
I have installed the vue-storefront in our local with node (8.5.0 version) and we are finding a issue with the category pages. None of the category showing the products. 
Also had a issue with order creation. It  only creates order in indexdb not in magento2.

**Comment by pkarw** [comment]
Hi, are you using local or remote (https://demo.vuestorefront.io/api/catalog) backend? Did you use `npm run installer` to run your local instance?

To have orders synchronized with Magento you have to run `worker/order_to_magento.js` from `vue-storefront-api` using the following command: `npm run o2m` inside your `vue-storefront-api` folder

**Comment by ewallkrishnaprakash** [comment]
Hi, I am using local catalog and done the manual installation of vue-storefront for my local instance.

 Thanks for the update in order sync.

**Comment by pkarw** [comment]
OK, strange. I advise you to use the `npm run installer` because it's quite easy to forget about any of the steps like for example restoring the data dump or running the migrations (did you do both these steps? I mean: `npm run restore` -> `npm run migrate` within `vue-storefront-api`?)

**Comment by ewallkrishnaprakash** [comment]
Ok, let me try with the installer and shall get back.

**Comment by Chiragsorathiya** [comment]
I have same problem my category is displayed but products are not displayed. can you help me ?

**Comment by parthkamdar** [comment]
Hi, I am having the same issue. Every time I try `npm run o2m` i am getting the same error as show by Chiragsorathiya.
Also, after any new additions of products or any changes to the magneto backend do I have to restore and migrate the database and then restart the vuestorefront-api?
