### ISSUE TITLE
No products found on category pages for multistore - it_IT / de_DE

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3172]
## Current behavior
No products found on any category pages (for it_IT / de_DE stores), but I can open product page directly using URL

![image](https://user-images.githubusercontent.com/36628922/60591636-29e8e300-9d9f-11e9-993f-af9f18c7cb49.png)

## Expected behavior
All products should be displayed on category pages for it_IT / de_DE stores

## Steps to reproduce the issue
0. Setup multistore mode with default vue storefront settings
1. Open https://test.storefrontcloud.io/de or https://test.storefrontcloud.io/it
2. Go to any category

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
@patzick what's the status in here?

**Comment by cewald** [comment]
This might be same problem as I described here: #3286 
At least the empty category and missing title seems familiar.

**Comment by pkarw** [comment]
@cewald @alinadivante can we close this one after #3286 was already solved?

**Comment by cewald** [comment]
@pkarw Yes, it's solved.
