### ISSUE TITLE
Session gets lost

### ISSUE THREAD

**Issue by marvinhuebner** [DivanteLtd/vue-storefront#3178]
## Current behavior

If you are not active in the shop for some time, the session seems to lose its validity although "Remember me" was selected.

An error message (Consumer isn't authorized to access self) will appear in the frontend as "You are not logged in".

But the user is still access the account and navigate to data which is cached, but all new request to the API which requires authentication are throwing errors.

## Expected behavior

The session is not lost, especially if you user selects "remember me".

## Steps to reproduce the issue

![](https://gitlab.bergwerk.ag/heinz-gmbh/shop/magento/uploads/7c6efeccbecd52a3e1bd5ca259f39744/image.png)

## Can you handle fixing this bug by yourself?

We already tried to debug it, but currently we have no idea what could be the reason or where to start.

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome
- OS: Mac, Linux
- Node: 8
- Code Version: 1.9.2

**Comment by pkarw** [comment]
Hi! This is related to #3151 - if it will be fixed (and the fix is trivial as it seems ;-)) it should start refreshing the tokens again in case when token is outdated

**Comment by pkarw** [comment]
Related: https://github.com/DivanteLtd/vue-storefront-api/issues/297
