### ISSUE TITLE
Change the appearance of footer

### ISSUE THREAD

**Issue by Aekal** [DivanteLtd/vue-storefront#318]
I think we should change the appearance of the footer according to the design, because it differs now:
![zrzut ekranu 2017-11-27 o 10 32 19](https://user-images.githubusercontent.com/7126345/33259799-4af5c2b4-d35e-11e7-8043-c08934de0508.png)

From design:
![zrzut ekranu 2017-11-27 o 10 35 28](https://user-images.githubusercontent.com/7126345/33259955-bd7215ea-d35e-11e7-9ebb-8adf8b9119db.png)

I can work on it, just please let me know if it should be done this way.

**Comment by pkarw** [comment]
Yes, please take care of it if you can :) @karolbzik please confirm

**Comment by pkarw** [comment]
@Aekal ok please proceed with this one :)

**Comment by Aekal** [comment]
From where can I get social icons like Facebook etc? They don't appear in Material Icons. Do we have svg files or maybe we should add Font Awesome or similar pack?

**Comment by pkarw** [comment]
@Aekal could you just take them from Figma as SVG or sth?

**Comment by pkarw** [comment]
Could you just add the newsletter sign up popup? Like login page - only one field (email with validation) + checkbox, please?

**Comment by Aekal** [comment]
Sure, i can do it.

**Comment by karolbzik** [comment]
@Aekal - all assets are available to export via Figma's file, here - https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront-Open-Source.
In case of icons, we should use SVG files.

After you login to Figma (it's free), you will be able to use the exporting feature
<img width="744" alt="zrzut ekranu 2017-12-04 o 10 04 33" src="https://user-images.githubusercontent.com/18116406/33544336-b4476f66-d8da-11e7-8207-92bfd5eacaff.png">.

**Comment by karolbzik** [comment]
@pkarw please update our production (demo.vuestorefront.io) so I could test verify changes and confirm that the quality of footer ;)
