### ISSUE TITLE
eslint vue/no-use-v-if-with-v-for rule not respected

### ISSUE THREAD

**Issue by lsimone** [DivanteLtd/vue-storefront#3181]
## Current behavior
Currently in `Product` page `v-if` and `v-for` are used on the same element 4 times.

It [should be avoided](https://vuejs.org/v2/style-guide/#Avoid-v-if-with-v-for-essential) and eslint shows warnings.

Here the exact places:
- [one](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/pages/Product.vue#L60)
- [two](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/pages/Product.vue#L73)
- [three](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/pages/Product.vue#L85)
- [four](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/pages/Product.vue#L99)

## Expected behavior
either `v-if` should be used in a dom element that wraps the one having `v-for`, or the `v-for` should loop on a already filtered list (could be done in a computed prop), and `v-if` removed

## Steps to reproduce the issue
just run `npm run dev`

## Repository
https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/pages/Product.vue

**Comment by pkarw** [comment]
@filrak can you please take a look at this one?

**Comment by pkarw** [comment]
@przspa may I ask you to take care of this one please?

**Comment by przspa** [comment]
@pkarw sure :)

**Comment by przspa** [comment]
@pkarw but now @patzick working on #3217 it's not the same issues? In this case we should use computed property in this v-if.

**Comment by pkarw** [comment]
@przspa it's not - Patryk won't be changing the UI part

**Comment by patzick** [comment]
QA - after deploy there should be tested available options on product page - changing filters there. There should be visible only available options.

thanks @przspa

**Comment by alinadivante** [comment]
@przspa there are visible also not available options on PDP
