### ISSUE TITLE
Cart updates throttling in case of changing the quantity

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3191]
## What is the motivation for adding / enhancing this feature?

Currently (1.9.2, 1.10rc1) each keypress into `quantity` field (`Microcart/Product.vue`) causes the `cart/sync` action to be executed

There is something like this:

```
      <div class="h5 pt5 cl-accent lh25 qty">
        <base-input-number
          :name="$t('Quantity')"
          :value="product.qty"
          @input="updateQuantity"
          :min="1"
        />
      </div>
```

... and in the `microcart/components/Product.ts` (base component of this `Product.vue`)

```
    updateQuantity (quantity) {
      this.$store.dispatch('cart/updateQuantity', { product: this.product, qty: quantity })
    }
```

This causes immediate call to `cart/sync` and after entering kind of `6..1..` we've got two calls instead of one (just for 61)

We need a time-based throttling or some other way to limit this behavior

**Comment by pkarw** [comment]
@filrak or @patzick can you please take this one?

**Comment by pkarw** [comment]
We can probably use the `debounce` filter (example: https://github.com/DivanteLtd/vue-storefront/pull/2654/files)

**Comment by patzick** [comment]
@pkarw yes, debounce is right solution here:) it's 1.10 milestone, so will be added soon!
