### ISSUE TITLE
Add tags collection to product entity

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#32]
Migration documentation: https://github.com/DivanteLtd/vue-storefront-api/blob/master/doc/1.%20Data%20schema%20and%20migrations.md

it should be added in [vue-storefront-api](https://github.com/DivanteLtd/vue-storefront-api) project

The intent here is to have data source for product tags on ProductTile:
![tags](https://user-images.githubusercontent.com/211899/31143411-91ac8168-a87d-11e7-84d6-4720da55e590.png)

The migration should add some random tags to the existing products database

**Comment by karolbzik** [comment]
@pkarw - do you mean tags like "new" or "sale"?
