### ISSUE TITLE
Problem with placing an order if shipping method is different than default one

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3203]
##Relates to: 
#2881

## Steps to reproduce the issue
1. Add any product to cart and go to checkout
2. Fill in shipping address but, choose United States
3. In Shipping method choose Table Rate (different method than default)
4. Click "Continue to payment" and try to place the order

## Current behavior
The order can not be transferred. Internal server error occurs.

![shipping_method](https://user-images.githubusercontent.com/36628922/60886719-fac8ea80-a252-11e9-8728-40b743dc6d72.gif)

Wrong shipping_carrier_code/shipping_method_code:

![image](https://user-images.githubusercontent.com/36628922/60886308-ea644000-a251-11e9-8a59-5a8049d318c9.png)

```
shippingAddress: {region: "Dolnośląskie", region_id: 0, country_id: "US", street: ["Dmowskiego 123", "645"],…}
shipping_carrier_code: "flatrate"
shipping_method_code: "bestway"
```

What more: Sometimes the application does not respond after pressing the "Place an order" button

## Expected behavior
After choosing available shipping method order should be transferred correctly.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome 73.0.3683.103
- OS: Windows 10 Pro
- Code Version: v1.9.0

**Comment by alinadivante** [comment]
great :) I tried different combinations for shipping methods and payment methods and now it works! :)

**Comment by alinadivante** [comment]
One more thing @patzick  :P
Shipping method in not updated in Order Summary
![image](https://user-images.githubusercontent.com/36628922/61623346-c0aa1080-ac76-11e9-953b-da3c57f9766d.png)


Please fix it :)

**Comment by pkarw** [comment]
it seems like the `cart/syncTotals` is not being called or the `getters/cart/isTotalsSyncRequired` returns false. `cart/syncTotals` has a special flag `forceServerSync` - make sure it's set to true while switching the payment methods @patzick

**Comment by pkarw** [comment]
@patzick how about this one? It's seemingly the last one blocking the 1.10 release as @lukeromanowicz seemingly solved the memory leak issue

**Comment by pkarw** [comment]
@patzick what's the status with this one?

**Comment by patzick** [comment]
@pkarw done with PR #3335

**Comment by ArturDivante** [comment]
Problem gone :)
