### ISSUE TITLE
Get also none product image thumbnails via API

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront#3207]
## What is the motivation for adding / enhancing this feature?

At the moment it seems only to be possible to fetch product images thumbnails via the api (for Magento 1 and 2).

As I implement some CMS data to our Vue-Storefront I noticed that it might be a good core feature to also fetch images which are not in the `/media/catalog/product" folder.

In fact this is a feature which is deeply implemented everywhere in the core and theme and you would need to extend the API as well if you ad a new endpoint. This will be a lot of code changes.

I think the best way would be to extend the current `getThumbnail()` by a path parameter which might be set in the `config.json` for the different types (cms/product).

## What are the acceptance criteria 

- [ ] Add new parameter to method `getThumbnail()` to add a `/media` path with default product path as default parameter to get product images as usual to prevent to change the theme and core modules at all places
- [ ] Add two new paths to VSF config in `images` for `product_path` and `cms_path`
- [ ] Change API base `imgUrl` in `magento1` and `magento2` platform settings to `/media` base path without `/catalog/product` or maybe use `assetPath`
- [ ] Serve backwards compatibility for old path in api settings

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information

none

**Comment by pkarw** [comment]
It's good idea - for sure this should be configurable./extendable (the way we generate thumbnails). Related to https://github.com/DivanteLtd/vue-storefront/issues/3160

@filrak maybe we just can have a `mutator` hook on generating the thumbnail? It makes a lot of sense and it's very general purpose kind of hook

**Comment by cewald** [comment]
I opened a PR: #3209
