### ISSUE TITLE
Module cross-env in devDependencies

### ISSUE THREAD

**Issue by mkoszutowski** [DivanteLtd/vue-storefront#3210]
For command `yarn install --production` I have error `/bin/sh: cross-env: not found`. Module cross-env is in `devDependencies` but should be in `dependencies`

**Comment by przspa** [comment]
@pkarw I'm not sure about that. Cross-env is a devDependencis (https://www.npmjs.com/package/cross-env) and we need devDependencies to build VSF :)

**Comment by mkoszutowski** [comment]
@pkarw I tried to build optimised front docker image. I used command: 
```
RUN yarn install \
  && yarn build:client \
  && yarn build:server \
  && yarn build:sw \
  && yarn install --production
```
In my opinion it should work fine but it doesn't because of dependencies.

**Comment by pkarw** [comment]
@przspa can you please check it?

**Comment by przspa** [comment]
@pkarw ok I check it and find solution.
