### ISSUE TITLE
translation refactoring

### ISSUE THREAD

**Issue by unherz** [DivanteLtd/vue-storefront#3213]
## Current behavior
There are many translations for german but most of them use the informal way of adressing the reader. This is inappropriate in most cases.

## Expected behavior
All way of adressing the reader is either formal passive. This means for the german language for example: "Sie" instead of "du" aso.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: any
- OS: any
- Node: any
- Code Version: release/1.10

**Comment by pkarw** [comment]
Good point!

**Comment by unherz** [comment]
It this a general point including serveral other languages?

**Comment by pkarw** [comment]
I have no idea - I can just say it's fine for PL and EN :)

**Comment by unherz** [comment]
Okay, for now wen can stick to german with this topic. The german translations need some refreshment. I will take care of it either later today or tomorrow and open a PR for it :)

**Comment by pkarw** [comment]
Cool! Thanks!

**Comment by unherz** [comment]
Short update on this topic: I'm halfway done. There si just the pretty short core translatiuon file left. I might open an PR in the next two hours.
