### ISSUE TITLE
Multi Store without "/de" but with subdomain

### ISSUE THREAD

**Issue by Ravin0319** [DivanteLtd/vue-storefront#3221]
Hello,

For the Multi store how can i achieve the below:-

1. I have 2 stores ['ae', 'sa']
2. The default store is 'sa' and language is "arabic"
3. i need to change the store from "Language.vue" with vue methods/function - here the user can select One country and also the language English or Arabic.
4. How to change Language (English and Arabic) from a vue method function.
5. How to change Store ("sa", "ae") from a vue method function.

I have updated my local.json accordingly.

But i do not want the "url": "/ae" if a different store is picked, Instead i need the Language in the URL: "/en" for english and no url for Arabic as this is the default language.

Final Result:-
1. www.example.com (this is "sa" default store so no subdomain)
2. www.example.com/en (/en if english language)
3. ae.example.com (for "ae" store)
4. ae.example.com/en (for english)

Based on the subdomain/vue method the store needs to be set accordingly so i can use the below details to access the current store.

const storeView = currentStoreView()
storeView.i18n.currencyCode
storeView.i18n.defaultCountry
storeView.i18n.defaultLanguage

Is there an easy way to achieve this? without changing alot of things.

Many Thanks

**Comment by Ravin0319** [comment]
@lukeromanowicz Sir, Please help me out with the above.

**Comment by lukeromanowicz** [comment]
@Ravin0319 what are the store codes for every each these URLs?

**Comment by Ravin0319** [comment]
`"ae": {
        "url": "",
        "storeCode": "ae",
        "disabled": false,
        "storeId": 1,
        "name": "United Arab Emirates Store",
        "tax": {
          "sourcePriceIncludesTax": false,
          "defaultCountry": "AE",
          "defaultRegion": "",
          "calculateServerSide": true
        },
        "i18n": {
          "fullCountryName": "United Arab Emirates",
          "fullLanguageName": "Arabic",
          "defaultLanguage": "AR",
          "defaultCountry": "AE",
          "defaultLocale": "ar",
          "currencyCode": "AED",
          "currencySign": "AED",
          "dateFormat": "HH:mm D-M-YYYY"
        }
      }`

The above is for the 'ae'  and 'sa' is Default store

**Comment by lukeromanowicz** [comment]
For every url you need to have separate storeview code. In current setup there is no way to have multiple URLs set for the same storeview. It doesn't even make sense to do it from seo perspective since Google doesn't like content duplication across multiple pages.

**Comment by Ravin0319** [comment]
Sorry, Not sure if i understand your question. below is the storeViews defined in my local.json

"storeViews": {
      "multistore": true,
      "commonCache": true,
      "mapStoreUrlsFor": ["ae", "kw", "iq"],
      "ae": {
        "url": "/ae",
        "storeCode": "ae",
        "disabled": false,
        "storeId": 1,
        "name": "United Arab Emirates Store",
        "elasticsearch": {
          "host": "/api/catalog",
          "index": "vue_storefront_catalog_ae"
        },
        "tax": {
          "sourcePriceIncludesTax": false,
          "defaultCountry": "AE",
          "defaultRegion": "",
          "calculateServerSide": true
        },
        "i18n": {
          "fullCountryName": "United Arab Emirates",
          "fullLanguageName": "Arabic",
          "defaultLanguage": "AR",
          "defaultCountry": "AE",
          "defaultLocale": "ar",
          "currencyCode": "AED",
          "currencySign": "AED",
          "dateFormat": "HH:mm D-M-YYYY"
        }
      },
      "kw": {
        "url": "/kw",
        "storeCode": "kw",
        "disabled": false,
        "storeId": 2,
        "name": "Kuwait Store",
        "elasticsearch": {
          "host": "/api/catalog",
          "index": "vue_storefront_catalog_kw"
        },
        "tax": {
          "sourcePriceIncludesTax": false,
          "defaultCountry": "KW",
          "defaultRegion": "",
          "calculateServerSide": true
        },
        "i18n": {
          "fullCountryName": "Kuwait",
          "fullLanguageName": "Arabic",
          "defaultLanguage": "AR",
          "defaultCountry": "KW",
          "defaultLocale": "ar",
          "currencyCode": "KWD",
          "currencySign": "KWD",
          "dateFormat": "HH:mm D-M-YYYY"
        }
      },
      "iq": {
        "url": "/iq",
        "storeCode": "iq",
        "disabled": false,
        "storeId": 11,
        "name": "Iraq Store",
        "elasticsearch": {
          "host": "/api/catalog",
          "index": "vue_storefront_catalog_iq"
        },
        "tax": {
          "sourcePriceIncludesTax": false,
          "defaultCountry": "IQ",
          "defaultRegion": "",
          "calculateServerSide": true
        },
        "i18n": {
          "fullCountryName": "Iraq",
          "fullLanguageName": "Arabic",
          "defaultLanguage": "AR",
          "defaultCountry": "IQ",
          "defaultLocale": "ar",
          "currencyCode": "USD",
          "currencySign": "$",
          "dateFormat": "HH:mm D-M-YYYY"
        }
      }
    }

we are migrating to VueStoreFront and our website has different subdomains for each country ("ae", "kw", "iq") and "sa" is the default sore without the subdomain.

currently VSF has "/de" the country code in the url, instead of this i want to change to "/en" if the language is "English" and  have the store code as subdomains. 

If this approach is not correct, Please suggest the best way to proceed. (but i really need the '/en' in the url instead of the country code )

**Comment by filrak** [comment]
https://medium.com/@apalshah/vue-js-how-to-handle-multiple-subdomains-on-a-single-app-cba9b1f916c4 you may need to do a little bit of hacking on rputer with passing proper storecodes but seems doable

**Comment by Ravin0319** [comment]
Thanks @filrak

**Comment by lukeromanowicz** [comment]
It's not possible to do it in 1.9 without dirty hacking. You can implement it easily with 1.10 if I remember correctly, but it hasn't been released yet.
