### ISSUE TITLE
Plugin doesnt called

### ISSUE THREAD

**Issue by serzilo** [DivanteLtd/vue-storefront#3238]
## Current behavior
I create new module and set plugin to store. But this plugin doesnt call when I update the store.

```
export const Wishlist = createModule({
  key: KEY,
  store: {
    modules: [{key: KEY, module}],
    plugin
  },
  afterRegistration
})
```

## Expected behavior
Plugin must be called.

## Additional information
I see that I can fix it in file core/lib/module/index.ts Just need to add:
```
const mergedStore = { modules: [], plugin: null }
mergedStore.plugin = extendedStore.plugin || originalStore.plugin || null
```

**Comment by filrak** [comment]
Thanks for spotting this bug! Could you propose the fix by yourself as PR?

**Comment by serzilo** [comment]
Yes.

**Comment by serzilo** [comment]
https://github.com/DivanteLtd/vue-storefront/pull/3241

**Comment by serzilo** [comment]
Fixed.
