### ISSUE TITLE
console.debug is not a function

### ISSUE THREAD

**Issue by talalus** [DivanteLtd/vue-storefront#326]
Currently getting this error 
```
TypeError: console.debug is not a function
    at server-bundle.js:20710:17
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
console.debug() isn't exist in node.js https://nodejs.org/api/console.html
Need to replace it with something else.

**Comment by pkarw** [comment]
Can you take care of this probably applying some logger (Winston?) which works on both client and server side?

**Comment by talalus** [comment]
ok I'll add Winston

**Comment by kacperknapik** [comment]
`console.debug` didn't work in Node.js v6.x (as well as a few other things),
updating Node to v8.x fixed the problem for me

**Comment by talalus** [comment]
closing this since it works fine with Node v8.x
