### ISSUE TITLE
SSR localized routes problem with Multistore

### ISSUE THREAD

**Issue by grimasod** [DivanteLtd/vue-storefront#3262]
## Current behavior

In a multistore setup, all stores get the same localized routes in SSR, depending on which store was requested first.

## Expected behavior

Each store should have correct localized routes in SSR

## Steps to reproduce the issue

1. Using a default installation of VS, enable multistore in local.json `"storeViews":  "multistore": true, ...`
2. Build with multistore enabled `yarn build` and start the server `yarn start`
3. In a browser, view the default store home page source `view-source:http://localhost:3000`
4. Search for `<a href`. The first result is the logo link `<a href="/" title="Home Page" ...` 
5. Do the same for DE store `view-source:http://localhost:3000/de`
6. The logo link is still non-localized `<a href="/" title="Home Page" ...` it should be `/de/`
7. Now restart the server `yarn start`
8. Refresh `view-source:http://localhost:3000/de`
9. The route is correct for this store `<a href="/de/" title="Home Page" ...`
10. But, refresh the default store `view-source:http://localhost:3000`
11. And now it incorrectly has the DE routes `<a href="/de/" title="Home Page" ...`

The same problem can be see on demo.storefrontcloud.io and next.storefrontcloud.io. See `view-source:https://next.storefrontcloud.io/de` - the routes are not localized.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 75
- OS: MacOS Mojave
- Node: v10.15.3
- Code Version: v1.10

**Comment by pkarw** [comment]
thanks, @grimasod; what struck me is that the only route that causes this problem is `/` - all the product and category links look just fine (can you please confirm?)

**Comment by grimasod** [comment]
@pkarw I think it's more complicated than that, unfortunately. I get a mixture of fine (Products) and not fine (Home, Categories, Footer links).

After the steps above, here's a selection of links:

- <a href="/de/" title="Home Page"
- <a href="/de/c/women-20"
- <a href="/de/c/men-11" 
- <a href="/de/c/gear-3"
- <a href="/women/tops-women/tees-women/tees-25/radiant-tee-1561.html?childSku=WS12"
- <a href="/women/tops-women/tees-women/tees-25/desiree-fitness-tee-1593.html?childSku=WS05"
- ...
- <a href="/de/my-account"
- <a href="/de/delivery"
- ...

Do you get a different outcome?

**Comment by pkarw** [comment]
It seems like there is some issue with `localizedRoute` helpers - maybe after last changes to `multistore.ts` applied some time ago (to 1.9 I belive) @lukeromanowicz please check it

**Comment by pkarw** [comment]
@lukeromanowicz any progress on that?

**Comment by lukeromanowicz** [comment]
Issue reproduced but I haven't been able to investigate it yet.

**Comment by pkarw** [comment]
@lukeromanowicz can we close it just after #3331

**Comment by lukeromanowicz** [comment]
Yes :)

**Comment by ArturDivante** [comment]
Problem fixed on next :) Well done :)
