### ISSUE TITLE
ProductVideo component not displaying videos

### ISSUE THREAD

**Issue by juho-jaakkola** [DivanteLtd/vue-storefront#3263]
## Current behavior

Product videos do not play on the PDP. Instead the page gives the warning:

> [Vue warn]: Missing required prop: "id"

Since the commit  https://github.com/DivanteLtd/mage2vuestorefront/commit/6e5e370414f4d0ee807710108623eb2f61cdf94d both the `mage2vuestorefront` and `magento2-vsbridge-indexer` are mapping the video id to `video_id` field. The name however has not been changed into the `ProductVideo.ts` that receives it as a parameter.

## Expected behavior

It should be possible to watch product videos on the PDP.

## Steps to reproduce the issue

1. Add a video to a product in the Magento admin backend
2. Try to watch the video on the PDP in Vue Storefront 
3. The video placeholder image is visible, but the video won't start playing

## Repository

https://github.com/DivanteLtd/vue-storefront/blob/4c11039c2c6cfb63e4e233a9e3b3273da7844ad0/core/modules/catalog/components/ProductVideo.ts#L8

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: any
- OS: any
- Node: any
- Code Version: 4c11039c2c6cfb63e4e233a9e3b3273da7844ad0

**Comment by pkarw** [comment]
Hi @juho-jaakkola can yple please provide us with PR fixign this issue/

**Comment by alinadivante** [comment]
video is available on magento site https://magento231-demo.storefrontcloud.io/nona-fitness-tank.html
but on vsf not https://test.storefrontcloud.io/women/tops-women/tanks-women/bras-and-tanks-26/nona-fitness-tank-1737.html

probably something went wrong during fullreindex.sh (I did also yarn db rebuild)

We need to check why it doesn't work on VSF. We will probably need you @pkarw

**Comment by pkarw** [comment]
I've moved it to 1.11 - @lukeromanowicz could you please take a look at it? I coldn't find time to have it checked :/

**Comment by pkarw** [comment]
Re-assigned to @przspa

**Comment by przspa** [comment]
@pkarw I can check this issue after wednesday

**Comment by przspa** [comment]
@pkarw #3264 this PR isn't right because we have map for it https://github.com/DivanteLtd/vue-storefront/blob/be5d5faddf844ee7e731dc9adb206709bf288b3d/core/modules/catalog/helpers/index.ts#L540 I fix it 👍
