### ISSUE TITLE
Improve the caching headers for static files

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3268]
## What is the motivation for adding / enhancing this feature?

We can set the proper caching strategy in the [`core/scripts/server.js`](https://github.com/DivanteLtd/vue-storefront/blob/d8db8a4f2dc9b9e2315f19b7ad4e625ce2ff1558/core/scripts/server.js#L112)

Red more on setting the [serve-static](https://expressjs.com/en/resources/middleware/serve-static.html) cache control. 

Then the second option is to set the proper cache headers on the proxy (nginx or varnish)

## What are the acceptance criteria 

- [ ] `Etag`, `Cache-*` headers set for static files to improve the caching

**Comment by patzick** [comment]
Done by @phoenix-bjoern, nice job! :)

**Comment by boehsermoe** [comment]
The max age of the cache control header should be second not milliseconds! 
Wrong in -> https://github.com/DivanteLtd/vue-storefront/blob/master/core/scripts/server.ts#L134
