### ISSUE TITLE
Remove attribute.list from initial state for product page

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3281]
## What is the motivation for adding / enhancing this feature?

Currently, the initial state can be really huge mostly because of the __INITIAL_STATE__. Removing the server pre-fetched attributes list seems like a safe bet to improve it (as the attributes will be loaded client's side then anyway)

To comment out this line for tests: https://github.com/DivanteLtd/vue-storefront/blob/d6ace4928f3334739c099f7a481ad80e683175a4/core/modules/catalog/store/product/actions.ts#L627

TODO:
- [ ] figure out the Category initial state if there are any other things which can be safely removed from the initial state (and loaded just client's side)

**Comment by pkarw** [comment]
The potential issues will be related with the hydration

**Comment by patzick** [comment]
Closed by #3326 :)
