### ISSUE TITLE
New getter `category-next/getCategoryFrom` and `category-next/getCurrentCategory` always returns the root category

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront#3286]
## Current behavior

The new getter `category-next/getCategoryFrom` (and `category-next/getCurrentCategory`) on the new category page always returns the root category because of a wrong filter in its getter.

This happens if there is a category with a path like `/` or a empty one in the `category-next/categoriesMap` state.

E.g. if you are in `/boys.html` and the it crawls to the states it tests like:
```javascript
return getters.getCategories.find(category => path.includes(category.url_path)) || {}
```
If there is a category with path `/` (or empty) in the state, it will always return this one. This filter is quiet flacky. I would prefer something more concrete like this:
```javascript
return getters.getCategories.find(category => path.replace(/^(\/)/gm, '') === category.url_path) || {}
```

Also what happens if you use a different url path, then it would never find the right current category, e.g. I added an extra mapper fallback to let the `/new.html` category availaible ever `/new` this won't over work with the new getters based on route path. You will need at least another getter for this at least.

I think this new functionality leads a bit in the wrong direction and needs way more flexibility.

## Expected behavior

Get the right category from state.

## Steps to reproduce the issue

See above.

## Repository

develop

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: All
- OS: All
- Node: All
- Code Version: develop:latest

**Comment by cewald** [comment]
Okay, I think I found a solution and will open an PR later today for a more flexible integration :)

**Comment by cewald** [comment]
I added a PR with some comments: #3295

**Comment by cewald** [comment]
@patzick I made some improvements in the related PR #3295

**Comment by patzick** [comment]
Great job @cewald, thanks for your input! :)
