### ISSUE TITLE
"docker-compose up" is not working on OSX

### ISSUE THREAD

**Issue by philippsander** [DivanteLtd/vue-storefront#3299]
## Current behavior

Port 3000 is not exposed be cause "network_mode: host" does not work on OSX (https://docs.docker.com/network/host/) and just deleting the network_mode makes vue-storefront unable to communicate with the API, ES, ...

## Expected behavior

"docker-compose up" exposes port 3000

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: OSX 10.14.5 
- Node: 
- Code Version:

**Comment by philippsander** [comment]
@patzick please add the Hackathon-Label ;-) Thanks again for the awesome session!

**Comment by pkarw** [comment]
hey there! any ideas on how to solve this one? I believe it's related to https://github.com/DivanteLtd/vue-storefront/issues/2861

**Comment by philippsander** [comment]
hey! this actually seems to be related. My problems seem to be more drastical since I wasn't even able to view my application.

I'm looking for a clean solution, but my workaround was deleting the network_mode and then using "host.docker.internal" instead of "localhost" for the endpoints in the configuration

**Comment by tharoldD** [comment]
@philippsander your workaround worked for me too.

**Comment by pkarw** [comment]
Closed by #3801 @kkdg we probably need to add a note on this config option to the docs

**Comment by mateuszrusiecki** [comment]
> Closed by #3801 @kkdg we probably need to add a note on this config option to the docs

And where is the note? Looks like nobody added it
