### ISSUE TITLE
Add search widget feature

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#33]
Add the search widget feature.

Business scenarios:
- As a Customer I can open search widget by clicking the button on the top;
- As a Customer, I can type searched product (phrases like name of the product, SKU number, product category etc.) and as the result, I will instantly see the grid of products in search widget;
- As a Customer, I can modify searched phrase and the product grid will be instantly updated;
- As a Customer, I can click any product on the grid in search widget and move to the product card.

The design of the view:
<img width="1440" alt="search widget" src="https://user-images.githubusercontent.com/18116406/31162326-0332e458-a8dd-11e7-8eb2-46f2a65cfcf6.png">

**Comment by pkarw** [comment]
Probably need to user `search` action from  `/store/modules/catalog.js`

**Comment by collymore** [comment]
I can complete this task. What do you think about including https://community.algolia.com/vue-instantsearch/ as a secondary search service option?

**Comment by pkarw** [comment]
@collymore Cool! We’re using elastic search so we do have search capabilities already included :) I mean - Algolia is kind of cool product for search but as we’re on MIT we shouldn’t have any paid services included by default. Would be great to prepare optional extension for Algolia that user can use as a inplace replacement for the defaults.

What do you think? We already have a mechanism for extensions so I believe if you add proper events/hooks or simply use Mixins to override the default search I would work.

But the default search must base on ES.

Please take a look at src/pages/Category.vue on how we’re building sophisticated ES queries using product vuex store and bodybuilder package for elasticsearch-JS

In case of any questions just ask!

**Comment by collymore** [comment]
Thanks for the info, that makes sense. 

I'll get this done next week then on ES.  

What's the best way to request other issues to be assigned to me? 

Should I Comment on them or message on Slack?

**Comment by pkarw** [comment]
Cool to hear that! Yes, just please comment them and put me @pkarw in the comment to notify me
