### ISSUE TITLE
Add logged in user view

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#330]
Karl, as we do have login feature already implemented we do need some top-bar with logged-in user info and LogOut feature

**Comment by pkarw** [comment]
As for now please add just an icon (user profile) on the right side of shopping cart when the user is logged in that's redirecting to Customer Account page

**Comment by pkarw** [comment]
https://github.com/DivanteLtd/vue-storefront/issues/316 - here you have an idea how it should look like

**Comment by pkarw** [comment]
if `state.user.current !== null` i means user is logged in

**Comment by karolbzik** [comment]
Logout feature will be the available in the sidebar menu and in the dropdown menu after clicking the profile button at the top. Soon I will upload the design, I want us to have a consistent dropdown feature.

For now, I suggest creating the frame for My account feature from https://github.com/DivanteLtd/vue-storefront/issues/316 issue.

**Comment by karolbzik** [comment]
@pkarw is this issue finished or should we plan it for later?

**Comment by pkarw** [comment]
For me it’s finished - let’s add the logout feature while introducing Custmer Account what do you think?

**Comment by karolbzik** [comment]
I will extend sidebar navigation (nested navigation) and top navigation (dropdown) on display so the My account feature will be easily accessible.

**Comment by karolbzik** [comment]
Here's how we should extend sidebar navigation for a logged customer
<img width="360" alt="sidebar menu my account on mobile" src="https://user-images.githubusercontent.com/18116406/33961263-aa43396c-e04d-11e7-9366-a381a46d28a7.png">
<img width="360" alt="sidebar menu on mobile" src="https://user-images.githubusercontent.com/18116406/33961264-aa7802dc-e04d-11e7-945f-a813f709f406.png">

**Comment by pkarw** [comment]
Related to: #391 and #8

**Comment by pkarw** [comment]
@akbarik this is connected to #316
