### ISSUE TITLE
Direction RTL

### ISSUE THREAD

**Issue by Ravin0319** [DivanteLtd/vue-storefront#3304]
Hello Team,

I have english and arabic language in my VueStoreFront.

I want to ask, What is the correct way to implement the dir="rtl" for arabic language stores.

Please suggest which file and method to implement. The direction rtl should be applied before the page is loaded.

Thanks!

**Comment by filrak** [comment]
Hey!
This snippet in `src/themes/default/css/base/base.scss` should do the job
```css
div, p {
    direction: rtl;
}
```

**Comment by Ravin0319** [comment]
@filrak Thanks for answering

Will this apply to only arabic  language stores?

**Comment by Ravin0319** [comment]
Thanks @filrak

**Comment by talalus** [comment]
Here is a an example of extended webpack.config.js include postcss-rtl to auto flip css properties https://github.com/hoopoemedia/vsf-theme-default-rtl
