### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by SebSzcze** [DivanteLtd/vue-storefront#3309]
## Current behavior
In current develop some translation strings are missing 
https://tppr.me/iEgOk

## Expected behavior
No i18n warnings are displayed 

## Steps to reproduce the issue
`yarn dev` 

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

This is a bug report for current develop

**Comment by pkarw** [comment]
@SebSzcze is it for `en_us` locale?

**Comment by SebSzcze** [comment]
yes, but I suppose it's missing for all locales

**Comment by pkarw** [comment]
OK, can you add it to en_us as for now? it's always the most current one and the others are getting updated / synced to it

**Comment by pkarw** [comment]
This is strange - i've got no such messages in develop branch :( can you please recheck?
