### ISSUE TITLE
There is no information about the quantity of the product that is edited in the cart

### ISSUE THREAD

**Issue by Michal-Dziedzinski** [DivanteLtd/vue-storefront#3314]
## What is the motivation for adding / enhancing this feature?

In the cart it is now possible to change to such a product parameter that quantity is currently 0. This deletes the product, instead of informing the user that there is no possibility of such a change.

![microcart](https://user-images.githubusercontent.com/32803679/62207627-e29d4480-b394-11e9-8eb6-c04b4b107c1c.gif)

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information

I think a feature like #3165  in should be added

**Comment by pkarw** [comment]
Good point!
