### ISSUE TITLE
Adding Discount Coupon to Guest Cart always fails

### ISSUE THREAD

**Issue by fewinkelbauer** [DivanteLtd/vue-storefront#3318]
## Current behavior
Trying to add a discount coupon to a guest cart will always decline the coupon. Applying discount code works when logged into an account.

## Expected behavior
The discount coupon is applied to the guest cart.

## Steps to reproduce the issue
1. Add items to cart while not logged in
2. Try to apply a discount coupon

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Code Version: 1.9.0

**Comment by pkarw** [comment]
Hi! Thanks. Can you please check if this error occurs on the `release/v1.10` branch as well?

**Comment by juho-jaakkola** [comment]
I will test with `release/v1.10` later today.

**Comment by juho-jaakkola** [comment]
The discount code works in `release/v1.10` with a guest cart. I believe the issue can be closed.
