### ISSUE TITLE
problem with product counter

### ISSUE THREAD

**Issue by EliotRaven** [DivanteLtd/vue-storefront#3320]
## Current behavior
when the button is pressed, the counter behaves inappropriately

## Expected behavior
item will be added with the correct value

## Steps to reproduce the issue
![issue](https://user-images.githubusercontent.com/25608846/62291013-6e81a000-b46b-11e9-8d3b-37ba6b683de8.gif)

## Repository
https://github.com/DivanteLtd/vue-storefront

## Can you handle fixing this bug by yourself?
- NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: chrome
- OS: ubuntu 18.04
- Node: 10+
- Code Version: current

**Comment by pkarw** [comment]
It’s been fixed with 1.10 - please recheck

**Comment by EliotRaven** [comment]
@pkarw demo.vuestorefront.io 
this site still has this problem

**Comment by pkarw** [comment]
Sure, the demo is on 1.9.2; https://next.storefrontcloud.io is on 1.10

**Comment by EliotRaven** [comment]
@pkarw 
![issue2](https://user-images.githubusercontent.com/25608846/62299910-8b739e80-b47e-11e9-8802-a98872ca749b.gif)

**Comment by pkarw** [comment]
The debounce has been added to 1.11 (develop branch) - this behavior you showed on the screenshot is a correct one (quite a lot of requests but in the end they're queued so the totals are OK with the cart state) + the Add To Button (showed on the initial screen is being disabled until product land in the cart to prevent race conditions)
