### ISSUE TITLE
Not all content is rendered after redirecting from /my-account endpoint.

### ISSUE THREAD

**Issue by jakubmakielkowski** [DivanteLtd/vue-storefront#3325]
## Current behavior
When user is not logged in and tries access `/my-account` page, application refreshes itself with an error:
`vue.runtime.esm.js:1878 TypeError: Cannot read property 'image' of null`
After redirecting to home page not all components are rendered properly, there are no products in **Everything New** section in VueStorefront demo. Refershing the page solves the problem.

## Expected behavior
After redirecting all content should be rendered properly.

## Steps to reproduce the issue
1. Open https://demo.vuestorefront.io/ 
2. Go to https://demo.vuestorefront.io/my-account (when not logged in)
3. There are no products in Everything New collection.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Latest Chrome and Firefox
- OS: Ubuntu 18

**Comment by pkarw** [comment]
@przspa can you check this issue please?

**Comment by przspa** [comment]
@pkarw yes

**Comment by przspa** [comment]
@pkarw @patzick problem exists when we start app from "/my-account", ssr try to render MyAccount and client render Home when you logged out. 

We have two ways:
1.  moved requiresAuth from https://github.com/DivanteLtd/vue-storefront/blob/develop/core/modules/user/router/beforeEach.ts to https://github.com/DivanteLtd/vue-storefront/blob/develop/core/pages/MyAccount.js
2. add no-ssr for MyAccount pages

What did you think about that?

**Comment by pkarw** [comment]
Maybe we should have the server side redirect to home page exactly the same as we do have in checkout?

From these two options the second is probably better but I’m not sure how it will work? NoSSR means in the server markup there will be just well ... empty placeholder instead of my account so what will be the clients side behavior when I start the page from my-account url?

**Comment by przspa** [comment]
@pkarw I can resolve this issue after wednesday.  SSR redirect isn't good idea because user see only home page and can be confused why, but I will check all option for fix it and propose resolve.

**Comment by pkarw** [comment]
Perfect! Thanks
