### ISSUE TITLE
wrong flexbox grid class override

### ISSUE THREAD

**Issue by lsimone** [DivanteLtd/vue-storefront#3329]
## Current behavior

- VSF [redefines](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/css/utilities/_visibility.scss#L6) `hidden-xs` and `hidden-md` [flexbox grid classes](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/css/vendor/_flexboxgrid2.scss#L1192) with an inconsistent threshold (`em` instead of `px`).

- Furthermore, [it redefines](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/css/utilities/_visibility.scss#L14) `hidden-md` as an open interval (just `min-width`) so that it completely changes the meaning of [flexbox grid `hidden-md`](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/css/vendor/_flexboxgrid2.scss#L1203) that is meant as a closed one (it targets just medium screens, not large, nor xlarge)

## Expected behavior
I'd suggest to stick on the adopted flexbox grid, not to override the default behavior and change the name of custom `hidden-xs` and `hidden-md` in `hidden-over-xs` and `hidden-over-md` and to keep `px` as threshold units.

## Repository
https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/css/utilities/_visibility.scss

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

**Comment by pkarw** [comment]
@przspa I let myself to assign this one to you

**Comment by przspa** [comment]
@pkarw I checked this task and I will fix it after wednesday

**Comment by patzick** [comment]
Thanks @manvendra-singh1506 !
