### ISSUE TITLE
`category-next/getCategories` get cached and don't update with related state value

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront#3332]
## Current behavior

If you click through categories the headline and header of the category disappears like:

<img width="1392" alt="Screenshot 2019-08-05 18 28 48" src="https://user-images.githubusercontent.com/6112764/62481666-54212c80-b7b3-11e9-97e1-cdb2999c7672.png">

After some research I found out that it is caused by the `category-next/getCategories` getter used by the `category-next/getCurrentCategory` getter. It works if you load the page server-side but not if you browse between categories.

I found out that it's probably because `getCategories` is being cached. This is [default Vue.js behavior](https://vuex.vuejs.org/guide/getters.html), despite that it should know when related state data (in this case `state.categoriesMap`) is being updated, but it seems not to notice.  

In other getters it works normally, like in `categoriesMap`, if the state changes the getter returns correct data (I tested it with the VueJS-Dev-Tools in Chrome). The only difference in both getters is that `getCategories` uses `Object.values()` – idk, could this cause it?

~~I fixed it with returning a function getter instead of a plain value to prevent this getter to be cached and it started working again.~~ After some further research it turns out to be caused by a mutation caveat of using `Object.assign()` – If I use `Vue.set()` it also works with a "normal", cached property/getter as well.

## Expected behavior

… it should not disappear and show the titles and headlines always ;)

## Steps to reproduce the issue

* start at homepage
* go to a category page like `Women > Tops > Jackets`
* go to another category page like  `Women > Tops > Tees`
* the category headline should disappear and the `category-next/getCategories` and `category-next/getCurrentCategory` getter should be empty

## Repository

develop:latest https://github.com/DivanteLtd/vue-storefront/commit/121e52c9a9914b7b8aa80107ccca78ed52509117

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome
- OS: OSX
- Node: LTS
- Code Version: develop 121e52c9a9914b7b8aa80107ccca78ed52509117 

## Additional information

I already have an open issue #3286 and PR #3295 where I fix a bug of `getCategoryFrom` and made some optimizations to the getters.

I will merge this changes into this bugfix-/feature-branch.

**Comment by cewald** [comment]
I added a [commit](2a7e076216881ee04d1bfdcfb0199861cf037bd5) to the PR #3295.

**Comment by cewald** [comment]
After some further research it turns out to be caused by a mutation caveat of using `Object.assign()` – If I use `Vue.set()` it also works with a "normal", cached property/getter as well.

I've added it to the open PR.

**Comment by patzick** [comment]
@cewald nice catch! my bad, thanks!
Just for sharing knowledge - Object.assign works good, but it needs to be assigned into new object:
```js
state.something = Object.assign(state.something, newSomething) // not reactive

state.something = Object.assign({}, state.something, newSomething) // reactive and works like Vue.set
```
