### ISSUE TITLE
Optimize the `product/setupVariants` action

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3336]
## What is the motivation for adding / enhancing this feature?

After changes we did to the format of `product.configurable_options` I belive we don't need to call [`loadConfigurableAttributes`](https://github.com/DivanteLtd/vue-storefront/blob/4bf1a7e8d04742c72bd94912ad02cac4618941bb/core/modules/catalog/store/product/actions.ts#L247) anymore. This action sometimes - if attributes are not cached - involves a network call to get the definitions

It's not required as the attribute labels and other data is already stored within `configurable_options`  themselves: [`ov.label`](https://github.com/DivanteLtd/vue-storefront/blob/4bf1a7e8d04742c72bd94912ad02cac4618941bb/core/modules/catalog/store/product/actions.ts#L252)

## What are the acceptance criteria 

- [ ] no `product/loadConfigurableAttributes` action called (

**Comment by Valentin-Seehausen** [comment]
Also the action mutates state directly. This is problematic, because it is intransparent and difficult to detect.

My suggestion would be to only use mutations to mutate the state.

+1
