### ISSUE TITLE
Refactor the minor-vuex-stores to the proper conventions

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3337]
## What is the motivation for adding / enhancing this feature?

We're just a step from having all the vuex stores refactored to keep up with our coding standards :) Well, in a away (product vuex store still needs some love but the minimal refactoring has been already done)

## What are the acceptance criteria 

The following stores got refactored (the list is keeping the priorities - starting with the highest):
- [x] attribute,
- [x] order,
- [x] tax,
- [x] user,
- [x] stock,
- [x] checkout,
- [x] payment,
- [x] compare,
- [x] newsletter,
- [x] reviews,
- [x] wishlist,
- [x] cms.

Only the `cms` is kind of bigger one. It could be done at the very end.

Each should be covered with the following changes:
- [ ] getters refactored
- [ ] data resolvers extracted
- [ ] async/await instead of promises
- [ ] helpers extracted
- [ ] no direct state changes (only mutations)
- [ ] no modfify UI in the vuex action directly

Multiple Pull Requests are welcomed. Some vuex stores refactored even to 1.11 are welcomed.

**Comment by pkarw** [comment]
Reference - `core/modules/cart`, `core/modules/catalog-next`

**Comment by alinadivante** [comment]
I have to reject this issue, because, as I mentioned in PR #3378 I have problem with displaying prices in offline mode.

**Comment by pkarw** [comment]
@alinadivante are you using the newest API (test.storefrontcloud.io/api or local copy)?

**Comment by alinadivante** [comment]
@pkarw You are right. Today I changed endpoints in my config and I used demo.storefrontcloud.io
Using test.storefrontcloud.io/api endpoints then problem does not occur.
