### ISSUE TITLE
Problem with placing an order in offline mode

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3346]
## Current behavior
Currently, there is no possibility to place an order on https://next.storefrontcloud.io/ in **offline mode**
Pressing the "Place order" button does nothing.
![offline](https://user-images.githubusercontent.com/36628922/62779410-710b7780-bab3-11e9-90ae-83f85a09c4de.gif)

## Expected behavior
User should be redirected to Confirmation page and there should be information
"You are offline
You will receive Push notification after coming back online. You can confirm the order by clicking on it". 

## Steps to reproduce the issue
1. Open https://next.storefrontcloud.io
2. Switch offline mode
3. Open any product on Home page and add it to the cart
4. Go to checkout
5. Fill in all sections (personal details, shipping, payment, review order)
6. Click 'Place the order'

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
@patzick i belive this is pretty urgent

**Comment by pkarw** [comment]
@alinadivante I've just checked it on localhost (the current `develop`) and can't reproduce it:
https://www.dropbox.com/s/2a89jb4l9k4onkl/Screenshot%202019-09-04%2014.57.29.png?dl=0
