### ISSUE TITLE
Changing category resets porduct query but not SortBy option

### ISSUE THREAD

**Issue by jakubmakielkowski** [DivanteLtd/vue-storefront#3347]
## Current behavior
Choosing sorting and then navigating from one category to another may be misleading. If user follows this behaviour he/she will see choosen (active) SortBy and unsorted products.

## Expected behavior
Navigating to another category resets SortBy select option or (I think less reasonable) sorting query is not resetted after category change.

## Steps to reproduce the issue
1. Go to any category
2. Choose any sort option
3. Go to any other category by clicking Sidebarmenu category
4. SortBy option is still selected when products are not sorted

## Repository
https://demo.vuestorefront.io/

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO (I am not sure if my solution will be appropriate)

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome
- OS: linux, Ubuntu 18

## Additional information
Not sure, but could be resolved by listening to change category event and listening to that event in CategorySort.ts to update current option.

**Comment by pkarw** [comment]
Hi! There was huge refactoring effort made into 1.11 (develop branch) - can you please test out if this issue still exists in develop?

**Comment by alinadivante** [comment]
Bug does not exist in v1.11.0-rc.1 :)
