### ISSUE TITLE
After logging out wishlist is cleared.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3348]
## Current behavior
After logging out wishlist is cleared, but Compare list is still available and the added products are still visible.

![image](https://user-images.githubusercontent.com/36628922/62781724-e463b800-bab8-11e9-96e9-1ba18ff08260.png)

## Expected behavior
Compare list should be not visible after logging out.

## Steps to reproduce the issue
1. Log in 
2. Add any products to wishlist and compare list
3. Log out
4. Check both lists

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by patzick** [comment]
Done :)
