### ISSUE TITLE
error paypal

### ISSUE THREAD

**Issue by wubuyun** [DivanteLtd/vue-storefront#3357]
![2019-08-12 01-22-41屏幕截图](https://user-images.githubusercontent.com/35350235/62845643-213dd380-bca0-11e9-8619-a81cfc0879f3.png)
![2019-08-12 01-23-15屏幕截图](https://user-images.githubusercontent.com/35350235/62845644-21d66a00-bca0-11e9-9f70-104575253302.png)
![2019-08-12 01-23-49屏幕截图](https://user-images.githubusercontent.com/35350235/62845645-21d66a00-bca0-11e9-86a1-e5c3a717f14d.png)

**Comment by filrak** [comment]
@wubuyun please make an issue from the issue template. Otherwise, we can't help you without all the required information.
