### ISSUE TITLE
Wrong URLs for "de" and "it" stores.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3359]
## Current behavior
Currently, we have wrong URLs for "de"/"it" stores.
Please, see how the links look like on the example `/de`:

1. Link from sidemenu (and no products found):
![image](https://user-images.githubusercontent.com/47415585/62866074-4bc77500-bd10-11e9-9b0d-526d246a76f7.png)
2. Link from banner on homepage (user is redirected to /page-not-found):
![image2](https://user-images.githubusercontent.com/47415585/62866075-4bc77500-bd10-11e9-9e2e-8d32f0c7bbf0.png)
3. Link from breadcrumbs (user is redirected to /page-not-found):
![image3](https://user-images.githubusercontent.com/47415585/62866076-4bc77500-bd10-11e9-8b8f-9a9a218b0c2a.png)

## Expected behavior
For "de" store it should be → `/de/women/women-20`,
for "it" → `/it/women/women-20`

## Steps to reproduce the issue
1. Press one of banners on homepage
2. Open Sidemenu and choose for example Frauen category
3. Open any product ang press on any level from breadcrumbs

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
@lukeromanowicz can you Please take a look at this one?

**Comment by pkarw** [comment]
@alinadivante thanks for reporting! Is this issue only occurring on develop branch? can you please check 1.10 as well please?

**Comment by alinadivante** [comment]
Yes, I checked v1.10 at next.storefront and there is no problem there

**Comment by pkarw** [comment]
OK, @lukeromanowicz  so I belive it might be related to the last fixes in the `multistore.ts`

**Comment by pkarw** [comment]
@lukeromanowicz can you please check it out? I've co-assigned @patzick here as well in case you won't find time for it

**Comment by cewald** [comment]
It seems to be caused by `vue-storefront/core/modules/url/helpers/index.ts` – but only in multistore mode.

The variable `fullPath` is then regardless concatenated to itself.

I solved it by using the `removeStoreCodeFromRoute` method like:
```javascript
import { removeStoreCodeFromRoute } from '@vue-storefront/core/lib/multistore'
…

export function processDynamicRoute (routeData: LocalizedRoute, fullPath: string, addToRoutes: boolean = true): LocalizedRoute[] {
  fullPath = removeStoreCodeFromRoute(fullPath) as string
...
}
```

**Comment by alinadivante** [comment]
@pkarw everything looks all right, but I noticed that for **/de** store there is a typo in the URL after clicking `Der Frühling kommt`  banner from the Home page. Pleas fix it.

**Comment by pkarw** [comment]
Hi @alinadivante thanks for checking this out. Where's the type in the;

```
      "title": "Der Frühling kommt",
      "subtitle": "Hüte",
      "image": "/assets/ban3.jpg",
      "link": "/gear/gert-3"
    }
  ],
  "productBanners": [
	  {
	    "title": "Der Frühling kommt",
	    "subtitle": "Hüte",
	    "image": "/assets/ban3.jpg",
	    "link": "/gear/gert-3"
	  }
```

I can't see it :/

**Comment by alinadivante** [comment]
/de/gear/gerat-3  :)
fixed 👍
