### ISSUE TITLE
Add the i18n support for modules

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3369]
## What is the motivation for adding / enhancing this feature?

<img width="161" alt="Bildschirmfoto 2019-08-15 um 15 44 43" src="https://user-images.githubusercontent.com/211899/63101205-d3afb800-bf78-11e9-8875-c6cac355a36e.png">

**Chris (MDM):**

Hey, im working on an module and want to add my own i18n file for translation only in the module. Is it possible and how?
I add this structure directly in my /modules/module_name/ folder
But how can i include this files?

**pkarw**:
Hey Chris, we never did sth like this before :slightly_smiling_face: Currently i18n can be added only on the core or theme levels :disappointed:

you can still use the i18n helpers of course.

This sounds like a good PR to the core  - please take a look at this file: https://github.com/DivanteLtd/vue-storefront/blob/595c284a56f798f625a8d3ea69edbd7c244f4ae9/core/build/webpack.base.config.ts#L29

## What are the acceptance criteria 

- [ ] module can add their own translations / i18n

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by dz3n** [comment]
I will take this
