### ISSUE TITLE
`dynamicConfigReload` should use deep copy for `Object.assign()`

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront#3372]
# Summary
[summary]: #summary

If I use `dynamicConfigReload` to extend existing and nested config values (like in `config.storeViews`) the current `config = Object.assign(config, loadedConfig)` method will overwrite all nested values with the new array. It would be better to use the [deep-copy util](https://github.com/lorenwest/node-config/wiki/Using-Config-Utilities#extenddeepmergeinto-mergefrom-depth) of [node-config](https://github.com/lorenwest/node-config) in [`vue-storefront/core/scripts/server.js:215`](https://github.com/DivanteLtd/vue-storefront/blob/develop/core/scripts/server.js#L215) to prevent this and make it more powerful.

# Motivation
[motivation]: #motivation

In my case I added kind of a new level of [config file order](https://github.com/lorenwest/node-config/wiki/Configuration-Files#file-load-order) like `local-{deployment}-{instance}-storeview-de.EXT` to exclude store-view specific configs like Facebook-Id for each store view into a own JSON file. This is necessary in our case to make the config files more readable in the future when more and more values on store-view base will appear. 

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation

I just replaced the line in [`vue-storefront/core/scripts/server.js:215`](https://github.com/DivanteLtd/vue-storefront/blob/develop/core/scripts/server.js#L215) like and it instantly worked without problems:
```javascript
config = config.util.extendDeep(config, loadedConfig)
```

# My custom `configProvider`

Just to explain my usecase a bit more: this is my `configProvider` in `src/server/index.js`:
```javascript
module.exports.configProvider = (req) => {
  const fs = require('fs')
  const path = require('path')

  let storeViews = {}

  const configPath = path.resolve(__dirname, '../../config')
  const { NODE_APP_INSTANCE: man } = process.env

  const regex = new RegExp('local-(' + man + ')-storeview-(\\w*)\\.json', 'i')

  return new Promise((resolve, reject) => {
    try {
      fs.readdirSync(configPath).forEach(file => {
        if (regex.test(file)) {
          const [fileName, mandant, storeCode] = regex.exec(file)
          storeViews[storeCode] = require(path.resolve(configPath, fileName))
        }
      })

      resolve({ storeViews })
    } catch (error) {
      reject(error)
    }
  })
}
```

**Comment by cewald** [comment]
I opened a PR with my proposal: https://github.com/DivanteLtd/vue-storefront/pull/3373

**Comment by pkarw** [comment]
Hi Christian! Thanks, interesting case and thanks for the time spent on explaining it; you’ve convicted me :)
