### ISSUE TITLE
Unable to download the requested image - 400

### ISSUE THREAD

**Issue by omercan** [DivanteLtd/vue-storefront#3379]
# Is there something you don't understand? What is it? Describe it.	

Hello, I'm having trouble to display product images on VSF. My first products image can be seen but after second migration image requests failed:

`{
code: 400,
result: "Unable to download the requested image http://localhost:8888/magento/pub/media/catalog/product/1/0/10501-02734-os_01.jpg.sthumbnails.1000.1250-600x750.jpg"
}`

When I go to http://localhost:8888/magento/pub/media/catalog/product/1/0/10501-02734-os_01.jpg.sthumbnails.1000.1250-600x750.jpg link, I can see the picture of the product.

## Additional information
Here is my api config files:

`"magento2": {
    "imgUrl": "http://localhost:8888/magento/pub/media/catalog/product",
    "assetPath": "/../var/magento2-sample-data/pub/media",
...
  },

also see 
`      "allowedHosts": [
        ".*divante.pl",
        ".*vuestorefront.io",
        "localhost",
        "localhost:8080"
      ]
    },`

`

![Screen Shot 2019-08-19 at 12 38 39](https://user-images.githubusercontent.com/3155992/63256629-a0bf3a00-c280-11e9-94cd-0d010aab937a.png)
![Screen Shot 2019-08-19 at 12 38 44](https://user-images.githubusercontent.com/3155992/63256630-a0bf3a00-c280-11e9-91fc-fa439dc2e681.png)
![Screen Shot 2019-08-19 at 12 38 56](https://user-images.githubusercontent.com/3155992/63256631-a0bf3a00-c280-11e9-87b9-d2519e7fdb8b.png)
![Screen Shot 2019-08-19 at 12 39 22](https://user-images.githubusercontent.com/3155992/63256632-a157d080-c280-11e9-82d0-3e504da84764.png)

**Comment by pkarw** [comment]
If you're using docker to run all the containers make sure your `vue-storefront-api` container has the access to `localhost:8888` - I mean if the network is bridged otherwise it's trying to get the image from API cotnainer - 8888 port where it's probably not available

**Comment by omercan** [comment]
@pkarw thank you but I'm sure it's like that.

**Comment by pkarw** [comment]
It’s very hard for us to help you in this particular case; it’s seemingly not an VS core issue

**Comment by pkarw** [comment]
Maybe please add some debugging code like trying to retrieve the url and save it locally (I mean modifying the img.js endpoint) there must be some reason for api not being able to download the file

**Comment by Roywcm** [comment]
I have exactly the same problem. Looks like docker is restricting access to my localhost. I know it's not VSF related, but how to give docker access? 

> If you're using docker to run all the containers make sure your `vue-storefront-api` container has the access to `localhost:8888` - I mean if the network is bridged otherwise it's trying to get the image from API cotnainer - 8888 port where it's probably not available

**Comment by Roywcm** [comment]
Allright, figured it out sooner as expected. I added extra_hosts to my docker-compose.nodejs.yml

**Comment by Danielvandervelden** [comment]
Hi @Roywcm, could you explain exactly how you fixed this issue using extra_hosts? I'm running into the same issue but can't seem to figure it out..

**Comment by Roywcm** [comment]
I've added something like this: hostname with ip
```
extra_hosts:
      - "localhostname.test:xxx.xxx.xxx.xxx"
```
