### ISSUE TITLE
Add AJAX loader to Login and Register screens

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#338]
Particulary the registration process can take a while, would be great to have a loader for this operation i belive

**Comment by filrak** [comment]
http://tobiasahlin.com/spinkit/ second one looks good ;) 

The task includes creating global loader object with props that allows to show/hide him

**Comment by pkarw** [comment]
Approved :)

**Comment by karolbzik** [comment]
Won't it be a problem to add a progress bar, in the top of the page?
![homepage with sample data with loading bar](https://user-images.githubusercontent.com/18116406/33551621-40b0e5d8-d8f2-11e7-86ac-ff335d163a36.png)
In the design I used #333 color and 2px height.

**Comment by pkarw** [comment]
@collymore how does the progress look like here?

**Comment by BlitZ-UK** [comment]
#410

**Comment by pkarw** [comment]
Closed with #410 and #412
