### ISSUE TITLE
Invalid Discount code handling error

### ISSUE THREAD

**Issue by grimasod** [DivanteLtd/vue-storefront#3385]
## Current behavior

An invalid Discount code results in an error notification emitted from the task handler, with the error message coming from the API / Backend. The error is not returned to the calling function, so there is not opportunity to handle it in the theme. The default theme has code for handling this situation, but it never runs.

## Expected behavior

This should be handled by the theme, as it was before v1.10. The theme can display a user-friendly "warning" type notification. The warning text is already included in the language files.

## Steps to reproduce the issue

- Go to https://demo.storefrontcloud.io/
- Add an item to the cart, if empty
- Click on the Microcart icon to open the Microcart sidebar
- Click on "Add a discount code"
- Enter any invalid code, e.g. "1", and click on "Apply"
- A red error notification appears, saying "Coupon code is not valid", which is not included in the language files

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version: v1.10

**Comment by patzick** [comment]
QA - this should be tested on hotfix/v1.10.1 branch, or next, when its deployed. Steps to reproduce above.

**Comment by alinadivante** [comment]
Ok, have  `You've entered an incorrect coupon code. Please try again.` message on hotfix/v1.10.1 branch
