### ISSUE TITLE
Add product related hooks

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3387]
## What is the motivation for adding/enhancing this feature?

It would be great to add an elegant set of hooks related to the products to make the 3rd party integrations (like hotjar, GTM, analytics) easier.

Take a look at how guys are [doing GTM integration right now](https://github.com/DivanteLtd/vue-storefront/blob/master/src/modules/google-tag-manager/hooks/afterRegistration.ts). It requires you to dig really deeply into src code to make sure which mutations are doing what etc.

Can we add the following hooks to the core:
- product page before/after displayed (that allows the user to modify the product),
- category page before/after displayed - the category should be passed as a parameter + potentially the list of products,
- the order has been placed,
- the order is about to be placed (mutator letting the user mutate the order),

**Comment by pkarw** [comment]
Related: #3205

**Comment by pkarw** [comment]
Related: #3217

**Comment by pkarw** [comment]
@filrak if you won't find a time to implement this feature then @andrzejewsky please take care of it - we've got a deadline set for 19 th of September (the release date of 1.11-rc1)

**Comment by filrak** [comment]
The order-related ones are already implemented

**Comment by filrak** [comment]
Also what would be a use case to modify the product? Can't we do this just by modifying the searchQuery?
