### ISSUE TITLE
Add general purpose hooks

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3389]
## What is the motivation for adding / enhancing this feature?

- `afterAppInit: listener` - after modules and theme are registered
- `beforeStoreViewChange(storeView): mutator `- you can access/modify storeView object before changing
- `afterStoreViewChange(storeView): mutator`- you can access storeView object after changing storeView
- `beforePlaceOrder(order): mutator` - you can access/modify order object before sending order to backend
- `afterPlaceOrder(order, task): listener` - you can access order/task (order placement status) object after sending to backend 
- `beforeHydated(initialState):mutator` - caleld before `replaceState` and before `$mount`
- `onAfterProductThumbnailPathGenerated(path, sizex, sizey): mutator` - for integrating 3rd party services like Cloudinary,
- `onBeforeTaxesCalculated(productList)` - for integrating the 3rd party services like https://www.taxjar.com/ - it must work on kind of async/await Promises then

**Comment by pkarw** [comment]
Please mark @kkdg in PR; Degi please create a special page in the docs maybe just for hooks to have them all well listed? It will make a module development a way easier to have this reference in one oplace

**Comment by kkdg** [comment]
@pkarw Sure thing, noted, and module cookbook already has a single recipe dedicated to hooks. Let me arrange them and lay them out as efficient as possible once they are ready.
