### ISSUE TITLE
'Close' icon in the login popup is located in the wrong place.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3393]
## Current behavior
'Close' icon in the login popup is located in the upper **left** corner.

![image (1)](https://user-images.githubusercontent.com/47415585/63346488-607dbb80-c355-11e9-8e23-5b916760e6c3.png)

## Expected behavior
'Close' icon should be located in the upper **right** corner.

## Steps to reproduce the issue
1. Go to https://test.storefrontcloud.io
2. Press My account icon

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by filrak** [comment]
wasn't @andrzejewsky fixing this?

**Comment by andrzejewsky** [comment]
no 😄, but it looks so simple, I can do fix it in my other tasks as additional thing

**Comment by alinadivante** [comment]
@przspa just like we talked, please move `X` to the line
