### ISSUE TITLE
Add product listing with horizontal filters

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#34]
Add product listing with horizontal filters.
The view should use the same filters like on the already developed product listing with vertical filters: color, size, price.

The design of the view:
<img width="1440" alt="products listing with horizontal filters" src="https://user-images.githubusercontent.com/18116406/31162442-ca4e5ba8-a8dd-11e7-9f9a-ceb66997b45e.png">

**Comment by Aekal** [comment]
Is this issue still up-to-date? Do we need this view?

**Comment by pkarw** [comment]
I think it's not relevant anymore. Closing
