### ISSUE TITLE
Unnecessary check for `cartItem.quoteId` in _serverDeleteItem method

### ISSUE THREAD

**Issue by AshishSuhane** [DivanteLtd/vue-storefront#3415]
## Current behavior

There is a check for `cartItem.quoteId` in _serverDeleteItem method on `core/modules/cart/store/action.ts` file.
````
if (!cartItem.quoteId) {
    cartItem = Object.assign(cartItem, { quoteId: cartServerToken })
  }
  cartItem = Object.assign(cartItem, { quoteId: cartServerToken })
````

Here `if condition` is not making any sense as we are initializing it on both conditions i.e if  `quoteId` is empty we are initializing it with cartServerToken, and if it is there then also we are overriding it with the same value. If we remove that if condition then also it will show the same behavior    

## Expected behavior

There shouldn't be an` if` check as we are initializing it either way 

## Steps to reproduce the issue

- Open `core/modules/cart/store/action.ts` file.
- Navigate to _serverDeleteItem function (line: 92)

## Repository

https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/cart/store/actions.ts

## Can you handle fixing this bug by yourself?
[ ] yes

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

[ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case, Developer should create a branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  all
- OS: all
- Node: all
- Code Version:  1.9.0 ,1.10.0 and vs2.0

**Comment by pkarw** [comment]
Yeah, thanks for pointing this out :)

**Comment by patzick** [comment]
Thanks! :)
