### ISSUE TITLE
currentStoreView is bugged inside URL Mapping extend function

### ISSUE THREAD

**Issue by Fifciu** [DivanteLtd/vue-storefront#3418]
## Current behavior
Inside the URL Mapping function `currentStoreView` returns bad store code. I am on /eu/ storeView and it says I am on default one "/". What's interesting, `removeStoreCodeFromRoute` function works properly.

In 1.9 version `currentStoreView` worked properly in that place.

## Expected behavior
`currentStoreView` works properly in URL Mapping extend function in 1.10 as it worked in 1.9.

## Steps to reproduce the issue
1. Install VSF Pwa
2. Configure multistore
2. Go to src/modules
3. ```git clone git@github.com:kodbruket/vsf-mapping-fallback.git```
4. Apply URL mapping based on `vsf-mapping-fallback` repo tutorial.
5. Try to use currentStoreView function inside extending function.

Personally, I use this function there because I am adding an custom prefix based on storeView for products.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome 75
- OS: Ubuntu 16.04
- Node: 10.15.3
- Code Version: 1.10

**Comment by pkarw** [comment]
@lukeromanowicz can you take a look at this one please?

**Comment by pkarw** [comment]
Filip please just check if this is not related to https://github.com/DivanteLtd/vue-storefront/commit/4cbdc4179d95360cb5b613d3a12ddcbaf633bbe6#diff-53eb0dcbb2c62c8af0204c3f9aaf84fc and [further changes](https://github.com/DivanteLtd/vue-storefront/blob/master/core/lib/multistore.ts) that might require you to do some config changes in the config.storeViews section

**Comment by pkarw** [comment]
@lukeromanowicz if this is an unexpected behavior caused by this new feature implements it means we need a upgrade notes or some backward compatible defaults badly :-)

**Comment by ResuBaka** [comment]
I can test this tomorrow too. 

It would be create to have the storeViews config your are using.

And an other thing could be that you could try your config in the Unit test to check if they would work with your config? @Fifciu 

Link to the tests [master](https://github.com/DivanteLtd/vue-storefront/blob/master/core/lib/test/unit/multistore.spec.ts).

**Comment by Fifciu** [comment]
> Filip please just check if this is not related to [4cbdc41#diff-53eb0dcbb2c62c8af0204c3f9aaf84fc](https://github.com/DivanteLtd/vue-storefront/commit/4cbdc4179d95360cb5b613d3a12ddcbaf633bbe6#diff-53eb0dcbb2c62c8af0204c3f9aaf84fc) and [further changes](https://github.com/DivanteLtd/vue-storefront/blob/master/core/lib/multistore.ts) that might require you to do some config changes in the config.storeViews section

I have set `appendStoreCode` to true in each storeview.
What's interesting, `storeCodeFromRoute` and `removeStoreCodeFromRoute` works properly. Only `currentStoreView` is bugged.

### Example console logs
```
Base URL: eu/men-socks/knee-high
- storeCodeFromRoute returns "eu"
- removeStoreCodeFromRoute returns "men-socks/knee-high"
- currentStoreView returns { tax:
   { defaultCountry: 'US',
     defaultRegion: '',
     sourcePriceIncludesTax: false,
     calculateServerSide: true },
  i18n:
   { defaultCountry: 'US',
     defaultLanguage: 'EN',
     availableLocale:
      [ 'en-US',
        'de-DE',
        'fr-FR',
        'es-ES',
        'nl-NL',
        'jp-JP',
        'ru-RU',
        'it-IT',
        'pt-BR',
        'pl-PL',
        'cs-CZ' ],
     defaultLocale: 'en-US',
     currencyCode: 'USD',
     currencySign: '$',
     currencySignPlacement: 'preppend',
     dateFormat: 'HH:mm D/M/YYYY',
     fullCountryName: 'United States',
     fullLanguageName: 'English',
     bundleAllStoreviewLanguages: true },
  elasticsearch:
   { httpAuth: '',
     host: 'HIDDEN',
     index: 'HIDDEN',
     min_score: 0.02,
     csrTimeout: 5000,
     ssrTimeout: 1000,
     queryMethod: 'GET',
     disableLocalStorageQueriesCache: true,
     searchScoring:
      { attributes: [Object],
        fuzziness: 2,
        cutoff_frequency: 0.01,
        max_expansions: 3,
        minimum_should_match: '75%',
        prefix_length: 2,
        boost_mode: 'multiply',
        score_mode: 'multiply',
        max_boost: 100,
        function_min_score: 1 },
     searchableAttributes: { name: [Object], sku: [Object], 'category.name': [Object] } },
  storeCode: '',
  storeId: 1 }
```

### Part of my multistore config - with hidden URIs
```
"storeViews": {
    "multistore": true,
    "commonCache": true,
    "mapStoreUrlsFor": ["us", "mx", "eu"],
    "us": {
      "storeCode": "us",
      "disabled": false,
      "storeId": 1,
      "name": "United States Store",
      "url": "/us",
      "appendStoreCode": true,
      "productsPrefix": "special-prefix-for-products-from-usa-custom-url",
      "elasticsearch": {
        "host": "HIDDEN",
        "index": "HIDDEN"
      },
      "tax": {
        "sourcePriceIncludesTax": true,
        "defaultCountry": "USA",
        "defaultRegion": "",
        "calculateServerSide": true
      },
      "i18n": {
        "fullCountryName": "United States of America",
        "fullLanguageName": "English",
        "defaultLanguage": "EN",
        "defaultCountry": "USA",
        "defaultLocale": "en-US",
        "currencyCode": "USD",
        "currencySign": "$ ",
        "dateFormat": "HH:mm D-M-YYYY"
      }
    },
    "mx": {
      "storeCode": "mx",
      "disabled": false,
      "storeId": 2,
      "name": "Mexican Store",
      "url": "/mx",
      "appendStoreCode": true,
      "productsPrefix": "special-prefix-for-products-from-mexico-custom-url",
      "elasticsearch": {
        "host": "HIDDEN",
        "index": "HIDDEN"
      },
      "tax": {
        "sourcePriceIncludesTax": true,
        "defaultCountry": "MX",
        "defaultRegion": "",
        "calculateServerSide": true
      },
      "i18n": {
        "fullCountryName": "Mexico",
        "fullLanguageName": "Spanish",
        "defaultLanguage": "ES",
        "defaultCountry": "MX",
        "defaultLocale": "es-ES",
        "currencyCode": "MXN",
        "currencySign": "$ ",
        "dateFormat": "HH:mm D-M-YYYY"
      }
    },
   "eu": {
      "storeCode": "eu",
      "disabled": false,
      "storeId": 3,
      "name": "Europe Store",
      "url": "/eu",
      "appendStoreCode": true,
      "productsPrefix": "other-super-prefix",Above, I put only 2 
      "elasticsearch": {
        "host": "HIDDEN",
        "index": "HIDDEN"
      },
      "tax": {
        "sourcePriceIncludesTax": true,
        "defaultCountry": "EU",
        "defaultRegion": "",
        "calculateServerSide": true
      },
      "i18n": {
        "fullCountryName": "Europe",
        "fullLanguageName": "English",
        "defaultLanguage": "EN",
        "defaultCountry": "EU",
        "defaultLocale": "en-US",
        "currencyCode": "EUR",
        "currencySign": "€ ",
        "dateFormat": "HH:mm D-M-YYYY"
      }
    }
}
```

**Comment by ResuBaka** [comment]
My local config which I have used to test this https://pastebin.com/raw/G4pUk12m.

The change I have made to have working products https://www.diffchecker.com/kxtB3fUa.
This change is probably only needed because you have the product slug in the url_path in elasticsearch.  

I have tested this in the eu storeView and there the eu prefix was on product URLs and category URLs.

Can you try your config against https://demo.storefrontcloud.io/. You only need to change ES host and index to what I have used and maybe my code change for products.

But maybe @lukeromanowicz can reproduce your problem so we can fix it.

**Comment by ResuBaka** [comment]
One thing that I now see it the `productsPrefix` where and how are you using that. Maybe the problem has something to do with that? 
@Fifciu

**Comment by Fifciu** [comment]
> My local config which I have used to test this https://pastebin.com/raw/G4pUk12m.
> 
> The change I have made to have working products https://www.diffchecker.com/kxtB3fUa.
> This change is probably only needed because you have the product slug in the url_path in elasticsearch.
> 
> I have tested this in the eu storeView and there the eu prefix was on product URLs and category URLs.
> 
> Can you try your config against https://demo.storefrontcloud.io/. You only need to change ES host and index to what I have used and maybe my code change for products.
> 
> But maybe @lukeromanowicz can reproduce your problem so we can fix it.

So `currentStoreView` works properly for you inside forProduct and forCategory?



> One thing that I now see it the `productsPrefix` where and how are you using that. Maybe the problem has something to do with that?
> @Fifciu

It is custom parameter. There I define custom prefix which is appended for each product based on storeView. Source of the problem was - I couldn't identify storeCode with currentStoreView as I did in 1.9. I think it isn't problematic. I added custom parameters to config many times in different places.

**Comment by ResuBaka** [comment]
For it me it works like it should. I have no problem with storeCodes. 

All product URLs and category URLs are working fine.

**Comment by pkarw** [comment]
@Fifciu @ResuBaka im not sure if I can close this issue?

**Comment by ResuBaka** [comment]
I had no problem with URLs when I have tested so for me there is no error. 

I could only think that the problem comes from some custom code they have added because 1.10 has worked for like it should have.

**Comment by Fifciu** [comment]
Okay, we can close it
