### ISSUE TITLE
Cleaning the mess and setting project rules - Refactoring / Optimization / Documentation

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#343]
1 DOCS:

- [ ] 1 Create pull request checklist
- [ ] 2 Create styleguide and rules for JS code
- [ ] 3 Create styleguide and rules for HTML code
- [ ] 4 Create "Working with components" docs  with components list
- [ ] 5 Create "Working with filters" docs
- [ ] 6 Create "Working with stores" docs 
- [ ] 7 Create "Contribution rules" docs 
- [ ] 8 Create 'Contributor's starter" docs with basic information about project architecture and where to find what you want
- [ ] 9 Add component props example data to documentation

2 CODE:
- [ ] 1 Decide which components should be in core and which whould be only in theme (in other words which components aren't connected to defaul ttheme or fashion industry)
- [ ] 2 Refactor css mess written by other people to follow [CSS project rules](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Working%20with%20stylesheets%20(CSS).md
)
- [ ] 3 Move active theme name to config file and add webpack aliases based on this config
- [ ] 4 Split repeatable code to reusable components
- [ ] 5 Move data processing scripts to services and filters
- [ ] 6 Refactor HTML & js code to follow the contribution rules
- [x] 7 Change event-bus.js to index.js and get rid of `event-bus/event-bus` imports
- [ ] 8 Add component props validation
- [ ] 9 Remove unused data from 'resource/'

**Comment by filrak** [comment]
@kacperknapik @mercs600 1.9, 1.8, 1.2, 1.7, 1.3 can be done now, maybe you guys can help?

**Comment by mercs600** [comment]
@filrak I will take 2.7 right now
