### ISSUE TITLE
HTTP ERROR undefined while browsing sub/category pages.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3435]
## Relates to: 
#3298 

## Current behavior
502 errors in dev console.

In the following configuration, where:
`filterUnavailableVariants` = `true`
`configurableChildrenStockPrefetchStatic` = `false`
`configurableChildrenStockPrefetchDynamic` = `false`

`HTTP ERROR undefined` appears when browsing different pages.

![image](https://user-images.githubusercontent.com/36628922/63766307-2e2b0b80-c8cb-11e9-972d-a1937bacf04d.png)

## Expected behavior
There should be no errors.

## Steps to reproduce the issue
1. Just open vsf with the latest develop branch
2. Go to any category/sub-category page 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
Can't reproduce this on `develop`. My settings:
    "configurableChildrenStockPrefetchStatic": false,
    "configurableChildrenStockPrefetchDynamic": false,
    "configurableChildrenStockPrefetchStaticPrefetchCount": 8,
    "filterUnavailableVariants": true,
