### ISSUE TITLE
Photo of the unavailable variant is displayed.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3436]
## Relates to: 
#3298 

## Current behavior

In the following configuration, where:
`filterUnavailableVariants` = `true`
`configurableChildrenStockPrefetchStatic` = `true`
`configurableChildrenStockPrefetchDynamic` = `true`

when I open a product with an unavailable option directly via the URL - then it's OK → unavailable variant is removed from the list. **BUT** when I open this product (with the unavailable variant) from the Home page or category page, then I see photo of the unavailable variant. 

![image](https://user-images.githubusercontent.com/36628922/63766908-7d257080-c8cc-11e9-9476-38018d8b6219.png)

(after refreshing the page - variant disappears)

## Expected behavior
Out-of-stock variant should not be displayed - in this case picture with unavailable color/size shouldn't be displayed. 
Out-of-stock variants should be removed from the available variants list.

## Steps to reproduce the issue
1. Open vsf with the latest develop branch
2. Click  `Gwyn Endurance Tee` product (black blouse) from `Everything new` section  on Home Page
3. Try to add to cart default variant

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
@patzick please make sure we're supporting this feature in new product page as well: https://github.com/DivanteLtd/vue-storefront/commit/e24e10ea7c1f5e5ca8e757b1210aded7c9aaf8e1
