### ISSUE TITLE
Doubled SKU row in compare tab

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#3437]
## Current behavior
SKU table row is doubled for all products

![doubleSKU](https://user-images.githubusercontent.com/47415585/63782343-8d991380-c8eb-11e9-8754-5937aa63608b.png)

## Expected behavior
SKU row should only be displayed once. 

## Steps to reproduce the issue
1. Open test.storefrontcloud.io
2. Open any category page
3. From category page view, add any product to compare list
4. Open compare window

## Additional information
Appearance of this doubled row is triggered by adding product to compare from category page view. If on fresh instance we add product to compare from PDP, or from "Get inspired" homepage prouducts tiles, bug will not occur. 

However, once bug is triggered, then every time we add another product to compare (now no matter in which way) - SKU row will be doubled - even if we clear wishlist in the meantime.  

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Lastest Chrome
- OS: Ubuntu, Win 10
- Code Version: Develop

**Comment by pkarw** [comment]
@przspa can you please just take a look at this one?

**Comment by patzick** [comment]
thanks @manvendra-singh1506! :)

**Comment by ArturDivante** [comment]
Bug fixed
