### ISSUE TITLE
Translation in data function are broken in SSR 

### ISSUE THREAD

**Issue by ResuBaka** [DivanteLtd/vue-storefront#3445]
## Current behavior
When you have something like below. The rendert links are all in the default language or are not translated that I can't 100% say what happens here of these two cases.   
```javascript
 data () {
    return {
      map: [
        {id: 'halloId', link: this.$t('/hello'), name: 'Hallo'}
     ]
    }
  },
```

This problem does only only happen when your load the page over SSR when you are in CSR it all works like one would expect.

This problem does only happen in production mode. In development mode (yarn dev) it works with SSR and CSR.

## Expected behavior
The translation should be in the language you would expect. In my case they should be in german as I tied it with the german store we have.

## Steps to reproduce the issue
SSR
![image](https://user-images.githubusercontent.com/15260832/63933249-25684000-ca59-11e9-9a1d-a69e88cd6766.png)
CSR
![image](https://user-images.githubusercontent.com/15260832/63933276-31540200-ca59-11e9-9e33-07a2d0e02f42.png)

1. Create a component where you have translation which are in the data object like the code above. 
2. Then implement it somewhere.
3. Run yarn build
4. Run yarn start
5. open the Page where the component is directly and with a `router-link`.

Then you should see the problem.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO I currently have no time to check it myself.

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chromium latest version
- OS: Arch Linux Kernal 5.2.9
- Node: 12.9.0
- Code Version: f2d587bc52af4e0c3f654f2df9c8fdde2ddbbf11 (That is the latest commit we are currently are on)

**Comment by pkarw** [comment]
Hi @ResuBaka. Are you using `serverPrefetch` in these components? I mean when using the SSR the`old way with `asyncData` I’m not sure on when the component tree is being created; it’s possible it’s been created before the translations has been loaded/registered - kind of race condition. This is where I’d start checking this issue at least :P

**Comment by pkarw** [comment]
Changed to `question` as it's not related to the core probably (?) or is it?

**Comment by ResuBaka** [comment]
I think that this can be closed it looks like it is a problem as we use `v-runtime-template` and when I try the same problem on like home.vue it works in the theme. So I am going to close this as it looks like not a problem auf VSF.
