### ISSUE TITLE
" is out of the stock" should be " is out of stock"

### ISSUE THREAD

**Issue by indiebytes** [DivanteLtd/vue-storefront#3451]
## Current behavior

Checkout.vue contains a translated text reading   _is out of the stock_...

## Expected behavior

... but I think it should read _is out of stock_.

## Repository

https://github.com/DivanteLtd/vue-storefront/blob/develop/src/themes/default/pages/Checkout.vue#L66

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [X] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: MacOS Mojave 10.14.6
- Node: 
- Code Version:

**Comment by patzick** [comment]
Thanks:)
