### ISSUE TITLE
Unable to place order

### ISSUE THREAD

**Issue by lukeromanowicz** [DivanteLtd/vue-storefront#3453]
## Current behavior

Clicking place order on latest develop results with an error in console:
```
 config__WEBPACK_IMPORTED_MODULE_1__.entities.uniqueEntityId is not a function
```
The order does not get placed.

![image](https://user-images.githubusercontent.com/46789227/64093897-4337ec80-cd5a-11e9-8d37-8536678cccaa.png)

## Expected behavior

You can place an order by hitting place order button on checkout

## Steps to reproduce the issue

1. add something to cart
2. try to place order

## Repository

Latest develop: b3a61bc6b182af7e0b26ab67b9d4703d1e7492cf

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 73
- OS: Ubuntu 18 LTS
- Node: 10.x 
- Code Version: develop - b3a61bc6b182af7e0b26ab67b9d4703d1e7492cf

**Comment by ArturDivante** [comment]
Problem solved

**Comment by razzul** [comment]
> Problem solved

How you got the solution ? for me its still there I am not able to place order event in cash on delivery 

<div class="text-center p-3">
          <span class="border-wrap"><img src="/razzul/img/blob/master/order-failed.gif?raw=true" alt="order-failed.gif"></span>
      </div>
