### ISSUE TITLE
VSF should be flexible to support id values to be numeric as well as alphanumeric

### ISSUE THREAD

**Issue by adityasharma7** [DivanteLtd/vue-storefront#3456]
## What is the motivation for adding / enhancing this feature?
We have all the id values of product, category, attribute etc defined as numeric type.
https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/catalog/types/Product.ts
https://github.com/DivanteLtd/vue-storefront-api/blob/master/config/elastic.schema.product.json
https://github.com/DivanteLtd/vue-storefront-integration-boilerplate/blob/master/1.%20Expose%20the%20API%20endpoints%20required%20by%20VS/Product%20Attributes.md
https://github.com/DivanteLtd/vue-storefront-integration-boilerplate/blob/master/1.%20Expose%20the%20API%20endpoints%20required%20by%20VS/Required%20API%20specification.md
https://github.com/DivanteLtd/vue-storefront-api/blob/master/config/elastic.schema.attribute.json
It may be possible that the ecommerce ERP, it is integrated with may have support for alphanumeric identifier.
We would like to contribute towards the effort to make it support alphanumeric if community finds it useful.
Slack thread link: https://vuestorefront.slack.com/archives/CA5B80T4M/p1567406131004600

## What are the acceptance criteria 
Enable VSF to support **id** values to accept alphanumeric as well as numeric values. 
- [ ] ...

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
Hey! yeah, it makes sense; in the core, we're never casting these data to `numeric` but rather comparing the values always as strings so it's definitely what we aimed at (to let ppl. use the string ids); Please prepare the PR but also make sure it's still backward compatible

**Comment by adityasharma7** [comment]
Thanks @pkarw for looking into it!
We will definitely ensure the backward compatibility.
