### ISSUE TITLE
Add unit tests for `core/modules/breadcrumbs`

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3457]
## What is the motivation for adding/enhancing this feature?

Add unit tests for the module. Reference/example: 
- https://github.com/DivanteLtd/vue-storefront/tree/develop/core/modules/catalog-next/test/unit
- https://github.com/DivanteLtd/vue-storefront/blob/develop/core/modules/url/test/unit/formatCategoryLink.spec.ts

## What are the acceptance criteria 
- [ ] all the actions should be tested
- [ ] all the helpers should be tested
- [ ] all the mutations should be tested

**Comment by diboy2** [comment]
@pkarw Assign to me.

**Comment by pkarw** [comment]
@diboy2 it’s yours 👍

**Comment by mattheo-geoffray** [comment]
Linked PR: https://github.com/DivanteLtd/vue-storefront/pull/3637
