### ISSUE TITLE
Unexpected null in search input

### ISSUE THREAD

**Issue by vue-kacper** [DivanteLtd/vue-storefront#3474]
## Current behavior
The search input is bound to "null" value in particular edge case.

## Expected behavior
Search input should not be bound to "null" value

## Steps to reproduce the issue

- Visit https://demo.storefrontcloud.io
- Clear site data (Application tab in chrome dev tools)
- Refresh page
- Open search sidebar
- Click on white space to take out focus from the search input
- Close search sidebar
- Open sidebar again

## Release

- https://demo.storefrontcloud.io
- https://test.storefrontcloud.io
- https://next.storefrontcloud.io

## Environment details

- Browser: Latest Google chrome
- OS: Windows 10

## Additional information

![image](https://user-images.githubusercontent.com/42430550/64211758-6cb25e80-cea7-11e9-8b68-405620003438.png)

**Comment by ArturDivante** [comment]
Bug fixed
