### ISSUE TITLE
After changing the store, the products added to the cart are moved.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3478]
## Current behavior
When I add products to the cart as a guest at the US store, and then change the store to (e.g.) DE, the products are automatically transferred. Thus, I can have products available in various stores in my basket and place such an order.

The currency varies depending on the store I am in, e.g. I place an order in euros but the order in dollars goes to the Magento panel.

## Expected behavior
Added products to the cart shouldn' be moved after changing the store, because they may not be available for another store.

## Steps to reproduce the issue
1. Add some products to the cart
2. Change the store
3. Add another products
4. Check your cart 
5. Place an order

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version: 

## Additional information
This issue occurs on **master**.
I tested the same scenario on **develop** but there products aren't transferred for guest. Only for logged in user. 
But what if we add in one store a product available only there (as a logged uset) and then finish the purchasing process in another store?

**Comment by pkarw** [comment]
This issue doesn't exist in `develop` (1.11); the log-in/log-out scenario is safe - it means that you have these products added in Magento (for this specific users' cart); in that case when product doesn't exist it won't be added to your local cart when switching the store

if there is a possibility to login by the same account to multistores there should be also a way to handle this cross-shopping experience I belive and it's more on magento level. we can add a feature to prevent cart sync between carts from different stores but this is more a feature request

**Comment by pkarw** [comment]
ps. I've added products to the cart logged in:
https://www.dropbox.com/s/7c2wiqmv48rqy7x/Screenshot%202019-09-04%2014.30.33.png?dl=0

then i've switched store to DE
https://www.dropbox.com/s/7c2wiqmv48rqy7x/Screenshot%202019-09-04%2014.30.33.png?dl=0

we're syncing the cart with the `storeCode` given so it should be safe: https://www.dropbox.com/s/2pugg4iv9dlvlda/Screenshot%202019-09-04%2014.32.14.png?dl=0

**Comment by pkarw** [comment]
For 1.10.1 please switch `config.storeViews.commonCache` to false in the config
