### ISSUE TITLE
Product image is missing on PDP

### ISSUE THREAD

**Issue by jorkvist** [DivanteLtd/vue-storefront#3483]
## Current behavior
Navigate to product page shows a error message and the product image are loaded. 

## Expected behavior
Product Image should be shown

## Steps to reproduce the issue
Run v1.10.1 and goto a product page with only one product image. 

![image](https://user-images.githubusercontent.com/5425824/64291635-efe7b900-cf68-11e9-8cd1-9abfc22f39bc.png)

Console:
![image](https://user-images.githubusercontent.com/5425824/64291691-173e8600-cf69-11e9-8364-2e70b4471741.png)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome
- Node: v10.16.3
- Code Version: v1.10.1

**Comment by pkarw** [comment]
@przspa please check this issue - it’s high priority

**Comment by przspa** [comment]
@pkarw ok I checking it

**Comment by NavaneethVijay** [comment]
@jorkvist I've found the solution, I am making a pull request for the same

**Comment by przspa** [comment]
@pkarw https://github.com/przspa/vue-storefront/tree/hotfix/%233483v1.10.2 fixed but we should pull it to v.1.10.2 because 1.10.1 was released

**Comment by NavaneethVijay** [comment]
> @przspa please check this issue - it’s high priority

Hi, can you review my PR, the issue is been solved at the earliest.

**Comment by ArturDivante** [comment]
Problem fixed
