### ISSUE TITLE
Core > Unit Tests > Broken Tests because of missing depenancy

### ISSUE THREAD

**Issue by David-Dorr** [DivanteLtd/vue-storefront#3486]
## Current behavior

On running **Yarn test: unit**, 8 Unit Tests fail because of 

> Cannot find module '@vue-storefront/unit-tests/utils'.
> import { mountMixinWithStore } from '@vue-storefront/unit-tests/utils'

## Expected behavior

**Yarn test: unit** should complete all unit tests successfully

## Steps to reproduce the issue

Run **Yarn test: unit**

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  N/A CLI Test
- OS:  Ubuntu 18.04
- Node:  Node v8.10.0
- Code Version:  Develop Branch

## Additional information

Simple Fix. Dependencies have been moved to main repo. I will update the tests concerned to get them back to a working state. This will help progress on the other "Unit Tests" Taskings

**Comment by pkarw** [comment]
Ok cool; please make sure you’re on develop branch and feel free to fix this along with adding up some unit tests :)

**Comment by pkarw** [comment]
@David-Dorr i just wanted to kindly ask about the status?

**Comment by David-Dorr** [comment]
After doing some checking, it appears that with the Docker installation, there are some symlinks missing from the "@vue-storefront" node_module. 

Compare: Install using "Yarn Installer"
`drwxr-xr-x    2 dave dave  4096 сеп  6 11:52 .
drwxr-xr-x 1437 dave dave 49152 сеп  6 11:53 ..
lrwxrwxrwx    1 dave dave    18 сеп  6 11:52 cli -> ../../packages/cli
lrwxrwxrwx    1 dave dave    10 сеп  6 11:52 core -> ../../core
lrwxrwxrwx    1 dave dave    10 сеп  6 11:52 docs -> ../../docs
lrwxrwxrwx    1 dave dave    15 сеп  6 11:52 i18n -> ../../core/i18n
lrwxrwxrwx    1 dave dave    24 сеп  6 11:52 theme-default -> ../../src/themes/default
lrwxrwxrwx    1 dave dave    28 сеп  6 11:52 theme-default-amp -> ../../src/themes/default-amp
lrwxrwxrwx    1 dave dave    15 сеп  6 11:52 unit-tests -> ../../test/unit
`

Manual build with Docker.
`drwxr-xr-x    2 root root  4096 сеп  6 12:58 .
drwxr-xr-x 1246 root root 40960 сеп  6 12:59 ..
lrwxrwxrwx    1 root root    10 сеп  6 12:58 core -> ../../core
lrwxrwxrwx    1 root root    15 сеп  6 12:58 i18n -> ../../core/i18n
lrwxrwxrwx    1 root root    24 сеп  6 12:58 theme-default -> ../../src/themes/default
lrwxrwxrwx    1 root root    28 сеп  6 12:58 theme-default-amp -> ../../src/themes/default-amp
`

**Comment by David-Dorr** [comment]
For now, I will focus the tasks for building unit tests for the modules, as they have a higher priority, and will return to this when opportunity allows.

**Comment by pkarw** [comment]
Cool; thanks

**Comment by Ksardarion** [comment]
@pkarw @David-Dorr 
Is there are any updates?

**Comment by pkarw** [comment]
hmm @Ksardarion it's seemingly fixed from September, isn't it?

**Comment by Ksardarion** [comment]
@pkarw I'm getting a lot of issues like
`● Test suite failed to run

    Cannot find module '@vue-storefront/core/app' from 'blockMutations.spec.ts'

      2 | import blockMutations from '../../store/block/mutations'
      3 | 
    > 4 | jest.mock('@vue-storefront/core/app', () => jest.fn())
        |      ^
      5 | 
      6 | describe('Block mutations', () => {
      7 |   beforeEach(() => {

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (core/modules/cms/test/unit/blockMutations.spec.ts:4:6)
`

**Comment by Ksardarion** [comment]
@pkarw 
![Screenshot from 2020-02-11 13-12-15](https://user-images.githubusercontent.com/12583664/74231842-32f44800-4cd0-11ea-90a0-fbfac0b0166c.png)
That's what I get when doing ls -la @vue-storefront
