### ISSUE TITLE
Multistore -> nested routes names duplicated

### ISSUE THREAD

**Issue by kamileon-div** [DivanteLtd/vue-storefront#3489]
## Current behavior

When create a children route, it duplicates without language prefix.

## Expected behavior

Nested routes names should be prefixed by each language.

## Steps to reproduce the issue

Use multistore and create children route.

## Can you handle fixing this bug by yourself?

- [x ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome
- OS: Windows
- Node: 10
- Code Version: 1.10.1

**Comment by pkarw** [comment]
Hi! Thanks, can you paste example routing config to show the case please?

**Comment by pkarw** [comment]
`setupMultistoreRoutes` from `multistore.ts` is adding the localized routes

**Comment by kamileon-div** [comment]
Of course. Code below:

`{
    name: 'account',
    path: '/my-account',
    component: MyAccount,
    meta: { requiresAuth: true },
    children: [
      {
        name: 'account-settings',
        path: 'settings',
        component: AccountSettings,
        props: { page: 'lorem', title: 'Account settings' },
        meta: { requiresAuth: true }
      }
    ]
  },`

**Comment by pkarw** [comment]
yeah, we forgot about this :) can you please fix it? thanks!

**Comment by pkarw** [comment]
I just wanted to check up the status? The 1.11rc1 is planned for 19th of September

**Comment by AdKamil** [comment]
It seems that the problem is a little bit more complicated. I have to study it more.
