### ISSUE TITLE
Default root category level cannot be 0

### ISSUE THREAD

**Issue by themreza** [DivanteLtd/vue-storefront#3495]
## Current behavior

When using a custom category structure that has the root categories at level 0, the code ignores this, thinking the config is not set and automatically assumes a root level of 2.

This results in categories not showing up in the sidebar menu.

## Expected behavior

VSF should allow for root levels and other similar iterations to begin at 0 rather than 1, or at least mention this in the integration guide or the category vuex store description.

## Steps to reproduce the issue

If you set categoriesDynamicPrefetchLevel in the config (local.json) to 0 it will be overwritten to 2.

## Repository

https://github.com/DivanteLtd/vue-storefront/blob/master/core/compatibility/components/blocks/SidebarMenu/SidebarMenu.js#L14

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  Chrome
- OS:  Ubuntu 18.04
- Node:  8.16.1
- Code Version:  1.10.1

**Comment by pkarw** [comment]
Thanks, fixed with https://github.com/DivanteLtd/vue-storefront/pull/3497 - please do confirm it works for you

**Comment by themreza** [comment]
Yes, it does fix the issue.
Thank you.
