### ISSUE TITLE
All products are not importing to elastic database by mage2vs import command

### ISSUE THREAD

**Issue by kumarnaveenpal** [DivanteLtd/vue-storefront#3502]
Hi there,
As I am importing product by **yarn mage2vs import** command, it import products to elastic but not all. The import process has been completed successfully but the products count is less. I have approx 12000 product in my magento 2 store but it imported only 4000-5000 products only.

I am using :
Node Version : v8.16.1
NPM Version : 6.4.1
vue-storefront Version : 1.10.0
Magento2 Version : 2.2.6

Vue-storefront-api **config/local.json** is as below:

{
  "server": {
    "host": "localhost",
    "port": 8080,
    "searchEngine": "elasticsearch"
  },
  "orders": {
    "useServerQueue": false
  },
  "catalog": {
    "excludeDisabledProducts": false
  },
  "elasticsearch": {
    "host": "localhost",
    "port": 9200,
    "protocol": "http",
    "user": "elastic",
    "password": "changeme",
    "min_score": 0.01,
    "indices": [
      "vue_storefront_catalog"
    ],
    "indexTypes": [
      "product",
      "category",
      "cms",
      "attribute",
      "taxrule",
      "review"
    ],
    "apiVersion": "5.6"
  },
  "redis": {
    "host": "localhost",
    "port": 6379,
    "db": 0,
    "auth": false
  },
  "kue": {},
  "availableStores": [
    "en_migrated",
    "fr_migrated"
  ],
  "msi": {
    "enabled": false,
    "defaultStockId": 1
  },
  "storeViews": {
    "multistore": true,
    "mapStoreUrlsFor": [
      "en_migrated",
      "fr_migrated"
    ],
    "en_migrated": {
      "storeCode": "en_migrated",
      "disabled": false,
      "storeId": 2,
      "name": "English Store",
      "url": "/en",
      "elasticsearch": {
        "host": "localhost:8080/api/catalog",
        "index": "vue_storefront_catalog"
      },
      "msi": {
        "stockId": 2
      },
      "tax": {
        "defaultCountry": "CA",
        "defaultRegion": "",
        "calculateServerSide": true,
        "sourcePriceIncludesTax": false
      },
      "i18n": {
        "fullCountryName": "Canada",
        "fullLanguageName": "English",
        "defaultLanguage": "EN",
        "defaultCountry": "CAN",
        "defaultLocale": "en_CA",
        "currencyCode": "CAD",
        "currencySign": "CAD",
        "dateFormat": "HH:mm D-M-YYYY"
      }
    },
    "fr_migrated": {
      "storeCode": "fr_migrated",
      "disabled": false,
      "storeId": 3,
      "name": "French Store",
      "url": "/fr",
      "elasticsearch": {
        "host": "localhost:8080/api/catalog",
        "index": "vue_storefront_catalog"
      },
      "msi": {
        "stockId": 2
      },
      "tax": {
        "defaultCountry": "CA",
        "defaultRegion": "",
        "calculateServerSide": true,
        "sourcePriceIncludesTax": false
      },
      "i18n": {
        "fullCountryName": "Canada",
        "fullLanguageName": "French",
        "defaultCountry": "CAN",
        "defaultLanguage": "FR",
        "defaultLocale": "fr_CA",
        "currencyCode": "CAD",
        "currencySign": "CAD",
        "dateFormat": "HH:mm D-M-YYYY"
      }
    }
  },
  "authHashSecret": "__SECRET_CHANGE_ME__",
  "objHashSecret": "__SECRET_CHANGE_ME__",
  "cart": {
    "setConfigurableProductOptions": false
  },
  "tax": {
    "defaultCountry": "PL",
    "defaultRegion": "",
    "calculateServerSide": true,
    "alwaysSyncPlatformPricesOver": false,
    "usePlatformTotals": true,
    "setConfigurableProductOptions": true,
    "sourcePriceIncludesTax": false
  },
  "bodyLimit": "100kb",
  "corsHeaders": [
    "Link"
  ],
  "platform": "magento2",
  "registeredExtensions": [
    "mailchimp-subscribe",
    "example-magento-api",
    "cms-data",
    "mail-service",
    "example-processor"
  ],
  "extensions": {
    "mailchimp": {
      "listId": "e06875a7e1",
      "apiKey": "a9a3318ea7d30f5c5596bd4a78ae0985-us3",
      "apiUrl": "https://us3.api.mailchimp.com/3.0"
    },
    "mailService": {
      "transport": {
        "host": "smtp.gmail.com",
        "port": 465,
        "secure": true,
        "user": "vuestorefront",
        "pass": "vuestorefront.io"
      },
      "targetAddressWhitelist": [
        "contributors@vuestorefront.io"
      ],
      "secretString": "__THIS_IS_SO_SECRET__"
    },
    "example-processor": {
      "resultProcessors": {
        "product": "my-product-processor"
      }
    }
  },
  "magento2": {
    "imgUrl": "https://mymagento2.store/pub/media/catalog/product",
    "assetPath": "/../var/magento2-sample-data/pub/media",
    "api": {
      "url": "https://mymagento2.store/rest",
      "consumerKey": "xxxxxxxxxxxxxxxxxxxxxxxx",
      "consumerSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "accessToken": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "accessTokenSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    },
    "url": "https://mymagento2.store"
  },
  "magento1": {
    "imgUrl": "http://magento-demo.local/media/catalog/product",
    "assetPath": "",
    "magentoUserName": "",
    "magentoUserPassword": "",
    "httpUserName": "",
    "httpUserPassword": "",
    "api": {
      "url": "http://magento-demo.local/vsbridge",
      "consumerKey": "",
      "consumerSecret": "",
      "accessToken": "",
      "accessTokenSecret": ""
    }
  },
  "imageable": {
    "maxListeners": 512,
    "imageSizeLimit": 1024,
    "whitelist": {
      "allowedHosts": [
        ".*divante.pl",
        ".*vuestorefront.io",
        "localhost",
	".*mymagento.store",
	".*mymagento.com"
      ]
    },
    "cache": {
      "memory": 50,
      "files": 20,
      "items": 100
    },
    "concurrency": 0,
    "counters": {
      "queue": 2,
      "process": 4
    },
    "simd": true
  },
  "entities": {
    "category": {
      "includeFields": [
        "children_data",
        "id",
        "children_count",
        "sku",
        "name",
        "is_active",
        "parent_id",
        "level",
        "url_key"
      ]
    },
    "attribute": {
      "includeFields": [
        "attribute_code",
        "id",
        "entity_type_id",
        "options",
        "default_value",
        "is_user_defined",
        "frontend_label",
        "attribute_id",
        "default_frontend_label",
        "is_visible_on_front",
        "is_visible",
        "is_comparable"
      ]
    },
    "productList": {
      "sort": "",
      "includeFields": [
        "type_id",
        "sku",
        "product_links",
        "tax_class_id",
        "special_price",
        "special_to_date",
        "special_from_date",
        "name",
        "price",
        "priceInclTax",
        "originalPriceInclTax",
        "originalPrice",
        "specialPriceInclTax",
        "id",
        "image",
        "sale",
        "new",
        "url_key"
      ],
      "excludeFields": [
        "configurable_children",
        "description",
        "configurable_options",
        "sgn"
      ]
    },
    "productListWithChildren": {
      "includeFields": [
        "type_id",
        "sku",
        "name",
        "tax_class_id",
        "special_price",
        "special_to_date",
        "special_from_date",
        "price",
        "priceInclTax",
        "originalPriceInclTax",
        "originalPrice",
        "specialPriceInclTax",
        "id",
        "image",
        "sale",
        "new",
        "configurable_children.image",
        "configurable_children.sku",
        "configurable_children.price",
        "configurable_children.special_price",
        "configurable_children.priceInclTax",
        "configurable_children.specialPriceInclTax",
        "configurable_children.originalPrice",
        "configurable_children.originalPriceInclTax",
        "configurable_children.color",
        "configurable_children.size",
        "product_links",
        "url_key"
      ],
      "excludeFields": [
        "description",
        "sgn"
      ]
    },
    "product": {
      "excludeFields": [
        "updated_at",
        "created_at",
        "attribute_set_id",
        "status",
        "visibility",
        "tier_prices",
        "options_container",
        "msrp_display_actual_price_type",
        "has_options",
        "stock.manage_stock",
        "stock.use_config_min_qty",
        "stock.use_config_notify_stock_qty",
        "stock.stock_id",
        "stock.use_config_backorders",
        "stock.use_config_enable_qty_inc",
        "stock.enable_qty_increments",
        "stock.use_config_manage_stock",
        "stock.use_config_min_sale_qty",
        "stock.notify_stock_qty",
        "stock.use_config_max_sale_qty",
        "stock.use_config_max_sale_qty",
        "stock.qty_increments",
        "small_image"
      ],
      "includeFields": null,
      "filterFieldMapping": {
        "category.name": "category.name.keyword"
      }
    }
  },
  "usePriceTiers": false,
  "boost": {
    "name": 3,
    "category.name": 1,
    "short_description": 1,
    "description": 1,
    "sku": 1,
    "configurable_children.sku": 1
  }
}

Please guide me, Am I missing something or configured wrong?

Thanks!

**Comment by pkarw** [comment]
Hi there, please move this discussion to https://forum.vuestorefront.io
Please also do try the `magento2-vsbridge-indexer` instead of `mage2vuestorefront`: https://github.com/DivanteLtd/magento2-vsbridge-indexer
