### ISSUE TITLE
Error Something went wrong ...

### ISSUE THREAD

**Issue by bay20soft** [DivanteLtd/vue-storefront#3505]
I have installed vue storefront successfully. It shows me the success message and url with 3000 port. But when i ran it shows 'Something went wrong ...' and 'We've noticed Internal Server Error while rendering this request.

If you need an assistance you can drop us a line on a contact page'

Not sure what exactly this issue for.

**Comment by pkarw** [comment]
Please move this discussion to forum.vuestorefront.io or Slack. It's probably your `vue-storefront` app has no connectivity to `vue-storefront-api` - an issue pretty often taking place in docker env. make sure the endpoints are reachable from one container to another

**Comment by kristapsbriks** [comment]
How to make sure the endpoints are reachable from one container to another?
