### ISSUE TITLE
Comparison feature is not keeping a state on page reload.

### ISSUE THREAD

**Issue by vue-kacper** [DivanteLtd/vue-storefront#3508]
## What is the motivation for adding / enhancing this feature?

A small unconvenience - products on comparison list are not preserved between page reloads. That means we can not compare one product with another opened in a new tab.

We should keep products in comparison list in a session. This will prevent resets on page reload. We will be also able to open new links in new tabs with preserved items.

## What are the acceptance criteria 

Page reload should not reset comparison list items.

**Comment by pkarw** [comment]
They should; they were; something is broken probably with https://github.com/DivanteLtd/vue-storefront/blob/68e7b62ae52c53158f4724e7fe31cbfaef533a25/core/modules/compare/store/plugin.ts#L9 - or reading this itetm from `localStorage`
