### ISSUE TITLE
Consider moving the theme into its own git repository

### ISSUE THREAD

**Issue by juho-jaakkola** [DivanteLtd/vue-storefront#3519]
## What is the motivation for adding / enhancing this feature?

Upgrading upstream changes from the default theme into a project specific custom theme is painful manual work. How about simply moving the default theme into its own git repository? Custom themes could be forked from it, and then upgraded simply by doing a `git pull` from upstream repository.

It would even be possible to extract the theme without losing the commit history. See: https://help.github.com/en/articles/splitting-a-subfolder-out-into-a-new-repository

## Can you complete this feature request by yourself?

- [ ] YES
- [X] NO

I don't have permission to create new repos under DivanteLtd. I could however do the splitting if someone else creates the repo.

**Comment by juho-jaakkola** [comment]
Most likely there are some dependency issues, that would need to be solved in order for this to work?

**Comment by juho-jaakkola** [comment]
This is (maybe?) a bit off topic, but how are themes meant to work with multistore sites?

Does VSF already support having a separate theme for each storeview? So the config file would have separate entries for each:

`storeViews.en.theme = 'theme-left-to-right'` // English
`storeViews.ar.theme = 'theme-right-to-left'` // Arabic

I just started wondering, if it indeed is possible to define a separate theme for each storeview, having a separate repo would indeed be a good idea. Different branches from the theme repo could be installed into separate directories within VSF, and then enabled for specific storeviews.

All store specific themes would share all basic components from upstream, site specific stuff from some site base branch, and then would have storeview specific customizations in their own branches.

Changes would flow downstream like this:

- Upstream (default theme) ->
  - Site base theme ->
    - Storeview theme A
    - Storeview theme B
    - ...

**Comment by filrak** [comment]
@juho-jaakkola hey, thanks for your feedback. Fortunately this is exactly what we're working on for version 2.0  along with moving core to npm and multistore capabilities you mentioned ;) Stay tuned
