### ISSUE TITLE
Create an upgrade tutorial (1.10-1.11)

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3521]
## What is the motivation for adding / enhancing this feature?

We need someone who'll take the 1.10 clean installation and will try to upgrade it to 1.11 and create a tutorial/doc on what exactly needs to be changed. Plus commit all the changes required as a simple, one commit/pull request to show clearly what needs to be done in order to upgrade.

Something that @filrak did showing the upgrade from 1.5->1.6 back then: https://github.com/DivanteLtd/vue-storefront/commit/cc17b5bfa43a9510815aea14dce8bafac382bc7f#diff-fa33732560b7c39ea7854f701c4187bf

**Comment by kkdg** [comment]
Duly noted thanks!
