### ISSUE TITLE
"Clear wishlist" button on the wishlist page doesn't work

### ISSUE THREAD

**Issue by dz3n** [DivanteLtd/vue-storefront#3522]
## Current behavior
When you trying to remove some items from wishlish page with button "Clear wishlist", this button doesn't work and the items will not be deleted

## Expected behavior
This button have to work and clean the whole wishlist

## Steps to reproduce the issue
1. Add some item on wishlist
2. Try to remove it with "Clear wishlist" button

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 76.0.3809.132
- OS: Linux Mint
- Node: v8.16.1
- Code Version: master/develop

**Comment by pkarw** [comment]
@dz3n can you please fix it?

**Comment by dz3n** [comment]
@pkarw sure, PR is added
