### ISSUE TITLE
Error during e2e tests

### ISSUE THREAD

**Issue by juho-jaakkola** [DivanteLtd/vue-storefront#3536]
## Current behavior

When running the command:
```
yarn test:e2e:ci
```
I get the error:
```
1) add to cart "before all" hook for "verify that the configurable product
is added to cart":

Error: Failed to execute 'keys' on 'CacheStorage':
Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
at Context.<anonymous>
http://app.storefront.dev/__cypress/tests?p=test/e2e/support/index.js-629:52:24
```

My colleague made the following fix for it:

```diff
diff --git a/test/e2e/support/index.js b/test/e2e/support/index.js
index 1a5a601eedaa8bb815088ff044151c050bbdd2fc..5920be9bcc29496a45cbff25d7e39ea92c521701 100644
--- a/test/e2e/support/index.js
+++ b/test/e2e/support/index.js
@@ -20,13 +20,14 @@ import './commands'
 // require('./commands')
 
 before(() => {
-  return window.caches.keys().then((cacheNames) => {
-    return Promise.all(
-      cacheNames.map((cacheName) => {
-        return window.caches.delete(cacheName);
+  if (window.navigator && navigator.serviceWorker) {
+    navigator.serviceWorker.getRegistrations()
+      .then((registrations) => {
+        registrations.forEach((registration) => {
+          registration.unregister()
+        })
       })
-    );
-  })
+  }
 })
 
 beforeEach(() => {
```

Are the tests working in Divante's internal use? Any idea what might cause the problem in our case?

## Repository

https://github.com/DivanteLtd/vue-storefront/tree/v1.10.0

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO
- [x] Maybe

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
 - MacOS Mojave 10.14.6
 - yarn 1.15.2
 - node 10.13.0

**Comment by alinadivante** [comment]
No, these tests are old, I will try to find time to improve them.
You can run these tests with `yarn tests:e2e`

**Comment by juho-jaakkola** [comment]
I asked earlier about the location of the *new* tests. Where are those located? Any documentation about those yet?

**Comment by alinadivante** [comment]
oh, sorry, my mistake. Unfortunately, I don't know anything about new tests.

**Comment by juho-jaakkola** [comment]
> as we switched to the integration/unit tests some time ago.

@pkarw Where can I find these new tests you mentioned?

As far as I'm concerned, this issue can be closed, and the effort of fixing the old tests can be used on the new tests. But there should be some reference to the new tests so that whoever finds this issue is able to find them.

**Comment by pkarw** [comment]
@juho-jaakkola the tests are splited across modules (`core/modules/*/test`)
