### ISSUE TITLE
Problem with quantity of products added to cart. 

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#3547]
In given scenario, user is allowed to add 2 many products to cart. When that happens, it's impossible to reduce this quantity from cart window. 

## Steps to reproduce the issue
1. Open https://demo.storefrontcloud.io/women/tops-women/jackets-women/jackets-23/neve-studio-dance-jacket-1369.html?childSku=WJ11-XS-Black. Stick with XS Black version
2. Set quantity to 30 and add product to cart - 
3. Now open cart window and try to increase or REDUCE quantity

## Current behavior
Error message is displayed, suggesting desired quantity is not availible. Attempt to reduce quantity also fails, setting it back to 30. 

![QuantityBug](https://user-images.githubusercontent.com/47415585/64876633-da048300-d64f-11e9-8396-4470523b8f0f.gif)

## Expected behavior
Availability checks on adding to cart and in cart itself should be consistent

## Additional information
Same behaviour is reproducible on develop, where stock display is implemented. Displayed stock for this size/color combo is 47. Attempt to add more than 47 products immediately from PDP, is correctly blocked with error message displayed right away.

## Repository
- demo.storefrontcloud.io
- current develop

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Latest chrome
- OS: Ubuntu 18.04, Windows 7
- Code Version: master, develop

**Comment by pkarw** [comment]
Hi @ArturDivante this is unfixable error since it's in the magento2 core. Details: https://github.com/DivanteLtd/vue-storefront/issues/3083#issuecomment-508951884
