### ISSUE TITLE
Broken sidebar menu in mobile view

### ISSUE THREAD

**Issue by lukeromanowicz** [DivanteLtd/vue-storefront#3549]
## Current behavior
Subemnu in sidebarmenu displays wrong positioned homepage link.

![image](https://user-images.githubusercontent.com/46789227/64892681-5fe6f500-d675-11e9-90ff-525917d548fe.png)

## Expected behavior
Homepage link should be invisible

## Steps to reproduce the issue
open website on mobile, enter some submenu, scroll right

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
@przspa please take care of this one

**Comment by lukeromanowicz** [comment]
When fixing this issue please also add `-webkit-overflow-scrolling: touch;` to menu, search results and cart so the scrolling on phones was smooth.
