### ISSUE TITLE
Cannot add a review

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#3559]
## Current behavior

Currently, when I want to add a review using the form on product page, I get erore messages:
- testing locally I get 500
![image (6)](https://user-images.githubusercontent.com/49188852/64958463-82545a80-d88f-11e9-892d-cd2ae0590b98.png)

- testing on test env I get 404

![Selection_070](https://user-images.githubusercontent.com/49188852/64958471-88e2d200-d88f-11e9-8760-d640490c24dc.png)

## Expected behavior

I can add a review using the form on product page. After adding a review success message is displayed. 

## Steps to reproduce the issue

1. Go to https://test.storefrontcloud.io or branch develop locally
2. Go to any product page
3. Fill in Add review form 
4. Click on Add review

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 76
- OS: Ubuntu 18.04 LTS, Windows 10

## Additional information

The problem appears for both logged in and not logged users.

**Comment by pkarw** [comment]
This error is because the magento backend doesn't have the review module installed https://github.com/DivanteLtd/magento2-review-api. It's not a VSF issue (we haven't changed anything related to reviews recently)
