### ISSUE TITLE
Getting 500 when checking user newsletter subscription

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#3562]
## Current behavior

Currently, when I'm logging in or going to my newsletter in my account, the subscription status cannot be checked. 
There is an error message visible and in the console"
{"code":500,"result":"An error occured while accessing Mailchimp"}
for request GET /api/ext/mailchimp-subscribe/subscribe?email=user_email

## Expected behavior

When logging in or going to My newsletter in My account - newsletter subscription status should be got correctly and display proper info in My newsletter view. 

## Steps to reproduce the issue

1. Go to https://test.storefrontcloud.io
2. Click on My account icon
3. Log in to your account
4. Go to My newsletter view 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 76
- OS: Ubuntu 18.04 LTS

## Additional information

The problem doesn't appear locally on develop.

**Comment by GabiDivante** [comment]
![Peek 2019-09-16 14-45](https://user-images.githubusercontent.com/49188852/64960389-7cf90f00-d893-11e9-9038-e3809f08a451.gif)

**Comment by pkarw** [comment]
It seems like MailChimp misconfiguration

**Comment by alinadivante** [comment]
yes, problem exists on test API, it would be great to have Mailchimp configuration/test account.
And @andrzejewsky, I didn't test it after your changes in the API, now I found out that you did this PR in the API after my approval: DivanteLtd/vue-storefront-api#336 😛
