### ISSUE TITLE
Incorrect behavior of the wishlist at multistore

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3571]
## Current behavior
Products added to the wishlist in a store other than the default (/de, /it) after switching to the default store are automatically transferred to the wishlist.

## Expected behavior
IMHO wishlist shouldn't be moved after changing the store.

## Steps to reproduce the issue
1. Run the latest develop http://localhost: 3000/
2. Change the store to /de or /it
3. Add something to the wishlist
4. Return to the default store and check the wishlist
5. Change the store again and add other products to the wishlist
6. Repeat step 4

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version: 

## Additional information
v1.11.0-rc.1

**Comment by gibkigonzo** [comment]
I would like to fix it. @pkarw Can you assign me?

**Comment by pkarw** [comment]
Sure, there is a switch `localised` for having the prefixed localStorage keys for the wishlist - it should basically work just fine in 1.11 from what I see in the src: https://github.com/DivanteLtd/vue-storefront/blob/87214b516d25dcb5b4fb23a1b89efdb7e45c8450/core/helpers/initCacheStorage.ts#L15

**Comment by pkarw** [comment]
https://github.com/DivanteLtd/vue-storefront/blob/87214b516d25dcb5b4fb23a1b89efdb7e45c8450/core/modules/wishlist/index.ts#L7

**Comment by pkarw** [comment]
Oh the links were all wrong (1.10)

**Comment by pkarw** [comment]
This one: https://github.com/DivanteLtd/vue-storefront/blob/748efc08cda861373ad2bd836c142c83f1117aa1/core/lib/storage-manager.ts#L7

and here we have this localised based on config `localized = !config.storeViews.commonCache` the default value for this is: https://github.com/DivanteLtd/vue-storefront/blob/748efc08cda861373ad2bd836c142c83f1117aa1/config/default.json#L114 - `false` 

@alinadivante what's your setting of `config.storeViews.commonCache` in the `config/local.json`?

**Comment by alinadivante** [comment]
@pkarw     `"commonCache": false`

**Comment by pkarw** [comment]
that's strange :) in that case it should work just fine

**Comment by gibkigonzo** [comment]
I've created PR, I think this would fix a problem :) https://github.com/DivanteLtd/vue-storefront/pull/3577
