### ISSUE TITLE
Error applying coupon.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3578]
## Current behavior
When you try to apply valid discount coupon, nothing happens and there is error in dev console.
![image](https://user-images.githubusercontent.com/36628922/65158819-6093d880-da33-11e9-8627-484d72360545.png)

## Expected behavior
The discount coupon should be applied.

## Steps to reproduce the issue
1. Run the latest develop version
2. Add any product to the cart
3. Apply valid discount code, e.g. `mmtest`

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
Probably related to cart refactor(?)

**Comment by andrzejewsky** [comment]
It's not related to the refactor for sure. It seems like wrong reference to the `applyCoupon` I'm guessing there is some missing mixin... but I'll check, I'm pretty sure it'll be a quick fix

**Comment by andrzejewsky** [comment]
ahh even I can see it now... there is no mapped action, It supposed to be `this.$store.dispatch('cart/applyCoupon', this.couponCode)` call or `applyCoupon` mapped. I'll fix it.
