### ISSUE TITLE
2 Digit Locale breaks date filter

### ISSUE THREAD

**Issue by rain2o** [DivanteLtd/vue-storefront#3581]
## Current behavior
In the scenario where a locale is only 2-digits (e.g. 'en'), `separatorIndex` has a value of `-1`. The line `const languageCode = separatorIndex ? storeLocale.substr(0, separatorIndex) : storeLocale` checks the "truthiness" of that value, which according to [MDN](https://developer.mozilla.org/en-US/docs/Glossary/Truthy), -1 is actually truthy. This resulted in a series of errors because `languageCode` was an empty value which caused dayjs to complain about `dayjs().locale().locale()`.

## Expected behavior
The value of `separatorIndex` should be checked that it is greater than -1.

## Steps to reproduce the issue
* Set a store's locale to be a 2-digit code without a dash (such as 'en' or 'fr').
* Go to a view which uses the date filter, such as Order History.
* View console for all the errors.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Node: 10.16
- Code Version: v1.10.2

**Comment by patzick** [comment]
Thanks @rain2o :)
