### ISSUE TITLE
The same country is displayed twice in the country switcher.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3587]
## Current behavior
If you are in store other than the default store, you will see that the same country is displayed twice in the country switching module.

![image](https://user-images.githubusercontent.com/36628922/65321764-585baa80-dba5-11e9-97bb-ca882ab530fd.png)
(but url addresses are fine)

## Expected behavior
There should be three different country names:
- United States - English
- Germany - German
- Italy - Italian

## Steps to reproduce the issue
1. Go to non-default store, e.g.  http://localhost:3000/de
2. Scroll down the page
3. Press "country switcher"

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by andrzejewsky** [comment]
Unfortunately I'm unable to display all languages. Anyone know if there is some possibility to have access for all of available languages including default one?

**Comment by pkarw** [comment]
Please check your config: `storeViews.multistore` should be `true`. Reference: https://github.com/DivanteLtd/vue-storefront/blob/4c367452d306d80cd4397413fa60f7c568bf8e68/src/themes/default/components/core/blocks/Switcher/Language.vue#L9

**Comment by andrzejewsky** [comment]
@pkarw yeah, and this line displays current language but... when I have set "German" how can I display default one ("English")? There is no way to read the default lang. The `config.i18n.*` contains always current one.
