### ISSUE TITLE
Unexpected authorization error. Check your Network connection - but user is logged in.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3588]
## Current behavior
An authorization error occurred while attempting to log in due to a network problem. I get error message (visible on screenshot), the login pop-up remains, but after closing it turns out that I'm logged in.

![image](https://user-images.githubusercontent.com/36628922/65323246-22b8c080-dba9-11e9-9d3a-0bd482aa8533.png)

## Expected behavior
If  "Unexpected authorization error" occurs, I shouldn't log in, or if I am logged in successfully, there should be no such errors.

## Steps to reproduce the issue
1. I just logged in..

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by andrzejewsky** [comment]
Can't reproduce @alinadivante, please send me more details on Slack
