### ISSUE TITLE
Bestsellers are not loading properly on "404" page.

### ISSUE THREAD

**Issue by vue-kacper** [DivanteLtd/vue-storefront#3594]
## Current behavior

Bestsellers list is not loading properly on "404" page.

## Expected behavior

Bestsellers list should be rendered properly on "404" page.

## Steps to reproduce the issue

Visit: https://test.storefrontcloud.io/sample-error-page
Refresh page

![image](https://user-images.githubusercontent.com/42430550/65361661-a784f800-dc04-11e9-871a-a2140dbdee44.png)

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information

I think the problem is related to  "asyncData" function:
https://github.com/DivanteLtd/vue-storefront/blob/develop/core/pages/PageNotFound.js#L23

SSR side is able to set new element in a state, client-side is not.

The weird thing, when you clear cache and navigate to "404" page from home page via a link - everything work properly:

![image](https://user-images.githubusercontent.com/42430550/65361599-70aee200-dc04-11e9-9566-9b08200c74b8.png)

**Comment by andrzejewsky** [comment]
Actually duplicated here: https://github.com/DivanteLtd/vue-storefront/pull/3540#issuecomment-533501604

**Comment by andrzejewsky** [comment]
Actually duplicated here: https://github.com/DivanteLtd/vue-storefront/pull/3540#issuecomment-533501604
