### ISSUE TITLE
Add same SKU with different custom options to the cart

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3595]
## What is the motivation for adding / enhancing this feature?

Unfortunately, we haven’t supported this case yet (custom options, same SKU); we recently added support for this case for bundle products and I believe it’s something that could be extrapolated to custom options: https://github.com/DivanteLtd/vue-storefront/pull/3261 3

More info:
- https://forum.vuestorefront.io/t/how-to-create-different-cart-items-for-same-product-with-different-prices-and-product-type-is-giftcard/635
- https://forum.vuestorefront.io/t/issue-buying-multiple-products-with-the-same-sku/622/3

Seemingly, we need to be able to add multiple products with the same SKU to the cart with just customized product options

**Comment by ktopouzi** [comment]
Hey guys, since I really need this feature, can you please point me out to the right direction to either solve or bypass somehow this issue? I am more than willing to fix this if you can guide me in some way. Thanks :)

**Comment by manjula-gurjar-bod** [comment]
Hi @pkarw,

I want to add the same SKU product in the cart but the product type is not bundled I have a custom product and adding additional options from frontend with the help of API but on frontend after add to cart a product, on any page reload the product again add to cart and qty becomes double and subtotal also. I am trying to make the checksum different and added a random number in the custom_option on the frontend to make the product multiple in the cart.

Is there any other solution available by that I can achieve this for a custom product?
