### ISSUE TITLE
Problem with custom options

### ISSUE THREAD

**Issue by vue-kacper** [DivanteLtd/vue-storefront#3597]
## Current behavior
I'm unable to add bundle type product to cart.

## Expected behavior
I should be able to see bundle type product price and add it to cart. 

## Steps to reproduce the issue

Visit: https://test.storefrontcloud.io/gear/gear-3/sprite-yoga-companion-kit-45.html
Try to add the product to cart.

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information

There are minor differences in API response for this product between "test." and "demo.":

https://test.storefrontcloud.io/api/catalog/vue_storefront_catalog/product/_search?q=sku:24-WG080

https://demo.storefrontcloud.io/api/catalog/vue_storefront_catalog/product/_search?q=sku:24-WG080

**Comment by vue-kacper** [comment]
Related issue:

When I'm adding a bundle-type product to wishlist from the catalog page, in wishlist sidebar I can see the price of $0

![image](https://user-images.githubusercontent.com/42430550/65375308-355bf400-dc94-11e9-9c80-6f80eeb8ee11.png)

But from product details page - removing this bundle-type product from wishlist and adding it again will output different price in wishlist sidebar:

![image](https://user-images.githubusercontent.com/42430550/65375338-8cfa5f80-dc94-11e9-8473-b3de2c455faf.png)

**Comment by pkarw** [comment]
Related to: #3093 (last comment). @andrzejewsky or @patzick could you please fix it?

**Comment by pkarw** [comment]
I can confim the issue with product options seems to be fixed - it now works for me both for wislists + cart


BUT there is another problem with custom options - I can't add the product to cart

Product with custom options:
http://localhost:3000/gear/gear-3/wayfarer-messenger-bag-custom-options-4.html

Error:

https://www.dropbox.com/s/k26z2fbqz6i8pcb/Screenshot%202019-09-24%2011.46.38.png?dl=0

Plus - the radiobuttons under checkboxes doesn't look great :) It should look exactly the same way like it's for bundle: http://localhost:3000/gear/gear-3/sprite-yoga-companion-kit-45.html

**Comment by patzick** [comment]
fixed with #3600 :)

**Comment by pkarw** [comment]
@patzick it's not :) see the comment about custom options: https://github.com/DivanteLtd/vue-storefront/issues/3597#issuecomment-534482149

**Comment by andrzejewsky** [comment]
There were few errors but when I've fixed them, now it seems like it's also a problem with the API:
<img width="1098" alt="Screenshot 2019-09-25 at 20 37 03" src="https://user-images.githubusercontent.com/7943292/65629856-7c1f5600-dfd4-11e9-8cdb-b1eb266b210a.png">
<img width="783" alt="Screenshot 2019-09-25 at 20 37 12" src="https://user-images.githubusercontent.com/7943292/65629863-804b7380-dfd4-11e9-8cec-a1fe989c81fb.png">

**Comment by alinadivante** [comment]
I have the same problem when I add a bundle-type (or group) product to wishlist (or compare list) from the catalog page on release v11.1
![image](https://user-images.githubusercontent.com/36628922/65880729-8b1a5580-e392-11e9-953c-3dd4dc408f1a.png)

![image](https://user-images.githubusercontent.com/36628922/65880768-a1c0ac80-e392-11e9-980c-82bdb749a4e5.png)

**Comment by pkarw** [comment]
OK, this is urgent one. There is an option is using `priceInclTax` instead of `price_incl_tax` - but rather this is not this case; maybe it's becuase we're calculating the prices just on PDP. In that case I belive we may want to disable "add to wishlist" and "add to compare" for `budle` and `grouped` types of product on the category product list and let those products be added to the comparison/wishlist only from PDP. It's not the best solution but probably the quickest one.

**Comment by andrzejewsky** [comment]
everything works for me with the newest API (I have API installed locally), but it's just question of `priceInclTax` and `price_incl_tax` as you @pkarw said
