### ISSUE TITLE
Translations issues in production mode

### ISSUE THREAD

**Issue by ivancukns** [DivanteLtd/vue-storefront#3602]
## Current behavior

When trying to translate strings taken from the query string, in custom theme components, the translation does not work in production mode. In dev mode, it works always.
If I try with hardcoded values, the translation works, but in this case, we need the string to be taken from the query.
Example code: `i18n.t(this.$route.query.newsletter)`

## Expected behavior

The query string value should be translated, also when in the production mode.

## Steps to reproduce the issue

1. go to this url in the browser: http://localhost:3000/?newsletter=Your%20subscription%20has%20been%20confirmed.
2. Try to take the newsletter query value on mounted, translate it and send a notification.
`  mounted () {
    this.newsletterCheck()
  }`

`        this.$store.dispatch('notification/spawnNotification', {
          type: 'success',
          message: i18n.t(this.$route.query.newsletter),
          action1: { label: i18n.t('OK') }
        })`
## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  Google Chrome Version 77.0.3833.0 (Offizieller Build) dev (64-Bit)
- OS:  MacOS Sierra 10.12.6
- Node:  10.15.1
- Code Version:

**Comment by pkarw** [comment]
Just one question to clarify - you mean the string is not getting translated but the query parameter value is accessible or if the query parameter is empty?

**Comment by ResuBaka** [comment]
The query parameter is accessible but it is not translated in production mode in dev mode it works just fine. 


```typescript
  mounted () {
    this.newsletterCheck()
  },
  data () {
    return {
      newsletterResponse: [
        'Test 1',
        'Test 2',
        'Test 3'
      ]
    }
  },
methods: {
    newsletterCheck () {
      if (this.$route.query.newsletter && this.newsletterResponse.includes(this.$route.query.newsletter)) {
        this.$store.dispatch('notification/spawnNotification', {
          type: 'success',
          message: i18n.t(this.$route.query.newsletter),
          action1: { label: i18n.t('OK') }
        })
      }
    }
}
```

Here you have all the code to that we use. @pkarw

**Comment by ResuBaka** [comment]
Maybe some more missing info that are helpful.

* Multistore true
* default language: en-US 
* storeView language: de-DE

**Comment by gibkigonzo** [comment]
@ResuBaka I've created PR to fix this https://github.com/DivanteLtd/vue-storefront/pull/3605 Is your config `i18n.bundleAllStoreviewLanguages` in production is set on `false`?

**Comment by ResuBaka** [comment]
Hey @gibkigonzo it is set to `true`.

**Comment by gibkigonzo** [comment]
Ok :) I see also that there is in config `storeViews.de.disabled` and it's used only to build messages in one file. If we go on https://demo.storefrontcloud.io/de then on banners we have translation but on bottom of page there is still english.
