### ISSUE TITLE
Product SKU should be always cast to string 

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#3606]
## What is the motivation for adding / enhancing this feature?

Sometimes the client SKU is in the form of an integer. On the VSF side, we keep them as a string. With synchronization enabled, this results in duplicate products (for vsf, this product is not in the cart). For security reasons, it seems necessary to cast both values ​​on a string, i.e. instead of the selected condition in here:
https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/cart/store/actions.ts#L624
add this:
` const serverItem = serverItems.find((itm) => {
        return itm.sku.toString() === clientItem.sku.toString() || itm.sku.indexOf(clientItem.sku + '-') === 0 /* bundle products */
      })`

Casting string to string will give a string, casting int to string also will give a stirng, and then `===` will work.
(author: sszczepanski)
## Can you complete this feature request by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by andrzejewsky** [comment]
@GabiDivante is there any possibility to have sku as integer? I thought there is always a string as sku is in format like `xx-xx-xx` are you sure about that? can you show some examples or how to reproduce error when it breaks the synchronisation?

**Comment by pkarw** [comment]
@andrzejewsky it could be whatever. it should be cased to string to be sure

**Comment by andrzejewsky** [comment]
@pkarw ok I see, thanks 👍
