### ISSUE TITLE
`productName` property is not defined in reviews

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3607]
## Current behavior

On PDP page:
https://www.dropbox.com/s/y8hldtj9oc9qksc/Screenshot%202019-09-24%2011.24.52.png?dl=0

**Comment by andrzejewsky** [comment]
I can't even add a review: 
<img width="1300" alt="Screenshot 2019-09-24 at 21 37 10" src="https://user-images.githubusercontent.com/7943292/65544448-86c5e680-df13-11e9-8eca-e50cd06bf2a2.png">
API response says `Request does not match any route.` it might be a different route for reviews, for sure it needs to be checked as well.

@gibkigonzo please look at this, especially about that missing `productName` but let me know if you have some problems.

**Comment by pkarw** [comment]
Don’t worry about the issues with adding the reviews it’s because the particular endpoint you’re using for demo (test?) doesn’t has https://github.com/DivanteLtd/magento2-review-api installed. The only error to fix here is with prosuctName it’s  vidiblr on products having reviews like https://test.storefrontcloud.io/gear/gear-3/joust-duffle-bag-1.html

**Comment by andrzejewsky** [comment]
@pkarw In terms of reviews - yeah this is what I wanted to check today, thanks!
@gibkigonzo fixing that `productName` should be really quick, it seems like missing prop.
