### ISSUE TITLE
Can't login - probably due to mailchimp incorect settings

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3612]
## Current behavior

https://www.dropbox.com/s/qn32epafksiv7xc/Screenshot%202019-09-24%2013.02.36.png?dl=0

It's probably because Mailchimp is on the critical path

**Comment by andrzejewsky** [comment]
@gibkigonzo can you have look at this? I think it's related to https://github.com/DivanteLtd/vue-storefront/blob/develop/core/modules/user/store/actions.ts#L63 because that error is consumed in the template and displays as error notification which you can see on the screenshot (last one), would be nice to find out what where that error comes from.

**Comment by andrzejewsky** [comment]
@gibkigonzo Unfortunately I couldn't reproduce it for the first sight, but for sure it should occurs when you go to `/my-account` as not logged user, then you will see login dialog and try to log in.

**Comment by gibkigonzo** [comment]
@andrzejewsky working on it. Probably it's caused by wrong api key
```
{ type: 'http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/',
  title: 'API Key Invalid',
  status: 401,
  detail: 'API key has been disabled',
  instance: 'b5686623-b5ef-400f-afeb-01c024bc4d48' }
```
I will pull this information to the console so that we can check on https://test.storefrontcloud.io

**Comment by pkarw** [comment]
It's surely caused by wrong api key. But ppl. might have wrong keys. It should display the error message probably but don't block the login procedure. It shouldn't be on critical path

**Comment by pkarw** [comment]
I'd say that even we shouldn't show the error message when reading the subscription status; only when subscribing/desubscribing  as it was before in 1.10/1.9 - can you please fix it to the previous state?

**Comment by pkarw** [comment]
It's because of additional await added in https://github.com/DivanteLtd/vue-storefront/blob/ac72a07a489bfb4e040c088315cb338d7408097d/core/modules/user/store/actions.ts#L129
