### ISSUE TITLE
silentMode in task.ts ignored for spawnNotification if response is a string

### ISSUE THREAD

**Issue by rain2o** [DivanteLtd/vue-storefront#3621]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	
I am not sure if this is a bug, or if this was done intentionally. If it was intentional then I am trying to understand why.

In [core/lib/sync/task.ts#131](https://github.com/DivanteLtd/vue-storefront/blob/master/core/lib/sync/task.ts#L131) there is the following if statement. I split it up a lot to try and make it easier to read with all of the ands/ors and parentheses.

    if (
        !task.silent
        &&
        jsonResponse.result
        &&
        (
            typeof jsonResponse.result === 'string'
            ||
            (
                (
                    (
                        jsonResponse.result.result
                        ||
                        jsonResponse.result.message
                    )
                    &&
                    jsonResponse.result.code !== 'ENOTFOUND'
                )
                &&
                !silentMode
            )
        )
    )

The piece in question is the placement of `!silentMode`. Currently, if `jsonResponse.result` is a string, then `silentMode` doesn't matter and the following code is executed, which dispatches the notification to be displayed. The placement of the check on `silentMode` only matters if the response is not a string.

Why does `silentMode` not matter for string responses? Was this done for a specific reason, or was it just an oversight in the sea of parentheses that exist in this if statement?

## Additional information
This problem was noticed when testing the expiration of the Magento consumer token. If the initial responses are 401, an attempt to refresh the token is performed. Even if this is successful I still receive multiple notifications in the UI stating "Consumer is not authorized to access self" since Magento's initial response was this and it was returned as a string. But the refresh action was successful and those actions were retried successfully, so these notifications are confusing for the user.

**Comment by pkarw** [comment]
@andrzejewsky or @gibkigonzo please fix it before 1.11rc release
