### ISSUE TITLE
url_key update partially in VSF unless indexer:reindex vsbridge_category_indexer is invoked

### ISSUE THREAD

**Issue by undefinederror** [DivanteLtd/vue-storefront#3622]
Please answer the following questions for yourself before submitting an issue. 
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

I have Magento2 loaded with sample data.
I have installed magento2-vsbridge-indexer, all entities set on "update on save".
I went on `<magento>/admin/catalog/category/edit/` "Search Engine Optimization" and renamed the `url_key` of men->tops from "tops-men" to "tops-meeen" (to check how it will sync in VSF).

I checked in ES `http://localhost:9200/vue_storefront_catalog_1/_search?pretty=true&q=tops-men` and I can see ALL url_key properties correctly renamed to "tops-meeen"

In VSF, only the category itself seemed renamed correctly, 
![image](https://user-images.githubusercontent.com/8209966/65616875-11fab700-dfbc-11e9-9aba-2d34eaedb08a.png)

while the subcategories still retained the old "tops-men"
![image](https://user-images.githubusercontent.com/8209966/65616929-2343c380-dfbc-11e9-866b-fb7eb8bab14f.png)
refreshing/clearing cache/incognito didn't make a difference.

I then executed `php bin/magento indexer:reindex vsbridge_category_indexer` and refreshed the browser, and all urls now work as expected.

So my question is, 
- shouldn't magento2-vsbridge-indexer automatically update ES when set with "update on save"? 
- Also, how is it that vsbridge has indeed updated _something_ automatically, but not all?

I see that product names/prices do update in VSF with no need to run `indexer:reindex vsbridge_category_indexer`

Thank you

**Comment by pkarw** [comment]
@undefinederror you're right currently when the category is changed indexer is not performing re-index on products attached with this category and this is the reason why those products have the `product.url_path` field not updated (and this field is being taken to form the URLs). If you save / change any particular product (like prices) it's gonna be updatetd automatically. Can you please create a `feature rerquest`  in the https://github.com/DivanteLtd/magento2-vsbridge-indexer?

**Comment by undefinederror** [comment]
done! 
[DivanteLtd/magento2-vsbridge-indexer#122](https://github.com/DivanteLtd/magento2-vsbridge-indexer/issues/122)

Thank you @pkarw  for your prompt reply

**Comment by afirlejczyk** [comment]
@pkarw @underf

`product.url_path` - does not include parent category path (by default), so there is no need to update product after category changed.
we only have "short" url_path for products (by default) exported by https://github.com/DivanteLtd/magento2-vsbridge-indexer

As I take a look on screens, I understand that url path for **subcategories** is not updated ?
I will check that.

After we change **category url key** - all **subcategories** should be updated (**not products**)
