### ISSUE TITLE
Unable to place order 

### ISSUE THREAD

**Issue by razzul** [DivanteLtd/vue-storefront#3628]
<div class="text-center p-3">
          <span class="border-wrap"><img src="/razzul/img/blob/master/order-failed.gif?raw=true" alt="order-failed.gif"></span>
      </div>

**Comment by andrzejewsky** [comment]
@razzul thanks for reporting, and really nice video (it shows basically everything developers need) 👍 @gibkigonzo look at sending data to the API, it might be just wrong format

**Comment by pkarw** [comment]
@razzul are you using our demo-magento2.vuestorefont instance or your own?

**Comment by pkarw** [comment]
Hi @razzul I can't reproduce this error on `demo-magento2.vuestorefront.io` backend
https://www.dropbox.com/s/iei0mf3c0teter6/Screenshot%202019-09-27%2012.59.20.png?dl=0

Please do check the `vue-storefront-api` error log for more info. When there is no error message from the `api/order/create` endpoint it's probably a Magento2 related issue - maybe magento logs will be helpfull as well

https://github.com/DivanteLtd/vue-storefront-api/blob/6038563590fd0ae5c3887bb6500cb4abf2204071/src/api/order.js#L80

**Comment by razzul** [comment]
> @razzul are you using our demo-magento2.vuestorefont instance or your own?

My own, its working after doing these changes.

<div class="text-center p-3">
          <span class="border-wrap"><img src="/razzul/img/blob/master/change-payment-settings.gif?raw=true" alt="change-payment-settings.gif"></span>
      </div>
