### ISSUE TITLE
Add integration with Nosto recommendations

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#363]
It should be added as separate extension sending data to Nosto and then back - generating products widget

If some test-instance of nosto required - please ask @pkarw or @karolbzik will provide you with some test credentials

It probably requires to add `vue-storefront-api` method for generating the products feed in Nosto accepted format

**Comment by janmyszkier** [comment]
additional note:
Accordign to:
https://help.nosto.com/settings-and-troubleshooting-faq/tools-faq/understanding-the-product-update-and-creation-process
nosto does not REQUIRE any feed, and it should be installed on backend (e.g Magento) side if we need any updates based on the events.
the integration is therefore down to JUST adding the script with the identifier which should make it even easier to complete.

**Comment by Devors** [comment]
I can add it, if I correctly connect nosto
I do it in head part of `src/index.template.html` like:
`<script src="//connect.nosto.com/include/key" async></script>`

**Comment by pkarw** [comment]
https://github.com/Nosto/techdocs/wiki/SPA:-Implementation-Guide

**Comment by pkarw** [comment]
https://github.com/Nosto/techdocs/wiki/Updating-products-using-the-Products-API

**Comment by janmyszkier** [comment]
@pkarw I tihnk this can now be covered with their official implementation:
https://marketplace.magento.com/nosto-module-nostotagging.html#product.info.details.release_notes
