### ISSUE TITLE
cart sync not working

### ISSUE THREAD

**Issue by undefinederror** [DivanteLtd/vue-storefront#3632]
## Current behavior
I have added two products on my local Magento instance while being logged in.
I log into VSF and I don't see the items in the cart.
The items do show up in the `api/cart/pull` response, sometimes.
## Steps to reproduce the issue
Sorry the gif is long, magento takes forever to respond 
![cartsync](https://user-images.githubusercontent.com/8209966/65698555-fc999180-e07c-11e9-9002-29cb1fc9c37b.gif)

## Expected behavior
Cart on client should reflect what on server (I think)
## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Environment details
- Browser: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
- OS: Windows 10 Pro 1809
- Node: v10.16.3
- Code Version: VSF 1.10.3 / VSF-API 1.10.0

**Comment by undefinederror** [comment]
If it can help, these are the two items that are supposed to show up in cart

![image](https://user-images.githubusercontent.com/8209966/65700056-4f744880-e07f-11e9-9d55-69217657e2ba.png)

Let me know if I can provide more info

**Comment by pkarw** [comment]
@undefinederror would you be so kind and test this scenario on “develop” branch?

**Comment by undefinederror** [comment]
Of course!

![image](https://user-images.githubusercontent.com/8209966/65761813-e1cc2900-e11f-11e9-874b-ff12602d6d3b.png)

Seems like the "list" action returns no items, so nothing is added to client cart.
That sku doesn't look right, does it?
![image](https://user-images.githubusercontent.com/8209966/65762119-8babb580-e120-11e9-8419-f6f369bef961.png)

Could it be concatenating sku from all these "subproducts"?
![image](https://user-images.githubusercontent.com/8209966/65762673-da0d8400-e121-11e9-8dcf-a9b0a24f3c29.png)

Let me know if I can be more helpful

**Comment by undefinederror** [comment]
I just removed that one item, and now the cart syncs
![image](https://user-images.githubusercontent.com/8209966/65762949-85b6d400-e122-11e9-9442-07d54576bb7d.png)

**Comment by undefinederror** [comment]
I have re-added the item from VSF, I can see it in cart
![image](https://user-images.githubusercontent.com/8209966/65763467-cb27d100-e123-11e9-973f-4a8a8fd20c02.png)

`cart/update` payload has the short sku
![image](https://user-images.githubusercontent.com/8209966/65763568-ff02f680-e123-11e9-8489-1c8fdac83077.png)

response has the long sku
![image](https://user-images.githubusercontent.com/8209966/65763619-19d56b00-e124-11e9-9684-49dd841d9a8b.png)

If I log in from and incognito tab I now see only the other item (being now first in the `cart/pull` it is added to the client cart before the long sku item fails)
![image](https://user-images.githubusercontent.com/8209966/65763793-76388a80-e124-11e9-9fa3-144cfc9dc016.png)
And somehow totals don't add up.

So I think now the issue can at least be isolated to "configurable products"?

**Comment by pkarw** [comment]
Yeah, we  can't sync the bundle products this way - they never exist in the Elastic; it shouldn't cause the error though; it was introduced with Vuex refactor of cart sync in 1.10 and got fixed by @andrzejewsky in 1.11 and now needs to be ported to 1.10

**Comment by pkarw** [comment]
currently, when the sync proces is interupted (by bundle product) the totals won't be also summed up we must better support exceptions in the `cart/merge`

**Comment by andrzejewsky** [comment]
@undefinederror Did you use the newest develop branch? Because very similar issue was fixed yesterday, basically in the same place.

**Comment by pkarw** [comment]
Hint: check if the [`getProductVariant`](https://github.com/DivanteLtd/vue-storefront/blob/fd23a49d633b07134da4eaa25aa12379e2166f42/core/modules/cart/store/actions/productActions.ts#L17) is in `try/catch` if not - then you need to fetch latest develop

**Comment by undefinederror** [comment]
I just checked out to develop this morning around 1:30 hrs ago, version 1.11.0-rc.1
getProductVariant has **no** try/catch

I'll have a better look in a couple of hours, after lunch.
Thank you for replying so quickly

**Comment by pkarw** [comment]
it should look like this:

```js
  async getProductVariant ({ dispatch }, { serverItem }) {
    try {
      const options = await dispatch('findProductOption', { serverItem })
      const singleProduct = await dispatch('product/single', { options, assignDefaultVariant: true, setCurrentProduct: false, selectDefaultVariant: false }, { root: true })

      return {
        ...singleProduct,
        server_item_id: serverItem.item_id,
        qty: serverItem.qty,
        server_cart_id: serverItem.quote_id,
        product_option: serverItem.product_option || singleProduct.product_option
      }
    } catch (e) {
      return null
    }
  }

```

:) Let us know if we can close this issue and by the same time @gibkigonzo has ported this bugfix to 1.10

**Comment by undefinederror** [comment]
yes, my bad, sorry, I did checkout to develop by I had forgotten to pull :(
I see the try/catch clause now, and the error in console is gone.

So, if I understand correctly, bundle products is something that currently cannot be rendered in client cart when the cart is sync'd from server. Is it something that I should implement myself (though I don't think I can) or is it that is planned to be supported in the future?

In case, can I add a feature request?

**Comment by pkarw** [comment]
Thanks! Would be great if you'll like to implement this feature and raise a Pull Request; we haven't had this feature on our roadmap yet
