### ISSUE TITLE
Test the `runInNewContext: false` in SSR Renderer

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3635]
## What is the motivation for adding / enhancing this feature?

I believe we can save a lot on TTFB (Time to First Byte) by making use of the [`runInNewContext: false`](https://github.com/DivanteLtd/vue-storefront/blob/01a1a0e093c6185a667d5c49e19b0cb77d4880b1/core/scripts/server.js#L28).

Currently, the Renderer is getting the app bundle and re-interprets it with each incoming request. 

Unfortunately, this mode can bring us some new trouble as we're still using some [stateful singletons](https://github.com/DivanteLtd/vue-storefront/issues/2664)

Possible issues:
- `RouteManager` routes getting added multiple times between the requests,
- `i18n` translations messed out between multistore requests (`/de` - `/ie`)
- `storage.ts` in-memory cache is currently a singleton

We'd need to remove the reference to internal singleton based hash/collections to per-request context using some kind of common helper

Let's say replacing:

https://github.com/DivanteLtd/vue-storefront/blob/01a1a0e093c6185a667d5c49e19b0cb77d4880b1/core/lib/router-manager.ts#L5

```js
const RouterManager = {
  _registeredRoutes: new Array<RouteConfig>(),
...
 this._registeredRoutes.push(...uniqueRoutes)
```

to kind of:

```js
import { requestContext } from '@vue-storefront/core/helpers/requestContext'
requestContext('registeredRoutes).push(...uniqueRoutes)
```

**Comment by pkarw** [comment]
@gibkigonzo and @andrzejewsky I need your thougths on that :)

**Comment by pkarw** [comment]
I've shortly testedd it out - it given me a lot of `duplicated getters` issues; doesn't seem to be easy to fix; first we must ensure it's worth further investigation by doing some trace/New Relic profiling

**Comment by andrzejewsky** [comment]
@pkarw in my opinion, one person can spare one day for testing it, do some measurement as well, try to solve araised issues and decide, worth or not. What do you think?

**Comment by pkarw** [comment]
I've quickly checked it out and the amount of changes required for this option to work is way too big to justify by the results
