### ISSUE TITLE
Language not changing, its only redirecting to base url

### ISSUE THREAD

**Issue by razzul** [DivanteLtd/vue-storefront#3639]
<div class="text-center p-3">
          <span class="border-wrap"><img src="/razzul/img/blob/master/change-lang.gif?raw=true" alt="change-lang.gif"></span>
      </div>

As you can see, its only populating config.i18n default information, also there is no option to provide multiple i18n details to populate in modal.

**Comment by gibkigonzo** [comment]
It should work, it's probably related to your config. Can you check if in `storeViews` specific lang config is set to disabled?
For example:
```
  "storeViews": {
    "multistore": true,
    "de": {
      "disabled": true,
```
It should be set on false to work properly

**Comment by pkarw** [comment]
I can't reproduce this one. Please @razzul check the @gibkigonzo suggestion and let us know if it helped

**Comment by razzul** [comment]
> true

Hi @gibkigonzo here is my congif:

```json
"storeViews": {
      "multistore": false,
      "commonCache": true,
      "mapStoreUrlsFor": ["de", "it"],
      "de": {
        "storeCode": "de",
        "disabled": true,
        "storeId": 3,
        "name": "German Store",
        "url": "/de",
        "appendStoreCode": true,
        "elasticsearch": {
          "host": "/api/catalog",
          "index": "vue_storefront_catalog_de"
        },
```

**Comment by razzul** [comment]
Could you please guide me how to setup vue storefront for 2 languages 
1. en-US-USD
2. de-DE-EUR

**Comment by gibkigonzo** [comment]
I think we should remove `disabled` flag from config. It's misleading because it's used only in language switcher and while building messages json. It's not used in multistore. Maybe simpler solution is just check if specific storeView exist, for example:
```
const isLangAvailable = (storeCode) => {
  return isObject(config.storeViews[storeCode])
}
```
@pkarw, wdyt?

@razzul Probably just set `disabled` to `false` and it should work fine.

**Comment by razzul** [comment]
Hi @gibkigonzo, now I am able to see the language options for German and Italy 

<div class="text-center p-3">
          <span class="border-wrap"><img src="/razzul/img/blob/master/lang.gif?raw=true" alt="lang.gif"></span>
      </div>

But on clicking on German or Italy I am getting error

**Comment by Danail-Irinkov** [comment]
I am also having issue with creating additional stores. Can you please point us to a repository where multiple stores are deployed?

**Comment by crveniOrao** [comment]
Hello, I'm having the same issue, I cannot open /de route, it just leads to the error page, is there any more detailed tutorial on this? I use Magento2 as a backend.

**Comment by gibkigonzo** [comment]
@crveniOrao multistore is refactored on develop branch. If you use current vsf1 version then you can apply those changes to make it work
https://github.com/vuestorefront/vue-storefront/pull/5043
https://github.com/vuestorefront/vue-storefront/pull/5263
