### ISSUE TITLE
Custom category filter

### ISSUE THREAD

**Issue by mateuszrusyn** [DivanteLtd/vue-storefront#3652]
## Prerequisites
- [x] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

I've tried to add custom category filter (type, manufacturer). 
I added filters in local.json:

` "defaultFilters": ["color", "size", "price", "manufacturer", "type"],`

and in elastic.schema.product.json

`"manufacturer": {"type": "integer"},
       "type": {"type": "integer"},`

After that, I did DB rebuild & migrate.

I've used console.log in Category page:

`console.log(this.filters.available)`

and still get only default attributes (size, color, price).

Is there any other step to do to include it category filters?

**Comment by andrzejewsky** [comment]
@mateuszrusyn I'm not to sure but.. try to remove 'attribute' from `ssr.initialStateFilter` config option. @pkarw do you know how to solve this?

**Comment by pkarw** [comment]
@mateuszrusyn please make sure you’ve added “manufacturer” field to the config.entities.product*.includeFields so it will be fetched from the elastic. Please also make sure you’ve restarted elastic.

If none of those help the. Please paste a content elastic is returning from the /api/catalog/..../product/_search endpoint (in the network tab)

I’m also not sure which version of VS are you using? 1.10 (master) or 1.11 (develop)?

**Comment by vineeth030** [comment]
@mateuszrusyn Please let me know how you solved this issue.

**Comment by khouleman** [comment]
@mateuszrusyn Please let me know how you solved this issue.
