### ISSUE TITLE
Multiple `prepareStoreView` calls overwrites existing store-view config incorrectly 

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront#3655]
## Current behavior

If the `prepareStoreView` method is called multiple times after another, it overwrites the existing config with a plain store object if using `extend` to extend the current store.
After the first call, the `extend` property of the `StoreView` object is gone and then the `getExtendedStoreviewConfig` method merges wrong configs on second run.

This happens for example since in the new search adapter `core/lib/search/adapter/api/searchAdapter.ts:42` when it calls `prepareStoreView` method the second time.

It seems that it is caused by `delete storeView.extend` in the `getExtendedStoreviewConfig` method. If I remove this line, everything works as expected.

## Expected behavior

Show the correctly extended store view config, no matter how often it is prepared.

## Steps to reproduce the issue

* Enable multi-store environment with using `extend` on a store-view
* Log the store-view result of `prepareStoreView` method
* Load the store which is using the `extend` config
* On first method call it's correctly extended (Client-Log)
* On the second, e.g. called by `core/lib/search/adapter/api/searchAdapter.ts`, it's a plain one without the `extend` config value so it can't extend the configs correctly anymore

## Repository

develop:latest 8e3628937559ba659744ff47955829b575f2ae3b

## Can you handle fixing this bug by yourself?

- [x] YES (I try)
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 
- OS: OSX 
- Node: 10 LTS 
- Code Version: develop:latest

**Comment by cewald** [comment]
So, if I remove the `storeView.extend` code in `getExtendedStoreviewConfig` it is working:
```javascript
function getExtendedStoreviewConfig (storeView: StoreView): StoreView {
  if (storeView.extend) {
    const originalParent = storeView.extend

    if (!config.storeViews[originalParent]) {
      Logger.error(`Storeview "${storeView.extend}" doesn't exist!`)()
    } else {
      storeView = merge(
        {},
        getExtendedStoreviewConfig(config.storeViews[originalParent]),
        storeView
      )
    }
  }

  return storeView
}
```

I don't see the need of this two lines anyway when we are using `lodash-es/merge` in this order.
Should I open a PR without this lines or are there any doubts?

**Comment by pkarw** [comment]
hi, @cewald thanks for that one! @andrzejewsky was fixing pretty much similar issue; @andrzejewsky please look at this one

**Comment by andrzejewsky** [comment]
@cewald yeah you are right, it works without that line, thanks! (Sorry I was faster with the PR 😃 )
