### ISSUE TITLE
VSF freezes after selecting the checkbox "Use my company's address details".

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3656]
## Current behavior
VSF freezes after selecting the checkbox "Use my company's address details"

## Expected behavior
Company address details should be copied.

## Steps to reproduce the issue
1. Log in
2. Go to My Account
3. Switch to My shipping details tab
4. Press _Edit your shipping details_ 
5. Select the checkobox _Use my company's address details_ 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by ArturDivante** [comment]
Fixed correctly on develop
