### ISSUE TITLE
Inconsistent behaviour of multistore on next.storefrontloud.io

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#3659]
## Steps to reproduce the issue
1. Open https://next.storefrontcloud.io/it
2. Open https://next.storefrontcloud.io/de
3. Click on language selector in the footer

## Current behavior
/de shop opens from the link, but with content patrially in german, partially in english. 
/it shop returns "something went wrong" error. 
language selector opened from /de store contains only 1 option
![nextDe](https://user-images.githubusercontent.com/47415585/65877972-36c0a700-e38d-11e9-9955-91d82e4f8297.png)

## Expected behavior
If multistore is correctly enabled, then:
/de shop should contain all existing translations AND /it shop should correctly open, AND  language selector should contain all available options

if multistore is disabled, then /de shop should not be accessible

## Additional info
Problem seems to be either in config on next, or deployed version. During local test on release branch, behaviour of multistore is correct and consistent. 

## Repository
next.storefrontcloud.io

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: latest Chrome
- OS: Ubuntu, Win10
- Code Version: release/1.11

**Comment by alinadivante** [comment]
@andrzejewsky please change the addresses of static pages in the default store
from http://localhost:3000/about-us to http://localhost:3000/i/about-us
http://localhost:3000/i/customer-service http://localhost:3000/customer-service

**Comment by pkarw** [comment]
@andrzejewsky seemingly it's a mix of the other issues we already fixed in 1.11 and not yet in 1.10; maybe we should at first priority prepare 1.11 to the release and then fix this one in 1.10 by just backporting some fixes from 1.11; however if there is easier/other fix for this one please apply

**Comment by andrzejewsky** [comment]
@ArturDivante please set `false` for `enabled` option in the config file under the particular stores sections, and these languages will appear
