### ISSUE TITLE
This site can't be reached ( in mobile)

### ISSUE THREAD

**Issue by razzul** [DivanteLtd/vue-storefront#3668]
## Current behavior
I have hosted vue-storefront in my server which I can access from desktop but while I try to access from mobile it is not accessible 

<div class="text-center p-3">
          <span class="border-wrap"><img src="/razzul/img/blob/master/Screenshot_2019-10-01-11-51-22-373_com.android.chrome.png?raw=true" alt="Screenshot_2019-10-01-11-51-22-373_com.android.chrome.png"></span>
      </div>

## Expected behavior
It should be accessable as it is for desktop 

## Steps to reproduce the issue
Go to your mobile browser and open http://karmickdev.com:3001/

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details

- Browser: Chrome Mobile
- OS: Android 9
- Node: v10.16.0
- Code Version: Master

**Comment by pkarw** [comment]
Seems like some issue with devops/server configuration rather than VSF core

**Comment by razzul** [comment]
Hi @pkarw could you please guide me how to fix these issue

**Comment by razzul** [comment]
Issue solved, it was server related issue 
Thanks
