### ISSUE TITLE
Modal popup for static contents

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#367]
There should be an option to display static pages in the modal popup. Would be very useful for "Terms and conditions" in the checkout (right now it opens the URL which takes the user back from the checkout, not good for conversion rate).

**Comment by karolbzik** [comment]
First - @collymore thanks for the suggestion for the feature.

<img width="1440" alt="pop-up with content" src="https://user-images.githubusercontent.com/18116406/33652144-9326bd20-da68-11e7-8347-b9247bc47921.png">

**Comment by pkarw** [comment]
Looking good @mercs600 thanks! Closing the issue
