### ISSUE TITLE
Make cart design consistent for all types of products

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#3673]
## What is the motivation for adding / enhancing this feature?
After introducing possibility to edit product properties (color, size) from cart level, product box for them was redesigned - quantity field, remove button etc. were moved to new positions. 

However, for products that don't have such options, old design is still in use. So in case you have both types of products in cart at the same time, layout of fields and buttons looks inconsistent and might be confusing.  

![design](https://user-images.githubusercontent.com/47415585/65967583-229aa980-e462-11e9-8d8a-94d31c7e34ea.png)

## What are the acceptance criteria 
Layout of productbox in cart (inlcuding quantity fields, remove buttons etc. is consistent for all types of products. It might be a good idea to ask @StasiekDivante to prepare a design? :)

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
seems like UI bug - and pretty easy to fix
