### ISSUE TITLE
Login components shows up after Logging out

### ISSUE THREAD

**Issue by jakubmakielkowski** [DivanteLtd/vue-storefront#3680]
## Current behavior
Login component pops up when it should not. It shows in some cases when **logging out**.

## Expected behavior
After logout no Login component shows up.

## Steps to reproduce the issue
1. Log in
2. Open left SidebarMenu
3. Navigate to "My Account"
4. Click Log out in this menu
5. Now Login components Popup. It is propably fired because router treis to navigate to protected route /my-acount when logging out.

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [X] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome 77
- OS: LInux, Ubuntu 18

## Additional information
When removing commiting "ui/setSubmenu" from afterRegistration function in [afterRegistration.ts](https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/user/hooks/afterRegistration.ts) it works fine, but there could be some side effects of deleting this code.

**Comment by alinadivante** [comment]
After logging out and reopening the sideMenu, the main view with categories should be displayed. Now it looks like on my screen:
![image](https://user-images.githubusercontent.com/36628922/66317469-dba52c00-e919-11e9-813e-72236525e9cc.png)
