### ISSUE TITLE
Getting specific product in custom component

### ISSUE THREAD

**Issue by mateuszrusyn** [DivanteLtd/vue-storefront#3696]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

# Is there something you don't understand? What is it? Describe it.	
I don't know exactly how to use Vuex getters to get for example, single product object by ID/SKU in component. I want to get specific product using ID in my Vue component.

**Comment by pkarw** [comment]
Hi @mateuszrusyn please use the `product/list` or `product/single` action using the proper SearchQuery filter passed as an argument:

```js
const product_id = 129;
  let searchQuery = new SearchQuery()
      searchQuery = searchQuery.applyFilter({key: 'id', value: {'eq': product_id}})

      return context.dispatch('list', {query: searchQuery, start: 0, size: 1, updateState: false}).then((resp) => {
        if (resp.items.length >= 1) {
          const parentProduct = resp.items[0]
```
