### ISSUE TITLE
Comparison attributes not showing up

### ISSUE THREAD

**Issue by themreza** [DivanteLtd/vue-storefront#3697]
## Current behavior

When you add products to the comparison page, none of the product attributes show up, even though the imported attributes have is_comparable set to true.

## Expected behavior

It should correctly display the attributes marked to be shown in the comparison page.

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version: 

## Additional information

To fix it, change this line https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/compare/components/Compare.ts#L13 to:

```
return Object.values(attributesByCode).filter((a: any) => a.is_comparable === true)
```

**Comment by themreza** [comment]
Why use 1 and 0 when in most of the places type boolean is defined with true/false?

I think this classifies as a bug since according to the development guides, it should return true/false. Also, to adhere to the platform-agnostic guidelines, the system should uniformly follow types defined in ElasticSearch, and not in the proxy APIs (like vue-storefront-api).

Inconsistency:

https://github.com/DivanteLtd/vue-storefront-integration-sdk/blob/bf4c38771c574802159201aa62a04da6364c35eb/Format-attribute.md

vs.

https://github.com/DivanteLtd/vue-storefront-integration-sdk/blob/9093963a3c690f9ee9826c4e0c99a29afc6d8696/Dynamic%20API%20specification.md

**Comment by ThomasBaier** [comment]
So actually you are right, magento standard 1 & 2 are using true / false for there variables.

return Object.values(attributesByCode).filter((a: any) => a.is_comparable===true)
would be a good solution. 

unfortunately standard data of https://test.storefrontcloud.io is not representative with 0 1 data format.

**Comment by pkarw** [comment]
@andrzejewsky
