### ISSUE TITLE
Migration documentation

### ISSUE THREAD

**Issue by CompactCodeEU** [DivanteLtd/vue-storefront#3700]
With the new releases following up pretty fast it might be good to complete this documentation about migration :

https://github.com/DivanteLtd/vue-storefront/blob/master/docs/guide/cookbook/migration.md

**Comment by pkarw** [comment]
@kkdg is working on this; however he's on honeymoon right now :)

**Comment by pkarw** [comment]
Plus: https://medium.com/the-vue-storefront-journal/vue-storefront-1-11-and-the-roadmap-update-edb7ca939238
