### ISSUE TITLE
Add to cart notification is in the wrong language

### ISSUE THREAD

**Issue by ResuBaka** [DivanteLtd/vue-storefront#3716]
## Current behavior

When you add an product in the german store to the cart it shows an english message in the notification. 

![image](https://user-images.githubusercontent.com/15260832/66749984-858d3700-ee8b-11e9-9836-fe29843ded50.png)

## Expected behavior

Show german text in the notification. 

## Steps to reproduce the issue

1. got to here https://next.storefrontcloud.io/de/men/tops-men/tees-men/tees-16/balboa-persistence-tee-531.html?childSku=MS03-XS-Gray
2. Add the product to cart
3. See english message in the top right corner

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 77.*
- OS: 
- Node: 
- Code Version: 1.11 Release branch

## Additional information

When you look into the core/modules/cart/helpers/notifications.ts file here the notifications are created and at the point of creation the language is english so the notification is english and not german.

**Comment by nhp** [comment]
It looks like it is not just a thing of notifications but maybe something more general? It looks like in some cases that `$t()` is not working as expected.
Attached image shows wrong translations for prices (bottom) account/cart stuff (top right). 
The translations for top left are normally covered by this code: 
```<div class="inline-flex relative">
  <button type="button" class="bg-cl-transparent header-btn brdr-none pl5" @click="logout" v-if="isUserAuthenticated">
    {{ $t('Logout') }}
  </button>
  <button type="button" class="bg-cl-transparent header-btn brdr-none pl5" @click="handleLogin" v-else>
    {{ $t('Login') }}
  </button>
</div>
```
 For the topmost occurence (the cookie disclaimer within the grey box atop) we use this component code: 
```<transition name="fade" appear>
  <div class="w-100" v-if="isOpen">
    <div id="cookie-disclaimer">
      <span class="message">{{ $t('We use cookies to give you the best shopping experience.') }}
        <a class="link" :href="$t('/privacy-policy')" target="_blank">{{ $t('See details') }}</a>
        <a class="ok-button no-underline" id="okbutton" @click="accept">OK</a>
      </span>
      <div class="dismiss" id="xbutton" @click="dismiss">
        X
      </div>
    </div>
  </div>
</transition>
```

![image](https://user-images.githubusercontent.com/512911/67008930-d5b60480-f0ea-11e9-9c6f-53d03a48133e.png)

**Comment by pkarw** [comment]
@andrzejewsky

**Comment by gibkigonzo** [comment]
@nhp Which version do you use? This can occur in version `1.10.3` if in particular storeView config there is `disabled` flag set on `true`.

**Comment by ResuBaka** [comment]
@gibkigonzo He is part of the project so same version as the issue has in the description.
