### ISSUE TITLE
reviews for configurable product missing in product page

### ISSUE THREAD

**Issue by undefinederror** [DivanteLtd/vue-storefront#3735]
## Current behavior
When going from catalog to product page, reviews are not shown on product page unless the item is a simple product.
After refresh on product page, reviews are shown.

## Expected behavior
Reviews should show up either way

## Steps to reproduce the issue
![storefront (2)](https://user-images.githubusercontent.com/8209966/67209777-483f2100-f418-11e9-89ad-3d29af9832fe.gif)

## My 2 cents
AFAIK this happens because in core\modules\catalog\store\product\actions.ts `list()`, if the product is a configurable product it gets merged with a simple product variant.
![image](https://user-images.githubusercontent.com/8209966/67212030-f9938600-f41b-11e9-908f-b55b69bf152d.png).
Thus losing the id of the configurable product, which is what reviews are linked to.
`Product.vue` loads using the provided id (variant) and tries to pass originalProduct.id to `reviews`, although originalProduct has been lost due to the previous merge and it's now just the same as the variant product.
![image](https://user-images.githubusercontent.com/8209966/67212937-6d825e00-f41d-11e9-9e17-4d0792dccb6c.png)

## Can you handle fixing this bug by yourself?
- [ ] YES
- [x] YES BUT BADLY
- [ ] NO

A quick fix would be to save a reference to the configurable product id before merging with the variant
![image](https://user-images.githubusercontent.com/8209966/67214718-82142580-f420-11e9-9eab-ce9b71b038b1.png)
Then pass this if it exists to the review component.
![image](https://user-images.githubusercontent.com/8209966/67214816-ac65e300-f420-11e9-824a-8883e75ac576.png)

This doesn't feel very clean though. If it was for me I would never merge products in `list()` in the first place, it feels very hacky. I have tried to go through the code in actions but man... really, really hard to understand what happens there...

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
- OS: Windows 10 Pro 1809
- Node: v10.16.3
- Code Version: VSF 1.10.3 / VSF-API 1.10.0

**Comment by gibkigonzo** [comment]
I've tested it in 1.11 and it doesn't occur. Probably it happens in 1.10 because on category page is stored wrong product in cache. I will try to fix it for 1.10

**Comment by undefinederror** [comment]
Hi @gibkigonzo ,
Well in 1.11 code seems to be well refactored, also the product object isn't mutated in place, but used to extend an empty object which gets then returned.
![image](https://user-images.githubusercontent.com/8209966/67286765-3e7df200-f4da-11e9-8e4e-767c3ce8c6dd.png)

If this has already been fixed in 1.11 then cool, I guess this can be closed.
