### ISSUE TITLE
Add notification and changes in styles when the app switches to off-line and on-line

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#374]
- Notification when the app goes online -> offline
- Notification when the app goes offline -> online
- Black/white for images which we can't browse while the app is offline
- Changes in the checkout for offline (limited fields, different thank you page)

**Comment by pkarw** [comment]
We won't make it to customize the layout for offline for 0.3.0; Can add the message - but I'm moving it to 0.4.0

**Comment by pkarw** [comment]
We've discussed it and decided to add small "tag" to the top of the page like "offline" - user experienve shouldn't be downgraded when offline

**Comment by pkarw** [comment]
@filrak are you on this maybe?

**Comment by filrak** [comment]
done ;)
