### ISSUE TITLE
Wrong price after first return from product page. 

### ISSUE THREAD

**Issue by dmytrokravch** [DivanteLtd/vue-storefront#3740]
## Current behavior

After visiting the product list page I visit the product detail view page first time - Price there is correct. Then I return to the product list page again and then detail product view - this time I have the wrong price value (looks like it have discount of approximately 10%). this behavior seems to happen only on the second visit of the detail page, First visit and visits thereafter display the correct price.
## Expected behavior

Price should always remain the same 

## Steps to reproduce the issue

set config properties to
"sourcePriceIncludesTax": true,
"calculateServerSide": false
then
1 Load category page. 2 Load product. 3 Back to the category page.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  77.0.3865.120 Chrome
- OS: Windows 10
- Node: 12.13.0
- Code Version: VSF 1.10.4

**Comment by andrzejewsky** [comment]
@gibkigonzo @krskibin can either of you look at this?

**Comment by andrzejewsky** [comment]
@dmytrokravch I've noticed that you mentioned about `calculateServerSide` set to `false` - remember that you have to do it basically in both projects: `vue-storefront` and the `vue-storefront-api` where it must be also set to `false` otherwise you prices will be wrong calculated

**Comment by pkarw** [comment]
@dmytrokravch please provide us with more details about this product you're encountering the issue with; the best would be be to provide us with JSON for this particualr product

**Comment by svenehmer** [comment]
We encountered a similar or same issue regarding the original_price attribute which does not always store the correct value. It does not occure everytime, but quite often if you navigate from the catalog to pdp and back.
Our workaround for it was removing the lines 87 - 89 in taxCalc.ts -> updateProductPrices() as the original_price attribute was re-set with the wrong value.
 
The updateProductPrices method is usually receiving the "raw" product data, where the prices were not updated yet. In that case, the prices get set right. But sometimes the updateProductPrices method is receiving product data with already updated prices. In that case the original_price value will be overwridden with a wrong value.

**Comment by dmytrokravch** [comment]
@andrzejewsky yes, I know. 'calculateServerSide' in both projects set to 'false'.

**Comment by dmytrokravch** [comment]
@pkarw at the front we have only configurable products. Below I send an example of one of such product. Also, I attach its child product. All data originates from elasticSearch.
Configurable one:
`{
  "_index": "vue_storefront_magento_1",
  "_type": "product",
  "_id": "5429",
  "_version": 1,
  "_score": 21.866276,
  "_source": {
    "attribute_set_id": 10,
    "type_id": "configurable",
    "sku": "305000-005-c",
    "id": 5429,
    "name": "Kappa Edward S/S T-Shirt Black (305000-005)",
    "image": "/7/3/7362_1_2.jpg",
    "small_image": "/7/3/7362_1_2.jpg",
    "thumbnail": "/7/3/7362_1_2.jpg",
    "options_container": "container2",
    "image_label": "7362_1",
    "small_image_label": "7362_1",
    "thumbnail_label": "7362_1",
    "msrp_display_actual_price_type": "0",
    "url_key": "kappa-edward-s-s-t-shirt-black-305000-005",
    "gtin": "4056142433608",
    "dostawca": "KAPPA",
    "description": "<p>Kolorystyka: Black<br />Sezon: Wiosna/ Lato 2019<br />Skład: 100% Bawełna</p>",
    "short_description": "Kolorystyka: Black\nSezon: Wiosna/ Lato 2019\nSkład: 100% Bawełna",
    "price": 69.99,
    "status": 1,
    "visibility": 4,
    "tax_class_id": 2,
    "brand": 4126,
    "sex": 4733,
    "color": 87,
    "main_product": 0,
    "color_aggregated": 4682,
    "year": 4696,
    "slug": "kappa-edward-s-s-t-shirt-black-305000-005",
    "url_path": "kappa-edward-s-s-t-shirt-black-305000-005",
    "category": [
      {
        "category_id": 16,
        "name": "Wszystkie produkty",
        "position": 0
      },
      {
        "category_id": 323,
        "name": "KAPPA",
        "position": 0
      },
      {
        "category_id": 338,
        "name": "Męskie",
        "position": 0
      },
      {
        "category_id": 340,
        "name": "Odzież",
        "position": 0
      },
      {
        "category_id": 345,
        "name": "Koszulki",
        "position": 0
      }
    ],
    "category_ids": [
      16,
      323,
      338,
      340,
      345
    ],
    "final_price": 69.99,
    "regular_price": 69.99,
    "media_gallery": [
      {
        "typ": "image",
        "image": "/7/3/7362_1_2.jpg",
        "lab": "7362_1",
        "pos": 1
      },
      {
        "typ": "image",
        "image": "/7/3/7362_2_1.jpg",
        "lab": "7362_2",
        "pos": 2
      },
      {
        "typ": "image",
        "image": "/7/3/7362_3_1.jpg",
        "lab": "7362_3",
        "pos": 3
      }
    ],
    "product_links": [],
    "stock": {
      "item_id": 70883,
      "stock_id": 1,
      "qty": 0,
      "is_in_stock": true,
      "is_qty_decimal": false,
      "use_config_min_qty": true,
      "min_qty": 0,
      "use_config_min_sale_qty": true,
      "min_sale_qty": 1,
      "use_config_max_sale_qty": true,
      "max_sale_qty": 10000,
      "use_config_notify_stock_qty": true,
      "notify_stock_qty": 0,
      "use_config_qty_increments": true,
      "backorders": false,
      "use_config_backorders": true,
      "qty_increments": 1,
      "use_config_enable_qty_inc": true,
      "enable_qty_increments": false,
      "use_config_manage_stock": false,
      "manage_stock": true,
      "low_stock_date": null,
      "stock_status": 1
    },
    "configurable_options": [
      {
        "attribute_id": 145,
        "attribute_code": "size",
        "label": "Size",
        "values": [
          {
            "value_index": "4676",
            "label": "L"
          },
          {
            "value_index": "4677",
            "label": "M"
          },
          {
            "value_index": "4678",
            "label": "S"
          },
          {
            "value_index": "4680",
            "label": "XL"
          },
          {
            "value_index": "4681",
            "label": "XXL"
          }
        ]
      }
    ],
    "configurable_children": [
      {
        "sku": "305000-005@L",
        "name": "Kappa Edward S/S T-Shirt Black (305000-005) L",
        "price": 69.99,
        "special_price": 49.99,
        "special_from_date": "2019-10-22 12:44:46",
        "special_to_date": "2020-10-22 12:44:46",
        "status": 1,
        "visibility": 1,
        "size": 4676,
        "id": 5424,
        "regular_price": 69.99,
        "stock": {
          "is_in_stock": true,
          "min_qty": 0,
          "notify_stock_qty": 0,
          "use_config_notify_stock_qty": true,
          "qty": 4,
          "stock_status": 1
        }
      },
      {
        "sku": "305000-005@M",
        "name": "Kappa Edward S/S T-Shirt Black (305000-005) M",
        "price": 69.99,
        "special_price": 49.99,
        "special_from_date": "2019-10-22 12:44:46",
        "special_to_date": "2020-10-22 12:44:46",
        "status": 1,
        "visibility": 1,
        "size": 4677,
        "id": 5425,
        "regular_price": 69.99,
        "stock": {
          "is_in_stock": true,
          "min_qty": 0,
          "notify_stock_qty": 0,
          "use_config_notify_stock_qty": true,
          "qty": 3,
          "stock_status": 1
        }
      },
      {
        "sku": "305000-005@S",
        "name": "Kappa Edward S/S T-Shirt Black (305000-005) S",
        "price": 69.99,
        "special_price": 49.99,
        "special_from_date": "2019-10-22 12:44:46",
        "special_to_date": "2020-10-22 12:44:46",
        "status": 1,
        "visibility": 1,
        "size": 4678,
        "id": 5426,
        "regular_price": 69.99,
        "stock": {
          "is_in_stock": true,
          "min_qty": 0,
          "notify_stock_qty": 0,
          "use_config_notify_stock_qty": true,
          "qty": 1,
          "stock_status": 1
        }
      },
      {
        "sku": "305000-005@XL",
        "name": "Kappa Edward S/S T-Shirt Black (305000-005) XL",
        "price": 69.99,
        "special_price": 49.99,
        "special_from_date": "2019-10-22 12:44:46",
        "special_to_date": "2020-10-22 12:44:46",
        "status": 1,
        "visibility": 1,
        "size": 4680,
        "id": 5427,
        "regular_price": 69.99,
        "stock": {
          "is_in_stock": true,
          "min_qty": 0,
          "notify_stock_qty": 0,
          "use_config_notify_stock_qty": true,
          "qty": 1,
          "stock_status": 1
        }
      },
      {
        "sku": "305000-005@XXL",
        "name": "Kappa Edward S/S T-Shirt Black (305000-005) XXL",
        "price": 69.99,
        "special_price": 49.99,
        "special_from_date": "2019-10-22 12:44:46",
        "special_to_date": "2020-10-22 12:44:46",
        "status": 1,
        "visibility": 1,
        "size": 4681,
        "id": 5428,
        "regular_price": 69.99,
        "stock": {
          "is_in_stock": true,
          "min_qty": 0,
          "notify_stock_qty": 0,
          "use_config_notify_stock_qty": true,
          "qty": 2,
          "stock_status": 1
        }
      }
    ],
    "size_options": [
      4676,
      4677,
      4678,
      4680,
      4681
    ],
    "tsk": 1571748589
  },
  "fields": {
    "configurable_children.special_from_date": [
      1571748286000,
      1571748286000,
      1571748286000,
      1571748286000,
      1571748286000
    ],
    "configurable_children.special_to_date": [
      1603370686000,
      1603370686000,
      1603370686000,
      1603370686000,
      1603370686000
    ]
  },
  "highlight": {
    "configurable_children.name": [
      "Kappa Edward S/S T-Shirt Black (@kibana-highlighted-field@305000@/kibana-highlighted-field@-@kibana-highlighted-field@005@/kibana-highlighted-field@) L",
      "Kappa Edward S/S T-Shirt Black (@kibana-highlighted-field@305000@/kibana-highlighted-field@-@kibana-highlighted-field@005@/kibana-highlighted-field@) M",
      "Kappa Edward S/S T-Shirt Black (@kibana-highlighted-field@305000@/kibana-highlighted-field@-@kibana-highlighted-field@005@/kibana-highlighted-field@) S",
      "Kappa Edward S/S T-Shirt Black (@kibana-highlighted-field@305000@/kibana-highlighted-field@-@kibana-highlighted-field@005@/kibana-highlighted-field@) XL",
      "Kappa Edward S/S T-Shirt Black (@kibana-highlighted-field@305000@/kibana-highlighted-field@-@kibana-highlighted-field@005@/kibana-highlighted-field@) XXL"
    ],
    "name": [
      "Kappa Edward S/S T-Shirt Black (@kibana-highlighted-field@305000@/kibana-highlighted-field@-@kibana-highlighted-field@005@/kibana-highlighted-field@)"
    ]
  }
}`
its child: 
`{
  "_index": "vue_storefront_magento_2",
  "_type": "product",
  "_id": "5425",
  "_version": 1,
  "_score": 22.01842,
  "_source": {
    "attribute_set_id": 9,
    "type_id": "simple",
    "sku": "305000-005@M",
    "id": 5425,
    "name": "Kappa Edward S/S T-Shirt Black (305000-005) M",
    "url_key": "kappa-edward-s-s-t-shirt-black-305000-005-m",
    "gtin": "4056142433592",
    "dostawca": "KAPPA",
    "price": 69.99,
    "special_price": 49.99,
    "special_from_date": "2019-10-22 12:44:46",
    "special_to_date": "2020-10-22 12:44:46",
    "status": 1,
    "visibility": 1,
    "tax_class_id": 2,
    "brand": 4126,
    "sex": 4733,
    "size": 4677,
    "year": 4696,
    "rodzaj": 4711,
    "slug": "kappa-edward-s-s-t-shirt-black-305000-005-m",
    "category": [
      {
        "category_id": 16,
        "name": "All categories",
        "position": 0
      },
      {
        "category_id": 323,
        "name": "KAPPA",
        "position": 0
      },
      {
        "category_id": 338,
        "name": "Men's",
        "position": 0
      },
      {
        "category_id": 340,
        "name": "Clothing",
        "position": 0
      },
      {
        "category_id": 345,
        "name": "T-shirts",
        "position": 0
      }
    ],
    "category_ids": [
      16,
      323,
      338,
      340,
      345
    ],
    "final_price": 49.99,
    "regular_price": 69.99,
    "media_gallery": [],
    "product_links": [],
    "stock": {
      "item_id": 70879,
      "stock_id": 1,
      "qty": 3,
      "is_in_stock": true,
      "is_qty_decimal": false,
      "use_config_min_qty": true,
      "min_qty": 0,
      "use_config_min_sale_qty": true,
      "min_sale_qty": 1,
      "use_config_max_sale_qty": true,
      "max_sale_qty": 10000,
      "use_config_notify_stock_qty": true,
      "notify_stock_qty": 0,
      "use_config_qty_increments": true,
      "backorders": false,
      "use_config_backorders": true,
      "qty_increments": 1,
      "use_config_enable_qty_inc": true,
      "enable_qty_increments": false,
      "use_config_manage_stock": true,
      "manage_stock": false,
      "low_stock_date": null,
      "stock_status": 1
    },
    "configurable_children": [],
    "tsk": 1571748589
  },
  "fields": {
    "special_from_date": [
      1571748286000
    ],
    "special_to_date": [
      1603370686000
    ]
  },
  "highlight": {
    "name": [
      "Kappa Edward S/S T-Shirt Black (@kibana-highlighted-field@305000@/kibana-highlighted-field@-@kibana-highlighted-field@005@/kibana-highlighted-field@) M"
    ]
  }
}`
