### ISSUE TITLE
I need to return a json response in a route

### ISSUE THREAD

**Issue by Ravin0319** [DivanteLtd/vue-storefront#3743]
I need a route in my vuestorefront to return JSON response. (I'm not using vuestorefront api in my Project)

route:-
www.example.com/apple-app-site-association

examples:-
https://www.goldenscent.com/en/apple-app-site-association
https://www.noon.com/apple-app-site-association

In the above links Please check 'View Page Source' and 'Network Tab' for some details.

The link needs to return a JSON Object for the App's Universal Deep Linkings.

In the router/index.js i created the route but the issue is the component (I don't want to load a .vue file, just simply throw back the JSON on screen for one route.)

Is there a way i can do this? 

Please suggest

**Comment by pkarw** [comment]
Hi there! This might be helpfull: https://docs.vuestorefront.io/guide/core-themes/layouts.html

**Comment by Ravin0319** [comment]
Thanks @pkarw 

I was able to achieve this very easily, Just followed the 'Generating the XML output' example in the above link.

**Comment by Deiveson** [comment]
> Thanks @pkarw
> 
> I was able to achieve this very easily, Just followed the 'Generating the XML output' example in the above link.

Post the result please, I need it and I don't know how to do it
