### ISSUE TITLE
Sale price is not shown on category page when `"sourcePriceIncludesTax": true "calculateServerSide": false`

### ISSUE THREAD

**Issue by dmytrokravch** [DivanteLtd/vue-storefront#3750]
## Current behavior

Sale price is shown on category page

## Expected behavior

Show sale price on category page

## Steps to reproduce the issue

set value `sourcePriceIncludesTax` to `true` and `calculateServerSide` to `false` in config
also set  `calculateServerSide` to `false` in `vue-storefront-api`

## Can you handle fixing this bug by yourself?

- [] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
Browser: 77.0.3865.120 Chrome
OS: Windows 10
Node: 12.13.0
Code Version: VSF 1.10.4

## Additional information

 an example of one of sale product with its child:
`{
  "_index": "vue_storefront_magento_1",
  "_type": "product",
  "_id": "571",
  "_version": 3,
  "_score": 26.543175,
  "_source": {
    "attribute_set_id": 10,
    "type_id": "configurable",
    "sku": "1010610-1FG-c",
    "id": 571,
    "name": "Fila Wmn Disruptor Halfsandal White (1010610-1FG)",
    "image": "/6/9/6918_1_2.jpg",
    "small_image": "/6/9/6918_1_2.jpg",
    "thumbnail": "/6/9/6918_1_2.jpg",
    "options_container": "container2",
    "image_label": "6918_1",
    "small_image_label": "6918_1",
    "thumbnail_label": "6918_1",
    "msrp_display_actual_price_type": "0",
    "url_key": "fila-wmn-disruptor-halfsandal-white-1010610-1fg",
    "gift_message_available": false,
    "gtin": "8719477171558",
    "dostawca": "MEDICO",
    "ts_packaging_type": "none",
    "description": "<p>Kolorystyka: White<br />Sezon: Wiosna/ Lato 2019</p>",
    "short_description": "Kolorystyka: White\nSezon: Wiosna/ Lato 2019",
    "price": 389.99,
    "status": 1,
    "visibility": 4,
    "tax_class_id": 2,
    "brand": 4121,
    "sex": 4734,
    "color": null,
    "main_product": 0,
    "color_aggregated": 4684,
    "year": 4696,
    "slug": "fila-wmn-disruptor-halfsandal-white-1010610-1fg",
    "url_path": "fila-wmn-disruptor-halfsandal-white-1010610-1fg",
    "category": [
      {
        "category_id": 320,
        "name": "FILA",
        "position": 0
      },
      {
        "category_id": 337,
        "name": "Damskie",
        "position": 0
      },
      {
        "category_id": 41,
        "name": "Sneakersy",
        "position": 0
      },
      {
        "category_id": 23,
        "name": "Obuwie",
        "position": 0
      },
      {
        "category_id": 16,
        "name": "Wszystkie produkty",
        "position": 0
      }
    ],
    "category_ids": [
      320,
      337,
      41,
      23,
      16
    ],
    "final_price": 389.99,
    "regular_price": 389.99,
    "media_gallery": [
      {
        "typ": "image",
        "image": "/6/9/6918_1_2.jpg",
        "lab": "6918_1",
        "pos": 0
      },
      {
        "typ": "image",
        "image": "/6/9/6918_2_1.jpg",
        "lab": "6918_2",
        "pos": 1
      },
      {
        "typ": "image",
        "image": "/6/9/6918_5_1.jpg",
        "lab": "6918_5",
        "pos": 2
      },
      {
        "typ": "image",
        "image": "/6/9/6918_3_1.jpg",
        "lab": "6918_3",
        "pos": 3
      },
      {
        "typ": "image",
        "image": "/6/9/6918_4_1.jpg",
        "lab": "6918_4",
        "pos": 4
      }
    ],
    "product_links": [],
    "stock": {
      "item_id": 66025,
      "stock_id": 1,
      "qty": 0,
      "is_in_stock": true,
      "is_qty_decimal": false,
      "use_config_min_qty": true,
      "min_qty": 0,
      "use_config_min_sale_qty": true,
      "min_sale_qty": 1,
      "use_config_max_sale_qty": true,
      "max_sale_qty": 10000,
      "use_config_notify_stock_qty": true,
      "notify_stock_qty": 0,
      "use_config_qty_increments": true,
      "backorders": false,
      "use_config_backorders": true,
      "qty_increments": 1,
      "use_config_enable_qty_inc": true,
      "enable_qty_increments": false,
      "use_config_manage_stock": false,
      "manage_stock": true,
      "low_stock_date": null,
      "stock_status": 1
    },
    "configurable_options": [
      {
        "attribute_id": 145,
        "attribute_code": "size",
        "label": "Size",
        "values": [
          {
            "value_index": "4159",
            "label": "36"
          },
          {
            "value_index": "4160",
            "label": "37"
          },
          {
            "value_index": "4162",
            "label": "38"
          },
          {
            "value_index": "4161",
            "label": "39"
          },
          {
            "value_index": "4163",
            "label": "40"
          }
        ]
      }
    ],
    "configurable_children": [
      {
        "sku": "1010610-1FG@36",
        "name": "Fila Wmn Disruptor Halfsandal White (1010610-1FG) 36",
        "price": 389.99,
        "special_price": 289.99,
        "special_from_date": "2019-10-22 12:44:41",
        "special_to_date": "2020-10-22 12:44:41",
        "status": 1,
        "visibility": 1,
        "size": 4159,
        "id": 566,
        "regular_price": 389.99,
        "stock": {
          "is_in_stock": false,
          "min_qty": 0,
          "notify_stock_qty": 0,
          "use_config_notify_stock_qty": true,
          "qty": 0,
          "stock_status": 0
        }
      },
      {
        "sku": "1010610-1FG@37",
        "name": "Fila Wmn Disruptor Halfsandal White (1010610-1FG) 37",
        "price": 389.99,
        "special_price": 289.99,
        "special_from_date": "2019-10-22 12:44:41",
        "special_to_date": "2020-10-22 12:44:41",
        "status": 1,
        "visibility": 1,
        "size": 4160,
        "id": 567,
        "regular_price": 389.99,
        "stock": {
          "is_in_stock": false,
          "min_qty": 0,
          "notify_stock_qty": 0,
          "use_config_notify_stock_qty": true,
          "qty": 0,
          "stock_status": 0
        }
      },
      {
        "sku": "1010610-1FG@38",
        "name": "Fila Wmn Disruptor Halfsandal White (1010610-1FG) 38",
        "price": 389.99,
        "special_price": 289.99,
        "special_from_date": "2019-10-22 12:44:41",
        "special_to_date": "2020-10-22 12:44:41",
        "status": 1,
        "visibility": 1,
        "size": 4162,
        "id": 568,
        "regular_price": 389.99,
        "stock": {
          "is_in_stock": false,
          "min_qty": 0,
          "notify_stock_qty": 0,
          "use_config_notify_stock_qty": true,
          "qty": 0,
          "stock_status": 0
        }
      },
      {
        "sku": "1010610-1FG@39",
        "name": "Fila Wmn Disruptor Halfsandal White (1010610-1FG) 39",
        "price": 389.99,
        "special_price": 289.99,
        "special_from_date": "2019-10-22 12:44:41",
        "special_to_date": "2020-10-22 12:44:41",
        "status": 1,
        "visibility": 1,
        "size": 4161,
        "id": 569,
        "regular_price": 389.99,
        "stock": {
          "is_in_stock": true,
          "min_qty": 0,
          "notify_stock_qty": 0,
          "use_config_notify_stock_qty": true,
          "qty": 1,
          "stock_status": 1
        }
      },
      {
        "sku": "1010610-1FG@40",
        "name": "Fila Wmn Disruptor Halfsandal White (1010610-1FG) 40",
        "price": 389.99,
        "special_price": 289.99,
        "special_from_date": "2019-10-22 12:44:41",
        "special_to_date": "2020-10-22 12:44:41",
        "status": 1,
        "visibility": 1,
        "size": 4163,
        "id": 570,
        "regular_price": 389.99,
        "stock": {
          "is_in_stock": false,
          "min_qty": 0,
          "notify_stock_qty": 0,
          "use_config_notify_stock_qty": true,
          "qty": 0,
          "stock_status": 0
        }
      }
    ],
    "size_options": [
      4159,
      4160,
      4162,
      4161,
      4163
    ],
    "tsk": 1571935915
  },
  "fields": {
    "configurable_children.special_from_date": [
      1571748281000,
      1571748281000,
      1571748281000,
      1571748281000,
      1571748281000
    ],
    "configurable_children.special_to_date": [
      1603370681000,
      1603370681000,
      1603370681000,
      1603370681000,
      1603370681000
    ]
  },
  "highlight": {
    "configurable_children.name": [
      "Fila Wmn Disruptor Halfsandal White (@kibana-highlighted-field@1010610@/kibana-highlighted-field@-@kibana-highlighted-field@1FG@/kibana-highlighted-field@) 36",
      "Fila Wmn Disruptor Halfsandal White (@kibana-highlighted-field@1010610@/kibana-highlighted-field@-@kibana-highlighted-field@1FG@/kibana-highlighted-field@) 37",
      "Fila Wmn Disruptor Halfsandal White (@kibana-highlighted-field@1010610@/kibana-highlighted-field@-@kibana-highlighted-field@1FG@/kibana-highlighted-field@) 38",
      "Fila Wmn Disruptor Halfsandal White (@kibana-highlighted-field@1010610@/kibana-highlighted-field@-@kibana-highlighted-field@1FG@/kibana-highlighted-field@) 39",
      "Fila Wmn Disruptor Halfsandal White (@kibana-highlighted-field@1010610@/kibana-highlighted-field@-@kibana-highlighted-field@1FG@/kibana-highlighted-field@) 40"
    ],
    "name": [
      "Fila Wmn Disruptor Halfsandal White (@kibana-highlighted-field@1010610@/kibana-highlighted-field@-@kibana-highlighted-field@1FG@/kibana-highlighted-field@)"
    ]
  }
}`
its child:
`
{
  "_index": "vue_storefront_magento_1",
  "_type": "product",
  "_id": "569",
  "_version": 2,
  "_score": 24.728062,
  "_source": {
    "attribute_set_id": 9,
    "type_id": "simple",
    "sku": "1010610-1FG@39",
    "id": 569,
    "name": "Fila Wmn Disruptor Halfsandal White (1010610-1FG) 39",
    "options_container": "container2",
    "msrp_display_actual_price_type": "0",
    "url_key": "fila-wmn-disruptor-halfsandal-white-1010610-1fg-39",
    "gtin": "8719477171589",
    "dostawca": "MEDICO",
    "price": 389.99,
    "special_price": 289.99,
    "special_from_date": "2019-10-22 12:44:41",
    "special_to_date": "2020-10-22 12:44:41",
    "status": 1,
    "visibility": 1,
    "tax_class_id": 2,
    "brand": 4121,
    "sex": 4734,
    "size": 4161,
    "color": 87,
    "year": 4696,
    "rodzaj": 4714,
    "slug": "fila-wmn-disruptor-halfsandal-white-1010610-1fg-39",
    "category": [
      {
        "category_id": 320,
        "name": "FILA",
        "position": 0
      },
      {
        "category_id": 337,
        "name": "Damskie",
        "position": 0
      },
      {
        "category_id": 41,
        "name": "Sneakersy",
        "position": 0
      },
      {
        "category_id": 23,
        "name": "Obuwie",
        "position": 0
      },
      {
        "category_id": 16,
        "name": "Wszystkie produkty",
        "position": 0
      }
    ],
    "category_ids": [
      320,
      337,
      41,
      23,
      16
    ],
    "final_price": 289.99,
    "regular_price": 389.99,
    "media_gallery": [],
    "product_links": [],
    "stock": {
      "item_id": 66023,
      "stock_id": 1,
      "qty": 1,
      "is_in_stock": true,
      "is_qty_decimal": false,
      "use_config_min_qty": true,
      "min_qty": 0,
      "use_config_min_sale_qty": true,
      "min_sale_qty": 1,
      "use_config_max_sale_qty": true,
      "max_sale_qty": 10000,
      "use_config_notify_stock_qty": true,
      "notify_stock_qty": 0,
      "use_config_qty_increments": true,
      "backorders": false,
      "use_config_backorders": true,
      "qty_increments": 1,
      "use_config_enable_qty_inc": true,
      "enable_qty_increments": false,
      "use_config_manage_stock": true,
      "manage_stock": false,
      "low_stock_date": null,
      "stock_status": 1
    },
    "configurable_children": [],
    "tsk": 1571935915
  },
  "fields": {
    "special_from_date": [
      1571748281000
    ],
    "special_to_date": [
      1603370681000
    ]
  },
  "highlight": {
    "name": [
      "Fila Wmn Disruptor Halfsandal White (@kibana-highlighted-field@1010610@/kibana-highlighted-field@-@kibana-highlighted-field@1FG@/kibana-highlighted-field@) 39"
    ]
  }
}
`

**Comment by pkarw** [comment]
Related to #3740

**Comment by pkarw** [comment]
Good point. I belive it's worth pushing this change as a Pull Request to the core @dmytrokravch
