### ISSUE TITLE
Incorrect category links on homepage

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#3753]
## Steps to reproduce the issue
1. Open homepage
2. Click on one of the category tiles on homepage

## Current behavior
Tiles are hyprlinked with following links:
localhost:3000/women
localhost:3000/men
localhost:3000/gear
Clicking any of them result in displaying: `We can't find the page` message

Category pages themselves are still accessible trough hamburger menu or direct url (correct1) input. 

## Expected behavior
Tiles on homepage should be correctly hyperlinked and lead to correct categories on click. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: latest Chrome
- OS: Ubuntu 18.04
- Code Version: release/v1.11

**Comment by andrzejewsky** [comment]
@gibkigonzo as we talk together today there are two issues:
1. mentioned by @ArturDivante (occurs on 1.11) - just wrong links on homepage
2. wrong links on 1.10, on homepage we have links prefixex by `/c` - here please prepare hotfix from current master
