### ISSUE TITLE
SSL certificate for non-www vuestorefront.io still expired

### ISSUE THREAD

**Issue by paulocoghi** [DivanteLtd/vue-storefront#3755]
When entering the site without www, it shows that the SSL certificate expired on October 23.

This is also confirmed here: https://www.ssllabs.com/ssltest/analyze.html?d=vuestorefront.io&hideResults=on&latest

**Comment by paulocoghi** [comment]
Only the certificate on the site with "www" is valid, and expires on January 02 2020

https://www.ssllabs.com/ssltest/analyze.html?d=www.vuestorefront.io&s=3.218.135.46&hideResults=on&latest

**Comment by pkarw** [comment]
Thanks @paulocoghi we'll fix it

**Comment by pkarw** [comment]
Fixed!

**Comment by paulocoghi** [comment]
Just curious, is there a reason to use different certificates for "www" and "non-www"?

**Comment by pkarw** [comment]
well, tbh - I've got no clue :) will ask the admin
