### ISSUE TITLE
Add support for Catalog and Cart rules via dynamic proxy

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#376]

**Comment by pkarw** [comment]
OK, it seems like product prices are adjusted by catalog rules - regarding the -  special_price field - https://magento.stackexchange.com/questions/160049/magento-2-api-catalog-price-rule-is-not-applied

**Comment by pkarw** [comment]
We probably need to synchronize the carts with guest-carts or mine cart when the user is logged in:

```
Checkout

* POST   /V1/guest-carts/:cartId/shipping-information
POST   /V1/carts/mine/shipping-information
POST   /V1/carts/:cartId/shipping-information
POST   /V1/carts/:cartId/totals-information
POST   /V1/guest-carts/:cartId/totals-information
POST   /V1/carts/mine/totals-information
POST   /V1/guest-carts/:cartId/payment-information
GET    /V1/guest-carts/:cartId/payment-information
POST   /V1/carts/mine/payment-information
GET    /V1/carts/mine/payment-information
POST   /V1/guest-carts/:cartId/set-payment-information
POST   /V1/carts/mine/set-payment-information
```

**Comment by pkarw** [comment]
https://magento.stackexchange.com/questions/110803/carts-in-magento2-rest-api-and-front-end

**Comment by pkarw** [comment]
Related to: #503

**Comment by pkarw** [comment]
This is related to #503

**Comment by pkarw** [comment]
Duplicate od #503

**Comment by parekhreena** [comment]
It is not just about cart totals, even on listing page the catalog rule should show the reduced price, which is not happening right now as far as i know.
