### ISSUE TITLE
Add key additionalIncludeFields

### ISSUE THREAD

**Issue by benjick** [DivanteLtd/vue-storefront#3763]
## What is the motivation for adding / enhancing this feature?

It's not very nice to have to keep all the default fields in my config just to add a single one. I'm suggesting a new key called `additionalIncludeFields` which will be merged with `includeFields`

## What are the acceptance criteria 

- [ ] Being able to add new fields to `additionalIncludeFields` which are merged with `includeFields` during build time

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
I think this is not necessary needed feature - complicating our - already complicated configs :)
