### ISSUE TITLE
"null" value in search input

### ISSUE THREAD

**Issue by dmytrokravch** [DivanteLtd/vue-storefront#3778]
## Current behavior

After first entering the page, input field for search bound to "null" value

## Expected behavior

Search input should be clear

## Steps to reproduce the issue

Enter the https://demo.storefrontcloud.io/

## Repository

Enter the https://demo.storefrontcloud.io/ on any of browsers

## Can you handle fixing this bug by yourself?

- [] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome Version 72.0.3626.81 (Build officiel) (64 bits)
- OS: win 10
- Node:  v10.16.3
- Code Version: v1.10.4

## Additional information
![image](https://user-images.githubusercontent.com/32672282/68127681-a854bd80-ff16-11e9-936b-c7e3846e174e.png)

**Comment by ArturDivante** [comment]
I confirm, problem exist. 
I reproduced it by:
1.opening search 
2.clicking into the input
3. clicking out of it
4. closing search and reopening it
Similar problem was already addressed in #3474 
![Null in search](https://user-images.githubusercontent.com/47415585/68197163-0f777e00-ffba-11e9-8f32-07ae679c2ccd.gif)

**Comment by psmyrek** [comment]
v1.10.4 does not contain fix from #3474 - see https://github.com/DivanteLtd/vue-storefront/commit/6861c4bde35ff4ae2ad8af6e3ab84a17ed259db7

**Comment by AdKamil** [comment]
I've tried to replicate this behaviour on `release/v.1.11`, `master`, `hotfix/v1.10.5` branches and didn't meet that.  [gif](https://gyazo.com/0d164b8f0bc8265e176dcba29111ed30)
