### ISSUE TITLE
return button does not appear on product page 

### ISSUE THREAD

**Issue by dmytrokravch** [DivanteLtd/vue-storefront#3779]
## Current behavior

After entering the product page, return button does not appear

## Expected behavior

return button should be 

## Steps to reproduce the issue

Go to: https://demo.storefrontcloud.io/ and go to the product page

## Can you handle fixing this bug by yourself?

- [x] YES
- [] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

Browser: Chrome Version 72.0.3626.81 (Build officiel) (64 bits)
OS: win 10
Node: v10.16.3
Code Version: v1.10.4

**Comment by pkarw** [comment]
@alinadivante can anyone from QA confirm this one please?

**Comment by alinadivante** [comment]
@pkarw  @dmytrokravch  this issue is the lack of a back arrow on the PDP, right?
So the arrow was intentionally removed a few months ago →  https://github.com/DivanteLtd/vue-storefront/issues/2804#issuecomment-487170122
