### ISSUE TITLE
Memory leak in dynamic config

### ISSUE THREAD

**Issue by lukeromanowicz** [DivanteLtd/vue-storefront#3782]
## Current behavior
There is a memory leak when handling incoming requests having dynamic confic reload enabled. Memory usage is slowly rising until app crash.

## Expected behavior
No memory leaks

## Steps to reproduce the issue
1. enable dynamic config reload
2. build & start app
3. load test

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
This might be usefull: https://github.com/DivanteLtd/vue-storefront/pull/3075

**Comment by lukeromanowicz** [comment]
Indeed, #3075 seems to be fixing it.
