### ISSUE TITLE
Confusing default set of sorting dropdown

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#3785]
Im not sure if it was always that way or just changed at some point, but currently when we open category page, sorting dropdown i set in 'latest' position. It looks like sorting by 'latest' is applied by default. But in fact it is not - default sorting is diffrent than 'latest'. 

Other problem is, that user who actually want sort by 'latest', cannot do that directly, as this option is initialy unclickable (which is another suggestion that this sorting is already applied). He needs to switch to other sorting method and then select 'latest' again. 

![SortByLatest](https://user-images.githubusercontent.com/47415585/68211603-2dec7200-ffd8-11e9-9a6a-82568ce9dd0c.gif)

## Expected behavior
In default position (before 1st use), sorting dropdown should contain something like "Sort by": position. Clearly informing user what is the purpose of this element, and not suggesting, than any way of sorting was already applied. 

OR

2nd approach to this problem (IMHO less UX friendly) would be to actually do what current display suggest - show category page sorted by default by 1st position on the list (in this case 'latest') . But im not quite sure it would be correct. Decision will be needed here @pkarw  

## Steps to reproduce the issue
1. Open any category page, look at the sorting dropdown
2. Click on it, and try to apply sorting by 'latest'

## Repository
All

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser:latest chrome
- OS: Ubuntu 18.04

**Comment by AdKamil** [comment]
I'm on it
