### ISSUE TITLE
AMP-Pages are broken

### ISSUE THREAD

**Issue by dlandmann** [DivanteLtd/vue-storefront#3799]
## Current behavior
The generated "amphtml" Product-URL in the head (link-rel) isn´t correct. Error-Page (Something went wrong ...) is shown.

The AMP-Category Page works fine!

## Steps to reproduce the issue
Go the productpage and copy the amphtml URL from the code and paste into browser. In "older" versions of vue-storefront it works fine. Last work with the amp-feature was approx. 2 mounth ago.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome 78 and all others
- OS: OS X 10.15
- Node: 12
- Code Version: master and develop

**Comment by dlandmann** [comment]
I would check the changlog.md and then try to fix is

**Comment by pkarw** [comment]
@dlandmann thanks! It's on 1.10 and/or 1.11?

**Comment by dlandmann** [comment]
@pkarw In Short ... Its on 1.10 **and** (with other Behaviour) on 1.11. See following tests. All tested with a clean Repo and the default config (only api set to https://test.storefrontcloud.io.)

**1.11-rc2** 
- Category AMP it does not work
```
Example-URL: 
http://domain/men/tops-men/jackets-men/jackets-14 
Generated AMP-URL:
no URL given!
```
---
- Product AMP it does not work (Something went wrong ...)
```
Example-URL:
http://domains/men/tops-men/jackets-men/jackets-14/typhon-performance-fleece-lined-jacket-387.html?childSku=MJ11-XS-Black
Generated AMP-URL:
http://domain/amp/p/MJ11/typhon-performance-fleece-lined-jacket-387/MJ11-XS-Black
```
---
---
**1.10.4** 
- Category AMP works
```
Example-URL: 
http://domain/c/jackets-14 
Generated AMP-URL:
http://domain/amp/c/jackets-14
```
---
- Product AMP it does not work (Something went wrong ...)
```
Example-URL:
http://domains/men/tops-men/jackets-men/jackets-14/typhon-performance-fleece-lined-jacket-387.html?childSku=MJ11-XS-Black
Generated AMP-URL:
http://domain/amp/p/MJ11/typhon-performance-fleece-lined-jacket-387/MJ11-XS-Black
```
---
---
**1.9.3** 
- Category AMP works
```
Example-URL: 
http://domain/men/tops-men/jackets-men/jackets-14
Generated AMP-URL:
http://domain/amp/c/jackets-14
```
---
- Product AMP it does not work (Sww ..)
```
Example-URL:
http://domains/men/tops-men/jackets-men/jackets-14/typhon-performance-fleece-lined-jacket-387.html?childSku=MJ11-XS-Black
Generated AMP-URL:
http://domain/amp/p/MJ11/typhon-performance-fleece-lined-jacket-387/MJ11-XS-Black
```
---
---
less than version 1.9.3 it should work. I tested this feature successfully during the summer. I can not load 1.9.2 because my node version is too new and I can not / want to change that :-)
