### ISSUE TITLE
Product labels `new` and `sale` use an incorrect boolean type

### ISSUE THREAD

**Issue by themreza** [DivanteLtd/vue-storefront#3800]
## Current behavior

The `vue-storefront/core/modules/catalog/components/ProductTile.ts` component looks for two fields in the ElasticSearch product record to decide if the `new` and `sale` labels should be displayed on each product.

The checks for these fields assumes the fields to be of type string with an exact value of `'1'`.

![image](https://user-images.githubusercontent.com/5465057/68611426-5c77ba80-04ba-11ea-8402-1a41bc5ba170.png)

## Expected behavior

The fields should accept the standard true / false boolean types as input.

## Repository

https://github.com/DivanteLtd/vue-storefront/blob/release/v1.11/core/modules/catalog/components/ProductTile.ts#L37

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [X] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by andrzejewsky** [comment]
thanks for reporting @themreza, actually we've fixed something similar, looks like easy to fix

**Comment by WaleedTikken** [comment]
It has been fixed along with the product display on latest option. :)

**Comment by WaleedTikken** [comment]
Just changed the default sort to 

> "sort": "updated_at",
instead of 

> "sort": "updated_at:desc",

**Comment by themreza** [comment]
> Just changed the default sort to
> 
> > "sort": "updated_at",
> > instead of
> 
> > "sort": "updated_at:desc",

What does the sort order have to do with new and special labels? 

If it was fixed, would you please share the link to the new ProductTile.ts?

**Comment by andrzejewsky** [comment]
@WaleedTikken we've fixed issue with the sorting functionality on the category page and nothing else, this is about the `isOnSale` or `isNew` - it won't work if the value is different than `'1'` @themreza is right.
