### ISSUE TITLE
Make Cash on delivery code configurable

### ISSUE THREAD

**Issue by adityasharma7** [DivanteLtd/vue-storefront#3802]
## What is the motivation for adding / enhancing this feature?

The code for the cash on delivery is hard coded. 
https://github.com/DivanteLtd/vue-storefront/blob/release/v1.11/src/modules/payment-cash-on-delivery/index.ts#L18
The idea is to make it configurable so that the value can be as per the backend system

## What are the acceptance criteria 

- [ ]  Provision config file with offline payment code
- [ ]  Payment Cash on Delivery module honor config files

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
@adityasharma7 the other way around is just to copy this module and adjust it to your backend platform which probably is a preferred way rather than adding the configurable option
