### ISSUE TITLE
Product changes when the filter is removed, like select color and remove its color filter, product order will be changed

### ISSUE THREAD

**Issue by WaleedTikken** [DivanteLtd/vue-storefront#3809]
## Current behavior

I've noticed that, when I got to the men's product page, there I saw latest products, and when I choose color filter, it displays all items according to that color, but after removing that filter I'm unable to view old latest list of product that were displayed in first place.

## Expected behavior

I want the query to be sort updated_at, after the filter is removed :)

**Comment by pkarw** [comment]
Thanks Waleed!

**Comment by andrzejewsky** [comment]
Hello, @WaleedTikken I think it was fixed here: https://github.com/DivanteLtd/vue-storefront/pull/3793 and also now here: https://github.com/DivanteLtd/vue-storefront/pull/3817 (but it solves different issue)
