### ISSUE TITLE
VSF require only option id

### ISSUE THREAD

**Issue by boehsermoe** [DivanteLtd/vue-storefront#3813]
@afirlejczyk how can I access the attribute "types" in the vue storefront?

> By default VSF require only option id, real values are load from attribute type (from ES), where labels for a store view are exported.
> 
> You can do the same on VSF for a custom attribute and load option label from "attribute" type.
> 
> By default we won't be doing any changes regarding this attributes. @pkarw
> 
> _Originally posted by @afirlejczyk in https://github.com/DivanteLtd/magento2-vsbridge-indexer/issues/149#issuecomment-549058258_

**Comment by Fifciu** [comment]
## Best way
I think the most universal answer would be using `attribute/list` action to fetch this attribute. You could do it like that:
```
store.dispatch('attribute/list', {
    filtersValues: ['types'] // There you can provide an array of attributes' slugs you would like to fetch
})
```

As it is async action, use it with async/await or Promise. For sure:
```
// Inside async function
async someFunction () {
  await store.dispatch('attribute/list', {
    filtersValues: ['types'] // There you can provide an array of attributes' slugs you would like to fetch
  })
  console.log('Now I have it in the Vuex!')
}

// Inside classic function
someFunction () {
  store.dispatch('attribute/list', {
    filtersValues: ['types'] // There you can provide an array of attributes' slugs you would like to fetch
  }).then(response => {
    console.log('Now I have it in the Vuex!')
  })
}
```

After that, if it succeeds. You would have all the information about the attribute in the Vuex store. Then you could access it by:
```
const typesAttribute = this.$store.getters['attribute/attributeListByCode'] && this.$store.getters['attribute/attributeListByCode'].types;
```

The most often use case with that data is changing `option_id` to the readable for human label. The best way to do that imo is using `optionLabel` helper. So after fetching necessary data to the state, use: 
```
import { optionLabel } from '@vue-storefront/core/modules/catalog/helpers/optionLabel'

export default {
// some component data...
  mounted () {
    const someOptionId = 25
    const someOptionLabel = optionLabel(this.$store.state.attribute, {
      attributeKey: 'types', // Attribute slug/key in our case it is 'types'
      optionId: someOptionId // option_id
    })

    console.log(`OptionId ${someOptionId} corresponds to ${someOptionLabel} label`)
  },
}

```
Now in the `someOptionLabel` const we have:
a) If this optionId exists in the attribute - Label
b) If not, just an optionId

## Simple way
You could also try to add `types` to the `config.products.defaultFilters` so it would be fetched out-of-the-box. However, **only on the Category's view**. As I often needed to use it in different places - above you have a more scalable solution.

**Comment by boehsermoe** [comment]
Thank you, the optionlabel helper is exactly what I needed👍 next time I will check the docu first https://docs.vuestorefront.io/guide/modules/catalog.html#optionlabel
