### ISSUE TITLE
Zoom image issue on product page

### ISSUE THREAD

**Issue by AshishSuhane** [DivanteLtd/vue-storefront#3818]
## Current behavior
On the product page, once you tap on the zoom icon and then press the back button it will open the previous product page with the zoom image modal.

## Expected behavior
It should open the product page without a zoom image modal.

## Steps to reproduce the issue
1. open demo.vuestorefront.io in a browser
2. click on any product and choose any products from suggestions.
3. click on the zoom icon. image modal will open.
4. click on back button. previous product will open with image modal in zoom mode.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
@przspa can you take a look?
