### ISSUE TITLE
Changing defaultLocale to jp-JP in local.json is not working

### ISSUE THREAD

**Issue by hawaiiden** [DivanteLtd/vue-storefront#3824]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Information

I tried to change language and currency of my VS, so I edited i18n in local.json 
like this,

```
"i18n": {
      "defaultCountry": "JP",
      "defaultLanguage": "JP",
      "availableLocale": ["en-US","de-DE","fr-FR","es-ES","nl-NL", "jp-JP", "ru-RU", "it-IT", "pt-BR", "pl-PL", "cs-CZ"],
      "defaultLocale": "jp-JP",
      "currencyCode": "JPY",
      "currencySign": "円",
      "currencySignPlacement": "append",
      "dateFormat": "l LT",
      "fullCountryName": "Japan",
      "fullLanguageName": "Japanese",
      "bundleAllStoreviewLanguages": true
    }
```
Every locale is working except jp-JP, which is above way.
The error message is,

```
Error during render : /error
{ Error: Cannot find module './jp'
    at server-bundle.js:26736:12
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
(node:40996) UnhandledPromiseRejectionWarning: Error: Cannot find module './jp'
```

1. If there is better way  to change language and currency of VS, please let me know.
2. Why only Japan option is not working? Is this normal or I did something wrong? or should I install anything like Japanese language module?

**Comment by pkarw** [comment]
Fixed by https://github.com/DivanteLtd/vue-storefront/pull/3831
