### ISSUE TITLE
category "sort by price" sorts products by "original price", not "special price" when "sourcePriceIncludesTax": true, "calculateServerSide": false

### ISSUE THREAD

**Issue by dmytrokravch** [DivanteLtd/vue-storefront#3827]
## Expected behavior

shoud sort by special price if it exist

## Steps to reproduce the issue

set in config:
"sourcePriceIncludesTax": true, 
"calculateServerSide": false

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

Browser: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
OS: Windows 10 Pro 1809
Node: v10.16.3
Code Version: VSF 1.10.4 / VSF-API 1.10.0

## Additional information

![image](https://user-images.githubusercontent.com/32672282/69245460-22d43d00-0ba7-11ea-99e7-8e3d3ced1a5f.png)

**Comment by pkarw** [comment]
The only option here is to sort by `final_price`. The `vue-storefront-api` is adding `special_price` [field dynamically](https://github.com/DivanteLtd/vue-storefront-api/blob/8b7ded1c780bc1c90b93dca04f6acb0ad76045e6/src/lib/taxcalc.js#L40) - so it's not stored in Elasticsearch. You can sort only by the fields stored in the Elasticsearch.
