### ISSUE TITLE
Sync cart between tabs

### ISSUE THREAD

**Issue by Fifciu** [DivanteLtd/vue-storefront#3838]
## Current behavior

Let's imagine a typical e-commerce scenario. I am opening the category's view and browsing stuff. Then I am opening a few product's views in new carts. I jump to the first product and adding it to cart then in other tab I am adding to the cart another product. In the end, I am again in tab with the category's view. I refresh and... I have only one product in the cart - but I should have 2.

## Expected behavior

When I am adding to the cart in one tab I have sync in other tabs for the cart.

## Steps to reproduce the issue

In description..

## Repository

You can do test here: https://demo.vuestorefront.io/

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  Chrome
- OS:  Ubuntu 16.04
- Node: 
- Code Version: 

## Additional information

Maybe it could be helpful: https://github.com/xanf/vuex-shared-mutations

**Comment by andrzejewsky** [comment]
Yeah, I think is the cache-related problem. VSF doesn't update anything if you don't force it or there are current data in the cache. Thanks for reporting @Fifciu

**Comment by pkarw** [comment]
Good point. We should probably just call the `cart/load` whenever the tab is activated
