### ISSUE TITLE
New account gets registered to wrong store (when using multistore)

### ISSUE THREAD

**Issue by juho-jaakkola** [DivanteLtd/vue-storefront#3848]
## Current behavior

The registration is not working correctly in a multistore setup. The API request made to Magento is missing the `website_id` property, which causes Magento to use the default store instead of the one it should be using.

See: https://devdocs.magento.com/redoc/2.3/customer-rest-api.html#tag/customers

In my case I tried to create an account to the German store, but I the account got registered into the Polish store causing the welcome email to be in the wrong language.

This was apparently still working in 1.10, but got broken in 1.11.

## Expected behavior

Account should get created in Magento into the store that was being used in VSF.

## Repository

https://github.com/DivanteLtd/vue-storefront/tree/v1.11.0-rc.2

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by juho-jaakkola** [comment]
I'm not completely sure whether this should be fixed into VSF or VSF-API.

I suppose the missing `website_id` could be added in either one:
 - https://github.com/DivanteLtd/vue-storefront/blob/v1.11.0-rc.2/core/modules/user/store/actions.ts#L72-L74
 - https://github.com/DivanteLtd/vue-storefront-api/blob/v1.11.0-rc1/src/api/user.js#L35-L56

**Comment by juho-jaakkola** [comment]
I'm not able to reproduce the problem anymore. I'll reopen if I run into the problem again.

**Comment by gibkigonzo** [comment]
TODO:
1. send `website_id` to vsf-api
2. pass `website_id` to platform in vsf-api for user endpoints
