### ISSUE TITLE
Price of Recently Viewed Products Not Updated When Magento Updated

### ISSUE THREAD

**Issue by JuliaBonita** [DivanteLtd/vue-storefront#3862]
## Current behavior
When I update a product's price in Magento, if the product was already viewed in VSF, the old price remains in the "Recently Viewed" products list. If you then click on the product in the "Recently Viewed" list, it will display the product with the correct price. So, the problem seems to be limited to the list view only.

## Expected behavior
The current price should be updated in all VSF list views after it's updated in Magento.

## Steps to reproduce the issue
View a product in VSF. Then update its price in Magento. Then go to your "Recently Viewed" list in VSF. You will still see the old price for the product in that list. 

## Can you handle fixing this bug by yourself?
- [x ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x ] This is a bug report for current Stable version.

## Environment details

- Browser: Chromium Version 78.0.3904.108
- OS: Ubuntu
- Node: v10.17.0
- Code Version:  v1.10.4

**Comment by andrzejewsky** [comment]
Thanks for reporting, I'll look at this.

**Comment by pkarw** [comment]
Recently viewed products are cached in the `localStorage` therefore it's not possible to refresh the price when Magento price got refreshed
