### ISSUE TITLE
Extend in storeView config does not work

### ISSUE THREAD

**Issue by Fifciu** [DivanteLtd/vue-storefront#3863]
## Current behavior

When I've used extend option where value of `appendStoreCode` should be inherited. I could not open checkout. Button still was link to the `/checkout` (without storeCode). I had warning in console:
```
vue-router.esm.js:16 [vue-router] Route with name 'checkout' does not exist
```

I fixed it just by copy/paste stuff to storeViews instead of use `extend`. However, it would be so cool to use *extend* option.

## Expected behavior

Extend extending everything properly when we inherit `appendStoreCode`

## Steps to reproduce the issue

Create 2 storeVIews. First one should have `appendStoreCode` === true. Second one should extend the first one.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  The newest Chrome
- OS:  Ubuntu 16.04
- Node:  10.15.3
- Code Version:  1.11rc2

## Additional information

I think checking `extend` option inside below function could help:
```js
export function setupMultistoreRoutes (config, router: VueRouter, routes: RouteConfig[], priority: number = 0): void {
  const allRoutes: RouteConfig[] = []
  const { storeCode, appendStoreCode } = currentStoreView()
  if (storeCode && appendStoreCode) {
    allRoutes.push(...routes.map(route => localizedRouteConfig(route, storeCode)))
  } else {
    allRoutes.push(...routes)
  }
  router.addRoutes(allRoutes, true, priority)
}
```

**Comment by gibkigonzo** [comment]
@Fifciu I couldn't reproduce this issue. We have test case for extending storeView `core/lib/test/unit/multistore.spec.ts:367`. I tried to break it, but I failed. :sweat_smile:  Can you show storeViews config that was not working(with `extend`)?

**Comment by pkarw** [comment]
@lukeromanowicz can you please take a look at this one?

**Comment by gibkigonzo** [comment]
@Fifciu `appendStoreCode` can not be inherited with extend. Please check docs for 1.11 https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/basics/configuration.md ` Keep in mind that url, storeCode and appendStoreCode attributes cannot be inherited from oter storeviews.`

**Comment by Fifciu** [comment]
> @Fifciu `appendStoreCode` can not be inherited with extend. Please check docs for 1.11 https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/basics/configuration.md ` Keep in mind that url, storeCode and appendStoreCode attributes cannot be inherited from oter storeviews.`

That's quite interesting. Not inheriting storeCode is obvious. However, why not inherit appendStoreCode? I think people rather use it for each storeCode or do not use it. So inheriting/global option would be so useful
