### ISSUE TITLE
Redirect simple to configurable product problems

### ISSUE THREAD

**Issue by benjick** [DivanteLtd/vue-storefront#3866]
## Current behavior
(I'm on 1.10.4 but I have implemented this: https://github.com/DivanteLtd/vue-storefront/pull/3804/files)

1. Go to `http://localhost:3000/se/f-b-3040` (simple product)
2. End up at `http://localhost:3000/se/f-001-b` (configurable product)
3. Press back, end up at `http://localhost:3000/se/f-b-3040`
4. Press back again, nothing
5. Press back again, nothing
6. Press back again, `about:blank`

## Expected behavior
1. Go to `http://localhost:3000/se/f-b-3040` (simple product)
2. End up at `http://localhost:3000/se/f-001-b` (configurable product)
3. Press back, end up at `about:blank`

## Steps to reproduce the issue
1. Implement this fix: https://github.com/DivanteLtd/vue-storefront/pull/3804/files
2. Go to a simple product

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO (I've tried)

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Firefox 70
- OS: Mac OSX 10.14.5
- Node: 10
- Code Version: 1.10.4

**Comment by georgiev-ivan** [comment]
I would like to take this issue

**Comment by andrzejewsky** [comment]
@benjick could you put here the real links on our test.storefrontcloud.io (or demo)? because I can't even reproduce this bug

**Comment by pkarw** [comment]
Closing due to long inactivity (we can’t reproduce this issue)
