### ISSUE TITLE
static/ in .gitignore release/1.11

### ISSUE THREAD

**Issue by undefinederror** [DivanteLtd/vue-storefront#3870]
why is `static/` in .gitignore?
https://github.com/DivanteLtd/vue-storefront/commit/bb574a3133ea74687dd681f7de3c674783a58b58#diff-a084b794bc0759e7a6b77810e01874f2

A colleague of mine has pulled release/1.11 into a local branch, merged into master and pushed master back to our host.

because of the `static/` entry, the new folder `/src/themes/default/components/theme/blocks/Static` has not been added to git index and not pushed, resulting in this error for anybody else

![image](https://user-images.githubusercontent.com/8209966/70068755-e108b500-15f0-11ea-81ab-10926f4645cb.png)

if it is meant to be targeting something else, then the path should probably be more specific; while if it is actually meant to be targeting that folder, then why?

**Comment by undefinederror** [comment]
ok, that folder wasn't actually new, my bad, it has indeed been in master for a while.
The git update flow was a bit more convoluted than what I described, still that entry in .gitignore made it so that the folder got, well... ignored. :)

The question still stands though, whether `/src/themes/default/components/theme/blocks/Static` got intentionally targeted for being excluded from commits.

**Comment by pkarw** [comment]
Thanks for pointing this out. Well this directory is ignored to not let the users accidentally commit their files to the default theme when they’re contributing to the core. However it’s a ultra rare case it might happen and I agree it may lead to some unintentional issues. Please feel free to contribute a change to the core removing this gitignore, we’re happy to accept

**Comment by undefinederror** [comment]
Happy to contribute, but I don't quite get what your are saying. 
In order to prevent people from committing to default theme you have added `static/` to .gitignore?
That is only going to prevent people from committing to `/src/themes/default/components/theme/blocks/Static`, (only `static` folder in the whole project) isn't it?
Why not add `src/themes/default/` to .gitignore?
There is surely something I am not understanding :D

**Comment by pkarw** [comment]
@andrzejewsky @filrak we need your comment

**Comment by undefinederror** [comment]
ooooooaaaaaaaaaaaaaaaaa!! I think I get it! 
What you want to target is the /static folder that is created running `yarn generate {cmd}` 😄 
I didn't even know that folder would be there, I just run that command and saw the folder being generated.

So in .gitignore it should be `/static` instead of `static/`

Please let me know if my suspicions are correct. In case, if useful, I can submit a PR moving the slash from appended to prepended 😅

**Comment by andrzejewsky** [comment]
you guys were talking about `Static.vue` file while it's about static directory in the root of the project. I'm surprised that `Static.vue` haven't been committed in your case. It's super rare... so quickfix for you @undefinederror - turn off case sensitivity on you git

**Comment by undefinederror** [comment]
Hi @andrzejewsky 
I am talking about folder https://github.com/DivanteLtd/vue-storefront/tree/master/src/themes/default/components/theme/blocks/Static

I am on Windows so that's probably why my .gitignore is case insensitive.
The thing is, if I clone the default theme to make a custom one. Modify files contained in that `Static` folder, they won't be committed.

Since the intended target is `/static` (from project root) I think the entry in .gitignore should be `/static` rather than `static/` - which I believe applies to files contained in any `static` folder at any depth level.

**Comment by andrzejewsky** [comment]
@undefinederror are you 100% sure that exactly this ignore line solves your issue? I'm really sceptic about that because of we have people on board who are working on Windows and they never came across that issue before. 

To ignore this path you need a wildcard something like `*/**/static`, weird. If it's really solves your problem, feel free to prepare a PR (from `develop`)

**Comment by undefinederror** [comment]
@andrzejewsky Yes I am well positive :) 

I go and create a new file in the `Static` folder I mentioned
![image](https://user-images.githubusercontent.com/8209966/70706040-6e28c980-1cd5-11ea-8c7b-c18070b94317.png)

I see no changes picked up in source control
![image](https://user-images.githubusercontent.com/8209966/70706102-93b5d300-1cd5-11ea-8eb0-fcdb52a18277.png)

I change `static/` to `/static` and the new file shows up
![image](https://user-images.githubusercontent.com/8209966/70706166-b47e2880-1cd5-11ea-8d75-ab4a573feea6.png)

This behaviour is indeed in line with git [documentation](https://git-scm.com/docs/gitignore#_pattern_format)
![image](https://user-images.githubusercontent.com/8209966/70706785-f22f8100-1cd6-11ea-9fc7-619a8690cc5e.png)
