### ISSUE TITLE
`yarn start` crashes because `pm2` ecosystem file needs `script` property

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront#3871]
## Current behavior

If I currently start my VSF build using `yarn start`, I'll get the error `No script path - aborting` like:
```bash
yarn run v1.19.1
$ cross-env NODE_ENV=production TS_NODE_PROJECT="tsconfig-build.json" pm2 start ecosystem.json $PM2_ARGS
[PM2] Spawning PM2 daemon with pm2_home=/home/ubuntu/.pm2
[PM2] PM2 Successfully daemonized
[PM2][WARN] Applications server not running, starting...
[PM2][ERROR] No script path - aborting
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
Done in 0.89s.
```

This is caused by the missing `script` property in `ecosystem.json` – it's a required one.
So, if you change the file to the following, it's working again and uses the args for the interpreter:
```diff
{
  "apps": [
    {
      "name": "server",
      "max_memory_restart": "1G",
      "instances": "4",
      "exec_mode": "cluster",
      "env": {
        "TS_NODE_PROJECT": "tsconfig-build.json",
        "NODE_ENV": "production"
      },
      "interpreter": "./node_modules/.bin/ts-node",
-      "args": "-P ./tsconfig-build.json ./core/scripts/server.ts",
+      "interpreter_args": "-P ./tsconfig-build.json",
+      "script": "./core/scripts/server.ts",
      "node_args": "--max_old_space_size=1024",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "ignore_watch": [
        "core/build/config.json",
        "node_modules"
      ]
    }
  ]
}
```

## Steps to reproduce the issue

* Run `yarn`
* Run `yarn build`
* Run `yarn start`
* The `No script path - aborting` message should appear

## Repository

Caused by: 9c4f55f998ed3a74f3d39ee6df58c5d20de74933 and  noticed in latest `release/v1.11` - 5c73791cefcb6fc990d864cd5437e4793ac0725c

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: None 
- OS: All 
- Node: 10 LTS 
- Code Version: Latest `release/release/v1.11` 5c73791cefcb6fc990d864cd5437e4793ac0725c

**Comment by cewald** [comment]
PR is open: #3871

**Comment by andrzejewsky** [comment]
@cewald already fixed, but thanks for report!
