### ISSUE TITLE
non empty defaultStoreCode in multistore mode errors out

### ISSUE THREAD

**Issue by undefinederror** [DivanteLtd/vue-storefront#3881]
## Current behavior
These two are the only changes to config/default.json
![image](https://user-images.githubusercontent.com/8209966/70234990-344e4500-1762-11ea-8b08-118e6c6e8e0b.png)
It results in an error loop
![image](https://user-images.githubusercontent.com/8209966/70234944-197bd080-1762-11ea-997c-4f161d2ef58e.png)

## Expected behavior
Should behave like v1.10 ~~redirect to host/{defaultStoreCode}~~ storeView context switches to `defaultStoreCode`

## Steps to reproduce the issue
clone repo 
checkout release/v1.11, 
make 2 changes to config 
yarn dev

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 78.0.3904.108
- OS: Windows 10 Pro
- Node: v10.16.3
- Code Version: v1.11.0-rc.2

## Additional information
relates to #2731

**Comment by andrzejewsky** [comment]
thanks for reporting, we need to check that 👍

**Comment by pkarw** [comment]
Hi there! Are you sure it was doing the redirect in 1.10? I’m asking because #3643 is still open and not merged yet. Before that we haven’t got the redirect and this parameter was used for switching the elastic search index names and adding this parameter as ?storeView to api calls - in general for switching the store context for the default url

By having this parameter you were able to run the vs on root domain with specific storeView selected without the need of using /de, /it prefixes

**Comment by undefinederror** [comment]
Yes you are right, no redirect to host/{defaultStoreCode} as I said previously. Not sure which dream I took it from :D
