### ISSUE TITLE
Safari Browser: Homepage Images Don't Appear

### ISSUE THREAD

**Issue by JuliaBonita** [DivanteLtd/vue-storefront#3882]
## Current behavior

Everything works fine on Chrome and Edge, but on Safari (iOS & MacOS) the homepage product images never appear on first load. (Only the placeholder appears.) They also don't appear when you refresh the browser window. But if you click on any product or site link on the homepage and then click back to the homepage, all the product images appear as expected. Then refresh the homepage and they all disappear again until you click another link to some internal page.

## Expected behavior

All homepage product images should appear on the homepage like they do on Chrome/Edge.

## Can you handle fixing this bug by yourself?

No

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for current Stable version  

## Environment details

- Browser: Safari (13.0.2 on MacOS Catalina) and Safari recent version on iPhone 11 (I don't have the device with me now; so I don't know the exact Safari version.)
- OS: Client side: iOS and MacOS: Server side: Ubuntu (production installation; no Docker) 
- Node: v10.17.0
- Code Version:  v1.10.4

## Additional information

I've already tried purging the browser cache many times. So this is not a client-side caching problem. Everything works fine on Chrome and Edge. So this is not a `local.json` or Magento configuration problem.

There are a couple console errors, which I don't think are relevant, but here they are:

`Viewport argument key "minimal-ui" not recognized and ignored.` (This only appears on Safari.)

And for 3 JS files the following warning appears on Safari and Chrome:
`The resource <my-domain/javascript-file> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.`

Thank you for helping me resolve this as soon as possible.

**Comment by pkarw** [comment]
Thanks for raising this issue. I’ve got it only on v1.10 (demo.storefrontcloud.io) and it’s apparently gone on v1.11 (test.storefrontcloud.io)

**Comment by andrzejewsky** [comment]
@pkarw so maybe we have to backport / solve that issue on 1.10

**Comment by JuliaBonita** [comment]
Thank you. I've upgraded to v.1.11 and can confirm the issue is fixed. Much appreciated!

**Comment by pkarw** [comment]
Yeah, it's a backport candidate

**Comment by pkarw** [comment]
@andrzejewsky can we close this one tomorrow as well? Only these two and you’re free to go to Thailand 🇹🇭
