### ISSUE TITLE
Different shape of category in product object (Elasticsearch)

### ISSUE THREAD

**Issue by Fifciu** [DivanteLtd/vue-storefront#3883]
## What is the motivation for adding / enhancing this feature?

Easy sorting by sort order.

## What are the acceptance criteria 

- [ ] Change shape of category's attribute inside product

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information

Currently, category's attribute inside product looks like that:
```json
"category": [
   {
      "category_id": 2,
      "name": "Store",
      "position": 0
  }
],
```

But I think the better approach (I've used it in a few projects) would be just:
```json
"category": {
   "2": 0
},
```
So:
```ts
interface Category {
  [categoryId: string]: number // sortOrder
}
```

The main benefit would be so easy sorting by sort order:
```js
requestBody.sort = [
  {
    [`category.${categoryId}`]: {
      "mode": "max",
      "order": "asc",
      "nested_path": "category"
    }
  }
]
```

**Comment by pkarw** [comment]
@Fifciu there is `category_ids` in exactly that format - doesn't it solve the issue?

**Comment by Fifciu** [comment]
@pkarw `category_ids` looks to be array of ids. I need also information about **product's sort order in each category**. Of course, I have it in the `category` but as array of objects - so it is hard to sort by that straightly in Elasticsearch query. 

I've shown how easy could we sort them if we have proposed shape of data (I've used it in one project and it worked well)

**Comment by pkarw** [comment]
ok! @Fifciu now i got it :)
