### ISSUE TITLE
"No script path - aborting"

### ISSUE THREAD

**Issue by JuliaBonita** [DivanteLtd/vue-storefront#3884]
## Current behavior
`yarn start` throws this error: `[PM2][ERROR] No script path - aborting`

## Expected behavior
Yarn should start the VSF app with no error.

## Steps to reproduce the issue

Install the latest v1.11-rc.2 and try to start it.

## Can you handle fixing this bug by yourself?

YES

## Environment details
- Browser: Chromium
- OS: Ubuntu
- Node: v10.17.0
- Code Version: v1.11.0-rc.2

## Additional information

I'm not sure if this is the _correct_ solution, but I added `"script": "./core/scripts/server.ts",` to the `ecosystem.json` file. Then yarn could find the script and the app builds/starts correctly.

**Comment by pkarw** [comment]
@andrzejewsky i guess this is because of this missing “script” property in ecosystem.json we need to fix it quickly

**Comment by andrzejewsky** [comment]
@pkarw fixed on develop, a few days ago

**Comment by pkarw** [comment]
Oh, it’s been just fixed https://github.com/DivanteLtd/vue-storefront/pull/3872

@JuliaBonita please switch to develop for a while
