### ISSUE TITLE
Add to cart issue with non required custom options

### ISSUE THREAD

**Issue by ktopouzi** [DivanteLtd/vue-storefront#3885]
## Current behavior

Adding products with custom options on cart fails, asking for all product options to be selected.

## Expected behavior

Only the required options should be selected. Everything else is optional. The product should be added to cart successfully without selecting every option.

## Steps to reproduce the issue

Make a Magento 2 connection and pump some product with custom options (more that 1).
Make one of the product options required and leave the rest not required.
Synchronize VSF with Magento. 
Try to add to cart the product without selecting the NON-required option.

The following images shows what I have faced so far:

#### Initial product page
![Screenshot from 2019-12-07 19-22-48](https://user-images.githubusercontent.com/15310054/70378309-7aa0d100-1927-11ea-9477-768c5ff6434f.png)
I changed slightly the design so it could fit all the custom options. The second column is required as you can see in the screenshot.

#### Selecting only the required option
![Screenshot from 2019-12-07 19-23-34](https://user-images.githubusercontent.com/15310054/70378330-b63b9b00-1927-11ea-89af-961dba3cdf36.png)

#### Selecting all the required options
![Screenshot from 2019-12-07 19-23-47](https://user-images.githubusercontent.com/15310054/70378345-d10e0f80-1927-11ea-874c-a81631de2322.png)

In addition to that if I add successfully a product in cart, and then *deselect* the non-required options and add to cart the product, the amount on the cart is updating successfully but the custom options are not taking in consideration. I believe this strongly relates to #3595 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

But if someone guides me I could definitely give it a try.

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  Chrome Version 78.0.3904.108 (Official Build) (64-bit)
- OS:  ubuntu 18.04
- Node:  v10.17.0
- Code Version:  v1.11.0-rc.2

## Additional information

That's my first issue on the project. Please let me know if there's anything I can do/describe better. 
I really appreciate your work and would be more than happy to help with the issue.

**Comment by pkarw** [comment]
@gibkigonzo @andrzejewsky

**Comment by pkarw** [comment]
Maybe related to: #3595

**Comment by andrzejewsky** [comment]
@pkarw yeah, this the first thing that came to my mind. Worth to check that, thanks @ktopouzi

**Comment by pkarw** [comment]
Assigned to @gibkigonzo as he fixed something related in October: https://github.com/DivanteLtd/vue-storefront/pull/3694

@ktopouzi this PR was merged into develop branch (1.12rc1); can you please check it on develop?

**Comment by ktopouzi** [comment]
Hey @pkarw I have switched on the develop branch and tested again. This issue is still here. ( just for clarification the develop branch version is 1.11.0 and not 1.12. Am I in a wrong branch?)

**Comment by andrzejewsky** [comment]
@ktopouzi develop is currently 1.11 -we merge there just improvements and bugfixes (no BC) because release is comming , 1.12 haven't started yet

**Comment by ktopouzi** [comment]
Oh okay. Piotr actually mentioned 1.12 that's why I got confused.  Even after setting the develop branch up the issue is still here.
