### ISSUE TITLE
Mulistore Error page shows 404

### ISSUE THREAD

**Issue by grimasod** [DivanteLtd/vue-storefront#3890]
## Current behavior

The Error page on multistore sites shows 404 page-not-found 

## Expected behavior

The Error page should be the same as the default store. 

## Steps to reproduce the issue

Open the pages:

https://next.storefrontcloud.io/error 
https://next.storefrontcloud.io/it/error

Notice that the IT store is incorrectly showing the 404 page. The default store is correct.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version: develop and release/v1.11

**Comment by pkarw** [comment]
Hi @grimasod, hmm I didn't notice: what's wrong with this error page (for me it looks like this: https://www.dropbox.com/s/0oll82kpkn5bc91/Screenshot%202019-12-10%2016.02.50.png?dl=0)

**Comment by grimasod** [comment]
Hi @pkarw 
That's the page not found 404 page. It should be the error page, "Something went wrong ..." (using the Minimal layout)

**Comment by grimasod** [comment]
<img width="476" alt="Screen Shot 2019-12-11 at 10 24 50 AM" src="https://user-images.githubusercontent.com/29225088/70583380-ea051200-1c00-11ea-99af-e6b92ee009a5.png">
<img width="492" alt="Screen Shot 2019-12-11 at 10 25 04 AM" src="https://user-images.githubusercontent.com/29225088/70583384-ea051200-1c00-11ea-9a8b-80a2d78550a4.png">

**Comment by pkarw** [comment]
ah, OK! I got it (I guess): the issue is that under localized urls (/it/error) there is no error page but rather a 404 not-found-  is that the core of this issue?

**Comment by pkarw** [comment]
This issue is related to 1.11 only - but honestly, I don't know why is that because of the error page is a normal route - registered the same way as /page-not found (is in the same routing table) ...

**Comment by pkarw** [comment]
@gibkigonzo, @andrzejewsky will you please take a look?

**Comment by grimasod** [comment]
Yes, exactly. Sorry if my explanation was not clear :)

I don't understand either. I tried to figure it out, but don't have any more time to spend on it.

While investigating I saw some strange behavior sometimes where the current store code was not set in `window.__INITIAL_STATE__.user.current_storecode`. This could be the cause, but I'm not sure

**Comment by andrzejewsky** [comment]
it could be something related to the templates, we'll have a look
