### ISSUE TITLE
consider full url path for categories for more SEO friendly URLS

### ISSUE THREAD

**Issue by janmyszkier** [DivanteLtd/vue-storefront#3891]
## What is the motivation for adding / enhancing this feature?
To have more friendly URLS with bigger stores

## What are the acceptance criteria 
it should be possible for full category url_path to be unique:
men/coats/fancy-coats
women/coats/fancy-coats

currently only `fancy-coats` is used to figure out which category to show (so it will fail, because `fancy-coats` nor `coats` is unique for the whole store), but we need to consider the whole path to use more SEO friendly URLs.

Right now we can only do:
men/coats/fancy-coats
women/coats-1/fancy-coats-1

## Can you complete this feature request by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
This should be part of the `develop`.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
@janmyszkier I'm not sure if this is a request to the indexer/mage2vs? Because from the VSF point of view you can have whatever you like in the `url_path` - so it's probably not a FR to VSF itself, isn't it?

**Comment by lukeromanowicz** [comment]
Closing due to OP inactivity.
