### ISSUE TITLE
Categories and products show up on magento default page, but not on vuestorefront

### ISSUE THREAD

**Issue by abdulbar** [DivanteLtd/vue-storefront#3893]
Hi Everyone. I have installed Vue and Magento 2.3 on localhost on Linux, and used fast integration method.
Vsf-frontend and api are running fine without any errors. I have used custom theme for the frontend, and can see the homepage as well.
When I run `sudo yarn mage2vs import` I can see my categories and products in the API terminal as well.

When I try to access the categories using `http://localhost:3000/c/mycategoryname`it takes me to page-not-found.

I can see the categories and products on magento homepage though.

Does anyone know what I'm missing here?
It would mean alot to me if someone helped me with this question.
Thank you.

**Comment by lukeromanowicz** [comment]
Please try using native magento-vue storefront indexer instead of legacy javascript: https://github.com/DivanteLtd/magento2-vsbridge-indexer
