### ISSUE TITLE
Account + Wishlist and search icons on Mobile

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#391]
@karolbzik how it should look like on smartphone resolution? Now account and search icons are simply hidden

**Comment by karolbzik** [comment]
@pkarw on mobile we should extend sidebar navigation with search and wishlist buttons on the top
<img width="360" alt="sidebar menu on mobile" src="https://user-images.githubusercontent.com/18116406/33961347-0938f5ba-e04e-11e7-8130-4c447ec75ea5.png">

**Comment by pkarw** [comment]
@collymore could you take care of this one guys? it's for next release

**Comment by collymore** [comment]
Yes will get this done
