### ISSUE TITLE
Can't build storefront npm.

### ISSUE THREAD

**Issue by DJ-DESIGN** [DivanteLtd/vue-storefront#3911]
Noob here... 
I am running all latest versions and have been going through all documentation without any luck to resolve my issue. I have seen similar issues but no clear instruction on how to fix. 

The furthest I was able to get was here in the VS doc(How to prevent an error "Can’t build storefront npm"): 
https://docs.vuestorefront.io/guide/basics/recipes.html#how-to-get-dynamic-prices-to-work-catalog-rules
–which I then followed but still get the same issue as when I try the "easy setup" (https://docs.vuestorefront.io/guide/general/introduction.html#installing-vue-storefront)

I've scoured the forum and anywhere else I can to find a solution... no luck. :(

Problem I am having is that node(correct me if I'm wrong) is failing to build Vue Storefront. I've checked the log file but really am not savvy enough to know what to make of it other than it's failing at the installer script and "There is likely additional logging output above.":
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-storefront@1.10.5 installer: `node ./core/scripts/installer`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-storefront@1.10.5 installer script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Any help would be greatly appreciated. Looking forward to getting this up and running. Thanks!

**Comment by pkarw** [comment]
Please check your node version; it’s hard to say anything more without the logs provided

**Comment by dhaval-dev** [comment]
@DJ-DESIGN Did you get any solution? I am getting same issue.

**Comment by DJ-DESIGN** [comment]
Ok, thanks. I'm on version: 10.15.1

**Comment by DJ-DESIGN** [comment]
I had a typo(space) in one of my project directory folder names. Breaking my build. The error log explained it. I'm still learning... Thanks for responding!
