### ISSUE TITLE
Order-history request not fetching data

### ISSUE THREAD

**Issue by serzilo** [DivanteLtd/vue-storefront#3923]
## Current behavior
I am authorized user. After some time my token is invalidated. I go to cart and refresh page. I see many refresh and order-history requests.  

![image](https://user-images.githubusercontent.com/2085355/71071890-7ded5580-218e-11ea-9e39-831e92811244.png)

I think, the problem is that order-history request doesnt use new token.,

## Expected behavior
I am authorized user.

**Comment by pkarw** [comment]
@serzilo can you provide us with the error message `order-history` is returning or the `vue-storefront-api` output log?

**Comment by serzilo** [comment]
I think bug is here:
core/lib/sync/task.ts
![image](https://user-images.githubusercontent.com/2085355/71081107-9f0a7200-219f-11ea-81f6-ea1ae9545c14.png)

**Comment by pkarw** [comment]
@gibkigonzo can you please take a look?

**Comment by andrzejewsky** [comment]
got it, our token is not really invalidated, I mean it is, but it is not stored in the localStorage - just noticed that error in the code, I'll fix today.
