### ISSUE TITLE
Memory leak when dynamicConfigReload enabled

### ISSUE THREAD

**Issue by maikel-code** [DivanteLtd/vue-storefront#3925]
## Current behavior

With dynamic config relaod enabled, the memory the instance consumes, rises slowly but constantly. 
Happens on kubernetes.
We could fix that problem with reloading the config only once, as we need ENV vars inside config, which are available after build is done. You can see the difference in the image: 
![memory leaking graph](https://user-images.githubusercontent.com/17151530/71079778-2f3ebc00-218c-11ea-9728-e42655f3faae.png)

## Expected behavior

Consumed memory doesn´t rise over time, when config is reloaded
I´m supposing, that deleting `cachedConfigModule` or `require.cache` is causing that steady rise. 
Also the config is assigned twice Line 277 and 298, I suggest some refactoring at this point. 

## Steps to reproduce the issue

Enabled dynamicConfigReload option, run it on docker / kubernetes and check memory rise after a bnuch of request (We have health checking which checks the page every second)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome 78
- OS: on kubernetes with image: node:12.13.0-buster-slim
- Node: 12.13
- Code Version: release/v1.11

## Additional information

Related issue: [#3075 ](https://github.com/DivanteLtd/vue-storefront/issues/3053)

**Comment by pkarw** [comment]
Thanks! Good point. @gibkigonzo I guess you were debugging some memory leaks recently and maybe can take a look?

**Comment by andrzejewsky** [comment]
I'm wondering if should we even use dynamic reloading in the production mode, what do you think @pkarw ?

**Comment by pkarw** [comment]
@andrzejewsky we should :) It's very useful when scaling up the application etc. @mkoszutowski is using this feature on storefrontcloud.io as well

**Comment by maikel-code** [comment]
An idea: Reload config only when smth has changed

**Comment by pkarw** [comment]
@maikel-code yeah that's an easy option I guess (with some kind of hashing)

**Comment by andrzejewsky** [comment]
@maikel-code I was looking for what causes that problem and I came across to the line with extending the config.

Could you please change the line
```
config = config.util.extendDeep(config, loadedConfig)
```
to:

```
config = config.util.extendDeep({}, config, loadedConfig)
```

I tested this one with a status that pm2 shows and seems like it solves that problem (memory doesn't increase or is balancing). It's really hard to confirm that so I would appreciate that if you can do this short test.

**Comment by maikel-code** [comment]
The if clause for configProvider Extension is not being executed, as I don´t use config extension modules. So your propsed fix won´t be executed
It´s basically all about these lines:
```
if (config.server.dynamicConfigReload) {
    const cachedConfigModule = require.cache[require.resolve('config')]
    if (cachedConfigModule) {
      delete cachedConfigModule.parent.children
      delete require.cache[require.resolve('config')]
    }
    config = require('config') // reload config
    ....
}
```

**Comment by gibkigonzo** [comment]
```
  if (config.server.dynamicConfigReload) {
    const cachedConfigModule = require.cache[require.resolve('config')]
    if (cachedConfigModule) {
      delete cachedConfigModule.parent.children
      delete require.cache[require.resolve('config')]
    }
    if (configProviders.length > 0) {
      configProviders.forEach(configProvider => {
        if (typeof configProvider === 'function') {
          configProvider(req).then(loadedConfig => {
            config.util.extendDeep(config, loadedConfig)
            dynamicCacheHandler()
          }).catch(error => {
            if (config.server.dynamicConfigContinueOnError) {
              dynamicCacheHandler()
            } else {
              console.log('config provider error:', error)
              if (req.url !== '/error') {
                res.redirect('/error')
              }
              dynamicCacheHandler()
            }
          })
        }
      })
    } else {
      dynamicCacheHandler()
    }
  } else {
    dynamicCacheHandler()
  }
```
Generally I have removed config reassignment because we change it by ref anyway, so there is no point to do that. And after some snapshots in devtools it looks pretty good. @maikel-code Can you test it in your env?

**Comment by pkarw** [comment]
@gibkigonzo can we close this one already? We were just waiting for the feedback from @maikel-code tests aren’t we?
