### ISSUE TITLE
Multi Shipping

### ISSUE THREAD

**Issue by KevinGorjan** [DivanteLtd/vue-storefront#3926]
Hi

I've got a question for multi-shipping. Why does VueSF API only let me use 2 addresses? 
In the documentation, there is mentioned that VueSF has "Multiple shipping address management". I searched in the code but it seems all is restricted to "Shipping-" and "Billing-"address. Or do I miss something?
 
https://github.com/DivanteLtd/vue-storefront/blob/master/docs/guide/basics/feature-list.md#vue-storefront-magento2-support

Please answer the following questions for yourself before submitting an issue. 
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Check our forum:
We tried this solution, but it failed.
https://forum.vuestorefront.io/t/getting-issue-when-saving-address-from-my-account-section/701

**Comment by pkarw** [comment]
Hi @KevinGorjan I guess it's actually a good idea for a Pull Request! The limitation is actually just the UI one so can be easily re-configured

**Comment by pkarw** [comment]
... oh there is already a module for this: https://github.com/aureatelabs/vsf-address-book :-)

**Comment by SodHub** [comment]
Address book (add, edit, delete addreses) is not a multishipping feature. 
Multishipping in M2 is when you can ship to different addresses

**Comment by sudma** [comment]
> Address book (add, edit, delete addreses) is not a multishipping feature.
> Multishipping in M2 is when you can ship to different addresses

I think that the multi shipping can't be supported OOTB because of the Magento side limitations in the **Magento_Multishipping** module which does not have any API endpoints exposed for the multi shipping functionality. Magento multi shipping checkout is fully Controller based implementation without API usage.
