### ISSUE TITLE
Microcart/Product.vue don't use sourcePriceIncludesTax from  

### ISSUE THREAD

**Issue by Devors** [DivanteLtd/vue-storefront#3927]
## Current behavior
price-special includes tax twice when totals.discount_amount exist.

## Expected behavior
adding tax should be included depending on config. (sourcePriceIncludesTax)

## Steps to reproduce the issue
- sourcePriceIncludesTax: true
- add product with discount_amount to cart
- special price includes tax twice

## Repository
https://github.com/DivanteLtd/vue-storefront/blob/develop/src/themes/default/components/core/blocks/Microcart/Product.vue#L77

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ * ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [*] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [*] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [*] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
Does not matter. Template issue.

**Comment by pkarw** [comment]
The totals are not touched by VSF at all. They're provided by the MAgento. Make sure your tax configuration is aligned with backend/Magento config
