### ISSUE TITLE
Extendable Elasticsearch queries

### ISSUE THREAD

**Issue by Fifciu** [DivanteLtd/vue-storefront#3934]
## What is the motivation for adding / enhancing this feature?

When we are working on more advanced projects. We always need to create some custom stuff in ES queries. Custom aggregations, faceted filters or whole queries, e.g. for category view. It would be amazing if we could easily modify them (maybe from module?). Currently, it requires workarounds which is not a pleasure.

There should be some well-documented standards for that.

I think we should discuss about possibilities and ideas because it looks like big and so useful thing.

## What are the acceptance criteria 

- [ ] Standard for extending queries that VSF uses internally (maybe as one of new hooks?)
- [ ] Well documentation of that with use cases (it is essential)

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pablogiralt** [comment]
+1

**Comment by gibkigonzo** [comment]
there is an option to extend it by adding custom filter in `storefront-query-builder` https://github.com/DivanteLtd/storefront-query-builder/issues/1#issuecomment-579350403
