### ISSUE TITLE
How to use Docker in live server 

### ISSUE THREAD

**Issue by Sabari181** [DivanteLtd/vue-storefront#3944]
I have only 4gb server so i cant install redis and elastic search on 4gb server just i need to know how to use docker on my live server

**Comment by andrzejewsky** [comment]
Hello @Sabari181 

Actually you mentioned that you can't use ES and Redis and you are asking about using a docker? I didn't really understand what you mean. I think you have noticed that our docker-compose files install ES and Redis itself and you probably asking about setting up VSF without them but with using docker? Am I right?

First of all, you can install VSF without VSF-API but you need to have VSF-API somewhere, it could be on a different server but you need this for reading the catalog. VSF-API doesn't work without ES, unless you will use a different configuration / customized catalog storage - everything depends on your case... by default VSF-API stores catalog in the ES.

more information you can find in our docs: https://docs.vuestorefront.io/
