### ISSUE TITLE
Optimize the `setupBreadcrumbs` for the PDP

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3951]
## What is the motivation for adding / enhancing this feature?

We can optimize how [the breadcrumbs are set](https://github.com/DivanteLtd/vue-storefront/blob/19a7c2f836209a57089be6dc2d5413c58032c1fc/core/modules/catalog/store/product/actions.ts#L72) - first we can limit the `category/list` calls to just single one (including multiple category ids) - getting just the parent category + it's `path` as [it's done on `category` page:](https://github.com/DivanteLtd/vue-storefront/blob/19a7c2f836209a57089be6dc2d5413c58032c1fc/core/modules/catalog-next/store/category/actions.ts#L197)

then .. the even better way would be to move the `breadcrumbs` logic to the `storefront-api` or `vue-storefront-api` (or both). There is [an issue for that](https://github.com/DivanteLtd/storefront-api/issues/7)

## What are the acceptance criteria 

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by andrzejewsky** [comment]
@pkarw this file you mentioned is not even called. On the product page, we also have [loadProductBreadcrumbs](https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/catalog/store/product/actions.ts#L684) that calls `category-next/loadCategories` only once, I mean the [api call](https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/catalog-next/store/category/actions.ts#L145) inside of it is called just once

**Comment by gibkigonzo** [comment]
moved to storefront-api https://github.com/DivanteLtd/storefront-api/pull/71
