### ISSUE TITLE
404 handled incorrectly

### ISSUE THREAD

**Issue by jonathanribas** [DivanteLtd/vue-storefront#3956]
## Current behavior
If I access a random URL like https://demo.vuestorefront.io/test.html, I'm getting a timeout

## Expected behavior
I should see a proper 404 Page Not Found.

## Steps to reproduce the issue
Access a random URL like https://demo.vuestorefront.io/test.html and you will have a timeout:

<img width="1675" alt="Screen Shot 2019-12-27 at 14 59 34" src="https://user-images.githubusercontent.com/3003782/71519879-a295ab80-28b9-11ea-99cb-c40d8a87dfb1.png">

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome 79
- OS: Mac OS
- Node: 10
- Code Version: Tag v1.10.5

**Comment by pkarw** [comment]
Apparently this bug is related to 1.10 as it doesn’t occurs in 1.12: http://test.storefrontcloud.io/hdhd

**Comment by jonathanribas** [comment]
This bug occurs on 1.11.0 also.
