### ISSUE TITLE
Overlay still active after closing modal component

### ISSUE THREAD

**Issue by bottle93** [DivanteLtd/vue-storefront#3970]
## Current behavior

Overlay needs to be double-clicked to close, after modal disappear.

## Expected behavior

Overlay to disappear after closing modal

## Steps to reproduce the issue

Even on demo.storefrontcloud.io when you subscribe to the newsletter, you have to double-click to get rid off the overlay after clicking the "subscribe" button
![Selection_022](https://user-images.githubusercontent.com/20922778/71729024-003c7180-2e3f-11ea-8233-f3ffdd38ca35.png)
![Selection_023](https://user-images.githubusercontent.com/20922778/71729035-05012580-2e3f-11ea-8f47-ec6b6cf928aa.png)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by andrzejewsky** [comment]
@bottle93  thanks for reporting! 
@gibkigonzo it's probably related also to sidebar logic and cart edit mode

**Comment by gibkigonzo** [comment]
I could reproduce this only on 1.10.5 and here is backport https://github.com/DivanteLtd/vue-storefront/pull/3973 In 1.11 it works ok
