### ISSUE TITLE
Cart sync issue on products with custom options

### ISSUE THREAD

**Issue by ktopouzi** [DivanteLtd/vue-storefront#3976]
## Current behavior

Here I am again with another bug I found with custom options. This time I believe this affects the `Microcart` component and the quantity/totals synchronizations. In my example, I got several products with custom options and 4-5 simple products. 

I added the product **with** custom options in cart.

![Screenshot from 2020-01-08 17-21-41](https://user-images.githubusercontent.com/15310054/71990150-91df2100-323b-11ea-94fd-bf673b0a4360.png)

As you can see the green indicator **In stock** is not available, even though the quantities are synced correctly.

Now I add the product **without** custom options.

![Screenshot from 2020-01-08 17-22-21](https://user-images.githubusercontent.com/15310054/71990281-c5ba4680-323b-11ea-944f-952c42363e65.png)

Here you can see that the **In stock** label is shown. Also notice the total price of cart. It's calculated based on the last product (w/o custom options)

If I try to change the second product quantity, it is applied successfully. On the other hand when I change the quantity of the first product I get the following error, the totals are not updated and the quantity is not applied.

![Screenshot from 2020-01-08 15-50-43](https://user-images.githubusercontent.com/15310054/71990485-221d6600-323c-11ea-97a0-28c58a3e12b3.png)

**In addition** I just realized that if you refresh the page the quantities of products **with** custom options are doubled while the quantities of the other products are not affected. 

## Expected behavior

Both products, regardless they have custom options or not should be able to be modified inside Microcart.

## Steps to reproduce the issue
 - Create a M2 shop
 - Create a product with custom options and one simple without any options
 -  Pump the products in the VSF instance.
 - Add the two products in cart
 - Change the quantity on both products

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [X] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome Version 78.0.3904.108 (Official Build) (64-bit)
- OS: Ubuntu 18.04
- Node: v10.17.0
- Code Version: v1.11.0-rc.2

**Comment by pkarw** [comment]
Related issues: #3595, #3885

**Comment by gibkigonzo** [comment]
Hello :) I see this problem with "In stock" information, but I can't reproduce problem with quantity on https://next.storefrontcloud.io/ 

1. Added product with custom options:
![Zrzut ekranu z 2020-01-09 07-24-47](https://user-images.githubusercontent.com/42383376/72043319-259f0480-32b1-11ea-8111-25b526e43cf3.png)

2. Added simple product:
![Zrzut ekranu z 2020-01-09 07-26-21](https://user-images.githubusercontent.com/42383376/72043438-6dbe2700-32b1-11ea-9a7c-98644a6a0ff9.png)
and it looks ok. Previously was 101.72 + 23.37 + 15 (shipping increased) = 140.09
I don't have error in console when I change quantity. Can you please reproduce this problem on https://next.storefrontcloud.io ? @ktopouzi

**Comment by ktopouzi** [comment]
Hey @gibkigonzo, thank you so much for your reply and effort on this one. The dead line for my  project is really close and I have been struggling with custom options.

I have recorded a gif showing the exact issue on the latest version (same as https://next.storefrontcloud.io/) using the same set of products. I hope its clear enough. If I can do anything else please let me know I would be more than willing to help ( If only I could solve those on my own)

![Peek 2020-01-09 21-13](https://user-images.githubusercontent.com/15310054/72097527-4012c580-3325-11ea-9137-c485981ad87b.gif)

**Comment by andrzejewsky** [comment]
when @gibkigonzo finishes, I'll apply this fix in the upcoming release (1.11.1), there are other bugfixes and I think it's high time for release. @ktopouzi is that ok for you?

**Comment by gibkigonzo** [comment]
@ktopouzi thanks for this gif :) Please check out this pr https://github.com/DivanteLtd/vue-storefront/pull/3977 I reproduced it but would be great if you could check it.
