### ISSUE TITLE
Some question need clearly? 

### ISSUE THREAD

**Issue by clickgumshoe** [DivanteLtd/vue-storefront#3983]
I will use WordPress woocommerce as backend store.
I wondering how to manage orders, customers either in WordPress or vuestorefront admin ?
Data in storefront & woocommerce are synced whenever customer made a order? I mean orders & customers data in both platform?
Many thanks if you answer to my stupid question?

**Comment by pkarw** [comment]
Hi; Vue Storefront doesn't have admin panel. It's just a frontend. WooCommerce it's not 100% supported, and it's not officialy supported at the moment :(
