### ISSUE TITLE
Endless loop redirect in production setup - NGINX/VARNISH

### ISSUE THREAD

**Issue by gcampedelli** [DivanteLtd/vue-storefront#3992]
## Current behavior
Install on local and it works
Install VueStoreFront Production Setup it creates redirect loop
Server Ubuntu 18.04
Varnish => configured for multiple backends. If we dont config backends in Varnish for VueStorefront ports (api and vuestorefront) we get 502 bad gateway. 
Elasticsearch same version of tutorial
Complete tutorial and yarn start in both folders
Result => able to access myvuestore.domain/api
Redirect Loop in myvuestore.domain

## Expected behavior
Access VueStorefront without errors
## Steps to reproduce the issue

Install VueStoreFront setup in Ubuntu 18.04
Use LetsEncrypt
Apply the directive return 301 on server 8080 (we can't bind to port 80 while using varnish as it is already in use for it)
If remove directive 301 we get 403 unathorized

## Repository
Master Branch with redirect loop fix merged, but I found someone who was having same problem

## Can you handle fixing this bug by yourself?
No. I tried every possible NGINX/VARNISH configuration. 
We also get an error in webpack undefined for = index.minimal etc which is also described here but for docker install

- [ ] YES
- [ X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: All
- OS: Ubuntu 18.04
- Node: v10.18.1
- Code Version: Magento 2.3.3. VueStoreFront is master branch.

**Comment by pkarw** [comment]
@kkdg can you please take a look?

**Comment by kkdg** [comment]
@gcampedelli Which tutorial were you referring to? 
https://docs.vuestorefront.io/guide/installation/production-setup.html <-- this one?

**Comment by gcampedelli** [comment]
Yes, this one. I tried to reinstall again  with default configuration I get 502 error on vue-storefront. 
I tried to apply a patch concerning ecosystem.json without much luck. 
 I also tried to check some logs and I get this error while I execute "yarn pm2 logs" => 
" SyntaxError: Unexpected token {
3|server   |     at Module._compile (internal/modules/cjs/loader.js:723:23)
3|server   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
3|server   |     at Module.load (internal/modules/cjs/loader.js:653:32)
3|server   |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
3|server   |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
3|server   |     at /usr/lib/node_modules/pm2/lib/ProcessContainer.js:297:23
3|server   |     at wrapper (/usr/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
3|server   |     at next (/usr/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
3|server   |     at /usr/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
3|server   |     at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:186:13)
3|server   | 2020-01-19 21:45:27: WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
3|server   | 2020-01-19 21:45:27: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
3|server   | 2020-01-19 21:45:27: WARNING: NODE_APP_INSTANCE value of '3' did not match any instance config file names.
3|server   | 2020-01-19 21:45:27: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode"

**Comment by kkdg** [comment]
Thanks, let me work on this

**Comment by gcampedelli** [comment]
Now, after changing ecosystem.json again I have:

 import { serverHooksExecutors }  from '@vue-storefront/core/server/hooks'
1|server  |        ^
1|server  | SyntaxError: Unexpected token {

Same error as someone else. 

ecosystem.json is: 
{
  "apps": [
    {
      "name": "server",
      "max_memory_restart": "1G",
      "instances": "4",
      "exec_mode": "cluster",
      "env": {
        "TS_NODE_PROJECT": "tsconfig-build.json",
        "NODE_ENV": "production"
      },
      "interpreter": "./node_modules/.bin/ts-node",
      "script": "./core/scripts/server.ts",
      "args": "-P ./tsconfig-build.json",
      "node_args": "--max_old_space_size=1024",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "ignore_watch": [
        "core/build/config.json",
        "node_modules"
      ]
    }
  ]
}

**Comment by gcampedelli** [comment]
Hello, I changed it more to this. My ecosystem.json is now like this: 

```
{
  "apps": [
    {
      "name": "server",
      "max_memory_restart": "1G",
      "instances": "4",
      "exec_mode": "fork",
      "env": {
      "NODE_ENV": "development",
    },
    "env_production": {
      "NODE_ENV": "production",
    },
      "interpreter": "./node_modules/.bin/ts-node",
      "script": "./core/scripts/server.ts",
      "args": "-P ./tsconfig-build.json",
      "node_args": "--max_old_space_size=1024",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "postinstall": "$(yarn bin)/pm2 install typescript",
      "ignore_watch": [
        "core/build/config.json",
        "node_modules"
      ]
    }
  ]
}
```
And Nginx is like this

```
server {
        listen 8080;
	server_name vfs.mydomain;
	return 301 https://vsf.mydomain$request_uri/;
}

server {
    
	listen 443 ssl;
        server_name cr.m2app.cloud;
	ssl on;
        ssl_certificate /etc/letsencrypt/live/cr.m2app.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cr.m2app.cloud/privkey.pem;
          
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_prefer_server_ciphers on;	
	ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA;
	ssl_ecdh_curve secp384r1;
	ssl_session_tickets off;
	ssl_stapling on;
	ssl_stapling_verify on;
	resolver 8.8.8.8 8.8.4.4 valid=300s;
	resolver_timeout 5s; 


	add_header Strict-Transport-Security "max-age=31536000" always;
	add_header X-Frame-Options DENY;
	add_header X-Content-Type-Options nosniff;
	add_header X-XSS-Protection "1; mode=block";
	add_header X-Robots-Tag none; 

	gzip on;
	gzip_proxied any;
	gzip_types
		text/css
		text/javascript
		application/javascript
		application/json
    text/xml
		text/json;

	location / {
    proxy_pass http://cr.m2app.cloud:3008/;

	}

	location /assets/ {
		proxy_pass http://localhost:3008/assets/;   //I have changed the port only here. In vue-storefront local.json it remains por 3000. 
	}

    location /api/ {
		proxy_pass http://localhost:8081/api/;
	}

    location /graphql {
		proxy_pass http://localhost:8081/graphql;
	}
  
    location /img/ {
		proxy_pass http://localhost:8081/img/;
	}
}
```

**Comment by andrzejewsky** [comment]
@gcampedelli Hey try to install ts-node (`npm add ts-node --save-dev`) and use the following ecosystem config:

```
{
  "apps": [
    {
      "name": "server",
      "max_memory_restart": "1G",
      "instances": "4",
      "exec_mode": "cluster",
      "env": {
        "TS_NODE_PROJECT": "tsconfig-build.json",
        "NODE_ENV": "production"
      },
      "interpreter": "./node_modules/.bin/ts-node",
      "script": "./node_modules/.bin/ts-node",
      "args": "-P ./tsconfig-build.json ./core/scripts/server.ts",
      "node_args": "--max_old_space_size=1024",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "ignore_watch": [
        "core/build/config.json",
        "node_modules"
      ]
    }
  ]
}
```

**Comment by gcampedelli** [comment]
Ok, I tried it bow I get this in logs ```
"TSError: ⨯ Unable to compile TypeScript:
2|server   | core/scripts/server.ts(1,39): error TS2307: Cannot find module '@vue-storefront/core/server/hooks'."
```

**Comment by gcampedelli** [comment]
And after trying to debug nginx curl gives me => curl http://localhost:3001
Found. Redirecting to /error

So still in the subject of this issue - Endless redirect

**Comment by gcampedelli** [comment]
Hello, after a while, I got it, almost working without the redirect. I moved vuestorefront files to magento2 root. And I had to declare localhost as 0.0.0.0. There is no more redirect loop.
