### ISSUE TITLE
issue with defined variables that are not working

### ISSUE THREAD

**Issue by mahmoudzalik** [DivanteLtd/vue-storefront#3996]
![issue 2](https://user-images.githubusercontent.com/59918102/72671271-55d46900-3a50-11ea-8f5e-eefc9801217d.png)
 i have defined card_category in line 14 and txt_category_name in line 15 but as u can see in lines 19 and 20 i get error when i try to use them 

thanks in advance for help
 i am still a rookie :)

**Comment by andrzejewsky** [comment]
@maciejtrybula How is that related to the vue-storefront? I can't see any connection here...

PS. Android SDK hmm.. check your XML files, you maybe didn't declare something under that key
