### ISSUE TITLE
Lots of filters breaks the Category page

### ISSUE THREAD

**Issue by KevinGorjan** [DivanteLtd/vue-storefront#4003]
## Current behavior
For our client, we have 29 different filters.
`["category", "new", "collar", "material", "gender", "performance_fabric", "format", "color", "features_bags", "category_gear", "size", "eco_collection", "style_bottom", "style_general", "price", "activity", "strap_bags", "mp_reward_sell_product", "manufacturer", "style_bags", "erin_recommends", "sale", "sleeve", "pattern", "climate", "brand", "tv_size", "tv_features", "capacity", "air_conditioners_features"]` and may all be Genereic. 

But when we go to the Category page, I always receive the following errors:
- No products syncronized...
- Product, category, CMS Page not found, ...

Is there a limit what VueSF can handle? Because we get a response back from Elastic Search?

## Expected behavior

See all the filters we need to see.

## Steps to reproduce the issue
/

## Repository
Master (v1.11)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

**Comment by Fifciu** [comment]
Check network tab. Maybe in response you have ElasticSearch error which could be so helpful for us.

**Comment by revlis-x** [comment]
I experienced server errors with loooong GET-Request and various servers. Hace you tried switching to POST in config value elasticsearch.queryMethod.

**Comment by KevinGorjan** [comment]
Hi @Fifciu 
I checked the network tab and as I mentioned above, I receive a valid response from ES, but I think there is something wrong for handling the data in VueSF.
---
Hi @revlis-x 
We also tried to switch to POST, but it has the same outcome.
If you have problems with long GET-requests, you can increase the "max-http-header-size" of the VueSF API to "16384". In NodeJS v10 and higher, they decreased it.

Example in package.json:
> "dev": "NODE_OPTIONS=--max-http-header-size=16384 nodemon"

**Comment by andrzejewsky** [comment]
@KevinGorjan seems like `product/list` action returns empty response (ref: https://github.com/DivanteLtd/vue-storefront/blob/f3c218d7a202718915d13a87f09ee57a04396c0b/core/modules/catalog/store/category/actions.ts#L236) - please double-check what comes from API/ES in the network tab, make sure  there is a response object that contains a products

**Comment by pkarw** [comment]
@KevinGorjan any feedback on the vsf-api results (after checking what @andrzejewsky suggested?)

**Comment by fabianeichinger** [comment]
For anyone struggling with this: The problem seems to be that the request url becomes so large that it exceeds the `maxHeaderSize` limit for the `http` server in storefront-api (for us it seems to default to 16kb in Node 14). We've increased the limit (https://github.com/expressjs/express/issues/4131#issuecomment-565655526) to 32kb, which is enough for our filters, but obviously for even more filters you might need to look into ways to optimize the request.
