### ISSUE TITLE
Breadcrumbs not considering "categoriesRootCategorylId"

### ISSUE THREAD

**Issue by simonmaass** [DivanteLtd/vue-storefront#4027]
## Current behavior

When setting categoriesRootCategorylId the breadcrumbs still show categories above that root category id

## Expected behavior

When setting categoriesRootCategorylId i would expect the breadrumbs not showing any category that lies above this root category.

## Steps to reproduce the issue

Set categoriesRootCategorylId to a lower category in level 2 or 3 for example. go to product page and check breadcrumbs

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  Chrome79.0.3945.130 (64-Bit)
- OS:  Windows 10
- Node:  10
- Code Version:  1.11

**Comment by simonmaass** [comment]
also it looks like breadcrumbs are generated differently on server and client side...

**Comment by grimasod** [comment]
@simonmaass How about using a category filter or breadcrumb filter? They were introduced in v1.11.0 for exactly this purpose. See
https://docs.vuestorefront.io/guide/upgrade-notes/#_1-10-1-11

For example:

`"breadcrumbFilterFields": { "level": {"gt": 1} }` = only categories above level 1 (the Default Category in Magento). 

`"breadcrumbFilterFields": { "level": {"lte": 3} }` = only categories equal to or below level 3

`"breadcrumbFilterFields": { "level": [2,3] }` = only level 2 and level 3 categories

**Comment by grimasod** [comment]
It's still a bug, because `categoriesRootCategorylId` wasn't officially deprecated. However, in previous versions

- It applied to any category query, not just breadcrumbs
- It's the root, ie **minimum**, not max ID
- It works on the Category **ID**, not the level
- This is flawed, because IDs are often not in numerical order in Magento and are not even numerical in some other backend systems
- it has a spelling mistake categoriesRootCategory**l**Id

So, maybe it should just be dropped and this information added to the upgrade note

**Comment by grimasod** [comment]
> breadcrumbs are generated differently on server and client

Is it using the `catalog` store somewhere in the theme? It should be using `catalog-next` only.

Another way this can happen is when the product is in multiple categories. If you browse from Category to Product, the last browsed Category will be used in the breadcrumbs (if it can be). But when calculated on the sever, there's no current Category and there's no way to know which is the preferred Category, so the deepest Category is chosen. I don't think there's any way around this in 100% of all situations.

It can be improved by using a breadcrumb filter and turn off the "Include in Menu" setting (in Magento) for the Categories that you don't want to appear.

`"breadcrumbFilterFields": { "include_in_menu": true }`

**Comment by simonmaass** [comment]
@grimasod thank you for the very detailled response. I am fine with switching to the filter functionality... I guess `categoriesRootCategorylId` should really then be deprecated...

As you said.. its technically a bug but if it really should be deprecated i guess there is no point in fixing...

**Comment by Michal-Dziedzinski** [comment]
@grimasod @simonmaass is my change in PR above useful for you?

**Comment by simonmaass** [comment]
i went with "breadcrumbFilterFields": { "is_active": true, "include_in_menu": 1, "level": {"gt": 2} }

**Comment by grimasod** [comment]
@Michal-Dziedzinski thanks for asking, but I don't have any issue, just giving information. 
As I explained above and in a comment on your PR, categoriesRootCategorylId doesn't work for me.
So, I also use breadcrumbFilterFields, that I added for this purpose.

**Comment by andrzejewsky** [comment]
Ok so, I'm closing this issue, thanks 👍
