### ISSUE TITLE
Category amp page - No products found

### ISSUE THREAD

**Issue by dmytrokravch** [DivanteLtd/vue-storefront#4047]
## Current behavior

Products array is empty on each category amp page
Exemple: 
https://test.storefrontcloud.io/amp/c/all-2

## Expected behavior
There should be products

## Steps to reproduce the issue
Open any category amp page

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
Browser: Chrome
OS: Windows 10
Node: v10
Code Version: v1.11

**Comment by pkarw** [comment]
The `amp-renderer` module just got removed from 1.12rc1 (`develop branch`) it's hard for us (the core team) to fix it and maintain in 1.11. However we're open to any contributions
