### ISSUE TITLE
Clear cart not working when logged in (v1.11.1)

### ISSUE THREAD

**Issue by grimasod** [DivanteLtd/vue-storefront#4062]
## Current behavior

Clicking the "Clear cart" button only clears the cart in the client, not on the backend server. After reloading the page the previous cart contents reappear. Other problems can occur because of this, like quantities multiplying in the cart.

The Microcart `clearCart` method calls the `cart/clear` action, which deletes the server token. When `cart/sync` is called next, the server cart can't be synchronized. 

## Expected behavior

Clearing the cart should result in an empty cart on the server.

## Repository

1. Log in and add an item to the cart
2. Open Microcart and click "Clear cart"
3. Reload the page
4. The product is in the cart again

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version: v1.11.1

## Additional information

New in v1.11.1

**Comment by pkarw** [comment]
@gibkigonzo this came out after lazy cart change I guess. We need to make sure it works just fine in the 1.10.x as well. I saw that the user token is not cleared out - on Slack. It might cause this issue as well
https://vuestorefront.slack.com/archives/C7G188MFZ/p1580817976041500

**Comment by gibkigonzo** [comment]
When you click 'Clear cart' then we remove cart items and cart token, after that we make sync with backend. And we can't make sync if token is removed. So I've changed a little bit clear/cart, we can now manage what exactly we want to clear related to cart https://github.com/DivanteLtd/vue-storefront/pull/4068 (I will make same pr for 1.11)
