### ISSUE TITLE
Module: Google Tag Manager - Order placement not working

### ISSUE THREAD

**Issue by simonmaass** [DivanteLtd/vue-storefront#4064]
## Current behavior

GTM event not fired when order placed

## Expected behavior

Event fired and data should be available in data layer.

## Steps to reproduce the issue

Place order and check Google Tag Manager debug console

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome
- OS: Windows
- Node: 10
- Code Version: v1.11

**Comment by simonmaass** [comment]
it also looks like only orders from registered users are tracked...

`store.dispatch(
          'user/getOrdersHistory',
          { refresh: true, useCache: false }
        ).then(() => {
          const orderHistory = state.user.orders_history
          const order = orderHistory.items.find((order) => order['entity_id'].toString() === orderId)`

**Comment by tonyisworking** [comment]
I have a version that addresses this issue and adds in most of the GTM EE tracking. I can submit a PR for it later after some clean up.

**Comment by simonmaass** [comment]
This is definately wrong:

```
// Measuring Purchases
      if (type === 'order/order/LAST_ORDER_CONFIRMATION') {
```

The mutations has an "s".. shoudl be 
```
// Measuring Purchases
      if (type === 'order/orders/LAST_ORDER_CONFIRMATION') {
```

**Comment by pkarw** [comment]
Hi Simon! Thanks can you please open a PR with a fix?

**Comment by simonmaass** [comment]
@pkarw yeah will do - currently in contact with @tonyisworking... one of us will open a PR!

**Comment by simonmaass** [comment]
nice @Michal-Dziedzinski looks good - thank you!
