### ISSUE TITLE
Category page is freezing for a moment when a filter is applied/removed multiple times

### ISSUE THREAD

**Issue by haelbichalex** [DivanteLtd/vue-storefront#4074]
## Current behavior

The category page is freezing when you apply or remove the same filter you already applied again.

## Expected behavior

The page should not freeze.

## Steps to reproduce the issue

1. Visit category page (https://next.storefrontcloud.io/women/women-20)
2. Apply filter once
3. Notice the blue progress bar is showing the full loading progression
4. Remove filter again
5. You can only see the ending of the progress bar animation

You can even "increase" the bug when enabling CPU throttling, for example in the Chrome Performance tab. In my case when setting it to 6x slowdown I can't even see the progress bar at all. This might apply for older smartphones or slow computers.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [X] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [X] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
Using VSF v1.11.0 or above

**Comment by gibkigonzo** [comment]
I can't reproduce it. Bar is displayed every time when filter changes
