### ISSUE TITLE
Wrong invitation link to Slack Community

### ISSUE THREAD

**Issue by emancypage** [DivanteLtd/vue-storefront#4081]
Request for Slack invitation, it seems that in readme and in doc links are outdated.

**Comment by pkarw** [comment]
@tom-aniol do we have it fixed?

**Comment by emancypage** [comment]
@pkarw it seems to be fixed yesterday :) but on github readme file only. In [doc ](https://docs.vuestorefront.io/guide/general/introduction.html#useful-links )it is still wrong.

**Comment by pkarw** [comment]
I’ve closed it as it’s seemingly fixed in the docs as well. Thanks!
