### ISSUE TITLE
Sidebar menu cannot have more than one custom submenu

### ISSUE THREAD

**Issue by themreza** [DivanteLtd/vue-storefront#4087]
## Current behavior

The links in the sidebar menu are mostly generated from the root categories, with the possibility of paged navigation to subcategories.

This works fine for categories, but there is a problem with having more than one custom multi-level menu item. The `sub-btn` expects a prop called `id` which, when provided, performs an ElasticSearch lookup for the specified category.

In the default theme, links to[ _My Account_ ](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/components/core/blocks/SidebarMenu/SidebarMenu.vue#L111)are implemented as a custom menu item, not passing the `id` prop. When having more than one custom menu item in this fashion, clicking on any other menu item shows the submenu for the first item (matching the first menu item that passed its content with a null `id` prop).

Here is an example, where I have a custom menu item. It works fine when the user is logged out, but as soon as My Account links are available, it doesn't go to the right submenu:
![](https://i.imgur.com/A4k4si8.gif)

## Expected behavior

The sidebar menu should have a feature to properly create custom multi-level menu items.
Instead of providing a null `id` prop, there should be another prop for these custom items.

## Repository

https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/components/core/blocks/SidebarMenu/SidebarMenu.vue#L111

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [X] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [X] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by themreza** [comment]
I've fixed it in my project this way:

SubCategory.vue:

* [Change to `v-if="myAccountLinks && !children.length"`](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/components/core/blocks/SidebarMenu/SubCategory.vue#L53)

SidebarMenu.vue:

* [Add `id="my-account-links"` and `:is-category="false"`](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/components/core/blocks/SidebarMenu/SidebarMenu.vue#L119)
* [Change to `id="my-account-links"`]()

SubBtn.vue:

* [Add a new prop `isCategory: {
      type: Boolean,
      default: true
    }`](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/components/core/blocks/SidebarMenu/SubBtn.vue#L29)
* [Change to `if (config.entities.category.categoriesDynamicPrefetch && this.isCategory) this.$store.dispatch('category/list', { parent: this.id })`](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/components/core/blocks/SidebarMenu/SubBtn.vue#L50)

![](https://i.imgur.com/wCuIvEp.gif)

**Comment by pkarw** [comment]
Cool! Can you please prepare a PR with these fixed to the core?

**Comment by andrzejewsky** [comment]
@themreza When it comes to PR - please use `hotfix/v1.11.2` branch, we'll include this one in the upcoming release

**Comment by themreza** [comment]
I will make a PR this week.

**Comment by pkarw** [comment]
@themreza I just wanted to kindly ask you about the status in here?
