### ISSUE TITLE
Filter use on Category Page throws error

### ISSUE THREAD

**Issue by domideimel** [DivanteLtd/vue-storefront#4093]
## Current behavior
When using the filter on the Category Page, vue router throws an error due to missing callback by applying the filter in here:

https://github.com/DivanteLtd/vue-storefront/blob/6c4d2333a0c4724655b3e0b058cc8303515279e8/core/modules/catalog-next/store/category/actions.ts#L202-L204

The reason is explained hier https://github.com/vuejs/vue-router/issues/2881#issuecomment-520554378

![Bildschirmfoto 2020-02-18 um 08 54 25](https://user-images.githubusercontent.com/32941053/74715192-4d787500-522c-11ea-93a6-7d358c7f81b0.png)

## Expected behavior
Just add the route Params for the filter without throwing an issue.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

just add a callback to it:

```javascript
async changeRouterFilterParameters (context, query) {
  router.push({[products.routerFiltersSource]: query}, () => {})
},
```

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Google Chrome Version 81.0.4044.17
- OS: Mac OS 10.15.3
- Node: 10.15.2
- Code Version: https://github.com/DivanteLtd/vue-storefront/tree/v1.11.0

**Comment by pkarw** [comment]
Cool! Can you please propose a PR with the suggested fix?

**Comment by domideimel** [comment]
> Cool! Can you please propose a PR with the suggested fix?

Sure, can you grant me access to propose a PR?

**Comment by pkarw** [comment]
@domideimel you don’t need special rights to create a PR - best option is to create one from your personal fork
