### ISSUE TITLE
Add PURGE support for cache invalidation 

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#4096]
## What is the motivation for adding / enhancing this feature?

Most CDN including even simple proxies like nginx support cache invalidation by specific urls. You can just send a request to remove specific url from cache on demand

VSF is invalidating cache by cache tags

https://docs.vuestorefront.io/guide/cookbook/checklist.html#_2-ssr-output-cache

We need to modify the cache invalidate method to properly map the cache tag to all related URLs:

https://github.com/DivanteLtd/vue-storefront/blob/6c4d2333a0c4724655b3e0b058cc8303515279e8/core/scripts/server.ts#L83

In order to do so we need to match the relative urls to the tags assigned to them where the cache is set:

https://github.com/DivanteLtd/vue-storefront/blob/6c4d2333a0c4724655b3e0b058cc8303515279e8/core/scripts/server.ts#L207

We should iterate thru “tagsArray” and store the proper mapping in the redis.

The easiest way would be to store each url in separate redis cache entry all tagged with the cacheTag from tagsArray (eg P123 for product 123)

Something like:

        cache.set(
          'url2tag:' + req.url + tag
          reqUrl,
          [tag]
        ).catch(errorHandler)

The other option would be to store the urls in single redis entry per tag. As the number of urls related to single url can be pretty high number it still shouldn’t be more than few dozen kB array or urls

Then, within the invalidate function:

https://github.com/DivanteLtd/vue-storefront/blob/6c4d2333a0c4724655b3e0b058cc8303515279e8/core/scripts/server.ts#L83

We need to take the urls assigned to specific tag use want to invalidate and then send the PURGE request to CDN providers configured in the:

config.cdn.purgeRequestsBaseUrls = [“https://CDN.yourdomain.com/“]

If config.cdn.enablePurgeRequests is set to true the PURGE requests are sent to all of those urls:

for(eachRelativeContentUrlsFromRedis){ 
do HTTP PURGE on purgeRequestBaseUrl + relativeContentUrlFromRedis
}

**Comment by pkarw** [comment]
Related to #3949

**Comment by pkarw** [comment]
Reference: https://docs.nginx.com/nginx/admin-guide/content-cache/content-caching/#purge

**Comment by pkarw** [comment]
Reference: https://docs.fastly.com/api/purge

**Comment by pkarw** [comment]
Reference: https://www.varnish-software.com/wiki/content/tutorials/varnish/vcl_examples.html

**Comment by pkarw** [comment]
@ResuBaka if you’d have some spare time there is a pretty cool task waiting for you to look, it will improve the VSF server side performance pretty significantly so we could use full page nginx caching with on demand invalidation. Yet it’s pretty easy and satisfying task   :-)

**Comment by nhp** [comment]
From personal experience: be very careful to not "overload" with too many requests. I can remember this kind of behavior in leads to varnish restarts if it is done too heavily. It is easy to generate thousands of requests in a short time after bigger updates, e.g. many products (couple of hundred) that are present on different categories can lead to multiple thousand PURGE requests easily.
No idea if nginx will handle heavy usage of this.

**Comment by pkarw** [comment]
https://docs.fastly.com/en/guides/getting-started-with-surrogate-keys

**Comment by pkarw** [comment]
Related: https://github.com/DivanteLtd/vue-storefront-api/pull/332

**Comment by Fifciu** [comment]
Module for Varnish: https://github.com/new-fantastic/cache-varnish

**Comment by pkarw** [comment]
@Fifciu this is really awesome! Can you please send a PR to the core including this module by default?
Will it work with fastly.com (based on Varnish)?

**Comment by Fifciu** [comment]
@pkarw I will prepare PR when vsf-cache-**nginx** is also ready. About fastly, I don't really know

**Comment by pkarw** [comment]
@Fifciu thanks! `vsf-cache-nginx`: https://github.com/new-fantastic/vsf-cache-nginx

Great job! Thanks!

**Comment by pkarw** [comment]
Related: https://github.com/new-fantastic/vsf-cloudflare
