### ISSUE TITLE
Empty storeView errors prevents viewing state in devtools

### ISSUE THREAD

**Issue by komakino** [DivanteLtd/vue-storefront#4105]
## Current behavior

I'm not sure if this is a bug or if I have something not configured correctly, but when I try to `Load state` in devtools I get errors saying that `userGroupId` can't be read from undefined(and similar errors). The errors are a result of the fact that `storeView` in the root state is empty. I pinned it down to `currentStoreView()` in `core/lib/multistore.ts`, where the const `clientStoreView`, at least in my case, always is an object; namely an empty `Observable`, which results in `buildBaseStoreView()` never being called.

## Expected behavior

That I can inspect the state in devtools without errors.

## Steps to reproduce the issue

Non-multistore project, open devtools -> vuex tab, try to `Load state`.

## Can you handle fixing this bug by yourself?

- [ X] YES, if this is not a symptom of other problems.
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 79.0.3945.88
- OS: Ubuntu 18.04
- Node: v12.14.0
- Code Version: All relevant branches including `master`, `release/v1.11` and `hotfix/v1.11.2`.

**Comment by komakino** [comment]
Actually, I sort of mixed up related issues here. The original error I had was from `getIsUserGroupedTaxActive()` in `core/modules/catalog/store/tax/getters.ts`, which has nothing to do with `currentStoreView()`. `getIsUserGroupedTaxActive()` requires `storeView` to be populated in the state, so I guess that is the real issue here; why `storeView` is empty.

**Comment by gibkigonzo** [comment]
Hey, I'm trying to reproduce this error,but it works ok :thinking: :
1. `yarn dev` on `hotfix/v1.11.2`
2. on homepage open devtools and load state
Is this happen on all pages? Or maybe you changed default config?

**Comment by komakino** [comment]
@gibkigonzo that's weird. I just tried with a clean `hotfix/v1.11.2`, `yarn installer`(no changes), and get this error. We are also experiencing it on all our current vsf projects.

**Comment by komakino** [comment]
Ok, I figured it out. Apparently, I was running the beta channel of Vue devtools. I tried in another browser profile with stable Vue devtools and all was fine. So this *probably* isn't a VSF issue.
