### ISSUE TITLE
Wrong child SKU selected on product page

### ISSUE THREAD

**Issue by simonmaass** [DivanteLtd/vue-storefront#4108]
## Current behavior

I believe it used to work... If you browse to a product page:
https://next.storefrontcloud.io/women/bottoms-women/pants-women/pants-27/portia-capri-1908.html?childSku=WP13-29-GREEN

Standard Blue und 28 ist selected

![image](https://user-images.githubusercontent.com/32599710/74864671-33d04e00-5350-11ea-9a2d-65e1aa536d28.png)

## Expected behavior

I would expect the correct selected options: Size: 29 and Color: Green

## Steps to reproduce the issue

Just browser to: https://next.storefrontcloud.io/women/bottoms-women/pants-women/pants-27/portia-capri-1908.html?childSku=WP13-29-GREEN

Or any other child sku variation...

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by revlis-x** [comment]
Your link is wrong. Correct sku would be `WP13-28-Green` and with that it works.
https://next.storefrontcloud.io/women/bottoms-women/pants-women/pants-27/portia-capri-1908.html?childSku=WP13-28-Green

**Comment by simonmaass** [comment]
you are absolutely right - my bad!

**Comment by simonmaass** [comment]
I guess the only thing to think about is to maybe not make it case sensitive...
