### ISSUE TITLE
Filter out-of-stock child items from configurable products in category view

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront#4111]
## Current behavior

If you enable to hide out-of-stock products in category list with `products.listOutOfStockProducts` config value, it hides items that are out-of-stock. But its only working seriously for simple products. If I have a product with four configurable options which are all out of stock, the "parent" product will still be visible. Also the filter for super-attributes like `size` will work but not really fulfill it's purpose to show just items with an available size or whatever.

This isn't really a bug, more a missing feature – but I think it's important for a consistent shopping experience.

I already did some research. It should be possible to query this in ES by using `nested` properties for `configurable_children` and `configurable_children.stock` in `product` index. The problem is that they are both just array/object types yet. So, the indexer/data-pump had to be modified to create the correct mapping. Then it would be best to add a new property for stock-check in the VSF actions and extend the `DivanteLtd/storefront-query-builder` to handle it (in first place for ES) at the API side.

I will post an example index and query for ES below to explain my idea.
I think this #3780 is heading in the same direction – but I'm aiming especially at a stock filter feature.

## Expected behavior

If I enable to hide out-of-stock items the filter in category-view for super-attributes like `size` should only show available items.

## Repository

Latest `develop`

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: All 
- OS: All 
- Node: All 
- Code Version:  develop 
- Data-Source: Magento1 /w `DivanteLtd/magento1-vsbridge-indexer`

**Comment by cewald** [comment]
Okay I made a small test index with some sample products (sorry for the long post).

The query (at the bottom) should only show items where the child is available or simple-products – this way we could achieve the desired behavior to filter products with out-of-stock super-attributes.

```elasticsearch
DELETE /test-index-for-product-stock

PUT /test-index-for-product-stock
{
  "mappings": {
    "product": {
      "properties": {
        "configurable_children": {
          "type": "nested",
          "properties": {
            "size": {
              "type": "long"
            },
            "stock": {
              "type": "nested",
              "properties": {
                "is_in_stock": {
                  "type": "boolean"
                },
                "min_qty": {
                  "type": "float"
                },
                "notify_stock_qty": {
                  "type": "float"
                },
                "qty": {
                  "type": "float"
                },
                "stock_status": {
                  "type": "long"
                },
                "use_config_notify_stock_qty": {
                  "type": "boolean"
                }
              }
            }
          }
        },
        "name": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "type_id": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        }
      }
    }
  }
}

POST /test-index-for-product-stock/product
{
  "type_id": "configurable",
  "name": "Test-Product #1",
  "configurable_children": [
    {
      "size": 20,
      "stock": {
        "is_in_stock": true,
        "qty": 3
      }
    },
    {
      "size": 21,
      "stock": {
        "is_in_stock": true,
        "qty": 8
      }
    },
    {
      "size": 22,
      "stock": {
        "is_in_stock": true,
        "qty": 8
      }
    },
    {
      "size": 23,
      "stock": {
        "is_in_stock": true,
        "qty": 5
      }
    },
    {
      "size": 24,
      "stock": {
        "is_in_stock": true,
        "qty": 2
      }
    }
  ],
  "category_ids": [
    1,
    2,
    3
  ]
}

POST /test-index-for-product-stock/product
{
  "type_id": "configurable",
  "name": "Test-Product #2",
  "configurable_children": [
    {
      "size": 23,
      "stock": {
        "is_in_stock": true,
        "qty": 8
      }
    },
    {
      "size": 24,
      "stock": {
        "is_in_stock": true,
        "qty": 5
      }
    },
    {
      "size": 25,
      "stock": {
        "is_in_stock": true,
        "qty": 2
      }
    }
  ],
  "category_ids": [
    1,
    2,
    3,
    4
  ]
}

POST /test-index-for-product-stock/product
{
  "type_id": "simple",
  "name": "Test-Product #3",
  "category_ids": [
    2,
    3
  ]
}

POST /test-index-for-product-stock/product
{
  "type_id": "simple",
  "name": "Test-Product #4",
  "category_ids": [
    1,
    2
  ]
}

GET /test-index-for-product-stock/product/_search

GET /test-index-for-product-stock/product/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "terms": {
            "category_ids": [1,2]
          }
        }
      ],
      "should": [
        {
          "nested": {
            "path": "configurable_children",
            "query": {
              "bool": {
                "must": [
                  {
                    "term": {
                      "configurable_children.size" : 20
                    }
                  },
                  {
                    "nested": {
                      "path": "configurable_children.stock",
                      "query": {
                        "bool": {
                          "must": [
                            {
                              "term": {
                                "configurable_children.stock.is_in_stock": true
                              }
                            },
                            {
                              "range": {
                                "configurable_children.stock.qty": {
                                  "gt": 0
                                }
                              }
                            }
                          ]
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "bool": {
            "must": [
              // Default stock rules here ...
            ],
            "must_not": [
              {
                "term": {
                  "type_id": "configurable"
                }
              }
            ]
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}
```

**Comment by cewald** [comment]
I added an optional `stock` filter to the `buildQueryBodyFromSearchQuery` method of `DivanteLtd/storefront-query-builder` – I refactored the method to create the above query:
https://github.com/icmaa/storefront-query-builder#feature/add-stock-filter-for-configurable-products

But there are some pitfalls and minor changes needed:
* As we aim an agnostic approach for the `storefront-query-builder`, the `bodybuilder` query-chain-object is just added as a parameter to the `buildQueryBodyFromSearchQuery`. And as we use nested queries, we need a plain `bodybuilder` object [to build them](https://github.com/danpaz/bodybuilder/issues/183#issuecomment-391506327). That's why I wanted to use the build in `clone` method – but this comes with version `2.2.21` and the API is using  `2.2.13` or something I think. So I needed to upgrade the API's `bodybuilder` version.
* I also needed to upgrade my data-pump to map the fields `configurable_options`, `configurable_children` and `configurable_children.stock` as nested fields. I did this by extending the `DivanteLtd/magento1-vsbridge-indexer` – but this should been done for all data-pumps.
* We need to implement it into the VSF – this is the easiest part. I just added my new custom filter to the desired query like `searchQuery.applyFilter({ key: 'stock', scope: 'catalog', value: null })`.  In my case it was enough to put it into the `loadCategoryProducts` actions – but this sure should be configurable and need to be added at other places as well.
* And I needed to add all available configurable product filter attributes to a config value of `vue-storefront-api`: `"products": { configurable_options: [ "size", "color", ... ] }` to let the `storefront-query-builder` know which filter are for children and which are regular catalog-scoped-filters for parent products.

It is working – I can now filter for only available products and its configurable child-products by availability too.

This is a lot – I'm not sure if just us are in need of this feature – or this is good feature for others too.

If so, I would could go on to create a more configurable and implemented approach.

**Comment by pkarw** [comment]
Hi @cewald I really appreciate the effort you took to make this feature happen - it's not anything simple. Some questions:

1. Is there a way to make this child-queries more general (not limited to `configurable_children` but to let the users just query any nested structure?) I wouldn't like to bind the `storefront-query-builder` to the specific Magento-like data structures we're currently using. I guess we should stick to `applyFilter` query interface for any type of queries (?)

2. Please create a PRs to other indexers as well - especially `mage2vuestorefront` which is still default choice for many of the users + `magento2-vsbridge-indexer`

That's it from my side. After this generalization + applying the shema change to the indexers I'm OK with merging this in

**Comment by pkarw** [comment]
I've added `feature request` label as this is actually a new feature - extending the query mechanism

**Comment by TerrorSquad** [comment]
What's the status on this?

Is it merged?

**Comment by cewald** [comment]
It's not – but there is a project in merging process which supports this kind of filter as an extension.
Means, you can then extend the `storefront-query-builder`: https://github.com/DivanteLtd/storefront-query-builder/pull/6.

Once you are using the `api-search-query` adapter and `storefront-query-builder` you are able to add the above filter on your own inside the `storefront-api` or `vue-storefront-api`. This is how our custom stock-filter looks like: [`StockFilter.ts`](https://github.com/icmaa/vue-storefront-api/blob/develop-2020-04-08/src/api/extensions/icmaa-catalog/filter/catalog/StockFilter.ts).

I think we can close this issue in favour of #4234
