### ISSUE TITLE
filterValue.toLowerCase is not a function

### ISSUE THREAD

**Issue by simonmaass** [DivanteLtd/vue-storefront#4118]
## Current behavior

core\modules\catalog\helpers\prefetchCachedAttributes.ts

on each attribute value filterValue.toLowerCase() is called...

with "attribute_id" as filterField I have integer type and get 

filterValue.toLowerCase is not a function

## Expected behavior

Should only be called on string values

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
@gibkigonzo can you please take a look?
