### ISSUE TITLE
Discount code disappears at the time of placing the order

### ISSUE THREAD

**Issue by dmytrokravch** [DivanteLtd/vue-storefront#4123]
## Current behavior

After registering on the /checkout page at the time of placing the order, discount code disappears

## Steps to reproduce the issue

1 Create an account on Personal Details step
2 Place the order

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
Browser: Google Chrome Version 81.0.4044.17
OS: Win 10
Node: 10.15.2
Code Version: 1.11.1

**Comment by pkarw** [comment]
This is because the shopping cart is being resynced between guest and registered users cart . We need to improve the “cart/sync” method to synchronize the shopping cart discount code as well in order to fix this edge case
