### ISSUE TITLE
Upgrade node packages

### ISSUE THREAD

**Issue by peterlohaus** [DivanteLtd/vue-storefront#4126]
## What is the motivation for adding / enhancing this feature?
Running `yarn audit`  on clean installation of vue-storefront on branch master outputs 12110 vulnerabilities. 12101 with high severity. 
Running `yarn outdated` states most of the packages current version being behind wanted semver version and way behind latest versions, thus do not apply minor or major updates.

## What are the acceptance criteria 
- [ ] `yarn audit` shows 0 vulnerabilities
- [ ] `yarn outdated` shows packages apply latest version

## Can you complete this feature request by yourself?
- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information
![Screenshot from 2020-02-26 14-50-34](https://user-images.githubusercontent.com/33315207/75422538-1e08ed00-593d-11ea-97e6-46ec6328098d.png)

**Comment by simonmaass** [comment]
i can take this one

**Comment by pkarw** [comment]
Cool 🙌
