### ISSUE TITLE
"No such entity with cartId = 700598"

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#4133]
## Current behavior
The following error occurs in dev console `"No such entity with cartId = 700598"`.
Discount code disappears after placing the order.
Incorrect quantity of products in the order details.

![image](https://user-images.githubusercontent.com/36628922/75520646-4e688e00-5a06-11ea-9a6d-276f2dfbd2a5.png)

## Expected behavior
The order is placed with the right amount of products and the correct amount.

## Steps to reproduce the issue
1. Add any product to the cart 
2. Go to checkout 
3. Create an account on Personal Details step
4. Go to Payment
5. **Return to shopping**
6. Add a discount code 
7. Go to the checkout again and finish creating the account and placing the order

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by gibkigonzo** [comment]
this can be related to 4123 as there is not properly added configurable product.

**Comment by akrajna** [comment]
I does not work properly. After repeating the steps to reproduce the issue, in 'My account -My orders' the order user just made is without discount and the products are doubled.
![NoSuchEntity1](https://user-images.githubusercontent.com/57936972/75887222-bfa2a980-5e29-11ea-9124-f30a460a3cbb.gif)

**Comment by gibkigonzo** [comment]
Probably we need to filter somehow result from `order-history` :thinking: I've checked what is send to magento and it looks ok (only one configurable product). But in order-history we get one configurable product, one simple with prices and one simple without prices (I think that is discount). Same payload is send on https://demo.storefrontcloud.io/ but in return we get only one simple product (adding discount doesn't work).

**Comment by gibkigonzo** [comment]
it looks like its normal behavior of two products for configurable product https://magento.stackexchange.com/questions/97611/rest-api-order-including-a-configurable-product
