### ISSUE TITLE
It is possible to add product where the quantity is a negative integer or 0

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/vue-storefront#4136]
## Current behavior
It is possible to change the quantity of a product in cart to negative integer or 0 and place the order.
![CheckoutNegativeInteger](https://user-images.githubusercontent.com/57936972/75538642-38b09400-5a19-11ea-83e2-aa1ee7b0170d.gif)

## Expected behavior
It shouldn't be possible to change the quantity of a product in cart to negative integer or 0 and place the order.

## Steps to reproduce the issue
1. Go to any product page
2. Choose available variant of the product and click 'Add to cart' button
3. Click the 'cart' icon in upper right corner
4. Change the Quantity to -1
5. Click 'Go to checkout' button
6. Fill in all he necessary fields in checkout, shipping,  payment, review the order
7. Click 'Place the order' button
8. See the error

 ##
## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
@akrajna I can't reproduce it on both demo neither test instances. Do you have any errors in the browser console?
