### ISSUE TITLE
Different price on product page and in the cart

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/vue-storefront#4142]
## Current behavior
After adding some products to the cart the price is different in the cart than on the product page
![PricePPCart](https://user-images.githubusercontent.com/57936972/75631092-3eac9d80-5bf0-11ea-9049-276fdcd5bb63.gif)

## Expected behavior
The price is the same on product page and in the cart

## Steps to reproduce the issue
1. Go to any product page e.g. http://localhost:3000/women/tops-women/tanks-women/bras-and-tanks-26/celeste-sports-bra-1641.html?childSku=WB03-XS-Green
3. Check the price
2. Choose available variant of the product and click 'Add to cart' button
3. Click the 'cart' icon in upper right corner
4. Compare the prices

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
This seems like a Magento misconfiguration (Magento is showing the prices in Totals without taxes - Net prices). VSF is in charge of calculating product/category level prices but totals are taken 100% as they are in Magento
