### ISSUE TITLE
NOT_ALLOWED_SSR_EXTENSIONS_REGEX does not escape the extensions' dots

### ISSUE THREAD

**Issue by komakino** [DivanteLtd/vue-storefront#4147]
## Current behavior
We had a product named "Wombat Raw" with the slug being `wombat-raw`. This is unfortunately matched by the `NOT_ALLOWED_SSR_EXTENSIONS_REGEX` since the `.` in the file extensions(from `config.ssrDisabledFor.extensions`) are not escaped when injected into the regex. This results in a 404 with `Vue Storefront: Resource is not found`.

https://github.com/DivanteLtd/vue-storefront/blob/80f466443e19fcf663fbea8f1384527f6bfb3792/core/scripts/server.ts#L31

## Expected behavior
Products should be able have names ending in "raw"(or any other extension for that matter).

## Steps to reproduce the issue
Name a product "Something Raw" and try to load it with ssr enabled.

**Comment by gibkigonzo** [comment]
this regex is updated on develop https://github.com/DivanteLtd/vue-storefront/pull/4100 We can add it to 1.11 hotfix

**Comment by pkarw** [comment]
@gibkigonzo please port it to 1.11 if this isn’t a problem
