### ISSUE TITLE
Price in checkout is changing after logging in

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/vue-storefront#4149]
## Current behavior
Price in checkout is changing after logging in. It happens with bundle and group product.  And so it happens on hotfix/v1.11.2 and https://demo.storefrontcloud.io/
![PriceCheckoutLoggedin](https://user-images.githubusercontent.com/57936972/75867000-36c64680-5e06-11ea-8ebb-ae63db4af6cf.gif)

## Expected behavior
Price remains the same for logged in and logged out users

## Steps to reproduce the issue
Initial codition: use is not logged in
1. Go to bundle or group product page 
2. Click 'Add to cart' button
3. Click on 'Cart' icon
4. Click 'Go to checkout' button
5. Check the price
6. Click on 'login to your account'
7. Write in your email and password and click 'Login to your account' button
8. Check the price

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.
-  [x] This is a bug report for hotfix/v1.11.2

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by gibkigonzo** [comment]
In general magento returns different bundle products totals for user and for guest.
1. add bundle product to cart as guest => check microcart
2. add bundle product to cart as user => check microcart

**Comment by pkarw** [comment]
Maybe there is a shopping cart rule or tier prices set?

**Comment by pkarw** [comment]
This is returned by Magento so I guess it’s not a bug within the VSF itself
