### ISSUE TITLE
Impossible to add some products with quantity greater than 0 to the cart

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/vue-storefront#4152]
## Current behavior
When user is adding this product: MP11-32-Blue to the cart, despite the fact that Quantity is 98, there is a message: 'Product that you are trying to add is not available'
![QtyPlusCart](https://user-images.githubusercontent.com/57936972/75966820-3cd22b00-5ecb-11ea-9fd9-82ef5b01dac7.gif)

## Expected behavior
When user is adding product with quantity greater than 0, the product is successfully added to the cart.

## Steps to reproduce the issue
1. Go to this: MP11-32-Blue  product page
2. Check the quantity 
3. Click 'Add to cart' button
4. See the error

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by gibkigonzo** [comment]
We check qty for configurable option (MP11-32-Blue), but when we add to cart then there is sku MP11 with configurable options. I think that in magento doesn't check those option, only sku. I've checked that we can send full sku and then product can be added.
https://demo.storefrontcloud.io/men/bottoms-men/pants-men/pants-18/aether-gym-pant-872.html?childSku=MP11-32-Blue
![Zrzut ekranu z 2020-03-05 10-36-47](https://user-images.githubusercontent.com/42383376/75968150-3cd32a80-5ecd-11ea-9ad0-853abf7d6deb.png)

**Comment by pkarw** [comment]
It’s been confirmed by @mdanilowicz as a result of lack of m2-> elastic sync (disabled on demo)

**Comment by anyaoqi** [comment]
I met the same problem, exactly the same, how should I solve it?
![image](https://user-images.githubusercontent.com/19759151/110897001-9c151780-8337-11eb-8872-7953bc522d6d.png)
![image](https://user-images.githubusercontent.com/19759151/110897074-b9e27c80-8337-11eb-8005-1fe0be417c81.png)
