### ISSUE TITLE
Data prefetching optimizations

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#4161]
## What is the motivation for adding / enhancing this feature?

Currently, when you've got the PLP (Category) and navigate to the product, there is a API request executed to get this particular product details. Let's consider how to manage the prefetching?

I mean, from the PLP level we can prefetch and cache  using Service Worker the product info so no network roundtrip will be executed on PDP itself

There is no single URL request currently for PDP to fetch the data. The logic is embedded in Product:asyncData](https://github.com/DivanteLtd/vue-storefront/blob/2b9ffb14cef28ba4b19e515cb5b28d309717f4f7/src/themes/default/pages/Product.vue#L334)

Usually a few endpoints are called to get the product details.
How could we prefetch those the most elegant way? :)

@andrzejewsky @gibkigonzo @ResuBaka @cewald

**Comment by gibkigonzo** [comment]
I've made module to handle that case https://github.com/gibkigonzo/vsf-quicklink. There is only one issue that occurs also in https://github.com/GoogleChromeLabs/quicklink (there is this problem in capybara).

**Comment by pkarw** [comment]
We need to add a note on this to the docs @gibkigonzo ppl. are not aware they can use it

**Comment by gilbertococchi** [comment]
Hi @gibkigonzo, did you manage to review this PR here? https://github.com/GoogleChromeLabs/quicklink/pull/123

We would be really keen to listen to your feedback to better understand if the PR above would make Quicklinks fully compatible with VSF.

Gil
