### ISSUE TITLE
No notification about "The product has been added to the cart!" when the cache is cleared.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#4171]
## Current behavior
There is no notification about "The product has been added to the cart!" **when the cache is cleared.**

## Expected behavior
"The product has been added to the cart!" occurs always when user adds product to the cart.

## Steps to reproduce the issue
1. Run develop branch
2. Clear site data/cache
3. Go to any PDP
4. Add to cart **available** product variant

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by juho-jaakkola** [comment]
@gibkigonzo Are you working on this?

I was about to start working on #4185 (which is basically a duplicate) but I noticed you're assigned to this one.

**Comment by juho-jaakkola** [comment]
I in fact already made a PR: #4194

**Comment by gibkigonzo** [comment]
@juho-jaakkola  Thanks for handling that issue :)

**Comment by gibkigonzo** [comment]
closed by https://github.com/DivanteLtd/vue-storefront/pull/4194
