### ISSUE TITLE
Empty page for each product  from Gear or Training category

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#4172]
## Current behavior
Page without content for each product  from Gear or Training category
![image](https://user-images.githubusercontent.com/36628922/76638344-95996780-654c-11ea-9132-3bd9e4c2df82.png)

## Expected behavior
"The product has been added to the cart!" occurs always when user adds product to the cart.

## Steps to reproduce the issue
1. Run develop branch
2. Go to Gear or Training category
3. Open any PDP

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
It's OK with 1.11.2; for the 1.12.rc1 it requires you to re index the database so I guess that was the reason as we spoken on Slack

**Comment by alinadivante** [comment]
oh, yeah, you are right @pkarw 👍
