### ISSUE TITLE
Product and category Output Tags disappeared

### ISSUE THREAD

**Issue by Fifciu** [DivanteLtd/vue-storefront#4173]
## Current behavior

Product and category Output Tags disappeared on develop branch. Check it here in Response's headers.
- For product: https://test.storefrontcloud.io/women/tops-women/tanks-women/bras-and-tanks-26/celeste-sports-bra-1641.html?childSku=WB03-XS-Green
- For category: https://test.storefrontcloud.io/women/women-20

It makes impossible to clear cache of each category & product. So if we use `*` in invalidate URL. Categories & Products cache will not be purged!

## Expected behavior

Output tags are properly being added.

## Steps to reproduce the issue

Open links from description, compare them with Master (demo) instance.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
I’m not sure if cache is turned on on this instance (?) @gibkigonzo can you please check out this issue?

**Comment by Fifciu** [comment]
@pkarw I think it is. If you open network tab before refresh you could find tags in response headers. On master instance we have same but there we have also `category`.
![image](https://user-images.githubusercontent.com/30155292/76699057-cf33b500-66a9-11ea-96ef-1b3a4494ea23.png)

**Comment by pkarw** [comment]
OK, so the problem is that the grouping tags `category` and `product` are missed; correct? there are the individual product/category tags assigned correctly but just the page-type tag is missing?

**Comment by Fifciu** [comment]
> OK, so the problem is that the grouping tags `category` and `product` are missed; correct? there are the individual product/category tags assigned correctly but just the page-type tag is missing?

Exactly!

**Comment by pkarw** [comment]
can you maybe fix it? :) would be awesome!

**Comment by Fifciu** [comment]
Sure, I could. However, I am not sure how fast I will be able to do that.
