### ISSUE TITLE
Question for magento2-vsbridge-indexer, did not work.

### ISSUE THREAD

**Issue by gfd6th** [DivanteLtd/vue-storefront#4175]
#https://github.com/DivanteLtd/magento2-vsbridge-indexer/issues/237#issue-581012128

Magento ver 2.3.2.
This is my configs in magento.
![Jietu20200314-112211@2x](https://user-images.githubusercontent.com/6814715/76674022-15274500-65e6-11ea-96d1-29e6a68ed100.jpg)

And the reindex command:
![Jietu20200314-112451@2x](https://user-images.githubusercontent.com/6814715/76674080-8535cb00-65e6-11ea-90cf-478e76990cdf.jpg)

But there is no vue_storefront_cataog in es
![Jietu20200314-112555@2x](https://user-images.githubusercontent.com/6814715/76674101-ae565b80-65e6-11ea-8cab-f3131f4b3cca.jpg)

![Jietu20200314-112740@2x](https://user-images.githubusercontent.com/6814715/76674130-db0a7300-65e6-11ea-805d-ea2224b16601.jpg)

**Comment by pkarw** [comment]
@afirlejczyk can you please take a look?

**Comment by afirlejczyk** [comment]
It looks like duplicated issue:
https://github.com/DivanteLtd/magento2-vsbridge-indexer/issues/237#issue-581012128
