### ISSUE TITLE
afterCacheInvalidated hook is not being invoked after cache invalidated

### ISSUE THREAD

**Issue by Fifciu** [DivanteLtd/vue-storefront#4176]
## Current behavior

Take look at this part of server.ts:
```ts
serverHooksExecutors.beforeCacheInvalidated({ tags, req })

      tags.forEach(tag => {
        if (config.server.availableCacheTags.indexOf(tag) >= 0 || config.server.availableCacheTags.find(t => {
          return tag.indexOf(t) === 0
        })) {
          subPromises.push(cache.invalidate(tag).then(() => {
            console.log(`Tags invalidated successfully for [${tag}]`)
          }))
        } else {
          console.error(`Invalid tag name ${tag}`)
        }
      })

      // Why here? We have only array of promises (subPromises variable). But not fullfilled
      serverHooksExecutors.afterCacheInvalidated()

      Promise.all(subPromises).then(r => {
        apiStatus(res, `Tags invalidated successfully [${req.query.tag}]`, 200)
      }).catch(error => {
        apiStatus(res, error, 500)
        console.error(error)
      })

      // There we could write finally block and inside invoke hook

      if (config.server.invalidateCacheForwarding) { // forward invalidate request to the next server in the chain
        if (!req.query.forwardedFrom && config.server.invalidateCacheForwardUrl) { // don't forward forwarded requests
          request(config.server.invalidateCacheForwardUrl + req.query.tag + '&forwardedFrom=vs', {}, (err, res, body) => {
            if (err) { console.error(err); }
            try {
              if (body && JSON.parse(body).code !== 200) console.log(body);
            } catch (e) {
              console.error('Invalid Cache Invalidation response format', e)
            }
          });
        }
      }
```

## Expected behavior

Run `afterCacheInvalidated` after cache invalidated - not after an array of promises prepared to send.

## Repository

Current Develop

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version: 

## Additional information

In my opinion, `afterCacheInvalidated` should also has `tags` and `req`. Why? With that, I could figure out URL and instantly send BYPASS Nginx request (in vsf-cache-nginx module). So no user will have big cacheless waiting time.

**Comment by pkarw** [comment]
OK, you're right - PR is more than welcome ;)
