### ISSUE TITLE
Add Varnish cache support to the default distribution + production docs

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#4178]
## What is the motivation for adding / enhancing this feature?

Please include the https://github.com/new-fantastic/vsf-cache-varnish in the default distribution.
@kkdg can we have this module listed as an option in the Production setup docs?

**Comment by Fifciu** [comment]
I encourage you to add both it and vsf-cache-nginx as `git submodule` so it will be so easy to update for users and there will be no need to make PR to Core for each small update.

**Comment by pkarw** [comment]
@kkdg can you please take care of this? alternatively - @Fifciu can you do a PR with adding this to the core the way you described?

**Comment by kkdg** [comment]
@pkarw all right, this part is already mentioned in the docs but also working on cookbook.
