### ISSUE TITLE
Problem when running 1.11.1 on Docker

### ISSUE THREAD

**Issue by williamwd** [DivanteLtd/vue-storefront#4187]
## Current behavior
Trying to run the docker-compose up command returns the following error:
`front_1  | 18:51:15 3|server   | Error: Cannot find module '/var/www/start'
front_1  | 18:51:15 3|server   |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
front_1  | 18:51:15 3|server   |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
front_1  | 18:51:15 3|server   |     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
front_1  | 18:51:15 3|server   |     at main (/var/www/node_modules/ts-node/src/bin.ts:226:14)
front_1  | 18:51:15 3|server   |     at Object.<anonymous> (/var/www/node_modules/ts-node/src/bin.ts:485:3)
front_1  | 18:51:15 3|server   |     at Module._compile (internal/modules/cjs/loader.js:778:30)
front_1  | 18:51:15 3|server   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
front_1  | 18:51:15 3|server   |     at Module.load (internal/modules/cjs/loader.js:653:32)
front_1  | 18:51:15 3|server   |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
front_1  | 18:51:15 3|server   |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.267Z axm:profiling [-] v8-profiler not found in path /var/www/node_modules/v8-profiler
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.270Z axm:profiling Checking v8-profiler in path /var/node_modules/v8-profiler
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.271Z axm:profiling [-] v8-profiler not found in path /var/node_modules/v8-profiler
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.271Z axm:profiling Checking v8-profiler in path /node_modules/v8-profiler
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.271Z axm:profiling [-] v8-profiler not found in path /node_modules/v8-profiler
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.272Z axm:profiling [x] v8-profiler NOT FOUND
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.273Z axm:profiling Checking v8-profiler-node8 in path /var/www/node_modules/pm2/lib/node_modules/v8-profiler-node8
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.273Z axm:profiling [-] v8-profiler-node8 not found in path /var/www/node_modules/pm2/lib/node_modules/v8-profiler-node8
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.273Z axm:profiling Checking v8-profiler-node8 in path /var/www/node_modules/pm2/node_modules/v8-profiler-node8
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.273Z axm:profiling [-] v8-profiler-node8 not found in path /var/www/node_modules/pm2/node_modules/v8-profiler-node8
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.273Z axm:profiling Checking v8-profiler-node8 in path /var/www/node_modules/v8-profiler-node8
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.273Z axm:profiling [-] v8-profiler-node8 not found in path /var/www/node_modules/v8-profiler-node8
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.273Z axm:profiling Checking v8-profiler-node8 in path /var/node_modules/v8-profiler-node8
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.273Z axm:profiling [-] v8-profiler-node8 not found in path /var/node_modules/v8-profiler-node8
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.274Z axm:profiling Checking v8-profiler-node8 in path /node_modules/v8-profiler-node8
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.274Z axm:profiling [-] v8-profiler-node8 not found in path /node_modules/v8-profiler-node8
front_1  | 18:51:15 3|server   | 2020-03-19 18:51:15: 2020-03-19T18:51:15.274Z axm:profiling [x] v8-profiler-node8 NOT FOUND`

We're getting this running the provided docker-compose.yml.
Currently we have an application in production running an older version of VueStorefront and wanted to upgrade it to a later version.
Tried to install v8 and v8-profiler but no luck.

## Expected behavior
This error should not occur and VSF should start normally on Docker

## Steps to reproduce the issue
Clone the repo
Change VS_ENV on docker-compose.yml from dev to prod
docker-compose up

## Can you handle fixing this bug by yourself?
Been trying for 2 days now.
- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
1.11.1

## Environment details
Docker 19.03.8

**Comment by pkarw** [comment]
We can't reproduce this issue on clean VSF install :-( Make sure its' not related to your app custom changes please
