### ISSUE TITLE
Window freeze roughSizeOfObject function of storage.ts

### ISSUE THREAD

**Issue by CompactCodeEU** [DivanteLtd/vue-storefront#4189]
## Current behavior
When calculating the size of large cached Objects it results in a temporary tab freeze for the client. This happens in `vue-storefront/core/store/lib/storage.ts` on 1.10.4 vuestorefront.

We are working on a client with big grouped and configurable products resulting in large cached entities. Looping trough the object keys results in performance issues.

With Google's profiling i narrowed it down to the `roughSizeOfObject` function that took over 4 seconds even when `disableLocalStorageProductsCache` is set to true in the config.

## Expected behavior
This should not affect users experience.

## Steps to reproduce the issue
1. Navigate trough some categories with large grouped/configurable products
2. Go to the product page and just click on qty up button for reference if its stuck
3. After 30 seconds the iterator goes trough the cached objects and the tab will be frozen

Note : We have customized products and types of products so our object for a product is also bigger.

## Can you handle fixing this bug by yourself?

- [X ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome 
- OS: Windows 10
- Node: 10.16.0
- Code Version: 1.10.3 with changes from 1.10.4

## Additional information
Note that this is a development environment.
See video 
https://www.youtube.com/watch?v=0OQ8_D38MlU&feature=youtu.be
I have also tested if the output bytes is the same and it is.
The code is copied from https://gist.github.com/zensh/4975495 with a small adjustment to always return bytes

**Comment by pkarw** [comment]
OK gotcha. The reason for this function is to clear the localStorage in order to avoid storage quota exceeded. There is currently an exception handled of quota exceeded (surely in 1.11) so maybe we can disable this.

**Comment by CompactCodeEU** [comment]
I might understand it wrong but shouldn't local storage only be deleted on 'old content'? Maybe trough an expires_at date or something. Now it is clearing the local storage every 30 seconds so isn't this kind of counter productive? I also noticed it does not only look at local storage but also at indexedDB storage (where currently the products are being cached).

**Comment by gibkigonzo** [comment]
@CompactCodeEU I couldn't reproduce it on version 1.10.3+. Can you please reproduce it on current `master` branch or `lts-1.10`? Please also make tests in production mode. Site from video is running in development mode which can shows wrong information.

**Comment by gibkigonzo** [comment]
@CompactCodeEU Please also take a look on those changes https://github.com/DivanteLtd/vue-storefront/pull/3830/files#diff-3363520e41e1f3a8021c1e57284dc7e7 Its important to store data in `this._localCache` without reference. So we can safely read data (for example keep reference to object in this place https://github.com/DivanteLtd/vue-storefront/blob/hotfix/v1.10.3/core/store/lib/storage.ts#L16). I think it's not counter productive, because most time we just read data. Maybe we should check current storage size every time when we add new data. But this could trigger even more actions.
