### ISSUE TITLE
Add to cart a few products fastly

### ISSUE THREAD

**Issue by Fifciu** [DivanteLtd/vue-storefront#4195]
## Current behavior

When we add a few products to the cart fastly - quantity will be multiplied randomly. It creates bad UX for custom features like add to cart from products' listing.

## Expected behavior

Adding to the cart a few products without waiting to finish previous AddToCart action should work properly.

## Steps to reproduce the issue

1. Open product with many variations
2. Remove `disable` property from AddToCart btn/action
3. Change variants and addToCart few items fastly

Personally, I have addToCart from product listing feature. So I just click on a few tiles and it gets bugged.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

This bug is in VSF since I remember. I think it might be bugged in each version.

**Comment by pkarw** [comment]
@Fifciu this `disabled` property was just to prevent the situation like this. Why did you remove it? I'm not sure if this is a bug
