### ISSUE TITLE
More human-friendly formatting in the config file

### ISSUE THREAD

**Issue by juho-jaakkola** [DivanteLtd/vue-storefront#4197]
## What is the motivation for adding / enhancing this feature?

When site owners upgrade their VSF projects, they usually need to manually check the upstream changes made into the `config/default.json` file and update their project specific config file when necessary.

This would be easier if the long arrays within the file would be:
 - Formatted into multiple rows
 - In alphabetical order

### Before: Difficult to see what has changed:
```diff
- "availableCacheTags": ["product", "category", "home", "checkout", "page-not-found", "compare", "my-account", "P", "C", "error", "attribute"],
+ "availableCacheTags": ["product", "category", "home", "checkout", "page-not-found", "compare", "my-account", "taxrule", "P", "C", "error", "attribute"],
```
### After: Easy to see what has changed:
```diff
    "availableCacheTags": [
      "product",
      "category",
      "home",
      "checkout",
      "page-not-found",
      "compare",
      "my-account",
+      "taxrule",
      "P",
      "C",
      "error",
      "attribute"
    ],
```

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by juho-jaakkola** [comment]
Oops, I was not supposed to choose `feature request`.

**Comment by pkarw** [comment]
Can you please preapre a PR with this change ?

**Comment by juho-jaakkola** [comment]
Yep, I can do it.
