### ISSUE TITLE
Problem with selecting subcats

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#42]
I've just added support for nested categories in sidebar and it stopped working .. Please take a look @filrak @patrykpiston

**Comment by filrak** [comment]
@pkarw the routes are empty.

**Comment by pkarw** [comment]
What do you mean by routes are empty? How should i fix it?

**Comment by pkarw** [comment]
I think it's done - to test after showing properly subcats

**Comment by pkarw** [comment]
OK, subcats for MVP, I'm clsoing this one
