### ISSUE TITLE
Invalid start_url property in manifest.json

### ISSUE THREAD

**Issue by dimasch** [DivanteLtd/vue-storefront#420]
Actual result:
https://github.com/DivanteLtd/vue-storefront/blob/690b9f7771bb922aef226675ee4832baf66c8786/src/assets/manifest.json#L34

Expected result:
`"start_url": "/"`

For pass PWA audit:
https://developers.google.com/web/tools/lighthouse/audits/install-prompt

**Comment by pkarw** [comment]
It was our intention to have PWA.html as starting point for the demo.vuestorefront.io, as the “/“ is restricted by htaccsss

**Comment by pkarw** [comment]
https://demo.vuestorefront.io/pwa.html - it’s configured on nginx proxy

**Comment by dimasch** [comment]
Ok, thx!
