### ISSUE TITLE
Cart Items duplicated when placing order with account creation

### ISSUE THREAD

**Issue by revlis-x** [DivanteLtd/vue-storefront#4205]
## Current behavior
When placing an order while simultaniously creating an account, cart items get duplicated in the placed order. There seems to be some kind of race condition, because this does not happen all the time...only sometimes - which makes it hard to reproduce consistently. 

## Expected behavior
Placed order has exactly the same items and quantities as the cart before clicking "Place Order".

## Steps to reproduce the issue
1. Put item in cart.
2. Place order while checking "I want to create an account"
3. Place order. -> (Sometimes) order has sku twice.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [X] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`

## Additional Information

Below is a screenshot of all calls made when placing order with account creation. There is a suspicios call to /update which is done after the call to /order, but actually finishes before it.
![Screenshot from 2020-03-28 13-16-37](https://user-images.githubusercontent.com/2040118/77823038-55171d80-70f8-11ea-9e59-5e6b3c684d67.png)

**Comment by pkarw** [comment]
Thanks @revlis-x! Is ths related to 1.11?

**Comment by revlis-x** [comment]
@pkarw Yes, I can reproduce this on https://test.storefrontcloud.io .

**Comment by gibkigonzo** [comment]
on https://test.storefrontcloud.io there is still version 1.11.1. On current master this problem shouldn't occur (1.11.3)

**Comment by gibkigonzo** [comment]
related https://github.com/DivanteLtd/vue-storefront/pull/4150
