### ISSUE TITLE
Add `vsf-capybara` support as a dependency and extend CLI to support customization

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#4209]
## What is the motivation for adding / enhancing this feature?

We need to add the https://github.com/DivanteLtd/vsf-capybara to the default VSF distribution and modify https://www.npmjs.com/package/@vue-storefront/cli to let the users customize it

Capybara should be the default / go-to theme for the users to start with

@kkdg we'll need to update the docs after guys figure out how to integrate the theme with 1.12

**Comment by pkarw** [comment]
@kkdg regarding the docs - we can include the:
- https://github.com/DivanteLtd/vsf-capybara/blob/develop/CODING_STANDARDS.md
- https://docs.storefrontui.io/customization.html

**Comment by kkdg** [comment]
@pkarw Noted, I am wrapping my head around understanding the system. thanks!
