### ISSUE TITLE
Remove the `graphql` support from the core

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#4214]
## What is the motivation for adding / enhancing this feature?

The current `graphql` support is pretty buggy and un-flexible. We've reworked the whole graphql support on the backend with https://github.com/DivanteLtd/storefront-api. But the current `searchAdapter` is not compatible with this. I tried fo fix it in the https://github.com/DivanteLtd/vue-storefront/tree/feature/storefront-api-graphql-support but only to get even more frustrated :-)

GraphQL support will be added in the `vsf-next` for Magento2 I guess and for now the `searchAdapter` for graphql: https://github.com/DivanteLtd/vue-storefront/tree/develop/core/lib/search/adapter/graphql should be moved to an optional module within the `src/search` (this path is [officially supported](https://github.com/DivanteLtd/vue-storefront/blob/250daa023264a7b15a8f1d4b20357fffae9a5ce8/core/lib/search/adapter/searchAdapterFactory.js#L12)) or pm package

**Comment by pkarw** [comment]
@kkdg we need to update the docs regarding this change. With `graphql` support in the `src/search` as optional module it will be still available - however unsupported/deprecated

**Comment by kkdg** [comment]
@pkarw all right! It was the heavily updated part in the meantime. I will edit them accordingly, thanks.
