### ISSUE TITLE
Pass item_id in addition to SKU/details for cart update/delete action

### ISSUE THREAD

**Issue by carlokok** [DivanteLtd/vue-storefront#4218]
## What is the motivation for adding / enhancing this feature?

Currently vue-storefront passes sku and the configurable/custom options info to the api when updating or deleting an item. For a custom implementation it would be a lot easier if in addition it could pass item_id, so that server implementations know which item it is exactly, without having to do a deep compare.

## What are the acceptance criteria 

- [ ] createCartItemForUpdate passes item_id from serverItem if serverItem is set.

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

 (got a patch ready if needed)

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.

**Comment by pkarw** [comment]
Hi @carlokok, yeah that's smart :)

**Comment by carlokok** [comment]
this is now fixed by the pull req.
