### ISSUE TITLE
parent_ids field on category so that breadcrumbs work without depending on the url path

### ISSUE THREAD

**Issue by carlokok** [DivanteLtd/vue-storefront#4219]
## What is the motivation for adding / enhancing this feature?

Currently vuestorefront uses the url_path to define breadcrumbs, by splitting it on / and using the parts as category names. However not all commerce servers use this exact seo path format. It would be great if, in addition to the default behavior, a server can set a parent_ids field that holds a list of parent id codes so that it can use that for breadcrumb navigation. 

## What are the acceptance criteria 

- [ ] If parent_ids are set, use this as the breadcrumb id list, else use the original behavior list

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.

## Additional information

I have a patch for this ready if this feature is acceptable. (In addition to this, a simple tweak that allows string id's to work with breadcrumbs)

**Comment by gibkigonzo** [comment]
@carlokok can you make pr for that? :)

**Comment by carlokok** [comment]
Fixed in associated pull request. Thanks!
