### ISSUE TITLE
Cart Item quantities doubled when logged-in, applying/removing coupon and reloading the page.

### ISSUE THREAD

**Issue by revlis-x** [DivanteLtd/vue-storefront#4220]
## Current behavior
In current master (1.11.2) all cart item quantites are doubled, when performing the actions described below.

## Steps to reproduce the issue
1. Have an account and be logged in and have items in cart.
2. Apply coupon code (e.g. mmtest on demo instance).
3. Reload page. -> Each cart item's quantity gets doubled.

Same happens again, when coupon is removed and page is reloaded.

## Expected behavior
Cart Item quantities stay the same after reload.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Additional information
This can be mitigated by setting mergeQty: false for the 'connect' action inside 'cart/authorize', but then quantity merging of client and server cart is no longer functional (#4017,#4041)

**Comment by pkarw** [comment]
Related to #4205
