### ISSUE TITLE
Documentation: Vuex module links broken

### ISSUE THREAD

**Issue by renestalder** [DivanteLtd/vue-storefront#4223]
## Current behavior
That issue came up actually a year ago, but it seems not fixed. My guess it's the identical problem to  #2979, which is closed but not fixed.

There are multiple page links broken or pages even missing in the documentation about the Vuex store.

## Expected behavior
Either those links or the page removed, as it seems this should no longer be used. Otherwise, those missing pages added again. Because it is confusing.

## Steps to reproduce the issue
Go to:
https://docs.vuestorefront.io/guide/vuex/introduction.html#vuex-conventions

Click cart, checkout, order or user Vuex modules.

## Can you handle fixing this bug by yourself?

- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
Unrelated.

**Comment by kkdg** [comment]
Hi @renestalder, it had been fixed but seems like needing updates once again. Thanks for reporting. This will be updated right away.

**Comment by kkdg** [comment]
@renestalder, I found the whole section for Vuex has been deprecated since `1.11` upgrade applied to `master` branch, so that this section is moved to archives while the newly created docs will be pushed under cookbook _module_ part. This will be done deploying soon. Thanks
