### ISSUE TITLE
Request help in installing wazicloud 

### ISSUE THREAD

**Issue by umucyoSoft** [DivanteLtd/vue-storefront#4224]
Dear Sir/Madam,
my name is Jean Louis NIRAGIRE, an IoT consultant in Rwanda,
I have full knowledge of Cloud dockers and images 

Hereby requesting your guide to install Waziup Platform, as i repeatedly tried but the whole instance of the platform could not be up

https://drive.google.com/file/d/1dKldNhbLLMAMZSOt4k1D2E2a7kdGmwHt/view

https://drive.google.com/file/d/1GHiGoZIZNHEqTVeAWvOYvK_-C8AAATmE/view
 PLEASE HELP ME

Whatsapp & Mobile: +(250)788248339

**Comment by pkarw** [comment]
Are you shure this request is vue-storefront related? Please try to use our https://forum.vuestorefront.io to get help on that
