### ISSUE TITLE
Sidebar microcart component is rendered everytime it shown

### ISSUE THREAD

**Issue by dverkade** [DivanteLtd/vue-storefront#4229]
## Current behavior

Everytime you open the sidecart it will render it completely again. This causes the method "created" to be executed again.

## Expected behavior

Once the sidecart is created make it inactive, but keep it as a VueJS component so that it doesn't need to instantiate the component again. 

## Steps to reproduce the issue

- Slide out the sidecart, it will show in the VueJS component DOM.
- Close it, it will be removed from the VueJS component DOM

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

![image](https://user-images.githubusercontent.com/1058480/78560364-4e825780-7816-11ea-9e1b-c47cf01deb3f.png)

**Comment by dverkade** [comment]
I've tested this solution and it doesn't solve the issue. The function created() in Microcart.vue is still called every time you open up the sidebar cart. This is not expected behaviour as you only want to render the actual component once.

**Comment by pkarw** [comment]
@gibkigonzo

**Comment by gibkigonzo** [comment]
@dverkade Please check current hotfix branch `hotfix/v1.11.3`. After adding
```
  created () {
    console.log('created')
  },
```
 to `src/themes/default/components/core/blocks/Microcart/Microcart.vue` you can see that its displayed in console only once. In comparison on master branch is displayed every time
