### ISSUE TITLE
Mapping domains on root categories

### ISSUE THREAD

**Issue by cszczotka** [DivanteLtd/vue-storefront#4237]
Hi,
I'm running vue-storefront and I have few root categories for example:
http://mystore.demo.com/catA
http://mystore.demo.com/catB
http://mystore.demo.com/catC

I would like to have separate dns domains which will be "mapped" on these root categories
for example:
http://catA-domain1.com -> http://mystore.demo.com/catA
http://catB-domain2.com -> http://mystore.demo.com/catB
...
In other words if user go to: http://catA-domain1.com will be displayed the same content like for http://mystore.demo.com/catA.

Is it possbile to do by configuring routing in vue-storefront ?

I read about multistore https://github.com/DivanteLtd/vue-storefront/blob/master/docs/guide/integrations/multistore.md but it works rather on the same domain.

Thanks

**Comment by gibkigonzo** [comment]
@cszczotka Hey, it's out of scope. VSF can handle internal routing or can initialize external routing but then this should be resolve on server.
