### ISSUE TITLE
Capybara theme error page fails when server is down

### ISSUE THREAD

**Issue by carlokok** [DivanteLtd/vue-storefront#4239]
## Current behavior
If the API is down, the capybara error page tries to do api requests for the menu, and fails if the API isn't running.

## Expected behavior
A proper error page, probably without the menu.

## Steps to reproduce the issue
Start vsf with capybara, kill the api server.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.

## Environment details

- Browser: Firefox 75
- OS: Windows 10
- Node: 13.7
- Code Version: head of both

**Comment by pkarw** [comment]
Can you please post the issue to https://github.com/DivanteLtd/vsf-capybara so the team will take care?
