### ISSUE TITLE
`isBackRoute` not working as expected

### ISSUE THREAD

**Issue by SDLyu** [DivanteLtd/vue-storefront#4266]
## Current behavior

Change category but products not change if the category page is visited.

## Expected behavior

Category page should display correct products which belongs the category.

## Steps to reproduce the issue

1. Visit A category page.
2. Visit B category page.
3. Visit A category page and the products not changed.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO
- [x] Not Sure

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 81.0.4044.113
- OS: MacOS 10.15
- Node: v10.19.0
- Code Version: v1.11.2

## Additional information
![bug](https://user-images.githubusercontent.com/2996108/79842506-7ca59100-83eb-11ea-9a2f-82f3b93de030.gif)

**Comment by gibkigonzo** [comment]
@SDLyu hey, thanks for reporting this bug. It will be fixed in next hotfix. You can check it here http://next.storefrontcloud.io/ and here is same issue https://github.com/DivanteLtd/vue-storefront/issues/4201
