### ISSUE TITLE
Shouldn't we introduce domain-logic models into the frontend?

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#43]
Right now the vuex stores returns PoJ (Plain Old Json ;)) objects. Kind of DTO's. So it's quite hard to add some logic or helper methods and it becomes more procedural development (with external helper classes) than OOP

Just thinking. The attribute data model is an example for this case

**Comment by pkarw** [comment]
@filrak @patrykpiston

**Comment by patrykpiston** [comment]
I think it's a good idea, it would allow a cleaner approach. @filrak what do you think?

**Comment by pkarw** [comment]
Some inspiration on that: https://www.npmjs.com/package/vuex-model-template

**Comment by pkarw** [comment]
http://aaronfrancis.com/2016/introducing-vue-model/

**Comment by pkarw** [comment]
https://github.com/reactjs/reselect

**Comment by pkarw** [comment]
It seems we rather should de-couple current Vuex stores and make it more fine-grained. One store per one entity (product, category, order ...)
