### ISSUE TITLE
PDP processed multiple times?

### ISSUE THREAD

**Issue by juho-jaakkola** [DivanteLtd/vue-storefront#4303]
## Current behavior

It seems that the `src/themes/default/pages/Product.vue` page component gets processed (rendered?) multiple times on a single page load (e.g. when accessing it from a link on the category page).

## Expected behavior

It should naturally be rendered only once. 

## Steps to reproduce the issue

I tested it by adding a simple method to the page component:

```js
  methods: {
    test() {
      console.log('- - - THIS SHOULD BE CALLED ONLY ONCE!')

      return true
    },
```

And then calling that in one of the top level elements in the template. One that doesn't have any `v-for` loops or anything else that might cause it to be used more than once:

```html
<template>
  <div id="product" itemscope itemtype="http://schema.org/Product">
    <section class="bg-cl-secondary px20 product-top-section">
      <div class="container" v-if="test()">
```
The expectation is that the message gets logged in the browser console only once. However, it is logged total of six times! (Three of the messages have been combined in the log.)

![image](https://user-images.githubusercontent.com/883920/80468804-fa175700-893f-11ea-81d8-f4764ec00104.png)

## Repository

https://github.com/DivanteLtd/vue-storefront/tree/v1.11.3

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Google Chrome, Version `81.0.4044.122` (Official Build) (64-bit)
- OS: MacOS Mojave `10.14.6` (18G3020)
- Node: `v10.19.0`
- Code Version: `v.1.11.3`

## Additional information

For my particular use case, I have suspicion that this is causing an infinite loop within one of my custom features related to configurable products. When a config option is chosen, this triggers changes on the page, and those changes potentially trigger all those page reloads, which again trigger something else, and the page gets stuck inside the loop.

Other that that, I believe this also reduces performance even on default setups, as the reloads are most likely doing the same things unnecessarily multiple times during a single page load.

**Comment by juho-jaakkola** [comment]
This may have something to do with the asynchronous call to check the stock status.

**Comment by pkarw** [comment]
It shouldn't be necessarily a bug. There are some calls for Vue to repaint the whole component - especially in checking stock status from Vuex. If the `asyncData` and `mounted` are called just once it's I guess OK

**Comment by gibkigonzo** [comment]
@juho-jaakkola
It's normal vue behavior, methods are calculated on each update. Use computed properties instead.
example: https://jsfiddle.net/w3jgaueq/1/
