### ISSUE TITLE
Add styles to the product card with grouped products

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#431]
Related to issues https://github.com/DivanteLtd/vue-storefront/issues/424.

<img width="1440" alt="product card with grouped products" src="https://user-images.githubusercontent.com/18116406/34052471-d38d575a-e1c2-11e7-8256-b38a81ba1833.png">

**Comment by pkarw** [comment]
Because we're short on time I'l move this one to 0.4; I've styled the feature differently, a little bit. I belive it's fine - as for now

**Comment by pkarw** [comment]
http://localhost:3000/p/24-WG085_Group/set-of-sprite-yoga-straps-2046 or https://test.vuestorefront.io/p/24-WG085_Group/set-of-sprite-yoga-straps-2046

**Comment by pkarw** [comment]
Could you take care of this one @Aekal?
