### ISSUE TITLE
Usage of slashes in CMS page URL path

### ISSUE THREAD

**Issue by peterlohaus** [DivanteLtd/vue-storefront#4319]
## Current behavior
Vue Storefront displays CMS pages properly, that consist of a single path declaration like `print`.
However, url keys of a CMS page consisting of longer paths to the resource are not functional.
In other words, `print/types`, `print/colors` or any other arbitrary path containing a slash `/` are not properly resolved.

## Expected behavior
Vue Storefront displays CMS pages, that own url keys of the format `path/to/page`

## Steps to reproduce the issue
1. In Magento create a CMS page with url key `print/color`
2. In Vue Storefront define the corresponding router
3. Run local project
4. Open path `localhost:3000/i/print/color` in browser

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by gibkigonzo** [comment]
cms_page route is resolved by vue-router and we have there `path: '/i/:slug'` So `/i/print/color` is invalid. If you know that you will have cms_page with second slug `path: '/i/:slug/:secondSlug'` then add it like this to your routes. We can't fix that right now, in 1.12 mappingFallback will also handle cms_page which will allow to use any key. Related https://github.com/DivanteLtd/vue-storefront/issues/4315

**Comment by peterlohaus** [comment]
@gibkigonzo Thank you for information on short term solution
