### ISSUE TITLE
Redirect from child product to configurable parent is broken

### ISSUE THREAD

**Issue by juho-jaakkola** [DivanteLtd/vue-storefront#4359]
## Current behavior
The configuration file has the entry:
```json
"products": {
    "preventConfigurableChildrenDirectAccess": true,
```

Documented here: https://docs.vuestorefront.io/guide/basics/configuration.html#products

> If this option is set to true (default), Vue Storefront will prevent accessing the simple products assigned with the configurable one. A user will be redirected to the main configurable product in such a case.

However, when I enter the URL of a child, I see the product detail page of the child product.

## Expected behavior

I'm expecting to get redirected to the PDP of the parent product.

## Repository

https://github.com/DivanteLtd/vue-storefront/tree/v1.11.3/

The related code is here: https://github.com/DivanteLtd/vue-storefront/blob/v1.11.3/core/modules/catalog/store/product/actions.ts#L654-L659

I'm not sure what exactly that part of the code is supposed to be doing.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by juho-jaakkola** [comment]
The feature was originally introduced here: https://github.com/DivanteLtd/vue-storefront/pull/558/files

**Comment by juho-jaakkola** [comment]
The redirect should be done by this: https://github.com/DivanteLtd/vue-storefront/blob/v1.11.3/core/pages/Product.js#L162-L166

But the `Product.vue` in the theme is in fact not using `Product.js` at all: https://github.com/DivanteLtd/vue-storefront/blob/v1.11.3/src/themes/default/pages/Product.vue

**Comment by juho-jaakkola** [comment]
What is the expected architecture here? Should the page component use `Product.js`?

Or have they been deliberately decoupled, but this particular feature has gone missing when that happened?

**Comment by juho-jaakkola** [comment]
For example the `Home.vue` page component IS still using the mixin from the core: https://github.com/DivanteLtd/vue-storefront/blob/v1.11.3/src/themes/default/pages/Home.vue#L43

**Comment by gibkigonzo** [comment]
@juho-jaakkola You shouldn't be using `Product.js`, probably it was forgotten after moving logic from this mixin.
