### ISSUE TITLE
Unable to start storefront

### ISSUE THREAD

**Issue by imnas** [DivanteLtd/vue-storefront#4361]
Have just tried running yarn dev and unable to start the project

![85b0bcacbfd279d55826ec09415bb2cf](https://user-images.githubusercontent.com/19938321/81482025-faf79500-922b-11ea-89f7-a1d3a8ef9bd2.png)

**Comment by gibkigonzo** [comment]
Can you provide more information? Those warnings shouldn't affect app. Can you reproduce it on master branch?
