### ISSUE TITLE
Lerna not starting

### ISSUE THREAD

**Issue by ArieRym** [DivanteLtd/vue-storefront#4362]
I installed Ubuntu 18.04, docker, nginx, nodejs 12, yarn, redis, Elasticsearch 7.x, mariadb, magento 2.3, vue storefront 1.11.3, vue-storefront-api 1.11.1, mage2, everything works
But when I install according to the instructions VSF Capybara 1.0-rc.1, vue storefront writes error, Tell me why lerna does not start, I count on a more specific reason and how to fix it.

![2020_05_10_12_42_14](https://user-images.githubusercontent.com/20755897/81493205-33df4a80-92bc-11ea-9136-59c378c6aa15.png)

I also tried to install install through cli, but I'm not sure that I correctly understood how?

![2020_05_10_12_52_55](https://user-images.githubusercontent.com/20755897/81493541-aea96500-92be-11ea-8698-3bd24a41a0eb.png)

**Comment by ArieRym** [comment]
I also tried to install install through cli, but I'm not sure that I correctly understood how?

![2020_05_10_12_52_55](https://user-images.githubusercontent.com/20755897/81493528-95081d80-92be-11ea-8399-22d661f2babc.png)

**Comment by gibkigonzo** [comment]
@ArieRym you need to install lerna globaly `yarn global add lerna`

**Comment by ArieRym** [comment]
> But when I install according to the instructions VSF Capybara 1.0-rc.1

**Comment by psmyrek** [comment]
This issue has been solved in https://github.com/DivanteLtd/vsf-capybara/issues/359.

**Comment by gibkigonzo** [comment]
thanks @psmyrek
