### ISSUE TITLE
Running a multistore environment with different domains and themes

### ISSUE THREAD

**Issue by haelbichalex** [DivanteLtd/vue-storefront#4366]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	

We have a Magento 2 multistore environment setup, with one store running in production with VSF as the frontend.
Now we are looking into creating the multistore setup also for the frontend – here a few questions came to mind:
1. Is it possible to have different domains (shop1.com & shop2.com) using the `storeViews` config or should this only be used with `appendStoreCode`?
2. Is is possible to have different themes for the storeViews?

Right now I am more and more convinced we have to run multiple instances of VSF with different configs to create what we want to achieve. Do you think in general this is a good idea?

# Can't find what you're looking for?

## Keep the problem description concise and include:
- [x] A brief description of the problem,
- [x] Where the problem is occurring,
- [x] The length of time the problem has been occurring,
- [x] The size of the problem.

**Comment by pkarw** [comment]
Hi @haelbichalex - if you need to have a separate themes the best way is to run separate instances to not bundle all the themes into the resulting JS bundle (which could be a case when done otherwise)

**Comment by Galch24** [comment]
I have the same task. Does anyone made multistore with different themes?   Or what the best practice for making different theme on each store?

**Comment by haelbichalex** [comment]
@Galch24 We basically did what @pkarw told me in his comment. We have multiple themes in the `src/themes` directory and tell the application which one to use via [node-config](https://github.com/lorenwest/node-config).
