### ISSUE TITLE
How to create 301 redirects in vsf 

### ISSUE THREAD

**Issue by steffen-wirth** [DivanteLtd/vue-storefront#4372]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	

I need information about how to do a 301 redirect for product, category & cms pages. I can't find any related info on the forum and documentation and i think it's a really important missing info when you change from Magento to vsf. 
The Info i found was about creating custom url mapping, see here [https://docs.vuestorefront.io/guide/basics/url.html#how-to-customize-the-mapping-mechanism](url).  I created a module and extended the url store action mappingfallback and also created api for vsf & magento 1 to get the rewritten path for cms, products or categories. But now i'm struggling how to do a 301 redirect in that store action.   

# Can't find what you're looking for?

Is the store action url/mappingFallback the right place to do this? 
How to redirect with 301 for the old url and load the new page with the rewritten url?

**Comment by gibkigonzo** [comment]
As I wrote to you on slack, you can use `AsyncDataLoader` to get access to response object. `AsyncDataLoader` queue will be resolved after components are rendered. [implementation](https://github.com/DivanteLtd/vue-storefront/blob/master/core/server-entry.ts#L34)
```
          AsyncDataLoader.push({
            execute: async ({ context }) => {
              if (context) {
                context.server.response.statusCode = 301
              }
            }
          })
```
Just remember that `AsyncDataLoader` is also triggered in csr and `context` object is only available in ssr

**Comment by gibkigonzo** [comment]
**Update**
We can also make redirection, not only adding status code
```
      const newUrl = '/women/tops-women/tees-women/tees-25/karissa-v-neck-tee-1529.html?childSku=WS10-XS-Green'
      AsyncDataLoader.push({
        execute: async ({ context }) => {
          if (context && !context.url.includes(newUrl)) {
            context.server.response.redirect(301, newUrl)
          }
        }
      })
```

**Comment by steffen-wirth** [comment]
thx @gibkigonzo  i can confirm that this solution works for me. working with the early 1.11 version you need to apply this little bugfix https://github.com/DivanteLtd/vue-storefront/pull/4114/files fixing that the context object is not always null

**Comment by didkan** [comment]
@gibkigonzo @steffen-wirth 
I'm also using the AsyncDataLoader to do server redirects in the mappingFallback action. It works, but every time I do a redirect I get an error in server-error.log:
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
``` 
I'm on VSF 1.11.4
Anything you've seen in your logs?

**Comment by gibkigonzo** [comment]
@didkan that my happen, because after we get from redirected request we still call res.send() https://github.com/DivanteLtd/vue-storefront/blob/master/core/scripts/server.ts#L234-L240 I've created issue for that https://github.com/DivanteLtd/vue-storefront/issues/4647

**Comment by francisjr1997** [comment]
@gibkigonzo I'm also using the AsyncDataLoader to do server redirects but once I use a newUrl as you showed, it gets cached and if I want to change that url into another one, it still redirects to the previous URL I gave. I believe that it's due to caching. How can I solve this?

**Comment by gibkigonzo** [comment]
@francisjr1997 use 302 instead of 301. Cache is normal with 301 because it's a permanent redirection.

**Comment by francisjr1997** [comment]
@gibkigonzo  But I want google SEO to recognize a new URL has been placed instead of the old one. I think 302 won't help.

**Comment by didkan** [comment]
@francisjr1997 I think what @gibkigonzo is trying to say is that 301 redirects get cached pretty much everywhere. From proxies, to routers to your own OS and browser. It is not necessarily a VSF cache "issue".
That is kind of the nature of 301:s. Once you decide to use a 301 it is slightly out of your control once it has propagated enough.
Eventually your new 301 will take effect, but it requires the old one to be purged from different caches online.
In local dev env it is usually enough to restart browser or flush OS DNS cache.

With regards to Google and this specific case I would handle it like this:
* implement your 301 in VSF to the correct redirect URL
* Add another 301 (e.g. in nginx) that redirects the previous faulty 301 redirect to the new correct URL
This way Google will find your canonical URL even if they already had time to index the previous faulty one.
