### ISSUE TITLE
Use vuex ui-store instead of global events from event-bus in UI interactions

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#44]
Now we have 3 events for toggling overlay, microcart and sidebar. It would be much better if we move all ui-related common events to one store. There is ui-store.js atm providing overlay, microcart and sidebar interactions but it's not used.

Definition of done: sidebar, overlay and microcart ui interactions are fired from ui-store.js not from global event bus

**Comment by mercs600** [comment]
@patrykpiston are you working on it ? I could refactore evens to ui-store

**Comment by patrykpiston** [comment]
Sure Adam, I could focus on rewriting classes to scss and later RWD :)

**Comment by mercs600** [comment]
I think we can close it.
