### ISSUE TITLE
configurableChildrenStockPrefetchStatic setting broken?

### ISSUE THREAD

**Issue by juho-jaakkola** [DivanteLtd/vue-storefront#4423]
## Current behavior

I set this in the configuration:
```
"products": {
    "configurableChildrenStockPrefetchStatic": true
```

As documented here: https://docs.vuestorefront.io/guide/basics/configuration.html#products

Then I run this on the category page:
```
parentProduct.configurable_children.forEach((child) => {
    console.log(child.stock)
}
```

The code above is logging `undefined` as the stock status of every child product.

## Expected behavior

The child products found from `product.configurable_children` should contain the stock information for each child product.

## Repository
`v.1.11.3`

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by juho-jaakkola** [comment]
Or have I understood the documentation wrong.

How I understand this part is that the values *within* the `configurabe_children` array get updated:

> Vue Storefront tries to dynamically get the stock quantities for simple products related to the configurable ones (products included in the configurabe_children array).

But does it in fact mean that only the caches are populated so that the children have the latest stock data, but that the values within `parentProduct.configurabe_children` array do not get updated?

**Comment by pkarw** [comment]
@juho-jaakkola I don't remember exactly but I guess they're just cached with this prefetching and filled into `configurable_children` only after you enter a PDP of specifc product - out of perf.opt purposes (we don't have full product data on PDP where these items are fetched so it makes no sens to add the info to `configurable_children`). Please look at (1.12): https://github.com/DivanteLtd/vue-storefront/blob/b02d06cb798f2bff65b38a9e5ddd04b11e27930a/core/modules/catalog-next/store/category/actions.ts#L114 and https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/catalog-next/helpers/cacheProductsHelper.ts
