### ISSUE TITLE
Update profile from My Account gives a 500 error on /api/user/me on validation fail and user is not aware of save failure

### ISSUE THREAD

**Issue by aloupfor** [DivanteLtd/vue-storefront#4427]
## Current behavior
Update profile from `My Account` gives a 500 error on `/api/user/me` on validation fail and user is not:
- aware of save fail
- aware of fields that failed validation
- able to change data that failed validation.

## Expected behavior
Update profile from `My Account` on validation fail, user is:
- aware of save fail
- aware of fields that failed validation
- able to change data that failed validation.

## Steps to reproduce the issue
On a project, users are unable to update their profile from `/my-account`.
I am able to trigger a similar behavior on https://demo.vuestorefront.io.

I create an account on https://demo.vuestorefront.io.
I go to https://demo.vuestorefront.io/my-account/shipping-details.
I fill all fields except "Phone Number"

![demo vuestorefront io_my-account_shipping-details](https://user-images.githubusercontent.com/11750180/82450721-58ea6f00-9aad-11ea-92f4-f4af8a2f0566.png)

I click "Update my shipping details"
Filled field appear on https://demo.vuestorefront.io/my-account/shipping-details

![demo vuestorefront io_my-account_shipping-details (1)](https://user-images.githubusercontent.com/11750180/82450741-5ee05000-9aad-11ea-9c0c-1a327a80c969.png)

I reload https://demo.vuestorefront.io/my-account/shipping-details page and then I become aware that something went wrong as my shipping details are lost. 

![demo vuestorefront io_my-account_shipping-details (2)](https://user-images.githubusercontent.com/11750180/82450763-66075e00-9aad-11ea-9179-107adf6c7208.png)

There is no error message in html.
User has no way to know that an error occurred ans will not be able to change data that failed validation.

In browser developer tools Network tab, I see a 500 error on: https://demo.storefrontcloud.io/api/user/me

```
{"code":500,"result":{"errorMessage":"\"telephone\" is required. Enter and try again.","code":400}}
```

I have similar errors on a project :

```
{"code":500,"result":[{"keyword":"maxItems","dataPath":".customer.addresses","schemaPath":"#/properties/customer/properties/addresses/maxItems","params":{"limit":2},"message":"should NOT have more than 2 items"}]}
```

```
{"code":500,"result":[{"keyword":"minLength","dataPath":".customer.addresses[0].postcode","schemaPath":"#/properties/customer/properties/addresses/items/properties/postcode/minLength","params":{"limit":5},"message":"should NOT be shorter than 5 characters"}]}
```

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by teuma86** [comment]
I have just come across a similar issue with the zip-code.  I have removed zip-code as required from VSF and the backend engine (Magento)  However the API is still wanting a min length of 3.

**Comment by pkarw** [comment]
I'm not sure but I guess we had a `notification` shown in that case before @gibkigonzo ?

**Comment by gibkigonzo** [comment]
As I see we don't display any notification `core/pages/MyAccount.js:47` Only logger.
This error occurs because we changed magento and there are different validations. We should also adjust validations in theme.
@teuma86 you need to change it here `src/themes/default/components/core/blocks/MyAccount/MyShippingDetails.vue:283`

**Comment by teuma86** [comment]
@gibkigonzo The issue was was with the API Call throwing a 500 error about zip code length.  Which was tracked to a scemafile within the API

**Comment by pkarw** [comment]
@gibkigonzo is this something we can close?

**Comment by teuma86** [comment]
FIX:
Update the below file within the API to match the validation you require.
src/models/userProfile.schema.json

**Comment by pkarw** [comment]
@teuma86 can you please create pull request with this fix?
