### ISSUE TITLE
Demo URL fails - https://demo.vuestorefront.io

### ISSUE THREAD

**Issue by sachinkondana** [DivanteLtd/vue-storefront#4444]
Demo URL fails in my local with status code **500**

<img width="1027" alt="Screenshot 2020-05-21 at 3 46 25 PM" src="https://user-images.githubusercontent.com/33169894/82549277-4e49db80-9b7a-11ea-848d-90a7f7c96f7d.png">

`
curl 'https://demo.vuestorefront.io/api/catalog/vue_storefront_catalog/attribute/_search?_source_include=activity%2Cattribute_code%2Cattribute_id%2Cdefault_frontend_label%2Cdefault_value%2Centity_type_id%2Cfrontend_input%2Cfrontend_label%2Cid%2Cis_user_defined%2Cis_visible_on_front%2Cis_visible%2Cis_comparable%2Coptions%2Ctier_prices&from=0&request=%7B%22query%22%3A%7B%22bool%22%3A%7B%22filter%22%3A%7B%22terms%22%3A%7B%22attribute_code%22%3A%5B%22color%22%2C%22erin_recommends%22%2C%22price%22%2C%22size%22%2C%22activity%22%2C%22final_price%22%2C%22id%22%2C%22image%22%2C%22name%22%2C%22new%22%2C%22original_price%22%2C%22original_price_incl_tax%22%2C%22price_incl_tax%22%2C%22product_links%22%2C%22sale%22%2C%22sku%22%2C%22special_price%22%2C%22special_price_incl_tax%22%2C%22special_from_date%22%2C%22special_to_date%22%2C%22status%22%2C%22tax_class_id%22%2C%22tier_prices%22%2C%22type_id%22%2C%22url_path%22%2C%22url_key%22%5D%7D%7D%7D%7D%7D&size=150&sort=' \
  -H 'authority: demo.vuestorefront.io' \
  -H 'accept: application/json' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'origin: http://localhost:3001' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: http://localhost:3001/error' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  --compressed
`

**Comment by gibkigonzo** [comment]
Hey, we've made changes with magento/ES instance. Index for demo has been changed to `vue_storefront_magento_1` So it should be `https://demo.storefrontcloud.io/api/catalog/vue_storefront_magento_1/attribute/_search`, not `https://demo.vuestorefront.io/api/catalog/vue_storefront_catalog/attribute/_search`

**Comment by gibkigonzo** [comment]
I will change config in default.json with 1.11.4 release

**Comment by gibkigonzo** [comment]
It should work fine. I've added `vue_storefront_catalog` index to config in `https://demo.storefrontcloud.io/api`
