### ISSUE TITLE
vue-storefront-api not working with local magento setup?

### ISSUE THREAD

**Issue by sachinkondana** [DivanteLtd/vue-storefront#4452]
Was there is any issues in with vue-storefront-api?

<img width="1056" alt="Screenshot 2020-05-22 at 8 40 54 PM" src="https://user-images.githubusercontent.com/33169894/82682375-cee90480-9c6c-11ea-8d7f-37ad1a536d7c.png">

`
curl 'http://localhost:8080/api/catalog/vue_storefront_catalog/attribute/_search?_source_include=activity%2Cattribute_code%2Cattribute_id%2Cdefault_frontend_label%2Cdefault_value%2Centity_type_id%2Cfrontend_input%2Cfrontend_label%2Cid%2Cis_user_defined%2Cis_visible_on_front%2Cis_visible%2Cis_comparable%2Coptions%2Ctier_prices&from=0&request=%7B%22query%22%3A%7B%22bool%22%3A%7B%22filter%22%3A%7B%22terms%22%3A%7B%22attribute_code%22%3A%5B%22color%22%2C%22erin_recommends%22%2C%22price%22%2C%22size%22%2C%22activity%22%2C%22final_price%22%2C%22id%22%2C%22image%22%2C%22name%22%2C%22new%22%2C%22original_price%22%2C%22original_price_incl_tax%22%2C%22price_incl_tax%22%2C%22product_links%22%2C%22sale%22%2C%22sku%22%2C%22special_price%22%2C%22special_price_incl_tax%22%2C%22special_from_date%22%2C%22special_to_date%22%2C%22status%22%2C%22tax_class_id%22%2C%22tier_prices%22%2C%22type_id%22%2C%22url_path%22%2C%22url_key%22%5D%7D%7D%7D%7D%7D&size=150&sort=' \
  -H 'Connection: keep-alive' \
  -H 'Accept: application/json' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://localhost:3000' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:3000/error' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  --compressed
`

**Comment by fuzzyjared** [comment]
this seems to be working again on my end. I tired the setup earlier this week with the demo and there was a comment about an endpoint change. However in testing again without making the change it seems to be working.

[https://github.com/DivanteLtd/vue-storefront/issues/4444](url)

> Hey, we've made changes with magento/ES instance. Index for demo has been changed to `vue_storefront_magento_1` So it should be `https://demo.storefrontcloud.io/api/catalog/vue_storefront_magento_1/attribute/_search`, not `https://demo.vuestorefront.io/api/catalog/vue_storefront_catalog/attribute/_search`

**Comment by agtoncerqueira** [comment]
Someone is getting error like those warnings, when running npm install?

`warning url-loader@1.1.2: Invalid bin field for "url-loader".
info fsevents@1.2.11: The platform "win32" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > eslint-config-standard@12.0.0" has incorrect peer dependency "eslint-plugin-node@>=7.0.0".
warning " > eslint-config-standard@12.0.0" has incorrect peer dependency "eslint-plugin-promise@>=4.0.0".
warning " > eslint-config-standard@12.0.0" has incorrect peer dependency "eslint-plugin-standard@>=4.0.0".`

**Comment by sachinkondana** [comment]
@fuzzyjared this won't be a URL issues, since if you see the screenshot it shows some signature issues. Are any graphQL or elastic search dependency setups are incomplete?

**Comment by gibkigonzo** [comment]
Hey :) there is issue for that in vsf-api. There were some breaking changes in one of @types dependencies and that's why you get this error. So please track this issue https://github.com/DivanteLtd/vue-storefront-api/issues/446
