### ISSUE TITLE
Error when integrating custom entity for mage 2 vuestorefront

### ISSUE THREAD

**Issue by ArjanStudent** [DivanteLtd/vue-storefront#4470]
When following documentation on https://docs.vuestorefront.io/guide/cookbook/elastic.html#_4-extend-elasticsearch-entities-for-vsf to add a custom extension from magento to vue storefront.  

The error i get is :
`error: Error occured: Error: Invalid URI`

even though I can copy the URI from the error message,
 use it in postman and get a normal response.

**Comment by pkarw** [comment]
@kkdg can you please check it?
