### ISSUE TITLE
Issue in Webpack.config.ts

### ISSUE THREAD

**Issue by shubham0503** [DivanteLtd/vue-storefront#4473]
## Current behavior
When we run yarn dev then `chunksSortMode` option inside `core\build\webpack.base.config.ts` throws an error saying 

> Type '"none"' is not assignable to type '"auto" | "manual" | ((entryNameA: string, entryNameB: string) => number)'.

## Expected behavior
The compilation issue shouldn't be there.

## Steps to reproduce the issue
Delete node_modules folder and install packages via `yarn` then run `yarn dev`

## Repository
https://github.com/DivanteLtd/vue-storefront
(Issue is in master only)

## Can you handle fixing this bug by yourself?

- [x] YES

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.

- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Google Chrome latest version
- OS: Windows 10 Pro
- Node: 10.16.0
- Code Version: 1.11.4

**Comment by gibkigonzo** [comment]
@shubham0503 I can't reproduce it. Here are newest types for this module https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/html-webpack-plugin/index.d.ts#L58 and we can use 'none' as a value :thinking: Feel free to reopen if this still occurs.

**Comment by JakubKontra** [comment]
Hi guys,
i have this error too. 


**Environment details**
Browser: Google Chrome latest version
OS: Mac OSX
Code Version: 1.12.2

**Comment by gibkigonzo** [comment]
@JakubKontra check in node_modules/@types/html-webpack-plugin/index.d.ts what type has `chunksSortMode`
