### ISSUE TITLE
Commands do not work: "build", "docker-compose -f docker-compose.elastic7.yml up", "yarn build && yarn && yarn start"

### ISSUE THREAD

**Issue by ArieRym** [DivanteLtd/vue-storefront#4489]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [1 ] I am running the latest version
- [1 ] I checked the documentation and found no answer
- [1 ] I checked to make sure that this issue has not already been filed

I have clean Ubuntu 18.04, Elasticsearch 7.3.2, redis server, nodejs 12.x, pm2@^2.10.4, nginx, php 7.2, Docker 03/19/10, Vue Storefront 1.11.4, Vue Storefront API 1.11 0 , 1

Installing vue storefront is a constant stress, for six months I could not install putting a bunch of vue store + vue store api + capybara + magento2-vsbridge-indexer
I tried to install both through the installer and through the manual installation, but there are always problems during the installation process.
Now for specific notes:

1.) Vue Storefront
“yarn build” does not work, so I can’t install the application.

My bash script for Vue Storefront

```
cd "${DIR_VSF}" || exit 255
cat <<EOM | tee "${DIR_VSF}/config/local.json" >/dev/null
{
  "server": {
    "host": "127.0.0.1",
    "port": 3100,
    "protocol": "http"
  },
  "redis": {
    "host": "127.0.0.1",
    "port": 6379,
    "db": 0
  },
  "api": {
    "url": "http://api.jblab.ru"
  },
  "elasticsearch": {
    "index": "vue_storefront_magento_1",
    "indices": [
      "vue_storefront_magento_1"
    ]
  },
  "images": {
    "useExactUrlsNoProxy": false,
    "baseUrl": "http://api.jblab.ru/img/",
    "productPlaceholder": "/assets/placeholder.jpg"
  },
  "install": {
    "is_local_backend": true
  },
  "tax": {
    "defaultCountry": "RU"
  },
  "i18n": {
    "defaultCountry": "RU",
    "defaultLanguage": "RU",
    "availableLocale": ["ru-RU"],
    "defaultLocale": "ru-RU",
    "currencyCode": "RUB",
    "currencySign": "₽",
    "currencySignPlacement": "preppend",
    "dateFormat": "l LT",
    "fullCountryName": "Russian Federation",
    "fullLanguageName": "Russian",
    "bundleAllStoreviewLanguages": true
  }
}
EOM

cd ${DIR_VSF}
yarn install
yarn build
yarn start
```

![Screenshot from 2020-05-30 02-06-03](https://user-images.githubusercontent.com/20755897/83326815-8648d100-a294-11ea-97a0-c97e22eae134.png)
 
![Screenshot_from_2020_05_30_13_44_47](https://user-images.githubusercontent.com/20755897/83326904-3fa7a680-a295-11ea-9e47-610ab0d0d44e.png)

2.) Vue Storefront API
In Vue Storefront API not working command "docker-compose -f docker-compose.elastic7.yml up"

My bash script for Vue Storefront API

```
cat <<EOM | tee "${DIR_VSF_API}/config/local.json" >/dev/null
{
  "server": {
    "host": "127.0.0.1",
    "port": 3130
  },
  "elasticsearch": {
    "host": "127.0.0.1",
    "port": 9200,
    "indices": [
      "vue_storefront_magento_1"
    ],
    "apiVersion": "7.2"
  },
  "redis": {
    "host": "127.0.0.1",
    "port": 6379,
    "db": 0
  },
  "authHashSecret": "__SECRET_CHANGE_ME__",
  "objHashSecret": "__SECRET_CHANGE_ME__",
  "tax": {
    "defaultCountry": "RU"
  },
  "magento2": {
    "imgUrl": "http://magento.jblab.ru/media/catalog/product",
    "api": {
      "url": "http://magento.jblab.ru/rest",
      "consumerKey": "XXXXXXXXX",
      "consumerSecret": "XXXXXXXXX",
      "accessToken": "XXXXXXXXX",
      "accessTokenSecret": "XXXXXXXXX"
    }
  },
  "magento1": {},
  "imageable": {
    "whitelist": {
      "allowedHosts": [
        "magento.jblab.ru"
      ]
    }
  }
}
EOM

cd "${DIR_VSF_API}"
yarn install
yarn build
yarn start
yarn db7 new
docker-compose -f docker-compose.elastic7.yml up
```

![Screenshot_from_2020_05_30_15_30_05](https://user-images.githubusercontent.com/20755897/83327151-75e62580-a297-11ea-88ed-119ccc181137.png)

3.) Capybara used to work through "yarn global add lerna", now does not work now you need to do so "yarn build && yarn && yarn start", I get this error

![Screenshot_from_2020_05_30_16_00_12](https://user-images.githubusercontent.com/20755897/83327205-ce1d2780-a297-11ea-838d-963b34fd5ea6.png)

3.) magento2-vsbridge indexer
I asked them why the data does not load in ES7, they said that you need to install magento2-vsbridge-indexer from the second branch, I did this to no avail, but asked for an answer, they generally closed my question. Is not cool.

4.) Installation via Cli
This is a good idea, but I have not tried it yet: I read somewhere that I can install capybara or vsf-default via Cli, but even in Vue Storefront version 1.11.4 from the VSF root I run the installer and I see no alternative choice, there is no choice capybara themes. Maybe I'm not starting Cli correctly.
In the meantime, I'm just embedding my bash script for local.json. What you need to write on the command line to start Cli to try.

As a result, I can’t start anything at all, Commands do not work: "build", "docker-compose -f docker-compose.elastic7.yml up", "yarn build && yarn && yarn start"

But the instructions do not lead to the desired result.
Please give a short instruction without unnecessary words, namely the sequence of commands in the console in my case with Ubuntu, so that this really leads to the result. I want to see a full working kit
Tell me what I'm doing wrong, because before everything worked.

Most of all, I wish you great success.

**Comment by sadowskipawel** [comment]
+1 i can't build it

**Comment by gibkigonzo** [comment]
Hey
1. there is some bug with babel and node 12+ https://github.com/babel/babel/issues/11439
here is fix for us https://github.com/DivanteLtd/vue-storefront/pull/4491/commits/72070e1c06b52be86e8e9b84767c81a1e020bafa
2.Those errors telling you that ports are already taken by other apps.  I don't know what dockers do you run, so check which dockers taken those ports and kill them.
3. when you add capybara you always need to install deps. by `lerna bootstrap` or by `yarn install`
4. here you have info about vsf-cli https://docs.vuestorefront.io/guide/cookbook/setup.html#_4-storefront-cli-at-your-service

**Comment by ArieRym** [comment]
> +1 i can't build it
> Solution, you need to build it twice
> 
> yarn install && yarn build
> 
> rm -fr node_modules
> 
> rm yarn.lock
> 
> yarn install && yarn build

this crutch didn’t work, errors again

![Screenshot from 2020-06-01 14-27-21](https://user-images.githubusercontent.com/20755897/83393743-ed8d8f00-a414-11ea-9640-b642f0427701.png)

**Comment by ArieRym** [comment]
> Hey
> 
> 1. there is some bug with babel and node 12+ [babel/babel#11439](https://github.com/babel/babel/issues/11439)
>    here is fix for us [72070e1](https://github.com/DivanteLtd/vue-storefront/commit/72070e1c06b52be86e8e9b84767c81a1e020bafa)
> 
> 2.Those errors telling you that ports are already taken by other apps. I don't know what dockers do you run, so check which dockers taken those ports and kill them.
> 
> 1. when you add capybara you always need to install deps. by `lerna bootstrap` or by `yarn install`
> 2. here you have info about vsf-cli https://docs.vuestorefront.io/guide/cookbook/setup.html#_4-storefront-cli-at-your-service

1.) I did not understand the first point, it was eventually fixed or not, can I download vue storefront now and will it work in a stable installation order, as before?

2.) The fact is that ports 6379, 9200, 9300 are always provided under redis and ElasticSearch. Especially since I installed clean Ubuntu and there should not be anything busy, I did it; they get hired by redis and ElasticSearch. How to do data loading in ElasticSearch?

![12](https://user-images.githubusercontent.com/20755897/83397165-c639c080-a41a-11ea-991f-d420dd072630.png)


3.) What is it and how to make a sequence of commands for capybara to work

**Comment by ArieRym** [comment]
@Tomasz Kostuch What about these questions?

**Comment by gibkigonzo** [comment]
@ArieRym Hey, sorry for late response 
1. This commit has been added to 1.12 release. But if you use 1.11.4 then you can add this changes and it should work with node lts.
2. If you want to have running redis and ES on your machine and in docker then change ports either for dockers or for redis/es on ubuntu. You can load data to ES by running `yarn mage2vs import` also you can use `magento2-vsbridge indexer` which is more flexible.
3. You can install it by git clone to `src/themes/capybara`. Then you need to install dependencies by running `yarn` or `lerna bootstrap`. And you need to update local.json based on local.config.js (I will update readme in capybara because there is still old info about local.json). There is also more automatic way, but it will be available after release of new version vsf cli.
4. we need to release new version. here is the implementation of installing theme https://github.com/DivanteLtd/vue-storefront/pull/4227

**Comment by ArieRym** [comment]
Thanks for answering. I appreciate your concern and understand that you work hard on developing VSF. But all this is still not installed, I’ve tried everything
1.) I do not see the capybary theme when I run "vsf init" and select the release "1.12"

![111](https://user-images.githubusercontent.com/20755897/83557515-6f71db00-a52f-11ea-9f38-893f28b38f88.png)

2.) It is also not installed through the Installer.
Swears at "Can't start Docker in background.", Although docker is installed, I even pointed out "sudo docker-compose up - in the line" in /var/www/jblab.ru/vue-storefront/core/scripts/installer.js d "and all this exactly leads to the same error.

![Screenshot from 2020-06-02 22-31-52](https://user-images.githubusercontent.com/20755897/83557389-2faaf380-a52f-11ea-831f-90dbb0f6d7e8.png)


3.) "Yarn Build" never starts.
I downloaded the vue storefront repository, put the local.json config in the "config" folder, put capybara manually, all according to the instructions, then ran yarn install && yarn build.
It's just some kind of joke :(

![Screenshot from 2020-06-03 00-06-09](https://user-images.githubusercontent.com/20755897/83557148-c4f9b800-a52e-11ea-847e-116fead48dfe.png)


```
git clone https://github.com/DivanteLtd/vue-storefront.git "${DIR_VSF}"
cd "${DIR_VSF}" || exit 255
cat <<EOM | tee "${DIR_VSF}/config/local.json" >/dev/null
{
  "server": {
    "host": "127.0.0.1",
    "port": 3100,
    "protocol": "http",
    "api": "api"
  },
  "redis": {
    "host": "127.0.0.1",
    "port": 6379,
    "db": 0
  },
  "api": {
    "url": "http://api.jblab.ru"
  },
  "elasticsearch": {
    "index": "vue_storefront_magento_1",
    "indices": [
      "vue_storefront_magento_1"
    ]
  },
  "images": {
    "useExactUrlsNoProxy": false,
    "baseUrl": "http://api.jblab.ru/img/",
    "productPlaceholder": "/assets/placeholder.jpg"
  },
  "install": {
    "is_local_backend": true
  },
  "tax": {
    "defaultCountry": "RU"
  },
  "i18n": {
    "defaultCountry": "RU",
    "defaultLanguage": "RU",
    "availableLocale": ["ru-RU"],
    "defaultLocale": "ru-RU",
    "currencyCode": "RUB",
    "currencySign": "₽",
    "currencySignPlacement": "preppend",
    "dateFormat": "l LT",
    "fullCountryName": "Russian Federation",
    "fullLanguageName": "Russian",
    "bundleAllStoreviewLanguages": true
  }
}
EOM
cd "${DIR_VSF}"
yarn global add lerna
git clone https://github.com/DivanteLtd/vsf-capybara src/themes/capybara
cd src/themes/capybara && git submodule update --init --remote && git checkout develop
sudo sed -i 's|src/themes/default|src/themes/capybara|' ${GEN_PATH}/${VSF_FRONT_WEB_HOST}/tsconfig.json
sudo sed -i 's|vue-storefront/theme-default|vue-storefront/theme-capybara|' ${GEN_PATH}/${VSF_FRONT_WEB_HOST}/config/default.json
cd "${DIR_VSF}" && yarn && yarn build
```

Solving the problem of the third point would be excellent!

Please reproduce the script. Record a video or show a sequence of commands in the console that will lead you to success.

**Comment by gibkigonzo** [comment]
@ArieRym Thanks. I see that there is a bug, here is fix https://github.com/DivanteLtd/vue-storefront/pull/4503 Which will be added in 1.12.1. 
Also I see that installer require more focus because there is no clear path to install vsf. I will try to fix that as soon as possible.

**Comment by ArieRym** [comment]
@tomasz How to use your workaround (config.i18n.defaultLocale)? Please write just what and where to click or enter commands in console? Because for me it is not clear. And the second question, when will it be fixed, approximately? Hour, day, week, month, I just really don’t know how long it will take to solve the issue of assembling the project?

**Comment by gibkigonzo** [comment]
```
  "i18n": {
    "defaultCountry": "RU",
    "defaultLanguage": "RU",
    "availableLocale": ["ru-RU"],
    "defaultLocale": "ru-RU",
    "currencyCode": "RUB",
    "currencySign": "₽",
    "currencySignPlacement": "preppend",
    "dateFormat": "l LT",
    "fullCountryName": "Russian Federation",
    "fullLanguageName": "Russian",
    "bundleAllStoreviewLanguages": true
  }
```
When we generate translations we use `availableLocale` and storeViews. We assumed that en-US ise default local, which is wrong. So in your case if you are missing en-US in `availableLocale` then it will fail. It will get `undefined`. What you can do to fix it, you can change `availableLocale` into `"availableLocale": ["ru-RU", "en-US"]`

**Comment by ArieRym** [comment]
@tomasz I'm happy. Happened. You are cool.

**Comment by ArieRym** [comment]
@tomasz But...
1.) above the address bar does not offer to install the application
2.) In the api.jblab.ru folder, when I try to run "yarn db7 new" I get "Error Command" db7 "not found. Did you mean" db "?"

**Comment by gibkigonzo** [comment]
yeah, there is only `yarn db new` I've added info in readme of vsf-api :) 
```
Tools are adjusted to ES7. You can use yarn db new, yarn restore, yarn mage2vs import. Just make sure that you have set up config.elasticsearch.apiVersion to 7.1.
```

**Comment by ArieRym** [comment]
> 1.) above the address bar does not offer to install the application
1.) @tomasz  What do you think about the first question that is indicated above?
2.) Ok.

**Comment by ArieRym** [comment]
@tomasz What is known on this issue (1.) above the address bar does not offer to install the application), more precisely what to do, why it does not work?

**Comment by gibkigonzo** [comment]
@ArieRym this is normal information. If you first time run `yarn start` then first time pm2 process will be created. Run second time `yarn start` and you will get
```
yarn run v1.17.3
$ cross-env NODE_ENV=production TS_NODE_PROJECT="tsconfig-build.json" pm2 start ecosystem.json $PM2_ARGS
[PM2] Applying action restartProcessId on app [server](ids: [ 0, 1, 2, 3 ])
[PM2] [server](0) ✓
[PM2] [server](1) ✓
[PM2] [server](2) ✓
[PM2] [server](3) ✓
```
That because applications server are already running.
