### ISSUE TITLE
[Bug] [Next] My account - impossible to change data

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/vue-storefront#4499]
## Current behavior
It is impossible to change data in 'My profile' and 'Shipping' sections in 'my account'. Changes made are not saved.

## Expected behavior
It should be possible to change data in 'My profile' and 'Shipping' sections in 'my account'. Changes should be saved.

## Steps to reproduce the issue

initial condition: user is logged in
1. go to 'My account'
2. click on 'My profile'
3. change First name
4. click 'update personal data' button
5. click on 'Shipping details'
6. click on 'change' button next to any address
7.  change street name
8. click 'update the addresses' button
9. click on ' My profile' - check the data
10. click on 'Shipping details' - check the data

![EditMyaccount](https://user-images.githubusercontent.com/57936972/83514186-70751f00-a4d3-11ea-9b3b-41b0be58f7c5.gif)

related to the issue: https://github.com/DivanteLtd/vsf-pro/issues/34

## Repository
Next - https://lovecrafts-demo.storefrontcloud.io/

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by AddyAhmed** [comment]
Hi @akrajna 

I faced the same problem, a fix is available for the "update personal data" which can be found below

Bug: https://github.com/DivanteLtd/vsf-capybara/issues/510
Fix: https://github.com/DivanteLtd/vsf-capybara/commit/bac3e5ea6e74c4cba470486407dc0ea3520173fd

To get the shipping details working, you will need to implement a similar fix to **components/organisms/o-my-account-shipping-details.vue**

Add the following imports 

```
import config from 'config';
import pick from 'lodash-es/pick';
```

Update line 247 

from

`let userDataToUpdate = this.$store.state.user.current;`

to 

`let userDataToUpdate = pick(this.$store.state.user.current, config.users.allowModification);`

Ensure allowModification is present under "users" in the **config/default.json**

```
"users": {
    "autoRefreshTokens": true,
    "loginAfterCreatePassword": true,
    "endpoint": "/api/user",
    "history_endpoint": "/api/user/order-history?token={{token}}&pageSize={{pageSize}}&currentPage={{currentPage}}",
    "resetPassword_endpoint": "/api/user/reset-password",
    "createPassword_endpoint": "/api/user/create-password",
    "changePassword_endpoint": "/api/user/change-password?token={{token}}",
    "login_endpoint": "/api/user/login",
    "create_endpoint": "/api/user/create",
    "me_endpoint": "/api/user/me?token={{token}}",
    "refresh_endpoint": "/api/user/refresh",
    "allowModification": ["firstname", "lastname", "email", "addresses"]
  }
```
  
The fix only sets the required customer details, in this case firstname, lastname, email and address. Previously it was sending the entire customer data, causing the API to throw an error and return a 500.

**Comment by AddyAhmed** [comment]
The delete address has the same issue

The fix in my previous comment needs to be appleid to the method **deleteAddress** in the same file **components/organisms/o-my-account-shipping-details.vue**

Update 

`let userDataToUpdate = this.$store.state.user.current;`

to

`let userDataToUpdate = pick(this.$store.state.user.current, config.users.allowModification);`

**Comment by Fifciu** [comment]
For VSF Next - @filipsobol is working on that right now
For VSF1 x Capybara - @AdamPawlinski will handle issues with updating & removing shipping details - thanks for useful snippets @AddyAhmed

**Comment by filipsobol** [comment]
VSF Next now supports updating My Account data.
