### ISSUE TITLE
CSS refactor

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#45]
All CSS rules related to colors, font sizes and types, margins & paddings should be atomic. Now there are some components (e.g ColorButton.vue) with very simple and repeatable css rules which should be atomic.

**Comment by patrykpiston** [comment]
Hey, you can find my commit [here](https://github.com/patrykpiston/vue-storefront/commit/f781f784263aae9d7ea073b17b5ae11fcc23880a)
