### ISSUE TITLE
Price $NaN is displayed

### ISSUE THREAD

**Issue by aloupfor** [DivanteLtd/vue-storefront#4513]
## Current behavior
Price $NaN is displayed.

## Expected behavior
Price is correctly displayed.

## Steps to reproduce the issue
Open: https://demo.vuestorefront.io/olivia-1-4-zip-light-jacket.html
Put 13 as quantity.

![Screenshot from 2020-06-04 13-39-45](https://user-images.githubusercontent.com/11750180/83752491-eced3680-a668-11ea-84b0-ae9b935a5fcf.png)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chromium Version 73.0.3683.75
- OS: Debian 9

## Additional information
Seems related to price value 1000.

**Comment by thonglm122** [comment]
Same issue when product price >1000. How to fix it?

**Comment by simonmaass** [comment]
I can reproduce this error aswell - also there is not tax displayed...

**Comment by gibkigonzo** [comment]
@simonmaass please check this pr https://github.com/DivanteLtd/vue-storefront/issues/4521

**Comment by simonmaass** [comment]
@gibkigonzo was just fixing it myself aswell - thnx for quick reponse!

Quick question... why dont we leverage the function toLocaleString more?

`const options = { style: 'currency', currency: currencyCode, minimumFractionDigits: fractionDigits, maximumFractionDigits: fractionDigits };`

if we insert style and currencyCode we dont need to applyCurrencySign for example.... what do u think?

**Comment by gibkigonzo** [comment]
@simonmaass Can you please create new feature issue with that?

**Comment by simonmaass** [comment]
@gibkigonzo done
