### ISSUE TITLE
Above the address bar does not offer to install the application

### ISSUE THREAD

**Issue by ArieRym** [DivanteLtd/vue-storefront#4517]
@tomasz Kostuch Where in the new version of vue storefront the ability to install the application disappeared, in the address bar?

![Screenshot from 2020-06-03 15-51-28](https://user-images.githubusercontent.com/20755897/83759784-b5df4b00-a691-11ea-9e8b-459628679ed1.png)

![Screenshot from 2020-06-04 19-17-59](https://user-images.githubusercontent.com/20755897/83765051-50428d00-a698-11ea-9a88-8ce91cd87e9b.png)

**Comment by gibkigonzo** [comment]
@ArieRym 
Do you have same error in dev mode? Can you show first error message? because you have on screen error after redirection, so please check what caused redirection in your case

**Comment by ArieRym** [comment]
@tomasz Kostuch I don’t quite understand what I need to do regarding the “redirect”?

I can assume this is due to the lack of goods.

If so, then I want to download products not through mage2vuestorefront, but through magento2-vsbridge-indexer. I’ll turn to them three times on this issue, but they don’t answer on the page https://github.com/DivanteLtd/magento2-vsbridge-indexer/issues/274. You can look?

I thought that I didn’t load data due to the fact that I need to upload it to docker containers, but I can’t do this because, as I wrote here (https://github.com/DivanteLtd/vue-storefront/ issues / 4489 # issuecomment-636746497) problems with ports that they are occupied by redis and ElasticSearch services, then I decided to change port values ​​in the files when I run "docker-compose -f docker-compose.elastic7.yml -f docker-compose .nodejs.yml up" it starts with new ports.

Then, when I create empty indexes "yarn db new" they are loaded into ElasticSearch: 9200, instead they should be created like containers on port 9201, but as far as I understand. How to create empty indexes on the new port 9201 or how to make data load 9200?

It would also be interesting for me to run through "docker-compose -f docker-compose.elastic7.yml up", but as I understand it, I need to have Kibana?
And it would be even cooler to start via "docker-compose.varnish.yml", is there any normal (not fragmentary) instruction on how to start with varnish?

But now the main question is how to load data from magento 2.3.3 into ElasticSearch 7?
Then the issue with a non-working application will be resolved automatically?
