### ISSUE TITLE
Error on installation 

### ISSUE THREAD

**Issue by CavalcanteLeo** [DivanteLtd/vue-storefront#4520]
## Current behavior

I couldn't even install using these command:

```bash
git clone https://github.com/DivanteLtd/vue-storefront.git vue-storefront
cd vue-storefront
yarn
yarn installer
```
the only error i get is that, nothing in the log file

```
node  v13.11.0
imagemagick installeds via homebrew
yarn v1.22.4
```
<img width="1249" alt="Captura de Tela 2020-06-04 às 21 10 39" src="https://user-images.githubusercontent.com/1735944/83823028-28a7f080-a6a9-11ea-8019-966f6d14cb93.png">

**Comment by minhkhoat** [comment]
Sorry
Is this issue fixed?
I try to install today, howeve somthing still error
![image](https://user-images.githubusercontent.com/61462612/84616896-859c7580-aef7-11ea-8c9a-a4808fbb1c1e.png)

**Comment by pkarw** [comment]
Hi @minhkhoat have you tried the fix @gibkigonzo proposed in the #4534?

**Comment by chodaumoi-com** [comment]
I have same issue!!!!

**Comment by minhkhoat** [comment]
@pkarw Hi
I think the branch didn't merge to master, so I can not view the document how to setup theme seperate

**Comment by gibkigonzo** [comment]
Hey, `yarn installer` should work with current master. I've also published vsf cli v0.2.1 and there is also a way to install theme: full installation - `vsf init`, or theme installation - `vsf init:theme`

**Comment by stegithub** [comment]
I've the same issue: https://github.com/DivanteLtd/vue-storefront/issues/5296

**Comment by stegithub** [comment]
Wow! I don't know how but the issue is solved. After a lot of clean installations
