### ISSUE TITLE
Price showing "NaN" on VSF 12.0 version

### ISSUE THREAD

**Issue by thonglm122** [DivanteLtd/vue-storefront#4521]
Hello there,

I just updated VSF 12.0 version but product price showing "$NaN" when price > 1000. The price displayed correctly should be "$1000.00" or "$1,000.00". How to fix it?

Thanks,

**Comment by gibkigonzo** [comment]
@thonglm122 thanks for reporting this issue, I've made pr here https://github.com/DivanteLtd/vue-storefront/pull/4523

**Comment by thonglm122** [comment]
It worked! Thanks for quick response!
