### ISSUE TITLE
No child menu displayed, The pictures does not switch, All products are not available for purchase, Bestsellers without products

### ISSUE THREAD

**Issue by ArieRym** [DivanteLtd/vue-storefront#4524]
The finishing touches are left :)

1) No child menu displayed

![Home_Page_Vue_Storefront](https://user-images.githubusercontent.com/20755897/83994095-09dc7f00-a973-11ea-90f5-bc0ca4a9ae7c.jpg)

2) On the product page, the image does not change when switching colors

![Nadia_Elements_Shell_Vue_Storefront](https://user-images.githubusercontent.com/20755897/83994168-3395a600-a973-11ea-9651-d8ea2cb55d49.jpg)

3) All products are not available for purchase

![Nadia_Elements_Shell_Vue_Storefront2](https://user-images.githubusercontent.com/20755897/83994179-414b2b80-a973-11ea-944d-275486a8543d.jpg)

4) There are no products on the main page in the Bestsellers block

![Home_Page_Vue_Storefront2](https://user-images.githubusercontent.com/20755897/83994202-4e681a80-a973-11ea-888d-3e135d1d2862.jpg)

Vsf version 1.12
Magento ver. 2.3.5-p1

@gibkigonzo  What do you think about this?

**Comment by gibkigonzo** [comment]
duplicated https://github.com/DivanteLtd/vsf-capybara/issues/384
