### ISSUE TITLE
vue-storefront alway  crash!Error 502

### ISSUE THREAD

**Issue by ldc321** [DivanteLtd/vue-storefront#4526]
## Current behavior

I'm running Vue Storefront 1.10.5
I have five servers:
redis/mysql/es/vsf/magento2
The server configuration is the same: CPU: 16   Memory: 64G

## Steps to reproduce the issue

My website always reports 502 errors, about 2 days apart!
I have to cd /vue-storefront ,   and run :yarn start ! The website will work again
**How do I set up this file:ecosystem.json**
This is my configuration：

{
  "apps": [
    {
      "name": "server",
      "max_memory_restart": "1G",
      "instances": "16",
      "exec_mode": "cluster",
      "script": "./core/scripts/server.js",
      "node_args": "--max_old_space_size=8192",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "ignore_watch": [
        "core/build/config.json",
        "node_modules"
      ]
    }
  ]
}

My server configuration is ok!

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
I belive this is not a bug but rather a question

**Comment by ldc321** [comment]
> I belive this is not a bug but rather a question

Yes,i think so! But the problem is deadly!  It means my production environment dies every few days
My website went down again two days ago
I run : yarn start ,Website reworking
This is the error log

`
2020-06-13 03:40:48: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: EADDRNOTAVAIL
2020-06-13 03:40:48:     at ServerResponse.writeHead (_http_server.js:248:11)
2020-06-13 03:40:48:     at ServerResponse.writeHead (/var/www/vue-storefront-api/node_modules/on-headers/index.js:44:26)
2020-06-13 03:40:48:     at ServerResponse._implicitHeader (_http_server.js:239:8)
2020-06-13 03:40:48:     at write_ (_http_outgoing.js:650:9)
2020-06-13 03:40:48:     at ServerResponse.end (_http_outgoing.js:760:5)
2020-06-13 03:40:48:     at ServerResponse.send (/var/www/vue-storefront-api/node_modules/express/lib/response.js:221:10)
2020-06-13 03:40:48:     at ServerResponse.json (/var/www/vue-storefront-api/node_modules/express/lib/response.js:267:15)
2020-06-13 03:40:48:     at apiStatus (/var/www/vue-storefront-api/src/lib/util.js:77:20)
2020-06-13 03:40:48:     at Object.apiError (/var/www/vue-storefront-api/src/lib/util.js:89:10)
2020-06-13 03:40:48:     at /var/www/vue-storefront-api/src/api/catalog.js:92:9 {
2020-06-13 03:40:48:   code: 'ERR_HTTP_INVALID_STATUS_CODE'
2020-06-13 03:40:48: }

`
Unable to connect to ES server
[search] Can not connect the vue-storefront-api / ElasticSearch instance! Error: FetchError in request to ES: FetchError: invalid json response body at https://olightstore.ca/api/catalog/vue_****e=50&sort= reason: Unexpected token < in JSON at position 0

**Comment by pkarw** [comment]
EADDRNOTAVAIL - Please maybe check if the vsfapi has connectivity to the elasticsearch via config.elasticsearch.host address and then please make sure the connectivity from vsf->vsfapi

**Comment by ldc321** [comment]
> EADDRNOTAVAIL - Please maybe check if the vsfapi has connectivity to the elasticsearch via config.elasticsearch.host address and then please make sure the connectivity from vsf->vsfapi

For two days it was normal, but the api process collapsed in the middle of the night! I feel An error status caused all api requests to report an error.. This is just my guess, as the site works fine most of the time.  When the site crashes, all I have to do is restart the api server

**Comment by ldc321** [comment]
this is my config: local.json
![image](https://user-images.githubusercontent.com/57743360/84574290-10864e80-add8-11ea-905c-1028aa7c30e8.png)
It works well

**Comment by ldc321** [comment]
I want to host my vue-storefront and vue-storefront-api  to your cloud server and still use my Magento in the background!   Can this be done. 

I can't solve my own 502 problem

We're under a lot of pressure because our project is already online

Looking forward to your reply 

ryan
地址：广东省深圳市
邮编：518000
手机：18627312414
MSN：
E-mail：cc_software@163.com 
   370049539@qq.com  
On 6/13/2020 19:36，Piotr Karwatka<notifications@github.com> wrote：

EADDRNOTAVAIL - Please maybe check if the vsfapi has connectivity to the elasticsearch via config.elasticsearch.host address and then please make sure the connectivity from vsf->vsfapi

**Comment by ldc321** [comment]
Thank you for your answer.  I have a question about why the API does not use load balancing! Only one api process


> > EADDRNOTAVAIL - Please maybe check if the vsfapi has connectivity to the elasticsearch via config.elasticsearch.host address and then please make sure the connectivity from vsf->vsfapi
> 
> For two days it was normal, but the api process collapsed in the middle of the night! I feel An error status caused all api requests to report an error.. This is just my guess, as the site works fine most of the time. When the site crashes, all I have to do is restart the api server

Thank you for your answer.  I have a question about why the API does not use load balancing! Only one api process

**Comment by ldc321** [comment]
> EADDRNOTAVAIL - Please maybe check if the vsfapi has connectivity to the elasticsearch via config.elasticsearch.host address and then please make sure the connectivity from vsf->vsfapi

I read a article in https://www.toptip.ca/2010/02/linux-eaddrnotavail-address-not.html
My server USES 10,000 ports and the traffic is not high，It could be higher at peak times
How can I solve it， thanks

**Comment by pkarw** [comment]
Please check this one - it should get this issue fixed: https://github.com/DivanteLtd/vue-storefront-api/pull/471/files

**Comment by ldc321** [comment]
> Please check this one - it should get this issue fixed: https://github.com/DivanteLtd/vue-storefront-api/pull/471/files

Thanks ,I also updated the code, now running stable, my job is saved    ^_^
