### ISSUE TITLE
Multi store not working

### ISSUE THREAD

**Issue by darshanperpule** [DivanteLtd/vue-storefront#4530]
## Current behavior
While making request from vue-storefront-api to Magento 2, in every API URL storeCode parameters is getting appended like `http://localhost:8080/api/stock/check?sku=WLNS3621&storeCode=wellness_forever_store`. Due to that, every Magento 2 API request gets failed.

## Expected behavior
Magento 2 API should not fail and return results per store wise.

## Steps to reproduce the issue
1) Configure vue storefront for multi store
2) Switch to any other storeview
3) Run any api from vue-storefront

## Can you handle fixing this bug by yourself?
- [ ] NO

## Environment details

- Browser: Google Chrome
- OS: Linux Mint
- Node: 12.16.3
- Code Version: master branch

**Comment by simonmaass** [comment]
can confirm that multistore works with v1.12... also worked in 1.11...
