### ISSUE TITLE
Reload /checkout results in error on node server

### ISSUE THREAD

**Issue by simonmaass** [DivanteLtd/vue-storefront#4535]
## Current behavior

If you navigate to checkout in frontend and then hit reload (f5) in browser i get the following errors on server side:

```
182|server  | 2020-06-11 14:14:30: cache miss [/checkout], request: 1ms
182|server  | 2020-06-11 14:14:30: Error during render : /checkout
182|server  | 2020-06-11 14:14:30: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
182|server  |     at ServerResponse.setHeader (_http_outgoing.js:470:11)
182|server  |     at /core/scripts/server.ts:199:13
182|server  |     at process._tickCallback (internal/process/next_tick.js:68:7)
180|server  | 2020-06-11 14:14:30: cache hit [/], cached request: 10ms
182|server  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
182|server  | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
182|server  |     at ServerResponse.setHeader (_http_outgoing.js:470:11)
182|server  |     at ServerResponse.header (node_modules/express/lib/response.js:771:10)
182|server  |     at ServerResponse.location (node_modules/express/lib/response.js:888:15)
182|server  |     at ServerResponse.redirect (node_modules/express/lib/response.js:926:18)
182|server  |     at errorHandler (/core/scripts/server.ts:177:18)
182|server  |     at process._tickCallback (internal/process/next_tick.js:68:7)

```

## Expected behavior

no errors shown...

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  chrome
- OS:  linux
- Node:  12
- Code Version:  1.12

**Comment by gibkigonzo** [comment]
I can't reproduce it on current master. Feel free to reopen if problem still occurs.
