### ISSUE TITLE
move fields to omit to config

### ISSUE THREAD

**Issue by simonmaass** [DivanteLtd/vue-storefront#4536]
## Current behavior

in core\modules\catalog\helpers\variant\omitSelectedVariantFields.ts

two fields are hard coded to omit (just cost me 1h to figure this out^^)

`  const fieldsToOmit = ['name', 'visibility']`

## Expected behavior

in my opinion this should be moved to config 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by AishwaryShrivastav** [comment]
Created a conifig 'omitVariantFields' inside config.products and used that instead of hard coded values.
https://github.com/DivanteLtd/vue-storefront/pull/4679/files
