### ISSUE TITLE
Offline orders not working

### ISSUE THREAD

**Issue by darshanperpule** [DivanteLtd/vue-storefront#4543]
## Current behavior
Offline orders not working. Nothing happens when clicking on the button "Place the order".

## Expected behavior
The order should be placed when click on the button "Place the order".

## Steps to reproduce the issue
1. Disable cart synchronize true from vue-storefront/local.json
2. Go to the checkout page and try to place an order in offline mode.

## Can you handle fixing this bug by yourself?
- [ ] NO

## Environment details

- Browser:Google Chrome
- OS: Linux Mint
- Node: 12.16.3
- Code Version: master branch

**Comment by pkarw** [comment]
This mode has not been supported since 1.10. Please not use it.
