### ISSUE TITLE
Vue Storefront won't work on my windows 10

### ISSUE THREAD

**Issue by aws95** [DivanteLtd/vue-storefront#4550]
i tried to follow the docs and all i got is an error message saying that the theme i chose doesn't exist when i ran yarn dev and when i checked there wasn't any themes inside src folder 
can anyone help please?

**Comment by boichoi** [comment]
kindly go to src/themes folder and add theme manually there like in attached image
![themes](https://user-images.githubusercontent.com/51024135/84920694-f05ad600-b0dc-11ea-98d8-0a740db31688.png)

**Comment by boichoi** [comment]
my issue is i could not configure vsf api on windows 10...if you can help plz

**Comment by gibkigonzo** [comment]
duplicate #4520
