### ISSUE TITLE
Hotfix v1.12.1 related to separate theme installation has broken "install theme" link

### ISSUE THREAD

**Issue by AntonioRossi** [DivanteLtd/vue-storefront#4554]
## Current behavior

You get a 404 error when trying to access instruction for theme installation

## Expected behavior

Access the information for theme installation

## Steps to reproduce the issue

* switch to branch "Hotfix v1.12.1"
* navigate to /docs/guide/installation/linux-mac.md
* scroll down to last paragraph "Install the vue-storefront"
* click link "install theme"

You get a 404 error when trying to access instruction for theme installation

**Comment by pkarw** [comment]
@kkdg can you take a look?

**Comment by AntonioRossi** [comment]
To me the link is still broken, here it is the URL missing:

https://github.com/DivanteLtd/vue-storefront/blob/hotfix/v1.12.1/guide/installation/theme.html
