### ISSUE TITLE
serverPrefetch - possible server to client vuex store issue in server-entry.ts

### ISSUE THREAD

**Issue by AbriDelacy** [DivanteLtd/vue-storefront#4558]
While using VSF we found out that using vuex actions that change some module’s store state in a serverPrefetch method, do not **pass serverside state to window.__INITIAL_STATE__**. We assume that this leads to increased request sizes due to needing to execute the same request on client side aswell. In conclusion we assume that the serverPrefetch feature is currently incomplete. Requests could be lowered by adding the following callback to 

https://github.com/DivanteLtd/vue-storefront/blob/master/core/server-entry.ts#L76

```
 context.rendered = () => {
     context.state = store.state
 }
```

We therefore refer to https://ssr.vuejs.org/guide/data.html#final-state-injection and would be more than happy if this could be fixed or if you could give us a hint on wether we use this feature in a wrong way.

**Comment by gibkigonzo** [comment]
@AbriDelacy we use serverPrefetch in default theme https://github.com/DivanteLtd/vsf-default/blob/master/layouts/Default.vue#L97 and it works ok. Is this happen for you with any module? or maybe some specific module is missing data on client side?

**Comment by cartok** [comment]
@gibkigonzo I guess the template rendered on server side is fine and just works on client side in this case, but the data must still be missing. Please recheck if you have the vuex data on client side. The usage of serverPrefetch is documented differently than in your example.

**Comment by Fifciu** [comment]
I also cannot reproduce it.

Do you still have this issue @cartok? Could you prepare us repository with the reproduced issue? Or at least code sample. Otherwise, we cannot do much

**Comment by cartok** [comment]
I'm sorry to say that I also can no longer reproduce this. Might have been the problem that the function that was called did not return a promise. In the current version is see that custom implementation in ssr-renderer.js filterState() where the data gets handled. Not sure if it was like that when this ticket got created. Thanks for trying guys!
