### ISSUE TITLE
Favicon gets loaded 8 times on page load

### ISSUE THREAD

**Issue by simonmaass** [DivanteLtd/vue-storefront#4559]
## Current behavior

The favicon gets loaded 8 times since 1.12 update

![image](https://user-images.githubusercontent.com/32599710/84904027-1ff2e980-b0af-11ea-893d-e4a0c59c9ad1.png)

## Expected behavior

only gets loaded once

## Steps to reproduce the issue

Load homepage in https://demo.vuestorefront.io/ and check network tab

## Repository

master branch v 1.12

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:  v1.12

**Comment by ghisleouf** [comment]
Hi there, 

Same issue on my side on previews versions of VSF.
It seems to be related ( in previous versions of VSF at least) to Vue-Meta and metaInfo() method called several times into page component ...

Unfortunately, I could not check deeper for the moment.

But it would be great to fond the reason why we have so much calls (and http requests).

**Comment by simonmaass** [comment]
any update on this? looks like it still persists in 1.12.2...

**Comment by gibkigonzo** [comment]
This problem exist in all versions and it's chrome problem https://bugs.chromium.org/p/chromium/issues/detail?id=112941
Solution: update pwacompat to 2.0.17 https://github.com/DivanteLtd/vsf-default/blob/master/head.js#L33
I will close it because it needs to be fixed in theme

**Comment by simonmaass** [comment]
yep works.. but i think integrity needs to also be updated... @gibkigonzo
