### ISSUE TITLE
Adjustments of the homepage on mobile

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#456]
Adjustments to the homepage on mobile
- [x] 1. Remove left and right margin in the top, near the „menu” and „cart” buttons 
- [x] 2.Make slider higher
- [x] 3. Change color of circle on „cart” button, like in the design;
- [x] 4. Add 2 columns of product boxes;
- [x] 5. Add gray background to the photo in the product box;
- [x] 6. Add transparency of product photo (20%), like in the design (it changes to 0% after mouseover);
- [x] 7. Change color of the headlines of sections, like in the design;
- [x] 8. Change colors of fonts in product box, like in the design;
- [x] 9. Add mouseover effect on the product box - change color of background, change transparency of the photo from 20% to 0%;
- [x] 10. Remove underline of price for mouseover for product box;
- [x] 11. Change size of font of headline „New Luna Yoga Collection” and other headlines of sections, like in the design;
- [x] 12. Adjust sizes, margins etc. in „New Luna Yoga Collection” section, like in the design;
- [x] 13. Turn off automatic sliding of product in „New Luna Yoga Collection” section;
- [ ] 14. Adjust size and margin of Inspiration blocks in "Get inspired" section
- [x] 15. Change font, colors, button in „Subscribe to the newsletter” section - like in the design;
- [x] 16. Add Social media section in the bottom - like in the design;
- [x] 17. Add mouseover effect for buttons in "social media section”;
- [ ] 18. Add underline in footer
- [ ] 19. Add changes in colors of font and underline for mouseover state of links

Improvements:
- [x] Adding slider’s pagination (dots) on the slides;
- [x] Add „search" and „favorite" button in the top - it requires changes of left and right margins
- [x] When there’s no product in cart - there should be only the icon of cart in the top, without circle and number 0;
- [ ] Change animation of the top while scrolling from the top to bottom, only above the fold;
- [ ] Add one product box - like in the design;
- [ ] Add static new section „Promoted offers” with static banners below slider.

![1c](https://user-images.githubusercontent.com/18116406/34253946-0779bcb2-e64a-11e7-8dd9-337d2caa76ea.png)
![1b](https://user-images.githubusercontent.com/18116406/34253947-0794aa18-e64a-11e7-9f01-6ab51b822637.png)
![1a](https://user-images.githubusercontent.com/18116406/34253948-07b34f86-e64a-11e7-8456-12e8328a13cf.png)

There's the view "Homepage on mobile" available here - https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront-Open-Source.
<img width="360" alt="homepage on mobile" src="https://user-images.githubusercontent.com/18116406/34254017-57441012-e64a-11e7-83d9-cafdf0ea91c1.png">

**Comment by pkarw** [comment]
Please just mark the issues you’re working on or already fixed by marking the specific points in comments

**Comment by pkarw** [comment]
@talalus

**Comment by pkarw** [comment]
Hi All! We do have a release date for 22.01 can I count on you with this issue? :) @rossmc @talalus @collymore @mercs600 @filrak

**Comment by rossmc** [comment]
@pkarw My day job has me pretty busy but will have time to work on a few more.

Below is a list of what I'm working on or have done:
- [ ] &nbsp;1. Remove left and right margin in the top, near the „menu” and „cart” buttons
- [ ] &nbsp;2. Make slider higher
- [ ] &nbsp;3. Change color of circle on „cart” button, like in the design;
- [x] 15. Change font, colors, button in „Subscribe to the newsletter” section - like in the design;
- [x] 16. Add Social media section in the bottom - like in the design;
- [x] 17. Add mouseover effect for buttons in "social media section”;

Improvements:

- [ ] When there’s no product in cart - there should be only the icon of cart in the top, without circle and number 0;

**Comment by pkarw** [comment]
Thanks @rossmc; Great job

**Comment by pkarw** [comment]
@rossmc could you take care of the rest bullets here (4-12?) and then we'll just close the task? :)

**Comment by rossmc** [comment]
@pkarw I won't have time until next Tues/Weds, so happy for anyone else to take a few in the meantime :)

**Comment by pkarw** [comment]
Sure Ross! Let's see who's willing to take this one? :)

We've 2 weeks yet till the release date, I belive we'll handle this

**Comment by mercs600** [comment]
@karolbzik I allowed myself to edit your comment and add task list, because I couldn't see what was fixed
@rossmc I applied your changes on main task list.

**Comment by mercs600** [comment]
@karolbzik According to 11. I think that font-sizes are the same like in the design. 

According to 12. We will have a problem with slider on mobile, it is a little buggy :/ I added issue, but I think it can be problem, because this project wasn't updated from october https://github.com/SSENSE/vue-carousel/issues/116

**Comment by mercs600** [comment]
I moved rest of improvements to new issues.
