### ISSUE TITLE
Is the Multistore feature is supported for Shopify ?

### ISSUE THREAD

**Issue by jesuismaxime** [DivanteLtd/vue-storefront#4560]
Hi there, it’s really a question about the features as we are searching for a potential solution for a potential client. I searched on both the doc (The multi store guide in the doc is focused on Magento) and the forum and I can’t find a clear answer to my question. 

We have potentially 3 Shopify stores (same brand, but 3 unique countries/currencies) to unify. As we are working a lot with Vue in past year, Vue Storefront seems a great solution but a one condition : that is support multiple Shopify stores in one site, is it ?

Thank you!

**Comment by pkarw** [comment]
@jesuismaxime at this moment we don't officialy support Shopify. However Aureate Labs are doing great job adding Shopify support to Vue Storefront Next: https://github.com/aureatelabs/next/tree/shopify-package

**Comment by jesuismaxime** [comment]
I'll go for a rebound on this, since the AureateLabs Shopify project seems to have been merged to your the project: will it supported multiple locale or multi-store and when a stable production version is to be expected?

Thank you!
