### ISSUE TITLE
How should we enable or getting work offline checkout?

### ISSUE THREAD

**Issue by darshanperpule** [DivanteLtd/vue-storefront#4561]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [ ] I am running the latest version

# Is there something you don't understand? What is it? Describe it.	
With respect to our previous bug [https://github.com/DivanteLtd/vue-storefront/issues/4543], how should we enable offline checkout? We want to faster checkout performance. Currently, it's taking 3 to 4 seconds to add to the cart. So we want to enable the offline mode of checkout.

# Can't find what you're looking for?
How exactly the offline mode is working?

**Comment by pkarw** [comment]
Checkout Offline mode is not supported from VSF1.11 on :(
