### ISSUE TITLE
http://localhost:3000/error

### ISSUE THREAD

**Issue by marcelowu** [DivanteLtd/vue-storefront#4566]
vue 1.11
![Captura de tela de 2020-06-18 15-29-05](https://user-images.githubusercontent.com/30912144/85058634-c656f180-b178-11ea-85f7-06922e2cc8ae.png)
![Captura de tela de 2020-06-18 15-29-15](https://user-images.githubusercontent.com/30912144/85058641-c951e200-b178-11ea-9167-71976f475de8.png)
![Captura de tela de 2020-06-18 15-30-07](https://user-images.githubusercontent.com/30912144/85058647-cb1ba580-b178-11ea-8946-1cb207045ba3.png)
![Captura de tela de 2020-06-18 15-30-17](https://user-images.githubusercontent.com/30912144/85058655-ce169600-b178-11ea-9801-e726d15074e4.png)

## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	

# Can't find what you're looking for?

## Keep the problem description concise and include:
- [ ] A brief description of the problem,
- [ ] Where the problem is occurring,
- [ ] The length of time the problem has been occurring,
- [ ] The size of the problem.

**Comment by pkarw** [comment]
Please check the error message in the console you got form Elastic - you need to change the schema (eg. changing the `vue-storefront-api/config/*.schema.json`) and run `yarn db rebuild`
