### ISSUE TITLE
Elasticsearch < 6.X Product Page can't be reached directly

### ISSUE THREAD

**Issue by domideimel** [DivanteLtd/vue-storefront#4572]
## Current behavior

When using VSF with Elasticsearch <= 6 and (probably) + magento2-vsbridge-indexer you get a 500 when loading a product url directly. This is the Error with some additional data thats output to the console:

`{
  "code": 500,
  "result": {
    "root_cause": [
      {
        "type": "query_shard_exception",
        "reason": "failed to create query: Can't parse boolean value [1], expected [true] or [false]",
        "index_uuid": "bCsJKCQTRCysH-Ts8ZBelA",
        "index": "vue_storefront_magento_de_attribute_1592917297"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "vue_storefront_magento_de_attribute_1592917297",
        "node": "x0BZRtWyQQCCEbUAG-DuCg",
        "reason": {
          "type": "query_shard_exception",
          "reason": "failed to create query: Can't parse boolean value [1], expected [true] or [false]",
          "index_uuid": "bCsJKCQTRCysH-Ts8ZBelA",
          "index": "vue_storefront_magento_de_attribute_1592917297",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "Can't parse boolean value [1], expected [true] or [false]"
          }
        }
      }
    ]
  }
}
[search] Can not connect the vue-storefront-api / ElasticSearch instance! Error: Unknown error with API catalog result in resultProcessor for entity type 'attribute'
    at SearchAdapter.exports.modules../core/lib/search/adapter/api-search-query/searchAdapter.ts.SearchAdapter.handleResult (vsf-search-adapter-api-search-query-searchAdapter.server-bundle.js:217:23)
    at Object.resultProcessor (vsf-search-adapter-api-search-query-searchAdapter.server-bundle.js:245:34)
    at server-bundle.js:4473:92
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error during render : /chaz-kangeroo-hoodie?childSku=MH01-XS-Black
Error: Error: Unknown error with API catalog result in resultProcessor for entity type 'attribute'
    at SearchAdapter.exports.modules../core/lib/search/adapter/api-search-query/searchAdapter.ts.SearchAdapter.handleResult (core/lib/search/adapter/api-search-query/searchAdapter.ts:133:14)
    at Object.resultProcessor (core/lib/search/adapter/api-search-query/searchAdapter.ts:161:22)
    at server-bundle.js:4473:92
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at _commonErrorHandler (core/server-entry.ts:18:11)
    at server-bundle.js:22530:41
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

## Expected behavior

The url can be reached without browsing the page before.

## Steps to reproduce the issue

- Magento 2 instance with Demo data and [magento2-vsbridge-indexer](https://github.com/DivanteLtd/magento2-vsbridge-indexer) (V 2.x)
- Elasticsearch <= 6.X
- the current VSF 1.12.X

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Firefox Devloper Edition v 78.0b9 (64-Bit)
- OS: Mac OS Catalina 10.15.5
- Node: v10.21.0
- Code Version: 1.12.1 Release

## Additional information

https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/catalog/helpers/createAttributesListQuery.ts#L20 and https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/catalog/helpers/createAttributesListQuery.ts#L23

the '1' needs to be removed

**Comment by mcs-jonasvanderhaegen** [comment]
Can confirm. I just set up vuestorefront yesterday and had this exact bug, 
I did the adjustment like Dominik Deimel suggested, restarted service-worker.js and error is gone.
