### ISSUE TITLE
configurableChildrenImages helper function incorrect loading images

### ISSUE THREAD

**Issue by MikusMarkevicsMagebit** [DivanteLtd/vue-storefront#4575]
## Current behavior

Loading thumbnail images are set from the main product image

## Expected behavior

Loading thumbnail images should be from configurable children images

```js
'src': getThumbnailPath((!hasImage(child) ? product.image : child.image), config.products.gallery.width, config.products.gallery.height),
'loading': getThumbnailPath(product.image, config.products.thumbnails.width, config.products.thumbnails.height),
```
Unless I am missing something or this is intenional, I think `loading` property should have the same logic as `src`

https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/catalog/helpers/index.ts#L129

```js
'src': getThumbnailPath((!hasImage(child) ? product.image : child.image), config.products.gallery.width, config.products.gallery.height),
'loading': getThumbnailPath((!hasImage(child) ? product.image : child.image), config.products.thumbnails.width, config.products.thumbnails.height),
```

## Steps to reproduce the issue

Visit this demo page, inspect through dev tools the product gallery slides, in all three slides the loading image points to the gray color of the hoodie image.
https://demo.vuestorefront.io/phoebe-zipper-sweatshirt.html?childSku=WH07-XS-Gray

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by fchienvuhoang** [comment]
I also got this error

**Comment by RakowskiPrzemyslaw** [comment]
https://github.com/DivanteLtd/vue-storefront/pull/4740
