### ISSUE TITLE
Allow distinct API URLs for server and client-side calls

### ISSUE THREAD

**Issue by michael-bouvy** [DivanteLtd/vue-storefront#4581]
## What is the motivation for adding / enhancing this feature?

VSF uses `.api.url` to communicate with VSF API, both in server-side (SSR) and client-side contexts.

Hence, this URL has to be a public hostname, reachable by the client (ie. https://api.vue-store-front-shop.com). 

In order to reduce potential overhead when VSF API is located on the same local network as VSF, it would be useful to be able to specify a server-side context specific API URL (ie. http://api.cluster.local).

This would reduce potential overhead: HTTPS, reverse proxy, etc. and make it possible for a service mesh (ie. Istio) to inject headers for tracing purposes as trafic would be HTTP (encrypted between services using mTLS).

## What are the acceptance criteria 

- [ ] Add an `.api.serverSideUrl` config property
- [ ] Use this property in server-side context
- [ ] Fallback to `.api.url` when not available

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.

- [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.

## Additional information

N/A

**Comment by Fifciu** [comment]
Doesn't https://github.com/DivanteLtd/vue-storefront/pull/3801 satisfy you?

**Comment by michael-bouvy** [comment]
Yes, thanks @Fifciu and sorry for the noise!
