### ISSUE TITLE
Prepare scripts to release integration packages and core (part 1)

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#4586]
ATM there is no simple way to publish NPM packages of a certain integration. What we agreed on is that we don't want to rely on lerna anymore as our repo is more like a set of independent monorepos than one big monorepo. We're keeping lerna only for local symlinks

Each integration currently has:
- API Client
- Composables (depending on API Client)
- Theme (depending on Composables)
- CLI (depending on Theme)

We should prepare a script (`release.js`) inside root `scripts` directory that is responsible for releasing packages related to specific integration.

# Propsed API:
```bash
node ./scripts/release.js {integration}/{package[optional])
```

- Release all packages for commercetools
```bash
node ./scripts/release.js commercetools
```

- Release only commercetools composables
```bash
node ./scripts/release.js commercetools/composables
```
There should be 3 gradations of releases: `major` (x.0.0) `minor` (0.x.0), `path` (0.0.x) all fo them specified as cli argument (required)

For example to release a minor upgrade for all commercetools packages we should write:
```bash
node ./scripts/release.js commercetools - minor
```

Commands: `core/comemrcetools/about-you` (you can automate it and base on dir structure for everything so it will be {integration}/package-name-without-workspace} (without `@vue-stroefront`)
# Implementation details

Under the hood you should just use some npm client to release the packages (there is a bunch of them on the internet, do your investigation ;>)

You should be cautious about dependencies versioning. When we release a package and bump its version we want to be sure that all its dependants have it upgraded as well.

**Comment by Fifciu** [comment]
When I update commercetools-theme I will look at other commercetools-x packages - should I update `dependencies` reference to them to their newest version?

**Comment by filrak** [comment]
1. yup
2. yup, also (1) doesnt apply to independent integrations (they should be a dependency of anything anyway)
3. error, always has to be provided. You can also show a list if its not provided so it can be selected
4. like it was (`^` is a default)
5. Only for pathes, otherwise keep other packages unchanged
6. what you mean by order rules?

Ad plan: you also have to take care of situation when release fails. In that case everything should come back to its previous state.
