### ISSUE TITLE
Static Blocks not shown

### ISSUE THREAD

**Issue by peterlohaus** [DivanteLtd/vue-storefront#4596]
## Current behavior
Vue Storefront is not able to display static blocks configured in magento using the `Block.vue` component since introduction of storefront-query-builder in v.1.12.0

## Expected behavior
Display of static block content.

## Steps to reproduce the issue
- Configure Static BLock in Magento
- Output in vsf with `Block.vue` component

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by gibkigonzo** [comment]
hey, there was similar issue https://github.com/DivanteLtd/vue-storefront/issues/4529 Please check if this can help you

**Comment by peterlohaus** [comment]
@gibkigonzo Unfortunately #4529  didn't help. storefront-query-builder already runs on recent v1.0.1

Results of query triggered by storefront-query-builder shows two dozens of search results. Subsequent code always returns first element. Sort order of elements listed vary after arbitrary static block is resaved in magento admin panel.

![Screenshot from 2020-07-06 13-22-34](https://user-images.githubusercontent.com/33315207/86588554-385a7380-bf8c-11ea-8bd3-5629d8a7ec48.png)

**Comment by gibkigonzo** [comment]
Please try this fix https://github.com/DivanteLtd/vue-storefront/pull/4605 We still have old hash for storefront-query-builder thats why it fetched old version

**Comment by peterlohaus** [comment]
@gibkigonzo This commit solved the issue I reported. Thank you for your fast response.
