### ISSUE TITLE
Product quantity gets doubled at random

### ISSUE THREAD

**Issue by 1070rik** [DivanteLtd/vue-storefront#4598]
## Current behavior
In some cases (totally random) a product added to the cart once will be sent to Magento twice.
The cart only shows it once, you see a price and tax of only one product only to find out that it got ordered twice once you receive the Magento email or check your order history.
![image](https://user-images.githubusercontent.com/14279658/86461735-b6b7db00-bd2a-11ea-9b27-e5fe9fd8e4f8.png)
In this image you can see that the product was sent with a quantity of 2. Sadly I did not get the chance to screenshot the amount showing as 1 in the cart.

## Expected behavior
The quantity shown in the storefront should match the quantity thats sent to Magento.

## Steps to reproduce the issue
Order a product and hope that it happens. I've seen it happen like 3 times in the last 2 weeks.

## Repository
https://github.com/DivanteLtd/vue-storefront

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome 83.0.4103.116
- OS: Mac OS 10.15.5
- Node: v10.18.0
- Code Version: v1.11.0

## Additional information
This occurs totally random and it took me a long time to eventually recreate it after a couple reports from clients.

**Comment by pkarw** [comment]
@gibkigonzo isnt this related with this issue of checking the checksum for cod virus or products in o2m you’ve just fixed?

**Comment by 1070rik** [comment]
I've gotten another report of this happening. When looking back at the hotjar recording that was made we can see that the user added a product to the shopping cart, after some time where nothing happened there was a reload and when the page reloaded the cart was empty (maybe they emptied their cart on another device?). They then proceeded to re-add the products to their cart which caused them to show up double on the order receipt.

**Comment by gibkigonzo** [comment]
@1070rik Here is similar problem https://github.com/DivanteLtd/vue-storefront-api/issues/477 But you should have info `< Wrong qty for` Can you check ( based on logs) if those products qty get updated in o2m? On screen that you provided it looks like product already has qty: 2 when it gets to vsf-api

**Comment by 1070rik** [comment]
After some time @gibkigonzo and I came to a possible cause of the problem. It's not really the same as the other issue. The orders that went wrong all had one thing in common. The cart from magento was empty whereas the cart from the client wasn't empty.
A temp fix would be to downgrade to magento 2.3.4 (where this didn't happen).
