### ISSUE TITLE
Wrong prices due to wrong tax calculation client side

### ISSUE THREAD

**Issue by simonmaass** [DivanteLtd/vue-storefront#4611]
## Current behavior

When setting the following settings:

tax.calculateServerSide = false
tax.sourcePriceIncludesTax = true

Wrong prices are calculated!!!

If the product is 75€ inkl Tax as source price for example the calculated price is 71,43€ - which is WRONG

## Expected behavior

if i set 
tax.calculateServerSide = false
tax.sourcePriceIncludesTax = true

and source price is 75€ the calculated price should also be 75€!!

## Steps to reproduce the issue

Set settings: 
tax.calculateServerSide = false
tax.sourcePriceIncludesTax = true

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version: 

## Additional information

i believe here: core\modules\catalog\helpers\taxCalc.ts

the function createSinglePrice need to know if it should produce prices including tax or without!

**Comment by pkarw** [comment]
Hi @simonmaass can you share your tax settings from the `vue-storefront-api` as well?

**Comment by simonmaass** [comment]
@pkarw good point - so i tried to debug this a big more and the problem is when the settings are not aligned...

So on API side i had tax.calculateServerSide = true and on client i had tax.calculateServerSide = false

But shouldnt the API still return the prices including tax if on api tax.sourcePriceIncludesTax = true

**Comment by simonmaass** [comment]
other related question... is there a reason all decimal places are left:

`priceWithTax { price: 94.28571428571428, tax: 4.714285714285714 }`

could you to a .toFixed(2) to both?

Reason is that in product.current.price_incl_tax the price is: 98.99999999999999 and not how it is in ES 99...

**Comment by pkarw** [comment]
@simonmaass the settings must be in sync. That's the thing. PLease make sure they are.
Actually I'm not sure why there is `!hasOriginalPrice` condition in the https://github.com/DivanteLtd/vue-storefront-api/blob/0024ecd172d8ebc928ef26c8b9d354d201d1c308/src/lib/taxcalc.js#L78

@gibkigonzo can you check it? Maybe this is the reason it doesn't work the right way?

**Comment by gibkigonzo** [comment]
@pkarw `hasOriginalPrice` it is only needed when we make second calculation on same product, which not happens in vsf-api
@simonmaass how about `finalPriceInclTax` setting? There are cases where final_price is used as price https://github.com/DivanteLtd/vue-storefront-api/blob/0024ecd172d8ebc928ef26c8b9d354d201d1c308/src/lib/taxcalc.js#L104  https://github.com/DivanteLtd/vue-storefront-api/blob/0024ecd172d8ebc928ef26c8b9d354d201d1c308/src/lib/taxcalc.js#L109 If you have `finalPriceIncludesTax` set to true and `final_price` doesn't have tax then `price` will be smaller (we assume then that tax is in price so we can extract it).

**Comment by simonmaass** [comment]
i want final prices to include tax and have on api and client "finalPriceIncludesTax": true,

**Comment by pkarw** [comment]
@gibkigonzo @simonmaass what's the status in here? Can we close this ticket?

**Comment by simonmaass** [comment]
yeah i guess this can be closed...
