### ISSUE TITLE
Add the website_id to the user/register call

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#4613]
## What is the motivation for adding / enhancing this feature?

Reference/discussion: https://github.com/DivanteLtd/vue-storefront/issues/3848

We need to add the `website_id` to be configurable via: `config.storeViews.*.website_id` and then passed via the JSON body to `vue-storefront-api`/`storefront-api`. Then we need to pass this very same information to the magento instance. So probably a minor change to https://github.com/DivanteLtd/magento would be required

## What are the acceptance criteria 

- [ ] `website_id` is configurable in the config.storeViews
- [ ] `website_id` is supported by the user/register call

**Comment by ArjanStudent** [comment]
Hey, Thanks for helping me with this in Slack but when I did more testing it also worked with passing on only the Store_id. One of the 2 needed to be passed though for it to register.

**Comment by grimasod** [comment]
Interestingly, if the storeCode is before "/rest" in the Magento url in VS-API, it works fine on Magento 2.3.5 without any storeId or websiteId.
E.g. `https://magento.example.info/us/rest/V1/customers/`
Unfortunately the same url format causes other problems with authenticated routes, which seems like a complicated issue to work through.

For now, @ArjanStudent 's solution is easy. Just to expand on it, all that's needed is to add the storeId to the user/register event data, in the callRegister method, in the Register component. E.g.:

```
this.$store.dispatch('user/register', {
  email: this.email,
  password: this.password,
  firstname: this.firstName,
  lastname: this.lastName,
  storeId: currentStoreView().storeId
})
```
