### ISSUE TITLE
Building new module

### ISSUE THREAD

**Issue by leonel1524** [DivanteLtd/vue-storefront#4617]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	

this [documentation](https://docs.vuestorefront.io/guide/cookbook/module.html) is outdated?
I tried to build a new module from scratch but it never registered, I followed the steps in the documentation and it didn't work for me. Can somebody help me?

# Can't find what you're looking for?

## Keep the problem description concise and include:
- [ ] A brief description of the problem,
- [ ] Where the problem is occurring,
- [ ] The length of time the problem has been occurring,
- [ ] The size of the problem.

**Comment by AishwaryShrivastav** [comment]
Hello @leonel1524, 
I think these docs are little outdated, you can refer to this [video](https://www.youtube.com/watch?v=bS7bHni36_k) by @mohammad-k8 on "How to register a module when using vsf-capybara theme".

**Comment by leonel1524** [comment]
Thank you @AishwaryShrivastav, I will review it as soon as I can and I will tell you how it went

**Comment by leonel1524** [comment]
The video has helped me a lot, thanks @AishwaryShrivastav

**Comment by AishwaryShrivastav** [comment]
Thanks @leonel1524, also for further questions, try posting it on slack or forum. 
Issues are generally for bugs and features.
HTH
