### ISSUE TITLE
<Short Description> from Magento2 API is not connected to Capybara Theme on Vue Storefront

### ISSUE THREAD

**Issue by AndriyDiduh** [DivanteLtd/vue-storefront#4618]
## Current behavior

Please look at the https://capybara.storefrontcloud.io/luma-yoga-for-life.html  
The **Description** of the product is same on "top" portion and on "bottom" portion of the page. 
There is no **Short Description** being used by Vue Storefront. 

## Expected behavior

I expect  **Short Description** from Magento2 API to be used on upper "top" portion under the price and separately the **Description** on lower part at the "bottom" portion.

Thank you for your time.

**Comment by pkarw** [comment]
Hi @AndriyDiduh can you post this kind of issues to the https://github.com/DivanteLtd/vsf-capybara directly? Let's keep this one here, no problem

**Comment by AndriyDiduh** [comment]
> Hi @AndriyDiduh can you post this kind of issues to the https://github.com/DivanteLtd/vsf-capybara directly? Let's keep this one here, no problem

Ok, will post other issues directly to capybara repo.

**Comment by pkarw** [comment]
Fixed in Cpaybara
