### ISSUE TITLE
Add product qty to cart (not enough stock) on product detail page leads to wrong (not existing) quantity in microcart overview and header

### ISSUE THREAD

**Issue by NicolasHofmairT23** [DivanteLtd/vue-storefront#4619]
## Current behavior

User can add products to the cart which are not in stock. Quantity and price is displayed wrong in microcart.

## Expected behavior

Quantity needs to be checked after adding product to the cart every time. If added quantity is bigger than stock do not only display notification. Also fix the quantity in Header counter and in Microcart.

## Steps to reproduce the issue

1. Go to a product and add the maximum stock amount to cart.
(Right now) for this one the stock seems to be 73 (not 100 as displayed) https://demo.vuestorefront.io/didi-sport-watch.html (this also is broken here https://next.storefrontcloud.io/bolo-sport-watch.html but the available qty seems to be correct) 

2. Add the same product in any quantity you wish below 73 (f.e. 10) again to the cart on the product detail page.

3. Microcart counter in Header is now 83. Open the microcart. Quantity for the product is 83, too. But price is calculated for the amount of 6716$. So server totals for the product seem to be correct but display is wrong. Quantity in product.qty has wrong, not existing number. If you change quantity in microcart again it will jump back to 73.

## Repository
https://demo.vuestorefront.io/

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome, latest version
- OS: IOS
- Node: https://demo.storefrontcloud.io
- Code Version: https://demo.storefrontcloud.io

**Comment by pkarw** [comment]
I can confirm. WIth VSF 1.11 after this kind of error the previous quantiy and totals were restored 
![image](https://user-images.githubusercontent.com/211899/87642090-59b81e00-c749-11ea-945a-4277eb3dcebc.png).

@gibkigonzo I think it got broken after the cart refactoring. in VSF it was this line that was in charge of fixing the qty back: https://github.com/DivanteLtd/vue-storefront/blob/daa61c0592bd0453f673af8bde45a60438ff7ce1/core/modules/cart/store/actions/quantityActions.ts#L10
