### ISSUE TITLE
Decompress items in `api-search-query` adapter

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront#4629]
## Current behavior

If you're using the `api-search-query` and make benefits of the `fieldsToCompress` config option, you will get a smaller catalog-product response from API. But the configurable children don't have alle their attributes anymore, regarding the `fieldsToCompress` feature of the API.
In the `api-search-query` adapter is already a method to decompact the attribute keys of the response, but not to "decompress" the missing attributes of the configurable children.

In our case this leads to some problems with wrong prices and option values on the product-detail-page (especially in client-side requests) as several configurable product options are missing these attributes. On server-side requests it works without problems – this is because of the `mapFallbackUrl` routine which is returning the product in a plain, uncompressed response and puts it into the in-memory cache. This is because `url/getFallbackByUrl` action does not use a `SearchAdapter`, so is not compressed.

## Expected behavior

Not only "decompact" the product response items, and also "decompress" them. So we need to extend the `core/lib/search/adapter/api-search-query/searchAdapter.ts`. I'll do it and open a PR.

## Repository

From `1.12.1` to latest `develop`

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome
- OS: OSX
- Node: NodeJS 13.14
- Code Version: 1.12.1

**Comment by pkarw** [comment]
Fair point. We didn't decompress the configurable_children by default because on PDP it's being merged with main product anyway but you're right that if you're using it on PLP it may lead to errors. Thanks
