### ISSUE TITLE
Where can we get more info about the integration with Salesforce Commerce Cloud?

### ISSUE THREAD

**Issue by danechitoaie** [DivanteLtd/vue-storefront#4633]
On the vuestorefront site and in the readme of this repo I see mentioned integration with Salesforce Commerce cloud but in https://docs.vuestorefront.io/guide/integrations/integrations.html I don't see it.

Any idea where can we get more info about this.

**Comment by pkarw** [comment]
Hi there! Great that you’re asking. We’ve got plans adding SFCC support it’s not yet ready. Please contact us via hello@vuestorefront.io
