### ISSUE TITLE
Configuration lost when syncing items from server after log-in

### ISSUE THREAD

**Issue by revlis-x** [DivanteLtd/vue-storefront#4641]
## Current behavior
As a logged-in user with configurable items in cart, when logging out and back in again, configurable items lose their configuration and turn into the default simple product of the original configurable product.

## Expected behavior
Configurable Items are restored from server, as they were previously put in the cart.

## Steps to reproduce the issue
1. Be logged-in
2. Add configurable item to cart (preferebly not the default variant)
3. Log out and log-in again.
-> Item in cart lost its configuration, is no longer a configurable product, but a simple product in default configuration from previiously added item.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [X] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [X] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
I don’t remember if it worked before (but I guess it did). With the shopping sync action we should add to the cart the primary SKU and set the “configurable_options” that should came from the cart/pull api endpoint

**Comment by pkarw** [comment]
... line 112 of VSF1.11.4 merge actions:
https://github.com/DivanteLtd/vue-storefront/blob/hotfix/v1.11.4/core/modules/cart/store/actions/mergeActions.ts

**Comment by pkarw** [comment]
... it seems exactly the same with1.12 so the question is if Magento returns the product options correctly and which Magento version you’ve got exactly @revlis-x?
https://github.com/DivanteLtd/vue-storefront/blob/hotfix/v1.12.2/core/modules/cart/store/actions/mergeActions.ts

**Comment by revlis-x** [comment]
Magento returns the options correctly, they are just not added to the client cart item. It is repdoducable on all test systems (demo.storefrontcloud.io and so on). 
Furthermore this leads to a situation, whre the simple is synced back to the server (which already has the configurbale) leading to wrong totals.

**Comment by revlis-x** [comment]
I debugged a little and found, that `product/findProducts` action returns default variant simple-sku for sku field which causes the error.
https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/cart/store/actions/productActions.ts#L9

As a workaround one can change `items[0].sku` to `items[0].parentSku` on Line 19 and it works, but I don't know why findProducts call returns wrong sku in the first place and what should be the correct format.
