### ISSUE TITLE
[Next] Missing features in basic checkout.com integration

### ISSUE THREAD

**Issue by Qrzy** [DivanteLtd/vue-storefront#4656]
- [x] Nuxt module passes only `publicKey` to setup function, thus it's not possible to set custom styles, webhook URL or tokenized card key (see https://github.com/DivanteLtd/vue-storefront/blob/d572e03c37454bea2d623ed9dd1d6a4bc7e9cd3f/packages/checkout-com/src/configuration.ts#L36 and https://github.com/DivanteLtd/vue-storefront/blob/d572e03c37454bea2d623ed9dd1d6a4bc7e9cd3f/packages/checkout-com/nuxt/plugin.js#L5)

- [x] Config is missing the `localization` option that allows to set custom placeholders.

- [x] Let's allow to pass all the options above also through the `initForm` function - this is important especially for localization.

- [x] There are no sourcemaps in the package, please add them via rollup config.

- [x] Sdk will be autoloaded based on the config

- [x] Let's allow to fetch all available payment methods from cko

- [x] Readme update

**Comment by Qrzy** [comment]
I did miss one point. :) 

> Let's allow to fetch all available payment methods from cko

**Comment by EugeneHlushko** [comment]
Fetching should probably take locale into account right?

**Comment by Fifciu** [comment]
I changed numbers to bullets so you can be more conscious of task's status.
Branch: https://github.com/DivanteLtd/vue-storefront/tree/update-nuxt-theme-module
