### ISSUE TITLE
Error running from "next" branch

### ISSUE THREAD

**Issue by Woland2k** [DivanteLtd/vue-storefront#4659]
## Current behavior

Get the following error after following instructions on setting up from next branch (https://github.com/DivanteLtd/vue-storefront/tree/next):

![image](https://user-images.githubusercontent.com/1566470/88238868-b7f86b80-cc37-11ea-95f7-1e9d7d5bda63.png)

## Expected behavior
Expect to see the storefront.

## Steps to reproduce the issue
1. Download repo from https://github.com/DivanteLtd/vue-storefront/tree/next
2. Run the following commands:
```
yarn install
yarn build:core
yarn build:prismic
yarn build:ct:tools
yarn dev:ct
```
3. Open web page http://192.168.50.131:3000/
4. See the error.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome latest
- OS: Windows 10
- Node: Latest NodeJS
- Code Version: https://github.com/DivanteLtd/vue-storefront/tree/next

## Additional information
Looks like URI is not configured, however I do see those in the setup theme file.

**Comment by Fifciu** [comment]
Have you configured setup API Credentials in theme's nuxt.config.js?

**Comment by Woland2k** [comment]
I checked nuxt.config.js and see the following lines in there (i know those are dev values but URI is specified):

```
    ['@vue-storefront/commercetools/nuxt', {
      disableGenerateTokenMiddleware: false,
      api: {
        uri: 'https://api.commercetools.com/vsf-ct-dev/graphql',
        authHost: 'https://auth.sphere.io',
        projectKey: 'vsf-ct-dev',
        clientId: 'xlea3xo3vcavMN5kmDlFP4nu',
        clientSecret: 'JejrKtQgU_KkNxPn_96UEAaEoPocNFqy',
        scopes: [
          'create_anonymous_token:vsf-ct-dev',
          'manage_my_orders:vsf-ct-dev',
          'manage_my_profile:vsf-ct-dev',
          'manage_my_shopping_lists:vsf-ct-dev',
          'manage_my_payments:vsf-ct-dev',
          'view_products:vsf-ct-dev',
          'view_published_products:vsf-ct-dev'
        ]
      }
    }]
```

**Comment by mmeester** [comment]
Thank you for sharing your client token and secret 🙏

**Comment by filrak** [comment]
@mmeester actually this one is public for our test instance, feel free to use ;)

**Comment by filrak** [comment]
@Woland2k Next doesnt work on Windows right now (its on the roadmap tho) I suggest using WSL in this case

**Comment by Woland2k** [comment]
> Thank you for sharing your client token and secret 🙏

This is already public, as it is part of this repo, so no secrets were shared.

> @Woland2k Next doesnt work on Windows right now (its on the roadmap tho) I suggest using WSL in this case

What is WSL?
