### ISSUE TITLE
Why does not the "Install App" offer appear in the browsers Safari, Opera.?

### ISSUE THREAD

**Issue by ArieRym** [DivanteLtd/vue-storefront#4662]
Installed a versions: Vue storefront api v1.12.1, Vue storefront 1.12.1, Capybara 1.0.2, Magento 2.3.5. 
What needs to be done for the application to be installed from these browsers?

**Comment by Qrzy** [comment]
Do you mean desktop versions of those browsers? 
If so, it's a matter of A2HS support, you can easily check that here:
https://caniuse.com/#feat=web-app-manifest

**Comment by ArieRym** [comment]
Yes. It turns out that safari won't work?

**Comment by ArieRym** [comment]
@Qrzy do you have an application running on iOS?
