### ISSUE TITLE
Checkout - Personal details wrong validation 

### ISSUE THREAD

**Issue by mercs600** [DivanteLtd/vue-storefront#469]
I noticed some problem with validation on first step of checkout. According to git history problem occured somewhere here https://github.com/DivanteLtd/vue-storefront/commit/375c3cf18128deed9a9613ed9bf605a3ec3463a9  

@akbarik Could you check this please ? Check please video below also. 
https://www.dropbox.com/s/iylqo2ug7wrwu2k/checkout-validation.mov?dl=0

**Comment by pkarw** [comment]
@mercs600 @akbarik i've just tested it on demo.vuestorefront.io and couldn't reproduce;
BUT on localhost where I do have the very latest version it seems to be a real issue - the same behavior like on @mercs600 video

**Comment by pkarw** [comment]
@mercs600 you're right; it's introduced in https://github.com/DivanteLtd/vue-storefront/commit/375c3cf18128deed9a9613ed9bf605a3ec3463a9

the problem occurs only within the 1st section (Personal Details); the other sections works just fine as for me
