### ISSUE TITLE
Create a CLI tool for VSF Next

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#4703]
1. Create a new project in `core` folder called `cli`
2. The CLI should be runnable via `init <projectname>` (`projectname` should determine npm project name and folder)
3. After that you should see a list of available backends (`inquirer.js`) https://www.npmjs.com/package/inquirer
4. Once the backend is chooses generate a project based on  agnostic and integration themes

**Comment by Fifciu** [comment]
Looks like we cannot use `yarn init`: https://classic.yarnpkg.com/en/docs/cli/init/
I will use `yarn cli:init` for now

**Comment by Fifciu** [comment]
```
projectname should determine npm project name and folder
```
Ok, I have to open createdProjectDirectory/package.json and change `name` to `<projectName>` in the `createProject` script, right?
