### ISSUE TITLE
Cannot run the application on kubernetes 

### ISSUE THREAD

**Issue by dhouhamaa** [DivanteLtd/vue-storefront#4722]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [ ✔️] I am running the latest version
- [✔️ ] I checked the documentation and found no answer
- [✔️ ] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	

I have deployed vue storefront app along with the API and the other needed services (elasticsearch, redis etc ) to my kubernetes cluster using the yaml files but the application is not working ! I was able to curl to all the other services but not the app and the API , I always receive " Connection refused" when I run curl cmd to the corresponding endpoints through port 8080 and 3000. 

# Can't find what you're looking for?
There is not much documentation on how to make the app run on kubernetes .

## Additional information
The application runs properly when deployed through docker and I can see it working from the browser .
Since it worked on docker , I pushed the images to a private registry and then I specify these images in the yaml files for kubernetes deployment . That was the only change of the yaml files that I did comparing to what is there in master branch.

**Comment by michael-bouvy** [comment]
Hi @dhouhamaa, can you please provide your full Kubernetes YAML files?

**Comment by dhouhamaa** [comment]
@michael-bouvy  I will paste the yaml files that I've changed but all the rest is same as the master branch.
For the vue storefront app ,  vue-storefront-deployment.yaml : 

apiVersion: apps/v1 

kind: Deployment 
metadata:
  name: vue-storefront
spec:
  selector:
    matchLabels:
      app: vue-storefront
  template:
    metadata:
      labels:
        app: vue-storefront
    spec:
      containers:
      - name: vue-storefront
        image: private.registry.com/vsf/vuestorefront_app:latest
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
        envFrom:
        - configMapRef:
            name: vue-storefront-config
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /var/www/.babelrc
          name: code
          subPath: .babelrc
          readOnly: true
        - mountPath: /var/www/config
          name: code
          subPath: config
          readOnly: true
        - mountPath: /var/www/core
          name: code
          subPath: core
        - mountPath: /var/www/ecosystem.json
          name: code
          subPath: ecosystem.json
          readOnly: true
        - mountPath: /var/www/.eslintignore
          name: code
          subPath: .eslintignore
          readOnly: true
        - mountPath: /var/www/.eslintrc.js
          name: code
          subPath: .eslintrc.js
          readOnly: true
        - mountPath: /var/www/lerna.json
          name: code
          subPath: lerna.json
          readOnly: true
        - mountPath: /var/www/package.json
          name: code
          subPath: package.json
          readOnly: true
        - mountPath: /var/www/src
          name: code
          subPath: src
          readOnly: true
        - mountPath: /var/www/var
          name: code
          subPath: var
        - mountPath: /var/www/dist
          name: dist
      imagePullSecrets:
      - name: mykey
      volumes:
      - name: code
        hostPath:
          path: "/root/vue-storefront"
          type: DirectoryOrCreate          
      - name: dist
        emptyDir:
          medium: Memory

and the rest is same as  the files here https://github.com/DivanteLtd/vue-storefront/tree/master/kubernetes

For the API 

-  elasticsearch-deployment.yaml 

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: elasticsearch
  namespace: customer-portal-dev
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: private.registry.com/customer-portal/vsf/elasticsearch:latest
        env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: bootstrap.memory_lock
          value: "true"
        - name: discovery.type
          value: single-node
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        ports:
        - containerPort: 9200
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
      imagePullSecrets:
      - name: mykey
      volumes:
      - name: data
        emptyDir: {}

- kibana-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: private.registry.com/vsf/kibana:latest
        env:
        - name: ELASTICSEARCH_URL
          value: '"http://vsf-elasticsearch:9200"'
        ports:
        - containerPort: 5601
      imagePullSecrets:
      - name: mykey 

- vue-storefront-api-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-storefront-api
spec:
  selector:
    matchLabels:
      app: vue-storefront-api
  template:
    metadata:
      labels:
        app: vue-storefront-api
    spec:
      containers:
      - name: vue-storefront-api
        image: private.registry.com/vsf/vuestorefrontapi_api:latest
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
        envFrom:
        - configMapRef:
            name: vue-storefront-api-config
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/www/config
          name: code
          subPath: config
        - mountPath: /var/www/migrations
          name: code
          subPath: migrations
          readOnly: true
        - mountPath: /var/www/package.json
          name: code
          subPath: package.json
          readOnly: true
        - mountPath: /var/www/scripts
          name: code
          subPath: scripts
          readOnly: true
        - mountPath: /var/www/src
          name: code
          subPath: src
          readOnly: true
        - mountPath: /var/www/var
          name: code
          subPath: var
          readOnly: true
        - mountPath: /var/www/dist
          name: dist
      imagePullSecrets:
      - name: mykey
      volumes:
      - name: code
        hostPath:
          path: "/root/vue-storefront-api"
          type: DirectoryOrCreate
      - name: dist
        emptyDir:
          medium: Memory

And the rest of the API services yaml files are same as here https://github.com/DivanteLtd/storefront-api/tree/master/kubernetes

**Comment by Fifciu** [comment]
Have you set up your `config` properly to also resolve `_ssr` requests proper way? I believe there might be different URLs for requests when they are being sent server-side. 

I had project like that in the past. We did not use K8s. However, I guess the solution might be similar. 

I prepared changes in the core to support different URL endpoints when they are dispatched from the server (not the client).  Please check this PR for details: https://github.com/DivanteLtd/vue-storefront/pull/3801

**Comment by dhouhamaa** [comment]
Update : 

the problem was that the files were not mounted properly to the pod.
After you deploy with the yaml files please double check from inside the pod if all necessary files for the app exists
