### ISSUE TITLE
Update documentation about multistore

### ISSUE THREAD

**Issue by Fifciu** [DivanteLtd/vue-storefront#4723]
This is our current doc about multistore: https://docs.vuestorefront.io/guide/integrations/multistore.html#multiwebsite-indexing

It is really old and needs strong update. This is what we should add in my opinion:

## Configure backend
- [x] Part `Multiwebsite indexing` should be marked as deprecated. It is really bad idea to use Node Indexer which sends so many requests to the backend when we have Bridge Indexers (e.g. Magento2 VSBridge Indexer). In my opinion, configuring multistore in the Backend should be the first step because the following ones will need that information.

## Configure PWA
In the current page, we have pasted example of config. I think we should put there some link to explanation which could be found here: https://docs.vuestorefront.io/guide/basics/configuration.html#store-views I am pretty sure there will be many people which won't find it without link.
  - [x] Below in global scope we have larger amount of attributes for `i18n` config. Can we set them per storeCode?:
```js
"i18n": {
    "defaultCountry": "US",
    "defaultLanguage": "EN",
    "availableLocale": [
      "en-US"
    ],
    "defaultLocale": "en-US",
    "currencyCode": "USD",
    "currencySign": "$",
    "currencyDecimal": "",
    "currencyGroup": "",
    "fractionDigits": 2,
    "priceFormat": "{sign}{amount}",
    "dateFormat": "HH:mm D/M/YYYY",
    "fullCountryName": "United States",
    "fullLanguageName": "English",
    "bundleAllStoreviewLanguages": false
  },
```
  - [x] Same for `tax`:
```js
"tax": {
    "defaultCountry": "US",
    "defaultRegion": "",
    "sourcePriceIncludesTax": false,
    "calculateServerSide": true,
    "userGroupId": null,
    "useOnlyDefaultUserGroupId": false,
    "deprecatedPriceFieldsSupport": true,
    "finalPriceIncludesTax": false
  },
```

## Configure VSF-API
- [x] What should I config in vsf-api for multistore? Detailed info about `storeId`, `websiteId` and `msi.stockId`. I am not sure if it wouldn't be too opinionated but it would be really nice to show Screenshots from M2 Dashboard where they could find these values.

## Developing PWA with Multistore
- [x] Part about using `currentStoreView` helper from `@vue-storefront/core/lib/multistore`. Search should be able to easily find a page about it. 
- [x] Same for part about `removeStoreCodeFromRoute` from the same file
- [x] Same for part about `adjustMultistoreApiUrl` from the same file
- [x] Same for part about `localizedRoute` from the same file
- [x] Same for part about `storeCodeFromRoute` from `@vue-storefront/core/lib/storeCodeFromRoute`

With that Multistore DX will grow.

## Developing VSF-API with Multistore
- [x] In `VSF-API/src/api/extensions/example-magento-api/index.js` we have example m2 extension. In my opinion, this example should also show how to create `Magento2Client` that supports *multistore* out-of-the-box. Check `src/platform/magento2/cart.js` for example case:
```js
this.api = Magento2Client(multiStoreConfig(config.magento2.api, req));
```

## Multistore limitations
- [x] List them and clearly describe whether we gonna to get rid of them or not. If so, we should point to the issue. So developers would have every detail and could take care of that

**Comment by janmyszkier** [comment]
I think it would be also nice to list current multistore limits (like the things where you cannot set different template per store) so people are aware what they cannot do with it (especially magento CAN and they will probably expect this is supported in vue). Then, add those limits to TODO and put on the roadmap as well.

**Comment by Fifciu** [comment]
@janmyszkier Very good idea. I added a bullet to the main post. Thanks!

**Comment by filrak** [comment]
Excellent idea! :)

@kkdg can you take it over?

**Comment by kkdg** [comment]
@filrak OK, let me fix this first
