### ISSUE TITLE
Card restore after login for configurable products

### ISSUE THREAD

**Issue by TTomas** [DivanteLtd/vue-storefront#4731]
## Current behavior

Yesterday I update from 1.11.4 to master v1.12.2 and notice this bug.
Login add some configurable product to card
Logout
Login, card is empty. For simple products card is OK.
Inspecting network request I notice after login /card/pull request return configurable sku: "WS05" and product_type:"configurable", previous versions return sku: "WS05-M-Orange" product_type":"configurable".
I inspect Add to card requests and notice /card/update request send sku: "WS05" and product_type:"configurable", previous versions send sku: "WS05-M-Orange", product_type:"configurable".
After login, after pull request client send product/_search with "terms":{"configurable_children.sku":["WS05"]} with empty result, search with bad sku, manual send same request with "terms":{"configurable_children.sku":["WS05-M-Orange"]} return correct product.
Bug is in wrong /card/update request with bad sku: "WS05", right sku: "WS05-M-Orange".

## Expected behavior

v1.11.4 and demo https://demo.storefrontcloud.io/ v1.12.1 is OK
Also https://test.storefrontcloud.io/ v1.12.2 2020-08-04 14:59:45 is OK card/update send sku: "WS05-M-Orange", "product_type":"configurable"

## Version of Vue Storefront

- [x ] Vue Storefront
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
Hi @TTomas it has been fixed with: https://github.com/DivanteLtd/vue-storefront/issues/4641 please check if it works for you?

**Comment by TTomas** [comment]
How to check? I have master version from yesterday. Comparing master with hotfix/1.12.2 and hotfix/1.12.3 are identical. Is something changed in protocol/data, I don't use vue-storefront-api as backend.

**Comment by TTomas** [comment]
Can you check card /update when add to card send correct sku
