### ISSUE TITLE
Add to card request

### ISSUE THREAD

**Issue by TTomas** [DivanteLtd/vue-storefront#4732]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [ x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	

This is connected to my bug report. Check to reopen again!
https://github.com/DivanteLtd/vue-storefront/issues/4731
I'm on yesterday master revision and notice change with previous versions when add product to card.
Main problem is in /card/update request when adding product to cart. Now I receive configurable product  parent sku in card, previous I receive simple child product sku for added product.
What is correct in future versions to prepare my backend  card and order system?

If this is not a bug, how to know products in order if user add several childs form same parent configurable product (white and black T-Shirt).

**Comment by TTomas** [comment]
I attach image, look at red rectangle. In Cart we have correct sku, but in /cart/update request we have parent sku

**Comment by TTomas** [comment]
![vsf-AddToCart](https://user-images.githubusercontent.com/689208/90115423-5fa71c00-dd54-11ea-972e-0da11d023247.jpg)

**Comment by TTomas** [comment]
![vsf-AddToCart2](https://user-images.githubusercontent.com/689208/90115918-10152000-dd55-11ea-8ffc-9fe564e8eca0.jpg)

**Comment by TTomas** [comment]
If someone have the same problem
I set config.cart.setConfigurableProductOptions: false and now I receive child sku in cart and cart is restored after login.
Need testing with setConfigurableProductOptions: true, pull return parent sku and next product search to restore cart is empty. product/_search is "terms":{"configurable_children.sku":["parent_sku"]}

**Comment by pkarw** [comment]
Thanks for the research! yes this option is exactly for this purpose
