### ISSUE TITLE
ElasticSearch indexes automatically deleted after sometime(index_not_found_exception)

### ISSUE THREAD

**Issue by kuldeepkiwitech** [DivanteLtd/vue-storefront#4737]
## Current behavior
We have migrated magento2 data using Mage2vs command but indexes get deleted automatically after 24-48 hrs from elastic search. 

  "code": 500,
  "result": {
    "root_cause": [
      {
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_or_alias",
        "resource.id": "vue_storefront_catalog",
        "index_uuid": "_na_",
        "index": "vue_storefront_catalog"
      }
    ],
    "type": "index_not_found_exception",
    "reason": "no such index",
    "resource.type": "index_or_alias",
    "resource.id": "vue_storefront_catalog",
    "index_uuid": "_na_",
    "index": "vue_storefront_catalog"
  }

## Expected behavior
Elastic index should persist.

## Steps to reproduce the issue
Setup new instance on google cloud and migrate data from magento2, elastic search index are deleted after 24-48 hrs without any deployment, elastic docker container still running but indexes are deleted for product, category and attributes. 

## Version of Vue Storefront
"version": "1.12.3"

## Can you handle fixing this bug by yourself?

No

## Environment details
- Browser: latest
- OS: Mac
- Node: 10.x
- Code Version: 1.12.3

## Additional information
We have to delete container again and migrate data then its working fir again its deleted after 24-48 hrs.

**Comment by elvinristi** [comment]
make sure your ElasticSearch is not accessible publicly or is behind password. 

you can check also what databases exist in Elastic and if you see there "meow" named ones then it might be bot removing those
- https://www.itnews.com.au/news/new-meow-bot-attacks-open-elasticsearch-instances-550735

**Comment by kuldeepkiwitech** [comment]
do you think this issue is because of virtual memory allocated to container?
