### ISSUE TITLE
support sylius or not?

### ISSUE THREAD

**Issue by benyang2015** [DivanteLtd/vue-storefront#476]

**Comment by pkarw** [comment]
Not yet! We do support Magento2 and Pimcore 4,5 as for now. You can take a look how integrator with Pimcore has been implemented: https://github.com/DivanteLtd/pimcore2vuestorefront

It will give you an idea how the integration with Sylius should work like/ We don't have resources to implement the integration with Sylius yet, so any support will be much appreciated!
