### ISSUE TITLE
Make GraphQL queries overrideable

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#4763]
## What is the motivation for adding / enhancing this feature?

Right now queries in Commercetools integration are setted in stone which is notably limiting benefits of using GraphQL in the project. Users should be able to modify the queries per composable.

## Proposed API

In the API Client (`packages/commercetools/api-client`) the custom GraphQL query (and query only) should be the last parameter of a function. If it's not provided we're using the default one (so the behavior remains unchanged). 

```js
getProduct({ params}, customQuery)
```

On the composables level we should make this behavior availalable through `search` and `load` functions. Also we won't implement that in all composables since some of them has to be refactored. Below is a list of new APIs in composables

- `useProduct`, `useCategory`
```js
search(params, customQuery)
```
- `useCart`, `useUser`, `useUserOrders`, `useUserAddresses`
```js
load(customQuery)
```
In that case `customQuery` has to be added to commercetools integration typings and to `factoryParams` in `core` using functions overloading (not all integrations has GraphQL so its not a typing that will appear on every integration). Feel free to suggest better approach (like inheritance)

## What are the acceptance criteria 

- [ ] All API Client queries are overrideable
- [ ] Listed Composables are allowing to override their API Client method queries
- [ ] TypeScript Interfaces are extended
- [ ] A document about extending queries is added to the composables

## Version of Vue Storefront

- [ ] Vue Storefront
- [x] Vue Storefront Next

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

**Comment by filrak** [comment]
New API allowing to override variables as well and have access to current query/variables

```js
search(params, (query, variables) => { query, variables }
```

**Comment by lukasborawski** [comment]
🎉
