### ISSUE TITLE
useReview factory

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#4775]
Create a Next factory function and typing for `useReview` composable with the following interface:

```js
const { reviews, search, loading, error } = useReview()
```

TODO
- types in `core` package
- factory in `core` package
- tests

**Comment by filipsobol** [comment]
PR linked above also includes following properties:

* `addReview` to submit new review,
* `totalReviews` and `averageRating` in case there are more reviews than we're able to fetch at once (pagination).
