### ISSUE TITLE
[Bug] There is no responsive version of compare page at all

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#480]
As for now the product blocks could be just aligned one under another using standard grid
![zrzut ekranu 2018-01-03 15 12 30](https://user-images.githubusercontent.com/211899/34523730-fae43a0a-f098-11e7-97a5-ff6ef3377a55.png)

**Comment by talalus** [comment]
I'm not sure I got the way you want it a quick sketch/design will be helpful.
I enabled horizontal overflow on mobile but I think it's ugly :D

**Comment by pkarw** [comment]
@talalus ok as for now just disable the feature on mobile - both adding to compare and icon to /compare page

OK?
