### ISSUE TITLE
Add compare icon to the header when at least one product is there

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#481]
![zrzut ekranu 2018-01-03 15 13 09](https://user-images.githubusercontent.com/211899/34523741-09fef318-f099-11e7-9e33-2913edc71dbf.png)

Doing so you can take a look at ui-store.js how it works with wishlist and others - to give you an idea how the isWishlist method should be implemented. It should have been using ui-store.js to check if there is wishlist enabled

**Comment by talalus** [comment]
@pkarw I used compare.js for the state
