### ISSUE TITLE
Reduce initial client-side bundle-size by lazy-loading `i18n` translations

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront#4813]
## What is the motivation for adding / enhancing this feature?

If you  are using a VSF shop with a lot of store-views, the `app.js` inside the bundle will automatically blow up because of the many different translation files it's possibly needs.

Its' caused by the dynamic import inside [`core/i18n/index.ts`](https://github.com/DivanteLtd/vue-storefront/blob/7ba4b91020f64333ef5f85c725edab7e63d1c9ec/core/i18n/index.ts#L52-L55). As a [dynamic expression import](https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import) is used, webpack needs to include all possible JSON files beneath the import path inside the bundle, to be able to load them later. If you have like 10 different languages, this leads to 9 unneeded, but loaded, language files and a package-size increase of around 500k+ (depending on the number of translations you are using) with a lot of initially unused code.
As we never know how much and which languages are needed at build-time this is a common way to approach but brings this flaw with it.

I've already tried to chunk the language includes (using webpack) to decrease the initial package-size of `app.js` but the unneeded languages will still be loaded in prefetch/preload requests and would still cause unused code.

I would suggest that we include an option to use `fetch` to load the languages (instead of `import`), this way users can reduce their package size and only load languages they actually need. I've already tested a solution where I copied the files using `CopyWebpackPlugin` and loaded them using `isomorphic-fetch` – these are problems and drawbacks to consider:
* We'd make two requests (on SSR and CSR) to fetch the JSON file – maybe they should be in state-management or a global to save this request when the language is already loaded.
* For SSR request we need an absolute URL to use the `fetch`, therefore you need another config variable including a base-path.

I could also imagine to use this issue to build some kind of translation handler to include your custom translation sources, like an CMS or custom API endpoint. This way we could achieve the above and add some flexibility.

What do you say about this? – any better Ideas?

**NOTE:** We are not using `bundleAllStoreviewLanguages` in this usecase ;)

## Version of Vue Storefront

- [x] Vue Storefront
- [ ] Vue Storefront Next

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by gibkigonzo** [comment]
you can split languages files by setting `bundleAllStoreviewLanguages` to false.
To remove unnecessary fetching in prefetch you can use this config
```
  "initialResources": [
    {
      "filters": ["lang-pl-PL"], // or use regexp to catch all `"filters": ["lang-.+"],`
      "onload": false
    }
  ],
```

**Comment by pkarw** [comment]
@gibkigonzo maybe we should put it as a default behavior how core is loading the langs (this rule will work even when `bundleAllStoreviewLanguages` is on because in that case the JS file with langs is named differently)

**Comment by cewald** [comment]
@gibkigonzo I didn't know about that feature and it didn't came across my mind to have a look at the renderer. Sorry :)

So, to make it work as is intended I first need to chunk the languages with:
```js
import { currentBuildLocales } from '@vue-storefront/i18n/helpers'

// ...

let localesCacheGroups = {}
currentBuildLocales().forEach(code => {
  const name = 'i18n-' + code
  localesCacheGroups[name] = {
    name,
    test: new RegExp(`core/i18n/resource/i18n/${code}\\.json`),
    chunks: 'all',
    priority: 3
  }
})

// ...

const config = merge(base, {
  optimization: {
    splitChunks: {
      cacheGroups: {
        commons: {
          // create 'vendor' group from initial packages from node_modules
          test: /node_modules/,
          name: 'vendor',
          chunks: 'initial',
          priority: 1
        },
        ...localesCacheGroups
      }
    },
    // ...
  },
  // ...
}
```

And then add the `initialResources` filter like:
```json
 "initialResources": [
    {
      "filters": ["i18n-.*", "lang-.+"],
      "type": "script",
      "onload": false,
      "rel": "preload"
    }
  ],
```

Right? – If so, it's not working, all `i18n-*` files are still loaded on CSR in parallel to `app.js`:

<img width="884" alt="Bildschirmfoto 2020-09-01 um 12 14 12" src="https://user-images.githubusercontent.com/6112764/91837800-cd0be580-ec4c-11ea-8353-6a400cbdf7ee.png">

**Comment by gibkigonzo** [comment]
You shouldn't add it as chunk. If `i18n-x.js`  files are lazy loaded then by default vue-renderer will add those files to prefetch/preload list (https://ssr.vuejs.org/api/#shouldpreload). `initialResources` just takes control over this behavior and removes specified files from prefetch/preload list. For example we make lazy load for `dayjs-locales` files https://github.com/DivanteLtd/vue-storefront/blob/master/core/i18n/index.ts#L32. But those files still will be loaded as prefetch, even if they are not used. So we can add:
```
    {
      "filters": ["dayjs-locales-.*"],
      "onload": false
    }
```
and to test it you can add `de-DE` in basic vsf project
```
    "availableLocale": [
      "en-US",
      "de-DE"
    ],
```

**Comment by cewald** [comment]
Thanks for your help. It works in your example, but what I don't get is: if I don't chunk the languages JSON imports, these will be bundled inside the `app.js` and therefore can't be lazy-loaded (and increase the package-size) – that is why I assumed that I need to split them first. Do you know what I mean?
The language files are (when chunked) included and loaded immediately with the `app.js` (at the bottom of the page) and not prefetched like the `dayjs` parts (in the header), despite they are imported the same way. Are they probably handled different because they are JSON files?

**Comment by cewald** [comment]
Found it: in the `VueI18n()` constructor is an [dynamic-expression-require](https://github.com/DivanteLtd/vue-storefront/blob/master/core/i18n/index.ts#L16-L17) for the `i18n/resources/i18n/*` folder too. This caused it to be always and initially loaded. If I change this line into a static require with a specific language it works and only the needed languages are lazy-loaded.

**Comment by gibkigonzo** [comment]
Yes, I see now where is the problem. Languages files are in one bundle and they should be splitted :thinking: I can't find other solution right now, then get back to static i18n fallback

**Comment by cewald** [comment]
We could build a default language-file using a dynamic variable in the language-preprocessor and name it always the same, like `default.json` and then just require this file instead of `{locale}.json` in the application code. Wdym?

**Comment by gibkigonzo** [comment]
good idea :)
todo:
- create `default.json` https://github.com/DivanteLtd/vue-storefront/blob/master/core/i18n/scripts/translation.preprocessor.js#L46
- prevent duplication if for example `default.json` will be same as `en-US.json`
- use `default.json` as fallback https://github.com/DivanteLtd/vue-storefront/blob/master/core/i18n/index.ts#L17
- check if `lang` is same as default then load default one https://github.com/DivanteLtd/vue-storefront/blob/master/core/i18n/index.ts#L52

**Comment by cewald** [comment]
Cool, I've already tried it and it worked – I'll open an PR for it.

**Comment by cewald** [comment]
I've opened up a PR: #4821
