### ISSUE TITLE
Add links to products within Wihslist sidebar

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#482]
![zrzut ekranu 2018-01-03 15 13 54](https://user-images.githubusercontent.com/211899/34523873-9822e0f0-f099-11e7-87e2-ec7671a2de31.png)

**Comment by szafran89** [comment]
Hi @pkarw First of all congrats for current state of this project. I would like to contribute from time to time. If possible I can handle this issue.

**Comment by pkarw** [comment]
@szafran89 - thanks for the feedback! We're doing our best here :)

Would be great to have your support, so don't hesitate to pick up this task and maybe even some others from Issues? In case of any problems just ask on Slack

**Comment by szafran89** [comment]
It's done.  
I'll do best to handle more issues or create some new.

**Comment by pkarw** [comment]
Congratulations @szafran89 it's already merged in! :) Don't hesitate to take care of some new issues like: https://github.com/DivanteLtd/vue-storefront/issues/488
