### ISSUE TITLE
Not able to extend core modules

### ISSUE THREAD

**Issue by Kannas24** [DivanteLtd/vue-storefront#4835]
I'm specifically trying to override the category/list action in category module.

I've a requirement where I need to generate multiple urls for single category (ex. {baseUrl/category1/filter1 , baseUrl/category1/filter2 ....} fo that I want to override list action of category module. I've tried almost everything mentioned over the vuestorefront website to do that, seems like there's no way now to override the core modules as we are registering them already on core.

Outdate documentation : https://docs.vuestorefront.io/guide/modules/introduction.html#extending-and-overriding-vue-storefront-modules

Forum link  - https://forum.vuestorefront.io/t/vsf-module-extending-in-1-11-1/1343/6

Forum link - https://forum.vuestorefront.io/t/extend-user-module/494

**Comment by gibkigonzo** [comment]
Hey, here is example how you can do that by creating vsf module

```
import { extendStore } from '@vue-storefront/core/helpers'

const exampleNameModule = {
  actions: {
    async list ({ dispatch }, { url, params }) {
      // ...
    }
  }
}

export const ExampleName: StorefrontModule = function ({app, store, router, moduleConfig, appConfig}) {
  extendStore('url', exampleNameModule)
}
```

**Comment by Kannas24** [comment]
> Hey, here is example how you can do that by creating vsf module
> 
> ```
> import { extendStore } from '@vue-storefront/core/helpers'
> 
> const exampleNameModule = {
>   actions: {
>     async list ({ dispatch }, { url, params }) {
>       // ...
>     }
>   }
> }
> 
> export const ExampleName: StorefrontModule = function ({app, store, router, moduleConfig, appConfig}) {
>   extendStore('url', exampleNameModule)
> }
> ```

Yes, this is what I did inside my theme folder, seems like it requires pre-existing store to extend it but I want to do extend it before even registering it.
Thanks 👍
