### ISSUE TITLE
Implement useUserShipping mock and designs

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#4841]
## What is the motivation for adding / enhancing this feature?

implement `useUserShipping` composable in
- user profile
- checkout

and mock it in CT integration and boilerplate.

https://www.figma.com/file/N0Ct95cSAoODNv7zYS01ng/Storefront-UI-%7C-Design-System?node-id=4472%3A10822
![image](https://user-images.githubusercontent.com/15185752/92464896-1a003680-f1ce-11ea-90c0-18444ebf38df.png)

The important part here is how "ADD NEW ADDRESS" button should work.

There should be a mocked list of addresses that we can push to by selecting "add new address" but it shouldn't be connected to CT (so it disappears on refresh). This way we will keep the data mocked and happy path working

## What are the acceptance criteria 

- [x] useUserShipping mock for logged in user is applied in checkout for CT and boilerplate
- [x] useUserShipping mock for logged in user is applied in user profile for CT and boilerplate
- [x] new designs are applied for checkout
- [x] we can place an order with mocked (or added address)

## Version of Vue Storefront

- [ ] Vue Storefront
- [x] Vue Storefront Next

**Comment by andrzejewsky** [comment]
Core interfacec related to shipping

```
export interface UseUserShipping<ADDRESS> {
  addresses: ComputedProperty<ADDRESS[]>;
  addAddress: (address: ADDRESS) => Promise<void>;
  deleteAddress: (address: ADDRESS) => Promise<void>;
  updateAddress: (address: ADDRESS) => Promise<void>;
  load: () => Promise<void>;
  setDefault: (address: ADDRESS) => Promise<void>;
  loading: ComputedProperty<boolean>;
}
export interface UserShippingGetters<ADDRESS> {
  getFiltered: (addresses: ADDRESS[], criteria: any) => ADDRESS[];
  getDefault: (addresses: ADDRESS[]) => ADDRESS;
  getTotal: (addresses: ADDRESS[]) => number;
  getPostCode: (address: ADDRESS) => string;
  getStreetName: (address: ADDRESS) => string;
  getCity: (address: ADDRESS) => string;
  getFirstName: (address: ADDRESS) => string;
  getLastName: (address: ADDRESS) => string;
  getCountry: (address: ADDRESS) => string;
  getStreetNumber: (address: ADDRESS) => string;
  getPhone: (address: ADDRESS) => string;
  getEmail: (address: ADDRESS) => string;
  getState: (address: ADDRESS) => string;
}
```

**Comment by Fifciu** [comment]
Gonna change `getState` to `getProvince`
