### ISSUE TITLE
Implement useUserBilling mock and designs

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#4842]
## What is the motivation for adding / enhancing this feature?

implement `useUserBilling` composable in
- user profile
- checkout

and mock it in CT integration and boilerplate.

https://www.figma.com/file/N0Ct95cSAoODNv7zYS01ng/Storefront-UI-%7C-Design-System?node-id=4472%3A10822

The important part here is how "ADD NEW ADDRESS" button should work.

There should be a mocked list of addresses that we can push to by selecting "add new address" but it shouldn't be connected to CT. This way we will keep the data mocked and happy path working

## What are the acceptance criteria 

- [ ] useUserBilling mock for logged in user is applied in checkout in CT and boilerplate
- [ ] useUserBilling mock for logged in user is applied in user profile in CT and boilerplate
- [ ] new designs are applied for checkout

## Version of Vue Storefront

- [ ] Vue Storefront
- [x] Vue Storefront Next

**Comment by Fifciu** [comment]
Proposed interfaces:
```ts
export interface UseUserBilling<ADDRESS> {
  addresses: ComputedProperty<ADDRESS[]>;
  addAddress: (address: ADDRESS) => Promise<void>;
  deleteAddress: (address: ADDRESS) => Promise<void>;
  updateAddress: (address: ADDRESS) => Promise<void>;
  load: () => Promise<void>;
  setDefault: (address: ADDRESS) => Promise<void>;
  loading: ComputedProperty<boolean>;
}

export interface UserBillingGetters<ADDRESS> {
  getFiltered: (addresses: ADDRESS[], criteria: any) => ADDRESS[];
  getDefault: (addresses: ADDRESS[]) => ADDRESS;
  getTotal: (addresses: ADDRESS[]) => number;
  getPostCode: (address: ADDRESS) => string;
  getStreetName: (address: ADDRESS) => string;
  getCity: (address: ADDRESS) => string;
  getFirstName: (address: ADDRESS) => string;
  getLastName: (address: ADDRESS) => string;
  getCountry: (address: ADDRESS) => string;
  getStreetNumber: (address: ADDRESS) => string;
  getPhone: (address: ADDRESS) => string;
  getEmail: (address: ADDRESS) => string;
  getProvince: (address: ADDRESS) => string;
  getCompanyName: (address: ADDRESS) => string;
  getTaxIdentificationNumber: (address: ADDRESS) => string;
}
```

**Comment by andrzejewsky** [comment]
I'm still wondering.... What if we have some other data in the response?  why dot this composable returns an array instead of an object. You actually don't know, how platform's billing looks like - maybe we'll need to read something from the pure response?. Look at the  following getters and types, we still have an access to whole billing object - so we  can introduce even more getters in the future if they are needed, we can read the billing addresses items by using getFiltered (later billing.items with agnostic types, getter evaluation here), we do the transformation only in the getters (reason why they are created for). As the  reference look at the composables and  getters  in the cart, wishlist, product, categories and so on - similar approach, why this one is different?

```
export interface UseUserBilling<USER_BILLING, USER_BILLING_ITEM> {
  billing: ComputedProperty<USER_BILLING>;
  addAddress: (address: USER_BILLING_ITEM) => Promise<void>;
  deleteAddress: (address: USER_BILLING_ITEM) => Promise<void>;
  updateAddress: (address: USER_BILLING_ITEM) => Promise<void>;
  load: () => Promise<void>;
  setDefault: (address: USER_BILLING_ITEM) => Promise<void>;
  loading: ComputedProperty<boolean>;
}
export interface UserBillingGetters<USER_BILLING, USER_BILLING_ITEM> {
  getFiltered: (addresses:USER_BILLING, criteria: any) => USER_BILLING_ITEM[];
  getDefault: (addresses: USER_BILLING) => USER_BILLING_ITEM;
  getTotal: (addresses: USER_BILLING) => number;
  getPostCode: (address: USER_BILLING_ITEM) => string;
  getStreetName: (address: USER_BILLING_ITEM) => string;
  getCity: (address: USER_BILLING_ITEM) => string;
  getFirstName: (address: USER_BILLING_ITEM) => string;
  getLastName: (address: USER_BILLING_ITEM) => string;
  getCountry: (address: USER_BILLING_ITEM) => string;
  getStreetNumber: (address: USER_BILLING_ITEM) => string;
  getPhone: (address: USER_BILLING_ITEM) => string;
  getEmail: (address: ADDREUSER_BILLING_ITEMS) => string;
  getProvince: (address: ADDRUSER_BILLING_ITEMSS) => string;
  getCompanyName: (address: USER_BILLING_ITEM) => string;
  getTaxIdentificationNumber: (address: USER_BILLING_ITEM) => string;
}
```
