### ISSUE TITLE
Adjustments of the sidebar cart on mobile

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#486]
Apply adjustments and improvements to make the view closer to the design ("Sidebar cart on mobile" in https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront-Open-Source).

The comparison, left - current stage, right - the design.
![2](https://user-images.githubusercontent.com/18116406/34533689-9ee06512-f0bb-11e7-81c3-c8363b8608ac.png)

The most important adjustments:
- Changes of the positions of header and close button;
- Adjustments in sizes and colors of fonts;
- Add gray background to the product's photo;
- Adjustments in margins and paddings;
- Bigger button "Go to checkout";
- Remove labels "edit" and "remove" of the products, leaving just icons.

The most important improvements (nice to have):
- Add link "return to shopping" below "go to checkout" button;
- Add animation while removing the product from the cart, eg. 0% to 100% of transparency of the row.

Some adjustments may be related to https://github.com/DivanteLtd/vue-storefront/issues/456.

**Comment by szafran89** [comment]
I'll handle this one.

**Comment by pkarw** [comment]
@szafran89 cool! Please accept the invitation to the Github team that I can assign this issue to you; in the meantime - would you be able to fix this task before 22.01? Because it's a release date of 0.40

**Comment by szafran89** [comment]
Yes, sure. I'll do that.

**Comment by pkarw** [comment]
486DX my first Computer ❤️

**Comment by szafran89** [comment]
I've done all points from issue and additionally I've noticed and fixed a few other points related with this component:
- changed classes/styles for desktop to fit design from figma,
- added tag button for close action, IMO we should follow this approach for all clickable elements (a11y), 
- on design there is `#BDBDBD` color for SKU, I changed it to `#8E8E8E` to achieve better contrast ratio (https://webaim.org/resources/contrastchecker/) It's also faild but looks better. We should ask graphic designer about changes on design (a11y),
- cleaned a little HTML code,
- set formatting for HTML code (one tag per line, if line length > 80 set one attribute per line). What do you think about this?

Below I attached screens of desktop/mobile microcart.
![screenshot at sty 18 21-09-12](https://user-images.githubusercontent.com/5370251/35118986-e8fb0aec-fc93-11e7-8d5c-f0e2f378bc65.png)
![screenshot at sty 18 21-07-20](https://user-images.githubusercontent.com/5370251/35118991-eb9763d6-fc93-11e7-9af4-aaa6da66e93d.png)
![screenshot at sty 18 21-06-15](https://user-images.githubusercontent.com/5370251/35119032-fd97139c-fc93-11e7-8927-d85a6a8a6ad8.png)

**Comment by szafran89** [comment]
Sorry I again accidentally closed issue :D

**Comment by pkarw** [comment]
@szafran89 great job! I've just tested it locally and merged in
