### ISSUE TITLE
Adjustments of the product card on mobile

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#488]
The set of adjustments and improvements to make the product card look better on mobile ("Product cart on mobile" in https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront-Open-Source).

The comparison, left - current stage, right - the design.
![4](https://user-images.githubusercontent.com/18116406/34535740-2b340468-f0c3-11e7-86b6-09b9dd8602db.png)

The most important adjustments:

- [x] 1. Adjustments in sizes and colors of fonts;
- [x] 2. Adjustments for the background colors (add a white color of the background of the product description);
- [x] 3. Adjustments in margins and paddings;
- [x] 4. Add changes in top (except the logo) and footer;
- [x] 5. Adjustments in product boxes (colors, fonts, sizes, margins, paddings, mouseover effect, adjustments like on the category page, listed here https://github.com/DivanteLtd/vue-storefront/issues/485).

The most important improvements (nice to have):
- [ ] 1. Add return arrow in the top (instead of the hamburger menu button);
- [x] 2. Add the gradient cover over description (after clicking the description, the full description should be presented); 
- [x] 3. Add the slider of the product (similar to the homepage) in "Perfect match" section;
- [x] 4. Add the banner to the featured section - in the project, I put "Sales Eco-friendly" banner;
- [x] 5. Add social media buttons in the footer;
- [x] 6. Add slider for the photos of the product;
- [x] 7. Add SKU (above the name of the product).

Some adjustments may be related to https://github.com/DivanteLtd/vue-storefront/issues/456.

**Comment by pkarw** [comment]
ad 3. The slider works just fine on destkop but on the mobile looks like "downscaled" :) @szafran89 
<img width="563" alt="zrzut ekranu 2018-01-22 17 56 11" src="https://user-images.githubusercontent.com/211899/35233327-1e52b976-ff9e-11e7-9fc1-3388e5c3c619.png">


Sometimes the slider doens't load the product boxes at all .. it's pretty crappy and we should exchange it to some other solution

**Comment by mercs600** [comment]
@szafran89 it's true, vue-carousel its a pretty buggy. On the other hand vue-swiper need swiper js as dependency which is a bit heavy > 100 kb. On the other hand it's hard to find a good vue alternative without external dependencies ;-( . https://github.com/lukaszflorczak/vue-agile promising, but not good for production..

**Comment by pkarw** [comment]
Maybe Just remove the carousel until we found
Better implementation? Would be important
To keep the current layout and that’s all :)

What do you think?

**Comment by pkarw** [comment]
I mean the same layout as for similar products - like on Figma designs

**Comment by szafran89** [comment]
Yes @mercs600 I checked it out and you're right. `vue-swiper` isn't good idea as well.
IMO we can temporary remove carousel and keep `similar products` layout to have time to think it over.

**Comment by pkarw** [comment]
Let’s do it

**Comment by pkarw** [comment]
Could you take care of this @mercs600 / @szafran89?

The release is next week, 29th

**Comment by szafran89** [comment]
I think I'll do it. I'll keep you up-to-date about status.

**Comment by szafran89** [comment]
@pkarw What about below issues:
- `Add changes in top (except the logo) and footer;` Is it still to do or it was handled before?
- `Add return arrow in the top (instead of the hamburger menu button);` What is a purpose of this? Should I change only icon or logic (return to previous page) as well?

**Comment by szafran89** [comment]
Issues related with slider moved to #590

**Comment by pkarw** [comment]
@szafran89  here you have the answers:
- changes in the top - done by fixes to other issues
- return arrow - it may have sense as a history.back(-1) - doesn't make sense to just change the icon of course

**Comment by pkarw** [comment]
@szafran89 you can move the issue with arrow to separate ticket and close this one as well

**Comment by szafran89** [comment]
Done.
