### ISSUE TITLE
RFC: Multichannel support in Checkout.com

### ISSUE THREAD

**Issue by Fifciu** [DivanteLtd/vue-storefront#4885]
I have to implement support for multichannels in Next's CKO integration. Developers will be able to pick up channel. That's why they will have to use some `setChannel` method in proper moment in their app.

The current shape of the config:
```ts
interface Configuration {
  publicKey: string;
  ckoWebHookUrl?: string;
  ctApiUrl?: string;
  tokenizedCardKey?: string;
  saveInstrumentKey?: string;
  card?: CardConfiguration;
}
```

The proposed shape of the new config:
```ts
interface MultichannelConfiguration {
  channels: Record<string, Configuration>,
  defaultChannel: string;
}
```

I would export function called `setChannel` which would take one argument - `channelKey: string`. It would be something like:
```ts
if (!compareObjects(currentConfig, configs[providedChannelKey])
  currentConfig = configs[providedChannelKey];
```
Ofc, with some fallback to previous value if someone tries to use a non existing channel.
The function will be exported in index.ts so we should be able to import it with:
```ts
import { setChannel } from '@vue-storefront/checkout-com';
```

What do you think about this approach?

**Comment by andrzejewsky** [comment]
I think it's another function in useCko composable that allows you to change channel, @Fifciu is there any concern why that's a bad idea? The composables shouldn't know about where parameters (URL etc.)  comes from, you provide this from the app
