### ISSUE TITLE
Add support for Prestashop

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#489]
Some details how it can be achieved: https://medium.com/@piotrkarwatka/how-to-connect-3rd-party-platform-to-vue-storefront-df9cb30779f6

**Comment by hiousi** [comment]
is there some sites using vuestorefront in front of Prestashop? did someone made a bridge?

**Comment by pmaojo** [comment]
@pkarw  
Would this be a good issue for the next hackaton?

**Comment by pkarw** [comment]
Not sure about It it doesn’t sound like something you can code within one day :)

**Comment by pkarw** [comment]
Check this out: https://github.com/jankawulok/tb2vuestorefront

**Comment by pmaojo** [comment]
@pkarw I don't think its a one day coding challenge 🗡 
 unless its a big team..
