### ISSUE TITLE
Add support for Sylius

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#490]
https://medium.com/@piotrkarwatka/how-to-connect-3rd-party-platform-to-vue-storefront-df9cb30779f6

**Comment by benyang2015** [comment]
@pkarw can't open the url https://medium.com/@piotrkarwatka/how-to-connect-3rd-party-platform-to-vue-storefront-df9cb30779f6

**Comment by pkarw** [comment]
@benyang2015 strange, for me it works just fine. But nevertheless - here you have the PDF copy
[How_to_connect_3rd_party.pdf](https://github.com/DivanteLtd/vue-storefront/files/1605850/How_to_connect_3rd_party.pdf)

**Comment by filrak** [comment]
Done https://github.com/BitBagCommerce/SyliusVueStorefrontPlugin
