### ISSUE TITLE
Some commercetools getters return 'Cannot read value of undefined'.

### ISSUE THREAD

**Issue by krskibin** [DivanteLtd/vue-storefront#4907]
## Current behavior

Some CT getters return 'Cannot read value of undefined' when reactive values are not present and it causes whole page error.
Methods like `getProductDescription` are not checking if params exist so they throw the error.
```js
export const getProductDescription = (product: ProductVariant): any => (product as any)._description;
```
It would be better to make sure if the value exists and return temporary value if not (like in `getProductName`)
```js
export const getProductName = (product: ProductVariant | Readonly<ProductVariant>): string => product ? (product as any)._name : '';
```
So the function implementation should look like this:
```js
export const getProductDescription = (product: ProductVariant | Readonly<ProductVariant>): string => product ? (product as any)._description : '';
```
## Expected behavior

All getters should handle undefined params and returns default value if that value not exists.

## Version of Vue Storefront

- [ ] Vue Storefront
- [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

all

**Comment by filipsobol** [comment]
Fix is merged and will be available in the next release.
