### ISSUE TITLE
Adding Google Analytics feature

### ISSUE THREAD

**Issue by hafeez3000** [DivanteLtd/vue-storefront#494]
Hi, is something possible to use plugin https://github.com/MatteoGabriele/vue-analytics for implementing Google Analytics?

I found documentation here https://matteogabriele.gitbooks.io/vue-analytics/content/

**Comment by pkarw** [comment]
Seems like a pretty straightforward solution and we should implement it! Thanks @hafeez300!
Are you willing to try to make it work?

**Comment by pkarw** [comment]
@hafeez3000 how are things in here?

**Comment by pkarw** [comment]
@hafeez3000 how are things?

**Comment by pkarw** [comment]
@hafeez3000 how about the improvements to this one?
