### ISSUE TITLE
Front-end can't fetch categories: Unknown error with API catalog result in resultProcessor for entity type 'category'

### ISSUE THREAD

**Issue by ArjanStudent** [DivanteLtd/vue-storefront#4945]
I'm getting following error consistently for a few days now when restarting the project:
``Unknown error with API catalog result in resultProcessor for entity type 'category'``
Things that I have tried to solve:
- ``yarn db rebuild ``
- ``node node_modules/mage2vuestorefront/src/cli.js categories``
- ``reinstalling the whole project with yarn installer``
The api and elasticsearch instance are both running. The product data is in elasticsearch and is displayed on the front-end vue-storefront project ( so it's only the categories he can't reach for some odd reason ).
I am having this issue with the capybara theme. One thing that I experienced was when I go through ``yarn installer``  and pick the default theme, then afterwards install capybara through ``vsf init:theme`` I do not get this error. The error comes back however when I restart the api containers.

**Comment by ArjanStudent** [comment]
Using https://app.elasticvue.com/search I am able to connect to be my elasticsearch and I do find a index with type category. This is filled with the data of all my categories, not sure why the api is not fetching it?

**Comment by ArjanStudent** [comment]
Using following request : http://localhost:9200/vue_storefront_catalog/category/_search I am able to fetch the categories aswell so it seems to be somehow front-end related?

**Comment by ArjanStudent** [comment]
Update: running the api outside of docker with yarn dev does NOT result in me getting this error so it has to do something with the docker environment.

**Comment by Fifciu** [comment]
Let's assume you are using docker for whole vsf-api. I have a few questions:
1. What is your OS?
2. By what URL you are trying to reach `category` index via VSF-API? Please put certain URL here
3. Have you tried to browse it with Kibana? Are you 100% sure records are inside ES? Could you please put here a screenshot?

**Comment by ArjanStudent** [comment]
I am working on Linux ( Fedora OS ).
I have not changed any URLs, it should all still be default config except for the magento2 authentication settings. ````api/catalog/vue_storefront_catalog/category/_search?_source_exclude=sgn&_source_include=children_count%2Cid%2Cis_active%2Clevel%2Cname%2Cparent_id%2Cpath%2Cposition%2Cproduct_count%2Csku%2Curl_key%2Curl_path%2C%2A.children_data.id%2C%2A.id&from=0&request=%7B%22_availableFilters%22%3A%5B%5D%2C%22_appliedFilters%22%3A%5B%7B%22attribute%22%3A%22is_active%22%2C%22value%22%3A%7B%22eq%22%3Atrue%7D%2C%22scope%22%3A%22default%22%7D%5D%2C%22_appliedSort%22%3A%5B%7B%22field%22%3A%22position%22%2C%22options%22%3A%22asc%22%7D%5D%2C%22_searchText%22%3A%22%22%7D&request_format=search-query&response_format=compact&size=4000````
to get categories.

Everything works when I run both the front-end & the api ( 8080 ) locally with yarn dev. The elasticsearch etc. are still running through docker.
I used a chrome application to search through my elasticsearch and i found a category type containing all my categories.

It all works now but I'm not able to run them in a docker environment.

**Comment by gibkigonzo** [comment]
if this  work `http://localhost:9200/vue_storefront_catalog/category/_search` then check if your categories have `is_active` set to `true`

**Comment by ArjanStudent** [comment]
Yes they are set to true. Other people are having the same issue with docker aswell, there is a thread about it in the vue storefront Slack : https://vuestorefront.slack.com/archives/CA68P1JUF/p1601369162097900 .

**Comment by gibkigonzo** [comment]
related: https://github.com/DivanteLtd/vue-storefront/pull/4951 https://github.com/DivanteLtd/vue-storefront/issues/4969

**Comment by gibkigonzo** [comment]
fixed by https://github.com/DivanteLtd/vue-storefront/pull/4951
