### ISSUE TITLE
Type errors in Url module

### ISSUE THREAD

**Issue by zAPFy** [DivanteLtd/vue-storefront#4957]
## Current behavior
When running `yarn generate` I get theese type errors and the command fails

```
core/modules/url/helpers/index.ts:7:26 - error TS2307: Cannot find module 'core/modules/catalog-next/types/Category'.

7 import { Category } from 'core/modules/catalog-next/types/Category'
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core/modules/url/helpers/index.ts:34:39 - error TS2554: Expected 1 arguments, but got 2.

34     router.addRoutes([preparedRoute], true)
                                         ~~~~
core/modules/url/helpers/index.ts:48:38 - error TS2554: Expected 1 arguments, but got 2.

48     router.addRoutes(preparedRoutes, true)
```

## Expected behavior
No type errors

## Steps to reproduce the issue
yarn generate

## Version of Vue Storefront
1.12.2
- [ x] Vue Storefront
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: null
- OS: Ubuntu
- Node: 10.18.1
- Code Version: 1.12.2

## Additional information
I'm guessing the import should use `@vue-storefront`

core/modules/url/helpers/index.ts
```
import { Category } from '@vue-storefront/core/modules/catalog-next/types/Category'

```

the other two I have not looked into

**Comment by gibkigonzo** [comment]
duplicate https://github.com/DivanteLtd/vue-storefront/issues/4532
