### ISSUE TITLE
Checkout ERR_STREAM_WRITE_AFTER_END

### ISSUE THREAD

**Issue by andrey-pomaz** [DivanteLtd/vue-storefront#4965]
## Current behavior

App fails after the refresh checkout page https://i.imgur.com/1DyJUbO.png 

## Expected behavior

The page should refresh successfully

## Steps to reproduce the issue
Press F5 on the checkout page at dev mode

## Version of Vue Storefront
- [ 1.12.2] Vue Storefront
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ x] NO

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome
- OS: Ubuntu 20.04
- Node: 14.3.0
-

**Comment by Fifciu** [comment]
There is already an issue for that: https://github.com/DivanteLtd/vue-storefront/issues/4647
@gibkigonzo almost finished fix for that: https://github.com/DivanteLtd/vue-storefront/pull/4937
