### ISSUE TITLE
An unexpected error occurred: "EEXIST: file already exists, symlink '../../../../core/nuxt-theme-module'

### ISSUE THREAD

**Issue by markbrocato** [DivanteLtd/vue-storefront#4985]
## Current behavior
Adding any package to packages/commercetools/theme and running yarn install yields this error:

```
error An unexpected error occurred: "EEXIST: file already exists, symlink '../../../../core/nuxt-theme-module' -> '/Users/markbrocato/Code/vue-storefront/packages/commercetools/theme/node_modules/@vue-storefront/nuxt-theme'"
```

## Expected behavior
Yarn install should finish without error

## Steps to reproduce the issue

```
clone the repo and checkout the next branch
yarn
yarn build:core
yarn build:prismic
yarn build:ct:tools
cd packages/commercetools/theme
yarn add <any package>
-- error occurs here --
```

## Version of Vue Storefront

- [ ] Vue Storefront
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: N/A
- OS: Mac OS
- Node: Node 12
- Code Version: next

**Comment by filipsobol** [comment]
This will be fixed once https://github.com/DivanteLtd/vue-storefront/pull/4971 is merged.

Unfortunately, until then, you have to manually add new dependency to `package.json`, run `lerna clean` in the root of the project and install all dependecies again.

**Comment by filipsobol** [comment]
Fix has been merged.
