### ISSUE TITLE
Syntax Error: Unexpected token: return product.price ? .discounted

### ISSUE THREAD

**Issue by markbrocato** [DivanteLtd/vue-storefront#4986]
## Current behavior
In the next branch, running yarn dev:ct yields a bunch of errors like:

```
Syntax Error: Unexpected token (55:62)                                                                                             friendly-errors 12:16:17

  53 | };
  54 | var getPrice = function (price) { return price ? price.value.centAmount / 100 : null; };
> 55 | var getDiscount = function (product) { return product.price ? .discounted : ; };
     |                                                               ^
  56 | var getSpecialPrice = function (product) {
  57 |     var discount = getDiscount(product);
  58 |     if (product.__typename === 'LineItem') {

                                                                                                                                   friendly-errors 12:16:17
 @ ../composables/src/getters/cartGetters.ts 3:0-58 19:9-20 58:9-26
 @ ../composables/src/getters/index.ts
 @ ../composables/src/index.ts
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./_theme/pages/Checkout.vue?vue&type=script&lang=js&
 @ ./_theme/pages/Checkout.vue?vue&type=script&lang=js&
 @ ./_theme/pages/Checkout.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
```

## Expected behavior
The app should start without error

## Steps to reproduce the issue
- clone the repo and checkout the next branch
- yarn
- yarn build:core
- yarn build:prismic
- yarn build:ct:tools
- yarn dev:ct

## Version of Vue Storefront

- [ ] Vue Storefront
- [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: N/A
- OS: Mac OS
- Node: 12
- Code Version: next

**Comment by filipsobol** [comment]
It looks like [an issue fixed about a week ago](https://github.com/DivanteLtd/vue-storefront/pull/4949). Can you confirm you are using latest version?

`tsconfig.json` in the theme you try to use should have property `compilerOptions > target` set to `es2018`.
