### ISSUE TITLE
Attribute dictionaries + filtering per category

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#5]
To have properly worked faceted search in the categories we should synchronize the Attribute dictionaries, not only the product itself. We should have filter-attributes stored per category to properly build the filters. At MVP it would be even hard-coded and limited to "color" and "size" as it's for fashion.

**Comment by pkarw** [comment]
It's related to https://github.com/DivanteLtd/vue-storefront/pull/37/files

As for now the attributes dictionary will be build by migration and statically filed with example values

**Comment by pkarw** [comment]
We have to map EAV: http://devdocs.magento.com/guides/m1x/magefordev/mage-for-dev-7.html

**Comment by pkarw** [comment]
... but the whole entity definition can be in one JSON object.
To remember: store these defintion in some additional vue store and synchronize with database. Also with distinction per category!

**Comment by pkarw** [comment]
Attributes must be stored by attribute code and THEN attached per type of entity

**Comment by pkarw** [comment]
Work in progress. Attribute sync added to mage2nosql; vue-storefront-api: migrations to change particular field types in progress (populating dictionaries for color and size right now); vue-storefront: vuex stores in progress

**Comment by pkarw** [comment]
@patrykpiston please let me know when you made the filters clickable - then I'll bind the filterling logick and we can close this one

**Comment by patrykpiston** [comment]
@pkarw Ok, I'll do it after my fixes and set a PR then

**Comment by patrykpiston** [comment]
@pkarw I just posted a PR #87
