### ISSUE TITLE
[BUG] Horizontal scroll on mobile shows empty space

### ISSUE THREAD

**Issue by rossmc** [DivanteLtd/vue-storefront#500]
On mobile if the user scrolls/swipes right they will see an empty space to the right of the content.  This is very obvious on the main slider or a main product image but occurs everywhere.

![horizontal-scroll-issue2](https://user-images.githubusercontent.com/2452991/34764946-ee159e96-f5e7-11e7-8dc4-bbc99415ab46.jpg)

We can fix this by adding the following CSS
```
html, 
body {
    overflow-x: hidden;
}
```

I suggest we create a new file to add this global css to, e.g. `src/themes/default/css/layout.scss`.  Although the [documentation](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Working%20with%20stylesheets%20(CSS).md#extending-scss-files) says we should not create any new files in this directory?

**Comment by pkarw** [comment]
@rossmc good point; please proceed

**Comment by filrak** [comment]
@rossmc Good idea, feel free to fix it! The styles modifying `body` element are in `App.vue`. now but it's a good idea to move them to some external file like `layout.scss` you mentioned ;)

**Comment by pakiam** [comment]
@rossmc very bad practice, cuz its a hack. 
Problem is more deep. In grid.

**Comment by rossmc** [comment]
@pakiam really? Any specific case where it would stand out as bad practice?

I like it as it's very clear in what it's doing and see where it's coming from. Can't think of many cases where you'd want horizontal scrolling on the body element.

Although I get your point, it's good not to have the underlying causes in the first place.  Though I don't think you should edit the [flexbox-grid.css](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/css/flexbox-grid.css) directly in [your PR](https://github.com/DivanteLtd/vue-storefront/pull/501), it's from [flexboxgrid.com](http://flexboxgrid.com/), and incase it was ever replaced with an updated version, we'd loose your changes.

**Comment by rossmc** [comment]
@pakiam interestingly there are some issues related to this reported on [flexbox-grid's github](https://github.com/kristoferjoseph/flexboxgrid/issues?utf8=%E2%9C%93&q=is%3Aissue+horizontal), I found these issues/comments interesting:
- [Issue 177 - Core Dev's Comment](https://github.com/kristoferjoseph/flexboxgrid/issues/177#issuecomment-239568734)
- [Issue 51](https://github.com/kristoferjoseph/flexboxgrid/issues/51)

Starting to think my original suggestion makes sense, unless there is a specific reason to avoid it. Either way, we should put whatever fix we have in a new `layout.scss` file rather than editing `flexbox-grid.css` directly.

**Comment by pkarw** [comment]
I would only suggest to not modify the core frameworks files we are using; first update and we are done

**Comment by filrak** [comment]
@pakiam i understand your concerns but this issue is related with flexbox grid itself so all we need to do is just wait for the fix and in the meantime make temporary fix which will not affect our css that much
@rossmc we should do as you suggested. If there is a problem with grid itself we should just fix it in easiest possible way and avoid modifying the core grid because it could break when we will update it. Go on with you'r idea. 

Moving to flexbox grid 2 is also a good idea but requires more time ;)

**Comment by pkarw** [comment]
@pakiam thanks for your solution, please report it to flexbox as a PR - i think it's good idea

**Comment by mercs600** [comment]
I agree with @pakiam overflow on body this is bad practice. We have problem for sure with grid, not with flexbox grid library but I think we have some nested rows or container. Another option we changed some margins on rows. 

@rossmc I had to change your quick fix. I removed overflow from body and I added it to #app container. Overflow on body breaks the router-link click behavior.

**Comment by pakiam** [comment]
@mercs600 hope i will find some time next week for this. There is much more bugs with this grid library, like wrong .container width on tablet screens.
Also I would like to make this grid library as a project dependency.

**Comment by mercs600** [comment]
@pakiam Nice ! If you need some help, let me know. BTW this is sad, because PR with fixes are waiting, but author can't accept it 😞
