### ISSUE TITLE
Shipment details does not loaded if user is logged

### ISSUE THREAD

**Issue by iehoshia** [DivanteLtd/vue-storefront#5041]
## Current behavior

When the user is in checkout and is logged the shipment details are not loaded from account.

## Expected behavior

The shipment detail loaded if shipToMyAddressCheckbox is selected. I need to deactivate and activate after it works. 

## Steps to reproduce the issue

1. Login in your account
2. Add product and go to checkout
3. Click on personal submit 
4. Shipment detail form is displayed but without the info 
5. Uncheck and check the button and the info is correctly loaded now. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ x] NO

## Environment details

- Browser: Chrome, Safari
- OS: Windows, iOS
- Code Version:  vue-storefront 1.11.4, vsf-default master

## Additional information
The info is doesn't loaded from database, need some manual action (check and uncheck). 

![imagen100](https://user-images.githubusercontent.com/4419325/85613368-073a8480-b617-11ea-8715-d70515c5c9ba.png)

**Comment by Fifciu** [comment]
Fixed by @AdamPawlinski
