### ISSUE TITLE
[vue-composition-api] already installed. Vue.use(VueCompositionAPI) should be called only once.

### ISSUE THREAD

**Issue by mrrobotisback** [DivanteLtd/vue-storefront#5084]
## Current behavior
Homepage show error for about-you packages.

[vue-composition-api] already installed. Vue.use(VueCompositionAPI) should be called only once.
![ErrorVue](https://user-images.githubusercontent.com/23551496/97298220-6c1b1b00-1853-11eb-90f3-cd3fafc18833.png)

## Expected behavior
Homepage show without error

## Steps to reproduce the issue
In server ready:
git clone https://github.com/DivanteLtd/vue-storefront.git
git checkout next
yarn install 
yarn build:core
yarn build:prismic
yarn build:ayc
yarn dev:ayc

## Version of Vue Storefront
Vue Storefront Next 

## Can you handle fixing this bug by yourself?
NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.
This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome 86.0.4240.111 (Official Build) (64-bit)
- OS: CentOS Linux 7
- Node: v10.20.1
- Code Version: branch next

**Comment by wfsovereign** [comment]
Any updates? or some method to works..

**Comment by wfsovereign** [comment]
> Any updates? or some method to works..

my solution is to keep consistency with the version.

**Comment by filipsobol** [comment]
Can you test this on latest `next` branch please? This issue was fix recently.

Currently some pages are broken in AYC integration, but should be fixed soon (probably next week), when I will migrate it to separate branch and update the codebase.
