### ISSUE TITLE
"We can't find the page" with direct URL request, but search Vue component works fine

### ISSUE THREAD

**Issue by mushketer888** [DivanteLtd/vue-storefront#5085]
Versions:
vsf: 1.12.2
es: 5.6.11
vsf-api: 1.12.3

SfOverlay Search Panel component can succesfully find and open products with "Fetching product data asynchronously", "Executing sync task".
But by accesing URL directly ,for example, /test.html it responds with "We can't find the page". So it doesn't give product from server side.
No errors in vsf and vsf-api console. But I got strange console log: `Top-most asyncData executed null`.

Prior to this, I was forced to change settings in vsf-api elastic.schema.product.json from "pattern": {"type": "text"}, to "pattern": {"type": "keyword"} to get rid of Internal Server Error. See:[ VSF-API #418](https://github.com/DivanteLtd/vue-storefront-api/issues/418). But I don't think it can be the cause.

What can be the cause or how to debug this?

**Comment by mushketer888** [comment]
`/api/catalog/vue_storefront_catalog/product/_search?q=bag&size=50&from=0`
gives only:
`{"took":0,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}`

while https://demo.vuestorefront.io/api/catalog/vue_storefront_catalog/product/_search?q=bag&size=50&from=0 returns:
`{"took":60,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":14,"max_score":7.200521,"hits":[{"_index":"vue_storefront_magento_1_1594277587","_type":"product","_id":"1","_score":7.200521,"_source":{"attribute_set_id":15,"updated_at":"2020-05-13 08:13:05","type_id":"simple","sku":"24-MB01","id":1,"media_gallery":[{"typ":"image","image":"/m/b/mb01-blue-0.jpg","lab":"Image","pos":1}],"name":"Joust Duffle Bag","image":"/m/b/mb01-blue-0.jpg","small_image":"/m/b/mb01-blue-0.jpg","thumbnail":"/m/b/mb01-blue-0.jpg","url_key":"joust-duffle-bag-1","status":1,"visibility":4,"price":34,"description":"<p>The sporty Joust Duffle Bag can't be beat - not in the gym, not on the luggage carousel, not anywhere. Big enough to haul a basketball or soccer ball and some sneakers with plenty of room to spare, it's ideal for athletes with places to go.<p>\n<ul>\n<li>Dual top handles.</li>\n<li>Adjustable shoulder strap.</li>\n<li>Full-length zipper.</li>\n<li>L 29\" x W 13\" x H 11\".</li>\n</ul>","slug":"joust-duffle-bag-1","url_path":"joust-duffle-bag.html","category":[{"category_id":3,"name":"Gear","position":0},{"category_id":4,"name":"Bags","position":0}],"category_ids":[3,4],"final_price":34,"regular_price":34,"product_links":[{"sku":"24-MB01","link_type":"upsell","linked_product_sku":"24-MB03","linked_product_type":"simple","position":2},{"sku":"24-MB01","link_type":"upsell","linked_product_sku":"24-MB05","linked_product_type":"simple","position":3},{"sku":"24-MB01","link_type":"upsell","linked_product_sku":"24-MB06","linked_product_type":"simple","position":4},{"sku":"24-MB01","link_type":"upsell","linked_product_sku":"24-MB02","linked_product_type":"simple","position":1},{"sku":"24-MB01","link_type":"upsell","linked_product_sku":"24-UB02","linked_product_type":"simple","position":5},{"sku":"24-MB01","link_type":"upsell","linked_product_sku":"24-WB03","linked_product_type":"simple","position":6}...`

**Comment by mushketer888** [comment]
It was because of misconfiguration

**Comment by duckchip** [comment]
@mushketer888 can you tell me what the misconfiguration was?

**Comment by mushketer888** [comment]
hard to tell. I messed configuration a lot. copied from some other project. I restored original configuration.
