### ISSUE TITLE
Issue on first load with Dom / V-dom becoming out of sync

### ISSUE THREAD

**Issue by teuma86** [DivanteLtd/vue-storefront#5194]
## Current behavior

When returning to the VSF website, the token for Magento expires. Throwing an error "The consumer can not access itself"
Something strange happens after this initial error, almost as if the virtual dom and dom have become out of sync.
if the customer logs into the website after a day, they can not check out or log out without refreshing the page.

## Expected behavior

Customer should be able to checkout / log out

## Steps to reproduce the issue

Using version 1.12 of both vsf and the api.  Have 2 customer accounts on the vsf site.
Log in.  Close the site, return the next day. Log out and log in as the 2nd customer.  
Go to the my account section and you will notice the 1st customer details are showing.

This also appears to prevent the customer from checking out.

## Version of Vue Storefront

- [ ] Vue Storefront

## Can you handle fixing this bug by yourself?

- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome
- OS: Mac, Android, iPhone

- Code Version: 1.12

## Additional information
Please see screen shot of the point the error is initially thrown, the token appears to regenerate, however the customer data is incorrect
![Screenshot 2020-10-19 at 06 49 08](https://user-images.githubusercontent.com/1490014/99265439-9ab86000-2819-11eb-914f-422823b2a5dd.png)

**Comment by gibkigonzo** [comment]
hey @teuma86 can you also check this on branch `hotfix/v1.12.3`? I've added some fixes for token invalidation to newest hotfix (not released yet)

**Comment by teuma86** [comment]
> hey @teuma86 can you also check this on branch `hotfix/v1.12.3`? I've added some fixes for token invalidation to newest hotfix (not released yet)

Good Morning

This appears to work fine on the branch hotfix/v.1.12.3.  Do you have a specific commit for this fix as this branch is not ready for release yet and we have just updated our clients site from 1.11 to 1.12?

Thank you

Jamie

**Comment by gibkigonzo** [comment]
Hey :),
those two:
https://github.com/DivanteLtd/vue-storefront/pull/4533/files
https://github.com/DivanteLtd/vue-storefront/pull/4882/files

**Comment by gibkigonzo** [comment]
closed by #4882

**Comment by teuma86** [comment]
Star, Seemed to resolve my issue
