### ISSUE TITLE
[316] User account icon doesn't work on mobile

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#524]
![zrzut ekranu 2018-01-17 12 26 59](https://user-images.githubusercontent.com/211899/35040546-c81be0d4-fb81-11e7-845f-85701d054e75.png)
Other icons work just fine. In that case we don't wan't to have an dropdown menu - jsut redirect to user account

**Comment by pkarw** [comment]
@akbarik it still doesn't work

**Comment by akbarik** [comment]
Piotr, I checked the icon, it works as intended after my last fix. Although I added some enhancements and minor bug fixes, the icon still worked. Can you please check it again?

**Comment by pkarw** [comment]
OK it's working right now!
