### ISSUE TITLE
Error: Can't build storefront dep

### ISSUE THREAD

**Issue by stegithub** [DivanteLtd/vue-storefront#5296]
## Current behavior
running yarn installer i've this error on "Build storefront dep..":
 Error: Can't build storefront dep.                                                                                        │
│     at /vue-storefront/core/scripts/installer.js:536:16                       │
│     at new Promise (<anonymous>)                                                                                          │
│     at Storefront.depBuild (/vue-storefront/core/scripts/installer.js:532:12) │
│     at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                   │
│     at async processAnswers (/vue-storefront/core/scripts/installer.js:902:3) │
│                                                                                                                           │
│ Please check log file for details: /vue-storefront/var/log/install.log        │

But install.log is empty.

## Expected behavior

Successfully build

## Steps to reproduce the issue
run yarn installer

## Version of Vue Storefront

- [x] Vue Storefront 1.12.2
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: Mac OS Big Sur
- Node: 13.11.0
- Code Version: I'm doing simply the "User-friendly installation" for Mac:
git clone https://github.com/DivanteLtd/vue-storefront.git vue-storefront
cd vue-storefront
yarn
yarn installer

## Additional information
I'm doing simply the "User-friendly installation" for Mac:
git clone https://github.com/DivanteLtd/vue-storefront.git vue-storefront
cd vue-storefront
yarn
yarn install

"Please check log file for details" ---->>  File /vue-storefront/var/log/install.log is EMPTY

**Comment by stegithub** [comment]
Wow! I don't know how but the issue is solved. After a lot of clean installations

**Comment by davidwindell** [comment]
I'm getting the same right now @stegithub , I'm wondering if its memory related or something

**Comment by deedy-tech** [comment]
I'm also getting this error.
