### ISSUE TITLE
Device module - problems with async initialization and ssr caveats

### ISSUE THREAD

**Issue by gibkigonzo** [DivanteLtd/vue-storefront#5297]
## Current behavior

1. https://github.com/DivanteLtd/vue-storefront/blob/master/src/modules/device/index.ts#L16 - VSF modules are not awaited, that means we can't lazy load device module because it can be assign to `Vue.prototype.$device` after component is rendered. Which will result in error `TypeError: Cannot read property 'isMobileOrTablet' of undefined`
2. https://github.com/DivanteLtd/vue-storefront/blob/master/src/modules/device/index.ts#L10 => `Vue.prototype.$ssrRequestContext.userAgent` doesn't exist because server context is purged in Vue.prototype
3. https://github.com/DivanteLtd/vue-storefront/blob/master/src/modules/device/index.ts#L21 => `Vue.prototype.$ssrRequestContext` is purged because we shouldn't pollute prototype. On server side Vue module is cached by node and shared between requests. So changing it on each request may result in overriding $device for other request. We shouldn't add $device to Vue prototype, because state of it is based on each request. Or $device functions should check userAgent on each request. Which will result in b/c and instead of `Vue.prototype.$device.isMobileOrTablet` we will have `Vue.prototype.$device.isMobileOrTablet()`. You can test problem with polluting Vue prototype:
```
  console.log('before', Vue.prototype.$test)
  Vue.prototype.$test = (Vue.prototype.$test || 1) + 1
  console.log('after', Vue.prototype.$test)
```

## Expected behavior

no errors

## Version of Vue Storefront

- [x] Vue Storefront
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pvoo** [comment]
this issue seems related : https://github.com/DivanteLtd/vue-storefront/issues/5164
