### ISSUE TITLE
[vue-catalog] Subscribe to newsletter

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#530]
Just emit the following event (+clear the input box) and you're done:

```
      EventBus.$emit('newsletter-after-subscribe', { email: this.email })
```

![zrzut ekranu 2018-01-17 12 59 27](https://user-images.githubusercontent.com/211899/35041790-4f67813e-fb86-11e7-9380-5261fec6a94e.png)

**Comment by filrak** [comment]
Lack of notifications atm -> todo

**Comment by filrak** [comment]
notification added ;)
