### ISSUE TITLE
[vue-catalog] Valid category query

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#537]
![zrzut ekranu 2018-01-17 13 09 44](https://user-images.githubusercontent.com/211899/35042163-bc6e64a4-fb87-11e7-9480-2c1c4cfc628a.png)

The valid query to get active categories is: 
```
    categories () {
      return this.$store.state.category.list.filter((op) => {
        return op.level === 2 // display only the root level (level =1 => Default Category)
      })
```

and then additional check

```
        <router-link v-if='category.product_count >0 || category.children_data.length>0' :to="{ name: 'category', params: { id: category.id, slug: category.slug }}">{{ category.name }}</router-link>
```

**Comment by filrak** [comment]
The second condition is ommited for demo purposes (we hava only 2 categories with 0 items)
