### ISSUE TITLE
Add nested categories in sidebar menu | Figma

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#54]

**Comment by karolbzik** [comment]
The designs are ready.
<img width="1440" alt="vue storefront - sidebar menu" src="https://user-images.githubusercontent.com/18116406/31318988-7b0ffe26-ac5b-11e7-8d74-31c63367c70e.png">
<img width="1440" alt="vue storefront - sidebar menu with nested categories" src="https://user-images.githubusercontent.com/18116406/31318990-7dcb0214-ac5b-11e7-87d9-cfa28b44eac4.png">
