### ISSUE TITLE
Email do not exist

### ISSUE THREAD

**Issue by tkapet** [DivanteLtd/vue-storefront#56]
vuestorefront@divante.co  that is written in the github readme do not exist.
Final-Recipient: rfc822; vuestorefront@divante.co
Action: failed
Status: 5.0.0
Diagnostic-Code: smtp; 550-5.1.1 The email account that you tried to reach does not exist. Please try
 550-5.1.1 double-checking the recipient's email address for typos or
 550-5.1.1 unnecessary spaces. Learn more at

Please put a contact information for sending invitations to new members in the slack chat.

**Comment by pkarw** [comment]
@tkapet thanks! I'm fixing the email issue at the moment. We'll send you slack invite + update the readme as well

**Comment by patrykpiston** [comment]
Hey @tkapet  
Here is the slack invite link  
https://join.slack.com/t/vuestorefront/shared_invite/enQtMjUyMzA1NDM1ODg4LTYzZjljNjZlN2JmMmM4NzQzOWFkOTA5NTMyOTg0NzIwNjMxNTNjYTZhNzAzOWM5MjEyYzE2OWE3ZTJmOTU3OTY

**Comment by pkarw** [comment]
E-mail issue fixed, should work now
