### ISSUE TITLE
Images placeholder

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#563]
We should add a static placeholder for product images into ProduxtTile.vue to  keep the sizes of ProduxtTiles (right now it sometimes flip-flops after photo is loaded)

The image should be stored under /assets therefore will be cached via service worker

**Comment by mercs600** [comment]
@pkarw What about first 6 images (#241). What do we want to have in source ? If we will set placeholder as default for first images, then in pre-render source we will get placeholder image as source. Is it ok for us ?

**Comment by pkarw** [comment]
We want yo have the image url for the first 6pics - IT worked fine;
The problem I observed is related more to the lazy loaded pictures when you scroll down - we should have used placeholders for these images for the time when they are downloaded

**Comment by pkarw** [comment]
https://www.dropbox.com/s/kjc3sf4zrrhsqnt/placeholders.mov?dl=0

It looks pretty good @mercs600!
