### ISSUE TITLE
Add filters in mobile view

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#58]
Full screen filters in mobile view.
<img width="360" alt="vue storefront - mobile product listing with horizontal filters" src="https://user-images.githubusercontent.com/18116406/31351838-dc1399e0-ad2c-11e7-83de-dd3e2afe25b2.png">

**Comment by patrykpiston** [comment]
@karolbzik full screen as it is now? Now filters go to the top (on top of all products)

**Comment by karolbzik** [comment]
@patrykpiston yes, let's add a full screen on filters.

@patrykpiston here you can find the design of the products listing with for the mobile, after clicking the button "filters" the filters should be opened on the full screen:
![mobile product listing with horizontal filters](https://user-images.githubusercontent.com/18116406/32461709-0aa2a1dc-c337-11e7-9578-2c0cd89db42b.png).
The design also available here with the grid and all layers separated.
