### ISSUE TITLE
Add saved products feature

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#59]
Add saved product feature.

Use scenarios:
- As a customer, I can save product by clicking the heart icon (available at the product block - during mouseover and at product card);
- As a customer, I can open list of saved product by clicking the heart icon at the top;
- As a customer, I can remove a product from the saved product list by clicking the full heart.

The visualization:
<img width="1440" alt="vue storefront - saved products" src="https://user-images.githubusercontent.com/18116406/31352074-aa2ec840-ad2d-11e7-8a52-8a0be985d639.png">

**Comment by pkarw** [comment]
@matibenav here you have the layout for wishlist
