### ISSUE TITLE
Product page - banner to the featured section

### ISSUE THREAD

**Issue by szafran89** [DivanteLtd/vue-storefront#591]
Add the banner to the featured section - in the project, I put "Sales Eco-friendly" banner;
Moved from #488 

"Sales Eco-friendly" banner is visible only on mobil. Is it ok?

**Comment by szafran89** [comment]
As we discussed I assigned to you ;)

**Comment by Aekal** [comment]
@karolbzik 
Do we need this banner only on mobile or also on desktop?

![zrzut ekranu 2018-02-09 o 17 17 02](https://user-images.githubusercontent.com/7126345/36037613-9102f1e8-0dbd-11e8-8239-0acd40d3270c.png)

**Comment by pkarw** [comment]
we should have it on both mobile and desktop @Aekal could you take care of this one?

**Comment by Aekal** [comment]
Done :)
