### ISSUE TITLE
eslint-plugin-vue

### ISSUE THREAD

**Issue by PanMisza** [DivanteLtd/vue-storefront#604]
I suggest to use [`eslint-plugin-vue`](https://github.com/vuejs/eslint-plugin-vue). In this project there is a lot of inconsistencies, anti-patterns, incorrect uses of `v-for` (missing `key`'s), incorrect uses of `v-if`, and many more. I think it would be a good idea to stick to a [Vue Style Guide](https://vuejs.org/v2/style-guide/). Most of inconsistencies we can fix just by running `eslint --fix`, using one of `eslint-plugin-vue` predefined configs. 

In some cases will be required human intervention, but I think it's worth it to achieve a consistent and readable code ;)

**Comment by pkarw** [comment]
Good point. I think we should have it in the project; Do you have any plan how to introduce it without distracting the development? I believe that one should enable it AND fix all the errors/misalignments to VSG to have a clear starting point. If you're willing to do some PR - it's good issue to take care of :)

**Comment by PanMisza** [comment]
I think the best solution is to do it once. The most of changes will be cosmetics - indentions, new lines for attributes, naming convention, self closing tags... There are also props types/values to define in some places and few other minor things to do.

I'll split changes to few commits, eg. _`eslint --fix` job_, _props types defined_, _new lines fixes_, _code reorder_, ...; so you can check changes more easily - there will be a lot of files changes (almost every Vue and JS file). So be ready ;)

You can assign me to this issue - tomorrow evening I'll do all this stuff.

**Comment by pkarw** [comment]
Done :)
