### ISSUE TITLE
Make assets theme-independent

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#606]
1. Create `theme/assets` alias - it should point to `theme/{activethemename}/assets`. `assets` alias should still point to `src/assets` - we will place theme-independent assets here.
2. Move assets from default and vue-catalog themes to correct folders after canging the alias and change the pathes on theme components so they will point to the new directory.
3. Update [project structure docs](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Project%20structure.md) after changes

**Comment by qiqqq** [comment]
@filrak I analyzed this task and I have other solution to do this:

In server.js we can add additional middleware which overwrite default src/assets/ like this:

```
app.use('/assets', serve(path.resolve(__dirname, 'src/assets'), true))
app.use('/assets', serve(path.resolve(__dirname, 'src/themes/' + theme + '/assets'), true))

```
We will have some global assets like logo, placeholder, etc. and theme-specific assets which will have priority to serve. Paths to assets remain unchanged and will be logic and simple to use in themes.

What you think about this solution?

I have also one question. There are some images like instagram feed or slides which are pointed in JSON files in /src/resources/. It should stay global assets?

**Comment by filrak** [comment]
@qiqqq sounds good, go on with it ;)

And instagram feed and slides should be theme-specific for default theme
