### ISSUE TITLE
Write down the current core components API for future improvements

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#609]
We want to standarize the core:
- Make core components API (methods and data exposed for theme components) as much development-friendly as it is possible
- Delete unnecessary core components
- Merge/split some core components to make them easier to use and more flexible

After this changes the Storefront will be fully implementation-ready, properly documented and easy to use for all developers which is what we're all aiming for.

But before doing this enchancements we need to write down the current API's and think what should be changed or improved. It's a lot of work and we need your help!

Please taka a look at [this document](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/components/%5Btemporary%5D%20core%20components%20API.md) and help us with writing down the current API's. This is the most important task in this milestone so your help is cruicial for us ;)

**Comment by pkarw** [comment]
@filrak how does the status look like here?

**Comment by pkarw** [comment]
What’s needed more to close this issue @filrak?

**Comment by filrak** [comment]
It's done. @akbarik awesome job!
