### ISSUE TITLE
Photos for HP slider

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#61]
Karl, we need photos + links for Home page slider to just close this part once and for all.

Could you please:
1) Edit and commit changes to: https://github.com/DivanteLtd/vue-storefront/blob/master/src/resource/slider.json
2) put the images under `src/assets/slides` which links to `/assets/slides/*` relative url:
```js
app.use('/assets', serve(path.resolve(__dirname, 'src/assets'), true))
```

So here you have an example of json:

```json
        {
            "title" : "Love Denim",
            "subtitle" : "Best of blues",
            "button_text" : "Shop now",
            "image" : "/assets/slides/slide_01.png"
        },
```

**Comment by pkarw** [comment]
@karolbzik we have to close this tomorrow - I've got 4h during commute to Poznań (railway) so I can configure the lacking things out - like final tweaks on HP

**Comment by karolbzik** [comment]
Here are the backgrounds for 3 slides:
<img width="1440" alt="slide3" src="https://user-images.githubusercontent.com/18116406/31516758-ef5c5310-af99-11e7-9785-482486df915e.png">
![Uploading Slide2.png…]()
![Uploading Slide1.png…]()

Please use headlines from the Figma mockup - https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront-Open-Source.

**Comment by karolbzik** [comment]
Also - the copy and button need to be centered, now they are eft-aligned.

![zrzut ekranu 2017-10-13 o 08 56 36](https://user-images.githubusercontent.com/18116406/31533828-75a58928-aff4-11e7-8c3a-b8300b077232.png)

**Comment by pkarw** [comment]
I'm taking this one!
