### ISSUE TITLE
Splitting `lib/filters.js` file

### ISSUE THREAD

**Issue by szafran89** [DivanteLtd/vue-storefront#612]
There is one file `filters.js` which contains Vue filters and global methods. IMO we should split it to 2 files `filters.js` and `helpers.js`. What do you think?

Additionally `displayAttribute` is unused.

**Comment by filrak** [comment]
good idea ;)

**Comment by szafran89** [comment]
I'll handle it in few days.

**Comment by filrak** [comment]
Thank you!
