### ISSUE TITLE
Core Pages have hardcoded notification texts

### ISSUE THREAD

**Issue by matibenav** [DivanteLtd/vue-storefront#615]
Should be part of the data, allowing those messages to be overwritten by merge.

**Comment by pkarw** [comment]
The key goal here is to have the possiility to apply translations?

**Comment by pkarw** [comment]
We should start using https://github.com/kazupon/vue-i18n

Starting with this purpose - notifications - it’s good starting point

**Comment by pkarw** [comment]
I’m closing this one because I’ve just opened more general issue #618
