### ISSUE TITLE
Add i18n supprt

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#618]
https://github.com/kazupon/vue-i18n

This is connected to #615

**Comment by pkarw** [comment]
We can start with test support just for notification messages for now

**Comment by filrak** [comment]
@matibenav maybe you can help Akbar with it since you started some work on this :)

**Comment by pkarw** [comment]
Guys I’m on it :) I’m traveling by train right now while coding this feature ;)
