### ISSUE TITLE
Configure proper home page products blocks regarding the design

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#62]

**Comment by pkarw** [comment]
Waiting for pinterest content to include @karolbzik

**Comment by karolbzik** [comment]
Related to https://github.com/DivanteLtd/vue-storefront/issues/79, the content for the Get inspired section will be linked from Instagram, not Pinterest.

**Comment by pkarw** [comment]
Waiting for #79 to close this one
