### ISSUE TITLE
Click on overlay should close active component eg. sidebar menu 

### ISSUE THREAD

**Issue by mercs600** [DivanteLtd/vue-storefront#622]
Steps to reproduce: 
1) Open sidebar menu by burger btn
2) Click on the overlay
3) Now you can see, that overlay disappeared, but sidebar is not closed. 

This is related with change of method name: 
https://github.com/DivanteLtd/vue-storefront/commit/61017138914a2cc51d730730168ade928c5cf8df#diff-fde08628ea19d9d6e7ae0824cb1aa00fR15

**Comment by filrak** [comment]
@mercs600 should it be closed?

**Comment by mercs600** [comment]
Yes we can close it now
