### ISSUE TITLE
Create Blank theme with component library

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#625]
I'm working on a new theme called 'blank' to help people implement VS faster -> it's just a basic VS setup without styling but with all functionalities. 
It will also contain ready to use ui component library.

The theme will include:
- Homepage 
- Category page (with filters)
- Product page
- User Dashboard
- Checkout
- Wishlist
- Cart
- Comparator

Each component will be properly documented :)

**Comment by pkarw** [comment]
https://github.com/DivanteLtd/storefront-ui
