### ISSUE TITLE
Add the $t() support for i18n for remaining components

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#627]
I've already added the support for translations (http://kazupon.github.io/vue-i18n/en/api.html#methods) to Category, Product, Home components and all the instances of 'notification' event - system wide according to #618 

We need to add some translation helper calls like:
```
<p>Filters</p>
```
should be changed to:
```js
<p> {{ $t('Filters') }}</p>
```

If there are any remaining, locale specific messages in the code we should change them for example from:

```js
      EventBus.$emit('notification', {
        type: 'success',
        message: `Product ${htmlDecode(product.name)} has been added to the compare!`,
        action1: {label: 'OK', action: 'close'}
      })
```
to

```js
import i18n from 'lib/i18n'

      EventBus.$emit('notification', {
        type: 'success',
        message: i18n.t('Product {productName} has been added to the compare!', { productName: htmlDecode(product.name) }),
        action1: {label: 'OK', action: 'close'}
      })
```

**Comment by Aekal** [comment]
We still need translations for all inputs with validation and checkboxes with label. 
@PanMisza could you apply these translations in #640 ?

**Comment by pkarw** [comment]
I've just fixed the forms
