### ISSUE TITLE
SyntaxError in installer.js

### ISSUE THREAD

**Issue by rushtoni88** [DivanteLtd/vue-storefront#638]
When I try to run **npm run installer** I get the following error:

`
> vue-storefront@0.0.0 installer /Users/Ian/Documents/Workspace/work/vue-storefront/vue-storefront
> node installer

/Users/Ian/Documents/Workspace/work/vue-storefront/vue-storefront/installer.js:651
  inquirer.prompt(questions).then(async function (answers) {
                                  ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-storefront@0.0.0 installer: `node installer`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-storefront@0.0.0 installer script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Ian/.npm/_logs/2018-02-06T15_18_16_096Z-debug.log`

Having looked at the section referred to of installer.js I can't see any syntax problems but this is a fresh install so wondered if anyone else had this issue?

**Comment by pkarw** [comment]
Can not confirm. Which version of node do you have? >=8.0.0 is required

https://www.dropbox.com/s/mi26fdipbn4c5kh/Zrzut%20ekranu%202018-02-06%2016.36.34.png?dl=0

**Comment by rushtoni88** [comment]
Apologies, it was because my node version was < 8.0.0. I'm now getting an error cannot find module 'shelljs'. Should this be installed globally or is this a required dev package?

**Comment by rushtoni88** [comment]
Upgrading node to > 8.0.0 fixed this. Thanks.

**Comment by pkarw** [comment]
I've fixed the problem with missing shelljs dependency
