### ISSUE TITLE
Change color names to more generic and reduce the color palette

### ISSUE THREAD

**Issue by Aekal** [DivanteLtd/vue-storefront#639]
Moved from #634.
Right now in default theme we're using classes like `c-lightgray`, `bg-emperor`, but it'll be better to use more generic classes and create better naming convention, like `c-primary`, `c-secondary`, etc.
We currently have 10+ colors, it'll be helpful to reduce the color palette and merge similar colors to one.

All ideas are welcome ;)

**Comment by pkarw** [comment]
@Aekal will you take care of this before 21st?

**Comment by Aekal** [comment]
I think so, but I'm still looking for a good idea with color naming convention

**Comment by pkarw** [comment]
@Aekal we do have release on 1st march. Will you handle this one before the date?

**Comment by mercs600** [comment]
@Aekal 100% agree with you, please look on my previous post #126 . I can take care of it

**Comment by Aekal** [comment]
@mercs600 Great! So please take care of it, I'm assigning to you

**Comment by filrak** [comment]
@mercs600 will you handle it till 1st of march or you want this task to be moved to the next milestone?

**Comment by mercs600** [comment]
I'm working on it, it will done in this release

**Comment by mercs600** [comment]
@Aekal @filrak What do you think about :hover support handling by css class ? Do we need this ? 
I noticed that @karolbzik mark on sigma some primary colors: 
![zrzut ekranu 2018-02-24 o 16 41 20](https://user-images.githubusercontent.com/7935392/36632057-9287c226-1981-11e8-9ca3-0f94b2f4ee44.png)

You can see there is 2 values for primary color. So I think this is hover variant.

**Comment by mercs600** [comment]
You can see what I mean on this draft: 
https://github.com/mercs600/vue-storefront/blob/99f48340d5e94a3146da2d9e7e7e9c39175d960a/src/themes/default/css/variables/_colors.scss 

1. I set list with real name colors 
2. Next we have maps with main project colors. These are colors which @karolbzik prepared on Sigma - UI guide. On these maps you can set simple color value or some additional variants like hover or focus. 
3. Then we can use one mixin to generate colors or background selectors with their states. 
Mixin:
https://github.com/mercs600/vue-storefront/blob/99f48340d5e94a3146da2d9e7e7e9c39175d960a/src/themes/default/css/helpers/mixins/_color-selectors.scss 
Usage: https://github.com/mercs600/vue-storefront/blob/99f48340d5e94a3146da2d9e7e7e9c39175d960a/src/themes/default/css/base/_color.scss#L17 

Before I will refactor all views I have to know if it's what I did make sense for you ?

**Comment by filrak** [comment]
For me it looks very good but not so staightforwart So it requires docs :)

**Comment by filrak** [comment]
@aekal wdyt?

**Comment by pkarw** [comment]
I think this is good idea. Please proceed @mercs600 and close it before 1st :)
