### ISSUE TITLE
Add components for form inputs

### ISSUE THREAD

**Issue by Aekal** [DivanteLtd/vue-storefront#640]
Right now we have a mess in code in places where we use many inputs (Checkout, MyAccount, Login/Register). Also the styles are often duplicated.

We should create reusable components to replace existing inputs and checkboxes.
For input component there should be an option to optionally add validation, icon (show/hide password) and so on.

**Comment by PanMisza** [comment]
@Aekal, You can assign me to this.

**Comment by Aekal** [comment]
Sure, I suggest to do this after merging my changes in #637 to prevent merge conflicts (I've refactored 
 templates/styles code).

Additionally, it'll be nice to remove `#my_account` and `#checkout` styles in `pages/Checkout.vue` and `pages/MyAccount.vue` and change styles scope there to `<style lang="scss" scoped>`. We have duplicated styles for inputs because of this.

**Comment by Aekal** [comment]
@pkarw Could you assign PanMisza to this issue? I don't see him on the list.

**Comment by filrak** [comment]
@Aekal It's merged now ;)

**Comment by filrak** [comment]
@PanMisza it would be also wise to make validation errors a component (i've started it long ago, there is a `validationError.vue` file). Instead of adding multiple div's (or other actions) for different validation errors we can do it in one components and just pass the error messages here.

**Comment by Aekal** [comment]
Maybe we could even mix `FormInput` and `ValidationError` components to one? Then just pass validation as optional prop to `FormInput` component? It may be too complicated but it'll be nice to try.

**Comment by filrak** [comment]
@Aekal very good idea!
 @PanMisza will you take care of it?

**Comment by PanMisza** [comment]
@filrak 
Yes, at the beginning of next week :)

**Comment by filrak** [comment]
@PanMisza great, thanks ;)

**Comment by pkarw** [comment]
@PanMisza please do accept the github invitation to allow me to assign the task to you please :)

**Comment by pkarw** [comment]
@PanMisza we do have release on 1st March; could you handle it before?

**Comment by PanMisza** [comment]
@pkarw 
Sorry for delay... I'm currently changing my flat and have no time for this.
I can finish this task this weekend.

**Comment by filrak** [comment]
@PanMisza Great ;)

**Comment by pkarw** [comment]
@PanMisza how the progress looks like for this one ?:)

**Comment by pkarw** [comment]
@PanMisza any progress on that?

**Comment by pkarw** [comment]
@Aekal any chance that you'll take care of this one maybe next week? It doesn't seem like any body is working on this :)

**Comment by Aekal** [comment]
@pkarw Ok, I'll work on it
