### ISSUE TITLE
New feature "Product reviews" on Product card in the Default theme

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#648]
@karolbzik we need a design here

**Comment by karolbzik** [comment]
<img width="1440" alt="vue storefront - product card product reviews 28 02 2018" src="https://user-images.githubusercontent.com/18116406/36802360-f966883e-1cb4-11e8-931c-6a7e112f85e1.png">

At https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront-Open-Source, under the name "Product card + product review".

**Comment by karolbzik** [comment]
I've updated a little the project, the most important changes:
- Unified fonts (color, size, weight)
- Separating lines on the mobile view
- Number of reviews in the headline of the section with reviews

<img width="360" alt="vs - 3 1 product cart on mobile 31 03 2018" src="https://user-images.githubusercontent.com/18116406/38164915-0c1312e4-350c-11e8-9c57-05a7589c7076.png">
<img width="1440" alt="vs - product card 1 03 2018" src="https://user-images.githubusercontent.com/18116406/38164916-0c35dd7e-350c-11e8-9fe0-44b782583a8e.png">

Both designs available in https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront under the names "Product card" and "Product card on mobile"

**Comment by karolbzik** [comment]
After coding and releasing - assign me please this task later so I could perform UX tests.
