### ISSUE TITLE
Home Page slider CTA is not linked

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#654]
We need to Just fix the button links on slider 
![207cdd69-6770-4429-bf16-46f9ee8991e0](https://user-images.githubusercontent.com/211899/36135485-b936c268-108b-11e8-8bd0-a67c246a4e18.png)

**Comment by adaudenthun** [comment]
Hi,

I'm new and i think is a good issue to start ! :)
Can you tell me where this link normally send us ?

Thanks

**Comment by pkarw** [comment]
Cool! You can choose it :) maybe just some category?

**Comment by adaudenthun** [comment]
OK , you can assign me this ticket ? 

Thanks ! :)

**Comment by pkarw** [comment]
Please accept the github invitation I’ve just send you to allow me adding you to the project thanks!

**Comment by adaudenthun** [comment]
it's ok for me

**Comment by adaudenthun** [comment]
#680

**Comment by adaudenthun** [comment]
Cool :)
