### ISSUE TITLE
Split Vuex Stores to actions/mutations/getters/helpers files

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#660]
Each module of our Vuex Store should be a separate folder containing `index.js` as a main export file and state + `actions.js`, `mutations.js`, `getters.js`. `helpers.js` (if needed). It will make reasoning about Vuex states easier and allow further refactoring of Stores

**Comment by pkarw** [comment]
@szafran89 we do have release planned for 1st March and I belive we should have this one finished for 1.0RC; is it possible for you?

**Comment by szafran89** [comment]
@pkarw I'll do it for sure.

**Comment by pkarw** [comment]
@szafran89 is the 1st March realistic? :)

**Comment by szafran89** [comment]
@pkarw done ;)

**Comment by filrak** [comment]
@szafran89 gr8 ;)
