### ISSUE TITLE
Create theme/core mixins/filters in the same way as plugins + write docs

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#661]
In docs you shouldplace basic overwiew of how to use mixins/filters, how to write and register one and list of current mixins/filters

https://github.com/DivanteLtd/vue-storefront/blob/master/doc/filters/Working%20with%20filters.md
https://github.com/DivanteLtd/vue-storefront/blob/master/doc/mixins/Working%20with%20mixins.md

**Comment by pkarw** [comment]
@szafran89 is the 1st March realistic? :)
