### ISSUE TITLE
Shipping method - Droppoints

### ISSUE THREAD

**Issue by thomasthune** [DivanteLtd/vue-storefront#665]
Hi!

I'm working on making support for shipping droppoints(parcelshops). It's quite a big thing here in Denmark, so it's something that all projects we will be working on will be using.

So first things first, is this something that would make sense to "bake-in" to vue-storefront or should it be implemented more in a plugin/per use basis.

**Comment by pkarw** [comment]
Wow, cool stuff. We’ve decided some time ago to put all integrations and this kind of specific features into extensions. Take a look at mailchimp integration. Looking forward for this PR!

**Comment by thomasthune** [comment]
#681

**Comment by filrak** [comment]
@thomasthune it's assigned to Milestone 1.0RC - will you do it before 1st of March or should we move it to next milestone?

**Comment by thomasthune** [comment]
Yes, i don't think that should be a problem, hopefully i can wrap it up during the weekend.

**Comment by filrak** [comment]
Thanks ;)
