### ISSUE TITLE
Make resources theme-specific

### ISSUE THREAD

**Issue by qiqqq** [DivanteLtd/vue-storefront#666]
This task is related with [#606](https://github.com/DivanteLtd/vue-storefront/issues/606) where we created theme-specific assets. Now we should do the same with /src/resources/

This task required also changes in some components and modules uses some global resources:

- src/components/core/blocks/MainSlider/MainSlider.vue
- /src/store/modules/social-tiles.js
- /src/themes/default/components/theme/blocks/PromotedOffers/PromotedOffers.vue

**Comment by pkarw** [comment]
@qiqqq will you take care of this one?

**Comment by qiqqq** [comment]
@pkarw Yes, I can try

**Comment by pkarw** [comment]
@qiqqq what do you think: when should we have this one done?

**Comment by qiqqq** [comment]
@pkarw I want to do [#685](https://github.com/DivanteLtd/vue-storefront/issues/685) first and this next within a few days

**Comment by qiqqq** [comment]
@filrak @pkarw I analyzed this task and my solution for this is to move some resourses (ig_feed.json, slides.json and promoted_offers.json) to theme's resources. The problem is that this resources are imported in core components and stores, so we must change imports in global files to for example "theme/resource/ig_feed.json" and this will be cause webpack error if someone will be want to use core component or store in theme and specific resource will not be uploaded in theme's resources directory.

Second solution is to leave this files in core/resource and eventualny allow user to overwrite this if he upload this file to  theme's resources directory. But here problem is, we still have this resources in core and they should'nt be here in my opinion.

What do you think?

**Comment by pkarw** [comment]
Thanks for digging into this. First solution is much better in my opinion.


BUT


Why not to make the paths to resources theme dependent?
I mean - to move the resource path to the component property to be set within specific theme?

<slider resource=“theme/slides.json” />

?

So it’s a variant of your first solution. We can keep the default paths as property defaults

**Comment by filrak** [comment]
@pkarw @qiqqq I think this component shouldn't be  external json-dependent at all and have the data inside of it. Core component should only be responsible for taking the data as props

**Comment by filrak** [comment]
Tbh i think this feed should be an extension
