### ISSUE TITLE
Add input for product qty in product page

### ISSUE THREAD

**Issue by Aekal** [DivanteLtd/vue-storefront#667]
We should be able to specify quantity of products added to cart. 
At the moment we can add only 1 product by clicking on `Add to cart` button. 
We have a design for qty in bundle products, so maybe we can implement this also in product page?

![image](https://user-images.githubusercontent.com/7126345/36249667-ad6ba8de-123b-11e8-80ea-507681f3ab0c.png)

**Comment by pkarw** [comment]
@filrak could You add it before 1.0?
