### ISSUE TITLE
Add 'Sort by' feature

### ISSUE THREAD

**Issue by Aekal** [DivanteLtd/vue-storefront#671]
In design of category page we have 'Sort by …' select.
![image](https://user-images.githubusercontent.com/7126345/36250438-15f95796-123e-11e8-8739-845cbb852a20.png)
We should create this select with logic and add options like:
- Price: low to high
- Price: high to low
- Newest
- *Popularity
- *On sale: show first

**Comment by pkarw** [comment]
@kruchy8 ok, go on :)

**Comment by pkarw** [comment]
@filrak could You take a look at it - @kruchy8 prepared a PR but it's not integrated with the Elastic Search - I can help you with this
