### ISSUE TITLE
Sidebar menu adjustments

### ISSUE THREAD

**Issue by Aekal** [DivanteLtd/vue-storefront#672]
- Extend clickable area of 'My account' link to full width when user is not logged in 
<img width="373" alt="zrzut ekranu 2018-02-15 o 10 58 12" src="https://user-images.githubusercontent.com/7126345/36251054-141d2ec8-1240-11e8-914c-c07c4b572f46.png">
- Change arrow tag from `span` to `button` and extend clickable area (50% for link and 50% for arrow will be good) 
<img width="532" alt="zrzut ekranu 2018-02-15 o 10 58 51" src="https://user-images.githubusercontent.com/7126345/36251088-2b0ac30c-1240-11e8-9923-8064ea5fe8ad.png">
- Change tags of top icons to `button` 
<img width="352" alt="zrzut ekranu 2018-02-15 o 11 00 08" src="https://user-images.githubusercontent.com/7126345/36251006-ed3118c4-123f-11e8-986b-7c7fa2aa78e6.png">

**Comment by pkarw** [comment]
@Aekal I've just assigned this one to you :)
