### ISSUE TITLE
Create store locator extenstion

### ISSUE THREAD

**Issue by qiqqq** [DivanteLtd/vue-storefront#677]
To do is create extenstion to VS which allow to add store locator with google map and ability to filter local stores.

**Comment by BlitZ-UK** [comment]
Where would the store location data be pulled in from? As i am unsure if all the platform adaptors would have this data available, where else can it be pulled from?

**Comment by filrak** [comment]
For the beginnig it should get the data from mocking  json and be implemented as an extension. We can świtch to sync instead of json later

**Comment by pkarw** [comment]
Please take a look at: https://github.com/DivanteLtd/vue-storefront/tree/master/src/extensions/droppoint-shipping and https://github.com/DivanteLtd/vue-storefront/blob/master/doc/extensions/droppoint-shipping.md
