### ISSUE TITLE
Move scripts to separate folder

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#685]
- [ ] Create an webpack alias 'scripts' and change all pathes pointing to them to use alias
- [ ] Move scripts to `core/scripts` folder (all.js, installer.js, server.js, fixconfigs.js) 
- [ ] Make changes in package.json to adjust script pathes
- [ ] Make sure all scripts still works properly (especially installer)
- [ ] Make sure pathes in above scripts and in the project are still viable after changing folder structure

**Comment by pkarw** [comment]
@qiqqq we have time for this til l1st March; is it doable?

**Comment by pkarw** [comment]
please test the installer and other scripts at least twice 👯‍♂️

**Comment by qiqqq** [comment]
@pkarw Yes, I want to do this within a few days

**Comment by pkarw** [comment]
@qiqqq please test the installer after moving it - for sure you should change the default path were `vue-storefront-api` is installed (to move it one '../' level up) https://github.com/DivanteLtd/vue-storefront/blob/646f41349244becf1fce5991b7ddb5be6f9dcb4e/installer.js#L575

The same with other paths (config files etc)

**Comment by qiqqq** [comment]
@pkarw Changes in installer.js are unnecessary. There are only shell scripts invoked by [shelljs](https://www.npmjs.com/package/shelljs) and this package invoke scripts always form root directory. I tested it and additionaly I checked shell.exec('pwd') returns root directory (location of installer.js file does not matter)

Here is pull request -> https://github.com/DivanteLtd/vue-storefront/pull/744
