### ISSUE TITLE
Add docs for vuex stores

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#687]
We need a basic docs for vuex stores API - which is the core data api for Vue Storefront:
- [x] cart.js
- [x] product.js
- [x] category.js
- [x] checkout.js
- [x] meta.js
- [x] order.js
- [x] stock.js
- [x] sync.js
- [x] user.js
- [x] attribute.js

**Comment by filrak** [comment]
I'm adding content from duplicated issue:
*First fill this document with general approach to our data handling https://github.com/DivanteLtd/vue-storefront/blob/master/doc/data/Working%20with%20Vuex.md
*Make separate docs for each Vuex Store like in this example https://github.com/DivanteLtd/vue-storefront/blob/master/doc/data/Product%20Store.md
