### ISSUE TITLE
Create documentation on Vuex Stores

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#692]
* First fill this document with general approach to our data handling https://github.com/DivanteLtd/vue-storefront/blob/master/doc/data/Working%20with%20Vuex.md
* Make separate docs for each Vuex Store like in this example https://github.com/DivanteLtd/vue-storefront/blob/master/doc/data/Product%20Store.md

**Comment by pkarw** [comment]
OK, it's duplicate of #687 I'll take care of it
