### ISSUE TITLE
[i18n] Create the Spanish translation

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#693]
Working with translations is pretty easy with Vue Storefront, take a look at: https://github.com/DivanteLtd/vue-storefront/blob/master/doc/i18n/Working%20with%20translations.md for reference

**Comment by anthuanvasquez** [comment]
I can help, assign to me

**Comment by pkarw** [comment]
Great, please go for it!

**Comment by anthuanvasquez** [comment]
@pkarw can you check the PR https://github.com/DivanteLtd/vue-storefront/pull/856
