### ISSUE TITLE
Contentful / Headless CMS integration

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#697]
Would be great to have Contentful.com integration as the CMS is one of the key parts of Fashion eCommerce

I see it as a general components/widgets that can be easily themable to get specific Contentful documents and colections 

For reference: https://www.contentful.com/developers/docs/javascript/tutorials/integrate-contentful-with-vue-and-nuxt/ 

```js
<script>
  import {createClient} from '~/plugins/contentful.js'

  const client = createClient()

  export default {
    // `env` is available in the context object
    asyncData ({env}) {
      return Promise.all([
        // fetch the owner of the blog
        client.getEntries({
          'sys.id': env.CTF_PERSON_ID
        }),
        // fetch all blog posts sorted by creation date
        client.getEntries({
          'content_type': env.CTF_BLOG_POST_TYPE_ID,
          order: '-sys.createdAt'
        })
      ]).then(([entries, posts]) => {
        // return data that should be available
        // in the template
        return {
          person: entries.items[0],
          posts: posts.items
        }
      }).catch(console.error)
    }
  }
</script>
```

We can try to move some statics to Contenful as well

**Comment by pkarw** [comment]
It can be Strapi CMS as well: https://strapi.io/

**Comment by Triloworld** [comment]
Can be GraphCMS as well: https://graphcms.com/ ?

**Comment by pkarw** [comment]
Why not? Sure

**Comment by juliankoehn** [comment]
https://github.com/juliankoehn/vsf-contentful
Should add a route Watcher validateRoute ()

https://github.com/juliankoehn/vsf-contentful-api
