### ISSUE TITLE
Add support for virtual products

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#699]
I mean very simple support: if you've got only virtual products in the cart, no shipping address should be required for the checkout. Is meant for orders of digital media/gift cards etc

**Comment by kyvaith** [comment]
This should be provided with extensible "custom action" after purchase. In example the purchased ebook should open in a web player.

**Comment by ananth-iyer** [comment]
@pkarw 	I am working on this issue

**Comment by ananth-iyer** [comment]
@pkarw 	@filrak Please review my changes and let me know if you have questions

**Comment by patzick** [comment]
Thank you @ananth-iyer :)

**Comment by ananth-iyer** [comment]
Hurray! I got my first PR merged to develop

**Comment by patzick** [comment]
Yeah, that feeling is great! ;) Keep it up, it get's even better!
