### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#7]
/src/pages/Category.vue:22 - right now it's the Exception thrown when specific category page doesn't exist; need to be fixed - with global exception handler and custom exception class OR simply showing 404

We need "no result's message" anyway - when ES return no results

@filrak

**Comment by filrak** [comment]
In case when URL does not match category name i added `     if (self.category === undefined) {
          console.error('Category not found!') 
          self.$router.push('/')
        }`

**Comment by pkarw** [comment]
OK, so it's not bat but would be rather better to add real 404 - as we're doing SSR (Server Side Rendering) - can you add some Error404 page and redirect to this one in this case? And then close :)

**Comment by filrak** [comment]
@pkarw yup i will ;)

**Comment by karolbzik** [comment]
Catch the design for the 404 page.
<img width="1440" alt="404" src="https://user-images.githubusercontent.com/18116406/33629499-9086b66a-da04-11e7-80c3-12b2f05c7b41.png">

I suggest adding links to a chat (activate the livechat or any other chat tool, I will create a separated task for integration with this kind of tool), contact page, search (open the sidebar widget) and displaying the list of products (bestsellers or recommendations).
