### ISSUE TITLE
Make separate package.json and gitignore files for themes

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#705]
Now we have one big package.json file, we should split the dependencys to core and theme-specific.

- [x] Move default theme dependencys to `themes/default/package.json`
- [x] Move catalog theme dependencys to `themes/catalog/package.json`
- [x] Add `.gitignore` for both themes with `node_modules`

**Comment by qiqqq** [comment]
@filrak @pkarw I can do this task

**Comment by pkarw** [comment]
Great!
