### ISSUE TITLE
Change Category Page to new proposal

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#715]
- [x] Change the Category Page component according to https://github.com/DivanteLtd/vue-storefront/blob/master/doc/new-core-proposal/CategoryPage.md
- [x] Make changes in default and catalog theme so they work with new core page
- [x] Remove Core Category from temporary docs 
- [x] Fill the official docs for Category Page https://github.com/DivanteLtd/vue-storefront/blob/master/doc/components/core/CategoryPage.md

**Comment by pkarw** [comment]
@akbarik how about this one Akbar?

**Comment by pkarw** [comment]
Would be good to complete this one to 1.0RC because it's a major structural change. Please be VERY VERY careful :)
