### ISSUE TITLE
Add prompt (question) to installer.js to allow user overwrite local.json file if exist

### ISSUE THREAD

**Issue by qiqqq** [DivanteLtd/vue-storefront#728]
When /config/local.json file exist and someone run installer.js, then installer breaks with info:

`ERROR
Can't create backend config.
Please check log file for details: .../vue-storefront/var/log/install.log`

but there is no information in the install.log file. This can be confusing for new users so maybe shoud we ask user if he wants to overwrite the file or add some info to logs?

I know that there is no local.json file in the repository but there is simple way to it appeared. Just have to Redis or ES installed localy on default ports, then run installer which create local.json and breaks on next step (dockerComposeUp), because Redis or ES ports are busy. In the next installation local.json file will be exist and installer breaks on step described above.

What do you think?

**Comment by pkarw** [comment]
Sure, go for it @qiqqq !

**Comment by qiqqq** [comment]
I need to analyze it because there is probably another reason for the error than not overwriting the file. I will check it.

**Comment by filrak** [comment]
Can we move it to 1.1 milestone? It's a great UX feature and we definietely need to add this but for now we need to prepare for release.

**Comment by pkarw** [comment]
This is in fact probably as easy as it looks like - I mean, the reason is that `jsonFile.write()` throws an exception when the file exists. So in case user select to overwrite the file we should just remove it just before writing the new one

**Comment by pkarw** [comment]
After fixing this issue please add `npm run installer` to the `core/scripts/postinstall.js` which will shorten the installation sequence to just one command :)

**Comment by qiqqq** [comment]
@pkarw @filrak This problem does not occur. When i moved scripts to /core/scripts/, I had some typo in code and propably this cause this problem. I tested it now few times and jsonFile.write() overwrite local.json file, there are no errors. I think this task is to close.

**Comment by pkarw** [comment]
Thanks!
