### ISSUE TITLE
Add some global helper for showing popup alerts

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#73]
For example i would love to add popup for showing alert when products with price 0 or stock qty > available is being added to cart

@karolbzik could you design such alerts please?

**Comment by karolbzik** [comment]
For all types of notifications, I suggest using consistent notification popup like in the example:
<img width="1440" alt="vue storefront - notifications" src="https://user-images.githubusercontent.com/18116406/31425545-15460ce6-ae60-11e7-87d7-bc4267ff69d2.png">

For the validation on the product cart (if there is no size, quantity or color chosen) I suggest using also a notification on the "Add to cart" button, for example:
<img width="1440" alt="vue storefront - validation on the product card" src="https://user-images.githubusercontent.com/18116406/31425756-de5da88c-ae60-11e7-8154-59dd824a270c.png">

**Comment by pkarw** [comment]
@filrak or @patrykpiston could you please prepare this modal?

**Comment by pkarw** [comment]
@filrak here you have an example call (I'll use this format):

```
          EventBus.$emit('notification', {
            type: 'error',
            message: 'Internal validation error. Please check if all required fileds are filled in. Please contact us on contributors@vuestorefront.io',
            action1: { label: 'OK', action: 'close' }
          })
```

**Comment by pkarw** [comment]
@filrak we need to finish this one as well (styling for information/warning etc)

**Comment by pkarw** [comment]
@filrak warnings are waiting for their color :)

**Comment by pkarw** [comment]
@filrak I've tried to fix it - could you just check it and close this issue if it's fine?

**Comment by filrak** [comment]
yup, it's done for a long time
