### ISSUE TITLE
Make Service Worker extendable in themes

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#730]
Now we have file called `service-worker-ext.js` - it should be placed in theme root and compiled along with main sw file .

- [x] Remove current `service-worker-ext.js` from thtmes root.
- [x] Place `service-worker-ext.js` in `theme/{themename}/` for each theme
- [x] Change pathes in webpack config according to changes
- [x] Test if it works (you can attach some console log for install event)

**Comment by pkarw** [comment]
OK, I'll take this one
