### ISSUE TITLE
[catalog] theme not displaying - wrong mixins path

### ISSUE THREAD

**Issue by anqaka** [DivanteLtd/vue-storefront#740]
In two files (`src/themes/catalog/components/theme/Search.vue`, `src/themes/catalog/components/core/blocks/Wishlist/Product.vue`) 
there is a wrong mixin's path: 
`mixins: [coreComponent('core/blocks/...')]`
webpack cannot find a module and front doesn't display

**Comment by filrak** [comment]
Feel free to assign yourself to issues you're willing to do ;)
