### ISSUE TITLE
Standarizing Core Pages API 

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#749]
Bedore 1.0RC I want to prepare new API proposals for core pages + most important Core component with @akbarik 

- [x] Home
- [x] Category
- [ ] Product
- [ ] Compare
- [ ] Search
- [ ] Product Tile component

The implementation task will be created after 1.0RC
You can find new proposals here: https://github.com/DivanteLtd/vue-storefront/tree/master/doc/new-core-proposal

**Comment by pkarw** [comment]
Product Page done!
