### ISSUE TITLE
Create list of all event across all the components and stores

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#776]

**Comment by opiumated** [comment]
Would love to have a go on this task. A description would help clear things up.

**Comment by pkarw** [comment]
Please go on!

**Comment by opiumated** [comment]
Can this go into a separate .md file? Or is there a specific place in the codebase you want this list of events?

**Comment by pkarw** [comment]
Separate file is fine. Please put it into /doc folder and link from README.MD

**Comment by pkarw** [comment]
Would be Great if you could paste some links to the reference $emits of these events by pasting the Github permalinks (click on the left gutter of any source code line on github.com and choose Copy permalink)

It will make this documentation really useful and interactive

**Comment by jablpiotrek** [comment]
I'll start it
