### ISSUE TITLE
Windows npm install fail on vue-carousel hotfix

### ISSUE THREAD

**Issue by jimhill21** [DivanteLtd/vue-storefront#783]
The vue-carousel hotfix will not allow npm install in windows regardless of the cli tried.  If this syntax will stay the same it should detect the env and adjust the syntax.  

Don't hate me because I'm on windows :stuck_out_tongue_closed_eyes:

Applying vue-carousel hotfix for https://github.com/SSENSE/vue-carousel/issues/139

'cp' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:644
    throw err;
    ^

**Comment by pkarw** [comment]
Good point :)

Could you please fix it as a first PR?:)

**Comment by pkarw** [comment]
OK, @jimhill21 I think it's fixed now: https://github.com/DivanteLtd/vue-storefront/pull/788

Could you retest and if it's fine close this issue?
The hotfix is no longer needed as vue-carousel 0.6.9 solves the original problem that hotfix was prepared for

**Comment by jimhill21** [comment]
Works great!
