### ISSUE TITLE
Sample data for "Get inspired" section on the homepage

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#79]
I will prepare a set of data for the section, it bases on photos, usernames and links from Instagram.

**Comment by karolbzik** [comment]
For this section I used the sample data from Magento2, the design is shared in the open source Figma file here - https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront---Open-Source.

<img width="1440" alt="vue storefront - homepage with the sample data from magento2" src="https://user-images.githubusercontent.com/18116406/31516182-f0db04cc-af97-11e7-9402-23e51c1b1835.png">

Please use "@Instagram" as a sample name for an account on Instagram and link it directly to the website https://www.instagram.com/.

**Comment by karolbzik** [comment]
Here you can find images exported from Figma:
<img width="360" alt="inspiration 6" src="https://user-images.githubusercontent.com/18116406/31516367-a5a63ade-af98-11e7-82c5-380157d59975.png">
<img width="360" alt="inspiration 5" src="https://user-images.githubusercontent.com/18116406/31516369-a620918a-af98-11e7-9bc7-2ed289ee0b09.png">
<img width="360" alt="inspiration 4" src="https://user-images.githubusercontent.com/18116406/31516371-a65efd26-af98-11e7-8f8f-0b6eba7bbebf.png">
<img width="360" alt="inspiration 3 mouseover" src="https://user-images.githubusercontent.com/18116406/31516374-a6912670-af98-11e7-96ea-e51f4a727ade.png">
<img width="360" alt="inspiration 2" src="https://user-images.githubusercontent.com/18116406/31516375-a6c32436-af98-11e7-97bd-c798e7feb514.png">
<img width="359" alt="inspiration 1" src="https://user-images.githubusercontent.com/18116406/31516376-a73642c2-af98-11e7-8c7b-642da5ff50f6.png">

**Comment by pkarw** [comment]
@patrykpiston please fix this PR and let's close this one!

**Comment by karolbzik** [comment]
Padding and alignment in this section need to be improved after changes in the RWD.

@patrykpiston please fix this according to the desired stage from the design.

Current stage:
![16](https://user-images.githubusercontent.com/18116406/32464374-15675b04-c340-11e7-8edc-b254f9e2fc87.png)

Desired stage from the design:
![zrzut ekranu 2017-11-06 o 22 16 41](https://user-images.githubusercontent.com/18116406/32464409-34c67f84-c340-11e7-99b9-d6f9f3abdff6.png)
