### ISSUE TITLE
vuetify no longer being recognized after 1.0RC

### ISSUE THREAD

**Issue by jimhill21** [DivanteLtd/vue-storefront#790]
After the 1.0RC branch my vuetify package is no longer working.  I have been using vuetify globally within my project and it has stopped working.

> Unknown custom element: \<v-app\> - did you register the component correctly? For recursive components, make sure to provide the "name" option."

> Unknown custom element: \<v-navigation-drawer\> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

I tried with my packages in the main package.json as well as moving my packages to the themes folder packages.json

**{{theme}}/plugins/vuetify**
```
import Vue from 'vue'

import Vuetify from 'vuetify'
import 'vuetify/dist/vuetify.css'

Vue.use(Vuetify, {
  theme: {
    primary: '#447233',
    secondary: '#63c566',
    accent: '#82B1FF',
    error: '#FF5252',
    info: '#2196F3',
    success: '#4CAF50',
    warning: '#FFC107'
  }
})
```

**Comment by jimhill21** [comment]
This issue may be related to webpack changes made prior and am closing until further investigation.

**Comment by jimhill21** [comment]
I have discovered the root of the issue.  Vuetify works great if it's in the main core/app.js but if I try to run it from the theme plugins it will not get recognized.

**Comment by filrak** [comment]
@marlass please take q look, it could be related to your webpack tweaks

**Comment by jimhill21** [comment]
@filrak @marlass I actually tried pre 1.0RC and this issue was still happening

**Comment by pkarw** [comment]
@jimhill21 did it work for you with vuestorefront before? When exactly did it stop to work?

We’ve modified the web pack config two days before release ;-)

**Comment by jimhill21** [comment]
@pkarw I apologize for a bad title on this ticket.  Initially I thought it was due to the RC but I tried checking out older versions and found it has been an issue maybe always.

I think your webpack changes are totally fine as it pertains to this issue.  This seems existing prior to the RC.

**Comment by filrak** [comment]
Have you tried importing components separately?

**Comment by filrak** [comment]
Or please provide a branch with your code so I can see whats going on ;)

**Comment by filrak** [comment]
Please take a look at core/plugins/index.js. You can find there this function:
````
Object.keys(pluginsObject).forEach(function (key) {
  Vue.use(pluginsObject[key])
})
````

So you should only export used plugin in your `{theme}/plugins/index.js`
Somethign like this:
````
import Vuetify from 'vuetify'

export {
  Vuetify
}
````
The plugins folder is meant to be used for your own plugins, not external.

In case of Vuetify config we would need some extender for app.js. I'll take care of it

**Comment by filrak** [comment]
Please take look at this branch. I made vuetify working here by creating app-extend.js file )take a look ta vuetify-test template).

I willa dd this functionality to the core

https://github.com/filrak/vue-storefront/tree/vuetify-test

**Comment by jimhill21** [comment]
I could always get it to work in the main app.js.  I was trying to use the plugins so I didn't need to modify the core. 

If we could add something like the app-extend you did to the core that would be awesome!

**Comment by filrak** [comment]
@update i added this feature
https://github.com/DivanteLtd/vue-storefront/commit/ffcf7e0775a51f86d6b834d86fa9000c0928ac8c
pull the changes please ;)

**Comment by jimhill21** [comment]
awesome!  I will close this as you provided 2 great solutions!
