### ISSUE TITLE
Add Stripe support via Payment request API

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#792]
Related to #86 
The payment method should be implemented as an extension (https://github.com/DivanteLtd/vue-storefront/blob/3d93b214720a9ae0636f6a94803d918bdf61a419/doc/extensions/Working%20with%20extensions.md)
It seems to be pretty easy on the checkout / front end. But let’s discuss with @pkarw how to integrate the status changes with the backend

**Comment by collymore** [comment]
Assign this to me, will take care of it next week.

**Comment by pkarw** [comment]
Regarding payments - please take a look at:

- #822 - any payment extension should be compliant with this "new stanard" - it will be merged in within few days but please treat it as already merged :)
- and the: https://github.com/DivanteLtd/vue-storefront/blob/master/doc/components/Extending%20UI%20from%20extensions.md

**Comment by pkarw** [comment]
@collymore do You think that's doable to add the Payment Request experimental support for credit cards and Stripe?

It would be one of the first eComm platforms supporting this new standard

**Comment by kyvaith** [comment]
Stripe imposes a fee on payments. Please implement Payment request API directly as a default payment method.
