### ISSUE TITLE
Add PayPal support 

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#793]
Related to #86 and #792 

The payment method should be implemented as an extension (https://github.com/DivanteLtd/vue-storefront/blob/3d93b214720a9ae0636f6a94803d918bdf61a419/doc/extensions/Working%20with%20extensions.md)
It seems to be pretty easy on the checkout / front end. But let’s discuss with @pkarw how to integrate the status changes with the backend

**Comment by pkarw** [comment]
https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNSetup/ - we need to add the ipn listener as a vue-storefront-api extension

**Comment by pkarw** [comment]
https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/

**Comment by pkarw** [comment]
https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/server-side-REST-integration/#set-up-the-payment

**Comment by pkarw** [comment]
Regarding payments - please take a look at:

#822 - any payment extension should be compliant with this "new stanard" - it will be merged in within few days but please treat it as already merged :)
and the: https://github.com/DivanteLtd/vue-storefront/blob/master/doc/components/Extending%20UI%20from%20extensions.md

**Comment by nacimux** [comment]
I pick this one, assign it to me please.

**Comment by pkarw** [comment]
Ok, Please go on; remember about the #822 (should be merged with core early next week)

**Comment by pkarw** [comment]
@nacimux how are things in here? :)

**Comment by nacimux** [comment]
@pkarw sorry, I have a huge pressure in my job ! i can't work on the issue before next Thuersday ! mybe you can add "Help wanted" to the issue ?

**Comment by filrak** [comment]
@nacimux we can wait, no problem

**Comment by collymore** [comment]
Hi, can you assign this to us and we'll be working on it from today.

**Comment by pkarw** [comment]
OK, @mdanilowicz will help You if You need any support.

**Comment by benyang2015** [comment]
paypal can work now or not？

**Comment by pkarw** [comment]
https://www.npmjs.com/package/vsf-payment-paypal

**Comment by pkarw** [comment]
https://www.npmjs.com/package/vsf-payment-paypal-api

**Comment by collymore** [comment]
https://github.com/develodesign/m2-paypal-payment is also required for sending orders back to Magento, we're working on removing the need for this soon.

**Comment by pkarw** [comment]
Dobe with https://www.npmjs.com/package/vsf-payment-paypal + https://www.npmjs.com/package/vsf-payment-paypal-api + https://github.com/develodesign/m2-paypal-payment
