### ISSUE TITLE
Can't build storefront npm.

### ISSUE THREAD

**Issue by hengsoheak** [DivanteLtd/vue-storefront#797]
I'm using below environment

OS: Ubuntu 16.*
Docker+Node 8.*
try to install Vue-storefront as their introduction in gitHub.
Then I got below error 

`ERROR in ./core/app.js
    Module not found: Error: Can't resolve 'theme/app' in '/home/sopheak/Desktop/vue-storefront/core'
     @ ./core/app.js 2:0-28
     @ ./core/client-entry.js
Child
    Hash: b2461c01062d79caea3f
    Time: 2300ms
                        Asset     Size  Chunks             Chunk Names
        service-worker-ext.js  3.01 kB       0  [emitted]  service-worker-ext
    service-worker-ext.js.map  3.22 kB       0  [emitted]  service-worker-ext
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vue-storefront@1.0.0-RC build:client: `cross-env NODE_ENV=production webpack --config ./core/build/webpack.prod.client.config.js --progress --hide-modules`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the vue-storefront@1.0.0-RC build:client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sopheak/.npm/_logs/2018-03-03T03_30_08_265Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vue-storefront@1.0.0-RC build: `rimraf dist && npm run build:client && npm run build:server`
npm ERR! Exit status 2
npm ERR! `

**Comment by pkarw** [comment]
Please check if there is the App.vue file within your theme folder:
```js
const themeApp = '../../src/themes/' + theme + '/App.vue'
```

**Comment by hengsoheak** [comment]
I have no Thems folder 
<img width="893" alt="screen shot 2018-03-03 at 1 41 50 pm" src="https://user-images.githubusercontent.com/812528/36931475-c6e035be-1ee8-11e8-801f-6c493b92bdbc.png">

**Comment by hengsoheak** [comment]
I've clone but why I have no this file
<img width="868" alt="screen shot 2018-03-03 at 1 45 43 pm" src="https://user-images.githubusercontent.com/812528/36931493-336fd0d6-1ee9-11e8-9b97-4ece28c46de4.png">

**Comment by pkarw** [comment]
App.vue is probably within default theme - here is the original one:
https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/App.vue

**Comment by hengsoheak** [comment]
So I have to copy from it from default to thems directory?

**Comment by hengsoheak** [comment]
Oh i check I have this file existing in default directory

**Comment by filrak** [comment]
If you want to make your own theme Just copy theme-starter and rename it. It contains all required files

**Comment by hengsoheak** [comment]
No, i didn't, It is the first time for with me Vue-storefront so I have to complete my installation but now I'm still facing the error. Let me try to reinstall and follow some tutorial

**Comment by filrak** [comment]
@hengsoheak pull last changes. The problem was with webpack aliases, now it should work ;)

**Comment by hengsoheak** [comment]
It is work as well 

Thank you very much @filrak

**Comment by filrak** [comment]
Thanks! ;)

**Comment by hengsoheak** [comment]
I'm using in Mac it is simply a little bit slow for requesting do I need to do or read some document to prevent slow request in local development and how is it going if I am planning for 2000 users active real time?

`Elasticsearch INFO: 2018-03-03T15:24:46Z
  Adding connection to https://demo.vuestorefront.io/api/catalog

Mailchimp extension registered
Google Analytics extension registered
Ensure google analytic account ID is defined in config
custom-event
Entering asyncData for Home root Sat Mar 03 2018 22:24:46 GMT+0700 (+07)
Entering asyncData for Home Sat Mar 03 2018 22:24:46 GMT+0700 (+07)
Elasticsearch DEBUG: 2018-03-03T15:24:46Z
  starting request {
    "method": "POST",
    "path": "/vue_storefront_catalog/category/_search",
    "body": {
      "query": {
        "bool": {
          "filter": {
            "term": {
              "is_active": true
            }
          }
        }
      }
    },
    "query": {
      "size": 4000,
      "from": 0,
      "sort": "position:asc"
    }
  }
  

Elasticsearch DEBUG: 2018-03-03T15:24:50Z
  Request complete

Result from ES for fe40814de8c963c837862626fc47e0b361576243 (category),  ms=4228
Elasticsearch DEBUG: 2018-03-03T15:24:50Z
  starting request {
    "method": "POST",
    "path": "/vue_storefront_catalog/product/_search",
    "body": {
      "query": {
        "bool": {
          "filter": {
            "range": {
              "visibility": {
                "gte": 3,
                "lte": 4
              }
            }
          },
          "must": {
            "match": {
              "category.name": "Tees"
            }
          }
        }
      }
    },
    "query": {
      "size": 8,
      "from": 0,
      "sort": "created_at:desc"
    }
  }
  

Elasticsearch DEBUG: 2018-03-03T15:24:53Z
  Request complete

Result from ES for 3b641691a0a00da9e11baa54ee36c35b59811b6a (product),  ms=3276
Taxes calculated server side, skipping
Elasticsearch DEBUG: 2018-03-03T15:24:53Z
  starting request {
    "method": "POST",
    "path": "/vue_storefront_catalog/product/_search",
    "body": {
      "query": {
        "bool": {
          "filter": {
            "range": {
              "visibility": {
                "gte": 3,
                "lte": 4
              }
            }
          },
          "must": {
            "match": {
              "category.name": "Women"
            }
          }
        }
      }
    },
    "query": {
      "size": 4,
      "from": 0,
      "sort": "created_at:desc"
    }
  }
  

Elasticsearch DEBUG: 2018-03-03T15:24:54Z
  Request complete

Result from ES for 7e3f323e13e1ccdce75424632358acd86bdfba36 (product),  ms=1198
Taxes calculated server side, skipping
Loading cart ...
Elasticsearch DEBUG: 2018-03-03T15:24:54Z
  starting request {
    "method": "POST",
    "path": "/vue_storefront_catalog/category/_search",
    "body": {
      "query": {
        "bool": {
          "filter": {
            "term": {
              "is_active": true
            }
          }
        }
      }
    },
    "query": {
      "size": 4000,
      "from": 0,
      "sort": "position:asc"
    }
  }
  

Result from cache for fe40814de8c963c837862626fc47e0b361576243 (category), ms=56
whole request: 8796ms
Elasticsearch DEBUG: 2018-03-03T15:24:55Z
  Request complete
`

**Comment by pkarw** [comment]
Seems like slow network connection to demo.vuestorefront.io used as a backend
Please reinstall VS and choose the option to install vue-storefront-api backend locally it will speed up everything

We’re using macOS for development and average response time is always <0.5s for the whole request
