### ISSUE TITLE
Support for nested categories

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#8]
How do we support nested categories in navigation? Right now it's not supported (/src/themes/default/components/core/blocks/SidebarMenu/SidebarMenu.vue:16 need to be changed) - the categories object already consist of hierarchical data:

```json
{  
  "_index":"vue_storefront_catalog",
  "_type":"category",
  "_id":"29",
  "_version":1,
  "_score":1,
  "_source":{  
    "id":29,
    "parent_id":2,
    "name":"Promotions",
    "is_active":false,
    "position":6,
    "level":2,
    "product_count":0,
    "children_data":[  
      {  
        "id":30,
        "parent_id":29,
        "name":"Women Sale",
        "is_active":true,
        "position":1,
        "level":3,
        "product_count":224,
        "children_data":[  

        ]
      },
      {  
        "id":31,
        "parent_id":29,
        "name":"Men Sale",
        "is_active":true,
        "position":2,
        "level":3,
        "product_count":39,
        "children_data":[  

        ]
      },
      {  
        "id":32,
        "parent_id":29,
        "name":"Pants",
        "is_active":true,
        "position":3,
        "level":3,
        "product_count":247,
        "children_data":[  

        ]
      },
      {  
        "id":33,
        "parent_id":29,
        "name":"Tees",
        "is_active":true,
        "position":4,
        "level":3,
        "product_count":192,
        "children_data":[  

        ]
      }
    ],
    "tsk":1505573191094
  }
}


```

**Comment by pkarw** [comment]
@filrak it seems it need to be styled on the frontend - could you do that? And then we need to change /vue-storefront/src/store/modules/catalog.js:61 (loadCategories method) to:

```js
 return new Promise((resolve, reject) => {
      client.search({
        index: config.elasticsearch.index, // TODO: add grouped prodduct and bundled product support
        type: 'category',
        q: qr,
        '_sourceInclude': ['name', 'position', 'id', 'parent_id', **'children_data'**]

      }).then(function (resp) {
        commit(types.CATALOG_UPD_CATEGORIES, resp)
        resolve(resp)
      }).catch(function (err) {
        reject(err)
      })
    })
```

**Comment by pkarw** [comment]
+ add is_active = true to filter @pkarw

**Comment by filrak** [comment]
@pkarw of course i will ;) As far as i remember Karol said that current graphics are as simple as possible. That's the reason why there are no nested categories yet but they should be implemented later and according to what you wrote

**Comment by pkarw** [comment]
So right now we should display only the 1. level and thats all? @filrak @karolbzik

**Comment by filrak** [comment]
@pkarw according to design and what @karolbzik said - yup

**Comment by pkarw** [comment]
Added to the sidebar but with some minor issue to be fixed (#42). @filrak @karolbzik we need some design idea for this - how to present the subs?

Right now it's quite awkward
![zrzut ekranu 2017-10-06 09 02 29](https://user-images.githubusercontent.com/211899/31266667-1f2e8d30-aa75-11e7-8062-d1d8ebf81028.png)
:

**Comment by karolbzik** [comment]
https://github.com/DivanteLtd/vue-storefront/issues/54

**Comment by karolbzik** [comment]
<img width="1440" alt="vue storefront - sidebar menu" src="https://user-images.githubusercontent.com/18116406/31318988-7b0ffe26-ac5b-11e7-8d74-31c63367c70e.png">
<img width="1440" alt="vue storefront - sidebar menu with nested categories" src="https://user-images.githubusercontent.com/18116406/31318990-7dcb0214-ac5b-11e7-87d9-cfa28b44eac4.png">
<img width="360" alt="sidebar menu my account on mobile" src="https://user-images.githubusercontent.com/18116406/33962336-84ccfa7a-e051-11e7-96ef-6e51280e6f28.png">
<img width="360" alt="sidebar menu on mobile" src="https://user-images.githubusercontent.com/18116406/33962338-8578f262-e051-11e7-9096-4aed4fb73fa2.png">

**Comment by pkarw** [comment]
Related to: #391

**Comment by pkarw** [comment]
@filrak you should take care of this one as it's kind of core change to the navigation

**Comment by pkarw** [comment]
Marvelous job @mercs600!
