### ISSUE TITLE
Add the set of links to the static pages in the sidebar menu

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#80]
The set needs to be added below the categories, as a secondary navigation, visible only on the view with the general categorioes. 
<img width="299" alt="zrzut ekranu 2017-10-11 o 08 57 48" src="https://user-images.githubusercontent.com/18116406/31426108-4d6edd94-ae62-11e7-94bf-f696e24c57bf.png">

Let's link sites from the secondary navigation to the static pages for now.

**Comment by pkarw** [comment]
this is related to #81

**Comment by karolbzik** [comment]
@patrykpiston here you can find an example of a static page, it's really simple for now ;).
Please use a random lorem ipsum content to every page.

<img width="1440" alt="vue storefront - static page" src="https://user-images.githubusercontent.com/18116406/31515508-a6ef3538-af95-11e7-8152-a680aa0ea848.png">
