### ISSUE TITLE
Install Vue-storefront on Ubuntu16.4 VmWare machine

### ISSUE THREAD

**Issue by hengsoheak** [DivanteLtd/vue-storefront#802]
Dear Vue-Storefront,

I'm testing vue-storefront with Ubuntu16.4 as your tutorial after then I got below error.

`ERROR                                                                                         │
│                                                                                               │
│ Can't start docker in background.                                                             │
│                                                                                               │
│ Please check log file for details: /home/sopheak/Documents/vue-storefront/var/log/install.log `

Messages in Log files

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'installer' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'preinstaller', 'installer', 'postinstaller' ]
5 info lifecycle vue-storefront@1.0.0-RC~preinstaller: vue-storefront@1.0.0-RC
6 info lifecycle vue-storefront@1.0.0-RC~installer: vue-storefront@1.0.0-RC
7 verbose lifecycle vue-storefront@1.0.0-RC~installer: unsafe-perm in lifecycle true
8 verbose lifecycle vue-storefront@1.0.0-RC~installer: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/sopheak/Documents/vue-storefront/node_modules/.bin:/home/sopheak/bin:/home/sopheak/.local/b
in:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle vue-storefront@1.0.0-RC~installer: CWD: /home/sopheak/Documents/vue-storefront
10 silly lifecycle vue-storefront@1.0.0-RC~installer: Args: [ '-c', 'node ./core/scripts/installer' ]
11 silly lifecycle vue-storefront@1.0.0-RC~installer: Returned: code: 1  signal: null
12 info lifecycle vue-storefront@1.0.0-RC~installer: Failed to exec installer script
13 verbose stack Error: vue-storefront@1.0.0-RC installer: `node ./core/scripts/installer`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid vue-storefront@1.0.0-RC
15 verbose cwd /home/sopheak/Documents/vue-storefront
16 verbose Linux 4.13.0-36-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "installer"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue-storefront@1.0.0-RC installer: `node ./core/scripts/installer`
22 error Exit status 1
23 error Failed at the vue-storefront@1.0.0-RC installer script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

`

**Comment by pkarw** [comment]
Thanks for the report. It seems like you don’t have the docker installed

**Comment by jacintoo** [comment]
I have similar issue, and docker is installed on a fresh ubuntu server. You'll need to add yourself in the group:
sudo usermod -a -G docker <you>



and re-login.
