### ISSUE TITLE
Add open source / headless CMS integration

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#804]
Related to #697 

We should select one of the most popular headless CMSes (https://headlesscms.org/) - would be great if it's based on Node.js for coherent technological stack with VS and implement an integration.

At first stage it can be just the content-block integration, then we can think of building the navigation and other meta data editors based on JSON API provided by such CMS

**Comment by karolbzik** [comment]
@pkarw I think we need to discuss and clarify the direction for the content management (static pages and banners).

**Comment by filrak** [comment]
@karolbzik there is a task for this with Wordpress integration https://github.com/DivanteLtd/vue-storefront/issues/812

**Comment by pkarw** [comment]
https://github.com/netlify/netlify-cms
https://strapi.io/demo

**Comment by kyvaith** [comment]
Also, please refer to my proposal https://github.com/DivanteLtd/vue-storefront/issues/812#issuecomment-380364586

**Comment by pkarw** [comment]
https://github.com/Agence-DnD/vue-storefront-prismic-connector

**Comment by pkarw** [comment]
Well, it has been already done in the mean time: https://github.com/develodesign/vsf-wp :-)
