### ISSUE TITLE
One-click deployment to PaaS

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#805]
There is an idea to use the https://zeit.co/now#frequently-asked-questions to build a multi cloud hosting for VS

I imagine the process like:
- you're developing the VS locally,
- at some point enters the command like "vsf live",
- you need to provide the Magento2 auth keys,
- all other stuff is published by the "vsf" management tool automatically - like zeit now does for the general nodejs.apps

Does it make sense for you? I'm just curious. The node.js production deployments can be a little bit complicated for the newcomers, this is the reason I'm just wondering if it makes sense to make the process more straightforward.

**Comment by EliasKotlyar** [comment]
We could also use google firebase. Its basically the same as zeit(as far as i can compare it), and its hosted by google.

**Comment by Igloczek** [comment]
Maybe something like this?
https://devcenter.heroku.com/articles/heroku-button

**Comment by pkarw** [comment]
Deploy to Heroku is cool -> https://github.com/strapi/strapi

It sounds to me.

**Comment by 2monkey** [comment]
I think firebase is a great solution, there we have the native push notifications and all other stuff for progressive web apps.

**Comment by pkarw** [comment]
OK, so the preferred option is with Heroku.

https://devcenter.heroku.com/articles/heroku-button
https://github.com/strapi/strapi -> here you have "Deploy to heroku" button included

Challenges:
1. We need to have both: vue-storefront and vue-storefront-api installed by one click
2. Both projects are using Redis and ElasticSearch local instalations - the good news is that we can switch to Heroku add-ons; ES 5.2+ is expected
3. Then we need to deal with the configs. By default, the installer.js script (https://github.com/DivanteLtd/vue-storefront/blob/master/core/scripts/installer.js) is generating the conf/local.json.

We're using https://www.npmjs.com/package/config for config management - so the values can be overridden by ENV variables (https://github.com/lorenwest/node-config/wiki/Environment-Variables) - `$ export NODE_CONFIG='{"Customer":{"dbConfig":{"host":"customerdb.prod"}}}'`

4. The full procedure seems like: https://github.com/DivanteLtd/vue-storefront/blob/311ffe34bb2f011962cce7c96c3c63160aa19aa8/core/scripts/installer.js#L473

**Comment by pkarw** [comment]
Another option is Digital Ocean: https://www.digitalocean.com/products/one-click-apps/django/

**Comment by pkarw** [comment]
https://www.digitalocean.com/community/tutorials/how-to-create-digitalocean-snapshots-using-packer-on-ubuntu-16-04

**Comment by tobiasdalhof** [comment]
Google Cloud Launcher is also another option: https://console.cloud.google.com/launcher

**Comment by EatPrayCode** [comment]
This project seems so powerful and cool.
Thinking of trying out vuestorefront for the next project.

Did anyone create such a build setup (one-click deployment on a paas)?
