### ISSUE TITLE
wrong product and customer details are  added in magento 2 backend

### ISSUE THREAD

**Issue by ganeshr28** [DivanteLtd/vue-storefront#806]
i having issue wrond product name and customer details is added in magento 2 backend

vuestorefont 
![screenshot from 2018-03-05 15-33-32](https://user-images.githubusercontent.com/32222445/36969402-64bebd52-208b-11e8-96d8-b3038b46ffb7.png)

![2](https://user-images.githubusercontent.com/32222445/36969425-76a6b3f8-208b-11e8-8597-9804928be747.png)

check the order no its 15

![3](https://user-images.githubusercontent.com/32222445/36969438-7e5c6e12-208b-11e8-8c8f-5a8c7f126ff0.png)
*magento 2 backend sales tab* check the order no its 15

![4](https://user-images.githubusercontent.com/32222445/36969534-bf3962e6-208b-11e8-8211-64b295c4a01b.png)

**Comment by pkarw** [comment]
Any idea why "ganesh rames" exactly this string could be used for the customer name? Haven't you placed a similar order with this customers details before?

**Comment by pkarw** [comment]
I've just tested it on demo.veustorefront.io and it works fine - could you please test it there as well? You should be able to check the data Magento stored with the order by checking the e-mail provided 
![screenshot 2018-03-05 11 30 24](https://user-images.githubusercontent.com/211899/36970363-9d7c8bec-2068-11e8-8ed4-82b22184af31.png)
![screenshot 2018-03-05 11 29 25](https://user-images.githubusercontent.com/211899/36970364-9d9bbec2-2068-11e8-8e24-f4544a6ff44f.png)

**Comment by ganeshr28** [comment]
@pkarw  yes i have placed with "ganesh remesh" before but form vue storefront when add new name like above it dosnt take that name evey time it takes name which i have entered earlier

**Comment by pkarw** [comment]
vue storefront is queuing the orders and it is possible that the new order you placed was transferred to the magento later on - could you please check it?

**Comment by ganeshr28** [comment]
how can i check wheather my order is queued 
can you tell me how can i remove all database value and start fresh and then retrive the product details form magento 2

**Comment by pkarw** [comment]
@ganeshr28 you need to use https://github.com/DivanteLtd/mage2vuestorefront; details: https://medium.com/@piotrkarwatka/vue-storefront-how-to-install-and-integrate-with-magento2-227767dd65b2

The database is stored in ES - so you can run some GUI against the Elastic Search to manage the index
The order queue is managed by KUE https://github.com/Automattic/kue - please find some more info there on how to clear the queue etc

**Comment by ganeshr28** [comment]
@pkarw thanks i solved the issue by doing the following  in mage2vuestorefront :
in src folder 
node --harmony cli.js fullreindex
followed by 
node cli.js taxrule
node cli.js attributes
node cli.js categories
node cli.js productcategories
node cli.js products

thanks once again @pkarw :+1:
