### ISSUE TITLE
Google - Payment Request API

### ISSUE THREAD

**Issue by 2monkey** [DivanteLtd/vue-storefront#809]
How about this option?
With this option implemented, you dont need a user account (like PayPal Express).

https://developers.google.com/web/fundamentals/payments/deep-dive-into-payment-request

![pr-top](https://user-images.githubusercontent.com/8565430/37020311-a24a1988-211b-11e8-973a-78f2a6327dc7.png)

**Comment by pkarw** [comment]
#86 is all about that :) So yeah, it's cool we should have this an a option, implemented using extensions to VS. Are you willing to build such extension?

**Comment by 2monkey** [comment]
Yeah of course.

**Comment by pkarw** [comment]
@2monkey @MikeSheward seems to work on this in #86 please contact directly to avoid feature duplication :)

**Comment by 2monkey** [comment]
Ok, i will contact him.

**Comment by pkarw** [comment]
I'll close this one as a duplicate :)
