### ISSUE TITLE
Add links to the navigation in the footer

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#81]

**Comment by pkarw** [comment]
Yesterday we decided to assign this to Patryk

**Comment by pkarw** [comment]
@patrykpiston when we finish this one we've got pretty nice looking look&feel
As we sad - we can provide static files like route which is loading *.md files from /resource folder:

/s/terms-conditions -> /resource/terms and condditions.js where you have:

```json
{
title: "Terms and condtions",
content: "Markdown content"
}
```

Does it make sense? The title is required for example for <meta title and so
