### ISSUE TITLE
Firefox - > Product keeps added in cart after removing them

### ISSUE THREAD

**Issue by HRR1337** [DivanteLtd/vue-storefront#810]
Hi there,

Issue: On firefox @ demo.vuestorefront.io

Add products to cart - > Remove them via the minicart - > Hit refresh. (or ctrl - f5)
Message pops-up: products added to cart (and products are added to cart). 

Outcome should be: just refresh the page, and dont add products to cart.

Thanks,

HRR

**Comment by HRR1337** [comment]
Small update - its also on Chrome

**Comment by pkarw** [comment]
I found some issue on Firefox regarding JSON files support OR serviceworker?, we'll investigate it

**Comment by pkarw** [comment]
This is service worker misconfirugration. FIxing it

**Comment by pkarw** [comment]
@HRR1337 fixed and updated on the demo.vuestorefront.io - please flushh the application storage or test in the incognito mode because it required the update of Service Worker

**Comment by glevhen** [comment]
@pkarw have the same issue for my project, could you provide walkthrough how to fix it?

**Comment by pkarw** [comment]
It's been fixed with the https://github.com/DivanteLtd/vue-storefront/pull/2828 - so the changes have been already merged into `develop` branch (1.10-rc1) - You can take it from ther
