### ISSUE TITLE
Create Wordpress Integration extension

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#812]
It would be great to have posibility to connect wordpress for static sites and blog posts. The extension should provide some injectable components (as a mixins) with very basic functionalities like:
- single post (id via props)
- posts list 
- comments for post (id via props)

Also the posts and templates should be cached for offline-ready experience.

**Comment by filrak** [comment]
We can also think about using contentful for this

**Comment by kyvaith** [comment]
From my perspective would be better to implement #896 for building views and integrate https://github.com/TryGhost/Ghost for blogging.

**Comment by dimasch** [comment]
Related to #2028

**Comment by Zyles** [comment]
Use the wordpress rest API for this. So you can use WP as a headless CMS.

**Comment by Cyclonecode** [comment]
This was actually on my TOODO list =)

**Comment by pkarw** [comment]
Well, it has been already done in the mean time: https://github.com/develodesign/vsf-wp :-)
