### ISSUE TITLE
Messenger - Customer Chat-Plugin

### ISSUE THREAD

**Issue by 2monkey** [DivanteLtd/vue-storefront#818]
How about this? 

https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin

![23423329_322601184884475_7886446887677460480_n](https://user-images.githubusercontent.com/8565430/37093810-ef4b65de-2210-11e8-9e37-5b8838e7f9b1.png)

**Comment by pkarw** [comment]
Would be great to have FB messenger integration, go for it (it should be implemented as an extension)

**Comment by filrak** [comment]
It will be also cool for demo purposes ;)

**Comment by karolbzik** [comment]
@2monkey great suggestion, will you work on it? Do you know if this widget will have any scenario for off-line? It would be great to have on-line / off-line stages with this widget. Eg. in Drify or LiveChat there are "we are currently off-line" stages.

**Comment by 2monkey** [comment]
@karolbzik yeah you can use the offline event - to access typical info messages.

**Comment by pkarw** [comment]
@2monkey I Just wanted to ask if you’re on this topic maybe?

**Comment by 2monkey** [comment]
@pkarw yeah, will create a github for this extension. I think on the weekend or begin of the next week.
The PHP Code is already finished.

**Comment by 2monkey** [comment]
@pkarw what is the hook to bind a script tag (like google analytics tag) ?
[This](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/components/Extending%20UI%20from%20extensions.md) is the only doc that i found.

**Comment by pkarw** [comment]
I'm affraid we don't have this kind of event yet; right now we do have per-page events, like product-after-created etc. You need something more general. Please take a look at vue-analytics module which is used by VS for analytics support, it can be kind of inspiration how to embed such a permanent element

**Comment by pkarw** [comment]
Oh, and of course if needed please add your own event hook and create a PR to the core, no problem

**Comment by 2monkey** [comment]
Alright, thank you 👍

**Comment by allozaur** [comment]
@pkarw @2monkey @filrak we have developed an Out-of-the-box solution and will publish it in matter of days as an Open Source Vue Storefront module :)

![Zrzut ekranu 2019-04-6 o 18 50 10](https://user-images.githubusercontent.com/37627284/55672580-d698ee80-589c-11e9-93ca-ce2358b2b7b3.jpg)

**Comment by Hackbard** [comment]
@allozaur  is it published? Then the ticket can be closed?

**Comment by daksamit** [comment]
That's it - https://github.com/2monkey/vue-storefront-fb-messenger ?

**Comment by filrak** [comment]
It is https://github.com/BitBagCommerce/SyliusVueStorefrontPlugin
