### ISSUE TITLE
Add basic annimations

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#82]
Let's add basic animations for components:
- Sidebar cart
- Sidebar menu
- Sidebar search widget
- Mouseover for product block
- Notification block
- Slider
- Touch feedback animation

In animations let's stick to patterns from the Material Motion https://material.io/guidelines/motion/material-motion.html.

**Comment by patrykpiston** [comment]
Since the animations have been added and are going to be added gradually with new components I'm closing this one.
