### ISSUE TITLE
Products are not synchronized when i m used in mobile(Offline Mode and online mode both)

### ISSUE THREAD

**Issue by anilahy** [DivanteLtd/vue-storefront#824]
I have done integration the vue-storefront with the magento2. when I am used the website from mobile then the products are not synchronized alert popup is shown.

need a help

**Comment by pkarw** [comment]
It's hard to say without more details. What does it mean you've integrated the site (which steps did you execute)? What works on desktop vs mobile? Could you provide the screenshots please? Any errors in the console?

**Comment by anilahy** [comment]
Hello Piotr Karwatka,

I have integrated the Vue storefront and magento2(local machine) successfully.
The website is working fine on desktop but when I m open the website  
in mobile then products are not synchronised is shown. 

I have followed the steps which are given in this   
link: https://medium.com/@piotrkarwatka/vue-storefront-how-to-install-and-integrate-with-magento2-227767dd65b2

DESKTOP SCREENSHOT

CONSOLE SCREENSHOT

MOBILE SCREENSHOT

why are products not synchronized when I have used the website on mobile? 

Thanks and Regards,  Anil Kale

Quoting Piotr Karwatka <notifications@github.com>:

**Comment by pkarw** [comment]
The screenshots haven't been attached properly, please resend

**Comment by pkarw** [comment]
Thanks for the details on Drift; here it's the video showing this issue in action: https://drive.google.com/file/d/1NUWHNCvjyHw9I0N7KvZdwS2kJWPEoQ3F/view 

@anilahy could you please send us the output of Chrome Devloper's console please?

I'll investigate this issue in the next few days

**Comment by pkarw** [comment]
Thanks for reporting this issue! Fixed with https://github.com/DivanteLtd/vue-storefront/pull/861

Please pull the most recent changes from "develop" branch: https://github.com/DivanteLtd/vue-storefront/tree/develop
