### ISSUE TITLE
Push Notifications - Extension

### ISSUE THREAD

**Issue by 2monkey** [DivanteLtd/vue-storefront#825]
Extension worthy? 
Im working currently on Payments API and FB Messenger Integration, but i think this feature is a must.

https://onesignal.com/

![unbenannaat](https://user-images.githubusercontent.com/8565430/37196754-4f94ef42-2378-11e8-808e-75514d3f433c.PNG)

**Comment by pkarw** [comment]
yes, it's cool!

Regarding payments - please take a look at:
- https://github.com/DivanteLtd/vue-storefront/pull/822 - any payment extension should be compliant with this "new stanard" - it will be merged in within few days but please treat it as already merged :)
- and the: https://github.com/DivanteLtd/vue-storefront/blob/master/doc/components/Extending%20UI%20from%20extensions.md

**Comment by filrak** [comment]
I this we shoul implement native notifications as it is possible with existing vue-storefront-api as a push server. There is no need to use 3rd partys

**Comment by 2monkey** [comment]
@filrak yeah native is the best option, but currently the only native options for that are things like firebase.

**Comment by filrak** [comment]
@2monkey, nah we can implement it using our API server without any problems

**Comment by 2monkey** [comment]
@filrak that sounds great, so we need a backend extension for sending and analytics. Is it right? or do you want to use CLI for sending?

**Comment by filrak** [comment]
No, we need backend with exposed endpoint for sending push notifications. We shouldn't stick to 3rd partys like Firebase since they require additional steps to use VS (like gnerating Firebase config keys). We can easly do it in a native way. Do you want to take care of it @2monkey ?

**Comment by 2monkey** [comment]
@filrak  yeah after the FB Messenger and  Payments API Integration.

**Comment by filrak** [comment]
Amazing, thanks!

**Comment by michhy** [comment]
Hi all,
Looking forward for any updates on the push notification, no matter via 3rd party on build in.
Many thanks for the hard work!
