### ISSUE TITLE
Improve modals/pop-ups animations

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#830]
We need to improve animation for modals.
TODO - 1) check good practices for material motion 2) describe improvements for modals.

**Comment by jahvi** [comment]
I'd like to give this one a go if that's ok

**Comment by pkarw** [comment]
Sure, please propose sth :)

**Comment by jahvi** [comment]
I'm giving this a go at #1859, any feedback is appreciated 🙂
