### ISSUE TITLE
Design and change favicon

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#836]
We need to design and change favicon for the main template.

**Comment by StasiekDivante** [comment]
favicon
[favicon.ico.zip](https://github.com/DivanteLtd/vue-storefront/files/2025543/favicon.ico.zip)

**Comment by pkarw** [comment]
This faivicon is not transparent ;( https://www.dropbox.com/s/daqqjq2hkc6zt5y/Screenshot%202018-06-25%2022.47.54.png?dl=0 @StasiekDivante @qiqqq
