### ISSUE TITLE
Design Track my order page

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#837]
We need to design and develop "track my order" page for use scenarios:
- As a Customer, I can check a status of my order (status in store, status in delivery) by typing the number of my order in form;
- As a Customer, I can check a status of my order without login.

The base for that page is here https://demo.vuestorefront.io/order-tracking

**Comment by fancydev18** [comment]
@pkarw Why was this closed, please?

**Comment by pkarw** [comment]
@fancydev18 this feature was out of the standard eCommerce features set we are able to add to the core - it requires additional integrations etc. it’s a great idea for community / 3rd party module to be published on our marketplace!

**Comment by mariusa** [comment]
@pkarw thanks, makes sense

**Comment by fancydev18** [comment]
@pkarw Thanks, makes sense
