### ISSUE TITLE
Test and improve UX at Compare products page

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#838]
We need to test the page on mobile screens and unify typography, colors and styling for tables.https://demo.vuestorefront.io/compare.

TODO:
1. Test https://demo.vuestorefront.io/compare on mobile screens and desktop, list adjustments
2. Select adjustments & discuss them 
3. Apply adjustments

**Comment by talalus** [comment]
I can continue on this

**Comment by pkarw** [comment]
OK!

**Comment by talalus** [comment]
@pkarw maybe something like this https://codyhouse.co/demo/products-comparison-table/index.html ?

**Comment by pkarw** [comment]
I don't have an opinion on this :) @karolbzik?

**Comment by StasiekDivante** [comment]
@talalus that table looks good, lets go with it

**Comment by StasiekDivante** [comment]
![compare products](https://user-images.githubusercontent.com/37068687/37284047-69b23f54-25fa-11e8-8e45-c428c5bcaf03.png)
I made you design for compare page, hope that will be helpful

**Comment by StasiekDivante** [comment]
if there are more than 2 products table should scroll horizontally on its own

**Comment by pkarw** [comment]
@talalus how about this one? :)

**Comment by talalus** [comment]
I'll work on it in this weekend

**Comment by pkarw** [comment]
@talalus how about this ticket?

**Comment by talalus** [comment]
Sorry for the delay, I'm still on it, I was in total miss in the past few weeks applying for master. 
50% is done
