### ISSUE TITLE
Integration with Emarsys 

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#842]
I have a suggestion to consider integration with Emarsys - they are a great marketing automation engine for enterprise eCommerce companies. The integration could contain 1) e-mail 2) tracking on the web 3) recommendation engine.

If someone would be interested - I can arrange a demo account and configure the tool so we could have eCommerce extended with this robust eCommerce tool used only by enterprise companies.

**Comment by shkodasv** [comment]
@karolbzik do you have any progress here? I am interested in this integration too
