### ISSUE TITLE
Shopify integration

### ISSUE THREAD

**Issue by admench** [DivanteLtd/vue-storefront#843]
Hi,

Love the platform. Quick question, is it possible to integrate with the shopify api? 

When I heard your talk at this at the London vuejs meetup you said it was possible to integrate with many ecommerce platforms, just wondered if you could respond with your take on this?

Many thanks

**Comment by filrak** [comment]
Yes  it's possible without any problems but shopify connector is not created yet. Currently we have working connectors for magento 2, pimcore and magento 1 on the way. Maybe you will take care of this? You can find tutorials on how to integrate any platform in our README

**Comment by ryanhmaas** [comment]
Is that tutorial up to date? The file structure of the most recent build seems substantially different.

Thanks!

**Comment by pkarw** [comment]
@ryanhmaas not sure which exactly? The vue-storefront code structure changed before 1.0RC, maybe this is the reason?

**Comment by admench** [comment]
Thanks @filrak - I don't think I quite have the skills to build a connector yet, but may in the future! In the meantime I am making a nuxt.js implementation using the Shopify Javascript SDK.

**Comment by filrak** [comment]
@admench the integration is not that hard, maybe you should give it a a try at least with basic stuff (we can help with the rest) before creating everything from scratch by yourself - here is a tutorial on how to do the integration https://medium.com/@piotrkarwatka/how-to-connect-3rd-party-platform-to-vue-storefront-df9cb30779f6 . In case of any questions @pkarw will be happy to help you ;)

**Comment by Bek81** [comment]
Hi all,
are there any news regarding the connector with Shopify?

Thanks a lot.

**Comment by schellenbergk** [comment]
bump :)

**Comment by lgs** [comment]
+1 bump

**Comment by agcty** [comment]
+1

**Comment by janmyszkier** [comment]
To be honest I do not share @filrak thoughs on "without any problems" as I already see upcoming issues that would have to be fought with. Example:
https://help.shopify.com/en/api/reference/products/product-variant
this is representation of the "child" product, which is nowhere close to magento format (and what vueSF currently expects). there's no telling what color it is, and there's no telling it's actually a variant based on color.

To have this convert-able, whole Shopify store would have to be probably made based on metafields (to keep extra data we currently need). That's SOME work. Some data conversion needs to be made first before pushing things to ES. Same goes for making Shopify cart working using the current code (not possible without any problems, unless you're OK with replacing a lot of code with non-vue-storefront one). The easier way is middleware, the way that makes sense is getting storefront-api done first.
After the shared e-commerce standard of storefront-api is made and production-ready we can try to implement this to not reinvent the wheel.

**Comment by esklein** [comment]
Agree with @janmyszkier feedback on this. VueStorefront entire model is tied too tightly to Magento model. The storefront api and next gen architecture might provide approaches to handle this, but IMO mode should be more generic and extensible to truly support multi-platform in a real world environment.

**Comment by filrak** [comment]
It will be done within Vue Storefront Next and already started by Aureate Labs ;)

**Comment by christianechevarria** [comment]
> It will be done within Vue Storefront Next and already started by Aureate Labs ;)

Hi, following up on this, tried looking for Vue Storefront Next and ended up back at this repo since it seems like Vue Storefront Next was [archived](https://github.com/DivanteLtd/next)?

Just wanted to check to see if there was anything to look at for creating / facilitating the Shopify integration before attempting to build it out on a new repo. It seems like several people have needed this so that basically gives me the confidence to start the project and potentially acquire some collaborators from the community.

Any info would be greatly appreciated @filrak

**Comment by agcty** [comment]
@filrak Will VS support Shopify anytime soon? Can't find anything at all in the documentation / blog posts or even the Vue Storefront Next repo.

If it really will be available in the Next release adding "[WIP] Shopify" would be of great help for other people asking themselves if Shopify will be released:
![image](https://user-images.githubusercontent.com/12101091/83939427-4aa28f80-a7dd-11ea-8b21-7afa715761c9.png)

**Comment by CavalcanteLeo** [comment]
add this official support, please

**Comment by filrak** [comment]
@CavalcanteLeo @agcty https://github.com/DivanteLtd/vue-storefront/pull/4580 its coming within a week or two ;)

**Comment by BornaSepic** [comment]
Just wanted to check in how this is coming along?
We're considering using Vue storefront for a fairly large project and Shopify integration is definitely a must for us.

Thanks

**Comment by filrak** [comment]
@BornaSepic few polishments have left for the docs before we can release the beta in the next week sorry it took us a bit longer

**Comment by bloodf** [comment]
@admench Sorry for the long delay,

We now have a stable Shopify integration with the Vue Storefront 2

https://github.com/vuestorefront/shopify

You can use it :)

Please check our announcement blog post at https://blog.vuestorefront.io/unlock-limitless-possibilities-with-shopify-integration/
