### ISSUE TITLE
Add dynamic port allocation

### ISSUE THREAD

**Issue by Igloczek** [DivanteLtd/vue-storefront#849]
The way how Vue folks handle it - https://github.com/vuejs-templates/webpack/pull/913

For those who run into `Error: listen EADDRINUSE :::3000` before it will be fixed - just run `killall node` and you will be fine 😉

**Comment by pkarw** [comment]
@Igloczek this is good idea with the port-scanner, thanks

**Comment by MikeSheward** [comment]
This is a good idea, i have come across this need myself.
