### ISSUE TITLE
Cleanup release tags

### ISSUE THREAD

**Issue by Igloczek** [DivanteLtd/vue-storefront#855]
All release tags should follow same format, for example https://git-scm.com/book/en/v2/Git-Basics-Tagging
So we should change:
```
0.2.1-alpha -> v0.2.1-alpha.0 or v0.2.0-alpha.1
0.3.0 -> v0.3.0
0.4.0 -> v0.4.0
1.0RC -> v1.0.0-rc.0
v0.2-alpha -> v0.2.0-alpha.0
```
Also will be nice to register for the pre-release program - https://github.com/prerelease/agreement

**Comment by pkarw** [comment]
Hmm. Renaming past releases and tags on Github is not working as smoothly as I've thought; just tried to rename 0.2.1-alpha -> v0.2.1-alpha.0

without any success :) Could You try this @Igloczek or @filrak ?

**Comment by pkarw** [comment]
To not mess up I suggest just moving to the semantic versioning (the difference is basically just the "v" prefix and then numeric postfix for -alpha, -rc releases) with the next release; wdyt @Igloczek ?

**Comment by pkarw** [comment]
I've created the semantic copies of tags - https://www.dropbox.com/s/ssk7sr47wyyxp43/Screenshot%202018-03-18%2013.50.00.png?dl=0

But by some reason they are not displayed in the Github https://github.com/DivanteLtd/vue-storefront/tags -> so I'm not able to modify the releases ..

**Comment by pkarw** [comment]
OK! The reason was pretty silly :) Wrong origin :) 

Now it's fixed!
