### ISSUE TITLE
Integration with Intercom

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#858]
It would be great if someone could develop an integration with https://www.intercom.com/.
This tool contains both livechat and marketing automation.

**Comment by kszewczyk** [comment]
I'll take that

**Comment by pauluse** [comment]
@kszewczyk did you by any chance already make a start on this? Otherwise we'd like to pick up this feature request for the Hackathon @ Amsterdam

**Comment by kszewczyk** [comment]
You can take it

**Comment by MikeSheward** [comment]
I'll sort this one.

**Comment by pkarw** [comment]
https://github.com/develodesign/vsf-intercom

**Comment by MikeSheward** [comment]
@pkarw Thanks, i forgot to link it here too !
