### ISSUE TITLE
Shouldn't we emplement payment-requests spec?

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#86]
https://www.w3.org/TR/payment-request/

**Comment by pkarw** [comment]
https://developers.google.com/web/fundamentals/payments/deep-dive-into-payment-request#paymentrequest_shim

**Comment by pkarw** [comment]
https://stripe.com/docs/payment-request-api

**Comment by pkarw** [comment]
Go @BlitZ-UK Go! :)

**Comment by filrak** [comment]
@BlitZ-UK maybe you can take care of this one?

**Comment by BlitZ-UK** [comment]
Sure! With Stripe integration it'll be built right in anyway (to some extent). But in a future milestone it would be good to add this support for manual Payment Request API integration.

**Comment by pkarw** [comment]
@MikeSheward  -> @2monkey is willing to help with this - as commented on #809

**Comment by pkarw** [comment]
@MikeSheward not sure, but this: https://github.com/DivanteLtd/vue-storefront/blob/master/doc/data/How%20to%20get%20Magento2%20order%20id%20after%20sync.md

May be interesting and helpfull. We're now storing the resulting Magento2 order id's in the vue-storefront-api redis cache:

https://github.com/DivanteLtd/vue-storefront-api/blob/0acfc471534c9f0abeaf5c263719e08118a96dcc/src/worker/order_to_magento2.js#L215

and

https://github.com/DivanteLtd/vue-storefront-api/blob/0acfc471534c9f0abeaf5c263719e08118a96dcc/src/api/sync.js#L16

**Comment by MikeSheward** [comment]
@pkarw thanks for them links, i'll take a look.

**Comment by 2monkey** [comment]
@MikeSheward hey :) how far are you with this extension?

**Comment by MikeSheward** [comment]
Hey, it's currently very WIP. I've made some changes to the core to allow for adding dynamic payment provider sections to be added to the checkout, a few new events ect, which should make it easier for other payment providers to use too, i'll try and get something to show by the end of today.

**Comment by pkarw** [comment]
Great! Please send us some PR with the changes as I'm concerning how should we implement Paypal integration right now :)

**Comment by pkarw** [comment]
@MikeSheward maybe this new feature will be usefull for you guys: https://github.com/DivanteLtd/vue-storefront/blob/master/doc/components/Extending%20UI%20from%20extensions.md

I've added it with Paypal integration on mind :)

**Comment by MikeSheward** [comment]
Thanks, this is useful - To be uniform across extensions, I will refactor the Stripe to adhere to this doc instead, previously i was using the Dynamic Components method from the Vue docs, but this will also work just as well.

**Comment by pkarw** [comment]
@2monkey are on this?

**Comment by pkarw** [comment]
Regarding payments - please take a look at:

#822 - any payment extension should be compliant with this "new stanard" - it will be merged in within few days but please treat it as already merged :)
and the: https://github.com/DivanteLtd/vue-storefront/blob/master/doc/components/Extending%20UI%20from%20extensions.md

**Comment by 2monkey** [comment]
Okey, good to know.

**Comment by filrak** [comment]
It's ntoa ssigned to anyone so I will take care of this ;)
