### ISSUE TITLE
Bootstrap Vue import config

### ISSUE THREAD

**Issue by MarcosMdo** [DivanteLtd/vue-storefront#869]
Has anyone imported  BootstrapVue in with vue storefront? Curious as to how you went around doing so with how storefront is set up.

Thanks

**Comment by filrak** [comment]
I dont see any potentat problems. What do you mean by 'how storefront is set up'?

**Comment by shubham0503** [comment]
Hello filrak,
I have installed Bootstrap-vue in vue storefront only without any other steps, and after installing while rendering the page I am getting the bootstrap components in vendor.js but while using the bootstrap class the design is still same not using the bootstrap class, as of now I am using theme-starter. Please suggest me is there any further steps to use of it.
