### ISSUE TITLE
Design Select country and language pop-up

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#881]
We need to design a pop-up where Customer could select country and language (in case there are multiple languages in a specific country). Let's use an existing style guide to design this component.

**Comment by pkarw** [comment]
Related to #455

**Comment by lorenaramonda** [comment]
Hi @pkarw I would like to try to do this, the only thing that leaves me hesitant is the mentioned style guide. You mean that there are out there style guides that tells you how to make a language switcher popup? 😁For instance, a dropdown language list rather than a modal with form fields to set the settings?
Maybe we can make it as a modal in which user can set language country and in case currency?

**Comment by lorenaramonda** [comment]
Ah, ok, uhm, i found this:
<img width="625" alt="switch-country" src="https://user-images.githubusercontent.com/4409084/39617265-52cf67cc-4f7f-11e8-9471-7f93f804b7b3.png">
so it must be this way? 😁

**Comment by pkarw** [comment]
Corect

**Comment by lorenaramonda** [comment]
great! i'll try although i surely would have doubts on something so probably I would ask lots of questions 😁 ✌️

**Comment by lorenaramonda** [comment]
ah one other thing, the modal should be open by click on united states in the footer?

**Comment by pkarw** [comment]
Yes :) we have to figure out how to support the multi site installation - but it’s a topic for different discussion:)

**Comment by lorenaramonda** [comment]
@pkarw can u please assign me this? 😁

**Comment by pkarw** [comment]
Hi Lorena

Are You Working on the popul as well?
I’ve put my research for Multiwebsite in here:
https://github.com/DivanteLtd/vue-storefront/issues/1135
https://github.com/DivanteLtd/vue-storefront/issues/1134

Please check the comments / there is a config file example that can be used in the pop up to list the available stores.
This is the specification on how multiwebsite will be implemented

It will be additionally switching the current i18n Lang regarding the shop setting so the local culture names like the example with “United States” should be solved via i18n (translation in the Italian CSV in this case)

Does it make sense?

**Comment by pkarw** [comment]
Done in the https://github.com/pkarw/vue-storefront/commits/feature/1135_multistore

**Comment by lorenaramonda** [comment]
I need to know which are the color codes for countries and languages links in this modal because from the jpg it's hard to know, they seems to be grey but I'm not sure, maybe @StasiekDivante could help me? 😁

**Comment by lorenaramonda** [comment]
and @pkarw does your implementation provides more than one language per country?

**Comment by lorenaramonda** [comment]
Hi @pkarw I did a little refactoring, added some style and divided the list in two column when storeviews enabled are more than a minim number (by default 3 + 1 - the current country).
But this function still needs to be completed: https://github.com/bitbull-team/vue-storefront/blob/59e853a1f275c4aad06a372b3cb2021fa1034d8d/src/themes/default/components/core/blocks/Switcher/Language.vue#L45

Here are two screenshots of the two cases:
<img width="1492" alt="Modal with two columns" src="https://user-images.githubusercontent.com/4409084/40589695-46d88be4-61f2-11e8-8199-256e5cca2d03.png">
<img width="1445" alt="Modal with one column" src="https://user-images.githubusercontent.com/4409084/40589697-597b7a40-61f2-11e8-833f-f442a6d9c184.png">
