### ISSUE TITLE
Guest order with associated account

### ISSUE THREAD

**Issue by AurelienLavorel** [DivanteLtd/vue-storefront#884]
![before](https://user-images.githubusercontent.com/5844661/37564996-47088aca-2aa1-11e8-9d66-2a0fea6aa9cf.png)

If I already have an account and I forgot to log in, in **personal data** checkout step, I can continue checkout.

We should have a no blocking validation message, for example: You already have an account, please login to see your complete order list

![login-warning](https://user-images.githubusercontent.com/5844661/37565049-1bfea4e4-2aa2-11e8-936b-228230fe30f0.png)

If you agree with that, I'll make that changes.

**Comment by pkarw** [comment]
You mean that we should check if the e-mail exists in the database in the background right? I'm not sure if this is not a security breach (this kind of service may be used for scanning the e-mail addresses against Magento customer database). On the other hand probably this is not a high risk and we can have it as an option configured in the config. Good point

**Comment by pkarw** [comment]
I belive that we need to create a special API method within the `vue-storefront-api` just getting the email address on the input and returning true/false whatever account exists

**Comment by filrak** [comment]
@pkarw such service could also use a register page so i think its not a security issue
