### ISSUE TITLE
Developer's experience feedback

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#886]
Hi All! 

As our community is growing rapidly we're getting more and more feedback from developers. We would like to put it simply: Best possible developer's experience is one of our key goals!

This is the reason we decided to create three Release Candidate's versions: RC -> RC2 -> RC3 -> 1.0 Final. 

From the 1.0RC we try to not change any key application parts that can break Extensions or Themes, VS is production ready any many Folks are doing some implementations over the world. This is great. We'll try to not mess things out :)

What we'll try to do is we'll try to improve developer's experience by:
- adding some additional events,
- refactoring internal classes and methods,
- decomposing some monolithic components by divide and conquer rule,
- make extension development more seamless.

**This ticket is for You to give us your feedback. What should we improve at first hand? Please note all your ideas right in here and we'll take care of them!**

**Comment by nuovecode** [comment]
I'm just jotting down a few ideas to start a discussion.

- I would really like a strong deploy strategy for a VS project. We discussed a bit on slack but I'd like to deepen. In development you can fork the project and then develop the theme inside it. Correct? but I'd like not to keep all the core under version control, I'd like to have in the repo of my project just a configuration file (and maybe the theme). This is to reinforce concept of the separation between the core and the project-custom stuff. 

- In general I prefer a mobile first approach for the style. Being a PWA I imagined that it would be a natural choice. What do you think?

- I'd like more separation between presentation components and logic components. For example the component SidebarMenu contains both the list of categories and the open/closed states of the sidebar. The developer is pushed to construct the whole menu within that component (in fact it was done in the default theme) while it would be preferable to have a dummy component for the sidebar and a different one for the list of categories and subcategories that could also be used elsewhere.

eehm.. for now enough. I really love this project
