### ISSUE TITLE
Move all data fetches from components to pages. (dumb/smart components)

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#888]
All core components that are grouped in pages (this excludes root components like microcart or overlay) should be dumb components which means they should only display data passed by the props. The data fetching from Vuex stores should take place in pages ONLY. The pages and global components should be the only smart  components.

(You can read more about this principle [here](https://coryrylan.com/blog/angular-design-patterns-feature-and-presentation-components) )

**Comment by pkarw** [comment]
It should be possible to make Smart Components -> Web Components; so for example "smart" Producft component should have been provided with "<Product sku="SKU" />" to get the data and display the proper product. By doing such decomposition we would be able to offer the Smart Components even to other frameworks by being compilant with WebComponents standard (for example)

**Comment by filrak** [comment]
I disagree. For me only route components (pages) and root components (the ones that are in App.vue) should handle the vuex data. It would be much easier to compose pages and dubug them with this approach. @igloczek what do you think?

**Comment by pkarw** [comment]
To be discussed :)

**Comment by pkarw** [comment]
Good example is a Headless CMS integration: https://github.com/DivanteLtd/vue-storefront/issues/804

I imagine the integration as a Core component like `<CmsBlock path="headless cms identifier" />`. When embeded it get's via Headless CMS api the JSON object to be displayed.

Then as a theme developer you create your own component like BlogPost.vue which has "CmsBlock" as a mixin. In your component you use specific JSON properties from Headless CMS  like "title" and "content".

BUT the core component is in charge of getting the data object from CMS, no matter the format and purpose is.

This is how I understand the Smart Component. What's wrong with this? :)

**Comment by filrak** [comment]
I think Such integration should be am extension in a first place

**Comment by filrak** [comment]
This case is different than what the task is about. This task is about vs core and the data mess here. I agree the data from 3rd partys should be handled differently and case by case

**Comment by pkarw** [comment]
OK :) I belive that we need a short discussion,  2-3 beers and we ahieve a consensus here ;)

**Comment by filrak** [comment]
...or kill each other ;)

**Comment by Igloczek** [comment]
I have no opinion on this topic yet, but I'll drop some article that may help to choose the right way.

https://hackernoon.com/architecting-single-page-applications-b842ea633c2e

BTW. I would not consider any kind of refactoring as a "good first issue".
