### ISSUE TITLE
Add all required install steps to Travis

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#892]
http://elliot.land/post/using-docker-compose-on-travis-ci

Its the core/scripts/installer.js procedure but not in interactive mode to be copied here. Doing so we will be able to run some HTTP tests to check if there are no critical runtime errors to the core after each build

**Comment by pkarw** [comment]
The installer script probably just need to have an —silent mode to install the app using defaults

**Comment by marlass** [comment]
I can work on that issue.
