### ISSUE TITLE
External checkout extension

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#895]
Allow to use external checkout (eg from Magento) in VS

**Comment by pkarw** [comment]
http://demo-magento2.vuestorefront.io/vue/cart/sync/token/s7nirf24cxro7qx1hb9uujaq4jx97nvp/cart/3648

and then check the: 

http://demo-magento2.vuestorefront.io/checkout/cart/

**Comment by pkarw** [comment]
General endpoint URL is: http://demo-magento2.vuestorefront.io/vue/cart/sync/token/{userToken}/cart/{cartId}

**Comment by filrak** [comment]
The frontend ext is coming ;)

**Comment by pkarw** [comment]
https://github.com/filrak/vsf-external-checkout
+ 
https://github.com/DivanteLtd/magento2-external-checkout

DEMO: https://demo-magento-checkout.vuestorefront.io/
