### ISSUE TITLE
Add 'proceed to checkout' action in 'Add to cart' notification

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#897]
Such an action would be a great UX improvement
![image](https://user-images.githubusercontent.com/15185752/37651875-e3794a86-2c39-11e8-9d9f-357e4e9f8b2f.png)

**Comment by pkarw** [comment]
We need extend the `notification` message for the `action2` I belive:

```
          this.$bus.$emit('notification', {
            type: 'error',
            message: i18n.t(result.result),
            action1: { label: 'OK', action: 'close' }
          })

```

**Comment by Januszpl** [comment]
Working on it
