### ISSUE TITLE
How do we plan to support promo-rules and special prices

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#9]
I believe we can get special_price from M2API - and it's the result of catalog promotion rules applied; but what to do with cart rules? It seems we need to send out each cart to Magento and calculate the prices there which does make no sense as we're trying to be platform agnostic :D

**Comment by pkarw** [comment]
https://github.com/DivanteLtd/vue-storefront/wiki/UX-User-Stories-for-offline - it's the place to collect all this kind of information

**Comment by filrak** [comment]
I'm not familiar with M2 API and how cart rules works but I assume there are no endpoints to get ones (and I couldn't find it here http://devdocs.magento.com/guides/v2.0/rest/list.html, only some 3rd party solutions like https://github.com/bangerkuwranger/Magento-2-Coupon-Code-API).

I don't know how many types of cart rules are over there in M2 but maybe we need some restrictions for this types or add cart rules via  vue-storefront admin panel (like static pages) which seems like the easiest solution but adds another layer of config ;/

**Comment by pkarw** [comment]
Of course we can synchronize coupon codes - and yes it's the simplest and quite powerfull solution

**Comment by pkarw** [comment]
Then we can create a proxy web method - cart and user data given at the input and calculated cart on the other end. Doing so we can calculate the prices online regarding all the promo rules you can have, no matter which backend is in use. Of course will work only while online which I think is not such big deal
