### ISSUE TITLE
Create order placement test

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#904]
The test should simulate filling the checkout form and proceeding to "place order". It should also check if the request was correctly sent to vue-storefront-api without any errors like wrong schema format etc.

**Comment by pkarw** [comment]
This should be E2E test - and the first step is: https://github.com/DivanteLtd/vue-storefront/issues/892

It's funny - we discussed it Today with @bobbyshaw  :)

**Comment by pkarw** [comment]
This is done!
