### ISSUE TITLE
npm run installer is not working

### ISSUE THREAD

**Issue by HemanthkumarHJ** [DivanteLtd/vue-storefront#908]
I am using ubuntu server16.x. 

git clone https://github.com/DivanteLtd/vue-storefront-api.git vue-storefront-api
cd vue-storefront-api
npm install

above 3 commands are worked properly, but last one "npm run installer" giving some error like below
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-storefront@1.0.0_RC installer: 'node ./core/scripts/installer'
npm ERR! Exit status 1
npm ERR! Failed at the vue-storefront@1.0.0-RC installer script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!  /home/ubu/.npm/_logs/2018-03-23T10_24_50_555z-debug.log

**Comment by pkarw** [comment]
It's hard to say, we need some more info. Please attach the full log of the installer. It's not clear from your description but of course you're running the `npm run installer` inside `vue-storefront` directory right?

Which branch are you using (develop or master)?

**Comment by pkarw** [comment]
I've just tested it on Debian server (https://demo-magento-checkout.vuestorefront.io/) and seems to work;

I've got the following versions of tools:
```
npm -v
5.3.0
yarn -v
1.5.1
node -v
v8.5.0
```

**Comment by HemanthkumarHJ** [comment]
yes, i am running the `npm run installer` inside `vue-storefront` directory. I am using develop branch.

**Comment by pkarw** [comment]
Please check if You have docker-compose installed - https://docs.docker.com/compose/install/

**Comment by arijit-codilar** [comment]
I have got the same issue and I have docker compose installed
