### ISSUE TITLE
The whole dark-gray area should be "clickable" - now only the label +3/4px is which is confusing

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#91]
<img width="650" alt="zrzut ekranu 2017-10-11 19 19 37" src="https://user-images.githubusercontent.com/211899/31455840-3293bc90-aeb9-11e7-8e85-27b4b0034941.png">

**Comment by patrykpiston** [comment]
I'll handle this one and the filter z-indexes quickly before starting the
rest of my issues tomorrow :)
