### ISSUE TITLE
the vue-storefront can use one page checkout instead of default checkout？

### ISSUE THREAD

**Issue by benyang2015** [DivanteLtd/vue-storefront#911]

**Comment by pkarw** [comment]
As far as I know there is no module for it; but to be honest - our checkout is very close to One page checkout :)

**Comment by filrak** [comment]
The checkout will be rewritten soon to allow more flexibility. Also - you can do one page checkout with this checkout too. You just need to send all section events at the end and voila ;)

**Comment by benyang2015** [comment]
@filrak the next version(RC2) will release about rewritten checkout?

**Comment by filrak** [comment]
Not yet, i'd say rc3

**Comment by filrak** [comment]
But i can't guarantee
