### ISSUE TITLE
Fix checkout form in mobile

### ISSUE THREAD

**Issue by noindie** [DivanteLtd/vue-storefront#912]
I suggest you to fix this behaviour in mobile form: when you forget to fill in a field and click on the button to proceed there usually is a javascript that brings you back to the "incomplete" field that is required.

![vuestorefronycheckout](https://user-images.githubusercontent.com/10724669/37865738-378d1c0c-2f81-11e8-96ed-69f08b5884e9.png)

ciao

**Comment by bobbyshaw** [comment]
I've started work on this if you wish to assign to me.

**Comment by ElijahKotyluk** [comment]
Is this issue available?
