### ISSUE TITLE
Move core to separate npm module

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#918]
Gentleman, I think it should be the cornerstone task for the RC3; We need to have a plan here. This task is very important for two reasons:
- first, to make vue-storefront very easy to be updated
- second, to make the git-repo management more streamlined.

Right now the best way to work on your custom implementation is to do the fork or another kind of copy of the main repo + then git pull our origins to get the updates. Ok, not too bad, but still could be improved

Could you think of it and create some roadmap for this issue?

**Comment by filrak** [comment]
IMO We should keep this project with for development of core and default theme but we should also create a template (separate repo) for creating VS stores.

**Comment by pkarw** [comment]
I'm closing this one as it seems to makes no sense at this point
