### ISSUE TITLE
giving error while installing vue-storefornt

### ISSUE THREAD

**Issue by ganeshr28** [DivanteLtd/vue-storefront#944]
@pkarw 
while installing i am getting error 
![screenshot from 2018-03-29 13-36-06](https://user-images.githubusercontent.com/32222445/38077309-2e887f60-3356-11e8-9e89-bda89e0639bf.png)

**Comment by pkarw** [comment]
Hello please try again with the latest version pulled from the git; I've fixed one installer related issue and it works for me on Debian Linux

If the problem occurs, please go to `vue-storefront` directory and execute the sequence of:

`yarn install
yarn build`

Then please provide us with the console output of these commands

**Comment by pkarw** [comment]
Is it any better after the changes? Can we close this one?
