### ISSUE TITLE
No breadcrumbs and different font size on mobile

### ISSUE THREAD

**Issue by StasiekDivante** [DivanteLtd/vue-storefront#953]
right now there is no bredcrumbs on mobile:

<img width="503" alt="screen shot 2018-03-30 at 11 45 57" src="https://user-images.githubusercontent.com/37068687/38133564-099d85fa-3410-11e8-8a8c-c1e23cf9f315.png">

also header should be a little bit bigger (36px instead of 24px)

<img width="359" alt="screen shot 2018-03-30 at 11 42 29" src="https://user-images.githubusercontent.com/37068687/38133588-2775a2ec-3410-11e8-9517-ba47acfb6adf.png">

**Comment by pkarw** [comment]
@jmikolajczyk the breadcrumb doesn't look good on the Product page / mobile version: https://www.dropbox.com/s/5kniaigkpaudc8o/Screenshot%202018-04-13%2021.33.17.png?dl=0

Also on static pages like /legal the font size hasn't been fixed to 36px

**Comment by pkarw** [comment]
Fine for me

**Comment by jmikolajczyk** [comment]
Also I fixed header font size on static page.
![header_static_page_mobile](https://user-images.githubusercontent.com/38243788/38801653-b96f6536-416a-11e8-91cc-062ac69fb5ac.png)
