### ISSUE TITLE
Spacing problem

### ISSUE THREAD

**Issue by StasiekDivante** [DivanteLtd/vue-storefront#954]
right now header have same margin on top and bottom

![screen shot 2018-03-30 at 11 47 55](https://user-images.githubusercontent.com/37068687/38133631-512aa268-3410-11e8-835d-5fff52ad19de.png)

Spacing should be 35px on top and 10px at the bottom on mobile

<img width="459" alt="screen shot 2018-03-30 at 11 48 05" src="https://user-images.githubusercontent.com/37068687/38133646-62e1beb0-3410-11e8-848b-13a930dd7f2c.png">

and 40px top 25px on bottom on desktop

<img width="708" alt="screen shot 2018-03-30 at 11 49 40" src="https://user-images.githubusercontent.com/37068687/38133670-79b0c212-3410-11e8-8cf6-11de0fa05643.png">

**Comment by bobbyshaw** [comment]
I don't have permission to. You may wish to assign this item to me.

**Comment by kacperknapik** [comment]
This task seems finished:

![image](https://user-images.githubusercontent.com/22354613/40233895-00fd19b8-5aa5-11e8-96a1-a416216d8540.png)
