### ISSUE TITLE
Capital button letters

### ISSUE THREAD

**Issue by StasiekDivante** [DivanteLtd/vue-storefront#955]
All buttons should have normal case letters instead all caps

![screen shot 2018-03-30 at 12 02 41](https://user-images.githubusercontent.com/37068687/38134278-8ea55e24-3412-11e8-8e9c-3f97977753b1.png)
![screen shot 2018-03-30 at 11 51 23](https://user-images.githubusercontent.com/37068687/38134279-8ec2baf0-3412-11e8-98c7-32ffa8f91c2d.png)

**Comment by lorenaramonda** [comment]
Hi @StasiekDivante that said, you mean removing all .uppercase class? Because I think it's that class that cause the uppercase

**Comment by karolbzik** [comment]
@lorenaramonda yes, we improved styling for all buttons, key changes are:

Desired state:
<img width="318" alt="zrzut ekranu 2018-03-31 o 22 31 32" src="https://user-images.githubusercontent.com/18116406/38167311-8861e952-3533-11e8-9bf9-0038e8374563.png">
<img width="256" alt="zrzut ekranu 2018-03-31 o 22 31 55" src="https://user-images.githubusercontent.com/18116406/38167312-8885f52c-3533-11e8-908d-243c6c119979.png">
<img width="338" alt="zrzut ekranu 2018-03-31 o 22 40 05" src="https://user-images.githubusercontent.com/18116406/38167374-7e7b847e-3534-11e8-84a4-99586b523d00.png">

Changes for all buttons in Slider/Banners, Footer (Subscribe to the newsletter), Product card, Shopping process; changes apply to desktop and mobile:
1. Removing uppercase in all buttons
2. Changing font for Roboto Regular 18px
3. Set a minimum width of the button for 250px

The only one exclusion from the rule is the contextual button on a category page, responsible for showing filters <img width="340" alt="zrzut ekranu 2018-03-31 o 22 37 25" src="https://user-images.githubusercontent.com/18116406/38167359-205d47d8-3534-11e8-87c3-b8d437d11f23.png">. This one should have height = 45px, font = Roboto, Regular, 14px and no requirement for a minimum width.

Could you help us in the unification of all buttons in the default theme?

**Comment by lorenaramonda** [comment]
Thank you @karolbzik, having a style guide is way much helpful, especially for those not on the project since the beginning. If these are all the info needed for this task, I would be happy to help you.
