### ISSUE TITLE
Slight color change

### ISSUE THREAD

**Issue by StasiekDivante** [DivanteLtd/vue-storefront#956]
Change all #333 colors to #4F4F4F

**Comment by lorenaramonda** [comment]
Hi @StasiekDivante just to be sure to operate in the right context, can you make an example in where it should changed, ie a button?
I see that #333 is set as value of the color variable of night-rider, if this color should not be present at all we could consider to remove it from variables list and replacing it where used with the proper color (#4f4f4f)
