### ISSUE TITLE
Improvements of the input labels in forms

### ISSUE THREAD

**Issue by StasiekDivante** [DivanteLtd/vue-storefront#958]
If input is in focus or have value in it upper label should be visible

<img width="618" alt="screen shot 2018-03-30 at 12 39 53" src="https://user-images.githubusercontent.com/37068687/38135266-8127ed52-3417-11e8-85b5-9910696df424.png">

right now there is no label at all

![screen shot 2018-03-30 at 12 37 51](https://user-images.githubusercontent.com/37068687/38135270-89c6634e-3417-11e8-9839-b19969415ceb.png)

**Comment by karolbzik** [comment]
We designed all forms based on Material Design guidelines - https://material.io/guidelines/components/text-fields.html, official documentation may be useful here.

**Comment by pkarw** [comment]
Tomek could you make this happen?:)
