### ISSUE TITLE
Adjustments in "My account dropdown" component

### ISSUE THREAD

**Issue by StasiekDivante** [DivanteLtd/vue-storefront#966]
<img width="289" alt="screen shot 2018-03-30 at 20 14 03" src="https://user-images.githubusercontent.com/37068687/38148506-187bf9b6-3457-11e8-919a-302fca560a05.png">

Dropdown redisn

<img width="183" alt="screen shot 2018-03-30 at 20 14 57" src="https://user-images.githubusercontent.com/37068687/38148527-27c32eee-3457-11e8-9774-15e09ff34c29.png">

- text should be aligned left 
- fonts should have different color and size
- there should be no 1px gap between button and menu
- spacing in dropdown itself should also be different
- there should be few more positions

**Comment by karolbzik** [comment]
I made some adjustments to make this dropdown:
<img width="311" alt="zrzut ekranu 2018-03-31 o 10 42 48" src="https://user-images.githubusercontent.com/18116406/38161507-77397784-34d0-11e8-9c2a-9bc19b42a270.png">

Important:
1. Heigh of a single row in the navigation = 40px
2. Shadow 10px 10% of visibility;
3. Mouseover - a different color for a row and font

The design is available in "My orders" view in https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront?node-id=4515%3A2459.

@StasiekDivante FYI

**Comment by qiqqq** [comment]
@pkarw I can do this improvement. You can assign this to me.

**Comment by pkarw** [comment]
Thanks!

**Comment by karolbzik** [comment]
@qiqqq great, thanks! Before closing this issue please assign it to me for testing.

**Comment by karolbzik** [comment]
@qiqqq there was a good suggestion from @StasiekDivante that we should add a margin 5px like this ![27](https://user-images.githubusercontent.com/18116406/38244385-c88b6e8c-373a-11e8-9a48-f602c3942b48.png)

@StasiekDivante thanks!

**Comment by pkarw** [comment]
It should appear in the dropdown menu as other links I belive

**Comment by qiqqq** [comment]
@karolbzik this is done on **feature/my-account-dropdown** branch in my repository. Let me know uf you test it, I will create pull request.

**Comment by pkarw** [comment]
Ready for tests: https://test.vuestorefront.io
