### ISSUE TITLE
Adjustments in the products slider component

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#967]
Current state:
![2](https://user-images.githubusercontent.com/18116406/38148468-f640250c-3456-11e8-99dc-4f57e567e002.png)

Desired state:
<img width="623" alt="zrzut ekranu 2018-03-30 o 20 15 15" src="https://user-images.githubusercontent.com/18116406/38148505-1749a70a-3457-11e8-8952-aceed28d85e6.png">

We need to improve products slider:
1. Currently, product boxes on slider contain name and price of the product, it doesn't look good if we don't have right photos of products (solo product like this one 
<img width="373" alt="zrzut ekranu 2018-03-30 o 20 08 41" src="https://user-images.githubusercontent.com/18116406/38148303-2ccdf1f4-3456-11e8-899c-9fecf46d7cb2.png">)
 => to make this feature look better let's remove product's name and price from the slider 
![1](https://user-images.githubusercontent.com/18116406/38148435-cffd73d6-3456-11e8-8117-8d4d7d19efdd.png)

2. Let's remove margin/padding and make the slider with the heigh of the image from the product box; ![1](https://user-images.githubusercontent.com/18116406/38148435-cffd73d6-3456-11e8-8117-8d4d7d19efdd.png)

3. Lets add a gradient on the left and right 
![3](https://user-images.githubusercontent.com/18116406/38148676-c22b4cfa-3457-11e8-96ae-f57ec6436ccd.png)

4. Now product boxes don't stick to the grid, there's different spacing between product boxes in products slider and in the other areas of the theme 
![4](https://user-images.githubusercontent.com/18116406/38148857-74405408-3458-11e8-83c6-f7db2d90bbb3.png) => let's apply the same grid for the products slider, so all product boxes presented in the theme stick to the same grid 
![5](https://user-images.githubusercontent.com/18116406/38148960-eebedbf0-3458-11e8-993e-4748402b9544.png)

5. Products slider can't work properly while resizing eg. here's how it looks after resizing to a mobile screen 
<img width="463" alt="zrzut ekranu 2018-03-30 o 20 31 57" src="https://user-images.githubusercontent.com/18116406/38149075-6ddb602a-3459-11e8-85f4-7413cd7a8f1c.png">
=> we need to apply the same grid for the products slider so it could work well while resizing 
<img width="201" alt="zrzut ekranu 2018-03-30 o 20 32 44" src="https://user-images.githubusercontent.com/18116406/38149109-896f2916-3459-11e8-9092-15542cc507ba.png">
<img width="642" alt="zrzut ekranu 2018-03-30 o 20 32 28" src="https://user-images.githubusercontent.com/18116406/38149110-899633f8-3459-11e8-808b-05d2f7db3203.png">

**Comment by karolbzik** [comment]
After making these changes from this issue - please assign this issue to me so I could verify the changes and make sure that everything is working well.

**Comment by filrak** [comment]
I don't agree with some of the desired changes. I'll discuss it with @karolbzik and then change accordingly ;)

**Comment by qiqqq** [comment]
@karolbzik can you check these changes on test environment and tell me, can I close this task?
