### ISSUE TITLE
Adjustments on "Search sidebar widget" component

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#971]
Current state:
<img width="876" alt="zrzut ekranu 2018-03-31 o 14 27 53" src="https://user-images.githubusercontent.com/18116406/38163168-c85b079e-34ef-11e8-9643-2981bfddf601.png">
<img width="935" alt="zrzut ekranu 2018-03-31 o 14 27 34" src="https://user-images.githubusercontent.com/18116406/38163170-c87d2f04-34ef-11e8-9240-94118cbfc0ec.png">
<img width="366" alt="zrzut ekranu 2018-03-31 o 14 27 18" src="https://user-images.githubusercontent.com/18116406/38163171-c89e6282-34ef-11e8-9f9a-c21224fc0396.png">

Desired state:
<img width="640" alt="zrzut ekranu 2018-03-31 o 14 29 29" src="https://user-images.githubusercontent.com/18116406/38163187-f4cba2d4-34ef-11e8-871e-23239fe1b2c7.png">
<img width="634" alt="zrzut ekranu 2018-03-31 o 14 29 21" src="https://user-images.githubusercontent.com/18116406/38163188-f4ed7850-34ef-11e8-82b2-469abea50ec8.png">
<img width="257" alt="zrzut ekranu 2018-03-31 o 14 29 09" src="https://user-images.githubusercontent.com/18116406/38163189-f50f8224-34ef-11e8-91f8-38dd80b9907a.png">
<img width="629" alt="zrzut ekranu 2018-03-31 o 14 28 52" src="https://user-images.githubusercontent.com/18116406/38163190-f531c0b4-34ef-11e8-8783-f06b2299df3a.png">

Adjustments:

1. We need to change a font, size and position of a search field, as a font we need to use Playfair Display 18px, the height of the search field should be 60px, the search field should be 60px height with 40px margin from left and right, search icon is the same as the one used in the top
![12](https://user-images.githubusercontent.com/18116406/38163228-dfa661cc-34f0-11e8-9e94-a91b7849a74e.png)

2. We should apply styles for an inactive stage of the field 
<img width="634" alt="zrzut ekranu 2018-03-31 o 14 29 21" src="https://user-images.githubusercontent.com/18116406/38163246-24b71fe0-34f1-11e8-9b2e-5b2635858e9c.png"> and different styles for active field
<img width="629" alt="zrzut ekranu 2018-03-31 o 14 28 52" src="https://user-images.githubusercontent.com/18116406/38163249-33300e24-34f1-11e8-98a9-ae6883244779.png">, changes are in color of fonts and color of the buttom line of the search field

3. Product boxes in the search sidebar widget should be presented with the same spacing as on the main grid, originally we have 30px gutter between columns in the grid on a desktop and 10px gutter on a mobile grid, 2 columns; 
![13](https://user-images.githubusercontent.com/18116406/38163288-07ff23ec-34f2-11e8-94b8-07e934425d0d.png), 
![14](https://user-images.githubusercontent.com/18116406/38163317-517e9b74-34f2-11e8-9f33-d7e427541577.png)

4. Product boxes should behave as with the grid, they should stick to the grid 
![15](https://user-images.githubusercontent.com/18116406/38163356-0303d94a-34f3-11e8-829b-4cdc97f7099f.png), 
![17](https://user-images.githubusercontent.com/18116406/38163439-6ec88f6c-34f4-11e8-9186-cc745ee91564.png)

5. We need to define a default height of a product box and product's photo should match this height ![16](https://user-images.githubusercontent.com/18116406/38163377-98f5fd0c-34f3-11e8-8a29-08b8ae8f2b2a.png)

**Comment by karolbzik** [comment]
Please assign me for testing after this issue will be done.

**Comment by szafran89** [comment]
I'll take care about this issue

**Comment by diboy2** [comment]
@pkarw Did anyone ever work on this issue? I'd like to work on it.

**Comment by pkarw** [comment]
@diboy2, cool it seems you’re good to go with this one as I haven’t seen any progress yet
