### ISSUE TITLE
Adjustments on "Order confirmation page"

### ISSUE THREAD

**Issue by karolbzik** [DivanteLtd/vue-storefront#972]
Order confirmation page = thank you page.

Current state:
<img width="397" alt="zrzut ekranu 2018-03-31 o 15 49 50" src="https://user-images.githubusercontent.com/18116406/38163871-5d00598e-34fb-11e8-983d-961f26bcddc1.png">
<img width="1227" alt="zrzut ekranu 2018-03-31 o 15 49 36" src="https://user-images.githubusercontent.com/18116406/38163873-5d22fbec-34fb-11e8-9c0b-6c97b89a698a.png">

Desired state (views with a grid):
<img width="167" alt="zrzut ekranu 2018-03-31 o 15 51 47" src="https://user-images.githubusercontent.com/18116406/38163881-71b556d6-34fb-11e8-8963-eaa2ebd43e39.png">
<img width="596" alt="zrzut ekranu 2018-03-31 o 15 51 39" src="https://user-images.githubusercontent.com/18116406/38163882-71d6bf4c-34fb-11e8-8151-856daefa55c9.png">

Important things:
1. Headlines are different on the desktop and mobile 
![18](https://user-images.githubusercontent.com/18116406/38163916-050d2288-34fc-11e8-97e7-946a7a754c22.png), 
![19](https://user-images.githubusercontent.com/18116406/38164849-02d0f634-350b-11e8-9a25-0ff7105c2f9a.png)

2. There's the Feedback widget with a text form, styles of this component should stick to the material design https://material.io/guidelines/components/text-fields.html#text-fields-layout

All designs available in Figma https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront?node-id=4783%3A0 , views under the names "Confirmation page" and "Confirmation page on mobile".

**Comment by bartdominiak** [comment]
can I take this one?

**Comment by pkarw** [comment]
Sure, go on!
