### ISSUE TITLE
Fix the PWA manifest regarding iOS limitations

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#973]
https://medium.com/@firt/progressive-web-apps-on-ios-are-here-d00430dee3a7?source=linkShare-40e7fcac2098-1522520805

1. The icon - shouldn’t require transparent background (not supported on iOS)
2. App Top Bar - now it’s transparent and totally not usable
3. Is there a way to fix the Splash screen?

**Comment by pkarw** [comment]
The topbar need to be fixed on android as well. It's kind of orange :) should be white

**Comment by collymore** [comment]
Assign this to me and I'll fix this. 
There are also a few basic fixes from Lighthouse testing I'll look at

<img width="781" alt="screen shot 2018-04-08 at 21 55 38" src="https://user-images.githubusercontent.com/55946/38472421-b7a24b40-3b77-11e8-925b-c15362555a05.png">

**Comment by pkarw** [comment]
Thanks Luke!

**Comment by pkarw** [comment]
https://www.netguru.co/codestories/few-tips-that-will-make-your-pwa-on-ios-feel-like-native
