### ISSUE TITLE
Separate Vuex stores as npm module

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#976]
Related to #918

I think it would be great to have the whole data api (aka vuex stores :)) in separate npm module. By refactoring the project to such form we'll allow developers to play wth the eCommerce data models and Magento (vue-storefront-api) integration in their own projects - no matter if based on Vue.js or React ...

This potentially is great value because around 50% of time spent on the project (regarding Toggl.com reports) is for data management  (the rest is UI).

I think that the next step could creating kind of web-components set - which will  use this data management api to allow users to embed eCommerce components like "Add to Cart" or "Product listing" inside their own apps.

@filrak @Igloczek would be great to hear your opinion on this

**Comment by pkarw** [comment]
TODO:
[ ] Move the 'theme/store' dependency out of the 'store/index.js' to avoid the circular references
[ ] Move 'core/lib/storage' to 'core/store/lib/storage' - this module is used ONLY by Vuex stores
[ ] Add localForage dependency to package.json
[ ] Move the 'core/lib/search' to 'core/store/lib/search' - this module is used ONLY by Vuex stores
[ ] Add bodybuilder dependency to package.json
[ ] Move 'core/lib/entities' to 'core/store/lib/entities' - this module is used ONLY by Vuex stores
[ ] Add dependency to 'config' node package - user will need to have ES configs in the config files managed by config module
[ ] Remove dependency of 'core/lib/i18n' - maybe by exposing some translation resources that wll be externally populated by the VS core?
[ ] Remove direct dependency of 'import EventBus from 'core/plugins/event-bus' by: adding event bus to store and creating an webpack alias in VS OR by adding the possibility to inject external EventBus (by default we can have a copy of EventBus helper here - like the default EventBus)
[ ] Add package.json dependency of 'object-hash'
[ ] Add package.json dependency of 'lodash'
[ ] Copy import { htmlDecode } from 'core/filters' to 'core/store/lib/filters'
[ ] Add package.json dependency of 'ajv'
[ ] Move import { breadCrumbRoutes } from 'core/helpers' to 'core/store/helpers' (the helper is used on Category.vue + Vuex only)
[ ] Move import { optionLabel } from 'core/store/modules/attribute/helpers' to local helpers - module used only in Vuex + Category.vue
[ ] Remove dependency of import shippingtMethods from 'core/resource/shipping_methods.json' - by external setup for 'shipping' module
[ ] Move import { execute as taskExecute } from 'core/lib/task' to core/store/lib/task - dependency of Vuex stores + client_entry.js
[ ] Move import { ValidationError } from 'core/lib/exceptions' to 'core/store/lib/exceptions'

**Comment by Igloczek** [comment]
Store is now available on npm - https://www.npmjs.com/package/@vue-storefront/store
