### ISSUE TITLE
VS integration with Nuxt

### ISSUE THREAD

**Issue by alexjoverm** [DivanteLtd/vue-storefront#979]
Hi there! Loving vue-storefront, I find it very well done and in my company we're deciding whether to use it for the next online store project.

The thing is, we wanted to use Nuxt and have full SSR support, so some questions arise:

 - Is it possible to integrate VS with Nuxt? Any guidance and examples to do that?
 - How's the SSR support so far? I've found some issues such as #138 #165 but it's not clear for me how well supported SSR is, specially for SEO purposes. Is there any doc or further info to look upon?

Thanks beforehand!

**Comment by filrak** [comment]
VS SSR support out of the box works very well so you don't need nuxt ;) We are supporting it fully for SEO purposes and rendering speed.
