### ISSUE TITLE
Rename API urls /api/changePassword and /api/resetPassword

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#981]
... accordingly to: /api/change-password and /api/reset-password

**Comment by ekoeditaa** [comment]
Looks like I may be able to help. Can you help advise me on where to start?

**Comment by pkarw** [comment]
You should start with vue-storefront-api changing the api routing the. For the backward compatibility we should keep the old endpoint names along with the new fixed ones. Then you need to modify the vue-storefront/config/default.json to point to the new endpoints and to a find in files to double check if there are no other references to it

**Comment by ekoeditaa** [comment]
What are the API names supposed to be changed to? Which file(s) should I modify first for the global setting?

**Comment by nahuelsanchez** [comment]
Hello there, I'll give it a try. :)

**Comment by pkarw** [comment]
Go for it!

**Comment by nahuelsanchez** [comment]
I created two PR for this, one for the vue-storefront repo and the other one for vue-storefront-api. I'm attaching both direct links.

- https://github.com/DivanteLtd/vue-storefront/pull/1519
- https://github.com/DivanteLtd/vue-storefront-api/pull/79

:)

**Comment by pkarw** [comment]
Thanks! works just fine, merged in :)
