### ISSUE TITLE
Fix the order-history to display the most recent orders

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#982]
https://www.dropbox.com/s/7mh03k5o7no3kg6/Screenshot%202018-04-04%2005.08.55.png?dl=0

Requires some tweaks to `/user/order-history` api endpoint

**Comment by makiten** [comment]
Does the API call only come from Magento?
If so, would the fix be in `vue-storefront-api`, since `src/platform/magento2/magento2-rest-client/lib/customers.js` is where the API call happens?

**Comment by qiqqq** [comment]
Yes, this is done
