### ISSUE TITLE
Installation issue - Can't restore data for ElasticSearch.

### ISSUE THREAD

**Issue by jasonmarysael** [DivanteLtd/vue-storefront#984]
When running the installation I face the following error:

![err1](https://user-images.githubusercontent.com/28600053/38326967-5de42d86-3847-11e8-8619-173c3ce86d86.png)

install.log:

![err2](https://user-images.githubusercontent.com/28600053/38327002-759fd2d6-3847-11e8-988e-63f99159e166.png)

Can anybody please tell me what I am doing wrong?

**Comment by pkarw** [comment]
Seems like Elastic Search isn't working; please take a look at this: https://github.com/DivanteLtd/vue-storefront/blob/master/doc/FAQ%20and%20Receipes.md#problem-docker-installer

Please check the output from `docker-compose up -d` in `vue-storefront-api` directory. Then make sure that ES is working properly by - for example running: `curl -i http://localhost:9200`

In the end if there is a permanent problem with docker, please do install ElasticSearch and Redis, on defaults locally (without docker)

**Comment by djpaoloc** [comment]
Try to install Elasticsearch + Redis 
`brew install elasticsearch`
`brew install redis` 
(if use OSX)
