### ISSUE TITLE
Make extensions theme specific

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#986]
Desired path for `src/extensions` is `src/{theme}/extensions`.

Right now we have one global place for extensions which is ok for developing single themes but doesn't work good with multiple themes since it requires all of them to support all extensions so they should be theme specific

**Comment by pkarw** [comment]
I think we should have support for both: global extensions and theme level extensions

**Comment by pkarw** [comment]
Done with https://github.com/pkarw/vue-storefront/commit/8911093e986fb41b931a7525eaa3e324e88e1218
