### ISSUE TITLE
UI for product Galery + Display subsequent simple product photos in gallery on configurable

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#99]

**Comment by karolbzik** [comment]
@pkarw please be more specific here

**Comment by pkarw** [comment]
For configurable products we do have separate pictures for each variant (for example blue tee or red one etc) - we can display the subsequent pictures in kind of gallery or slider

How it should look like?

We can also synchronize product media (more than 1 picture assigned to the product) - so basically we can asume we have product galleries

**Comment by Igloczek** [comment]
Maybe we can go with a simpler design without the typical gallery [like Nike did in their new store](https://econsultancy.com/blog/69844-why-nike-s-refreshed-product-pages-improve-cx-beat-adidas).

**Comment by pkarw** [comment]
@karolbzik I would love to implement media sync and close the gallery feature; are you willing to provide some designs?

**Comment by karolbzik** [comment]
@pkarw it's ready

Gallery on mobile, visible after clicking zoom icon / photo
<img width="360" alt="3 3 product card with zoomed photo on mobile" src="https://user-images.githubusercontent.com/18116406/38165462-f9bedd8c-3513-11e8-823f-6d42313b7bf8.png">

Gallery on desktop, visible after clicking zoom icon / photo
<img width="1440" alt="3 2 product card with zoomed photo" src="https://user-images.githubusercontent.com/18116406/38165448-d3c71a0e-3513-11e8-92ae-9b7fe396dbad.png">

Zoom button on mobile
<img width="360" alt="3 1 product card on mobile" src="https://user-images.githubusercontent.com/18116406/38165449-d3e972c0-3513-11e8-94d2-801f89ff2bb7.png">

Mouseover on product's photo on desktop
<img width="1440" alt="3 product card mouseover on image" src="https://user-images.githubusercontent.com/18116406/38165450-d40bb66e-3513-11e8-8f27-b04b88c4cb9b.png">

Product card with zoom icon
<img width="1440" alt="3 product card" src="https://user-images.githubusercontent.com/18116406/38165451-d430d76e-3513-11e8-8abf-c6e940c1465c.png">

**Comment by karolbzik** [comment]
All designs are available here - https://www.figma.com/file/VKyqbHFI55TKIKcQlFLiVpVF/Vue-Storefront under the names:
- Product card (including mouse over and mouse away the image)
- Product card on mobile
- Product card with zoomed photo
- Product card with zoomed photo on mobile

Important issues:
1. Distance between photos in zoomed photos view = 30px 
![20](https://user-images.githubusercontent.com/18116406/38166774-bde87eb0-3529-11e8-862e-3ef2b641e9e2.png)

2. Try to use existing components eg. closing icon can be the same as used in login pop-up, photos could be taken from product's box component

3. On product card, while browsing via desktop when a mouse is over the photo = we should show arrows, arrows are not shown when a mouse is away;

4. As a Customer I should be able to browse photos on mobile by swiping left/right 
![22](https://user-images.githubusercontent.com/18116406/38166828-e611d5ca-352a-11e8-9c3a-0b99ea9bc926.png)

5. Zoom photo icon should be positioned 20px from left and down of the photo 
![21](https://user-images.githubusercontent.com/18116406/38166802-6d256672-352a-11e8-9d40-ff0ae60fdfb8.png)

**Comment by karolbzik** [comment]
Assign me please to test this feature after it's done.

**Comment by pkarw** [comment]
@nuovecode I'm merging this in but there is just one bug with the zoom on mobile: https://www.dropbox.com/s/ii2b7tn8si5w6pw/Screenshot%202018-04-02%2016.19.17.png?dl=0
